### PR TITLE
feat(stepfunctions-tasks): additional IAM statements for AWS SDK service integration

### LINKED ISSUE #22006: (aws-stepfunctions-tasks): CallAwsService to allow custom iam policyStatement
### Describe the feature

[CallAwsService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.CallAwsService.html) attaches an IAM permission policy with single action to StepFunction Role.

### Use Case

I have Stepfunction that needs to call rekognition service to detect labels in S3 object.
This requires the step function IAM role to have 2 permissions: 

1. rekognition:detectLabels
2. s3:GetObject

Currently CallAwsService only adds `rekognition:detectLabels` and so the stepfunction execution fails

CDK snippet:
---

```ts
new tasks.CallAwsService(this, 'detectLabels',{
          service: 'rekognition',
          action: 'detectLabels',
          parameters: {
            Image: {
              S3Object: {
                Bucket: {bucketName},
                Name: {imageName}
              }
            }
        },
      iamResources:['*']
      })
```

### Proposed Solution

Possible Solutions:
1.  Allow user to manually pass 'PolicyStatement' in  CallAwsService. If present it will be used to create the role for StateFunction.
2. Depending on `service:action`, rekognition:detectLabels in this case, add additional service policy permissions.

### Other Information

Current work around is to manually grant the additional permissions after defining stepfunction.
Example:
`{S3Object}.grantRead({stepFunctionObject})`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2

### Environment details (OS name and version, etc.)

macOS

### PR DESCRIPTION
**Pull request by jogold**
Add a `additionalIamStatements` prop to pass additional IAM statements. To be used when the call requires more than a single statement to be executed.

Closes #22006

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@kaizencc

**Comment by Naumel** [comment]
Hello,

Thank you for taking the time and submitting a PR.

Pointing the obvious before starting to look at the change, from the linter:
`Error: Features must contain a change to an integration test file`

**Comment by jogold** [comment]
Hi @Naumel 

Given the changes here I would say this PR could have a `pr-linter/exempt-integ-test`...?

**Comment by TheRealAmazonKendra** [comment]
> Hi @Naumel
> 
> Given the changes here I would say this PR could have a `pr-linter/exempt-integ-test`...?

Can you provide more information about why you think this should be exempt from integ testing? We have recently increased our testing requirements and I am hesitant to provide exemptions except in the case where a convincing argument has been made.

I know you're a long time contributor (and one of our top, for that matter), so this may seem annoying, but we are implementing some new standards across the board to drive down our bug count as much as possible.

**Comment by jogold** [comment]
> Can you provide more information about why you think this should be exempt from integ testing? We have recently increased our testing requirements and I am hesitant to provide exemptions except in the case where a convincing argument has been made.

@TheRealAmazonKendra The change here adds statements to an IAM policy. This is shown in the unit test. Updating an integ test snapshot will show the same "diff" as the unit test. As for the "deployable" part we already know that an IAM policy can be deployed.

What are you trying to cover with an extra integ test? "Deployability" or hidden changes to the CF template? If it is the latter then "snapshoting" stacks (`expect(Template.fromStack(stack).toJSON()).toMatchSnapshot()`) in the unit tests would lead to the same results (but without having to rely on another testing framework)? I think that an integ test should mainly be used to check "deployability". I would say that the boundary between unit test and integ test is not clear.

Anyway, if you want me to add or update an integ test here, I will do it 🙂.

**Review by corymhall — APPROVED** [review]

**Pull request merged**
