### PR TITLE
feat(appsync): enhances and completes auth config

### PR DESCRIPTION
**Pull request by SachinShekhar**
### Commit Message
feat(appsync): enhances and completes auth config

- Enhances auth config system with strongly-typed interfaces.
- Adds support for `AWS_IAM` and `OPENID_CONNECT` authorization.
- Fixes issue with `API_KEY` default authorization which caused CDK to not create new API Key upon not finding `apiKeyDesc` (the intended behavior was creation of new API key when no auth config was present).

BREAKING CHANGE: Changes way of auth config even for existing supported methods viz., User Pools and API Key.
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by alextriaca** [comment]
This is an awesome feature! Would love to have this merged in to simplify a boat load of messy Cfn objects.

**Comment by p0wl** [comment]
yes, we would also like to see this merged! Awesome work!

**Comment by tyroneerasmus** [comment]
+1 to getting this merged!

**Comment by p0wl** [comment]
For those who are looking for a solution for now: you can use the cloudformation resource and add the openid authentication settings like this:

```
    const api = new appsync.GraphQLApi(this, "GAPI", {
      name: `GraphQL API`,
      logConfig: {
        fieldLogLevel: appsync.FieldLogLevel.ALL,
      },
      schemaDefinitionFile: "./resources/schema.graphql",
    });

    const cfnApi = api.node.defaultChild as appsync.CfnGraphQLApi;
    cfnApi.authenticationType = "OPENID_CONNECT";
    cfnApi.openIdConnectConfig = {
      issuer: process.env.AUTH0_ISSUER, // https://something.something.com
      authTtl: 0,
      iatTtl: 0,
      clientId: "your client id"
    };
```

**Pull request merged**
