### PR TITLE
feat: bump jsii from 0.21.2 to 0.22.0

### PR DESCRIPTION
**Pull request by NetaNir**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by skinny85** [comment]
One small comment: we usually do JSII bumps with `feat:`, as otherwise, JSII upgrades are not reflected in the ChangeLog, and they probably should (JSII can have bugs unrelated to the CDK, which might be mysterious otherwise).

**Comment by NetaNir** [comment]
> One small comment: we usually do JSII bumps with `feat:`, as otherwise, JSII upgrades are not reflected in the ChangeLog, and they probably should (JSII can have bugs unrelated to the CDK, which might be mysterious otherwise).

I'll add it manually to the change log?

**Comment by skinny85** [comment]
> > One small comment: we usually do JSII bumps with `feat:`, as otherwise, JSII upgrades are not reflected in the ChangeLog, and they probably should (JSII can have bugs unrelated to the CDK, which might be mysterious otherwise).
> 
> I'll add it manually to the change log?

You could, but why do something manually when you can automate it with a simple change 🙂

**Comment by NetaNir** [comment]
> > > One small comment: we usually do JSII bumps with `feat:`, as otherwise, JSII upgrades are not reflected in the ChangeLog, and they probably should (JSII can have bugs unrelated to the CDK, which might be mysterious otherwise).
> > 
> > 
> > I'll add it manually to the change log?
> 
> You could, but why do something manually when you can automate it with a simple change 🙂

I meant this time?

**Pull request merged**
