### PR TITLE
fix(lambda-nodejs): docker build container attempts to use unsupported pnpm version for node runtime

### LINKED ISSUE #25710: NodejsFunction: ERROR: This version of pnpm requires at least Node.js v14.6, The current version of Node.js is v12.22.12
### Describe the bug

I'm in the process of upgrading from an old version of CDK `1.x`, to the latest CDK `2.x` (`2.80.0`).

I had some old `NodejsFunction` code that was using `runtime: Runtime.NODEJS_12_X`

**Old code that caused error:**

```ts
this.fnHandler = new NodejsFunction(this, 'Handler', {
  description: handlerDescription,
  entry: path.join(__dirname, '..', 'functions', handlerPath),
  handler: handlerExport,
  runtime: Runtime.NODEJS_12_X,
  memorySize: 128,
  timeout: Duration.seconds(60),
})
```

### Expected Behavior

The framework would give me a more meaningful error message telling me what the issue was.

### Current Behavior

```shell
⇒ yarn cdk-dev diff '*'
yarn run v1.22.15
$ yarn -s awsvault-dev:nosession cdk diff '*'
$ /Users/devalias/dev/REDACTED-infrastructure/node_modules/.bin/ts-node bin/REDACTED.ts
[+] Building 19.8s (11/13)
 => [internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                            0.0s
 => [internal] load build definition from Dockerfile                                                                                                       0.0s
 => => transferring dockerfile: 1.30kB                                                                                                                     0.0s
 => [internal] load metadata for public.ecr.aws/sam/build-nodejs12.x:latest                                                                                2.1s
 => [ 1/10] FROM public.ecr.aws/sam/build-nodejs12.x@sha256:4748f3e85ef16460a48f502433eec0b8282f374bd646553392e7dc27a1c20579                               0.0s
 => CACHED [ 2/10] RUN npm install --global yarn@1.22.5                                                                                                    0.0s
 => [ 3/10] RUN npm install --global pnpm@7.30.5                                                                                                           4.2s
 => [ 4/10] RUN npm install --global typescript                                                                                                            3.7s
 => [ 5/10] RUN npm install --global --unsafe-perm=true esbuild@0                                                                                          8.3s
 => [ 6/10] RUN mkdir /tmp/npm-cache &&     chmod -R 777 /tmp/npm-cache &&     npm config --global set cache /tmp/npm-cache                                0.5s
 => [ 7/10] RUN mkdir /tmp/yarn-cache &&     chmod -R 777 /tmp/yarn-cache &&     yarn config set cache-folder /tmp/yarn-cache                              0.7s
 => ERROR [ 8/10] RUN mkdir /tmp/pnpm-cache &&     chmod -R 777 /tmp/pnpm-cache &&     pnpm config --global set store-dir /tmp/pnpm-cache                  0.3s
------
 > [ 8/10] RUN mkdir /tmp/pnpm-cache &&     chmod -R 777 /tmp/pnpm-cache &&     pnpm config --global set store-dir /tmp/pnpm-cache:
#0 0.282 ERROR: This version of pnpm requires at least Node.js v14.6
#0 0.282 The current version of Node.js is v12.22.12
#0 0.282 Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
------
Dockerfile:31
--------------------
  30 |     # Ensure all users can write to pnpm cache
  31 | >>> RUN mkdir /tmp/pnpm-cache && \
  32 | >>>     chmod -R 777 /tmp/pnpm-cache && \
  33 | >>>     pnpm config --global set store-dir /tmp/pnpm-cache
  34 |
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir /tmp/pnpm-cache &&     chmod -R 777 /tmp/pnpm-cache &&     pnpm config --global set store-dir /tmp/pnpm-cache" did not complete successfully: exit code: 1

/Users/devalias/dev/REDACTED-infrastructure/node_modules/aws-cdk-lib/core/lib/private/asset-staging.js:2
`).map((line,idx)=>`${idx===0?firstLine:padding}${line}`)};const reason=proc.signal!=null?`signal ${proc.signal}`:`status ${proc.status}`,command=[prog,...args.map(arg=>/[^a-z0-9_-]/i.test(arg)?JSON.stringify(arg):arg)].join(" ");throw new Error([`${prog} exited with ${reason}`,...prependLines("--> STDOUT:  ",proc.stdout)??[],...prependLines("--> STDERR:  ",proc.stderr)??[],`--> Command: ${command}`].join(`
                                                                                                                                                                                                                                            ^
Error: docker exited with status 1
--> Command: docker build -t cdk-56873b35ad5918ca4be680982cd873a337a6409face1e9609c1043d328c6fd66 --platform "linux/amd64" --build-arg "IMAGE=public.ecr.aws/sam/build-nodejs12.x" --build-arg "ESBUILD_VERSION=0" "/Users/devalias/dev/REDACTED-infrastructure/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib"
    at dockerExec (/Users/devalias/dev/REDACTED-infrastructure/node_modules/aws-cdk-lib/core/lib/private/asset-staging.js:2:237)
    at Function.fromBuild (/Users/devalias/dev/REDACTED-infrastructure/node_modules/aws-cdk-lib/core/lib/bundling.js:1:4085)
    at new Bundling (/Users/devalias/dev/REDACTED-infrastructure/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.js:1:2315)
    at Function.bundle (/Users/devalias/dev/REDACTED-infrastructure/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.js:1:599)
    at new NodejsFunction (/Users/devalias/dev/REDACTED-infrastructure/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.js:1:1310)
    at new CustomNodeLambdaEventHandler (/Users/devalias/dev/REDACTED-infrastructure/lib/constructs/CustomNodeLambdaEventHandler.ts:44:22)
    at new REDACTEDEventStack (/Users/devalias/dev/REDACTED-infrastructure/lib/REDACTED-event-stack.ts:100:43)
    at Object.<anonymous> (/Users/devalias/dev/REDACTED-infrastructure/bin/REDACTED.ts:46:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/devalias/dev/REDACTED-infrastructure/node_modules/ts-node/src/index.ts:837:23)
error Command failed with exit code 1.
```

### Reproduction Steps

See above

### Possible Solution

Throw a more useful error/warning at the CDK framework level that describes the issue, rather than it being surfaced through arbitrary warnings within a related docker build container.

**Workaround**

Manually figure out that the error relates to using `runtime: Runtime.NODEJS_12_X`, find it in your code, and update it to something supported such as `runtime: Runtime.NODEJS_14_X`

### Additional Information/Context

N/A

### CDK CLI Version

2.80.0 (build bbdb16a)

### Framework Version

2.80.0

### Node.js Version

v16.15.1

### OS

macOS Ventura 13.3.1

### Language

Typescript

### Language Version

_No response_

### Other information

N/A

### PR DESCRIPTION
**Pull request by 0xdevalias**
fixes #25710

In the process of upgrading from an old version of CDK `1.x`, to the latest CDK `2.x` (`2.80.0`), I had some old `NodejsFunction` code that was using `runtime: Runtime.NODEJS_12_X`

When running the CDK build, it used the Docker build container, which tried to use a version of `pnpm` that doesn't support running on Node `12.x`, producing the following error:

```
..snip..

 > [ 8/10] RUN mkdir /tmp/pnpm-cache &&     chmod -R 777 /tmp/pnpm-cache &&     pnpm config --global set store-dir /tmp/pnpm-cache:
#0 0.282 ERROR: This version of pnpm requires at least Node.js v14.6
#0 0.282 The current version of Node.js is v12.22.12
#0 0.282 Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.

..snip..
```

- https://r.pnpm.io/comp

This PR introduces the `PNPM_VERSION` `ARG` into the `Dockerfile` used for bundling (following existing CDK patterns used to inject the `ESBUILD_VERSION` `ARG`), which defines a `switch`/`case` of `pnpm` versions that should work with the corresponding `Runtime.NODEJS_*` versions.

You can see far more details of the error + working the proposed solution in:

- https://github.com/aws/aws-cdk/issues/25710

Previous PRs (potentially non-exhaustive) related to the `pnpm` version + runtime compatibility are:

- https://github.com/aws/aws-cdk/pull/24837
- https://github.com/aws/aws-cdk/pull/24821
- https://github.com/aws/aws-cdk/pull/14772

## TODO

- [ ] add/update any relevant unit and/or integration tests
  - see https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-3-work-your-magic
  - I theorise on what some useful tests might be that would have caught/prevented this in the following comment ([Ref](https://github.com/aws/aws-cdk/issues/25710#issuecomment-1562063323))

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by vinayak-kukreja** [comment]
Hey, is there a reason you want to run node 12?

**Comment by 0xdevalias** [comment]
> is there a reason you want to run node 12

@vinayak-kukreja Not overly, it was a bug/framework deficiency I noted as part of an upgrade/moernisation of a legacy stack.

But as was pointed out to me on the original issue I opened:

> The node 12 runtime option is marked as deprecated in CDK, but it's still a valid configuration for functions that were created on node 12, so we can't just throw an error if someone uses node 12. I'm not sure how we can throw a clear warning message in this exact case of container failure either, that could be pretty tricky. Thanks for letting us know this could be clearer
> 
> _Originally posted by @peterwoodworth in https://github.com/aws/aws-cdk/issues/25710#issuecomment-1561792615_
            
As I see it, the 2 paths forward are either fully deprecate/drop all support for Node `12.x`, which as noted above (if correct), isn't a viable path right now; or alternately, make a small change to the existing code that allows it to continue to work bug free (the approach I took here), until the point that it is deemed fully unsupported and dropped entirely.

**Comment by 0xdevalias** [comment]
Clarification Request

**Comment by vinayak-kukreja** [comment]
Hey, thank you for clarifying. It makes sense to me. 

For unit tests, you can take a look at tests in this [file](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts).

And, for integration tests, you can take a look at [DeployCommand](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.cloud_assembly_schema.DeployCommand.html#enabled) and create a synth only integ test since stack deployment with Node 12 would fail.

Let me know if you have any questions.

**Comment by 0xdevalias** [comment]
> Let me know if you have any questions.

@vinayak-kukreja I guess my main question RE: tests was around the nuances of my musings here:

>   - https://github.com/aws/aws-cdk/blob/v2.80.0/packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts#L81-L101
>     - Adding a test for Node `12.x` here might be a useful way to surface this error, and catch any future regressions. It'd probably be worth doing this for all versions that are considered 'supported'.
>     - Though I guess that test may not actually be running the build itself.. just testing that the right command is output.. so it might not be sufficient for this..
>   - https://github.com/aws/aws-cdk/blob/v2.80.0/packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts#L249-L258
>     - This test looks like it's actually running the bundle, and expecting an error to be thrown.. so perhaps similar could be done to run it within the docker container and expect no error to be thrown?
> 
> _Originally posted by @0xdevalias in https://github.com/aws/aws-cdk/issues/25710#issuecomment-1562063323_

As well as this part:

> I'd need to look deeper into those existing tests again to be sure of the best way to write one that would have identified this issue ahead of time + ensured it never broke in the first place though. Would seemingly have to be an actual run of the build container though, not just a mock.. so not sure how viable/desirable that is in the current test suite.
> 
> It would be good to get some guidance as to the best/most acceptable way to add some tests around this.
> 
> _Originally posted by @0xdevalias in https://github.com/aws/aws-cdk/issues/25731#issuecomment-1563631262_

@vinayak-kukreja Basically.. it feels like there is only sort of limited usefulness that I could get out of implementing unit tests with mocks/etc around this (eg. I could probably ensure that the version supplied is within the expected range for support I suppose, but it's still basically only testing the things I have already added in my code), whereas what feels like a 'proper' useful test would be to actually run the docker build itself, for each of the supported versions of Node, and then not see the failure anymore.

The clarity I was seeking (before I put the effort into writing those tests) is whether running a full proper docker build container for each supported version of node as part of these tests would be too 'heavy' to be accepted/acceptable.

Most of the existing tests within https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts are just checking that the appropriate function was called with the appropriate parameters (eg. [Ref](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts#L58-L78), which never would have surfaced the original error since the container wasn't actually being run.

For just checking that the params I define in the code get passed through appropriately for the given node version I could use a pattern like this one ([Ref](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts#L441-L459))

But re-skimming through https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts I don't see any examples where the docker build container is actually run, for us to then be able to see it error. For that part of it, is that where you were suggesting writing the integration tests with `DeployCommand`?

> And, for integration tests, you can take a look at [DeployCommand](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.cloud_assembly_schema.DeployCommand.html#enabled) and create a synth only integ test since stack deployment with Node 12 would fail.

If so, can you recommend any good examples of using `DeployCommand` for something similar to this? (I haven't actually searched the existing code myself to try and find any yet)

**Comment by 0xdevalias** [comment]
_sigh_ closed for lack of being able to add a couple of brief tests when the bulk of the work/fix is already done... what a waste.

**Pull request closed without merging**
