### PR TITLE
fix(elbv2): Use correct format for parsing imported target group ARNs

### PR DESCRIPTION
**Pull request by clareliguori**
Currently, the following CDK snippet results in outputting the target group ID, not the target group name.

```typescript
    const importedTgArn = cdk.Fn.importValue('ImportTargetGroupArn');
    const importedTg = elbv2.ApplicationTargetGroup.fromTargetGroupAttributes(stack, 'ImportedTg', {
      targetGroupArn: importedTgArn,
    });
    new cdk.CfnOutput(stack, 'TargetGroupOutput', {
      value: importedTg.targetGroupName,
    });
```

For example, for a sample target group ARN:
```
arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/MyTargetGroupName/6a58f7d61e2151d4
```
The stack above will output `6a58f7d61e2151d4` instead of the desired `MyTargetGroupName`.

This change fixes the ARN format used for parsing the imported ARN value.  It does not impact any existing CDK code passing a raw ARN string (as confirmed by existing unit tests), only CDK code trying to pass tokens such as import values.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
FYI - Ignore the PR Linter right now.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by corymhall — APPROVED** [review]

**Comment by corymhall** [comment]
@Mergifyio update

**Review by corymhall — APPROVED** [review]

**Comment by corymhall** [comment]
@Mergifyio update

**Pull request merged**
