### PR TITLE
feat(eks): support for Kubernetes version 1.24

### PR DESCRIPTION
**Pull request by robertd**
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-24/

image

Screen Shot 2022-11-16 at 1 39 22 PM

Right in time just before the ReInvent 😄 ✌️ 🚀 

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
@watany-dev You may want to redo #22939 once this PR lands.

**Comment by robertd** [comment]
@kaizencc & @madeline-k Please review this PR when you get a chance. 👍

**Review by madeline-k — APPROVED** [review]
Thanks, @robertd!

**Comment by kaizencc** [comment]
@Mergifyio refresh

**Comment by robertd** [comment]
`Queue: Embarked in merge train — This pull request cannot be embarked for merge` 

Ummm... not exactly sure what this means.

**Comment by robertd** [comment]
@madeline-k & @kaizencc 

I've merged the latest main into this PR. Please re-approve once build succeeds. Thanks in advance.

**Comment by robertd** [comment]
@Mergifyio refresh

**Review by kaizencc — APPROVED** [review]

**Pull request merged**
