### PR TITLE
feat(lambda-nodejs): add verbose and debug log level to esbuild bundling

### LINKED ISSUE #27634: aws-cdk-lib/aws-lambda-nodejs: add VERBOSE log level to esbuild bundling
### Describe the feature

The `NodejsFunction` constructs allows customers to bundle code using `esbuild`. The construct already has a `bundling.logLevel` property that allows to set the log level for the `esbuild` CLI.

Currently CDK exposes only some of the log levels (i.e. `INFO`, `ERROR`, `WARNING`, and `SILENT`), however `esbuild` [offers more](https://esbuild.github.io/api/#log-level), namely `VERBOSE`.

I propose to add the `VERBOSE` log level to the existing ones, so that CDK customers can use it to troubleshoot or inspect issues with the bundling process.

### Use Case

When bundling functions sometimes it's useful to see the full log output, this is especially helpful when debugging module resolution issues and to understand how a certain module ends up (or doesn't) in the final bundle.

For example, when enabled, the verbose output gives info similar to this (for each module resolved):
```log
⬥ [VERBOSE] Resolving import "@aws-lambda-powertools/commons" in directory "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/logger/lib/esm" of type "import-statement"

  Checking for package alias matches
    Failed to find any package alias matches
  Checking "@aws-lambda-powertools/commons" against the external pattern "@aws-sdk/*"
  Read 14 entries for directory "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/logger/lib/esm"
  Searching for "@aws-lambda-powertools/commons" in "node_modules" directories starting from "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/logger/lib/esm"
    Parsed package name "@aws-lambda-powertools/commons" and package subpath "."
    Checking for a package in the directory "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons"
    Read 2 entries for directory "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools"
    The file "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons/package.json" exists
    Read 3 entries for directory "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons"
    Looking for "." in "exports" map in "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons/package.json"
      Using the entry for "."
      Checking condition map for one of ["default", "import", "module", "node"]
        The key "require" does not apply
        The key "import" applies
        Checking condition map for one of ["default", "import", "module", "node"]
          The key "types" does not apply
          The key "default" applies
          Checking path "" against target "./lib/esm/index.js"
            Joined "" to "./lib/esm/index.js" to get "./lib/esm/index.js"
      The resolved path "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons/lib/esm/index.js" is exact
      Read 3 entries for directory "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons"
      Read 17 entries for directory "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons/lib"
      The file "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons/lib/esm/package.json" exists
      Read 19 entries for directory "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons/lib/esm"
      Resolved to "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons/lib/esm/index.js"
  Read 19 entries for directory "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons/lib/esm"
  Primary path is "/Users/johndoe/Codes/temp-ts/node_modules/@aws-lambda-powertools/commons/lib/esm/index.js" in namespace "file"
```

### Proposed Solution

Add the extra log levels to the , which is defined [here](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda-nodejs/lib/types.ts#L375-L384).

The change would look like this:
```diff
export enum LogLevel {
++  /** Show everything **/
++  VERBOSE = 'verbose';
--  /** Show everything **/
++  /** Show warnings, errors, and summary (default) */
  INFO = 'info',
  /** Show warnings and errors */
  WARNING = 'warning',
  /** Show errors only */
  ERROR = 'error',
  /** Show nothing */
  SILENT = 'silent',
}
```

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.102.0

### Environment details (OS name and version, etc.)

macOS

### PR DESCRIPTION
**Pull request by msambol**
Official log levels are [here](https://esbuild.github.io/api/#log-level).

Closes #27634.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by msambol** [comment]
@dreamorosi I also added `DEBUG` to round out the set.

**Review by kylelaker — APPROVED** [review]
Thanks for these and making sure they're covered by tests.

**Comment by msambol** [comment]
@SankyRed Can I nudge you for a review here?

**Review by SankyRed — APPROVED** [review]
LGTM, thank you for contributing @msambol

**Pull request merged**
