### PR TITLE
feat(ec2): Add support for P5 instances EC2

### LINKED ISSUE #27704: aws_ec2: Support for P5 InstanceClass
### Describe the feature

The P5 Instance type is now GA, but not currently supported as part of the InstanceClass Enum

### Use Case

P5 instances used in Batch pipelines for ML / Inference workloads, Creating the Batch piplines in CDK requires additional effort without the InstanceClass enum available

### Proposed Solution

Add the missing types to the list.

### Other Information

https://aws.amazon.com/ec2/instance-types/p5/

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.103.0 (build d0d7547)

### Environment details (OS name and version, etc.)

MacOS

### PR DESCRIPTION
**Pull request by niroam**
The P5 instance types were introduced in [July 2023](https://aws.amazon.com/blogs/aws/new-amazon-ec2-p5-instances-powered-by-nvidia-h100-tensor-core-gpus-for-accelerating-generative-ai-and-hpc-applications/).
The instance types are supported in [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html#cfn-ec2-instance-instancetype).

Closes #27704.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by niroam** [comment]
Exemption Request: This PR is similar to https://github.com/aws/aws-cdk/pull/27611, which didn't need changes to the README and tests.

**Comment by niroam** [comment]
Exemption Request: This PR is similar to https://github.com/aws/aws-cdk/pull/27611, which didn't need changes to the README and tests.

Please add tags pr-linter/exempt-readme and pr-linter/exempt-integ-test

**Review by scanlonp — CHANGES_REQUESTED** [review]
Looks good, thanks! Fix this typo and we are good to go.

**Review by scanlonp — DISMISSED** [review]

**Comment by scanlonp** [comment]
@mergifyio update

**Review by scanlonp — APPROVED** [review]

**Pull request merged**
