### PR TITLE
feat(aws-ecs-patterns) let user pass EventRole to ScheduledFargateTask

### LINKED ISSUE #10352: [ecs-patterns] Expose all created Roles for configuration
## :question: General Issue

If this should be filed as a feature request, I can reopen

### The Question

In short: Some resources implicitly create ("singleton") roles under the hood without allowing configuration; this blocks creation if account policies require a permission boundary etc. for IAM Roles.

Within my organization (as I understand is quite common), we have some global policies that prevent the creation of IAM Roles without a permission boundary (or specified path). Many resources in CDK allow you to explicitly pass the roles used by a resource meaning we can pre-create the role with proper configuration and then pass it in. However, several operations in CDK create IAM Roles behind the scenes without exposing that role at any point, thus preventing the use of that resource (Role fails to create due to permission/security issues).

I am currently encountering this issue while trying to use  [`ecs-patterns/ScheduledFargateTask`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts); the role itself is being created by a call dispatched to [events-targets/utils](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events-targets/lib/util.ts#L12). However, this same issue appears in other places throughout the library; one such example is the implicit role created when configuring S3 bucket configurations: the lambda created behind the scenes is not configurable or exposed in any way to allow specifying the role.

### Environment

  - **CDK CLI Version:** `1.60.0 (build 8e3f53a)`
  - **Module Version:** `1.63.0`
  - **Node.js Version:** `v12.14.1`
  - **OS:** all (OSX Mojave)
  - **Language (Version):** all (Python 3.7.4)

### Other information

Following is the cdk deploy output showing the trace through implicit role creation (technically tracing back to events-targets, but starting with ecs-patterns)

```
[STACK_NAME]: deploying...
[STACK_NAME]: creating CloudFormation changeset...
4:13:43 PM | CREATE_FAILED        | AWS::IAM::Role           | FargateTaskDefinitionEventsRole[HASH]
API: iam:CreateRole User: arn:aws-us-gov:sts::[ACCOUNT_ID]:assumed-role/advanceduser/[USER] is not authorized to perform: iam:CreateRole on resource: arn:aw
s-us-gov:iam::[ACCOUNT_ID]:role/[STACK_NAME]-FargateTaskDefinitionEventsRole[HASH]

	new Role (/private/var/folders/wv/gltyfn4j6f910j0cydhb2bwc0000gp/T/jsii-kernel-WyU4gb/node_modules/@aws-cdk/aws-iam/lib/role.js:44:22)
	\_ Object.singletonEventRole (/private/var/folders/wv/gltyfn4j6f910j0cydhb2bwc0000gp/T/jsii-kernel-WyU4gb/node_modules/@aws-cdk/aws-events-targets/lib/util.j
[█████████████████████████████·····························] (5/10)

4:13:43 PM | CREATE_FAILED        | AWS::IAM::Role           | FargateTaskDefinition/EventsRole
API: iam:CreateRole User: arn:aws-us-gov:sts:::[ACCOUNT_ID]:assumed-role/advanceduser/[USER] is not authorized to perform: iam:CreateRole on resource: arn:aw
s-us-gov:iam::[ACCOUNT_ID]:role/[STACK_NAME]-FargateTaskDefinitionEventsRole[HASH]

 ❌  [STACK_NAME] failed: Error: The stack named [STACK_NAME] failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:292:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:274:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:181:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:268:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:188:9)
The stack named [STACK_NAME] failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

### PR DESCRIPTION
**Pull request by michaelfedell**
aws-ecs-patterns/scheduled-fargate-task creates a new aws-events-targets/ecs-task to attach the task definition to a schedule. The EcsTask object accepts an optional `role` prop; defaulting to a newly created singleton role if not passed. This change allows the user to optionally specify an `eventRole` at the construction of `ScheduledFargateTask` object to pass through to the `addTaskDefinitionToEventTarget` method

Not yet resolved, but opening [WIP] for discussion sake - will remove [WIP] tag once the PR conforms to Contributing Guidelines

Fixes #10352 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by SoManyHs** [comment]
Hi @michaelfedell! Is this PR still WIP? If so, could we convert it to a draft? Thanks!

**Comment by michaelfedell** [comment]
> Hi @michaelfedell! Is this PR still WIP? If so, could we convert it to a draft? Thanks!

I've let this get stale but think it still needed tests and maybe a couple tweaks - will update and push soon

**Comment by SoManyHs** [comment]
@michaelfedell Any updates on this?

**Comment by amvi88** [comment]
Hey guys, there are a couple of issues #10352 and #16181 That could really benefit from this change ... would it be possible to reopen this?

**Pull request closed without merging**
