### PR TITLE
feat(pull-request-check): Add pull-request-check

### PR DESCRIPTION
**Pull request by hupe1980**
Publish cloudcomponents as part of the CDK:
cloudcomponents/cdk-components#8

----

Please read the [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) and follow the pull-request checklist.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eladb** [comment]
Hey @hupe1980, I am sorry if we had a misunderstanding on https://github.com/cloudcomponents/cdk-components/issues/8 - I was mainly referring to the static S3 bucket, not all constructs. I think the others are awesome and useful but I don't see them naturally fit into the CDK library.

**Comment by hupe1980** [comment]
Ah okay. No problem. I will then create a new PR for the static website

**Comment by eladb** [comment]
I am thinking that a static website should probably go under aws-s3-patterns (see aws-ecs-patterns) as an example.

**Comment by hupe1980** [comment]
@eladb I have now adapted my implementation to your specifications:
[https://github.com/hupe1980/aws-cdk/tree/hupe1980/aws-s3-static-website/packages/%40aws-cdk/aws-s3-static-website](https://github.com/hupe1980/aws-cdk/tree/hupe1980/aws-s3-static-website/packages/%40aws-cdk/aws-s3-static-website)

Next, I would switch to aws-s3-patterns.

By the way, is it okay to use [snapshots](https://github.com/cloudcomponents/jest-cdk-snapshot) for testing?

**Comment by eladb** [comment]
Yes absolutely. Most of our tests use snapshots.

**Pull request closed without merging**
