### PR TITLE
chore: inclusive language - allow and deny lists

### PR DESCRIPTION
**Pull request by njlynch**
As part of Amazon's ongoing effort to support inclusive language, this change
removes or deprecates uses of "whitelist" or "blacklist" from our public APIs
(where possible), in favor of "allowlist" and "denylist".

All public API elements were deprecated and new elements created. In cases where
this means two possible inputs can be supplied (e.g., both whitelist and
allowlist), I added checks to validate that only one was supplied.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by eladb — APPROVED** [review]

**Review by nija-at — COMMENTED** [review]
What about package READMEs? They would also need to be linted.

**Review by nija-at — COMMENTED** [review]
Would be useful to add an awslint rule that prevents using these terms in our public API and public docs?

**Comment by njlynch** [comment]
> What about package READMEs? They would also need to be linted.

I have updated the READMEs as well, in any cases where it was relevant.

> Would be useful to add an awslint rule that prevents using these terms in our public API and public docs?

Somewhat agreed, but also don't know that we would manually approve anything with this terms in it going forward. I considered a linter rule "bonus" work, but happy for us to discuss and decide to prioritize.

**Comment by nija-at** [comment]
> I considered a linter rule "bonus" work, but happy for us to discuss and decide to prioritize.

I believe the spirit of the task is to remove these language that's not inclusive, AND make sure it stays that way. I would consider some form of linter a requirement.

The bonus would be adding such a check into jsii so we can apply this across all our jsii repos and not just the aws cdk.

**Pull request merged**
