### PR TITLE
fix(iam): role/group/user's path not included in ARN

### PR DESCRIPTION
**Pull request by saltman424**
Solution to #13156 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — CHANGES_REQUESTED** [review]
You need to update tests, and I'm pretty sure the default `/` would already be included (so now your ARN would look like `arn:aws:...:role//rolename`

**Comment by saltman424** [comment]
@rix0rrr I have not had a chance to familiarize myself with the repo's testing structure. Do you have specific recommendations on what I should update and where? Also, I got rid of the 'resourceName' argument to avoid the default slash because as I understand it, just using the 'resource' argument shouldn't include any separator. Is this understanding inaccurate?

**Comment by rix0rrr** [comment]
> Do you have specific recommendations on what I should update and where?

There will be `role.test.ts`, `user.test.ts`, etc. files in the `packages/@aws-cdk/aws-ec2/test` directory. That would be a good place to add them.

Now this specific case is somewhat tricky to test, as it only comes into play when objects are being used transparently in a cross-env scenario. So in your unit test, you will need to create an `App` and two `Stack`s with different `env`s, create a `Role/Group/User` in one stack with a `path` and use its ARN in the other stack (just create a `CfnResource` with made-up properties, one of them using the ARN).

Then check that the value you're getting looks like what you expect.

I think there's even 3 cases I'd be interested in:

* No `path` supplied
* Path supplied that does NOT end in a `/`
* Path supplied that ends in a `/`
* (What if path STARTS with a `/`...?)

I wonder if IAM does any path normalization, or whether it rejects values with additional `/`es, or whether it just pastes them right in. We're going to have to mimic IAMs behavior here.

**Comment by rix0rrr** [comment]
As for what you did with the ARN components:

I liked the original better, where `resource = 'role'` and `resourceName = 'path/to/role'. Seems more logical to me (although it would produce the same string ultimately)

**Comment by saltman424** [comment]
@rix0rrr I can work on most of that. I just have one question (below).

Based on the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-path), my understanding was that IAM rejects any path that does not both start and end with a slash, so my implementation expects both. If you want CDK to support all of the cases you mentioned, we probably need to add path normalization in CDK as I believe CloudFormation will still require both. It shouldn't be hard, but do you want me to add that as part of this pull request?

I also did the pure resource implementation because it is slightly simpler when given both a beginning and ending slash, as I don't have to conditionally strip a leading slash from the path. But I can add the logic to allow us to use the resourceName argument if you think that'll be more readable.

With all that being said, I may not be able to get to it immediately. But let me know if you would like me to include path normalization or leave it for another pull request, and I'll let you know when I have had a chance to make these updates.

**Comment by rix0rrr** [comment]
> Based on the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-path), my understanding was that IAM rejects any path that does not both start and end with a slash, so my implementation expects both.

Good call. That is fine then. If we want to make that requirement more flexible, that PR would then be the moment to do that.

**Review by rix0rrr — DISMISSED** [review]
Needs tests

**Comment by saltman424** [comment]
@rix0rrr I know it took a while, but I was able to get back to this to add tests and switch to using resourceName. It seems like it is building successfully, so let me know if there is anything else needed to get this completed.

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
