### PR TITLE
feat(ec2): provide readonly access to NAT gateways in VPC

### LINKED ISSUE #4858: attach private subnet to existing VPC
Create a private subnet to VPC imported from other stack. It is possible to create a new subnet with `ec2.PrivateSubnet`. However, it is not possible to bind it default NAT route because nat gateways are not accessible outside of VPC class.  

#### Layered stacks

I’ve started with monolith Cloud Formation template that spin off entire infrastructure: networking gears, load balancers, compute resources, etc. The maintainability of it becomes a headache. It might even lead you to situation when you cannot apply updates without a downtime. Therefore, you have to split you solution for few independent layers - VPC networking shall be deployed in its own template.

The networking stack is deployed once per environment (e.g. dev, live). The deployment of The deployment of AWS resources in this design is grouped by unique routing requirement and deployed to appropriates subnets. 

**Existing** AWS CDK supports this use case

```typescript
// StackA
const vpc = new ec2.Vpc(this, 'Vpc', {/* config */})

// StackB
const vpc = /* ... pass VPC as props using multi-stack  */
```

The problem arise when we need to create a Private Subnet in StackB and ensure that subnet has internet connectivity via NAT.

```typescript
const subnet = new ec2.PrivateSubnet(this, 'MySubnet', {/* ... */})

subnet.addDefaultNatRoute(/* we are not able to add NAT here */)
``` 

The VPC class do not expose NAT GW!

### Proposed Solution

Indirectly Export natGatewayByAZ property, add method to VPC class.

```typescript
vpc.natGateway(az: string): string
```

```typescript
const gw = vpc.natGateway(vpc.availabilityZones[0])
subnet.addDefaultNatRoute(gw)
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by fogfish**
closes #4858

### CODE REVIEW

**Comment by rix0rrr** [comment]
This change will not play well with another one I have in a PR: 

https://github.com/aws/aws-cdk/pull/4898

Maybe we are better of splitting the VPC setup flow there into 2? 

* Build gateways
* Add to subnet routing tables

**Comment by fogfish** [comment]
I see. That feature looks complicated, I think I know its origins... Please let me review your proposal, I'll get back to you on this on next week.

**Comment by fogfish** [comment]
Indeed, two conflicting PR... 

About the design... I do not think that we need to impact the provisioning flow. It complicates the design and API. A new `NatProvider` fits nicely here:
* the provider maintain a set of GW (similarly to `natGatewayByAZ`)
* `Vpc.natGateway()` function is a proxy to the provider. 

The question is only PR logistic:
1. Merge this PR to master and then adopt  #4898 accordingly
2. Merge  #4898 and re-implement this feature there.

From my company perspective, we need #4858 asap, it is blocking our progress to some extends. I was hoping to see it in CDK 1.16.0

**Comment by fogfish** [comment]
Oh..., you already merged  #4898. The power of access to merge button in actions 😞 .

**Comment by fogfish** [comment]
w00t, why the review list is so big! Just because of `git rebase` !? Any this is your call now.

**Pull request closed without merging**
