### PR TITLE
feat(lambda): inline function code can exceed 4096 bytes

### PR DESCRIPTION
**Pull request by seyeong**
CloudFormation removed the 4k charcaters limit for inline function code.

Latest public documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile

Historic documentation: https://web.archive.org/web/20220309033724/https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile

Internal Code Review reference: CR-53662636

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by kaizencc — CHANGES_REQUESTED** [review]
Thanks for the documentation on this change @seyeong. Just to be sure, I would like to test this in an integ test (maybe in `integ.lambda.ts`) just to be sure that it will deploy with > 4096 bytes

**Comment by seyeong** [comment]
@kaizencc Can you please help me understand why you're requesting an integer test? I don't see a point adding it.

**Comment by kaizencc** [comment]
@seyeong for peace of mind. you're loosening a behavior that previously would have resulted in a failed deployment. it stands that we should check that the deployment will not fail before removing the check.

**Comment by seyeong** [comment]
> it stands that we should check that the deployment will not fail before removing the check.

The check can be done manually. To me, it feels like we're producing a tech debt by add it to the integration test. I personally test it myself and you can do it as well. If you still think that it is necessary to add an automated test, let me know.

**Review by kaizencc — APPROVED** [review]
The important thing is to have tested a deployment of this code (beyond what a unit test can do). Documenting that you have done so on this PR is enough for me.

**Review by TheRealAmazonKendra — DISMISSED** [review]
We need an update to the README for this change. [fromInline](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-lambda#handler-code) still documents this limit. Please also verify that you have manually tested this change and we can remove the label requiring the integration test.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
