### PR TITLE
fix(ec2): vpc.fromLookup doesn't set env.region correctl

### LINKED ISSUE #22178: aws_ec2: vpc.fromLookup doesn't set env.region correctly
### Describe the bug

The context is that the bug fix for #20496 and #20530 did not resolve the problem with the Route53.add_vpc() call not setting the region for the VPC correctly. The addVpc function is now using vpc.env.region if it is set, but the problem is that it is not set correctly to match the value in cdk.context.json and set the region from the stack instead.

### Expected Behavior

The template should have the correction region set for the VPC.

```
  "PrivateDnsE0FF4F9B": {
   "Type": "AWS::Route53::HostedZone",
   "Properties": {
    "Name": "slurmiad.local.",
    "VPCs": [
     {
      "VPCId": "vpc-nnnnnnnnnnnnnnnnn",
      "VPCRegion": "us-east-1"
     },
     {
      "VPCId": "vpc-nnnnnnnnnnnnnnnnn",
      "VPCRegion": "us-west-2"
     },
     {
      "VPCId": "vpc-nnnnnnnnnnnnnnnnn",
      "VPCRegion": "eu-west-1"
     }
    ]
   },
   "Metadata": {
    "aws:cdk:path": "slurmiad/PrivateDns/Resource"
   }
  },
```

### Current Behavior

The resulting CFN template has the correct VpcIds, but the incorrect regions:

```
  "PrivateDnsE0FF4F9B": {
   "Type": "AWS::Route53::HostedZone",
   "Properties": {
    "Name": "slurmiad.local.",
    "VPCs": [
     {
      "VPCId": "vpc-nnnnnnnnnnnnnnnnn",
      "VPCRegion": "us-east-1"
     },
     {
      "VPCId": "vpc-nnnnnnnnnnnnnnnnn",
      "VPCRegion": "us-east-1"
     },
     {
      "VPCId": "vpc-nnnnnnnnnnnnnnnnn",
      "VPCRegion": "us-east-1"
     }
    ]
   },
   "Metadata": {
    "aws:cdk:path": "slurmiad/PrivateDns/Resource"
   }
  },
```

### Reproduction Steps

I'm creating a Route53.HostedZone for use in 3 VPCs that are located in 3 different regions.
The VPCs aren't part of the stack and are created in CDK using 

```
                ec2.Vpc.from_lookup(
                    self, f"Vpc{region_dict['Region']}",
                    region = region_dict['Region'],
                    vpc_id = region_dict['VpcId'])
```

This causes an update to cdk.context.json where the VPC ids and regions are correct.
Extract from cdk.context.json:

```
  "vpc-provider:account=nnnnnnnnnnnn:filter.vpc-id=vpc-nnnnnnnnnnnnnnnnn:region=us-west-2:returnAsymmetricSubnets=true": {
    "vpcId": "vpc-nnnnnnnnnnnnnnnnn",
    "vpcCidrBlock": "10.3.0.0/16",
    "availabilityZones": [],
    "subnetGroups": [
      {
        "name": "Private",
        "type": "Private",
        "subnets": [
          {
            "subnetId": "subnet-nnnnnnnnnnnnnnnnn",
            "cidr": "10.3.64.0/18",
            "availabilityZone": "us-west-2a",
            "routeTableId": "rtb-nnnnnnnnnnnnnnnnn"
          },
          {
            "subnetId": "subnet-nnnnnnnnnnnnnnnnn",
            "cidr": "10.3.128.0/18",
            "availabilityZone": "us-west-2b",
            "routeTableId": "rtb-nnnnnnnnnnnnnnnnn"
          },
          {
            "subnetId": "subnet-nnnnnnnnnnnnnnnnn",
            "cidr": "10.3.192.0/18",
            "availabilityZone": "us-west-2c",
            "routeTableId": "rtb-nnnnnnnnnnnnnnnnn"
          }
        ]
      },
      {
        "name": "Public",
        "type": "Public",
        "subnets": [
          {
            "subnetId": "subnet-nnnnnnnnnnnnnnnnn",
            "cidr": "10.3.0.0/26",
            "availabilityZone": "us-west-2a",
            "routeTableId": "rtb-nnnnnnnnnnnnnnnnn"
          },
          {
            "subnetId": "subnet-nnnnnnnnnnnnnnnnn",
            "cidr": "10.3.0.64/26",
            "availabilityZone": "us-west-2b",
            "routeTableId": "rtb-nnnnnnnnnnnnnnnnn"
          },
          {
            "subnetId": "subnet-nnnnnnnnnnnnnnnnn",
            "cidr": "10.3.0.128/26",
            "availabilityZone": "us-west-2c",
            "routeTableId": "rtb-nnnnnnnnnnnnnnnnn"
          }
        ]
      }
    ]
  },
```

I create the Hosted Zone:

```
            self.hosted_zone = route53.HostedZone(self, "PrivateDns",
                vpcs = [self.vpc],
                zone_name = self.config['Domain']
            )
            self.hosted_zone.add_vpc(remote_vpcs[region_dict['Region']])
```

### Possible Solution

I'm not familiar with the context provider, but it either it's not returning the correct region or the VPC constructor isn't using it.

https://github.com/aws/aws-cdk/blob/v1-main/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1167-L1178

### Additional Information/Context

_No response_

### CDK CLI Version

2.42.1

### Framework Version

_No response_

### Node.js Version

16.15.0

### OS

AmazonLinux2

### Language

Python

### Language Version

Python 3.7.10

### Other information

_No response_

### PR DESCRIPTION
**Pull request by daschaa**
Will fix #22178

@peterwoodworth @TheRealAmazonKendra 
I have found out that the integration test had a bug. I passed the wrong stack in the `fromLookup` call.

Now I have fixed this, and adjusted the `ContextProvider` method for searching for a VPC. The problem is now, that the region is not set correctly even though i have adjusted the code in the `ContextProvider`. Do you have an idea / hint what i have done wrong? I'm somehow clueless at this point.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by daschaa** [comment]
> @daschaa
> 
> > Do you have an idea / hint what i have done wrong? I'm somehow clueless at this point.
> 
> We pass the region into the context provider, but we don't return that region in the response so the default is used (which is the stack region).
> 
> https://github.com/aws/aws-cdk/blob/68fdfc131b0810eba44659db1272e930f38168cf/packages/aws-cdk/lib/context-providers/vpcs.ts#L136

I have tried to add this in this pull request: https://github.com/aws/aws-cdk/pull/22263/files#diff-53c32f5599150c347bbc2e0fb7e851eb76551687cb9c0b311f09a05b128b6d3bR152 🤔
But I think I messed it up somehow, because the integration tests still show the "same" result.

**Comment by corymhall** [comment]
> I have tried to change the returned object in this pull request: [#22263 (files)](https://github.com/aws/aws-cdk/pull/22263/files#diff-53c32f5599150c347bbc2e0fb7e851eb76551687cb9c0b311f09a05b128b6d3bR152) 🤔
> But I think I messed it up somehow, because the integration tests still show the "same" result.

hmm it looks like it's because the current snapshot has the correct results already. I'm not sure how that is possible, there must be something else going on.

**Comment by daschaa** [comment]
> > I have tried to change the returned object in this pull request: [#22263 (files)](https://github.com/aws/aws-cdk/pull/22263/files#diff-53c32f5599150c347bbc2e0fb7e851eb76551687cb9c0b311f09a05b128b6d3bR152) 🤔
> > But I think I messed it up somehow, because the integration tests still show the "same" result.
> 
> hmm it looks like it's because the current snapshot has the correct results already. I'm not sure how that is possible, there must be something else going on.

@corymhall I think this is because I made a mistake in the current integration test. I have passed in the wrong stack in the lookup function. This is now changed and (correctly) leads to bug that is mentioned in the linked issue. So I can reproduce the error described in the issue with the integration test now.

And I thought the fix would be to return the region in the Context Provider response, but somehow I'm missing something. I'm really sorry for the confusion!

**Comment by TheRealAmazonKendra** [comment]
I don't think this was actually abandoned. It was waiting on feedback from us. Also, this isn't a CLI change so I'm just adding that exemption label.

**Pull request closed without merging**
