### PR TITLE
fix(iam): cannot import service role with a principal in its path

### LINKED ISSUE #8691: (aws-iam): role contains invalid characters for service roles
I have a service account role - generated by AWS itself - with about following ARN:

```
ssm_role_arn = "arn:aws:iam::123456789123:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM"
```

Then

```
aws_iam.Role.from_role_arn(id, "my_ssm_role", role_arn=ssm_role_arn).role_name
```

returns `aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM` but should return just `AWSServiceRoleForAmazonSSM` instead.

Using the Role `from_role_arn` leads to errors on deployment, as the role name contains invalid characters like `/`.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ThomasSteinbach**
Fixes #8691

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ThomasSteinbach** [comment]
It would be nice, if some typescript/cdk programmer could do this fix right.

**Comment by skinny85** [comment]
Thanks for the fix @ThomasSteinbach ! I've updated your PR, let's see if the CI build passes.

**Comment by ThomasSteinbach** [comment]
Cool, thanx @skinny85

**Comment by ThomasSteinbach** [comment]
Hi @rix0rrr , could you please review or assign so. to review the changes made by skinny85 and me? It looks like skinny85 known what he is doing, so it shouldn't be a great hassle :)

**Comment by dvonessen** [comment]
I need this too, so that we can migrate from AWS CFN to CDK.

**Pull request merged**
