### PR TITLE
feat(cdk): Add support for UseOnlineResharding with UpdatePolicies.

### PR DESCRIPTION
**Pull request by ZeldoKavira**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

@rix0rrr

### CODE REVIEW

**Comment by eladb** [comment]
Could you please add a unit test for this?

**Comment by eladb** [comment]
@ZeldoKavira apologies, didn't read through. At any rate, it's usually not a great practice to modify an existing test. Any chance you could instead add another test for this specific feature?

**Comment by ZeldoKavira** [comment]
@eladb I certainly can, but it seems like that test case was created to specifically test this use case, which is why I altered it

**Comment by ZeldoKavira** [comment]
@eladb All set!

**Pull request merged**
