### PR TITLE
chore(ec2): add M7g and R7g instances

### PR DESCRIPTION
**Pull request by jumic**
Support new M7g and R7g instances.

[Announcement](https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-ec2-m7g-r7g-instances/)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jumic** [comment]
Exemption Request:
No integration test has been added as EC2 instances do not have a test for each Instance type.

Clarification Request:
The README file has not been changed because it does not contain a list of instance types.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Per the announcement, these are only available in a few regions. This should be added to the doc string so users are aware

> All of these instances are available in the following [AWS Regions](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/): US East (Ohio), US East (N. Virginia), US West (Oregon), and Europe (Ireland).

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
Failure unrelated. Re-building

**Review by TheRealAmazonKendra — APPROVED** [review]
That failure was unrelated. Approving this pending a successful build.

**Pull request merged**
