### PR TITLE
feat(ec2): add missing endpoints to InterfaceVpcEndpointAwsService

### LINKED ISSUE #21402: (ec2): add codeartifact api and respository to InterfaceVpcEndpointAwsService
### Describe the feature

I would like to add the following to the InterfaceVpcEndpointAwsService:
```
    declare const vpc: ec2.Vpc;

    new ec2.InterfaceVpcEndpoint(
      this,
      'VpcEndpoint',
      {
        vpc: vpc,
        service: ec2.InterfaceVpcEndpointAwsService.CODEARTIFACT_API,  // Does not exist
      }
    );
```
OR
```
    declare const vpc: ec2.Vpc;

    new ec2.InterfaceVpcEndpoint(
      this,
      'VpcEndpoint',
      {
        vpc: vpc,
        service: ec2.InterfaceVpcEndpointAwsService.CODEARTIFACT_REPOSITORIES,  // Does not exist
      }
    );
```

### Use Case

I have to write out each of these endpoints separately from the existing ones, like so:
```
    this.vpc.addInterfaceEndpoint('AWSEndpointCodeArtifact', {
      service: {
        name: 'com.amazonaws.us-west-2.codeartifact.repositories',
        port: 443,
      },
      privateDnsEnabled: true,
    });
```

```
    this.vpc.addInterfaceEndpoint('AWSEndpointCodeArtifactApi', {
      service: {
        name: 'com.amazonaws.us-west-2.codeartifact.api',
        port: 443,
      },
      privateDnsEnabled: true,
    });
```

### Proposed Solution

I have opened a PR for this feature #21401

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

^2.21.0

### Environment details (OS name and version, etc.)

MacOS 12.5

### PR DESCRIPTION
**Pull request by michaeldrey**
This add the following endpoints to `InterfaceVpcEndpointAwsService`:
`codeartifact.api`
`codeartifact.respositories`
`batch`
`s3`
`autoscaling`
`autoscaling-plan`
`application-autoscaling`

closes #21402 #21220 #21338 #19420 #14423
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hoegertn** [comment]
duplicate of my PR #21220 but you have the missing tests.
Can you add S3 also? Then my PR would be superseded.

**Comment by michaeldrey** [comment]
Sure thing. I can add S3 and test cases for it todat

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Just two quick notes: 
1. This is missing the chore/feat/fix designation at the beginning of the PR title.
2. Looks like #21220 added these to the public docs. Can you do that as well?

**Comment by michaeldrey** [comment]
@TheRealAmazonKendra  Went ahead and added the S3 endpoint in #21220. Unfortunately it appears that integ tests aren't working correctly in the library (some tests havent been updated to use the integ-runner yet). If you think this also needs an integ test I'll have to open a seperate PR to fix those tests and add one.

Second, I added TSdoc entries for the endpoints as I do not understand why we are adding these endpoints doc entries to the ignore list. Happy to update the others with proper TSdoc update if we can agree on the verbiage so they're all consistent on the doc site

**Comment by TheRealAmazonKendra** [comment]
I don't think integ tests are needed here.

**Comment by TheRealAmazonKendra** [comment]
Oops, my comment above said they wrong thing. We went to add them to the exclude. TBH, I'm not sure why we've excluded these but we went it to be consistent with what we've done in the past.

**Comment by michaeldrey** [comment]
Sounds good! I'll add those to the exclude list for consistency

**Comment by michaeldrey** [comment]
Don't want to bloat the ticket or add scope creep, but i can add #21338 to this

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Go for it! Just putting this back in changes requested so I see when that's been done.

**Comment by TheRealAmazonKendra** [comment]
I see there's a few more endpoints requested in [issues](https://github.com/aws/aws-cdk/issues?q=is%3Aissue+is%3Aopen+InterfaceVpcEndpointAwsService). Feel free to add as many of those as you feel like doing in this PR.

**Comment by TheRealAmazonKendra** [comment]
Anymore you want to add or is this ready to go? It looks good on my end.

**Comment by michaeldrey** [comment]
@TheRealAmazonKendra This is ready to go, I think the others in that list might be a little more effort the ones i've already added

**Review by TheRealAmazonKendra — APPROVED** [review]

**Comment by animateM** [comment]
Too late to ask for the bedrock-runtime endpoints?

**Pull request merged**
