### PR TITLE
fix(lambda-nodejs): maximum call stack size exceeded or converting circular structure to JSON

### LINKED ISSUE #11693: (lambda-nodejs): Unit tests fail after upgrading to CDK 1.75.0: RangeError: Maximum call stack size exceeded         at Array.sort (native)
It seems there is some fundamental change in `NodejsFunction` as it no longer behaves in the same way when bundling. Running existing unit tests produces a "Maximum call stack size exceeded" error.

### Reproduction Steps

See example project at https://github.com/markusl/cdk-codepipeline-bitbucket-build-result-reporter/runs/1452010511 and https://github.com/markusl/cdk-ecr-image-scan-handler/runs/1452125431

```
FAIL test/index.test.ts (10.518 s)
  ✕ Create CodePipelineBitbucketBuildResultReporter (351 ms)

  ● Create CodePipelineBitbucketBuildResultReporter

    RangeError: Maximum call stack size exceeded
        at Array.sort (native)

```

### What did you expect to happen?

Would expect bundling & tests to work just fine after upgrading.

### Environment

  - **CDK CLI Version  :**  1.75.0 (build 7708242)
  - **Framework Version:** 1.75.0
  - **Node.js Version:** v14.15.0
  - **OS               :** macOS
  - **Language (Version):** TypeScript 4

### Other

--- 

This is :bug: Bug Report

### LINKED ISSUE #11726: (lambda): adding events in constructor causes circular json
When creating a lambda function, if the event sources are added in the constructor of the function cdk raises a circular json error.

### Reproduction Steps

```
const myQueue= new sqs.Queue(this, 'Queue', {
  queueName: 'financesUnorderTransactionsSqs',
});
const myLambda = new lambda.NodejsFunction(this, 'ConsumerUnorderTransactionFn', {
  entry: 'my-handler.ts',
  events: [new SqsEventSource(myQueue)],
});
```

### What actually happened?

When running `npx cdk list` this is the output:

```
Converting circular structure to JSON
    --> starting at object with constructor 'Queue'
    |     property 'node' -> object with constructor 'ConstructNode'
    --- property 'host' closes the circle
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :** 1.75
  - **Framework Version:** 1.75
  - **Node.js Version:** 14.8.0
  - **OS               :** Ubuntu Linux
  - **Language (Version):** TypeScript 3.9.7

--- 

This is :bug: Bug Report

### LINKED ISSUE #11762: (aws-lambda-nodejs): can't build with lambda layers
The `NodejsFunction` fails with the following error when attempting to build with a lambda layer.
```bash
$ cdk synth
Converting circular structure to JSON
    --> starting at object with constructor 'LayerVersion'
    |     property 'node' -> object with constructor 'ConstructNode'
    --- property 'host' closes the circle
Subprocess exited with error 1
error Command failed with exit code 1.
```

### Reproduction Steps

I created a repo to demonstrate the error here: https://github.com/elthrasher/circular-layer
Should be reproducible with any NodejsFunction + layer combo. Instructions in the README.

### What did you expect to happen?

Add a lambda layer to a NodejsFunction construct.

### What actually happened?

Got the error above.

### Environment

  - **CDK CLI Version: 1.75.0**
  - **Node.js Version: 12.19.1**
  - **OS: macOS Catalina**
  - **Language (Version): TypeScript (all)**

### Other

There is a workaround available (see https://github.com/elthrasher/circular-layer).

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
All the `FunctionOptions` were leaking into `core` where a cache key is
calculated in asset staging. Some of those options have circular references
making it impossible to calculate a cache key with the current implementation.

Another PR is needed to make the cache key calculation in `core` more
robust.

Closes #11693 
Closes #11726
Closes #11762

BREAKING CHANGE: bundling customization options like `minify` or `sourceMap` are now gathered under a new `bundling` prop.
* **lambda-nodejs**: `bundlingEnvironment` is now `bundling.environment`
* **lambda-nodejs**: `bundlingDockerImage` is now `bundling.dockerImage`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
Will add a test for the VPC case

**Comment by jogold** [comment]
@eladb this is ready for review and will fix the issue

**Comment by ligaz** [comment]
@jogold Can you update the [README.md](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-lambda-nodejs/README.md) as well?

**Comment by jogold** [comment]
> @jogold Can you update the [README.md](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-lambda-nodejs/README.md?rgh-link-date=2020-11-25T16%3A42%3A07Z) as well?

Good catch! Done.

**Comment by josebrandaoppb** [comment]
Nice finding. I'm actually hitting this case right now when passing a vpc to my lambda function. Is there any version where this is functional ?

**Comment by jogold** [comment]
> Nice finding. I'm actually hitting this case right now when passing a vpc to my lambda function. Is there any version where this is not happening ?

The problem starts with 1.75.0

**Comment by matthias-pichler-warrify** [comment]
This actually also happens when I try to deploy a Lambda@Edge (so not only VPC)

**Comment by jogold** [comment]
> This actually also happens when I try to deploy a Lambda@Edge (so not only VPC)

Thanks for the feedback, this PR will also fix this.

**Comment by msimpsonnz** [comment]
I am getting the same issue when trying to add defined IAM Role to the NodeJS function, hopefully this is fixed here too but thought I would mention it

**Comment by jogold** [comment]
> hopefully this is fixed here too but thought I would mention it

Yes, it should be the case.

**Review by eladb — APPROVED** [review]
Looks good

**Pull request merged**
