### PR TITLE
feat(cli): add stack resource count to cdk list --long

### PR DESCRIPTION
**Pull request by ghost**
The perennial question: how many resources are in my stack? Am I close to needing to split up my stack due to the CloudFormation 200-resource limit? Now `cdk ls --long` will tell you.

```
C:\Users\jkindall\pipeline>cdk ls --long
- id: LambdaStack
  name: LambdaStack
  resources: 7
  environment:
    account: unknown-account
    region: unknown-region
    name: aws://unknown-account/unknown-region
- id: PipelineDeployingLambdaStack
  name: PipelineDeployingLambdaStack
  resources: 26
  environment:
    account: unknown-account
    region: unknown-region
    name: aws://unknown-account/unknown-region
```

I considered adding the count to plain `cdk ls`, but there might be scripts out there relying on that being a simple list of stack names that we don't want to break. The output of `cdk ls --long` is YAML and consumers should be using a proper parser, so this is less breaky.

This will allow the `rescount.js` utility in the Guide's Troubleshooting topic to be removed.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Jerry-AWS** [comment]
@shivlaks It works fine with environment-agnostic stacks (the sample output above is from one of those), it just puts in `unknown-account` or `unknown-region`. That was already there.

I'll work on the help message and an integ test.

Do you think that while I'm in here, it would be useful to add anything else? I played around with including the names of parameters and outputs. It's easy to add those if you think it would be useful, but I don't want to get to a point where it's just a cut-down version of the full template.

**Comment by shivlaks** [comment]
> @shivlaks It works fine with environment-agnostic stacks (the sample output above is from one of those), it just puts in `unknown-account` or `unknown-region`. That was already there.
> 
> I'll work on the help message and an integ test.
> 
> Do you think that while I'm in here, it would be useful to add anything else? I played around with including the names of parameters and outputs. It's easy to add those if you think it would be useful, but I don't want to get to a point where it's just a cut-down version of the full template.

@Jerry-AWS I think it makes sense to add outputs since a few constructs generate them, and customers add them as well. They represent values that are not known until after the deployment has concluded.

However, I'd leave parameters out for now since many constructs (i.e. apigateway, assets) add their own. It could become really noisy fast. What do you think?

**Comment by Jerry-AWS** [comment]
@shivlaks I like including parameter names for users who are trying to deploy a stack with parameters, but this is kind of a niche use case anyway. I think I'll just leave it the way it is for now; add more when customers want it.

**Comment by rix0rrr** [comment]
Closing this for staleness. Let me know on Slack if you want to pursue this.

**Pull request closed without merging**
