### PR TITLE
feat(core): CloudFormation resource type providers

### PR DESCRIPTION
**Pull request by eduardomourar**
This is an initial attempt to use resource type providers. Therefore, we will allow to register a resource type that has already been packaged (you can find examples such as [`Atlassian::Opsgenie::Integration`](https://github.com/opsgenie/opsgenie-cloudformation-resources) and [`OC::Organizations::PasswordPolicy`](https://github.com/eduardomourar/aws-resource-provider-passwordpolicy/releases)).

In order to try out the registration, you can do something like this:

```ts
import { Construct } from '@aws-cdk/core';
import * as cr from '@aws-cdk/custom-resources';

export class OpsgenieIntegrationResourceProvider extends cr.ResourceTypeProvider {
  constructor(scope: Construct, id: string) {
    super(scope, id, {
      typeName: 'Atlassian::Opsgenie::Integration',
      semanticVersion: '0.1.0',
      schemaHandlerPackage: 's3://opsgeniedownloads/cloudformation/atlassian-opsgenie-integration.zip',
    });
  }
}
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by AlexCheema** [comment]
This is great! Currently the workflow for registering resources is convoluted. This solves a major pain point.

@eduardomourar It looks like you have some styling errors in the build.

**Comment by eduardomourar** [comment]
@AlexCheema , thanks. This is still working in progress, so I will fix some of these errors at some point.

One thing to consider, this has been implement with a custom resource that actually register the resource types, so you will have a high resource footprint because a lambda provider will be deployed in each region and account.

**Comment by AlexCheema** [comment]
> @AlexCheema , thanks. This is still working in progress, so I will fix some of these errors at some point.
> 
> One thing to consider, this has been implement with a custom resource that actually register the resource types, so you will have a high resource footprint because a lambda provider will be deployed in each region and account.

I see. So the Cloudformation-native approach is preferred then?

**Comment by eduardomourar** [comment]
> I see. So the Cloudformation-native approach is preferred then?

Yes, but that might take some time, because the initial CFN native version will (most probably) not handle named alias and deleting previous versions.

**Comment by eladb** [comment]
@eduardomourar we decided that we will not accept this feature at the moment. Happy to continue the conversation over an RFC, and I would also encourage you to publish this as a third party library.

See the README in https://github.com/construct-catalog/catalog for details.

**Pull request closed without merging**
