### PR TITLE
feat(cli): unable to access bootstrap bucket and assets without kms key

### PR DESCRIPTION
**Pull request by mark-ship-it**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by corrjo — APPROVED** [review]

**Comment by ahammond** [comment]
Hey, if you're already there, maybe you can throw an alias on that key so it's documented-ish in KMS?

**Comment by rix0rrr** [comment]
If you have additional requirements of the bootstrap stack for your particular use case, you can [customize it yourself](https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html).

This PR and your ticket do not describe a use case or problem that is addressed, just a solution.

Let me put this in crude terms: you need to convince me why it's worthwhile for *me* to take on maintenance of *your* code. Please describe the problem that 1000s of other CDK users have that this code solves. Without that, I cannot justify taking ownership of this code.

Closing this PR for now.

**Comment by mark-ship-it** [comment]
@rix0rrr , this is my first PR against the repo, so please bear with me as I get familiar with the standard procedure.
In order to read/write assets in the s3 bucket within the bootstrap stack, it is not sufficient to have s3:* permissions.  users must also have access to the kms key.  currently, there is no way for users to look this up easily.  providing an ssm parameter to look up the default Qualifier and the corresponding KMS key is a nice way to provide this information.

for those users with multiple bootstrap stacks, this solution doesn't work well and i accept your recommendations as to how best to address that use case.

**Comment by ahammond** [comment]
Fixes #10904

**Pull request closed without merging**
