### PR TITLE
fix(lambda-nodejs): pnpm installs frozen lockfile in a CI environment

### PR DESCRIPTION
**Pull request by Tucker-Eric**
[pnpm automatically enables `--frozen-lockfile` in CI environments](https://pnpm.io/cli/install#--frozen-lockfile) which breaks `NodejsFunction` local bundling.

This change appends the `--no-prefer-frozen-lockfile` flag as described in https://github.com/pnpm/pnpm/issues/1994#issuecomment-609403673

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Tucker-Eric** [comment]
Looking for an Exemption Request for the integration test as well.

**Comment by TheRealAmazonKendra** [comment]
I'm removing the exemption request label for now. Please use a quote reply to my last message to add it back when you respond to my question so I see that this needs another look.

Thanks for you work here!

**Comment by Tucker-Eric** [comment]
> > Looking for an Exemption Request for the integration test as well.
> 
> To provide the exemption request, can you please describe how this was manually tested? I am inclined to agree that this is difficult to write an automated test for.

Hey @TheRealAmazonKendra! Appreciate your help with this!

This was manually tested locally using the command dumped in the error output of the current command.
image

Removing/replacing the asset staging path with a local one and rerunning the same commands in order (with the `CI=true` env variable to mimmic a CI environment) the following commands were run.

without `--no-prefer-frozen-lockfile`
```bash
mkdir asset-staging && \
    echo '{"dependencies":{"pg":"8.10.0"}}' > "asset-staging/package.json" && \
    cp "pnpm-lock.yaml" "asset-staging/pnpm-lock.yaml" && \
    cd asset-staging && \
    CI=true pnpm install --config.node-linker=hoisted --config.package-import-method=clone-or-copy && \
    rm "node_modules/.modules.yaml"
```

with `--no-prefer-frozen-lockfile`
```bash
mkdir asset-staging && \
    echo '{"dependencies":{"pg":"8.10.0"}}' > "asset-staging/package.json" && \
    cp "pnpm-lock.yaml" "asset-staging/pnpm-lock.yaml" && \
    cd asset-staging && \
    CI=true pnpm install --config.node-linker=hoisted --config.package-import-method=clone-or-copy --no-prefer-frozen-lockfile && \
    rm "node_modules/.modules.yaml"
```
image

**Review by TheRealAmazonKendra — APPROVED** [review]
Thank you for your contribution!

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio reset

**Comment by ofhouse** [comment]
I there any ETA when this fix will be published?
Tested it with `aws-cdk-lib@2.72.1` but it seems like this was not part of the release: https://unpkg.com/browse/aws-cdk-lib@2.72.1/aws-lambda-nodejs/lib/package-manager.js

**Pull request merged**
