### PR TITLE
fix(cfnspec): update cfn spec source #3265

### PR DESCRIPTION
**Pull request by ScOut3R**
AWS Support confirmed that for this issue the published CFN specification is wrong in us-east-1 and ap-northeast-1. All the other regions are correct, but again, only for this specific issue.

Switching the CFN spec source to us-west-2 until the CFN team fixes the published resources in us-east-1.

fixes(#3265)

### CODE REVIEW

**Comment by rix0rrr** [comment]
Looks like `AWS::ManagedBlockchain` is not available in `us-west-2`, so from the PoV of the CDK that looks like a regression. Looks like there is no single correct version of the CFN specification just yet that contains both `AWS::SSM::MaintenanceWindowTarget` and `AWS::ManagedBlockchain::*`.

**Comment by ScOut3R** [comment]
> Looks like `AWS::ManagedBlockchain` is not available in `us-west-2`, so from the PoV of the CDK that looks like a regression. Looks like there is no single correct version of the CFN specification just yet that contains both `AWS::SSM::MaintenanceWindowTarget` and `AWS::ManagedBlockchain::*`.

Sorry for leaving the issue hanging in the air, I am just overwhelmed with work related tasks at the moment (CDK is going to production ;)).

Yes, it seems the best course of action is to wait for the CFN team to sort out the issue on their end, otherwise thinks might break even more further down the road.

It's a shame though, because my whole patching strategy (and some state management) was based on SSM.

**Comment by rix0rrr** [comment]
Looks like you're in luck, since submitting this PR the CFN team has updated the us-east-1 spec to include the SSM resource you need. Working on importing it here: https://github.com/aws/aws-cdk/pull/3710

**Comment by ScOut3R** [comment]
Yay, happy days!

Now if they were just to fix the issue with the Parameters property of AWS::SSM::Association :D

**Pull request closed without merging**
