### PR TITLE
chore: more style rules for eslint

### PR DESCRIPTION
**Pull request by jogold**
Configure `comma-spacing`, `no-multi-spaces`, `array-bracket-spacing`,
`array-bracket-newline`, `object-curly-spacing`, `object-curly-newline` and
`object-property-newline` to uniformize arrays and objects.

* Valid arrays (no bracket spacing, no space before comma, a single space after
comma):

```ts
[1, 2, 3]

[
  1,
  2,
  3,
]

[
  1, 2,
  3, 4,
]
```
* Valid objects (curly spacing):

```ts
{ key: 'value' }

{ key1: 'value1', key2: 'value2 }

{
  key1: 'value1',
  key2: 'value2',
}
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
Relevant diff: https://github.com/aws/aws-cdk/pull/9517/files#diff-52f1fdeb95d5b1b5d0a3f1af3a20e3d5

**Comment by skinny85** [comment]
CCing @eladb , who might have opinions on this.

**Comment by jogold** [comment]
> Thanks for the PR @jogold ! I'm putting it in "Request changes" to make sure it doesn't get merged before @eladb had a chance to look.

Just added newline consistency, you can put it back in "Request changes" if you want.

**Comment by jogold** [comment]
@eladb @skinny85 any feedback here? This branch/PR is quite hard to maintain if not merge quickly

**Comment by jogold** [comment]
@eladb fixed the last linting errors/merge conflicts. Can you re-approve? Thanks.

**Pull request merged**
