### PR TITLE
fix(cli): release outdir lock when synth fails

### LINKED ISSUE #27864: (cli): cdk watch does not recover if there is an error in cdk stack/app
### Describe the bug

If I made an error that does not resolve into a valid cloudformation, cdk watch throws the error on console. However, if I fix that issue, I would expect cdk to detect the issue to resolve and deploy the correct cloudformation template. CDK watch gets hung instead.

### Expected Behavior

Expect cdk watch to redeploy once the error has been fixed.

### Current Behavior

If I made an error that does not resolve into a valid cloudformation, cdk watch throws the error on console. However, if I fix that issue,  CDK watch gets hung. It detects the change but does not deploy.

### Reproduction Steps

This is a valid stack and app : 
```
app = App()
ApiEventBridgeLambdaStack(app, "ApiEventBridgeLambdaStack")
```
If I update it to the following while cdk watch is running, cdk watch will throw the error but stays hung after I fix the error (remove a mistyped N in this case): 
```
app = App()
ApiEventBridgeLambdaStack(appN, "ApiEventBridgeLambdaStack")
```

This happens with stack level changes as well.

Detects change but does not deploy, stays in hung state  : 

image

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

v2.100.0

### Framework Version

_No response_

### Node.js Version

v18.16.0

### OS

MAC

### Language

Python

### Language Version

3.10.6

### Other information

Reproducible with typescript too
Workaround is to interrupt the terminal and re run cdk watch.

### PR DESCRIPTION
**Pull request by misterjoshua**
### Issue # (if applicable)

Closes #27864

### Reason for this change

When using cdk watch mode, a synth failure causes the CDK CLI to no longer deploy changes. The CDK CLI must be restarted to resume watch mode. The cause of the issue is that CDK CLI never releases the outdir write lock if synthing fails, so subsequent attempts to exec the user's app cannot acquire the outdir writer lock.

### Description of changes

I added a try/catch that releases the outdir writer lock & rethrows the error when a synth fails.

### Description of how you validated changes

I added a unit test. I also ran the modified cdk cli on a project of my own and simulated the failure of a synth to see whether the issue was resolved, and it is.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by scanlonp** [comment]
This makes good sense. Let me know when it's ready for review, and we can run it through the pipeline.

**Comment by misterjoshua** [comment]
@scanlonp Thanks for checking in. I've marked it ready now. I'll keep an eye out for feedback. TY

**Comment by scanlonp** [comment]
Can look at our testing for `cdk watch`, but not sure we have the infrastructure for integ testing this type of change. Going to put the integ test exempt label for now.

I can also pull this down and test it out; I assume this fixed `watch` hanging on your side @misterjoshua?

**Comment by misterjoshua** [comment]
> Can look at our testing for `cdk watch`, but not sure we have the infrastructure for integ testing this type of change. Going to put the integ test exempt label for now.

Sounds good. I wasn't sure about that part and had been asking around. 😂

> 
> I can also pull this down and test it out; I assume this fixed `watch` hanging on your side @misterjoshua?

Yep. Works great for me!

**Comment by scanlonp** [comment]
@Mergifyio update

**Comment by scanlonp** [comment]
Worked clean in the pipeline. Adding labels.

**Comment by misterjoshua** [comment]
@scanlonp Hey. Do I need to do anything with the code to move this PR forward? I saw that the CodeQL action failed, but its failure appears to be an OOM condition not necessarily related to this change.

**Comment by scanlonp** [comment]
Hey @misterjoshua, I think the code is in a good spot. I want to test this out myself just to double check (even though I 100% believe your local testing results!). I'll make it a goal to have it in by the next release.

Also I believe the CodeQL is not concerning for this PR. We have been seeing that out-of-space failure consistently.

**Comment by misterjoshua** [comment]
@scanlonp

> Hey @misterjoshua, I think the code is in a good spot. I want to test this out myself just to double check (even though I 100% believe your local testing results!). I'll make it a goal to have it in by the next release.

Hey Parker. Sorry to bug, but how likely do you see this PR making it into the next release? Thanks.

**Review by moltar — APPROVED** [review]

**Review by mrgrain — APPROVED** [review]

**Pull request merged**
