### PR TITLE
 fix(ecs): allow imported self signed cert without domain/zone

### PR DESCRIPTION
**Pull request by zacyang**
This is related to https://github.com/aws/aws-cdk/issues/7120
In case I want to use a self signed certfication, there's no point to check the domain/zone since there's none.

with this change the following code can work 
```
const certificate = Certificate.fromCertificateArn(this, 'certificate', 'arn xxx')
new ApplicationLoadBalancedFargateService(
            this,
            'Service',
            {
                cluster,
                memoryLimitMiB: 1024,
                cpu: 512,
                certificate,
                serviceName: 'service',
                protocol: elbv2.ApplicationProtocol.HTTPS,
                taskImageOptions: {
                    image: ecs.ContainerImage.fromEcrRepository(
                        asset.repository,
                        asset.sourceHash
                    ),
                    enableLogging: true,
                    containerPort: 8080,
                    environment: {
                        BUNLDE_BUCKET: props.bundleBucketName,
                    },
                },
                desiredCount: 1,
            }
        );
```
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by SoManyHs — COMMENTED** [review]
Hi @zacyang, thanks for your contribution -- do you think you could add some tests to this change? Thank you!

**Comment by zacyang** [comment]
Thanks I will add some tests

**Comment by zacyang** [comment]
Hi @m17kea I will do it this weekend, as it's pretty busy working weeks recently.

**Comment by m17kea** [comment]
Thanks @zacyang

**Comment by NGL321** [comment]
I'm going to reopen since it seems that this is still in progress

**Comment by zacyang** [comment]
stilling working on it, last week was a release week,  did not have much time.

**Comment by cgarvis** [comment]
Resolved in #14004

**Pull request closed without merging**
