### PR TITLE
fix(dynamodb): missing grantRead for ConditionCheckItem

### PR DESCRIPTION
**Pull request by hoegertn**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by skinny85** [comment]
@hoegertn any justification on this change? Is this permission related to transactions? Should we have a separate API that includes transactions?

I'm just not 100% sure what the implications here are.

**Comment by hoegertn** [comment]
Yes, you are right, this permission is used within transactions. Imho it is a read action on a table so I see no reason why it should not be allowed on `grantRead`. I would even argue that adding it might help people to use transactions inside their apps because they can still use the normal grant methods.

**Review by bitbauer — COMMENTED** [review]
Changes are consistent.
As documented ConditionCheckItem is general read-only action:
https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondynamodb.html
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/specifying-conditions.html

When condition is used together with PutItem/UpdateItem/DeleteItem resulting permission error relates to write action. This will also help understanding permission issues. This is another reason to add it to overall read permissions.

**Review by skinny85 — APPROVED** [review]
Fine, you wore me down 🙂

**Pull request merged**
