### PR TITLE
chore(glue): support ConnectionType.MARKETPLACE and ConnectionType.CUSTOM

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

N/A

### Reason for this change
`MARKETPLACE` and `CUSTOM` are not supported in the current L2 Construct. (`SFTP` is also missing, but it is not supported at the moment.)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-connectiontype

### Description of changes
Add missing connection types.

### Description of how you validated changes
I determined that no testing was needed since this was only an addition of connection types.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍
Could you also add a link to CFN documentation to the documentation of the `ConnectionType` class for context?
```ts
 * If you need to use a connection type that doesn't exist as a static member, you
 * can instantiate a `ConnectionType` object, e.g: `new ConnectionType('NEW_TYPE')`.
 * 
 * @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-connectiontype
 */
export class ConnectionType {
```

**Comment by mazyu36** [comment]
@lpizzinidev 
Thank you for your review!
I added the link.

**Comment by TheRealAmazonKendra** [comment]
We have a team doing a refactor of this module so we will need them to review this to ensure it doesn't cause conflicts there. Adding a do-not-merge label in the meantime.

**Comment by natalie-white-aws** [comment]
Refactor PR linked here: https://github.com/aws/aws-cdk/pull/30833

**Comment by GavinZZ** [comment]
I'm removing the `do-not-merge` label as I cross compared with the glue refactor PR and it would not cause any conflicts. While we wait for the refactor PR, it's good to merge this in to support these two new types.

**Pull request merged**
