### PR TITLE
chore(ec2): invalid Interface VPC Endpoints

### PR DESCRIPTION
**Pull request by badmintoncryer**
### Issue # (if applicable)

None

### Reason for this change

The wrong URLs were set for several Interface Endpoints, so I corrected them.

For example, when retrieving the freetier endpoint via CLI, it shows as `aws.api.{region}.freetier`, but in CDK, it was set to `com.amazonaws.{region}.freetire`.

I believe this correction might be a breaking change, but since the previous URLs likely wouldn't have allowed access anyway, I'm unsure how to proceed. Which of the following approaches would be best?

- Directly fix the incorrect URLs (the current implementation)
- Implement a feature flag
- Deprecate the existing method and implement a new one

### Description of changes

Update URL from `com.amazonaws.{region}.{service}` to `aws.api.{region}.{service}`

- freetier
- bcm-data-exports 

### Description of how you validated changes

I've executed `described-vpc-endpoint-services` CLI.

```sh
❯ aws ec2 describe-vpc-endpoint-services --filters Name=service-type,Values=Interface Name=owner,Values=amazon --region us-east-1 --query ServiceNames | grep aws.api
    "aws.api.us-east-1.bcm-data-exports",
    "aws.api.us-east-1.freetier",
    "aws.api.us-east-1.kendra-ranking",
    "aws.api.us-east-1.qbusiness",
```

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by badmintoncryer** [comment]
exemption request
I don't think this PR requires updates to the README or test files.

**Review by go-to-k — APPROVED** [review]

**Review by GavinZZ — APPROVED** [review]
Thank you for the fix!

**Comment by badmintoncryer** [comment]
@mergify update

**Comment by badmintoncryer** [comment]
@mergify update

**Comment by badmintoncryer** [comment]
@mergifyio update

**Comment by badmintoncryer** [comment]
@mergifyio refresh

**Review by GavinZZ — APPROVED** [review]

**Pull request merged**
