### PR TITLE
build: fix type checker build errors

### PR DESCRIPTION
**Pull request by eladb**
TS2531: Object is possibly 'null'

Not 100% sure why this suddenly cropped up. Anyone curious to investigate?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by costleya** [comment]
I checked the tsconfig files in the repository and looked into the latest typescript release changes. Also made sure there were no recent changes in the build image. I also looked at the most recent 2 commits in this repository and did not find anything suspicious.

So - they mystery continues...

**Comment by eladb** [comment]
@rix0rrr I checked, but couldn't find anything that looked related.

**Comment by rix0rrr** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/18f21659bb12eff534cc29f4ba2aca0ab0680f8e

**Comment by rix0rrr** [comment]
So we are on `10.x.x` of `@types/node`. To avoid this in the future we can move to `9.x.x` which seems frozen. As long as we don't need any Node 10 specific features it shouldn't matter.

**Pull request merged**
