### PR TITLE
fix(codepipeline-actions): default branch for CodeCommit is master (under feature flag)

### LINKED ISSUE #27710: codepipelineActions.CodeCommitSourceAction: Default branch is 'Master'
### Describe the bug

When creating the resource `codepipelineActions.CodeCommitSourceAction`, if `branch` is not specified, it will default to 'master'.

However, when creating a CodeCommit repository through the console, the default branch is 'main', meaning that if everything is kept as default, the pipeline will fail.

### Expected Behavior

The default branch on `codepipelineActions.CodeCommitSourceAction` should be the same as the default branch in CodeCommit

### Current Behavior

`codepipelineActions.CodeCommitSourceAction` defaults to 'master'. If defaults are used, the following error occurs in the pipeline: `The action failed because no branch named master was found in the selected AWS CodeCommit repository`

### Reproduction Steps

1. Create a codecommit repo from the console called 'testRepo'.
2. Upload at least one file through the console - this will create the default branch `main`
3. 
```
pipeline = codepipeline.Pipeline(self, "testPipeline")
sourceOutput = codepipeline.Artifact()
repo = codecommit.Repository.from_repository_name(self, "testRepo", "testRepo")
pipeline.add_stage(stage_name="Source", actions=[
    codepipelineActions.CodeCommitSourceAction(action_name="CodeCommit", repository=repo, output=sourceOutput)
])
```
4. Once CDK has deployed, observe the pipeline in the console - it will have failed.

### Possible Solution

Change the default branch in CDK from "master" to "main"

### Additional Information/Context

_No response_

### CDK CLI Version

2.100.0 (build e1b5c77)

### Framework Version

_No response_

### Node.js Version

v18.12.1

### OS

macOS 13.5.2 (22G91)

### Language

Python

### Language Version

Python 3.9.6 (default, Aug 11 2023, 19:44:49) 

### Other information

_No response_

### PR DESCRIPTION
**Pull request by daschaa**
Closes #27710.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by daschaa** [comment]
Exemption Request: I ran the integration tests and the snapshots have been changed. So I think a new integration test is not needed.

**Comment by kylelaker** [comment]
I am not sure but wouldn't this probably need a feature flag? Since a user may have deployed when the default was `master` and built their stack when that was the expectation (according to https://docs.aws.amazon.com/codecommit/latest/userguide/history.html, any stacks built prior to March 2021 or repositories created via the console/API prior to Jan 2021), I think updating this to `main` would require them to make a code change in order to continue having a functioning stack.

**Comment by daschaa** [comment]
@kylelaker Thanks for the feedback. :) I think you are right -  it would make sense to introduce a feature flag here. I'll try to implement this. 
And if one of the maintainers says that it doesn't need a feature flag after all, I can revert the changes.

**Comment by mikewrighton** [comment]
Will approve once the build is fixed.

**Review by mikewrighton — APPROVED** [review]

**Pull request merged**
