### PR TITLE
chore(cx-api): break circular dependencies

### PR DESCRIPTION
**Pull request by rix0rrr**
Use the "Declaration Merging" feature from TypeScript, combined
with the "Monkey Patching" feature from JavaScript, to break the
circular dependencies between some of the classes in this library.

These dependency cycles interfere with proper bundling by `esbuild`.

Use `madge` to validate that we don't add those cycles back. Madge
validation only happens on the `.js` files, because those are the only
ones we care about when bundling. Cyclic imports that are only used to
import type information won't actually cause `require()` cycles at
runtime, since types don't exist in JS.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by eladb — APPROVED** [review]
Would be nice to chart a course to deprecate cx-api altogether.

**Comment by iliapolo** [comment]
@rix0rrr Looks like jsii compatibility is unhappy with this...

```console
API elements with incompatible changes:
err  - METHOD @aws-cdk/cx-api.AssetManifestArtifact.fromManifest: has been removed [removed:@aws-cdk/cx-api.AssetManifestArtifact.fromManifest]
err  - METHOD @aws-cdk/cx-api.CloudArtifact.fromManifest: has been removed [removed:@aws-cdk/cx-api.CloudArtifact.fromManifest]
err  - METHOD @aws-cdk/cx-api.CloudFormationStackArtifact.fromManifest: has been removed [removed:@aws-cdk/cx-api.CloudFormationStackArtifact.fromManifest]
err  - METHOD @aws-cdk/cx-api.NestedCloudAssemblyArtifact.fromManifest: has been removed [removed:@aws-cdk/cx-api.NestedCloudAssemblyArtifact.fromManifest]
err  - METHOD @aws-cdk/cx-api.TreeCloudArtifact.fromManifest: has been removed [removed:@aws-cdk/cx-api.TreeCloudArtifact.fromManifest]
```

**Comment by iliapolo** [comment]
> I feel very comfortable not caring about this. How about you?

Yeah, I see no reason why anyone would invoke it from the child classes.. (FLW)

**Comment by iliapolo** [comment]
Oh but wait, why does it complain on:

```console
@aws-cdk/cx-api.CloudArtifact.fromManifest
```

This one should be preserved...

**Comment by rix0rrr** [comment]
Good point, I'll check.

**Pull request merged**
