### PR TITLE
feat(lambda): nodejs14.x supports inline code

### PR DESCRIPTION
**Pull request by gkaskonas**
Cloudformation now supports Inline code for NodeJS14 runtime. Updating CDK to reflect that

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by peterwoodworth** [comment]
@gkaskonas can you link to the docs where it says this? thanks

**Comment by gkaskonas** [comment]
People are saying that it is working now https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/80

**Comment by peterwoodworth** [comment]
Looks good to me, but I'll let @nija-at take a look first

**Comment by nija-at** [comment]
> People are saying that it is working now aws-cloudformation/cloudformation-coverage-roadmap#80

This is not good enough.

Can you update the [test here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/test/integ.runtime.inlinecode.ts) and run a `cdk deploy --app test/integ.runtime.inlinecode.js` to see that it succeeds?

**Review by nija-at — CHANGES_REQUESTED** [review]
Setting the status to 'request changes' to address the comment above.

**Comment by gkaskonas** [comment]
@nija-at I have added an integration test for nodejs14 runtime. 

I was able to deploy that function in my AWS account and it returned:

```
aws lambda invoke --function-name aws-cdk-lambda-runtime-inlinecod-NODEJS14X930214A3-cGZMHuS8Evt4         --profile dev --region us-east-1  std
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
giedriuskaskonas@Giedriuss-MacBook-Pro tests % cat std
"success"%
```

**Review by nija-at — APPROVED** [review]

**Pull request merged**
