### PR TITLE
chore(docs): fix invalid anchor links in DESIGN_GUIDELINES

### PR DESCRIPTION
**Pull request by ren-yamanashi**
### Issue # (if applicable)

n/A

### Description of changes

Fix invalid anchor links in [DESIGN_GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md).

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by badmintoncryer — APPROVED** [review]
Thanks!

**Review by kaizencc — DISMISSED** [review]
thanks for the eagle eyes!

**Comment by ren-yamanashi** [comment]
@kaizencc 

Thank you for the approve! It seems that the CI has failed, so should I manually updating the branch?

**Comment by badmintoncryer** [comment]
@ren-yamanashi Please comment `@mergifyio update`. When it's not working well, it fails again, but if you keep trying without giving up, it occasionally succeeds😁

**Comment by ren-yamanashi** [comment]
@badmintoncryer 

Thank you for your comment! I'll try it right away!

**Comment by ren-yamanashi** [comment]
@mergifyio update

**Comment by ren-yamanashi** [comment]
@mergifyio update

**Comment by badmintoncryer** [comment]
@ren-yamanashi I apologize for the lack of information, but it’s better to run it with some time in between!

**Comment by ren-yamanashi** [comment]
@mergifyio update

**Comment by ren-yamanashi** [comment]
@mergifyio update

**Comment by ren-yamanashi** [comment]
@Mergifyio update

**Review by moelasmar — APPROVED** [review]

**Review by moelasmar — APPROVED** [review]

**Pull request merged**
