### PR TITLE
feat(glue): Added value to PythonVersion enum

### LINKED ISSUE #21568: (glue): Add support for Glue Job Python shell 3.9
### Describe the feature

Support Glue Job Python shell 3.9, which was released recently. [(AWS blog)](https://aws.amazon.com/blogs/big-data/aws-glue-python-shell-now-supports-python-3-9-with-a-flexible-pre-loaded-environment-and-support-to-install-additional-libraries/) 

Currently according to [the doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-job-jobcommand.html), it seems CFn does not yet support Python shell with Python 3.9 though. We should wait for the doc to be updated.

### Use Case

Python 3.6 is currently available for Python shell but 3.6 itself has already reached EOL. We need Python 3.9 support.

### Proposed Solution

After CFn will support it, update [`glue.Job` construct](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-glue-alpha.Job.html).

### Other Information

_No response_

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.37.1

### Environment details (OS name and version, etc.)

n/a

### PR DESCRIPTION
**Pull request by meve**
PR to fix #21568. Extended the PythonVersion enum to include 3.9, as it already seems to be supported everywhere (CloudFormation, SDK). https://github.com/aws/aws-cdk/issues/21568#issuecomment-1219668861

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by tmokmss** [comment]
I think we should add a validation here since`3.9` should only work for `pythonshell` jobs

https://github.com/aws/aws-cdk/blob/250232116739bba482d3a6af82064e81b4d9f0bf/packages/%40aws-cdk/aws-glue/lib/job-executable.ts#L285-L293

**Comment by meve** [comment]
I have added a validation for the condition you suggested. However, I would like to point out that some of the other validations seem to be a bit off. For instance: it should be possible to create a `pythonshell` job with _any_ `GlueVersion`. However, it is not possible to do this through CDK.

**Comment by TheRealAmazonKendra** [comment]
> I have added a validation for the condition you suggested. However, I would like to point out that some of the other validations seem to be a bit off. For instance: it should be possible to create a `pythonshell` job with _any_ `GlueVersion`. However, it is not possible to do this through CDK.

Can you expand upon this and which other validations are off? We should make sure we have a ticket to get those fixed.

**Comment by meve** [comment]
So for instance this one:

https://github.com/aws/aws-cdk/blob/5cc0d3514dd6c1bedd8233ec48074257b003fed0/packages/%40aws-cdk/aws-glue/lib/job-executable.ts#L290-L292

I actually thought of fixing it also in this PR, but I also figured I might risk it being rejected. But again using an escape hatch, I just tried to create a `pythonshell` Job using any `GlueVersion` (0.9, 1.0, 2.0, 3.0). All succeeded. It seems that the GlueVersion is ignored completely by the API when a `pythonshell` job is created.

The CloudFormation documentation [0] says:
> Jobs that are created without specifying a Glue version default to Glue 0.9.

But still that seems irrelevant for `pythonshell` jobs, and that makes me think that the validation does not really make sense, as it is completely irrelevant what GlueVersion is passed when creating a `pythonshell`. Also, when I perform a GetJob call, the GlueVersion is returned nowhere if it's not specified when creating it. 

I hope this makes sense.

[0] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-glueversion

**Comment by tmokmss** [comment]
@meve So the main problem seems to be [`glueVersion`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-glue.PythonShellExecutableProps.html#glueversionspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) property is currently taken as required while in reality it is unnecessary  for python shell jobs.
How about fix it in another PR? For now I believe the only validation we need is for python version.

**Comment by meve** [comment]
@tmokmss I agree that is the problem, and I also agree with creating another PR for this. I will create one over the next few days.

What is not clear to me, is what now is left to do for the current PR.

**Comment by tmokmss** [comment]
@meve 
I guess you should fix CI before the review, [which is currently failing](https://github.com/aws/aws-cdk/runs/7917893267?check_suite_focus=true). How about updating [the sample code](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-glue-readme.html#python-shell-jobs) on README.md to use python 3.9?

> Error: Features must contain a change to a README file

Also you can refer to [this document](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request) about contributing to CDK :)

**Comment by meve** [comment]
@tmokmss Something else. So in CDK and the API, `PythonVersion.TWO` is still supported. The console however seems to have dropped support for it (e.g., it cannot display the value anymore). Deploying a job still works though, and I still can run it:

```python
import sys

print(sys.version)
```

gives:
```
2.7.18 (default, Feb 18 2021, 06:10:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

See also [here](https://docs.aws.amazon.com/glue/latest/dg/add-job-python.html).

The point I am trying to make is that I decided to add it the way I did, is to at least try to point out the use of `PythonVersion.TWO` should not be encouraged.

**Review by corymhall — APPROVED** [review]

**Pull request merged**
