### PR TITLE
feat(aws-eks): allow the use of graviton3 processors

### PR DESCRIPTION
**Pull request by gergnz**
feat: allow the use of graviton3, 7th generation processors

fixes: https://github.com/aws/aws-cdk/issues/20482

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — DISMISSED** [review]
Thank you for your contribution. Looks like we just need an integration test for this change. As @corymhall mentioned in #20498, you can just update a current one to include the new instance type.

**Comment by gergnz** [comment]
> Thank you for your contribution. Looks like we just need an integration test for this change. As @corymhall mentioned in #20498, you can just update a current one to include the new instance type.

Added integration test.

**Comment by TheRealAmazonKendra** [comment]
> > Thank you for your contribution. Looks like we just need an integration test for this change. As @corymhall mentioned in #20498, you can just update a current one to include the new instance type.
> 
> Added integration test.

Thank you for getting that added. We just need the build working and then I'm happy to approve this. Can you please take a look at the failure?

**Comment by gergnz** [comment]
> Thank you for getting that added. We just need the build working and then I'm happy to approve this. Can you please take a look at the failure?

Looks to be something not related to my change. I've merged `main` into the branch so let's see if that resolves the issue.

**Comment by gergnz** [comment]
This integration testing is failing at the same space, but it's nothing I changed. Is this an issue in main?

**Comment by gergnz** [comment]
@TheRealAmazonKendra good to go please.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
