### PR TITLE
fix(aws-cloudfront): Fix loggingConfig being ignored

### LINKED ISSUE #721: Logging property not present on creating a Cloudfront distribution using construct
I've tried passing in an empty object for log bucket as well as an S3 Bucket, but the template generated by cdk doesn't have the Logging property.
```
new cfront.CloudFrontWebDistribution(
            this.props.stack,
            'CFWebDistribution',
            {
                originConfigs: [
                    {
                        s3OriginSource: {
                            s3BucketSource: this.props.originBucket,
                            originAccessIdentity: this.props.originAccessIdentity
                        },
                        behaviors: [{ isDefaultBehavior: true }]
                    }
                ],
                loggingConfig: {}
            }
        );
```
```
new cfront.CloudFrontWebDistribution(
            this.props.stack,
            'CFWebDistribution',
            {
                originConfigs: [
                    {
                        s3OriginSource: {
                            s3BucketSource: this.props.originBucket,
                            originAccessIdentity: this.props.originAccessIdentity
                        },
                        behaviors: [{ isDefaultBehavior: true }]
                    }
                ],
                loggingConfig: {
                    bucket: this.props.logsBucket   
                }
            }
        );
```
I'm generating the template using cdk sdk (stack.toCloudformation()). This seems to be a bug.

### PR DESCRIPTION
**Pull request by ZeldoKavira**
feat(aws-s3): Add support for domainName on BucketRef instead of just Bucket

Fixes #721 

Note: I know this goes against the policy of one fix/feature/ect per PR, but the s3 feature was required to complete this PR.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by ZeldoKavira** [comment]
@eladb || @rix0rrr Cannot set a reviewer

**Comment by rix0rrr** [comment]
I was ready to approve this, but while fixing up the docstrings I noticed that the intended purpose of `bucket` being optional was that a logging bucket would be automatically created.

That still seems like desirable behavior to me, so can you make that work? It involves new'ing up an `s3.Bucket()` on the spot if it happens that the bucket is unset. Probably makes sense to expose `loggingBucket?: s3.BucketRef` as a public attribute as well, so consumers can access the bucket object afterwards.

**Comment by rix0rrr** [comment]
Oh and apparently I broke something. Sorry! 👀

**Comment by ZeldoKavira** [comment]
I will take a look at the auto generation!

**Comment by ZeldoKavira** [comment]
@rix0rrr All set on that change!

**Comment by ZeldoKavira** [comment]
@rix0rrr Fixed merge issue from the other PR being accepted

**Comment by ZeldoKavira** [comment]
I messed up and overlooked export(), reverting to a different branch to keep the commits clean

**Pull request closed without merging**
