### PR TITLE
chore(dynamodb): migrate tests to assertions

### PR DESCRIPTION
**Pull request by robertd**
Depends on #18577 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
I'm not sure how to migrate `SynthUtils.toCloudFormation(stack).Conditions`... I don't think `assertions` has `Conditions` matcher.

cc @kaizen3031593 Would you mind chiming in on this one? (I've been following your recent `assertion` migration commits). TIA.

**Comment by robertd** [comment]
> I don't think assertions [package] has conditions matcher.

I just created MR for this...  #18577

**Comment by otaviomacedo** [comment]
Thanks, @robertd. I'll just wait for #18577 to be merged to approve this one.

**Comment by robertd** [comment]
Thanks @otaviomacedo. I just updated this PR with latest changes from the master branch since #18577 just got merged in. Thanks in advance. ✌️

**Review by otaviomacedo — APPROVED** [review]

**Pull request merged**
