### PR TITLE
chore(integ-runner): revert integ runner change that limits to run javascript tests

### PR DESCRIPTION
**Pull request by GavinZZ**
After this PR change, https://github.com/aws/aws-cdk/pull/28770, integ-runner doesn't work anymore when specifying test files, i.e. yarn integ test/aws-apigatewayv2-integrations/test/websocket/integ.aws.t --update-on-failed.

Closes https://github.com/aws/aws-cdk/issues/28890

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by GavinZZ** [comment]
Exemption Request: No integ test is needed since it reverting it back to the original state.

**Review by ConnorRobertson — APPROVED** [review]

**Comment by mrgrain** [comment]
@mergifyio update

**Comment by GavinZZ** [comment]
@Mergifyio update

**Comment by mrgrain** [comment]
https://github.com/Mergifyio update

**Pull request merged**
