### PR TITLE
feat(aws-autoscaling): Support a external LaunchConfiguration and LaunchTemplate to AutoScalingGroup

### LINKED ISSUE #1403: AutoScaling: Support a external LaunchConfiguration and LaunchTemplate to AutoScalingGroup
I want to use custom LaunchConfiguration in AutoScalingGroup library.
For example, when to use a spot instance.

### PR DESCRIPTION
**Pull request by cohalz**
Fixed #1403
----

### Pull Request Checklist

Please check all boxes, including N/A items:

#### Testing

- [x] Unit test and/or integration test added
- [x] __Toolkit change?:__ [integration tests](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/integ-tests/test.sh) manually executed (paste output to the PR description)
- [x] __Init template change?:__ coordinated update of integration tests (currently maintained in a private repo).

#### Documentation

- [x] __README__: README and/or documentation topic updated
- [x] __jsdocs__: All public APIs documented

### Title and description

- [x] __Change type__: Title is prefixed with change type:
  * `fix(module): <title>` bug fix (_patch_)
  * `feat(module): <title>` feature/capability (_minor_)
  * `chore(module): <title> ` won't appear in changelog
  * `build(module): <title>` won't appear in changelog
- [x] __Title format__: Title uses lower case and doesn't end with a period
- [x] __Breaking change?__: Last paragraph of description is: `BREAKING CHANGE: <describe exactly what changed and how to achieve similar behavior + link to documentation/gist/issue if more details are required>`
- [x] __References__: Indicate issues fixed via: `Fixes #xxx` or `Closes #xxx`

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by eladb** [comment]
@cohalz this is awesome, but we generally avoid "leaking" the Cfn classes in the API of AWS constructs. Granted, this is a large surface area to cover, but also an opportunity to actually provide a lot of value to users.

As a workaround, users can use [property overrides](https://awslabs.github.io/aws-cdk/aws-construct-lib.html#access-the-aws-cloudformation-layer), so I hope you are not blocked by this. 

Let me know if you wish to take this to the next level. It's not a small project, I am aware 😄

**Comment by cohalz** [comment]
@eladb I want to use ECS Construct Library with spot instances, but AutoScalingGroup does not support LaunchTemplate. Also, InstanceDrainHook does not exported, so I need to describe too long Resources to construct cluster.

So, I added #1331 and this PR.

**Comment by cohalz** [comment]
I tried this code.

```typescript
const asgResource = asg.findChild('ASG') as autoscaling.cloudformation.AutoScalingGroupResource

asgResource.addPropertyDeletionOverride('LaunchConfigurationName')
asgResource.addPropertyOverride('LaunchTemplate', {
  LaunchTemplateId: appLaunchTemplate.ref,
  Version: '1'
})
```

It's working, but `AWS::AutoScaling::LaunchConfiguration` will be created uselessly.

**Comment by rix0rrr** [comment]
I agree we should either limit the scope of this change, or implement a proper Launch Configuration construct.

**Comment by eladb** [comment]
@cohalz closing for now. Feel free to reopen when/if you wish to continue this work.

**Comment by LeifW** [comment]
Would this be worth revisiting now that we have https://github.com/aws/aws-cdk/pull/12385 ?

**Pull request closed without merging**
