### PR TITLE
feat(ecs-patterns): Add support for taskSubnets and securityGroups  on QueueProcessingFagateService

### LINKED ISSUE #12603: (ecs-patterns): Add support to define specific subnets and security groups on QueueProcessingFargateService construct
Add support to define specific subnets and security groups on QueueProcessingFargateService.

### Use Case

I want to be able to specific subnets and security groups for my Fargate service on QueueProcessingFargateService construct. 

Example: Allow better security posture with isolated subnets and specific security groups.

### Proposed Solution

```ts
  const queueProcessingService = new QueueProcessingFargateService(stack, 'queue-processing', {
        vpc,
        image: ContainerImage.fromDockerImageAsset(dockerImage),
        taskSubnets: { subnetType: ec2.SubnetType.ISOLATED },
        securityGroups: [securityGroup]
    });
```

### Other

Current work around:

```ts
  const queueProcessingService = new QueueProcessingFargateService(stack, 'queue-processing', {
        vpc,
        image: ContainerImage.fromDockerImageAsset(dockerImage),
    });
    const cfnService = queueProcessingService.service.node.children[0] as ecs.CfnService;
    cfnService.networkConfiguration = {
        awsvpcConfiguration: {
            assignPublicIp: 'DISABLED',
            subnets: vpc.isolatedSubnets.map(s => s.subnetId),
            securityGroups: [securityGroup.securityGroupId]
        }
    };
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by lgvo**
Fixes #12603 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by lgvo** [comment]
Tested the construct with and without the new options using the new (added) integ tests. Created the stacks and validated that the service was consuming the messages from the queue.

**Review by SoManyHs — APPROVED** [review]
LGTM! 🎉 Thanks so much for contributing!!

**Comment by SoManyHs** [comment]
@mergifyio update

**Comment by SoManyHs** [comment]
@mergifyio update

**Comment by SoManyHs** [comment]
@mergifyio update

**Review by SoManyHs — APPROVED** [review]

**Pull request merged**
