### PR TITLE
docs(lambda): Use bundlingImage rather than bundlingDockerImage

### PR DESCRIPTION
**Pull request by michaelbrewer**
Resolves https://github.com/aws/aws-cdk/issues/13944
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
Runtimes still expose a `bundlingDockerImage` property, no?

**Comment by michaelbrewer** [comment]
> bundlingDockerImage

This actually does not work either.

**Comment by michaelbrewer** [comment]
@jogold  if i use `bundlingDockerImage` i get a casting error in Java. and if `bundlingImage` it does not actually deploy the code.

**Comment by michaelbrewer** [comment]
> Runtimes still expose a `bundlingDockerImage` property, no?
> 
> https://github.com/aws/aws-cdk/blob/767cd31c2b66b48b3b8fed7cd8d408a6846cf1e1/packages/%40aws-cdk/aws-lambda/lib/runtime.ts#L14



Yes, it does but with typed languages you now have to force a cast:

ie: `(Runtime.PYTHON_3_8.bundlingDockerImage as DockerImage?`

And the deprecation warning suggests you should use `bundlingImage`, which does not actually work.

Below is a working example using the now deprecated `bundlingDockerImage` 

```kotlin
        val function = Function(
            this,
            "loan${type.capitalize()}Function",
            FunctionProps
                .builder()
                .functionName("loanDevl")
                .handler("loan.app.lambda_handler")
                .runtime(Runtime.PYTHON_3_8)
                .code(
                    Code.fromAsset(
                        "../../src/",
                        AssetOptions
                            .builder()
                            .bundling(
                                BundlingOptions
                                    .builder()
                                    .image(Runtime.PYTHON_3_8.bundlingDockerImage as DockerImage?)
                                    .command(
                                        mutableListOf(
                                            "bash",
                                            "-c",
                                            "pip install -r requirements.txt -t /asset-output && cp -au . /asset-output"
                                        )
                                    )
                                    .build()
                            )
                            .build()
                    )
                )
                .build()
        )
```

**Comment by michaelbrewer** [comment]
Seems like these changes are current, I just an issue when running my unit tests and then run the a `cdk deploy`

**Comment by jogold** [comment]
> And the deprecation warning suggests you should use `bundlingImage`

you're right!

**Comment by michaelbrewer** [comment]
> > And the deprecation warning suggests you should use `bundlingImage`
> 
> 
> 
> you're right!

And this would also trigger a compilation error on Java / Kotlin (and i am sure other languages). 

What was confusing for me was when i switched `bundlingImage` switch, it did not properly deployed. It turned out that you need to delete the `cdk.out` folder if a build fails, otherwise it just uploads the directory specified, but without the dependencies. I am sure there is another issue for that to?

**Comment by michaelbrewer** [comment]
Note @nija-at this causes compile errors in Java runtime

**Comment by michaelbrewer** [comment]
@nija-at  will this be merged? It was a time sink for me when I came across this documentation error.

**Review by nija-at — DISMISSED** [review]

**Comment by michaelbrewer** [comment]
@nija-at  mergify is just hanging now?

**Comment by michaelbrewer** [comment]
@nija-at @mergify  is not working for me. And this is a PR from my personal github account

Screen Shot 2021-04-15 at 1 18 19 AM

**Comment by nija-at** [comment]
@michaelbrewer - we're having trouble with Mergify across the repo since yesterday. We will get this merged eventually.

**Review by nija-at — APPROVED** [review]

**Pull request merged**
