### PR TITLE
feat(aws-codestarnotifications): added codecommit repository as source for notification rule

### PR DESCRIPTION
**Pull request by badfun**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by skinny85 — DISMISSED** [review]
@badfun thanks for the contribution, but I think there's been some misunderstanding 🙂.

What we need to do here is to extend the `INotificationRuleSource` interface in the CodeCommit's `IRepository` interface. Similarly like [it's done for CodeBuild](https://github.com/aws/aws-cdk/blob/464cdc0baa1fc5b0634e428a9c7a15de4ca93d50/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L52-L52), for example.

Let me know if this is clear now!

Thanks,
Adam

**Comment by skinny85** [comment]
Maybe looking at the original PR that added this functionality will be helpful: https://github.com/aws/aws-cdk/pull/10833

**Comment by badfun** [comment]
Ah. Okay thanks Adam. I will take a look at that.
Ken

**Comment by badfun** [comment]
switching to local dev and will re-open when I get it all working.

**Comment by luckily** [comment]
> _By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license_

Your pull request message should indicate which issues are fixed: `fixes #<issue>` or `closes #<issue>`.

Reference [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#step-4-pull-request).

**Pull request closed without merging**
