### PR TITLE
chore(prlint): don't mark PRs as 'not ready' on community comment

### PR DESCRIPTION
**Pull request by laurelmay**
Community reviewers have the ability to choose any of the
approve/comment/request changes buttons that are available in the review
tab. Prior to this change, `prlint` would consider a comment from a
community reviewer as being equivalent to requesting changes (and in
fact, didn't consider the requesting changes case). This would remove
the `pr/needs-community-review` label which surprised some reviewers.

With this change, `prlint` will only remove the
`pr/needs-community-review` label when a community reviewer specifically
chooses "request changes". Additionally, reviewers are now able to
switch from approving to requesting changes (this doesn't override any
other reviewers' approvals, just that reviewer's own).

Additionally, this adds mocks for the `getTrustedCommunityMembers`
method and avoids hardcoding the logins of multiple community reviewers
into the tests. As a side effect, the tests also run faster since `curl`
isn't being invoked so frequently.

Here is a screenshot of what I see when reviewing on this repo:
image

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by kylelaker** [comment]
It also seems unnecessary to filter out reviews from the PR author as GitHub already doesn't allow self-approvals or self-requests (though you can comment). Here is what I see on _this_ PR's review tab:

image

**Comment by kylelaker** [comment]
For an example of a community member requesting changes, see https://github.com/aws/aws-cdk/pull/27744#pullrequestreview-1704173268. Even though GitHub shows it as "suggested changes", the API `state` field is still `CHANGES_REQUESTED`. https://api.github.com/repos/aws/aws-cdk/pulls/27744/reviews

**Review by go-to-k — APPROVED** [review]
Great! Thank you for addressing this matter.

**Review by vinayak-kukreja — APPROVED** [review]
Hey, this is great. Thank you for contributing this 🙌

**Pull request merged**
