### PR TITLE
feat(core): add creation policy configuration for appstream

### LINKED ISSUE #23604: (core): (creation policy missing for AWS::AppStream::Fleet)
### Describe the bug

```
{
    "CreationPolicy": {
        "StartFleet": {
            "Type": "Boolean"
        }
    }
}
```
is cannot be set

### Expected Behavior

CreationPolicy be able to set for an Appstream Resource

### Current Behavior

Not supported

### Reproduction Steps

n/a

### Possible Solution

_No response_

### Additional Information/Context

see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html

### CDK CLI Version

2.59.0

### Framework Version

_No response_

### Node.js Version

v19

### OS

mac (all)

### Language

Typescript, Python

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Jacco**
Fixes #23604 

I have:
- added startFleet to CfnCreationPolicy, including doc remarks for the property and the class.
- added a unit test to test wether it is rendered correctly in the CloudFormation template.
- added and ran an intergrity test in aws-appstream to verify that the Fleet is actually started.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Jacco** [comment]
I see the text: 'This branch is out-of-date with the base branch'. Should I fix that on my branch in my fork or use the "Update branch" button here (and do I rebase or merge)?

**Comment by Jacco** [comment]
@TheRealAmazonKendra is it ok to ping for a review? Its just a few lines of code an adjusted test and an integration test :-)

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
This is more of a feat than a fix since it's adding new functionality. The PR Linter is going to fail due to a missing README update. Is there a place in the readme where it makes sense to add documentation about this prop?

**Comment by Jacco** [comment]
@TheRealAmazonKendra I added some documentation about the use of the CfnOptions and startFleet in particular.

**Comment by Jacco** [comment]
@TheRealAmazonKendra 

Last time the build failed with the error:
`aws-cdk-lib: - [package-info/README.md/aws-cdk-lib-and-core] aws-cdk-lib README does not include a core documentation section that matches @aws-cdk/core (fixable)`

I am not sure how to fix that. Hopefully this build it is fixed. I removed an import from a code sample.

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra
> 
> Last time the build failed with the error: `aws-cdk-lib: - [package-info/README.md/aws-cdk-lib-and-core] aws-cdk-lib README does not include a core documentation section that matches @aws-cdk/core (fixable)`
> 
> I am not sure how to fix that. Hopefully this build it is fixed. I removed an import from a code sample.

This is one of our annoying problems with the package structure. Sorry, I forgot to mention it before. You'll just need to paste the same changes into the README for the aws-cdk-lib.

**Comment by Jacco** [comment]
What also worked is do a `yarn pkglint` in the `aws-cdk-lib` which does the copy pasting for you.

(I invoked it after a `yarn build` of that dir though, which is probably also necessary)

@TheRealAmazonKendra can the PR be reviewed now?

This is the most trouble I went through for a **one** line change of functional code :-)

```ts
readonly startFleet?: boolean;
```

**Comment by TheRealAmazonKendra** [comment]
> What also worked is do a `yarn pkglint` in the `aws-cdk-lib` which does the copy pasting for you.
> 
> (I invoked it after a `yarn build` of that dir though, which is probably also necessary)
> 
> @TheRealAmazonKendra can the PR be reviewed now?
> 
> This is the most trouble I went through for a **one** line change of functional code :-)
> 
> ```ts
> readonly startFleet?: boolean;
> ```

Just me being embarrassed that I didn't know that...

Taking a look :)

**Review by TheRealAmazonKendra — DISMISSED** [review]
Looks good!

**Comment by Jacco** [comment]
@TheRealAmazonKendra thanks for the review :-)

Now in the workflow there is an error preventing merging from succeeding.

The step: "Queue: Embarked in merge train" has an error.

It says:

```
The merge queue pull request can't be updated
Details:

Base branch update has failed

refusing to allow a GitHub App to create or update workflow .github/workflows/github-merit-badger.yml without workflows permission
err-code: C3996
```

Looking through some documentation I found that this checkbox should be enab;ed "Allow edits and access to secrets by maintainers" which it already it.

Also looked at the settings of my fork but can't find anything wrong there either.

**Comment by Jacco** [comment]
@Mergifyio update

**Comment by Jacco** [comment]
@TheRealAmazonKendra saw you do the above in another PR hoped it would work

**Comment by TheRealAmazonKendra** [comment]
Mergify:

**Comment by TheRealAmazonKendra** [comment]
@Jacco That usually is the right thing to do, though.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Comment by Jacco** [comment]
@TheRealAmazonKendra I think this was released not in 2.61.1 but I do not see any reference in the release notes

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra I think this was released not in 2.61.1 but I do not see any reference in the release notes

This was merged too late to make it into a release. Patch releases only contain the changes required to fix the p0 bug.

**Pull request merged**
