### PR TITLE
refactor(sdk): introduce generic function to instantiate a service

### PR DESCRIPTION
**Pull request by duarten**
aws-sdk services are created in a uniform fashion, so introduce a generic function instead of repeating code.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by duarten** [comment]
Should it not be externally exported then?

Basically, I want to avoid depending directly on aws-sdk, but fetch the current user’s name. The goal is then to prefix each construct’s name with it, thus allows multiple developers to have their own envs using a single account.

**Comment by rix0rrr** [comment]
It should not be externally exported, but more generally you shouldn't be importing `aws-cdk` into your CDK app at all. The fact that you currently can is an oversight on our part, I would say.

**Comment by duarten** [comment]
Fair enough. Do you want me to drop the patch exposing IAM and keep only
the refactoring, or drop the whole PR?

**Comment by rix0rrr** [comment]
I'd still like to take the refactoring if you don't mind, yes. I like it a lot :)

**Comment by duarten** [comment]
Updated :)

**Comment by duarten** [comment]
It seems impossible to get this merged :(

**Comment by rix0rrr** [comment]
> It seems impossible to get this merged :(

Please don't manually merge from master. It will take away the approval. The bot will take care of it.

**Comment by rix0rrr** [comment]
Aha you may have disabled the permissions for project owners to push changes to your branch. 

> Pull request can't be updated with latest base branch changes, owner doesn't allow modification

That is going to be tricky then. There should be a checkbox on your PR somewhere to enable this.

**Comment by duarten** [comment]
For some reason, the checkbox described [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) is not showing for me, which I guess has something to do with the fork being in an organization.

I guess I'll create an individual fork, for the sake of future PRs as well.

**Comment by duarten** [comment]
https://github.com/aws/aws-cdk/pull/6171

**Pull request closed without merging**
