### PR TITLE
fix(opensearchservice): support r7gd, i4i and i4g in aws_opensearchservice

### PR DESCRIPTION
**Pull request by sharp-pixel**
### Issue # (if applicable)

Closes #<issue number here>.

### Reason for this change

R7GD, I4I and I4G have instance storage and do not support EBS. However there is a list in aws_opensearchservice with allowlisted values to support instances with no EBS.

### Description of changes

This pull requests updates the checks made on instance type without EBS to include i4i, i4g and r7gd.
Also fixed some deprecations.

### Description of how you validated changes

Deployed an OpenSearch domain with r7gd using modified version of CDK, + unit tests.

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Battleroid** [comment]
Any idea when this might be merged?

**Comment by moelasmar** [comment]
@Battleroid could you please help the team by reviewing this PR. Our team prioritize the PRs that are already reviewed by the community.

**Review by fidelisojeah — APPROVED** [review]

**Review by mazyu36 — COMMENTED** [review]
Thank you for the contribution.

I left a minor comment.

**Comment by sharp-pixel** [comment]
Some of this has already been merged. Closing this one.

**Pull request closed without merging**
