### PR TITLE
feat(iot-actions): add support for DynamoDBv2 rule

### LINKED ISSUE #20162: (iot-actions) Add support for the dynamodbv2 action
### Describe the feature

AWS CDK has no support for the dynamoDBv2 riot rule action.

### Use Case

I am working on implementing a solution that requires this rule. Using couldformation resources would be possible, but adding in support would be a lot easier.

### Proposed Solution

It seems like this would be a small addition with a low effort. There are already similar rules implemented.

It would add a rule called `DynamoDBv2PutAction` that takes a `dynamodb.ITable` as argument.

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.20

### Environment details (OS name and version, etc.)

windows 10

### PR DESCRIPTION
**Pull request by bobveringa**
This merge request adds the dynamodbv2 IoT rule action as a new feature. This rule is useful for quickly logging device information into DynamoDB. Furthermore, it adds some other important functionality as IoT action.

Closes #20162

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by bobveringa** [comment]
The build failed due to a bug I had already noticed and resolved (I think), but the last commit was not used for the build. I merged master into my branch to trigger the build process again. This should include the latest commit in which I resolved the issue.

**Comment by bobveringa** [comment]
Is there any additional work I need to do for this PR?

**Review by yamatatsu — COMMENTED** [review]
@bobveringa Thank you to work for this issue!
I propose some small changes 😄 .

**Review by yamatatsu — APPROVED** [review]
Thank you for addressing my proposes! 😍 And sorry for my late reaction.
Once, I propose minor changes based on my experience of contributions to make smooth the review of the core maintainer. And I hope this PR will be merged 😌.

**Comment by daschaa** [comment]
@bobveringa Did you do any progress on this one ? :)

**Comment by bobveringa** [comment]
I have not yet have had the time to integrate this feedback. And due to the lack of interest from any maintainers or communication at all, I have not really been motivated to work on this solution. For our own project, we have figured out a way around it.

In general, I found the complete lack of communication very discouraging, and I have matters to work on that people are actually interested in.

**Comment by daschaa** [comment]
@bobveringa I'm really sorry to hear that you feel like nothing has happened here. It would be cool if you could still look at/resolve proposed adjustments. I guess the CDK just waited for your response on the suggestions. 
Would be cool if you could take a look ❤️

**Comment by bobveringa** [comment]
I've added an item to look at this next sprint. 

However, given this experience, it is unlikely that we will contribute changes in the feature. After 2 months, I feel like someone could have spent 30 seconds leaving a comment that changes are needed.

**Review by TheRealAmazonKendra — DISMISSED** [review]
@bobveringa On behalf of the team, I apologize for your experience submitting the PR and the radio silence on our end. The quality of this change is precisely what I look for when I'm reviewing so I sincerely hope that you'll continue contributing in the future.

Besides the comment below about the name of the file, I will just +1 the suggested changes by @yamatatsu. Everything else looks great.

**Comment by bobveringa** [comment]
I am not certain why this build is failing. The logs don't really help narrow it down. I'll investigate this once I have more time to work on it. If anyone has a clue why this started failing, please let me know.

**Comment by TheRealAmazonKendra** [comment]
> I am not certain why this build is failing. The logs don't really help narrow it down. I'll investigate this once I have more time to work on it. If anyone has a clue why this started failing, please let me know.

Looks like it was just that the name of the file in the exports didn't get updated. I added that fix.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Looks like the names of the files aren't consistent. Could you please update those and then I think this looks good to go.

**Comment by bobveringa** [comment]
> Looks like the names of the files aren't consistent. Could you please update those and then I think this looks good to go.

Do you mean the filename of the code and the filenames for the tests?

**Comment by TheRealAmazonKendra** [comment]
> > Looks like the names of the files aren't consistent. Could you please update those and then I think this looks good to go.
> 
> Do you mean the filename of the code and the filenames for the tests?

The tests. I also just noticed that the integ test isn't using our [integ test construct](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md) so it's not actually testing against the expected output. Apologies for not noticing that sooner.

**Comment by bobveringa** [comment]
> > > Looks like the names of the files aren't consistent. Could you please update those and then I think this looks good to go.
> > 
> > 
> > Do you mean the filename of the code and the filenames for the tests?
> 
> The tests. I also just noticed that the integ test isn't using our [integ test construct](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md) so it's not actually testing against the expected output. Apologies for not noticing that sooner.

I'll make this change. In addition someone should update the other tests, as none of them use the integ test construct.

**Comment by bobveringa** [comment]
I think that should be all the changes. Please let me know if there is any more work that needs to be done for this issue.

**Comment by TheRealAmazonKendra** [comment]
@Mergify update

**Comment by TheRealAmazonKendra** [comment]
Looks like the update wasn't quite right but I'm going to go ahead and update them since it will only take me a second. You're also right about us needing to update the other tests. We're slowly but surely making our way through those updates.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — APPROVED** [review]
As long as this build succeeds, I think this is good to go!

**Comment by bobveringa** [comment]
Alright, thank you very much for resolving that issue.

**Pull request merged**
