### PR TITLE
feat(cli): exposed synth's quiet option in cdk.json

### LINKED ISSUE #24251: aws-cdk / cli: option to have the `synth`'s `--quiet` option exposed in `cdk.json`
### Describe the feature

The vast majority of the time when running `cdk synth` we don't want the template to be written -- I can't think of a time when I _do_ want it to be written...

Whilst the `--quiet` option can be added to the command line, it would be nice to be able to specify this in any of the `cdk.json` files

### Use Case

When running `cdk synth`, the output is written to the `cdk.out/` folder, and this is generally what I look at when I want to view the CF Templates, etc.  On the console I really only want to be seeing the warnings and errors, never the template.

Adding `--quiet` each and every time I want to synth is cumbersome, often forgotten (which could mean scrolling back several hundred lines to see any other outputs), and is additional characters to have to type each and every time.

### Proposed Solution

Either a
```
"quiet": true
```
or
```
"synthesize": {
    "quiet": true
}
```
in the cdk.json, picked up in any of the files (personally I'd add it to `~/.cdk.json`).

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.65.0

### Environment details (OS name and version, etc.)

MacOS, although the feature would be for all OSes.

### PR DESCRIPTION
**Pull request by lpizzinidev**
The `quiet` option for `synth` can now be specified in `cdk.json` as:
```
{
  "quiet": true
}
```

Closes #24251

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by lpizzinidev** [comment]
Exemption Request.

Integration test added in [cli.integtest.ts](https://github.com/aws/aws-cdk/pull/24793/files#diff-eca84019bfd672acb376d98f398b27ef18f06ef7ab298854216333cc20c00e38).
The linter is not recognizing that file as valid integration test.

**Comment by TheRealAmazonKendra** [comment]
> Exemption Request.
> 
> Integration test added in [cli.integtest.ts](https://github.com/aws/aws-cdk/pull/24793/files#diff-eca84019bfd672acb376d98f398b27ef18f06ef7ab298854216333cc20c00e38). The linter is not recognizing that file as valid integration test.

We need to fix this. In the meantime, I'm adding the exemption here and will be running this through our integ test pipeline.

**Comment by TheRealAmazonKendra** [comment]
I just realized that the original version of this PR was closed due to staleness and that was totally on me. I had assigned it to myself, essentially telling my teammates that I had it covered and then ended up being unexpectedly out of the office for a few weeks. I apologize for that experience as a contributor. It was totally my fault.

**Comment by TheRealAmazonKendra** [comment]
@Merfigyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — APPROVED** [review]
Approving pending test run success. Will add the label to update the PR linter at that time.

**Comment by TheRealAmazonKendra** [comment]
The test added in this code passed but other tests failed. I suspect that the failures weren't actually related so I'm retrying.

Test output below:
```
FAIL cli_integ/tests/cli-integ-tests/cli.integtest.js (1343.15 s)
--
896 | ✓ VPC Lookup (1015541 ms)
897 | ✓ Construct with builtin Lambda function
898 | ✓ Stage with bundled Lambda function (96831 ms)
899 | ✓ Two ways of showing the version
900 | ✓ Termination protection
901 | ✓ cdk synth
902 | ✓ ssm parameter provider error
903 | ✓ automatic ordering
904 | ✓ automatic ordering with concurrency
905 | ✓ --exclusively selects only selected stack
906 | ✓ context setting
907 | ✓ context in stage propagates to top
908 | ✓ deploy
909 | ✓ deploy --method=direct
910 | ✓ deploy all
911 | ✓ deploy all concurrently
912 | ✓ nested stack with parameters
913 | ✓ deploy without execute a named change set
914 | ✓ security related changes without a CLI are expected to fail
915 | ✓ deploy wildcard with outputs
916 | ✓ deploy with parameters
917 | ✓ update to stack in ROLLBACK_COMPLETE state will delete stack and create a new one
918 | ✓ stack in UPDATE_ROLLBACK_COMPLETE state can be updated
919 | ✓ deploy with wildcard and parameters (1 ms)
920 | ✓ deploy with parameters multi
921 | ✓ deploy with notification ARN
922 | ✓ deploy with role
923 | ✓ cdk diff
924 | ✓ enableDiffNoFail
925 | ✓ cdk diff --fail on multiple stacks exits with error if any of the stacks contains a diff (17782 ms)
926 | ✓ cdk diff --fail with multiple stack exits with if any of the stacks contains a diff
927 | ✓ cdk diff --security-only --fail exits when security changes are present
928 | ✓ deploy stack with docker asset
929 | ✓ deploy and test stack with lambda asset
930 | ✓ cdk ls
931 | ✓ synthing a stage with errors leads to failure
932 | ✓ synthing a stage with errors can be suppressed
933 | ✓ synth --quiet can be specified in cdk.json (1 ms)
934 | ✓ deploy stack without resource
935 | ✓ IAM diff
936 | ✓ fast deploy
937 | ✓ failed deploy does not hang
938 | ✓ can still load old assemblies
939 | ✓ generating and loading assembly
940 | ✓ templates on disk contain metadata resource, also in nested assemblies
941 | ✕ CDK synth add the metadata properties expected by sam
942 | ✕ CDK synth bundled functions as expected
943 | ✕ sam can locally test the synthesized cdk application
944 | ✓ skips notice refresh
945 | ✓ test resource import (17636 ms)
946 | ✓ hotswap deployment supports Lambda function's description and environment variables (80565 ms)
```

**Comment by TheRealAmazonKendra** [comment]
Upon second glance I see that these tests are failing elsewhere too. Putting this on pause until we get those resolved.

**Comment by TheRealAmazonKendra** [comment]
Looks like yesterday's issue is resolved. Re-running the tests now.

**Comment by lpizzinidev** [comment]
> I just realized that the original version of this PR was closed due to staleness and that was totally on me. I had assigned it to myself, essentially telling my teammates that I had it covered and then ended up being unexpectedly out of the office for a few weeks. I apologize for that experience as a contributor. It was totally my fault.

@TheRealAmazonKendra 
Thanks for the feedback and the merge. 
No problem with the delay 👍

**Comment by gburke-ppb** [comment]
Cool.  Thank you for this!

**Pull request merged**
