### PR TITLE
fix: Default username in RoleSessionName

### LINKED ISSUE #19401: (api/aws-auth): Error on CDK commands when user does not exist
### What is the problem?

In some cases (i.e. Docker container) a system user might not be in `/etc/passwd` file. It causes `cdk diff` (for example) to fail.

### Reproduction Steps

For any CDK project run cli via docker container that has newly created user. for example:
```sh
docker run --rm -v `pwd`:/usr/src/app -w /usr/src/app -u 1001 -e NO_UPDATE_NOTIFIER=1 -e npm_config_cache=/tmp -e CDK_HOME=/tmp -v ~/.aws:/.aws node:14 npm run cdk diff
```

### What did you expect to happen?

By looking at code of `safeUsername()` function it's just used  as part of `RoleSessionName` name. It could have a nice fallback to i.e. `$USER` env var or just predefined default value. The function is very simple:
```js
function safeUsername() {
    return os.userInfo().username.replace(/[^\w+=,.@-]/g, '@');
}
```

### What actually happened?

It causes `cdk diff` (for example) to fail with following stack trace:
```
Stack EksCdkStack
Reading existing template for stack EksCdkStack.
Retrieved account ID xxx from disk cache
Assuming role 'arn:aws:iam::xxx:role/cdk-hnb659fds-lookup-role-xxx-eu-west-1'.
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at new SystemError (internal/errors.js:217:5)
    at new NodeError (internal/errors.js:302:7)
    at Object.userInfo (os.js:347:11)
    at safeUsername (/usr/src/app/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:462:13)
    at SdkProvider.withAssumedRole (/usr/src/app/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:348:37)
    at SdkProvider.forEnvironment (/usr/src/app/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:189:28)
```

### CDK CLI Version

2.10.0 (build e5b301f)

### Framework Version

_No response_

### Node.js Version

v14.19.0

### OS

Ubuntu 20.04

### Language

Typescript

### Language Version

_No response_

### Other information

I can contribute PR if you wish. Any hints of fallback value are appreciated :)

### PR DESCRIPTION
**Pull request by adambro**
In case user does not have entry in `/etc/passwd` the `os.userInfo()`
call will throw `SystemError` exception as documented:
https://nodejs.org/docs/latest-v16.x/api/os.html#osuserinfooptions

Fixes #19401 issue.

It can be tested inside Docker for ad-hoc 1234 user ID:
```sh
docker run -u 1234 -e CDK_HOME=/tmp npm run cdk diff
```

The `CDK_HOME=/tmp` is a workaround for #7937 issue, where CDK complains
that it can't write cached info in user homedir, because it does not
exists.

Once #7937 will be fixed then #19401 will most likely hit users. However
above workaround is a viable option. Hence those two issues are related,
but not duplicated.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

Yes, followed the guide.

### Adding new Unconventional Dependencies:

* [x] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

No new dependencies.

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

No, it's a bugfix, not a feature.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by adambro** [comment]
Linter is  complaining about missing change in test file. I can add superficial test for this helper function, but it's not going to be useful.

**Comment by adambro** [comment]
The code change I've done is just basically handling `SystemError` exception and returning a sane default value (instead of unhandled error) when it happens. Pretty straightforward to review.

**Review by comcalvi — DISMISSED** [review]

**Comment by adambro** [comment]
@comcalvi thanks for review and approve. Can you disable lint rule for missing test, please? I don’t think the test will provide any value here. It seems the the outstanding thing to do here.

**Review by comcalvi — CHANGES_REQUESTED** [review]
could you actually a test for this? I'd like to see one that verifies that `noname` is used when that call throws an error.

**Comment by adambro** [comment]
@comcalvi I've added a test case for one of the functions, because test structure was already there and it was fairly straightforward. Check out the 4ae946b commit, please :)

**Review by comcalvi — APPROVED** [review]

**Pull request merged**
