### PR TITLE
feat(eks): Windows nodes support

### LINKED ISSUE #4435: EKS Windows Server image support
### Use Case

EKS Windows image support was [just added](https://aws.amazon.com/blogs/aws/amazon-eks-windows-container-support-now-generally-available/), and it's possible to retrieve the [images through SSM](https://docs.aws.amazon.com/eks/latest/userguide/retrieve-windows-ami-id.html), like it is with Amazon Linux 2 now.

### Proposed Solution

Extend `EksOptimizedImage` to support Windows images

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by nmussy**
TODO:

* [x] throw in `addWindowsCapacity` if version < 1.14
* [x] throw if instance type in `C3, C4, D2, I2, M4 (excluding m4.16xlarge), R3`
* [x] revert `defaultCapacityOperatingSystem` field
* [ ] [Enable Windows support](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html) if cluster contains Windows nodes
* [ ] Error and user guidance if only Windows nodes in cluster
* [ ] Unit tests, integration
* [ ] Update `bump_kube.sh` to update new unit tests
* [ ] JSDocs, README

--- 

Lots of deprecations, but on the image side, it's the same as Linux, with Core/Full and without GPU images.

I also haven't looked into the changes to get a Windows cluster working, but it seems like there still needs to be a Linux node [according to the blog](https://aws.amazon.com/blogs/aws/amazon-eks-windows-container-support-now-generally-available/):

> Currently, at least one Linux node is required to support Windows node and pod networking

I'll look into it before writing the integration tests.

`bump_kube.sh` will need to be updated to handle the new SSM integ values

Fixes #4435 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nmussy** [comment]
Hey @eladb,

Looking at [the guide](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html), it looks like `eksctl` does a lot of the heavy lifting to add Windows support to the cluster, when you compare it to the "macOS and Linux" tab.

* Should we follow the manual steps described the "macOS and Linux" section, or try to integrate `eksctl`?
* `defaultCapacityOperatingSystem` feels like a premature parameter to add to the cluster, since a Linux node will be required to run anyway. How do you feel about removing that new parameter and using a boolean `enableWindowsSupport` property to the cluster, that will bootstrap. If `enableWindowsSupport` wasn't set, we could throw when calling `addWindowsCapacity`

**Comment by eladb** [comment]
> Should we follow the manual steps described the "macOS and Linux" section, or try to integrate eksctl?

Follow the manual steps. I don't think we should take a dependency on eksctl.

> How do you feel about removing that new parameter and using a boolean enableWindowsSupport property to the cluster, that will bootstrap. If enableWindowsSupport wasn't set, we could throw when calling addWindowsCapacity

Why not just automatically add windows support if `addWindowsCapacity` is called?

**Comment by nmussy** [comment]
> Follow the manual steps. I don't think we should take a dependency on eksctl.

Agreed, but I might have to hand the PR over to you. I don't have much experience with Kubernetes/EKS and it's a lot to take in. I'll see what I can do though.

> Why not just automatically add windows support if addWindowsCapacity is called?

I wanted to make `enableWindowsSupport` explicit, since it might create a Linux node even though the user didn't call `addCapacity`.

**Comment by eladb** [comment]
I am okay to include a  `windowsSupport` property at the cluster level, but default as `true`.

**Comment by nmussy** [comment]
Defaulting `windowsSupport` to true would make the property a little confusing. If the user only has Linux nodes with `windowsSupport` true, it doesn't make sense to bootstrap for the cluster for Windows nodes. If the property defaulted to true and only checked there are Windows nodes, it loses its use.

The alternative would be to do away with `defaultCapacityOperatingSystem` and `windowsSupport` entirely, and:
* Only bootstrap Windows when `addWindowsCapacity` has been called
* Before bootstrapping, verify that at least a Linux node is present, and throw if that's not the case

What do you think?

**Comment by eladb** [comment]
I like "Only bootstrap Windows when addWindowsCapacity has been called". Can we also add a linux node automatically if it's not present.

**Comment by nmussy** [comment]
Sorry for repeating myself, I'm really not a fan of adding "a" node automatically. A single node isn't ideal for reliability, multiple might be too expensive if the workload isn't mission critical. And there's also the issue of which instance type to chose.

If you don't feel this is an issue though, I agree it'd be a lot simpler for new users to get started.

**Comment by eladb** [comment]
Okay, fair enough. Let's just issue an error in that case with instructions on how to correct.

**Comment by eladb** [comment]
@nmussy sounds like this will require a custom resource or modification to the existing cluster creation custom resource.

**Comment by eladb** [comment]
Abandoned?

**Comment by eladb** [comment]
Closing for now. Please reopen when you are ready to continue.

**Pull request closed without merging**
