### PR TITLE
feat(pipelines): add support for caching to codebuild steps

### LINKED ISSUE #16375: cdk.pipelines -  Allow the configuration of Caching properties for Synth CodebuildProject
It would be helpful to add the abillity to set caching for the  synth code build project in a pipeline.  This will help with speed up the build and run times of pipelines.     I have achived the desired result by using escape hatches but this is not particaully elegent and could be improved with some minor work. 

```
if 'SynthProjectCachePropertys' in synth_cfg.keys():

            # the pipeline needs to be built bfore you can extract the synth
            # codebuild project. 
            # Everything needs to be done with buildingpipeline prior to this, 
            # as you can't modify it after you build. s
            pipeline.build_pipeline()

            codebuild_cache_bucket = s3.Bucket(self, 'codebuild_cache_bucket',
                auto_delete_objects= True,
                removal_policy= cdk.RemovalPolicy.DESTROY,
                block_public_access= s3.BlockPublicAccess.BLOCK_ALL
            )

            # finally use an escape hatch to manipulate the codebuild
            SynthCodeBuildProject: codebuild.CfnProject = pipeline.synth_project.node.default_child
            SynthCodeBuildProject.ProjectCacheProperty(
                type="S3",
                location = codebuild_cache_bucket.bucket_name,
                modes = synth_cfg['SynthProjectCachePropertys']['modes'],
            )
            # allow the code build project permission.
            codebuild_cache_bucket.grant_read_write(SynthCodeBuildProject)

### Use Case

Speed up the pipeline time.

### PR DESCRIPTION
**Pull request by Hi-Fi**
Fixes #16375

Closes #19084

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Hi-Fi** [comment]
@rix0rrr Opened new PR with tests to supersede #19084 which seemed quite silent for a long time. Hopefully this is something that can be merged, as at least original PR didn't had any implementation related comments/concerns.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
@Hi-Fi Thanks for making this change, complete with documentation and integ tests! We just need to have the conflicts resolved and I'll be happy to approve this change.

**Comment by Hi-Fi** [comment]
> @Hi-Fi Thanks for making this change, complete with documentation and integ tests! We just need to have the conflicts resolved and I'll be happy to approve this change.

Rebased branch from main and fixed the conflicts

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks good!

**Pull request merged**
