### PR TITLE
feat(cloudtrail): add dynamodb event selectors

### LINKED ISSUE #14886: (aws-cdk/aws-cloudtrail): Support DynamoDB as a DataResourceType in CloudTrail
About two months ago, AWS CloudTrail officially announced support for audit logging and monitoring of DynamoDb. More information about that [here](https://aws.amazon.com/blogs/database/amazon-dynamodb-now-supports-audit-logging-and-monitoring-using-aws-cloudtrail/). 
Today the aws-cdk only supports S3 and Lambda as data resource types and it would be super useful to be able to use cdk to construct our CloudTrail trails for DynamoDB as well.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by peterwoodworth**
fixes #14886

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by peterwoodworth** [comment]
I'm concerned we won't be able to add this - there still seems to be *some* regional support missing as I cannot successfully deploy this integration test with an error thrown describing lack of regional support. We may be blocked here still, @comcalvi am I missing something? https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudtrail-trail-dataresource.html

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Adding PR Blocked tag on this for the moment.

**Comment by peterwoodworth** [comment]
I'll close this for now and submit a ticket with Cfn

**Comment by peterwoodworth** [comment]
This feature is not allowed by default for internal accounts, which is why i have been running into this issue. I have submitted a request to whitelist my account, and will complete the integration test once my account is approved

**Comment by TheRealAmazonKendra** [comment]
> This feature is not allowed by default for internal accounts, which is why i have been running into this issue. I have submitted a request to whitelist my account, and will complete the integration test once my account is approved

What the efffff? If that's the case, we'll need to allow list our testing accounts and any user who is internal will need to do so as well. Given that, we should provide documentation about how to get allow listed.

**Comment by TheRealAmazonKendra** [comment]
Closing for now. We will reopen this after related issues are resolved.

**Pull request closed without merging**
