### PR TITLE
feat(cli): cdk init --from=path/to/local/template/dir

### PR DESCRIPTION
**Pull request by kaizencc**
You can supply a local template directory to `cdk init`. Suppose you have a local folder,
`path/to/local/templates`, that has a single template, `my-local-template`:

```console
$ cdk init --list --from=path/to/local/templates
Avaliable templates:
* my-local-template: Local Template for CDK Application

$ cdk init my-local-template --from=path/to/local/templates --language=typescript
```

We don't have any cli integ tests that test `cdk init`, but I did test this locally on my computer in addition to the unit test. 

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Is this accounting for hook scripts? Scripts that run after the files have been copied to update `requirements.txt` or run `dotnet add --project bla.csproj` (or whatever) ?

**Review by corymhall — COMMENTED** [review]
@kaizencc I'm just curious, what is the motivation for providing this functionality in the CLI? It seems like if anything we should be removing template generation from the CLI or offloading to some other tool (i.e. projen).

This opens up a lot of additional surface area for the CLI.

**Comment by kaizencc** [comment]
Going in a different direction; closing this PR

**Pull request closed without merging**
