### PR TITLE
feat(apprunner): support VpcConnectors

### LINKED ISSUE #18887: (apprunner): apprunner vpc support
### Description

Support for App Runner's recently introduced VPC support. https://aws.amazon.com/blogs/aws/new-for-app-runner-vpc-support/

### Use Case

Support for talking to VPC-only services and private services. (RDS, ElastiCache, etc...)

### Proposed Solution

Generating the new fields in the Cf L1 construct and adding VPC support to the L2 in a Lambda-like manner. E.g. Smartly taking VPC and optionally SGs and SubnetFilter, automatically adding the apprioriate IAM permissions.

### Other information

_No response_

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by DDynamic**
closes #18887

- Creates a new `VpcConnector` construct.
- Make the app runner service construct accept a `vpcConnector` property. When present, associate the service with the connector.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by RichiCoder1** [comment]
Considering how App Runner treats VPC Connectors, there's an argument that VPC Connector should it's own construct that's passed in (and therefore sharable) between App Runner services. Maybe still with the option for a service to implicitly create one for you.

**Comment by DDynamic** [comment]
@RichiCoder1 makes sense. I have added the new construct accordingly.

**Comment by yamatatsu** [comment]
@DDynamic Will this PR be revived?

**Comment by DDynamic** [comment]
@yamatatsu I'll take a look shortly!

**Comment by DDynamic** [comment]
New PR opened here: https://github.com/aws/aws-cdk/pull/20471

**Pull request closed without merging**
