### PR TITLE
chore: bump jsii to version 0.20.11

### PR DESCRIPTION
**Pull request by skinny85**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by skinny85** [comment]
Forgot to include the `yarn.lock` file in the first revision.

**Comment by RomainMuller** [comment]
You'll  probably want to upgrade TypeScript (there's a direct dependency on it here and there) to ^3.7.2 (or .3)

**Comment by skinny85** [comment]
Changed the JSII version to `0.20.10`.

**Comment by skinny85** [comment]
Changed the JSII version to `0.20.11`.

**Comment by skinny85** [comment]
Duplicated by Rico with #5432

**Pull request closed without merging**
