### PR TITLE
chore(codebuild): make `buildImage` required in the future

### PR DESCRIPTION
**Pull request by rix0rrr**
Add a feature flag to make `buildImage` required in the future.

Right now we default to `aws/codebuild/standard:1.0` which is long over
its due date and deprecated anyway, yet we can't bump the default
version for fear of what will break for other people. Effectively,
it's required anyway for users, might as well make it official (after
v2).

To achieve this, split the arguments from `environment` to the
top-level so it doesn't become annoying. We've always had this
split location going where `buildImage`, `computeType` and `privileged`
can only be specified *inside* `environment`, but `environmentVariables`
can be specified in two places?

And if `buildImage` is going to be required, it's silly for it to be
inside `environment` (which then must also become required). All
in all, the additional layer of indirection was annoying to work with,
so we splat it out to the top-level.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by skinny85 — APPROVED** [review]
I'm a little worried about this change, whether something will not break for customers using the previous default.

But if you think this is safe... OK.

**Comment by rix0rrr** [comment]
> But if you think this is safe... OK.

I'm assuming, but I don't know for a fact. It **should** be.

Do you have a different proposal?

**Comment by skinny85** [comment]
> > But if you think this is safe... OK.
> 
> I'm assuming, but I don't know for a fact. It **should** be.
> 
> Do you have a better idea?

I don't know if it's better, but the alternative that comes to mind here is leaving this as-is in V1, and submitting a change only to the `v2-main` branch: either changing the default to version 5, like you did here, or, given we'll be in a similar situation a few years down the line, maybe making `buildImage` a required parameter when creating a `Project`.

**Comment by richardhboyd** [comment]
I would propose we leave it the way it is in V1, and make it a required property in V2 (i.e. no default) unless you want to be making this same decision again in a year or so when the next Image gets deprecated. This has been causing people pain for a while and we haven't been able to make a change due to backwards compatibility requirements. Bumping the default version is just kicking the can down the road, making the parameter required is the better long term fix.


https://github.com/aws/aws-cdk/pull/12002
https://github.com/aws/aws-cdk/issues/6517
https://github.com/aws/aws-cdk/issues/11960
https://github.com/aws/aws-cdk/issues/12226

**Comment by eladb** [comment]
I generally agree with @richardhboyd that being in a position that the default needs to be changed is a bad place to be at. Having said that, if the new image is backwards compatible with the old image, I don't see a huge problem with moving everyone forward. In fact, there's some value to CDK customers - they don't need to worry about the fact that codebuild deprecated the old image, they will automatically be upgraded to the new image...

**Comment by richardhboyd** [comment]
I would be surprised if they were backwards compatible. If they were, there'd be no reason for CodeBuild to have bumped the version number. I suspect v1 is using something NodeJS 8 that isn't present on v3 and people using v1 will expect that it is still present. 

Customers may be manually installing newer versions of some dependencies with a v1 image and forcing them into v3 may cause conflicts (likely with the system python installation)

**Comment by eladb** [comment]
Fair points

**Pull request closed without merging**
