### PR TITLE
fix(aws-cloudfront): distribution comment length not validated (#14020)

### LINKED ISSUE #14020: [@aws-cdk/aws-route53-patterns]: HttpsRedirect throws 'The parameter Comment is too big'
I'm trying to create a HttpsRedirect on Route53 with CloudFront. When deploying, the CDK is throwing the below error.

The comment itself is auto-generated and the props interface for the `HttpsRedirect` does not allow to customize the comment. The comment pattern is: `Redirect to <target> from <recordName>`.

```
The parameter Comment is too big. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidArgument; Request ID: c8ea25db-e10a-4b47-bc81-d1cc818806d9; Proxy: null)
--
  | new CloudFrontWebDistribution (/app/node_modules/@aws-cdk/aws-cloudfront/lib/web-distribution.js:293:30)
  | \_ new HttpsRedirect (/app/node_modules/@aws-cdk/aws-route53-patterns/lib/website-redirect.js:51:30)
  | \_ StorybookAppStack.createRedirect (/app/dist/apps/deploy/src/stacks/storybook.stack.js:50:9)
  | \_ new StorybookAppStack (/app/dist/apps/deploy/src/stacks/storybook.stack.js:12:14)
  | \_ Object.<anonymous> (/app/dist/apps/deploy/src/storybook.app.js:9:1)
  | \_ Module._compile (internal/modules/cjs/loader.js:1063:30)
  | \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  | \_ Module.load (internal/modules/cjs/loader.js:928:32)
  | \_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
  | \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
  | \_ internal/main/run_main_module.js:17:47
```

### Reproduction Steps

```
    const dnsSuffix = StackHelper.dnsSuffix(slice);
    const zone = StackHelper.getHostedZone(this);
    const {
      aws_certificatemanager: { Certificate, CertificateValidation },
      aws_route53_patterns: { HttpsRedirect },
    } = base;

    new HttpsRedirect(this, StackHelper.createId('Redirect'), {
      zone: zone,
      recordNames: [`super.large.url.should.help.${application}${dnsSuffix}`],
      targetDomain: `${bucket.bucketWebsiteDomainName}/add/more/blocks/just/to/increase/the/size`,
      certificate: new Certificate(this, 'Certificate', {
        domainName: `${stage}.${DOMAIN}`,
        validation: CertificateValidation.fromDns(zone),
      }),
    });
```

### What did you expect to happen?

Should create the route redirect using AWS CloudFront from a dns to a bucket target url

### What actually happened?

The route fails to be created because of a comment property, not an invalid redirect.

### Environment

  - **CDK CLI Version	: 1.95.1**
  - **Framework Version	: 1.95.1**
  - **Node.js Version	: 14.16.0** 
  - **OS               	: Linux **
  - **Language (Version): TypeScript 4.2.3** 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by minuz**
fixes #14020

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by minuz** [comment]
@njlynch not sure if this is normal, but I had to use `lint --fix`, probably due to my local vscode settings and the PR end up getting a bit polluted with those fixes.

**Review by njlynch — CHANGES_REQUESTED** [review]
> not sure if this is normal, but I had to use lint --fix, probably due to my local vscode settings and the PR end up getting a bit polluted with those fixes.

Yeah, looks like your local VSCode settings are quite different from ours! Unfortunately, this makes the diff almost impossible to read. Can you clean this up? One approach might be to use `git reset` + `git add -p` to reset (not remove) all of these changes, and then only add back in the relevant lines. As-is, there are too many unrelated changes here for me to be confident reviewing just the few lines of comments-related stuff.

**Comment by minuz** [comment]
> > not sure if this is normal, but I had to use lint --fix, probably due to my local vscode settings and the PR end up getting a bit polluted with those fixes.
> 
> Yeah, looks like your local VSCode settings are quite different from ours! Unfortunately, this makes the diff almost impossible to read. Can you clean this up? One approach might be to use `git reset` + `git add -p` to reset (not remove) all of these changes, and then only add back in the relevant lines. As-is, there are too many unrelated changes here for me to be confident reviewing just the few lines of comments-related stuff.

No worries, I've cleaned up the PR and now it's only the actual changes.

**Review by njlynch — APPROVED** [review]
Thanks! :+1:

**Pull request merged**
