### PR TITLE
feat(region-info): added AppMesh ECR account for eu-south-1 region

### PR DESCRIPTION
**Pull request by rajal-amzn**
AppMesh is launched in `eu-south-1` region and has a separate account for storing Envoy images in ECR.
Updated the ECR account information.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by shivlaks — CHANGES_REQUESTED** [review]
@rajal-amzn - looks like there are tests in the `ecs-service-extensions` module that need to be updated as well.

**Comment by rajal-amzn** [comment]
> @rajal-amzn - looks like there are tests in the `ecs-service-extensions` module that need to be updated as well.

`ecs-service-extensions` failed since the old Envoy image version was not present in MXP. The Envoy image is updated to the latest as part of a different PR. Builds pass locally.

**Comment by shivlaks** [comment]
> > @rajal-amzn - looks like there are tests in the `ecs-service-extensions` module that need to be updated as well.
> 
> `ecs-service-extensions` failed since the old Envoy image version was not present in MXP. The Envoy image is updated to the latest as part of a different PR. Builds pass locally.

@rajal-amzn is it #11297 ? - if so, updating the branch should do it.

**Review by shivlaks — CHANGES_REQUESTED** [review]
tests that are broken are directly related to changes in this PR:

i.e. - this expected mappings file is no longer correct because a change was made for `eu-south-1`. [example](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk-containers/ecs-service-extensions/test/integ.all-service-addons.expected.json#L3384-L3386)

pleas re-run the failing integration test(s)
```
yarn integ integ.all-service-addons.js integ.multiple-environments.js
```

they will verify deployment and upon successful deployment, automatically update the `.generated` file. please do not modify the generated file(s) directly.
```

**Comment by rajal-amzn** [comment]
> tests that are broken are directly related to changes in this PR:
> 
> i.e. - this expected mappings file is no longer correct because a change was made for `eu-south-1`. [example](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk-containers/ecs-service-extensions/test/integ.all-service-addons.expected.json#L3384-L3386)
> 
> pleas re-run the failing integration test(s)
> 
> ```
> yarn integ integ.all-service-addons.js integ.multiple-environments.js
> ```
> 
> they will verify deployment and upon successful deployment, automatically update the `.generated` file. please do not modify the generated file(s) directly.

Fixed the failing tests now.

**Review by shivlaks — APPROVED** [review]

**Review by shivlaks — APPROVED** [review]

**Pull request merged**
