### PR TITLE
fix(custom-resources): provider framework creates duplicate roles

### PR DESCRIPTION
**Pull request by markussiebert**
## Changes:

This pull request will reduce the IAM roles created for every custom resource provider.

## Context

fixes: #17849 

We are talking about the IAM roles of the "helper" or "framework" functions (onEvent..., isComplete... and onTimeout... functions that are provided by the cr provider itself) - not the role and permissions of the lambda functions you have to provide via the props. 

For the mentioned 3 functions/IAM roles you have 2 options:

a) Let the cr provider create the roles:
This is handled via the default behaviour of the lambda function. Each lambdafunction will create it's own role and identical IAM permissions will be added to the role of every function. (See the createFunction method, that will create the lambdaFunction and than add the invoke IAM permissions for the onEvent and isComplete handler). So we will have 3 identical IAM roles. 

b) Create the role yourself and pass it via the role propertie. 
Now, the passed role will be used for all 3 framework lambda functions and identical permissions will be added 3 times.

This pr will change the behaviour described in a). Instead of creating a role for every new function (the default behaviour of the lambda function) we will create a role in the same way the lambda function would create it, and then use the functionality of b) to reuse this one role several times.

One could ask: So why don't you use the property described in b) for your projects? 
The answer: Because I can not. There are a lot of resource providers that won't let me specify this property.

Why do you want to reduce the IAM roles?
Because since using cdk we were increasing our IAM role limits several times and I think it is unnecessary. Yes it doesn't cost extra money, but there is also no reason to create them. And If you use CDK, there can be a lot of cr providers that are created in the background (I like them - don't get me wrong!)  

Are we getting bigger, less least privileged IAM roles?
My answer: No, because all functions get the same permissions - so there is no reason to create 3 roles for them.

Are you introducing new permissions?
My answer: No, really, no new permissions...

Is this a breaking change?
My answer: IAM roles will be "replaced" and lambda roles changed, but I don't think this will break anything :-)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by markussiebert** [comment]
I was not able to run the integration test because of this error:

```ts
 ❌  integ-provider-framework: destroy failed Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
    at SdkProvider.resolveEnvironment (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts:208:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CloudFormationDeployments.prepareSdkFor (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/api/cloudformation-deployments.ts:260:33)
    at CloudFormationDeployments.destroyStack (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/api/cloudformation-deployments.ts:229:58)
    at CdkToolkit.destroy (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/cdk-toolkit.ts:348:9)
    at initCommandLine (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/bin/cdk.ts:267:9)
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
Error: Command exited with status 1
    at exec (/Users/markussiebert/github/aws-cdk/tools/@aws-cdk/cdk-integ-tools/lib/integ-helpers.js:349:15)
    at IntegrationTest.invokeCli (/Users/markussiebert/github/aws-cdk/tools/@aws-cdk/cdk-integ-tools/lib/integ-helpers.js:180:20)
    at main (/Users/markussiebert/github/aws-cdk/tools/@aws-cdk/cdk-integ-tools/bin/cdk-integ.js:51:32)
error Command failed with exit code 1.
```
So my integrationtest was upgraded with dry run, but -  famous last words - I think this will work like expected :-/

**Review by rix0rrr — CHANGES_REQUESTED** [review]
This needs a flag.

You complain that there are too many Roles. If we do this unconditionally, other people are going to complain that the functions have too many permissions, because we are unnecessarily sharing Roles between Functions (and what if there's a vulnerability?)

People are very particular about IAM Roles, and we have to be able to accommodate the strictest requirements.

Since this is effectively the same as passing in a `role`, can't we do that instead?

**Comment by rix0rrr** [comment]
Also, it would help a lot if you put more context in the PR body. Please describe the problem, the approach you took to solve it and the alternatives you considered.

**Comment by rix0rrr** [comment]
We might also explore the use of [condition keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html) to make sure the additional permissions cannot be misused?

**Comment by markussiebert** [comment]
Thanks for your comments,

I reworked the PR message, so I hope it's more clear.

**Review by rix0rrr — APPROVED** [review]
My apologies. Upon deeper review you are right that all roles get exactly the same permissions. I'm sure there are unnecessary permissions in there still, but given that this PR doesn't change anything about the permission set, I'm okay merging it.

Thanks for sticking it out with me!

**Comment by markussiebert** [comment]
Thank you! Now as you are fine with this, i have to update some Tests, because they will now fail because all will miss the extra roles :-)

**Pull request closed without merging**
