### PR TITLE
feat(ec2): Endpoint service az context provider

### PR DESCRIPTION
**Pull request by flemjame-at-amazon**
## Commit Message
feat(ec2): lookup available AZs for Interface Endpoints

This commit adds a new context provider which will make a DescribeVpcEndpointServices call to figure out what AZs are available. This will filter the user-provided `subnets` parameter to only include subnets for the AZs discovered through DescribeVpcEndpointServices.
## End Commit Message

Today, it is possible to configure the availability zones for a VpcEndpointService like so:
```ts
new InterfaceVpcEndpoint(stack, "VPC Endpoint", {
  vpc,
  service: new InterfaceVpcEndpointService("com.amazonaws.vpce.us-east-1.vpce-svc-uuddlrlrbastrtsvc", 443),
  subnets: {
    subnetType: SubnetType.ISOLATED,
    availabilityZones: ["us-east-1a", "us-east-1c"]
  }
```

However this requires the user to go into the AWS console and using the VPC wizard to create an interface endpoint to discover the available AZs. It would be a good experience to be able to have CDK discover the available AZs on behalf of the user, if possible.

This commit adds a new context provider which will make a DescribeVpcEndpointServices call to figure out what AZs are available. This will filter the user-provided `subnets` parameter to only include subnets for the AZs discovered through DescribeVpcEndpointServices.

The intended behavior is as follows:

- If no account or region is provided, the interface endpoint service will not make use of the context provider. 
- If account and region are provided, but no subnet selection provided, the interface endpoint will be placed in all available AZs, in subnets in accordance with the VPC default selection strategy.
- If account and region are provided, but subnetSelection is provided, the interface endpoint will not add additional subnets to those provided by the user via `subnets`, only remove non-available subnets.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
> * If account and region are provided, but subnetSelection is provided, the interface endpoint will not add additional subnets to those provided by the user via `subnets`, only remove non-available subnets.

I don't think this is intuitive behavior. If I give a list, I would expect that list to be honored, not changed out from under me.

> * If account and region are provided, but no subnet selection provided, the interface endpoint will be placed in all available AZs, in subnets in accordance with the VPC default selection strategy.

Thereby potentially including AZs that are not available for VPC Endpoint Services, and failling?

-------

This PR seems to assume everyone already knows what AZ restrictions have to do with VPC Endpoint Services. I for one don't.

Is it that only a subset of AZs in a region are available to create VPC Endpoint Services in? And will picking the wrong one cause a deployment failure?

-------

I think I'd prefer a `filterDownToAvailableAzs?: boolean` flag or something (probably using a better name).

**Comment by flemjame-at-amazon** [comment]
> > * If account and region are provided, but subnetSelection is provided, the interface endpoint will not add additional subnets to those provided by the user via `subnets`, only remove non-available subnets.
> 
> I don't think this is intuitive behavior. If I give a list, I would expect that list to be honored, not changed out from under me.

I agree, however if the user provides subnets with AZs that the endpoint service is not available in, they will get a deployment-time error like "The VPC endpoint service <-service name-> does not support the availability zone of the subnet". 

What would you recommend to balance the "abide by the provided arguments" vs "the provided arguments will cause an error"?

> > * If account and region are provided, but no subnet selection provided, the interface endpoint will be placed in all available AZs, in subnets in accordance with the VPC default selection strategy.
> 
> Thereby potentially including AZs that are not available for VPC Endpoint Services, and failling?
> 

My wording was poor -- I meant:
* If account and region are provided, but no subnet selection provided, the interface endpoint will be placed in all AZs the service is available in, in subnets in accordance with the VPC default selection strategy.

It will only include the AZs the service is actually available in.

> This PR seems to assume everyone already knows what AZ restrictions have to do with VPC Endpoint Services. I for one don't.
> 
> Is it that only a subset of AZs in a region are available to create VPC Endpoint Services in? And will picking the wrong one cause a deployment failure?

That is correct. the specific error is:
 "The VPC endpoint service <-service name-> does not support the availability zone of the subnet". 

A concrete example of this is Kinesis Firehose, which in us-west-2 is available in AZs [2a, 2b, 2c] but not "2d". Below is the DescribeVpcEndpointServices call for that service.

```
        {
            "ServiceType": [
                {
                    "ServiceType": "Interface"
                }
            ], 
            "PrivateDnsName": "firehose.us-west-2.amazonaws.com", 
            "ServiceName": "com.amazonaws.us-west-2.kinesis-firehose", 
            "VpcEndpointPolicySupported": true, 
            "Owner": "amazon", 
            "AvailabilityZones": [
                "us-west-2a", 
                "us-west-2b", 
                "us-west-2c"
            ], 
            "AcceptanceRequired": false, 
            "BaseEndpointDnsNames": [
                "firehose.us-west-2.vpce.amazonaws.com"
            ]
        }
```

**Comment by rix0rrr** [comment]
How about a flag:

```
/** 
 * Limit to only those availability zones where the endpoint service can be created
 *
 * Setting this to 'true' requires a lookup to be performed at synthesis time. Account
 * and region must be set on the containing stack for this to work.
 *
 * @default false
 */
readonly lookupSupportedAzs?: boolean;
```

When enabled, will filter down the list of given/all availability to those that can actually be used.

**Comment by flemjame-at-amazon** [comment]
> How about a flag:
> 
> ```
> /** 
>  * Limit to only those availability zones where the endpoint service can be created
>  *
>  * Setting this to 'true' requires a lookup to be performed at synthesis time. Account
>  * and region must be set on the containing stack for this to work.
>  *
>  * @default false
>  */
> readonly lookupSupportedAzs?: boolean;
> ```
> 
> When enabled, will filter down the list of given/all availability to those that can actually be used.

Updated and checked in

**Comment by rix0rrr** [comment]
Looks good! Just need to confer with my colleagues on how we should handle versioning here. There might be more work...

**Comment by rix0rrr** [comment]
This PR needs the following one to be handled first: https://github.com/aws/aws-cdk/pull/7800

**Comment by flemjame-at-amazon** [comment]
@rix0rrr does #7800 mean I don't have to have the files in cx-api anymore?

**Pull request merged**
