### PR TITLE
fix(synthetics): correct getbucketlocation policy

### LINKED ISSUE #13572: (synthetics): getbucketlocation policy is incorrect
Synthetics canary default role policy contains the incorrect arn syntax for a call to `s3:GetBucketLocation`

When using Synthetics runtime "syn-nodejs-puppeteer-3.1" the canary will try to call `s3:GetBucketLocation` but with an improper policy which will result in denied access.

### Reproduction Steps

minimal amount of code that causes the bug (if possible) or a reference:
The current implementation on `master` is bugged:

```
        new iam.PolicyStatement({
          resources: [this.artifactsBucket.arnForObjects(`${prefix ? prefix+'/*' : '*'}`)],
          actions: ['s3:PutObject', 's3:GetBucketLocation'],
        })
```

### What did you expect to happen?

Allow the "syn-nodejs-puppeteer-3.1" runtime to operate correctly without generating IAM access denied errors.

### What actually happened?

The role will be denied access by IAM get call `s3:GetBucketLocation` on that S3 bucket.

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

Should be fixed by creating a separate policy that breaks `s3:GetBucketLocation` out into a separate policy that is targeted specifically at just the bucket arn:

```
        new iam.PolicyStatement({
          resources: [this.artifactsBucket.bucketArn],
          actions: ['s3:GetBucketLocation'],
        }),
        new iam.PolicyStatement({
          resources: [this.artifactsBucket.arnForObjects(`${prefix ? prefix+'/*' : '*'}`)],
          actions: ['s3:PutObject'],
        }),
 ```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by csumpter**
When using synthetics runtime "syn-nodejs-puppeteer-3.1" the default role tries to call s3:getBucketLocation on the artifacts bucket, but the policy is incorrect to allow that action.

The policy should allow for that call directly on the bucket arn.

fixes #13572

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by NetaNir** [comment]
I have commented on the issue, lets discuss the fix there.

**Review by kaizen3031593 — APPROVED** [review]
Thanks for the fix @csumpter! I've verified that this looks good on my end. Sorry it took so long to get to it!

**Comment by csumpter** [comment]
> Thanks for the fix @csumpter! I've verified that this looks good on my end. Sorry it took so long to get to it!

Thank you @kaizen3031593 for the follow-up and approval, really appreciate it.

**Review by kaizen3031593 — APPROVED** [review]

**Comment by wilhen01** [comment]
Does anyone know when this will be released? It's not in the [changelog](https://github.com/aws/aws-cdk/blob/v2.9.0/CHANGELOG.v2.alpha.md) for `2.9.0`

**Comment by kaizen3031593** [comment]
@wilhen01 `2.9` corresponds with `1.140` and not with the latest on `master`. Look out for `1.141` released this week, and then the corresponding `2.10` released the week after.

**Pull request merged**
