### PR TITLE
fix(cfn-diff): allow resources to change types

### LINKED ISSUE #13921: Cannot get .resourceType, because the type was changed
`cdk diff` exits with `Cannot get .resourceType, because the type was changed` error message, `cdk synth` works fine.

### Reproduction Steps

Cannot provide them, I still have no idea how I ended up in that state, sorry.

### What did you expect to happen?

Diff should be shown or at least a clear error message with exact resource id, old and new types.

### What actually happened?

`Cannot get .resourceType, because the type was changed`

### Environment

  - **CDK CLI Version  :** 1.95.1 
  - **Framework Version:** 1.95.1 
  - **Node.js Version:** v15.12.0
  - **OS               :** macOS 11.2.3
  - **Language (Version):** Java (8)

### Other

```
Reading existing template for stack
Cannot get .resourceType, because the type was changed
Error: Cannot get .resourceType, because the type was changed
    at ResourceDifference.get resourceType [as resourceType] (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff/types.ts:587:13)
    at TemplateDiff.scrutinizablePropertyChanges (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff/types.ts:124:40)
    at new TemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff/types.ts:53:29)
    at calculateTemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:110:10)
    at Object.diffTemplate (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:43:19)
    at Object.printStackDiff (/usr/local/lib/node_modules/aws-cdk/lib/diff.ts:24:24)
    at CdkToolkit.diff (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:103:18)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:208:9)
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
When writing the cloudformation-diff module,
it was assumed that resources would never change their CloudFormation types between deployments.
As it turns out, there is a legitimate case for resources changing types,
and that's when you migrate from a template that uses Transforms
(like the Serverless Transform) to one that doesn't use them.

Because of that, handle the case of resources changing types in diff.

Fixes #13921

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — CHANGES_REQUESTED** [review]
This needs to be interpreted as a replacement, no?

**Comment by skinny85** [comment]
> This needs to be interpreted as a replacement, no?

Yes, this is already handled by `()` here: https://github.com/aws/aws-cdk/blob/186dc329aa87157d11e3d0148c1d9d957adcf1fa/packages/%40aws-cdk/cloudformation-diff/lib/diff/types.ts#L155-L157

This is how the experience looks like in the CDK CLI:

```shell
$ yarn cdk diff

...

Resources
[+] AWS::IAM::Role S1/Template/LambdaSaverRole LambdaSaverRole 
[+] AWS::ApiGateway::Deployment S1/Template/SaveApiDeployment14a59e22ee SaveApiDeployment14a59e22ee 
[+] AWS::ApiGateway::Stage S1/Template/SaveApiprodStage SaveApiprodStage 
[+] AWS::Lambda::Permission S1/Template/LambdaSaverSaveApiPermissionprod LambdaSaverSaveApiPermissionprod 
[~] AWS::Lambda::Function S1/Template/LambdaSaver LambdaSaver replace
[~] AWS::ApiGateway::RestApi S1/Template/SaveApi SaveApi replace
```

**Review by rix0rrr — APPROVED** [review]

**Comment by rix0rrr** [comment]
> Yes, this is already handled by `scrutinizableResourceChanges()` here:

Damn that sounds weird

**Comment by skinny85** [comment]
> > Yes, this is already handled by `scrutinizableResourceChanges()` here:
> 
> Damn that sounds weird

I _think_ that's because you can't really handle the replacement of an entire resource on the level of the property change, so that's why you can't do it from `scrutinizablePropertyChanges ()`.

**Pull request merged**
