### PR TITLE
fix(rds): rename 'instanceClass' in DatabaseInstance to 'instanceType'

### PR DESCRIPTION
**Pull request by skinny85**
BREAKING CHANGE: the property 'instanceClass' in DatabaseInstanceNewProps has been renamed to 'instanceType'

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by fogfish** [comment]
Thank you for the change! It really nice improvement to API semantic. How this type of changes are communicated to developers? 

These type of changes comes as a broken build surprise ;-(

Please apologise, If I missed the communication!

**Comment by nija-at** [comment]
@fogfish - we have this announced in our CHANGELOG for [`1.46.0`](https://github.com/aws/aws-cdk/releases/tag/v1.46.0). That's where all our breaking changes are usually announced.

Is there something else we can do to better communicate these changes?

**Comment by fogfish** [comment]
Thank you for point out! I've completely missed this change log! 

So far, I've been 100% relying on [npm version policy](https://docs.npmjs.com/about-semantic-versioning): Major release is changed every time when api compatibility break is introduced. I am not sure if you are able to adapt this policy.

I'd be more careful to follow up release notes!

**Comment by skinny85** [comment]
@fogfish some of our packages are still considered 'experimental', which means they can have breaking changes in minor releases (although we strive to keep them to a minimum). RDS is one of those packages.

The stability of a module can be found in its ReadMe, for example [on NPM](https://www.npmjs.com/package/@aws-cdk/aws-rds), or [in the CDK docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-rds-readme.html).

Thanks, and sorry for the trouble.
Adam

**Pull request merged**
