### PR TITLE
fix(scheduler): schedule not added to group with unspecified name

### LINKED ISSUE #27885: aws-scheduler-alpha: Schedule Group is ignored
### Describe the bug

When I set a Schedule Group on a Schedule, the setting is ignored, and my Schedule ends up in the `default` group.

### Expected Behavior

I expect my Schedule to be associated with the Schedule Group I created and specified.

### Current Behavior

The setting is ignored, and my Schedule ends up in the `default` group. The template does not have a `GroupName` attribute set on the `AWS::Scheduler::Schedule` resource.

### Reproduction Steps

```java
        final IGroup scheduleGroup = new Group(this, "ScheduleGroup", GroupProps.builder()
                .build());
        final ISchedule schedule = new Schedule(this, "Schedule", ScheduleProps.builder()
                .group(scheduleGroup)
                .key(appKey)
                .schedule(ScheduleExpression.rate(Duration.minutes(10)))
                .target(LambdaInvoke.Builder.create(function)
                                .retryAttempts(0)
                                .input(ScheduleTargetInput.fromText("{}"))
                                .build())
                .build());
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.104.0 (build 3b99abe)

### Framework Version

_No response_

### Node.js Version

npm@9.5.1

### OS

Windows 10

### Language

Java

### Language Version

Java 11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by msambol**
Closes #27885.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Looks good to me 👍
Just a file cleanup is needed.
Also, the title should be `fix(scheduler) ...`

**Comment by msambol** [comment]
@lpizzinidev Updated per your feedback 💪🏼

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍

**Review by kaizencc — APPROVED** [review]

**Comment by vinayak-kukreja** [comment]
@Mergifyio update

**Pull request merged**
