### PR TITLE
feat(cfnspec): Manually generate AWS Device Farm L1 Constructs

### PR DESCRIPTION
**Pull request by workeitel**
AWS Device Farm is only in us-west-2 while CDK uses the AWS CloudFormation resource specification from us-east-1 for generating L1. That causes AWS Device Farm missing https://github.com/aws/aws-cdk/issues/22565

This change manually includes the resource specification for AWS Device Farm and generates the package with L1. It means the resources are not automatically updated on changes.

Fixes: https://github.com/aws/aws-cdk/issues/17893

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by workeitel** [comment]
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Features must contain a change to an integration test file and the resulting snapshot.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.

I did not add any new code. Everything is auto-generated so without adding new L2 an integration test does not make sense

**Comment by TheRealAmazonKendra** [comment]
Is Device Farm only in us-west-2?

**Comment by workeitel** [comment]
> Is Device Farm only in us-west-2?

yes: https://docs.aws.amazon.com/general/latest/gr/devicefarm.html

**Comment by workeitel** [comment]
> This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

no work needed. Please review and merge.

**Pull request closed without merging**
