### PR TITLE
docs(lambda-go): fix typos

### PR DESCRIPTION
**Pull request by matthiasgubler**
### Reason for this change
Typos in doc

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by msambol** [comment]
@matthiasgubler Could you change the title to `docs(lambda-go): fix typos` ?

**Comment by matthiasgubler** [comment]
@msambol done!

**Review by msambol — APPROVED** [review]
LGTM. Thanks @matthiasgubler

**Review by scanlonp — APPROVED** [review]
Good find, thanks @matthiasgubler!

**Pull request merged**
