### PR TITLE
feat(ecs): attach EBS volume to ECS task

### PR DESCRIPTION
**Pull request by go-to-k**
WIP.

- Releases and blogs
  - https://aws.amazon.com/jp/about-aws/whats-new/2024/01/amazon-ecs-fargate-integrate-ebs/
  - https://aws.amazon.com/jp/blogs/aws/amazon-ecs-supports-a-native-integration-with-amazon-ebs-volumes-for-data-intensive-workloads/
- Developer and User Guide
  - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ebs-volumes.html
  - https://docs.aws.amazon.com/AmazonECS/latest/userguide/troubleshoot-ebs-volumes.html 
- CloudFormation
  - ConfiguredAtLaunch
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-volume.html#cfn-ecs-taskdefinition-volume-configuredatlaunch
  - VolumeConfigurations
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-volumeconfigurations

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mrgrain** [comment]
@go-to-k It's now available: https://github.com/aws/aws-cdk/pull/28684

**Comment by go-to-k** [comment]
@mrgrain 

Thanks, I will take this PR.

**Comment by MrArnoldPalmer** [comment]
@go-to-k we have another PR that we have been working on https://github.com/aws/aws-cdk/pull/28682

Let us know what you think!

**Comment by go-to-k** [comment]
@MrArnoldPalmer 

Is that the intention of the core team? If so, I will withdraw my PR.

**Comment by go-to-k** [comment]
@MrArnoldPalmer 

Instead, I would like to support you by doing a community review of your PR.

**Comment by MrArnoldPalmer** [comment]
@go-to-k yes, this PR has been worked on by the core team. We would appreciate a review!

**Pull request closed without merging**
