### PR TITLE
fix(eks): missing question marks cause update cluster setting failure

### PR DESCRIPTION
**Pull request by guessi**
introduced by #21185

Fixes: #21436

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [X] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thank you for your contribution. We cannot provide a review or accept code without tests.

**Comment by mrgrain** [comment]
Hey @guessi thanks for coming back to this! Looks like we've missed a unit and/or integration test the first time around. Could you please add one now?

**Comment by guessi** [comment]
@TheRealAmazonKendra @mrgrain I think it would be better to done by you for faster response as I'm not that familiar with integ test. ( I tried, but that relatively hard for me )

**Review by TheRealAmazonKendra — APPROVED** [review]
After diving deep on this, I'm not sure that we can actually really test this. So, approving it and saying YOLO.

**Pull request merged**
