### PR TITLE
fix(core): asset bundling runs as root

### LINKED ISSUE #8489: Custom asset bundling for lambda using docker results in output code that is owned by root
The custom asset bundling feature released in v1.45 -(https://github.com/aws/aws-cdk/pull/7898) results in output from the docker image that is owned by root (or the user that executes the commands in the docker container in general).

This is unexpected, and could be a problem if a user does not have root access on the machine to clean up the cdk.out folder.

### Reproduction Steps

```python
bundling_options = core.BundlingOptions(image=aws_lambda.Runtime.PYTHON_3_7.bundling_docker_image,
                                        command=[
                                            'bash', '-c',
                                            'pip install -r requirements.txt -t /asset-output && rsync -r . /asset-output',
                                        ])
source_code = aws_lambda.Code.from_asset('src/test', bundling=bundling_options)


handler = aws_lambda.Function(self, f"{self.id}-TestBundling",
                              function_name=f"{self.id}-TestBundling",
                              handler=f'handlers.test',
                              runtime=aws_lambda.Runtime.PYTHON_3_7,
                              code=source_code)
```

### Error Log

executing `ls -la` in the output folder yeilds the following as an example

```
-rw-r--r--  1 root   root     573 Jun 11 06:03 handlers.py
```

### Environment

  - **CLI Version      :1.45.0 (build 0cfab15)**
  - **Framework Version:1.45.0**
  - **Node.js Version:v12.0.0** 
  - **OS               :*Debian 10.4*
  - **Language (Version):Python 3.7.6** 

### Other

As per discussion on https://github.com/aws/aws-cdk/pull/7898, passing `-u $UID:$UID` as part of dockerArgs in `packages/@aws-cdk/core/lib/bundling.ts` might be the solution.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
Get `uid` and `gid` of current user and pass it to `docker run` to avoid
running the container as `root`. On Windows, use `1000:1000` as default.

Add `user` to `BundlingOptions`.

Fixes #8489

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@eladb I think this needs #8481 for the build to succeed

**Comment by eladb** [comment]
> @eladb I think this needs #8481 for the build to succeed
> 
> EDIT: actually I'm not sure `1000:1000` will correctly work in CI

In master now

**Comment by jogold** [comment]
@eladb do you think `uid` and `gid` should be exposed in `BundlingOptions`?

**Comment by eladb** [comment]
> @eladb do you think `uid` and `gid` should be exposed in `BundlingOptions`?

Eventually they will be requested.

**Pull request merged**
