### PR TITLE
feat(core): use parameter store refs instead of exports

### PR DESCRIPTION
**Pull request by corrjo**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by corrjo** [comment]
Hey @skinny85, @rix0rrr  I finally found some cycles to work on this (re: https://github.com/aws/aws-cdk/discussions/13184) but hit a broken test in `@aws-cdk/aws-eks-legacy` I started working on a fix but also noticed https://github.com/aws/aws-cdk/blob/c6ca2aba915ea4f89e3044b7f388acda231e295d/packages/%40aws-cdk/aws-eks-legacy/lib/cluster.ts#L343 is it worth spending time to fix this?

**Comment by rix0rrr** [comment]
Thanks for the intent, but this is really a fundamental design change that's going to need discussion. `exports` definitely have value which should be taken into account.

I recommend you open up an [RFC](https://github.com/aws/aws-cdk-rfcs) first with a proposal and a motivation and thinking through some of the impacts.

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Thanks for the intent, but this is really a fundamental design change that's going to need discussion. exports definitely have value which should be taken into account.

I recommend you open up an RFC first with a proposal and a motivation and thinking through some of the impacts.

**Comment by corrjo** [comment]
> Thanks for the intent, but this is really a fundamental design change that's going to need discussion. exports definitely have value which should be taken into account.
> 
> I recommend you open up an RFC first with a proposal and a motivation and thinking through some of the impacts.

https://github.com/aws/aws-cdk-rfcs/pull/311

**Comment by corrjo** [comment]
relates to https://github.com/aws/aws-cdk/pull/12778

**Comment by TheRealAmazonKendra** [comment]
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

**Pull request closed without merging**
