### PR TITLE
fix(core): updatedProperties function name is misspelled

### PR DESCRIPTION
**Pull request by michimani**
This PR only fix typo in the name of protected function.

`Properites` -> `Properties`

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by michimani** [comment]
My apologies. Perhaps this fix affects more places than I realize?

**Review by kaizencc — DISMISSED** [review]
Oh gosh. Thanks for finding this and bringing it to our attention. I'm not sure we can do this because it is a breaking change. What we have to do is deprecate `updatedProperites` and introduce a new `updatedProperties` method that does the same thing. @michimani is this something you're interested in doing?

**Comment by michimani** [comment]
Excuse my repeated comments.
I will still proceed with the correction in this pull request.

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks good! Thanks for catching this!

**Pull request merged**
