### PR TITLE
feat(docdb): added ability to enable performance insights

### LINKED ISSUE #24036: aws-cdk-lib/doc-db: Add option to enable performance insights in instances
### Describe the feature

It would be great if there is an option to enable performance insights when creating a cluster with the L2 construct available for DocumentDb.

### Use Case

This will help to automate the process of when creating instances, enable the performance insights on them.

### Proposed Solution

I see in the [DocumentDB Instance cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbinstance.html#cfn-docdb-dbinstance-enableperformanceinsights) that it just needs a boolean parameter at the instance level.

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.63.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.1

### PR DESCRIPTION
**Pull request by rodrigomata**
Added the ability to enable performance insights in the L2 construct for DocumentDB Cluster so it can be enabled programmatically in all instances inside the cluster.

> [CONTRIBUTING GUIDE]: https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md
> [DESIGN GUIDELINES]: https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md

Closes #24036.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by Jewhurst — APPROVED** [review]

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
This looks good overall, but from the looks of it, there are not enough changes in the integ test snapshot output for this to have been run. Was this manually updated? Please remove the manual update from the snapshot and run this with `yarn integ --update-on-failed`.

**Comment by rodrigomata** [comment]
> This looks good overall, but from the looks of it, there are not enough changes in the integ test snapshot output for this to have been run. Was this manually updated? Please remove the manual update from the snapshot and run this with `yarn integ --update-on-failed`.

I removed the manual update and ran the `yarn integ --update-on-failed` command; however, nothing changed after running it and after committing the change the pipeline breaks, am I missing something? Read throughout the contributing and integration tests section but couldn't find anything related

**Comment by MrArnoldPalmer** [comment]
Hey @rodrigomata , so there are integ test snapshot changes that result from the change you've added. I don't have permissions to push to your fork, so I can't add the commit with the update here, [you can enable changes to your fork for upstream maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so I can push the updates, or you can apply the commit yourself from [here](https://github.com/MrArnoldPalmer/aws-cdk/commit/7cd7efb23258ea691749e15afaa57e398ede54bc).

**Comment by rodrigomata** [comment]
> Hey @rodrigomata , so there are integ test snapshot changes that result from the change you've added. I don't have permissions to push to your fork, so I can't add the commit with the update here, [you can enable changes to your fork for upstream maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so I can push the updates, or you can apply the commit yourself from [here](https://github.com/MrArnoldPalmer/aws-cdk/commit/7cd7efb23258ea691749e15afaa57e398ede54bc).

Thanks for replying @MrArnoldPalmer and adding what was missing. Strange because the permissions were enabled but probably a bug on Github, so I disabled and re-enabled hoping it made some effect so you can push the commits you already have there:

Screenshot 2023-03-08 at 13 55 24

**Comment by MrArnoldPalmer** [comment]
ahh I may have been trying to push the wrong branch actually, no worries working now.

**Review by MrArnoldPalmer — APPROVED** [review]

**Pull request merged**
