### PR TITLE
fix: importing `aws-cdk-lib` is slow

### PR DESCRIPTION
**Pull request by mrgrain**
Fixes slow import of top-level aws-cdk-lib.

At the very end of the build, the compiled `index.js` file is replaced with a version optimized for import performance.
Instead of loading submodules directly at the top level, exports are defined as getter functions.
This way they will only be required when actually imported from `aws-cdk-lib`.
Improves AWS CDK app performance by ~400ms.

Background reading: https://medium.com/trabe/exporting-getters-in-commonjs-modules-dd8f98b7d85e

----

```console
$ hyperfine -i "node -e \"const { App } = require('aws-cdk-lib');\"" "node -e \"const { App } = require('aws-cdk-lib-candidate');\"" --warmup 5
Benchmark 1: node -e "const { App } = require('aws-cdk-lib');"
  Time (mean ± σ):      1.227 s ±  0.125 s    [User: 1.102 s, System: 0.262 s]
  Range (min … max):    1.110 s …  1.508 s    10 runs
 
Benchmark 2: node -e "const { App } = require('aws-cdk-lib-candidate');"
  Time (mean ± σ):     251.9 ms ±  19.7 ms    [User: 226.6 ms, System: 51.0 ms]
  Range (min … max):   224.6 ms … 278.3 ms    10 runs
 
Summary
  'node -e "const { App } = require('aws-cdk-lib-candidate');"' ran
    4.87 ± 0.62 times faster than 'node -e "const { App } = require('aws-cdk-lib');"'
```

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mrgrain** [comment]
Exempted tests and integ-tests as no change and passing tests is a sign of this working as expected.

**Review by rix0rrr — APPROVED** [review]
Lovely hack-fix! 😍

**Comment by mrgrain** [comment]
Leaving the do not merge label on until he have decided if this is a good idea.

**Comment by mikolaj-w-provectusalgae** [comment]
Is there a chance that this PR broke es6 style imports? 

```
import { aws_cognito as cognito, aws_ssm as ssm } from 'aws-cdk-lib';
         ^^^^^^^^^^^
SyntaxError: Named export 'aws_cognito' not found. The requested module 'aws-cdk-lib' is a CommonJS module, which may not support all module.exports as named exports.

**Comment by mrgrain** [comment]
Thanks @mikolaj-w-provectusalgae We are working on a fix.

**Comment by mrgrain** [comment]
@mikolaj-w-provectusalgae Can you confirm if [v2.62.1](https://github.com/aws/aws-cdk/releases/tag/v2.62.1) fixes this for you?

**Comment by mikolaj-w-provectusalgae** [comment]
It is partially fixed. The project can be synthesized and deployed, but the tests fail. I'll do some digging in Jest's configuration and see what's wrong.

```
Test suite failed to run

    lib/index.ts:3:5 - error TS2305: Module '"../node_modules/aws-cdk-lib/lazy-index.js"' has no exported member 'aws_ec2'.

    3     aws_ec2 as ec2,
          ~~~~~~~
    lib/index.ts:4:5 - error TS2305: Module '"../node_modules/aws-cdk-lib/lazy-index.js"' has no exported member 'aws_iam'.

    4     aws_iam as iam,
          ~~~~~~~
    lib/index.ts:5:5 - error TS2305: Module '"../node_modules/aws-cdk-lib/lazy-index.js"' has no exported member 'aws_lambda'.

    5     aws_lambda as lambda,
    
    ...
```

**Comment by mikolaj-w-provectusalgae** [comment]
I guess `lazy-index.d.ts` is the problem. `index.d.ts` with all exports should be used.

**Comment by mrgrain** [comment]
Makes sense. Could you try adding a `types` entry to `node_modules/aws-cdk-lib/package.json` in your project?

Relevant section would then look like this:
```json
{
  //...
  "exports": {
    ".": {
      "types": "./index.d.ts",
      "import": "./index.js",
      "require": "./lazy-index.js"
    },
    // ...
}
```

**Comment by mikolaj-w-provectusalgae** [comment]
Yep. That's it! test, synth and deployment pass.

**Comment by mrgrain** [comment]
Sweet! Thanks for helping out. We'll get the fix out asap.

**Comment by mikolaj-w-provectusalgae** [comment]
> Sweet! Thanks for helping out. We'll get the fix out asap.

Thanks for your quick response!

**Comment by mrgrain** [comment]
@mikolaj-w-provectusalgae [v2.62.2](https://github.com/aws/aws-cdk/releases/tag/v2.62.2) is released

**Pull request merged**
