### PR TITLE
fix(region-info): EC2 service principal in Chia

### PR DESCRIPTION
**Pull request by pahud**
EC2 service principal in Chia should be `ec2.amazonaws.com.cn` rather than `ec2.amazonaws.com`. 

This feature was previously broke from https://github.com/aws/aws-cdk/pull/22589 and this PR fixes that.

Closes https://github.com/aws/aws-cdk/issues/24696

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
Exemption Request

**Comment by pahud** [comment]
I can't find the document about this, but per the IAM console from AWS China, the service principal should be `ec2.amazonaws.com.cn`.

image

**Comment by ItielOlenick** [comment]
Still an issue on 2.74.0 (latest python)

**Comment by djessup** [comment]
Ya'll seem to break China like this every few months or so. AWS Partitions are a thing, China and GovCloud are the notable examples. I don't know what the situation is in AWS C2S (aka "spook-cloud"), but probably it's a similar deal. Given how deep-rooted and necessary this concept seems to be, I can't see it going away anytime soon. 

Next time somebody has a bright idea to optimise or get rid of `region-info` somehow - please, just don't.

**Pull request closed without merging**
