### PR TITLE
chore(location): add validation for description property in PlaceIndex class

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

N/A

### Reason for this change
Add validation for PlaceIndex description, similar to #30648, #30682, and #30711 .

### Description of changes
Add validation and unit tests for description.

### Description of how you validated changes
Add unit tests.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mazyu36** [comment]
Exemption Request: As this only involves adding validation, I think updating the README and integration tests is not needed.

**Review by go-to-k — CHANGES_REQUESTED** [review]
Could you add a description for the character count constraint to JSDoc for the property? It would surely benefit users.

https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-location-alpha/lib/place-index.ts#L51-L52

**Comment by mazyu36** [comment]
@go-to-k 
Thank you for the review.
I've updated docs.

**Review by TheRealAmazonKendra — APPROVED** [review]
I've updated this to a chore, which has different validation for the PR.

**Pull request merged**
