### PR TITLE
chore(eslint-plugin-cdk): use a fixed directory for test output within the package folder

### LINKED ISSUE #10731: eslint-plugin-cdk permission denied making a tmp directory
This is the error I get when doing a yarn build after pulling in the fix from https://github.com/aws/aws-cdk/pull/10719

> eslint-plugin-cdk: FAIL test/rules/no-core-construct.test.js
> eslint-plugin-cdk:   ● Test suite failed to run
> eslint-plugin-cdk:     EACCES: permission denied, mkdtemp '/tmpXXXXXX'
> eslint-plugin-cdk:       12 | });
> eslint-plugin-cdk:       13 | 
> eslint-plugin-cdk:     > 14 | const outputDir = fs.mkdtempSync(os.tmpdir())
> eslint-plugin-cdk:          |                      ^
> eslint-plugin-cdk:       15 | const fixturesDir = path.join(__dirname, 'fixtures', 'no-core-construct');
> eslint-plugin-cdk:       16 | 
> eslint-plugin-cdk:       17 | describe('no-core-construct', () => {
> eslint-plugin-cdk:       at Object.<anonymous> (test/rules/no-core-construct.test.ts:14:22)
> eslint-plugin-cdk: Test Suites: 1 failed, 1 total
> eslint-plugin-cdk: Tests:       0 total
> eslint-plugin-cdk: Snapshots:   0 total
> eslint-plugin-cdk: Time:        1.47 s
> eslint-plugin-cdk: Ran all test suites.
> eslint-plugin-cdk: npm ERR! Test failed.  See above for more details.
> eslint-plugin-cdk: error Command failed with exit code 1.
> eslint-plugin-cdk: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Unless I'm missing something, it's trying to make a directory at the root? I tried giving permissions to /tmp and to everything recursively in the aws-cdk folder, but still nothing.

### PR DESCRIPTION
**Pull request by blaenk**
The use of [`fs.mkdtemp()`](https://nodejs.org/api/fs.html#fs_fs_mkdtemp_prefix_options_callback) in `no-core-construct.test.ts` doesn't provide a trailing path separator, so instead of attempting to create `/tmp/randomstring`, it attempts to create `/tmprandomstring`.

https://github.com/aws/aws-cdk/blob/41f6de2b3fe6cb20a49fce2d3db0bd25812fd5d9/tools/eslint-plugin-cdk/test/rules/no-core-construct.test.ts#L14

See the linked docs for more information:

> The fs.mkdtemp() method will append the six randomly selected characters directly to the prefix string. For instance, given a directory /tmp, **if the intention is to create a temporary directory within /tmp, the prefix must end with a trailing platform-specific path separator (require('path').sep).**

I discovered this while working on something else.

I don't think CI has failed because I think you all use privileged mode on CodeBuild, in which case such an operation would succeed.

fixes #10731 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by nija-at — COMMENTED** [review]
Thanks for taking the effort to open this PR.

How about completely dropping the tmp dir, and simply creating a folder, say `test-output` in the root of this package and adding it to `.gitignore`?

This way, we remove the entire need that `/tmp` exists and is writable.

**Comment by blaenk** [comment]
Sounds good, made that change.

**Review by nija-at — COMMENTED** [review]
Sorry, what you have is not going to work for us. There's no need to modify things at the repo level.

I've pushed a more changed contained to this specific package.  Can you test this locally and check that it works for you?.

**Comment by blaenk** [comment]
Sorry about that, I misread what you wrote:

> in the root of this package

as the "root of this repo"

Thanks for the fix! I probably won't have time to look at this until later tomorrow so feel free to take over if this is time sensitive.

I did try `yarn build` at the repo root and got:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for monocdk@1.66.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Review by nija-at — APPROVED** [review]

**Pull request merged**
