### PR TITLE
feat(aws-lambda-event-sources): adding new CW Event IEventSource implementation

### PR DESCRIPTION
**Pull request by mbonig**
Adding a new CloudWatch Event implementation for the IEventSource interface. This will allow Lambdas to be easily registered one recurring schedules or other patterns as defined by the [Rule](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.Rule.html)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mbonig** [comment]
I'm not sure I understand your comment. I don't need to wrap the LambdaFunction in an IEventSource implementation to get a crontab-like experience with lambda?

**Comment by nija-at** [comment]
You can already do something like this - 

```ts
#!/usr/bin/env node
import { App, Stack } from '@aws-cdk/core';
import { Function, Code, Runtime } from '@aws-cdk/aws-lambda';
import { Rule, Schedule } from '@aws-cdk/aws-events';
import { LambdaFunction } from '@aws-cdk/aws-events-targets';

const app = new App();
const stack = new Stack(app, 'mystack');

const lambdaFn = new Function(stack, 'fn', {
  // ...
});

const rule = new Rule(stack, 'cron', {
  schedule: Schedule.cron({
    // ...
  }),
})

rule.addTarget(new LambdaFunction(lambdaFn));
```

**Comment by mbonig** [comment]
That's fair, and makes sense. If that's the case, then do you not see any value in having a Rule implementation for IEventSource?

**Comment by nija-at** [comment]
The implementations of this module are usually around Lambda's event source mapping feature - https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventsourcemapping.html.

Based on what I see in this documentation, there is no way to connect a Cloudwatch Event rule to an event source mapping, so I would say we close out this PR and use the event rule target mechanism we have already.

**Comment by mbonig** [comment]
Sounds good.

**Pull request closed without merging**
