### PR TITLE
fix(custom-resource-handlers): better fallback for require failures 

### LINKED ISSUE #30067: (custom-resources): Package does not exist
### Describe the bug

I'm trying to use `AwsCustomResource` from Python for a couple of actions on `@aws-sdk/client-cognito-identity-provider`, and deployment keeps failing with errors like:

```
Received response status [FAILED] from custom resource. Message returned:
Package @aws-sdk/client-cognito-identity-provider does not exist. (RequestId: 99b79a89-1a17-4acf-864c-84b3ac3e5664)
```

### Expected Behavior

The affected resource (see repro steps below) should deploy successfully and create a user in the provided Cognito user pool.

### Current Behavior

I'm getting the above mentioned error message and the resource fails to create (or rollback/delete). Also tried providing the service name as `CognitoIdentityServiceProvider` but this gave the same error message (with `@aws-sdk/client-cognito-identity-provider` package name)

Possibly this may be intermittent, as I managed to get the stack to deploy (update existing to add this resource) at least once? But now facing the error consistently.

### Reproduction Steps

Given Python CDK construct with a resource something like:

```python
AwsCustomResource(
    self,
    "AwsCustomResource-CreateUser",
    on_create=AwsSdkCall(
        action="adminCreateUser",
        parameters={
            "UserPoolId": ...,
            "Username": ...,
            "MessageAction": "SUPPRESS",
            "TemporaryPassword": ...,
        },
        physical_resource_id=PhysicalResourceId.of(
            f"AwsCustomResource-CreateUser-{...}"
        ),
        service="@aws-sdk/client-cognito-identity-provider",
    ),
    on_delete=AwsSdkCall(
        action="adminDeleteUser",
        parameters={
            "UserPoolId": ...,
            "Username": ...,
        },
        service="@aws-sdk/client-cognito-identity-provider",
    ),
    policy=AwsCustomResourcePolicy.from_sdk_calls(
        resources=AwsCustomResourcePolicy.ANY_RESOURCE
    ),
    install_latest_aws_sdk=True,
)
```

...Try to deploy the stack

### Possible Solution

🤷‍♂️

### Additional Information/Context

Originally observed on CDK v1.126.0, so tried upgrading to 2.140.0 but it didn't help.

### CDK CLI Version

2.140.0

### Framework Version

2.140.0

### Node.js Version

20.9.0

### OS

macOS 14.4.1

### Language

Python

### Language Version

Python 3.12.1

### Other information

Seems possibly related to #28005, which was closed due to inactivity but raised against an older CDK version.

### PR DESCRIPTION
**Pull request by glitchassassin**
### Issue # (if applicable)

Closes #30067.

### Reason for this change

Fallback to existing AWS SDK import misses a rare/flaky edge case where the npm install passes, but the subsequent `require` fails

### Description of changes

Fall back to the pre-existing AWS SDK if requiring the latest version fails

### Description of how you validated changes

- Fixed no-op test "installs the latest SDK"
- Added test "falls back to installed sdk if require fails"

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
Thanks for your contribution. We can't take this just yet because it will conflict with node runtime upgrades (https://github.com/aws/aws-cdk/pull/30108) but once that PR is merged we will take a look at this one. 

Unfortunately, when that one is merged it will cause merge conflicts for all of your integ tests so I would advise holding off on any additional work here until that time so you're not having to deal with a lot of churn. In the meantime, I'm going to add the `do-not-close` label to this PR so you don't have to recreate it again if merging that one takes too long (it should not, but I'm just going to be cautious).

**Comment by glitchassassin** [comment]
I've pushed up the integration test snapshot updates I've gotten through so far. I'm out of the office for the weekend, so if someone else wants to help with those that'd be great! Otherwise, I'll finish them up when I get a chance.

**Comment by glitchassassin** [comment]
@TheRealAmazonKendra I've updated most of the integration tests, but there are a few that appear to be failing due to trying to assume roles without permissions. Anything you can do for the last few tests?

```
yarn integ --update-on-failed aws-appsync/test/integ.js-resolver.js
yarn integ --update-on-failed aws-certificatemanager/test/integ.dns-validated-certificate.js
yarn integ --update-on-failed aws-chatbot/test/integ.chatbot-logretention.js
yarn integ --update-on-failed aws-cloudfront/test/integ.cloudfront-cross-region-cert.js
yarn integ --update-on-failed aws-cloudfront/test/integ.distribution-function-runtime.js
yarn integ --update-on-failed aws-cloudfront/test/integ.distribution-lambda-cross-region.js
```

**Comment by TheRealAmazonKendra** [comment]
Don't make anymore snapshot updates for now. We are continuing to have some problems around them so I'm going to add a do-not-close label to this PR and then probably appear to be ignoring it for another couple weeks. I really appreciate your patience with these delays. 

BTW, I did see your message on cdk.dev and that is the right way to get my attention.

**Comment by TheRealAmazonKendra** [comment]
Oh, the label is already added. Good. I absolutely plan to come back to this first once I get the other wrinkles ironed out.

**Comment by glitchassassin** [comment]
sounds good; I'll check back in after two weeks!

**Comment by glitchassassin** [comment]
@TheRealAmazonKendra How are we looking now? Ready to pick this back up?

**Comment by GavinZZ** [comment]
Hello @glitchassassin, the node runtime upgrade is complete and please address the conflicts. We will get back to you on the PR.

**Comment by glitchassassin** [comment]
@GavinZZ, I re-ran these failing integration tests locally like so:

```
yarn integ --update-on-failed custom-resources/test/aws-custom-resource/integ.aws-custom-resource.js
```

For most of these, this appeared to successfully update the snapshot and pass, but when I re-ran `yarn integ`, all of the tests once again failed.

**Comment by GavinZZ** [comment]
@glitchassassin Sorry for the late response. Because the changes were made in `@aws-cdk/custom-resource-handlers` module, you need to
1. navigate to `packages/@aws-cdk/custom-resource-handlers/`
2. run `yarn build`
3. run `npx lerna run build --scope=aws-cdk-lib`
4. then re-run the failed tests.

**Comment by glitchassassin** [comment]
@GavinZZ Thanks. I did re-run those builds, but it's having no effect: when I update the snapshot, the test still fails the next time I run `yarn integ`.

**Comment by glitchassassin** [comment]
Closing in favor of #31571

**Pull request closed without merging**
