### PR TITLE
feat(tokens): enable type coercion

### LINKED ISSUE #2679: Token.toNumber fails with Tcp/UdpPort after the ...FromAttribute versions were removed
**Describe the bug**
After this was merged https://github.com/awslabs/aws-cdk/pull/2580 I now see errors like this:

```
(node:22) UnhandledPromiseRejectionWarning: Error: Token value is not number or lazy, can't represent as number: ${Token[DBCluster.Endpoint.Port.199]}
    at Token.toNumber (/app/node_modules/.registry.npmjs.org/@aws-cdk/cdk/0.32.0/node_modules/@aws-cdk/cdk/lib/token.ts:162:15)
    at new PostgreSQLDb (/app/context/nbnsq-infra/constructs/PostgreSQLDb.ts:92:52)
    at new NbnSq (/app/context/nbnsq-infra/stacks/NbnSq.ts:354:17)
    at /app/context/nbnsq-infra/app.ts:137:2
```

**To Reproduce**
```ts
const sg = new SecurityGroup(this, "SecurityGroup", {...});
const cluster = new CfnDBCluster(this, "DBCluster", {...});
sg.addIngressRule(
    new CidrIPv4('127.0.0.1/32'),
    new TcpPort(new Token(cluster.dbClusterEndpointPort).toNumber())
);
```

**Expected behavior**
`TcpPort` to accept the `Token` after being converted with `toNumber` as outlined in the `v0.32.0` change log: _"`ec2.TcpPortFromAttribute` and `UdpPortFromAttribute` removed. Use `TcpPort` and `UdpPort` with `new Token(x).toNumber` instead."_

**Work around**
This still produces a working template.

```ts
const sg = new SecurityGroup(this, "SecurityGroup", {...});
const cluster = new CfnDBCluster(this, "DBCluster", {...});
sg.addIngressRule(
    new CidrIPv4('127.0.0.1/32'),
    cluster.dbClusterEndpointPort as any as number
);
```

**Version:**
 - Programming Language: Typescript
 - CDK Version: 0.32.0

### PR DESCRIPTION
**Pull request by eladb**
Relax restrictions on input types for Token.toXxx in order to allow flexible type coercion.

This may be needed in situations where users want to force a token typed as one type to be represented as another type and generally allow tokens to be used as "type-system escape hatches".

Previously, this did not work:

    const port = new Token({ "Fn::GetAtt": [ "ResourceId", "Port" ] }).toString(); 
    new TcpPort(new Token(port).toNumber());

Also, this did not work:

    const port = new Token({ "Fn::GetAtt": [ "ResourceId", "Port" ]}).toNumber();

These were just examples. The point is that if a user reached the point where you actually need a token, they basically indicate to the framework that “I know what I am are doing”. It’s a sort of an “as any” at the framework level.

Fixes #2679

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by rix0rrr** [comment]
you need to instantiate a CfnReference instead of a Token.

**Comment by eladb** [comment]
> you need to instantiate a CfnReference instead of a Token.

That was just an example. The point is that I think we don’t need to be defensive in Token.toXxxx methods. If you’ve reached the point where you actually need a token, you basically indicate to the framework that “you know what you are doing”. It’s a sort of an “as any” at the framework level.

**Comment by rix0rrr** [comment]
In my mind, there are 2 types of Tokens, both doing some kind of escape mechanism, but they're not the same escape mechanism:

- Represent CFN intrinsics. This bypasses the type system in that we have an opaque value that we want to use to represent a `string`, or whatever. Importantly: the intrinsic will ultimately render to an object structure, and there's no way for us to verify whether its declared type matches the actual (deploy-time) type.
- Represent laziness. This bypasses the type system in that we get a `string` value NOW, even though we will actually only have the actual `string` value available LATER. We *could* still do type validation on this, since we know (and can check) that the value returned at the LATER time is actually of type `string`.

I want to use different classes to represent different kinds of tokens, and so the code you wrote up there could not be written anymore (`new Token({ Ref: "abc" })` will not be valid).

I'm okay to merge it now if you really want to, though.

**Comment by eladb** [comment]
@rix0rrr you are right that we are using tokens for those two use cases, and I am open to looking into differentiating these two use case using a higher-level API. Let's look into this as part of #1933, ok?

**Pull request merged**
