### PR TITLE
chore(cli): make the "new" bootstrapping the default in V2

### PR DESCRIPTION
**Pull request by skinny85**
Make the "new" bootstrapping
(that adds additional resources beyond the S3 bucket to the template,
like an ECR repository, and IAM roles)
the default.
Allow using the "old" bootstrapping by setting the `CDK_LEGACY_BOOTSTRAP`
environment variable.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — CHANGES_REQUESTED** [review]
To be clear, this is intended to be merged into the v2 branch, yeah?

Because right now it looks like it's going into the v1 branch, which I don't think we want to disturb existing setups that much.

**Comment by rix0rrr** [comment]
And are you following up by making the DefaultSynthesizer the default as well?

**Comment by skinny85** [comment]
> And are you following up by making the DefaultSynthesizer the default as well?

I was planning to follow up with a PR that flips the `@aws-cdk/core:newStyleStackSynthesis` flag to `true` in V2.

**Comment by skinny85** [comment]
> To be clear, this is intended to be merged into the v2 branch, yeah?
> 
> Because right now it looks like it's going into the v1 branch, which I don't think we want to disturb existing setups that much.

Hmm. I was actually under the impression that we wanted to switch this default in V1 as well (as the new-style bootstrapping supports the old-style Assets fine).

@nija-at do you want to weigh-in here? What is it that we should do here?

**Comment by nija-at** [comment]
> @nija-at do you want to weigh-in here? What is it that we should do here?

I believe the requirement, at a min, was to change to the new style boostrapping as the default on v2. 
I'll defer to @rix0rrr's judgement on whether this should also be done in v1.

If we're only switching this on v2, could we do something simple as reading the version# of the CLI and picking the default. Could that be a simple code change that can be done on master (i.e., avoid branch divergence)?

**Comment by skinny85** [comment]
> If we're only switching this on v2, could we do something simple as reading the version# of the CLI and picking the default?
> Could that be a simple code change that can be done on master (i.e., avoid branch divergence)?

Technically, I think we could - we already read the `package.json` file of the package for the `cdk version` command [here](https://github.com/aws/aws-cdk/blob/8782e672d6a8f8bbe201f2572c4b0fca7589168d/packages/aws-cdk/lib/version.ts#L15-L20).

However, I think this will be difficult to reconcile with our integration tests, that need to explicitly use a specific version of the bootstrapping in them, like [here](https://github.com/aws/aws-cdk/blob/8782e672d6a8f8bbe201f2572c4b0fca7589168d/packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts#L30-L49).

@rix0rrr what's your take on this?

**Comment by skinny85** [comment]
I'm wondering whether doing it only for V2 makes sense at all...

At some point, V2 will be GA, and then running `npx cdk` will run CDK V2. When that happens, what instructions will you give to V1 users of CDK Pipelines? Considering that `npx cdk bootstrap` will run the new bootstrapping...

**Comment by skinny85** [comment]
Discussed offline. Will go with switching to new bootstrapping only in V2, and making the switch on `master`, based on the version of the package, like Niranjan suggested.

**Comment by skinny85** [comment]
@rix0rrr changed to only make "new" bootstrapping default in V2. Would appreciate another review!

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
