### PR TITLE
fix(cli): deployment error traceback overwritten by progress bar

### LINKED ISSUE #14780: (cli): failed cloudformation deployment should show individual resource errors (in addition to stack error)
Right now, a failing stack deployment  always says something like "deployment failed: rollback requested by user" (or something).

This is what CloudFormation says the `StatusReason` is.

That's fair enough, but it's almost never useful. Typically, the error will be somewhere in the resource event log, and will be a message for a resource that ends up in `CREATE_FAILED` or `UPDATE_FAILED`:

```
12:34:82 | S3Bucket | CREATE_FAILED | Bucket with name 'foo' already exists
```

We should remember the individual error messages and print those again at the end.

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by BenChaimberg**
Currently, when the "stack activity monitor" is asked to stop, it does a final poll of the stack state and sends the new events to the progress-bar printer. However, the monitor already told the printer to stop, at which time it re-printed all failures. This means that the final poll will erroneously overwrite the failures (because the behaviour of the printer is to repeatedly print to the same console space). This change ensures the printer is asked to stop after the final poll occurs.

This change also removes the failure message for the root stack from the failure re-print, since it's not interesting information to surface to the user.

This change also re-prints failures for the legacy events-based printer.

fixes #14780

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by BenChaimberg** [comment]
I didn't include any tests because there aren't any tests currently, but please let me know if you'd like me to set some up. I think testing the `print`/`stop` order might be a bit tricky since it would be testing concurrent ordering, but maybe defining a mock printer that fails if `print` is called after `stop` would work.

**Comment by BenChaimberg** [comment]
Also, called this a bug fix since we really were doing something incorrectly: overwriting the traceback that was the original feature request.

**Comment by BenChaimberg** [comment]
Here is what the output looks like as of this change:
```
7:52:19 PM | CREATE_FAILED        | AWS::CloudFormation::Stack | NestedNestedStackN...ckResourceDEFDAA4D                                                                             
Embedded stack arn:aws:cloudformation:us-west-2:898231755174:stack/TestAppStack-NestedNestedStackNestedNestedStackResourceDEFDAA4D-JZVU60XP6AC9/88a06270-b9df-11eb-8d9d-027f8bacea2  
3 was not successfully created: The following resource(s) failed to create: [CDKMetadata, TestAppBucket59492B1A].                                                                    
                                                                                                                                                                                     
        new NestedStack (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/core/lib/nested-stack.ts:132:21)                                                                       
        \_ new NestedStack (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/aws-cloudformation/lib/nested-stack.ts:71:5)                                                        
        \_ new TestAppStack (/Users/chaimber/opensource/test-app/lib/test-app-stack.ts:20:20)                                                                                        
        \_ Object.<anonymous> (/Users/chaimber/opensource/test-app/bin/test-app.ts:6:1)                                                                                              
        \_ Module._compile (node:internal/modules/cjs/loader:1102:14)                                                                                                                
        \_ Module.m._compile (/Users/chaimber/opensource/test-app/node_modules/ts-node/src/index.ts:1056:23)                                                                         
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1131:10)                                                                                                         
        \_ Object.require.extensions.<computed> [as .ts] (/Users/chaimber/opensource/test-app/node_modules/ts-node/src/index.ts:1059:12)                                             
        \_ Module.load (node:internal/modules/cjs/loader:967:32)                                                                                                                     
        \_ Function.Module._load (node:internal/modules/cjs/loader:807:14)                                                                                                           
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)                                                                                        
        \_ main (/Users/chaimber/opensource/test-app/node_modules/ts-node/src/bin.ts:198:14)                                                                                         
        \_ Object.<anonymous> (/Users/chaimber/opensource/test-app/node_modules/ts-node/src/bin.ts:288:3)                                                                            
        \_ Module._compile (node:internal/modules/cjs/loader:1102:14)                                                                                                                
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)                                                                                                  
        \_ Module.load (node:internal/modules/cjs/loader:967:32)                                                                                                                     
        \_ Function.Module._load (node:internal/modules/cjs/loader:807:14)                                                                                                           
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)                                                                                        
        \_ node:internal/main/run_main_module:17:47                                                                                                                                  
                                                                                                                                                                                     
                                                                                                                                                                                     
 ❌  TestAppStack failed: Error: The stack named TestAppStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE                            
    at Object.waitForStackDeploy (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/lib/api/util/cloudformation.ts:305:11)                                                         
    at processTicksAndRejections (node:internal/process/task_queues:93:5)                                                                                                            
    at Object.deployStack (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/lib/api/deploy-stack.ts:294:26)                                                                       
    at CdkToolkit.deploy (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/lib/cdk-toolkit.ts:180:24)                                                                             
    at initCommandLine (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/bin/cdk.ts:209:9)                                                                                        
The stack named TestAppStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE 
```

**Comment by rix0rrr** [comment]
Hey Ben,

Thanks for this, and sorry it took me so long to get to it.

Can you elaborate a bit more in the PR body about what the issue was and how you solved it? I see you shifting around a couple of statements but that doesn't give me a sense for why it fixes the problem.

Also, you're correct that the "progress bar" stack monitor already does this, but we also have the "legacy"/"event-based" stack monitor and iirc that doesn't do it yet. Could you confirm/disconfirm that, and if it doesn't have the error recaps add it there as well?

I distinctly remember users recently pasting error messages into bug reports, and those error messages were not showing the root cause errors.

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Requesting a bit more investigation into the other progress reporter as well

**Comment by BenChaimberg** [comment]
Here is what the output for the events-based printer looks like after this change:
```
TestAppStack: deploying...                                                                                                                                                                                                                     
TestAppStack: creating CloudFormation changeset...                                                                                                                                                                                             
 0/3 | 10:33:17 AM | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack | TestAppStack User Initiated                                                                                                                                           
 0/3 | 10:33:23 AM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | TestAppStack User Initiated                                                                                                                                           
 0/3 | 10:33:27 AM | CREATE_IN_PROGRESS   | AWS::S3::Bucket    | Bucket (Bucket83908E77)                                                                                                                                                       
 0/3 | 10:33:27 AM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata | CDKMetadata/Default (CDKMetadata)                                                                                                                                             
 0/3 | 10:33:27 AM | CREATE_FAILED        | AWS::S3::Bucket    | Bucket (Bucket83908E77) my-bucket already exists                                                                                                                              
        new Bucket (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/aws-s3/lib/bucket.ts:1331:22)                                                                                                                                         
        \_ new TestAppStack (/Users/chaimber/opensource/test/cdk-app/lib/test-app-stack.ts:8:5)                                                                                                                                                
        \_ Object.<anonymous> (/Users/chaimber/opensource/test/cdk-app/bin/test-app.ts:6:1)                                                                                                                                                    
        \_ Module._compile (node:internal/modules/cjs/loader:1102:14)                                                                                                                                                                          
        \_ Module.m._compile (/Users/chaimber/opensource/test/cdk-app/node_modules/ts-node/src/index.ts:1056:23)                                                                                                                               
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
        \_ Object.require.extensions.<computed> [as .ts] (/Users/chaimber/opensource/test/cdk-app/node_modules/ts-node/src/index.ts:1059:12)                                                                                                   
        \_ Module.load (node:internal/modules/cjs/loader:967:32)                                                                                                                                                                               
        \_ Function.Module._load (node:internal/modules/cjs/loader:807:14)                                                                                                                                                                     
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)                                                                                                                                                  
        \_ main (/Users/chaimber/opensource/test/cdk-app/node_modules/ts-node/src/bin.ts:198:14)                                                                                                                                               
        \_ Object.<anonymous> (/Users/chaimber/opensource/test/cdk-app/node_modules/ts-node/src/bin.ts:288:3)                                                                                                                                  
        \_ Module._compile (node:internal/modules/cjs/loader:1102:14)                                                                                                                                                                          
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)                                                                                                                                                            
        \_ Module.load (node:internal/modules/cjs/loader:967:32)                                                                                                                                                                               
        \_ Function.Module._load (node:internal/modules/cjs/loader:807:14)                                                                                                                                                                     
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)                                                                                                                                                  
        \_ node:internal/main/run_main_module:17:47                                                                                                                                                                                            
 0/3 | 10:33:28 AM | CREATE_FAILED        | AWS::CDK::Metadata | CDKMetadata/Default (CDKMetadata) Resource creation cancelled                                                                                                                 
        new MetadataResource (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/core/lib/private/metadata-resource.ts:22:24)                                                                                                                
        \_ /Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/core/lib/private/synthesis.ts:140:5                                                                                                                                            
        \_ visit (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/core/lib/private/synthesis.ts:202:5)                                                                                                                                    
        \_ visit (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/core/lib/private/synthesis.ts:198:5)                                                                                                                                    
        \_ injectMetadataResources (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/core/lib/private/synthesis.ts:131:3)                                                                                                                  
        \_ Object.synthesize (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/core/lib/private/synthesis.ts:18:3)                                                                                                                         
        \_ App.synth (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/core/lib/stage.ts:180:23)                                                                                                                                           
        \_ process.<anonymous> (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/core/lib/app.ts:123:45)                                                                                                                                   
        \_ Object.onceWrapper (node:events:483:26)                                                                                                                                                                                             
        \_ process.emit (node:events:376:20)                                                                                                                                                                                                   
        \_ process.EventEmitter.emit (node:domain:470:12)                                                                                                                                                                                      
        \_ process.emit (/Users/chaimber/opensource/test/cdk-app/node_modules/source-map-support/source-map-support.js:495:21)                                                                                                                 
 0/3 | 10:33:28 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | TestAppStack The following resource(s) failed to create: [CDKMetadata, Bucket83908E77]. Rollback requested by user.                                                   
 2/3 | 10:33:45 AM | DELETE_SKIPPED       | AWS::S3::Bucket    | Bucket (Bucket83908E77)                                                                                                                                                       
 2/3 | 10:33:45 AM | DELETE_COMPLETE      | AWS::CDK::Metadata | CDKMetadata/Default (CDKMetadata)                                                                                                                                             
 2/3 | 10:33:45 AM | ROLLBACK_COMPLETE    | AWS::CloudFormation::Stack | TestAppStack                                                                                                                                                          
                                                                                                                                                                                                                                               
Failed resources:                                                                                                                                                                                                                              
 10:33:27 AM | CREATE_FAILED        | AWS::S3::Bucket    | Bucket (Bucket83908E77) my-bucket already exists                                                                                                                                    
        new Bucket (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/aws-s3/lib/bucket.ts:1331:22)                                                                                                                                         
        \_ new TestAppStack (/Users/chaimber/opensource/test/cdk-app/lib/test-app-stack.ts:8:5)                                                                                                                                                
        \_ Object.<anonymous> (/Users/chaimber/opensource/test/cdk-app/bin/test-app.ts:6:1)                                                                                                                                                    
        \_ Module._compile (node:internal/modules/cjs/loader:1102:14)                                                                                                                                                                          
        \_ Module.m._compile (/Users/chaimber/opensource/test/cdk-app/node_modules/ts-node/src/index.ts:1056:23)                                                                                                                               
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1131:10)                                                                                                                                                                   
        \_ Object.require.extensions.<computed> [as .ts] (/Users/chaimber/opensource/test/cdk-app/node_modules/ts-node/src/index.ts:1059:12)                                                                                                   
        \_ Module.load (node:internal/modules/cjs/loader:967:32)                                                                                                                                                                               
        \_ Function.Module._load (node:internal/modules/cjs/loader:807:14)                                                                                                                                                                     
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)                                                                                                                                                  
        \_ main (/Users/chaimber/opensource/test/cdk-app/node_modules/ts-node/src/bin.ts:198:14)                                                                                                                                               
        \_ Object.<anonymous> (/Users/chaimber/opensource/test/cdk-app/node_modules/ts-node/src/bin.ts:288:3)                                                                                                                                  
        \_ Module._compile (node:internal/modules/cjs/loader:1102:14)                                                                                                                                                                          
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)                                                                                                                                                            
        \_ Module.load (node:internal/modules/cjs/loader:967:32)                                                                                                                                                                               
        \_ Function.Module._load (node:internal/modules/cjs/loader:807:14)                                                                                                                                                                     
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)                                                                                                                                                  
        \_ node:internal/main/run_main_module:17:47                                                                                                                                                                                            
                                                                                                                                                                                                                                               
 ❌  TestAppStack failed: Error: The stack named TestAppStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE                                                                                      
    at Object.waitForStackDeploy (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/lib/api/util/cloudformation.ts:305:11)                                                                                                                   
    at processTicksAndRejections (node:internal/process/task_queues:93:5)                                                                                                                                                                      
    at Object.deployStack (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/lib/api/deploy-stack.ts:294:26)                                                                                                                                 
    at CdkToolkit.deploy (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/lib/cdk-toolkit.ts:180:24)                                                                                                                                       
    at initCommandLine (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/bin/cdk.ts:209:9)                                                                                                                                                  
The stack named TestAppStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
