### PR TITLE
chore(cfnspec): new libraries do not conform to pkglint

### PR DESCRIPTION
**Pull request by rix0rrr**
When we updated the minimum Node version, we did not update it
in the template that is used to stamp out new construct libraries
when new CFN namespaces are added to the spec.

Meaning every cfnspec update now fails because the new packages
fail `pkglint` validation.

Update the Node version in the template.

Closes #20856.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
@mergifyio backport v1-main

**Comment by iliapolo** [comment]
@rix0rrr did you mean to have this PR close https://github.com/aws/aws-cdk/pull/20856 ... ?

**Comment by iliapolo** [comment]
Added `do-not-merge` in case you need to change the PR body

**Comment by rix0rrr** [comment]
I did. The other PR needs to be re-rolled.

**Pull request merged**
