### PR TITLE
ci: Create pr-linter-no-permissions.yml

### PR DESCRIPTION
**Pull request by Youssef1313**
While https://github.com/aws/aws-cdk/issues/22624 was closed, I think this addresses the problem and it's still in a secure way.

What do you think @TheRealAmazonKendra?

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
I'm not sure what you're trying to accomplish here. As I said in the issue, this is by design.

**Comment by Youssef1313** [comment]
> I'm not sure what you're trying to accomplish here. As I said in the issue, this is by design.

The reasoning for closing the issue as by design was mainly about security. The fix here simply doesn't impose any security risks.

**Comment by TheRealAmazonKendra** [comment]
The bot can't request changes on a branch created from a fork. This change is not needed. Closing this again.

**Comment by Youssef1313** [comment]
This is not the goal of the PR. 
The goal is making sure there are no build errors and that all tests are passing. So this is a typical build and test workflow.

**Pull request closed without merging**
