### PR TITLE
chore(opensearch): support OpenSearch version 2.17

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

N/A

### Reason for this change
Support  OpenSearch version 2.17.
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/release-notes.html

### Description of changes
Add Enum.

### Description of how you validated changes
Add unit tests and integ tests.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mazyu36** [comment]
Exemption Request: As this only involves adding an enum for versions, I think that modifying the README was unnecessary.

**Review by GavinZZ — APPROVED** [review]
Thank you! I'd treat it more as a chore as it's version support. Updating the title.

**Comment by mazyu36** [comment]
@mergifyio update

**Comment by mazyu36** [comment]
@mergifyio refresh

**Review by badmintoncryer — APPROVED** [review]

**Comment by mazyu36** [comment]
@mergifyio update

**Comment by mazyu36** [comment]
@mergifyio refresh

**Comment by mazyu36** [comment]
@Mergifyio update

**Comment by mrgrain** [comment]
@mergifyio update

**Pull request merged**
