### PR TITLE
fix(aws-eks): support http proxy in EKS onEvent lambda

### PR DESCRIPTION
**Pull request by ryparker**
## Summary

Currently when a user wants to route all of the EKS lambda's `aws-sdk-js` requests through a proxy then they are [instructed to configure an env var named `HTTP_PROXY` or `http_proxy`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-eks-readme.html#cluster-handler).

e.g.
```ts
const cluster = new eks.Cluster(this, 'hello-eks', {
  version: eks.KubernetesVersion.V1_21,
  clusterHandlerEnvironment: {
    'http_proxy': 'http://proxy.myproxy.com'
  }
});
```

However the JS SDK [requires further configuration to enable proxy support](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html).

This PR:

**The below changes have been refactored to avoid use of `NodeJsFunction`. See the PR comments below for [reasoning](https://github.com/aws/aws-cdk/pull/16657#issuecomment-928260661) and [updated changes](https://github.com/aws/aws-cdk/pull/16657#issuecomment-928529421).**
- ~~Adds a `package.json` with the dependency ['http-proxy-agent'](https://github.com/TooTallNate/node-http-proxy-agent) to the `cluster-resource-handler/` lambda bundle~~
- ~~Uses `NodeJSFunction` to install lambda dependencies and bundle.~~
- Adds a condition that checks the environment for `HTTP_PROXY` or `http_proxy` values. If present then configures the aws-sdk to use that proxy (using `http-proxy-agent`).

~~Note: I placed the `http-proxy-agent` in the `devDependencies` of `package.json`. If the dependency is placed in the `dependencies` section then the CDK builder [throws an error: `NPM Package cluster-resources-handler inside jsii package '@aws-cdk/aws-eks', can only have devDependencies`](https://github.com/aws/aws-cdk/blob/7dae114b7aac46321b8d8572e6837428b4c633b2/tools/pkglint/lib/rules.ts#L1332)~~

Fixes: SIM D29159517, https://github.com/aws/aws-cdk/issues/12469

Tested this using squid proxy on an ec2 instance within the same VPC as the EKS cluster.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ryparker** [comment]
@otaviomacedo Would you be able to help me get this released? I found the [release docs](https://github.com/aws/aws-cdk/blob/master/docs/release.md) state to run `./bump.sh` to perform a minor bump. Is that all that I need to do to trigger the release?

**Comment by ryparker** [comment]
> ### AWS CodeBuild CI Report
> * CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
> * Commit ID: [444cae4](https://github.com/aws/aws-cdk/commit/444cae428cdf333ae4dcf8f4196a916c5c3cf17e)
> * Result: FAILED
> * [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=03acbad5-f8b2-4be8-bf25-bb9200fcbb9b%2Fbuild.log) (available for 30 days)
> 
> _Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)_

Looks like CI is failing but passing locally.

Failure:

```sh
@aws-cdk/aws-eks: Bundling asset Stack/@aws-cdk--aws-eks.ClusterResourceProvider/OnEventHandler/Code/Stage...
@aws-cdk/aws-eks: FAIL test/service-account.test.js (15.937 s)
@aws-cdk/aws-eks:   â— service account â€º add Service Account â€º defaults should have default namespace and lowercase unique id
@aws-cdk/aws-eks:     Failed to bundle asset Stack/@aws-cdk--aws-eks.ClusterResourceProvider/OnEventHandler/Code/Stage, bundle output is located at /tmp/cdk.outzgYgUF/bundling-temp-4d81264e075d2e80c50708b10b07860eeab9a1dfc587b7e5c4cc63407f6728bf-error: Error: bash exited with status 1
@aws-cdk/aws-eks:       396 |
@aws-cdk/aws-eks:       397 |   /**
@aws-cdk/aws-eks:     > 398 |    * Determine the directory where we're going to write the bundling output
@aws-cdk/aws-eks:           |             ^
@aws-cdk/aws-eks:       399 |    *
@aws-cdk/aws-eks:       400 |    * This is the target directory where we're going to write the staged output
@aws-cdk/aws-eks:       401 |    * files if we can (if the hash is fully known), or a temporary directory
@aws-cdk/aws-eks:       at AssetStaging.bundle (../core/lib/asset-staging.ts:398:13)
@aws-cdk/aws-eks:       at AssetStaging.stageByBundling (../core/lib/asset-staging.ts:246:10)
@aws-cdk/aws-eks:       at stageThisAsset (../core/lib/asset-staging.ts:137:35)
@aws-cdk/aws-eks:       at Cache.obtain (../core/lib/private/cache.ts:24:13)
@aws-cdk/aws-eks:       at new AssetStaging (../core/lib/asset-staging.ts:162:44)
@aws-cdk/aws-eks:       at new Asset (../aws-s3-assets/lib/asset.ts:68:21)
@aws-cdk/aws-eks:       at AssetCode.bind (../aws-lambda/lib/code.ts:183:20)
@aws-cdk/aws-eks:       at new Function (../aws-lambda/lib/function.ts:331:29)
@aws-cdk/aws-eks:       at new NodejsFunction (../aws-lambda-nodejs/lib/function.ts:51:5)
@aws-cdk/aws-eks:       at new ClusterResourceProvider (lib/cluster-resource-provider.ts:63:21)
```

**Review by otaviomacedo — APPROVED** [review]

**Comment by ryparker** [comment]
I'm a little concerned that the CI all of a sudden passed without an explicit change. Now it looks like it failed when mergify updated the branch with master.

It seems to be a bundling error. My PR uses the NodeJsFunction to bundle a NPM directory. I found a way to replicate the error locally by removing `esbuild`. 

I then did some issue searching and found this issue where someone states
> “Because the CDK uses jsii and the CDK team doesn’t currently want to bundle esbuild in the CDK we cannot use the Node.js API or declare esbuild as a peer dependency unfortunately.”

[_link to comment_](https://github.com/aws/aws-cdk/issues/13179#issuecomment-783196697)

If we don’t support bundling `esbuild` with our packages then perhaps I should avoid using the `NodeJsFunction` in the aws-eks package. Instead I could create a lambda layer with `http-proxy-agent` installed. @otaviomacedo thoughts?

**Comment by ryparker** [comment]
I'm deploying this manually and testing proxy is in fact being used.

**Comment by ryparker** [comment]
I can confirm that the onEvent lambda now routes traffic to the proxy provided in the `http_proxy` `Cluster` prop.

<kbd>

CleanShot 2021-09-27 at 21 15 38@2x

</kbd>

**Comment by ryparker** [comment]
@otaviomacedo I re-requested your review since I made a major refactor of my fix.

**Comment by ryparker** [comment]
@Mergifyio refresh

**Review by G3N3R4LE4RL — APPROVED** [review]

**Review by otaviomacedo — APPROVED** [review]

**Pull request merged**
