### PR TITLE
chore(dynamodb): do not install aws-sdk in replica handler

### PR DESCRIPTION
**Pull request by jogold**
### Commit Message

chore(dynamodb): do not install aws-sdk in replica handler (#7047)

The Node.js 12.x runtime now comes with AWS SDK for JavaScript v2.631.0. Installation
of the latest version is no longer necessary (`ReplicaUpdates` has been introduced in
v2.577.0).

### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
https://github.com/awsdocs/aws-lambda-developer-guide/pull/171#issuecomment-606893332

**Comment by RomainMuller** [comment]
@jogold thanks for that! Have you been able to run the integration tests over this change (I wanna make sure this deploys cleanly, still - the code looks okay, but runtime can be treacherous)? I can do it otherwise...

**Comment by jogold** [comment]
> @jogold thanks for that! Have you been able to run the integration tests over this change (I wanna make sure this deploys cleanly, still - the code looks okay, but runtime can be treacherous)? I can do it otherwise...

Yes, updated the `.expected.json` by running the integ test here.

**Comment by RomainMuller** [comment]
Ergh... this got merge conflicted on the integration test expectations... 😔

I'll get back here and resolve that unless you beat me to it 😅

**Comment by jogold** [comment]
> I'll get back here and resolve that unless you beat me to it 😅

on it

**Comment by RomainMuller** [comment]
> > I'll get back here and resolve that unless you beat me to it 😅
> 
> on it

**Comment by jogold** [comment]
@RomainMuller can you check again?

**Pull request merged**
