### PR TITLE
chore: upgrade jsii to v1.2.0

### PR DESCRIPTION
**Pull request by MrArnoldPalmer**
### Commit Message

COMMIT MESSAGE HERE (preserve newline after "Commit Message" heading)

### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by MrArnoldPalmer** [comment]
@eladb @rix0rrr @RomainMuller @NetaNir 

Lets talk about the JSII upgrade here yay!

So first thing, jsii-reflect has some changes to types that it exposes making some properties `readonly`. This required us to make the code changes in `awslint` to convince the typescript compiler that we aren't mutating its precious "readonly properties" in `flatMap`. We may be able to change the type signature of `flatMap` itself to let typescript know that the function is "pure" but that feels kinda outside typescript's wheelhouse because that obviously means the callback has to also be "pure". @RomainMuller I defer to you here because reasons.

The second thing is that jsii-diff now shows a bunch of incompatible API changes in various cdk modules since last release. Mostly superclasses that were once being extended no longer are.

```
err  - CLASS @aws-cdk/core.Construct: not assignable to all base types anymore: @aws-cdk/core.Construct does not extend @aws-cdk/core.IDependable [base-types:@aws-cdk/core.Construct]
```

I assume this is a bug with `jsii-diff` from the recent change we made to detect removal of superclasses from the inheritance chain. I think maybe this isn't going further than one level up to check?

**Comment by eladb** [comment]
I am okay with massaging `awslint` so compiler is happy.

And `Construct` is expected to implement `IDependable` but it seems like it’s done thought `IConstruct` and not directly, which means you are right that it’s a bug in jsii diff (copy @rix0rrr). For now, just add `IDependable` as a direct interface of `core.Construct`.

**Comment by NetaNir** [comment]
While we are on the topic, a few notes.
#### Why didn't we see `awslint` breakage on JSII fancy new integ tests?
The new integ tests verifies that the new version of JSII successfully build the @aws-cdk modules, `aws-lint` uses JSII as a dependency and is not build by it.

#### Can we release the CDK with a previous version of JSII?
Yes, but there is as somewhat minor concern, since the JSII modules upgrade is a minor version upgrade (`1.1.0` -> `1.2.0`), modules which depends on the JSII, if consume by users directly, it might still resolved to `1.2.0`. Since the only non private module that takes a dependency on JSII is  `decdk`, is not effected by this upgrade this is a minor concern.

#### Maybe we should use fixed dependencies for JSII modules?
We can, and this even makes sense since we manually upgrade JSII dependencies in the CDK. We do this since they required to be upgraded as a single unit, which is not supported by our dependency bot. However this brings us to an issue we encounter in the past. If module A defines a dependency on a fixed version of a JSII module B and a fixed version of JSII module C, while model B defines a `^` version dependency on Module C, this will result in module B having nested `node_modules` to satisfy `^` which may result in TS compilation errors. 
Again this is a minor concern, but I thought it's a good opportunity to write this up in case someone else is contemplating on this.

**Comment by MrArnoldPalmer** [comment]
@eladb sorry shoulda been more clear. That was one example of many (10s of them!) So we gotta fix this first. Will work with @rix0rrr on that.

**Comment by rix0rrr** [comment]
https://github.com/aws/jsii/pull/1492

I'm sorry all!

**Comment by rix0rrr** [comment]
@MrArnoldPalmer don't forget to update the PR description

**Comment by MrArnoldPalmer** [comment]
Closing in favor of https://github.com/aws/aws-cdk/pull/7393

**Pull request closed without merging**
