### PR TITLE
chore(rds): deprecate PostgreSQL 10.x

### PR DESCRIPTION
**Pull request by robertd**
I received this email today. Hence, it's time to put a deprecation notice on Postgres 10.x . :wave:

```email
[Action Required] Amazon RDS for PostgreSQL is deprecating major version 10

Hello,

You are receiving this message because you have one or more Amazon RDS DB instances running with the deprecated 
PostgreSQL major version 10 that requires your attention. The PostgreSQL community deprecated PostgreSQL 10 on
 November 10, 2022 [1] and it has not received any security patches since November 10, 2022.

Your affected Amazon RDS DB Instances are listed in the "Affected Resources" tab of the AWS Health Dashboard.

On September 1, 2022, Amazon RDS for PostgreSQL announced the deprecation of PostgreSQL major version 10. 
We recommend you take immediate action, and upgrade your databases to a later major version, such as PostgreSQL 14
 before April 17, 2023. Should you not take action, Amazon RDS will automatically upgrade your PostgreSQL 10 databases
 to PostgreSQL 14 during a scheduled maintenance window between April 17, 2023 00:00:01 UTC and July 18, 2023 
00:00:01 UTC. After July 18, 2023 00:00:01 AM UTC, any PostgreSQL 10 databases that remain will be automatically 
upgraded to version 14 regardless of your scheduled maintenance window.

PostgreSQL 14 includes performance improvements for parallel queries, heavily-concurrent workloads, partitioned tables,
 logical replication, and vacuuming. To learn more about the benefits of PostgreSQL 14, please refer to ‘PostgreSQL 14
 Community Release Announcement’ [2].

To upgrade your DB instance from major version 10, we recommend that you first upgrade your current version of database
 to the PostgreSQL 10.21 or later, and then perform an upgrade to a later major version. To learn more about upgrading
 PostgreSQL major versions in RDS, review the 'Upgrading Database Versions' page [3].

Please note minor versions 10.17, 10.18, 10.19 and 10.20 will reach end of standard support on March 20, 2023, as we 
communicated during January 2023. For end of standard support dates of all versions, please refer to the release calendar
 for Amazon RDS for PostgreSQL [4].

If you have any questions or concerns, the AWS Support Team is available on AWS re:Post [5] and via Premium Support [6].
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by comcalvi — DISMISSED** [review]
Some of these versions are still used by tests, eg:

```
  test('addRotationSingleUser()', () => {
    // GIVEN
    const instance = new rds.DatabaseInstance(stack, 'Database', {
      engine: rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_10 }),
      vpc,
    });
```

Could you update these to the latest (15)?

**Comment by robertd** [comment]
@comcalvi I've updated all test to reference `VER_15_2`. 

I also had to remove a test case that was testing `VER_10_6`'s missing feature.
```
    test('returns no features for older versions', () => {
      const engineNewerVersion = rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_10_6 });

      const engineConfig = engineNewerVersion.bindToInstance(new cdk.Stack(), {});
      expect(engineConfig.features?.s3Import).toEqual(undefined);
      expect(engineConfig.features?.s3Export).toEqual(undefined);
    });
```

**Comment by robertd** [comment]
@comcalvi Speaking of which... do we ever get to remove deprecated params? i.e. I see `9.x` is still there.

**Comment by robertd** [comment]
@comcalvi ready for your review

**Comment by robertd** [comment]
poke @comcalvi @kaizencc

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
