### PR TITLE
docs: Added beta header

### PR DESCRIPTION
**Pull request by Doug-AWS**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

Updates doc build script to overwrite layout in any python lib so it contains a header; supplies the header.

Screen shot:

image

### CODE REVIEW

**Comment by Doug-AWS** [comment]
The only change to layout.html is the addition of line 169, to enable a header.

**Comment by rix0rrr** [comment]
Functionally okay, but ugly.

Might I suggest the following CSS:

https://jsfiddle.net/vqz63jp2/

**Comment by eladb** [comment]
Also we don’t use the term “beta” but rather developer preview

**Comment by Doug-AWS** [comment]
<p style="background-color:#e47911; border-top:1px solid #ccc; margin-top:6px; padding-top:10px; padding-bottom:10px; padding-left:5px; font-weight:bold; font-style:italic; font-size:16px; color:white; vertical-align:middle">

renders as:

image

**Comment by Doug-AWS** [comment]
The header uses "developer preview", not "beta". Here's the paragraph style:

"background-color:#e47911; border-top:1px solid #ccc; margin-top:6px; padding-top:10px; padding-bottom:10px; padding-left:5px; font-weight:bold; font-style:italic; font-size:16px; color:white; vertical-align:middle"

**Comment by Doug-AWS** [comment]
Not sure why there are 7 files in this PR. I'm closing and trying again.

**Pull request closed without merging**
