### PR TITLE
fix(dynamodb): Support iampolicy minimize credential

### PR DESCRIPTION
**Pull request by watany-dev**
fixes https://github.com/aws/aws-cdk/issues/20545

As noted in the link below, the following IAM Policy permissions appear sufficient for this support.
- dynamodb:DescribeTable
- dynamodb: UpdateTable

https://github.com/aws/aws-cdk/issues/20545#issuecomment-1218166746

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
I'm concerned that this has the potential to break user's functionality. How do we know that these are the only two permissions needed?

**Comment by watany-dev** [comment]
I'll explain some of the overlap with what I wrote in this link
https://github.com/aws/aws-cdk/issues/20545#issuecomment-1218166746

The IAMRole (onEvent) to which privileges are added in this process is granted to this Lambda.

https://github.com/aws/aws-cdk/blob/75bfce70dbc57fe688c96b3c5cbb67fc4e6fcc56/packages/%40aws-cdk/aws-dynamodb/lib/replica-handler/index.ts

When checking the AWS SDK for this code, I confirmed that only two DynamoDB actions are available.

**Comment by TheRealAmazonKendra** [comment]
> I'll explain some of the overlap with what I wrote in this link [#20545 (comment)](https://github.com/aws/aws-cdk/issues/20545#issuecomment-1218166746)
> 
> The IAMRole (onEvent) to which privileges are added in this process is granted to this Lambda.
> 
> https://github.com/aws/aws-cdk/blob/75bfce70dbc57fe688c96b3c5cbb67fc4e6fcc56/packages/%40aws-cdk/aws-dynamodb/lib/replica-handler/index.ts
> 
> When checking the AWS SDK for this code, I confirmed that only two DynamoDB actions are available.

The problem is that often under the hood, the visible APIs call other APIs that this change may now remove permissions for. This is especially true for CloudFormation calls. They are often doing more under the hood than is visible. [This comment block](https://github.com/aws/aws-cdk/blob/75bfce70dbc57fe688c96b3c5cbb67fc4e6fcc56/packages/%40aws-cdk/aws-dynamodb/lib/replica-handler/index.ts#L16-L22) gives me even more pause.

**Comment by blncoxauto** [comment]
@TheRealAmazonKendra The [changes in the policy will be limited to the ReplicaProvider Lambda CRP runtime](https://github.com/aws/aws-cdk/blob/75bfce70dbc57fe688c96b3c5cbb67fc4e6fcc56/packages/%40aws-cdk/aws-dynamodb/lib/replica-provider.ts#L83) though, right? I believe we just need to make sure that the SDK calls for that specific resource provider have been granted the appropriate permissions.

We're running into the same issue with security scans flagging the role that gets created to do the replicated table management.

**Pull request closed without merging**
