### PR TITLE
chore(lambda): fix StreamEventSourceProps docs

### PR DESCRIPTION
**Pull request by nmussy**
Correct `batchSize` JSDoc (`DynamoEventSourceProps` max was incorrect)

Related to #4260

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nmussy** [comment]
Not sure why the build failed there, did it just stop?

**Comment by nmussy** [comment]
Seems like a JSII error:
`@aws-cdk/aws-lambda-event-sources: Interface declares same member as inherited interface: batchSize`

Any idea, or should we ping Romain?

**Comment by nija-at** [comment]
Hello @nmussy. 
For now, I would suggest not to replicate the member in the subclasses. Instead, update the documentation to say that the max ranges is 1000 when using Dynamo and 10000 when using Kinesis.
This would also be a useful feature for JSII to support, so perhaps you could open an issue in the JSII repo requesting this.

**Comment by nmussy** [comment]
Thanks @nija-at, it should be fixed now. I opened an issue in JSII as you suggested: [jsii#869](https://github.com/aws/jsii/issues/869)

**Pull request merged**
