### PR TITLE
feat(cognito): add support for token revocation in UserPoolClient

### LINKED ISSUE #15126: aws-cognito: support token revokation
Cognito [recently introduced token revocation](https://aws.amazon.com/about-aws/whats-new/2021/06/amazon-cognito-now-supports-targeted-sign-out-through-refresh-token-revocation/), which needs to be enabled at the user pool level, but is apparently not yet supported by CDK.

### Use Case

To revoke tokens; same reason as why Cognito introduced it.

### Proposed Solution

[According to the Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/token-revocation.html), the `EnableTokenRevocation` parameter needs to be set for the user pool. Thus, the builders of `UserPool`, `UserPoolClient` and `UserPoolResourceServer` probably need such a parameter.

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by jumic**
Add support for token revocation in UserPoolClient.

For new user pool clients, token revocation is enabled by default. Property `enableTokenRevocation` introduces the possibility to enable token revocation for existing user pool clients.

Closes #15126

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by peterwoodworth — DISMISSED** [review]
Looks great, thank you for the contribution!

**Comment by jumic** [comment]
@peterwoodworth Thank you for approving this PR. 👍 Because of the missing description in the readme, I hat to change the PR. Could you please review it again?

**Comment by peterwoodworth** [comment]
Thanks for the additional readme comment 😄 

Could you add one more test which ensures you can set this variable through the L2 construct `UserPoolClient` rather than just the `addClient()` method?

**Comment by jumic** [comment]
Additional test is added as requested. (Not sure if this comment is necessary to mark this change as done).

**Review by peterwoodworth — DISMISSED** [review]
Looks great, thanks!

**Comment by jumic** [comment]
The build failed after the current master branch was merged to this branch. Class TemplateAssertions was renamed to Template. I corrected the name in the test cases of this PR.
Could you please review the changes again? Thanks.

**Review by peterwoodworth — APPROVED** [review]
Sorry for the delay here, and thank you for the contribution 🙏

**Pull request merged**
