### PR TITLE
fix(cdk): go template breaks go list

### LINKED ISSUE #13971: (aws-cdk): go template breaks go list
#13840 added an app template for go and the filenames break `go list ./...` when cdk project is embedded inside of a Go project.

### Reproduction Steps

```bash
mkdir project
cd project
cdk init app --language=typescript
go mod init github.com/test/project
echo "package main\nfunc main() { return }\n" > main.go
go list ./... # fails because of template files

package github.com/test/project/node_modules/aws-cdk/lib/init-templates/v1/app/go: invalid input file name "%name%.template.go"
```

### What did you expect to happen?

I expected `go list ./...` to return a list of package names.

### What actually happened?

List of package name was not returned and an error was returned instead.

```
package github.com/test/project/node_modules/aws-cdk/lib/init-templates/v1/app/go: invalid input file name "%name%.template.go"
```

### Environment

  - **CDK CLI Version:** 1.96.0 (build 39f3df8)
  - **Framework Version:** ?
  - **Node.js Version:** v15.13.0
  - **OS               :** macOS 11.2.3
  - **Language (Version):** all
  - **Go (Version):** 1.16.3

### Other

I think it might be possible to add an empty `go.mod` file into the template directory to prevent this from happening, but I'm hardly an expert in Go.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by daschaa**
Fixes aws/aws-cdk-cli#648

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
Have you run the tests for this? They don't run automatically in the build. If not (the instructions for doing this might not be easy to find and/or might not exist), I can run this through our test pipeline.

**Comment by daschaa** [comment]
@TheRealAmazonKendra No I haven't run them, thanks for pointing this out! It would be very cool if you could run them in your test pipeline and I will try to run them on my own too. Can I just follow the guide in the `CONTRIBUTING.md` in this package? Will the stacks for the integration tests produce (significant) costs?

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra No I haven't run them, thanks for pointing this out! It would be very cool if you could run them in your test pipeline and I will try to run them on my own too. Can I just follow the guide in the `CONTRIBUTING.md` in this package? Will the stacks for the integration tests produce (significant) costs?
> 
> Thanks in advance! :)

Nothing gets deployed in these tests so no cost, but I'm not sure that we have documentation about these. I'll get them run tomorrow. I'm a little concerned that there will be some unforeseen consequences of this change, but I suppose that's what the tests are for.

**Comment by TheRealAmazonKendra** [comment]
Not sure why the PR Bot didn't respect the do-not-close label, but I'll reopen this once I get the tests fixed.

**Comment by daschaa** [comment]
@TheRealAmazonKendra Thank you! :)

**Comment by daschaa** [comment]
@TheRealAmazonKendra Any updates regarding the tests? :)

**Pull request closed without merging**
