### PR TITLE
fix(init): TypeScript code is not being recompiled automatically

### PR DESCRIPTION
**Pull request by ghost**
The use of `npx ts-node` to run the app in the TypeScript init templates is intended to make sure the source code gets transpiled before every synth without the user needing to `npm run build` explicitly. I have had reports on the Hello World dev guide topic that an `npm run build` is still needed, even though it shouldn't be. I was able to reproduce this issue today (was not able to do so previously).

The problem is that, by default, `ts-node` prefers resolving imports to JavaScript files. If a JavaScript file exists, as it would be after the first build, it is simply imported as-is. The corresponding TypeScript module is not transpiled. Therefore changes you make to the TS code are never picked up and stale JS code is used.

The flag `--prefer-ts-exts` solves this issue. It causes module imports to prefer importing TypeScript files, which means that the modules will get recompiled if necessary.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Jerry-AWS** [comment]
Reported by a CDK Dev Guide reader in https://github.com/awsdocs/aws-cdk-guide/issues/284

**Review by eladb — APPROVED** [review]

**Comment by Jerry-AWS** [comment]
@eladb What do I need to do to get this merged now that you've reviewed it?

**Review by eladb — CHANGES_REQUESTED** [review]
Which `ts-node` version introduces this feature?

It seems like the version declared in the template's package.json does not include this:

```shell
$ npx ts-node@8.1.0 --help

Usage: ts-node [options] [ -e script | script.ts ] [arguments]

Options:

  -e, --eval [code]              Evaluate code
  -p, --print                    Print result of `--eval`
  -r, --require [path]           Require a node module before execution

  -h, --help                     Print CLI usage
  -v, --version                  Print module version information

  -T, --transpile-only           Use TypeScript's faster `transpileModule`
  -I, --ignore [pattern]         Override the path patterns to skip compilation
  -P, --project [path]           Path to TypeScript JSON project file
  -C, --compiler [name]          Specify a custom TypeScript compiler
  -D, --ignore-diagnostics [code] Ignore TypeScript warnings by diagnostic code
  -O, --compiler-options [opts]   JSON object to merge with compiler options

  --files                        Load files from `tsconfig.json` on startup
  --pretty                       Use pretty diagnostic formatter
  --skip-project                 Skip reading `tsconfig.json`
  --skip-ignore                  Skip `--ignore` checks
```

**Comment by Jerry-AWS** [comment]
@eladb Looks like it was introduced in v8.3.0 from June of 2019.

https://www.npmjs.com/package/ts-node/v/8.3.0

I'll update the `package.json`.

**Comment by eladb** [comment]
Can you please confirm that you tested this change by creating a new project using a local build?

**Comment by Jerry-AWS** [comment]
I can confirm I was able to build the CLI from this PR on GitPod, create a new project, verify the cdk.json and package.json changes, and synth the new project.

**Review by eladb — APPROVED** [review]

**Pull request merged**
