### PR TITLE
fix(aws_s3): fixed notification handler role bug identified in issue 20702

### LINKED ISSUE #20702: aws_cdk.s3: IAM policy created despite using notifications_handler_role
### Describe the feature

When creating an instance of s3.Bucket, I use notifications_handler_role to explicitly choose an IAM role to be used for the Lambda function that will create the bucket notifications. Despite that, CDK generates an IAM policy and attaches it to the role that I provided. For example:

`  HandlerRolePolicy39F50E2E:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:PutBucketNotification
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: HandlerRolePolicy39F50E2E
      Roles:
        - s3_handler_role
    Metadata:
      aws:cdk:path: AspectsStack/HandlerRole/Policy/Resource`

I do NOT want a policy created. I will add the correct policies to the role as needed.

### Use Case

I work in an environment where I do not have permission to create IAM roles or policies. Those are created by a central admin team. I need CDK to NOT create any roles or policies.

### Proposed Solution

In the implementation of notifications_handler_role, do not create a new policy.

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.27.0 (build 8e89048)

### Environment details (OS name and version, etc.)

AWS Cloud9

### PR DESCRIPTION
**Pull request by patrickmryan**
When using "notifications_handler_role", the existing code would attempt to add additional policies to the role, regardless of whether it was an existing role or note. The patched code will only add new policies when a new IAM role is being created.

closes #20702

### CODE REVIEW

**Review by peterwoodworth — CHANGES_REQUESTED** [review]
Thanks for the submission @patrickmryan,

This change as you have it break existing users who are passing their own roles and relying on CDK to add the appropriate permissions. I understand your use case however, maybe there's some way where we can make this functionality you desire optional

Also, we will need to test the new functionality you provide with unit testing 🙂

**Comment by patrickmryan** [comment]
Thanks for the feedback @peterwoodworth. I understand the concern but I disagree with the existing design. If I explicitly provide an IAM role to be used for this purpose, I would not want CDK tweaking the policies attached to the role. In my specific customer environment, I cannot create roles or policies. I have to provide existing roles that cannot be modified. Under the current design, I cannot add bucket notifications via CDK.

(FYI, I do know about IAM permissions boundaries. For reasons that are stupid and boring, I cannot create an IAM role, even with a permissions boundary. I will not waste your time explaining why I cannot use that excellent feature.)

All that said, I will go back and figure out how to add a unit test for my PR.

**Comment by corymhall** [comment]
@patrickmryan I think in this case you should use [withoutPolicyUpdates()](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Role.html#withoutwbrpolicywbrupdatesoptions) with the role you create and pass in. This will prevent CDK from attaching any policies to the role.

```ts
const role = new iam.Role(...).withoutPolicyUpdates()
new NotificationsResourceHandler(this, 'Handler', {
  role,
});
```

**Comment by patrickmryan** [comment]
Will resolve this issue another way.  Likely modification to IRole.

**Pull request closed without merging**
