### PR TITLE
fix(cli): `cdk context --reset <number>` does not work

### LINKED ISSUE #3033: `cdk context --reset <number>` does not work
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**
Running `cdk context` outputs a table with indices for the current context entries. On the bottom of the output there's a text `Run cdk context --reset KEY_OR_NUMBER to remove a context key. It will be refreshed on the next CDK synthesis run.`. However, running `cdk context --reset 1` will error with:

  ```
  No context key with number: 1
  ```

* **What is the expected behavior?**
  Resetting a context entry works when passed a number.

* **Please tell us about your environment:**
  - CDK CLI Version: 0.35.0

* **Other information**
  I debugged this a bit and it seems that regardless of the amount of context entries, the index to key mapping will _always_ be `[[1, 'bags']]`; I'm guessing the context is now wrapped in a distinct `Context` structure which the reset functionality does not take into account.

### PR DESCRIPTION
**Pull request by diesal11**
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

Fixes #3033

### CODE REVIEW

**Review by rix0rrr — APPROVED** [review]
Thanks!

**Comment by NetaNir** [comment]
Hi @diesal11! 
I had to revert this as it was breaking `cdk context`, I have added a simple unit test that should help with fixing this PR. 
Let me know if you want to pick it up, of not I will. Thanks!

**Comment by diesal11** [comment]
No worries @NetaNir. I was concerned that the test coverage was a little low to be sure something like this wouldn't happen. My apologies as i should have mentioned that in the initial PR.

Jumping back on this now 👍

**Comment by diesal11** [comment]
@NetaNir Fixed :)

I've had to create a new PR (#10753) as i had already deleted my fork which this PR was based off.

**Pull request merged**
