### PR TITLE
feat(sns): topic name with `.fifo` suffix generated automatically

### PR DESCRIPTION
**Pull request by dreamorosi**
This PR adds logic for automatic generation of FIFO topics.

When customers don't pass a `topicName` during creation, the construct now generates an unique name that respects the maximum length allowed by the CloudFormation resource (256) and that ends with the `.fifo` suffix.

The previous behavior was to throw an error when the topic was of type FIFO and no name was passed.

Fixes ##18740

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by dreamorosi** [comment]
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Features must contain a change to a README file.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.

In this specific case the PR addresses an implementation detail inside the construct which in turns compensates a [roadmap item from CloudFormation](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/681). 

I'm not sure it needs a README change, if it does I'd appreciate some guidance as for where/what to change.

**Review by corymhall — CHANGES_REQUESTED** [review]
> I'm not sure it needs a README change, if it does I'd appreciate some guidance as for where/what to change.

Can you update the section of the readme that talks about fifo topics? Update the example to not pass a name and note that one will be generated for you.

https://github.com/aws/aws-cdk/blob/635129ca95313afef7b3d8fc62d077afbfd0c088/packages/%40aws-cdk/aws-sns/README.md?plain=1#L22-L33

**Comment by dreamorosi** [comment]
> Can you update the section of the readme that talks about fifo topics? Update the example to not pass a name and note that one will be generated for you.

Done in the latest commit

**Review by corymhall — APPROVED** [review]
Thanks @dreamorosi!

**Pull request merged**
