### PR TITLE
chore (docs): Rename default Python stack to HelloCDkStack

### PR DESCRIPTION
**Pull request by Doug-AWS**
----

### Pull Request Checklist

* [ ] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by rix0rrr** [comment]
Why this change?

**Comment by rix0rrr** [comment]
If anything, this should be in the `sample-app` template.

**Comment by Doug-AWS** [comment]
Because every other template uses "HelloCdkStack", thus making all of the descriptions of using the templates consistent. Actually we have bigger consistency problems:

- Should the default template create one stack, with no resources? It does in TypeScript and Python, but no other language.
- Should the **sample-app** template create a CDK app with two stacks? Both stacks containing an SQS queue, an SNS topic, an IAM policy document so the topic could send messages to the queue, and a user-created construct. Each stack calls the user-created construct to create five (four in Python) S3 buckets, create a new user, and give the user access to the S3 buckets. *The TypeScript version creates a CDK app with stack containing an SQS queue, an SNS topic, and an IAM policy document so the topic could send messages to the queue.*

**Comment by eladb** [comment]
That doesn't make sense. The current implementation is what we want. If at all, let's fix the other templates.

**Pull request closed without merging**
