### PR TITLE
feat(cdk): add kotlin gradle init

### PR DESCRIPTION
**Pull request by michaelbrewer**
## Description

Add Kotlin init examples using Gradle (this could also be used for Java Gradle init templates)

This could alternatively be used to resolve: https://github.com/aws/aws-cdk/issues/1293

## Reasons for this template

- Gradle is ultimately faster for building and running CDK stack than Maven
- Kotlin has the same static typing that Java has, plus more when considering types for nullability
- Kotlin is a much more concise and user friendly than older versions of Java but can still target these older JVMS.

image
Maven build performance (first is a clean build and second is a incremental build)

image
Gradle build performance  (first is a clean build and second is a incremental build) 

## Things to consider

  - Testing libraries used Kotlin test or Junit 5
  - Assertions library used
  - Logging dependency (even the basic java example does not include a logging library)

## Checklist

- [x] Add Kotlin app template for V1
- [ ] Add Kotlin sample-app template for V1
- [ ] Add Kotlin app template for V2
- [ ] Add Kotlin sample-app template for V2

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by michaelbrewer** [comment]
@rix0rrr  it is cool to continue with this, i will add the samples and v2 version

**Comment by rix0rrr** [comment]
Hi @michaelbrewer, I appreciate the submission but I'm a little hesitant to accept it.

It's great as an initial submit, but all code will have to be maintained for the future and we don't have the expertise to maintain this. 

Wouldn't it be better to vend a [cookiecutter](https://github.com/cookiecutter/cookiecutter) template instead?

If you really want this in the CDK, I would request that you also add some facilities to the CLI to mark certain init templates as `UNSUPPORTED`, and I would expect the users to be informed that the template is unsupported when listing and when it's executing. We will not add it to our test suite and we will not keep it up to date. If it breaks, it breaks.

**Comment by michaelbrewer** [comment]
> Hi @michaelbrewer, I appreciate the submission but I'm a little hesitant to accept it.
> 
> It's great as an initial submit, but all code will have to be maintained for the future and we don't have the expertise to maintain this.
> 
> Wouldn't it be better to vend a [cookiecutter](https://github.com/cookiecutter/cookiecutter) template instead?
> 
> If you really want this in the CDK, I would request that you also add some facilities to the CLI to mark certain init templates as `UNSUPPORTED`, and I would expect the users to be informed that the template is unsupported when listing and when it's executing. We will not add it to our test suite and we will not keep it up to date. If it breaks, it breaks.

I have found that the current cdk templates (like Maven and Java or the Python one), to now really work.

For example we use Gradle (and i am sure more Java developers have moved over to this) and the performance difference is notable.

For Python more people would use something like PipEnv or Poetry over using Setup.py.

**Comment by rix0rrr** [comment]
> For Python more people would use something like PipEnv or Poetry over using Setup.py.

I appreciate that these are "better" in some dimension, but we are aiming for "standard" and "familiar". If people are experienced enough to know that they want a non-standard package manager, they are experienced enough to know how to set that up, and even how to make it easier for themselves.

We need to cater to a wide audience, and prefer to stay on standard tooling as much as possible (i.e., the tooling that's most broadly understood and also the easiest to get Google hits on).

"init templates" are not our area of core competence: this is not where we are innovating, so let's not try to do too many things at once.

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Would prefer to see an external project template solution.

**Comment by michaelbrewer** [comment]
Ok @rix0rrr fair enough, I will close this, and create a Projen or CookieCutter template.

FYI, Gradle has been gaining transaction since Android, Spring and other popular java frameworks use it by default. So I would revisit this (https://github.com/aws/aws-cdk/issues/1293)

Also here is a comparison or Maven or Gradle for completeness:
- https://gradle.org/maven-vs-gradle/

**Comment by adrian-baker** [comment]
It would be great to at least have first class Gradle support, on par with the existing Maven support.

**Comment by michaelbrewer** [comment]
@adrian-baker - i would have liked it too.

**Pull request closed without merging**
