### PR TITLE
chore(cfnspec): add junit.xml to ignore files

### PR DESCRIPTION
**Pull request by NetaNir**
When generating a new module, add `junit.xml` to `.npmignore` and `.gitignore`, this is required by `aws-lint` rule. 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by shivlaks — APPROVED** [review]
I'd mark this as a `chore`.
Can you also add the motivation as well in the commit body: (i.e. we added `junit.xml` to gitignore to support test reports and we missed adding it when creating new libraries from the spec import`)

**Comment by NetaNir** [comment]
@Mergifyio refresh

**Review by shivlaks — APPROVED** [review]
looks good!

**Comment by NetaNir** [comment]
@Mergifyio update

**Pull request merged**
