### PR TITLE
feat(aws-cdk-lib): ADOT Lambda Layer v0.31.0

### PR DESCRIPTION
**Pull request by vasireddy99**
This PR adds New ADOT Lambda Layers v0.31.0 in the CDK library

Reference PR - 

- https://github.com/aws-observability/aws-otel-lambda/pull/653
- https://github.com/aws-otel/aws-otel.github.io/pull/596
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — APPROVED** [review]
Looks good to me (community reviewer) 👍

**Review by mrgrain — DISMISSED** [review]

**Comment by mrgrain** [comment]
@vasireddy99  are these published in a machine readable source anywhere?

**Review by mrgrain — APPROVED** [review]

**Comment by vasireddy99** [comment]
> @vasireddy99 are these published in a machine readable source anywhere?

I think the only readable source could be from here - https://github.com/aws-observability/aws-otel-lambda/pull/653/files . cause in terms of the publishing to customers we are just pasting ARNS in the website to use.

**Review by mrgrain — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]

**Comment by vasireddy99** [comment]
> 

actually, the layer is like in format -`arn:aws:lambda:<region\>:901920570463:layer:aws-otel-collector-<architecture\>-ver-0-82-0:1`. so the `region` and `architecture` are the fields that changes

**Pull request merged**
