### PR TITLE
feat: support CodeStar Notifications for CodeBuild and CodePipeline

### PR DESCRIPTION
**Pull request by luckily**
I am ready for the first run.

This PR is includes:

1. L2 construct for CfnSlackChannelConfiguration of chatbot package.

2. L2 construct for CfnNotificationRule of codestarnotification package.

3. `addNotification({...})` method of codebuild and codepipeline depend on above implements.

Resolves: #5020 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by luckily** [comment]
Hi Adam

Thanks for your feedback.

I have some ideas for this PR.

First, I create 3 issues for this feature.

Second, I split this PR to 3 PRs and link to their each issues.
The first one is for Chatbot.
The second one is for Codestar Notification,
And the last one is for about `addNotification({...})` method of Codebuild and Codepipeline.

We can review the each small parts after PRs submit again, and I will migrate tests from NodeUnit to Jest.

Maybe this PR can be deprecated.

Thanks,
Joel

**Comment by skinny85** [comment]
> Hi Adam
> 
> Thanks for your feedback.
> 
> I have some ideas for this PR.
> 
> First, I create 3 issues for this feature.
> 
> Second, I split this PR to 3 PRs and link to their each issues.
> The first one is for Chatbot.
> The second one is for Codestar Notification,
> And the last one is for about `addNotification({...})` method of Codebuild and Codepipeline.
> 
> We can review the each small parts after PRs submit again, and I will migrate tests from NodeUnit to Jest.
> 
> Maybe this PR can be deprecated.
> 
> Thanks,
> Joel

That sounds like a great plan 🙂.

Feel free to keep this PR open until create the other ones.

Thanks!

**Comment by bryan-hunter** [comment]
@luckily Thanks for this!

I copied over this code for now (until you get everything merged) - and it worked perfectly for me.

The only weird part I came across was: I wanted to use the same Slack Channel for multiple pipelines:
- I had to use `new SlackChannelConfiguration` in one pipeline and `SlackChannelConfiguration.fromSlackChannelConfigurationArn` in the other
- alternatively, I'd have to have something else dedicated to just owning the `new SlackChannelConfiguration` and everywhere else using the `SlackChannelConfiguration.fromSlackChannelConfigurationArn`

I think this is probably more due to AWS Chatbot not allowing you to configure the same Slack Channel twice, because that would solve a lot.


Also another small thing - I was using the newer `CdkPipeline` (`import { CdkPipeline } from '@aws-cdk/pipelines';`) which doesn't expose the pipelineArn very easily, so I had to generate it in order to pass it to the NotificationRule, but that was simple enough too.

```
const pipelineArn = Stack.of(this).formatArn({
    service: 'codepipeline',
    resource: 'MyPipelineName',
});
```

Just some notes in case it helps.  Thanks again!

**Comment by luckily** [comment]
> @luckily Thanks for this!
> 
> I copied over this code for now (until you get everything merged) - and it worked perfectly for me.
> 
> The only weird part I came across was: I wanted to use the same Slack Channel for multiple pipelines:
> 
> * I had to use `new SlackChannelConfiguration` in one pipeline and `SlackChannelConfiguration.fromSlackChannelConfigurationArn` in the other
> * alternatively, I'd have to have something else dedicated to just owning the `new SlackChannelConfiguration` and everywhere else using the `SlackChannelConfiguration.fromSlackChannelConfigurationArn`
> 
> I think this is probably more due to AWS Chatbot not allowing you to configure the same Slack Channel twice, because that would solve a lot.
> 
> Also another small thing - I was using the newer `CdkPipeline` (`import { CdkPipeline } from '@aws-cdk/pipelines';`) which doesn't expose the pipelineArn very easily, so I had to generate it in order to pass it to the NotificationRule, but that was simple enough too.
> 
> ```
> const pipelineArn = Stack.of(this).formatArn({
>     service: 'codepipeline',
>     resource: 'MyPipelineName',
> });
> ```
> 
> Just some notes in case it helps. Thanks again!

**Review by skinny85 — CHANGES_REQUESTED** [review]
Putting the PR in "Request changes" so that disappears from my to-do list.

@luckily are you still submitting smaller PRs for this? If you want, feel free to link them back to this one.

**Comment by luckily** [comment]
Hi @skinny85 

Sorry for the late update PRs.
Actually, The code of this PR has been done, but it seems not pretty good.
I have some question, hope to discuss with you.

In my proposal, I hope to add addNotification(...) method to codebuild module and codepipeline module, It is easy way to integrate notification with codebuild and codepipeline, but i encountered an issue about cyclic dependency. like as below:

Implemnets that getting codebuild/codepipeline ARN will get dependency as below:
aws-codestarnotifications (depends)-> aws-codebuild
aws-codestarnotifications (depends)-> aws-codepipeline

Implemnets the addNotification(...) method will get dependency as below:
aws-codebuild (depends)-> aws-codestarnotifications
aws-codepipeline (depends)-> aws-codestarnotifications

Cyclic dependency:
aws-codestarnotifications <-> aws-codebuild/aws-codepipeline

What do you think? And thanks for your patience.

**Comment by skinny85** [comment]
Hey @luckily ,

yes, this is s very common problem in the CDK 🙂. The solution is almost always to create a new package. In this case, it would be something like `@aws-cdk/aws-codestar-notifications-targets`. You would have that package depending on `@aws-cdk/aws-codebuild`, `@aws-cdk/aws-codepipeline`, etc. You probably would have a separate class for each target type - for example, a `CodeBuildTarget`, `CodePipelineTarget`, etc. They would take the appropriate type as its argument (`codebuild.IProject`, `codepipeline.IPipeline`, etc.). This way, you avoid the cycle between them.

Does this make sense?

**Comment by luckily** [comment]
I will give it a try. 🙂

**Comment by skinny85** [comment]
Take a look at how CloudWatch Events are modeled, and the `@aws-cdk/aws-events-targets` package - I assume the CodeStar notifications will follow a similar path.

**Comment by luckily** [comment]
Resolved by this PR #10833

**Pull request closed without merging**
