### PR TITLE
fix(lambda-layer-kubectl): update kubectl layer to use v1.22.0

### LINKED ISSUE #19843: (aws-eks): kubectl layer is not compatible with k8s v1.22.0
### Describe the bug

Running an empty update on an empty EKS cluster fails while updating the resource `EksClusterAwsAuthmanifest12345678` (`Custom::AWSCDK-EKS-KubernetesResource`).

### Expected Behavior

The update should succeed.

### Current Behavior

It's fails with error:
```
Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=Ingress, Namespaced=true: no matches for kind "Ingress" in version "extensions/v1beta1"\n' Logs: /aws/lambda/InfraMainCluster-awscdkawseksKubec-Handler886CB40B-rDGV9O3CyH7n at invokeUserFunction (/var/task/framework.js:2:6) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async onEvent (/var/task/framework.js:1:302) at async Runtime.handler (/var/task/cfn-response.js:1:1474) (RequestId: acd049fc-771c-4410-8e09-8ec4bec67813)
```

### Reproduction Steps

This is what I did:
1. Deploy an empty cluster:
```typescript
export class EksClusterStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);

    const clusterAdminRole = new iam.Role(this, "ClusterAdminRole", {
      assumedBy: new iam.AccountRootPrincipal(),
    });

    const vpc = ec2.Vpc.fromLookup(this, "MainVpc", {
      vpcId: "vpc-1234567890123456789",
    });

   const cluster = new eks.Cluster(this, "EksCluster", {
      vpc: vpc,
      vpcSubnets: [{ subnetType: ec2.SubnetType.PRIVATE_WITH_NAT }],
      clusterName: `${id}`,
      mastersRole: clusterAdminRole,
      defaultCapacity: 0,
      version: eks.KubernetesVersion.V1_22,
    });

    cluster.addFargateProfile("DefaultProfile", {
      selectors: [{ namespace: "default" }],
    });
  }
}
```
2. Add a new fargate profile
```typescript
    cluster.addFargateProfile("IstioProfile", {
      selectors: [{ namespace: "istio-system" }],
    });
```
3. Deploy the stack and wait for the failure.

### Possible Solution

_No response_

### Additional Information/Context

I checked the version of `kubectl` in the lambda handler and it's `1.20.0` which AFAIK is not compilable with cluster version `1.22.0`. I'm not entirely sure how the lambda is created. I thought it matches the `kubectl` with whatever version the cluster has. ~But it seems it's not~ It is not the case indeed (#15736).

### CDK CLI Version

2.20.0 (build 738ef49)

### Framework Version

_No response_

### Node.js Version

v16.13.0

### OS

Darwin 21.3.0

### Language

Typescript

### Language Version

3.9.10

### Other information
Similar to #15072?

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
Updated kubectl version for CDK v1 to 1.22. Because the Kubernetes version supported by EKS is now 1.22 and above, it no longer makes sense to use an older version of kubectl.

Closes #19843 #22604 for CDK v1

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mrgrain** [comment]
Hey @daisuke-yoshimoto 

I think this is the solution you are looking for:
https://www.npmjs.com/package/@aws-cdk/lambda-layer-kubectl-v22

But I realize our documentation might not be clear about this. 🤔

**Comment by daisuke-yoshimoto** [comment]
@mrgrain 

Now that the PR is out of draft status, please review it.

**Review by mrgrain — CHANGES_REQUESTED** [review]
Apologies for the delayed response @daisuke-yoshimoto 

I don't think we will be able to accept this change:
>AWS CDK v1 is no longer receiving higher-level “L2” construct updates for new or existing services. It will continue receiving updates for new and updated resource level “L1” constructs, critical bug fixes, and security updates only.  We recommend you upgrade your applications to the new major version of CDK – [AWS CDK version 2 (v2)](https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html), which continues receiving new features and bug fixes.

https://aws.amazon.com/blogs/developer/version-1-of-the-aws-cloud-development-kit-aws-cdk-is-now-in-maintenance-mode/

I also think this might be a breaking change with a risk of data loss. Checking with the EKS experts on our team.

**Comment by daisuke-yoshimoto** [comment]
@mrgrain 

I don't understand why it's a risk. 

Next week EKS will no longer have Kubernetes 1.20 and 1.21 clusters.
There's no point in keeping kubectl for 1.20 and 1.21, right?

I understand that you won't be making any major changes to CDK v1 anymore, but this is a pressing issue that needs to be addressed, so please include it.

> I also think this might be a breaking change with a risk of data loss. Checking with the EKS experts on our team.

**Comment by mrgrain** [comment]
> I don't understand why it's a risk.

Users on EKS 1.19 won't be able to use this version of kubectl.

**Comment by daisuke-yoshimoto** [comment]
@mrgrain 

Check [Amazon EKS Kubernetes release calendar](https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) carefully. 1.19 has been out of support for over a year now, so 1.19 clusters don't exist on EKS.

Kubernetes version | Upstream release | Amazon EKS release | Amazon EKS end of support
-- | -- | -- | --
1.25 | August 23, 2022 | March 2023 | May 2024
1.24 | May 3, 2022 | November 15, 2022 | January 2024
1.23 | December 7, 2021 | August 11, 2022 | October 2023
1.22 | August 4, 2021 | April 4, 2022 | May 2023
1.21 | April 8, 2021 | July 19, 2021 | February 15, 2023
1.20 | December 8, 2020 | May 18, 2021 | November 1, 2022
1.19 | August 26, 2020 | February 16, 2021 | August 1, 2022

**Comment by TheRealAmazonKendra** [comment]
The fix here is to move to v2. Is there anything major blocking you from being able to do so? As you noted, we put v1 into maintenance mode on July 1st of 2022 so we no longer backport updates unless they are security updates.

**Comment by daisuke-yoshimoto** [comment]
@TheRealAmazonKendra 

I will also send a PR to v2, so could you please merge this fix first? If you don't include this fix, users running EKS with cdk v1 will be in a lot of trouble. Users will not be able to update the manifest via cdk. I think this is a very serious bug.

Also, the documentation also says that critical bugs will be fixed until June 1, 2023. `It will continue receiving updates for new and updated resource level “L1” constructs, critical bug fixes, and security updates only. ` https://aws.amazon.com/jp/blogs/developer/version-1-of-the-aws-cloud-development-kit-aws-cdk-is-now-in-maintenance-mode/

Please, can you accept the modification? I think that users who are operating with cdk v1 are very troubled.

**Comment by mrgrain** [comment]
There is no need to create a PR for v2.

We have created a more flexible system for this, see the link I've posted earlier:

https://www.npmjs.com/package/@aws-cdk/lambda-layer-kubectl-v22

**Comment by daisuke-yoshimoto** [comment]
@mrgrain 

However, cdk v2 also has kubectl 1.20 set by default.
https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/lambda-layer-kubectl/package.json#L93
https://github.com/aws/aws-cdk/blob/f2e54478b69310291ccd76c498c4c6b2b4156ec7/packages/%40aws-cdk/lambda-layer-kubectl/package.json#L93

I think it is necessary to modify the default setting to `@aws-cdk/lambda-layer-kubectl-v22`.

**Comment by mrgrain** [comment]
Unfortunately changing the default version for the layer is a breaking change. We could introduce this behind a feature flag, but this would require us to depend on multiple layer packages, which isn't ideal either. I absolutely agree that the user experience isn't great here, but neither is breaking people. In hindsight, the `kubectlLayer` prop should have never been optional, given its tight coupling with the EKS version.

Not sure I currently see a way out of this. Maybe we could do some stuff with the `KubernetesVersion` class:
```ts
new Cluster(scope, id, {
  version: ClusterVersion.for(KubernetesVersion.V1_24, new KubectlV24Layer(this, 'kubectl'))
};

class ClusterVersion implements IKubernetesVersion {
  static public for(version: KubernetesVersion, kubectlLayer: ILayerVersion {
  }
}
```

And `props.kubectlLayer` would be deprecated and get new default check: `const kubectlLayer = props.version.kubectlLayer ?? props.kubectlLayer ?? currentDefault`

**Pull request closed without merging**
