### PR TITLE
feat(rds): add custom secret name to database instance from snapshot

### PR DESCRIPTION
**Pull request by gfkl**
Add possibility to customize name of secret generated for database instance created from snapshot using `SnapshotCredentials.fromGeneratedSecret`

When you create database instance the first time, you can use DatabaseInstance and put Credentials generated by Credentials.fromGeneratedSecret() and specify secretName through CredentialsBaseOptions.
This is great to create secret and database in the same time.

Unfortunately, when you want to create a new database instance from a snapshot using DatabaseInstanceFromSnapshot, you are not able to specify custom secretName in SnapshotCredentialsFromGeneratedPasswordOptions for SnapshotCredentials.fromGeneratedSecret().

So yes, you can create DatabaseSecret and pass it to DatabaseInstanceFromSnapshot (what I am currently doing), but I think, this small improvement helps to make DatabaseInstance and DatabaseInstanceFromSnapshot constructs more consistent.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by corymhall — COMMENTED** [review]
@gfkl can you provide some details on the motivation for this feature? Why should we provide this option? It's also possible to provide your own secret instead of having the library create one for you.

**Comment by gfkl** [comment]
Hello @corymhall, sure I can. 

When you create database instance the first time, you can use `DatabaseInstance` and put `Credentials` generated by `Credentials.fromGeneratedSecret()` and specify `secretName` through `CredentialsBaseOptions`.
This is great to create secret and database in the same time.

Unfortunately,  when you want to create a new database instance from a snapshot using `DatabaseInstanceFromSnapshot`, you are not able to specify custom `secretName` in `SnapshotCredentialsFromGeneratedPasswordOptions` for `SnapshotCredentials.fromGeneratedSecret()`.

So yes, you can create `DatabaseSecret` and pass it to DatabaseInstanceFromSnapshot (what I am currently doing), but I think, this small improvement helps to make `DatabaseInstance` and `DatabaseInstanceFromSnapshot` constructs more consistent.

**Review by corymhall — DISMISSED** [review]
Ok thanks for the explanation! I think the only thing that is missing is an update to an integration test. You can just add another instance here with the secretName provided

https://github.com/aws/aws-cdk/blob/0b7e69e90bdbc016e274a4c5679407c4ec986f45/packages/%40aws-cdk/aws-rds/test/integ.cluster-snapshot.ts#L30-L42

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Looks like we're still needing an integration test for this change.

**Pull request closed without merging**
