### PR TITLE
feat(assets): cdk-assets docker build with shell

### PR DESCRIPTION
**Pull request by scedward**
This relates to the @dillon-odonovan [comment](https://github.com/aws/aws-cdk/issues/14395#issuecomment-889391936) in #14395 regarding `docker build --build-arg FOO=$FOO` values not being expanded from the build environment.  The reason this does not work appears to be the cdk-assets module using the [NodeJS child_process.spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) function, which by default does not use a shell to execute the command thus preventing variable expansion.  Allowing users to instruct cdk-assets to build the Docker image asset in a shell should allow for build args to be pulled from the build environment by specifying the asset like:

```ts
const asset = new DockerImageAsset(this, 'MyBuildImage', {
  directory: path.join(__dirname, 'my-image'),
  buildArgs: {
    HTTP_PROXY: '$HTTP_PROXY',
  },
  buildShell: '/bin/sh' // will enable shell expansion of --build-arg HTTP_PROXY=$HTTP_PROXY
});
```

The fundamental change in this PR is to pass the `{ shell: options.buildShell }` option to the `execute` call in `cdk-assets/lib/private/docker.ts`, which in turn calls the `shell` function from `cdk-assets/lib/private/shell.ts`, which makes the call to `child_process.spawn` to perform the docker build.

This PR also updates similar code in `@aws-cdk/core/lib/bundling.ts` to seed a similar-look-and-feel `buildShell` option on the `DockerBuildOptions` interface that is used by the `aws-lambda-{go,nodejs,python}` modules, but I did not update those modules to consume the new option to limit the scope of this PR.

---

@eladb -- This is my first CDK PR attempt so to be transparent I'm not 100% sure I've got it all right, but I was lucky to find #18114 by @kirintwn that you recently reviewed.  I mostly followed that PR as a guide, as well as attempting to match the implementation of the similar `buildArgs` option where it seemed appropriate.

I have not been able to deploy this code for manual validation of the changes (I just don't know how to do that), but https://github.com/scedward/build-spawn-test provides a simple CodeBuild project to test the effects of enabling `{ shell: '/bin/sh' }` when using a NodeJS script to build docker images with build args from environment variables.

```
...
[Container] 2022/03/02 18:28:14 Entering phase BUILD
[Container] 2022/03/02 18:28:14 Running command node build-args-shell-test.js
process.env.FOO is: bar
building images...
no-build-args-no-shell: FOO is: ()
no-build-args-with-shell: FOO is: ()
build-args-no-shell: FOO is: ($FOO)
build-args-with-shell: FOO is: (bar)

...
```

An alternative I considered at first was something like this, which would work without the need for a shell:

```ts
const asset = new DockerImageAsset(this, 'MyBuildImage', {
  directory: path.join(__dirname, 'my-image'),
  buildArgs: {
    FOO: null // would have produced docker build --build-arg FOO ...
  }
});
```

but I ran into problems with jsii not liking the `dockerBuildArgs?: { [name: string]: string | null }` type union and wasn't sure of the effects of changing that to `any`, so I went the shell-enabling route as I could follow the approach laid out in #18114.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by otaviomacedo** [comment]
Thanks for the PR, @scedward. Overall, it looks good, but I have a concern about security. The Node.js doc says:

> If the shell option is enabled, do not pass unsanitized user input to this function. Any input containing shell metacharacters may be used to trigger arbitrary command execution.

I understand that this is exactly what you want for `$`, but it opens the door to everything else.

**Comment by scedward** [comment]
@otaviomacedo adding a shell option caught my attention too. Given the cdk-assets command itself is already running in a shell, as do all CodeBuild commands, the option to have the docker build command spawn in a shell seemed sensible to me with the more-secure default remaining no shell. That said, it's always worth being cautious with security and I certainly don't want to inadvertently introduce a dirty feature, even if it's very useful, so happy to wait on further reviews if necessary. The alternative of `buildArgs: { FOO: null }` producing `--build-args FOO` may be worth a look, I just wasn't sure I could assemble that PR.

The way I'd imagine "unsanitized user input" getting into a command here would be some kind of service running CodeBuild projects on a per-customer basis, perhaps to build images with a CUSTOMER_ID build arg, and then an unsanitized "CUSTOMER_ID" comes in as `docker build --build-arg CUSTOMER_ID=$(apt install steal-your-stuff)`. I don't know how cdk-assets might become involved in that kind of setup, but the engineers here are letting an untrusted source (user input) determine the build arg value and then running it through a shell expansion. NodeJS spawn could be used in countless similarly inadvisable ways, which is the way I understand their boldface note.

Where engineers are maintaining control of the build arg value and only setting it from trusted sources, the main risk to me seems to be secret exposure from building a secret into the image, as noted in the readme. The most common value sources seem to be plaintext, SSM, or Secrets Manager values placed in the CodeBuild environment, or custom variable exports in the buildspec commands. Engineers will need to ensure these sources are trusted, and understand the build args will appear in the docker history.

Beyond that, I'm not familiar with the risk of something nefarious happening within cdk-assets itself, perhaps a third party package mucking around with commonly used build arg values in `process.env`. I'm also not a creative hacker type, so again happy to wait on further security reviews to be sure here.

**Comment by otaviomacedo** [comment]
Internal: t/V538899633

**Comment by otaviomacedo** [comment]
@scedward Are you still interested in this PR?

**Comment by scedward** [comment]
@otaviomacedo I think what I actually wanted when I did this was the ability to pull `docker build --build-arg ...` values from the build environment.  That could be done with the shell expandable strings implemented here, or via the alternative I mentioned which would allow `buildArgs: { FOO: null }` to produce the command `docker build --build-arg FOO`, which would let the docker build command pull FOO from the environment without a shell.  IIRC, what happens now with a null value is you get `docker build --build-arg FOO=null` which prevents docker from pulling the value from the environment.

So I'm still interested in the feature of being able to pull build arg values from the build environment, but I'm not tied to either implementation (or other options, if they exist).

**Comment by otaviomacedo** [comment]
@scedward in that case, I would rather have the alternative version, with `buildArgs: { FOO: null }`

**Comment by scedward** [comment]
@otaviomacedo I think that's a reasonable decision.  I'd want to review the current docs to open a good feature request for allowing `buildArgs: { FOO: null }` to mean "let Docker pull the value of FOO from the build environment", but I think we can close this PR with the shell-enabling approach as a no-go.

**Pull request closed without merging**
