### PR TITLE
fix(apigateway): invalid schema generated due to un-mapped `ref`

### PR DESCRIPTION
**Pull request by RomainMuller**
When using a `ref` (which in JSON Schema really is `$ref`) for the type
of some object property, the `$ref` replacement did not happen because
the arbitrary property names were not white-listed for transformation.

----

Please read the [contribution guidelines](https://github.com/awslabs/aws-cdk/blob/master/CONTRIBUTING.md) and follow the pull-request checklist.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eladb** [comment]
@RomainMuller what's up with this?

**Comment by eladb** [comment]
@RomainMuller can you please update from master?

**Comment by eladb** [comment]
@RomainMuller can you follow up on this?

**Comment by RomainMuller** [comment]
@eladb - this is now in a mergeable state!

**Pull request merged**
