### PR TITLE
fix(ec2): Duplicate EIP when NatGatewayProps.eipAllocationIds is provided

### PR DESCRIPTION
**Pull request by liverpoolGerrard**
Closes https://github.com/aws/aws-cdk/issues/15422

Added an optional `eipAllocationId` parameter to the addNatGateway method to use the provided eipAllocationId instead of creating a new AWS::EC2::EIP resource.

Tested successfully with the following AWS CDK stack: 

```
import * as cdk from '@aws-cdk/core';
import ec2 = require('@aws-cdk/aws-ec2');

export class CdkEc2VpcNatEipStack extends cdk.Stack {


  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, "Vpc", {
      cidr:"60.0.0.0/16",
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'ingress',
          subnetType: ec2.SubnetType.PUBLIC,
        },
        {
          cidrMask: 24,
          name: 'application',
          subnetType: ec2.SubnetType.PRIVATE_WITH_NAT,
        }
      ],
      natGatewayProvider: ec2.NatProvider.gateway({eipAllocationIds: ["eipalloc-12345abcde"]}),
      natGateways: 1
    });

  }
}
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by njlynch — APPROVED** [review]
Thanks!

**Review by njlynch — CHANGES_REQUESTED** [review]
Actually, our PR linter is complaining -- for a valid reason. Can you please add a test for this behavior?

**Comment by liverpoolGerrard** [comment]
Added test case

**Review by njlynch — APPROVED** [review]
Great, thanks!

**Pull request merged**
