### PR TITLE
chore: assign aws-cdk-owners members to PRs

### PR DESCRIPTION
**Pull request by peterwoodworth**
When a PR is opened, this automation will:

- Assign the member from `aws-cdk-owners` with the lowest number of currently assigned PRs to the PR
- Do nothing if the issue was submitted by someone from `aws-cdk-team`

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by peterwoodworth** [comment]
Action ran successfully, so the token works here https://github.com/aws/aws-cdk/runs/6032421375?check_suite_focus=true

Repository [here](https://github.com/peterwoodworth/team-assignment-manager)

Also, should we disable the automatic requesting of reviews from `aws-cdk-owners` on top of this?

**Review by kaizen3031593 — CHANGES_REQUESTED** [review]
Thanks! I read the [source code](https://github.com/peterwoodworth/team-assignment-manager/blob/main/src/index.ts) and I'll do my best to relay comments from that.

- I think it's a bit cumbersome to have to configure both `pull_request_target: types: [opened]` and `target: "pull-requests"` on the action itself. If you omit one or the other, suddenly things don't work the way you think they do. It's more robust to exit the action gracefully if it encounters an issue when `target: "pull_request"`, instead of relying on the workflow configuration to only send the action PRs.
- should `core-team` be renamed something that conveys what it's doing, like `exempt-team` or `exempt-members`? _We_ want the core team to be exempt from assignment (at least I do) but that's our own implementation detail.

**Comment by peterwoodworth** [comment]
Changed it to `exempt`. I didn't like the `core` name either

As for the first point, I could make it so that if the issue opened is an issue then it only counts issues, and same with PRs. I think I like that better

**Review by kaizencc — APPROVED** [review]
I am fine with the system of assigning PRs to the lowest number of PRs currently. Since it's not what @rix0rrr originally envisioned, I'm adding `do-not-merge` to give him a chance to disagree.

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
