### PR TITLE
feat(pipelines): provide bucket for build artifacts

### PR DESCRIPTION
**Pull request by quincycs**
Using CDKPipelines, I encountered a situation where every commit (a build) would make a new S3 bucket. This would eventually fill up the limit of buckets for an account.  Doomsday situation would be trying to ship an urgent fix, and discovering this issue...quickly resolving it by deleting some old buckets and re-running the pipeline.

This PR fixes that by allowing you to define & reuse a bucket in the CDKPipeline construct.  It's a simple property pass down to the underlying CodePipeline.

Another soul encountered the same situation as I did: #10080

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by quincycs** [comment]
Hooray 👍 , all checks passed.  Should be good for review.

**Comment by quincycs** [comment]
@nija-at , just a polite ping.  Any chance you could review?  Impact of this PR is pretty big IMO.  CdkPipelines currently fill up an account with buckets ... and eventually hitting bucket limit.  This PR adds a bucket prop to easily fix that.

**Comment by nija-at** [comment]
Sorry @quincycs. This seems to have slipped from our auto assignment system. I've fixed the title so it's correctly picked up and assigned to the owner (@rix0rrr).

**Comment by rix0rrr** [comment]
The fix is fine, I suppose, but should not be necessary. Can you speak a little more to this:

> Using CDKPipelines, I encountered a situation where every commit (a build) would make a new S3 bucket. 

Can we dive into why that is?

**Comment by rix0rrr** [comment]
I can see this happening if you try to deploy the pipeline anew, and it fails and rolls back, and you do that over and over again.

But that is --or should not be-- "every commit".

**Review by rix0rrr — CHANGES_REQUESTED** [review]
(Not actually "changes required" but this is a convenient way for me to put the ball back into your court :) )

**Comment by quincy-mitchell-perficient** [comment]
@rix0rrr - appreciate the review.  You were right, this would only be helpful if you were deleting/recreating the cdkpipeline a bunch of times.  I'm closing this because existing behavior is okay.  thanks again!

**Comment by quincycs** [comment]
@rix0rrr  - thanks for the review.  I had some time to get back to this and you were totally right.  With fresh eyes, I wasn't able to reproduce new buckets being created every commit.  I'm okay to close this PR.

I imagine this PR might have some small use case though for people who want to add a few more settings / policies / configurations on that bucket.  Not a big deal IMO.  What do you think?  Close?  Happy to make a little edit here if there's some value nearby.  Otherwise,  I can close this PR.  Again, appreciate your review :)

**Comment by damyan-h** [comment]
We have more then 20 CDK pipelines, and yould love to use the same bucket for all of them. Why would we need a bucket per pipeline at all?
Creating the underlying CodePipeline just to pass a bucket does not look sexy at all. Can we please reopen and merge this option?

**Pull request closed without merging**
