### PR TITLE
fix(acm): Cleanup route53 when deleting DNS Validated Certificates

### LINKED ISSUE #3333: certificatemanager: Route 53 records not cleaned up after removing DNS Validated Certificate
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**

Following this code:

```
const zone = new route53.HostedZone(this, 'zone', { zoneName: 'bar.com' })

new certificateManager.DnsValidatedCertificate(this, 'cert', {
  hostedZone: zone,
  domainName: `foo.bar.com`,
})
```

An ACM certificate is created and validated via DNS. However, when you destroy the stack, it fails with the following error `(Service: AmazonRoute53; Status Code: 400; Error Code : HostedZoneNotEmpty ...`

* **What is the expected behavior (or behavior of feature suggested)?**

The stack was destroyed cleanly.

* **What is the motivation / use case for changing the behavior or adding this feature?**

A stack created by CDK should naturally be destroyable. Checking the lambda resource that handles the validation, I can see that when the resource is destroyed, no attempt is made to clean up the route53 record. This explains why it fails.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all]
  - Language: [TypeScript ]

### PR DESCRIPTION
**Pull request by netroy**
fixes #3333

additionally made some other changes. please let me know if you do not prefer the other changes I made.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
Different certificates using the same domain name share the same Route 53 record for validation.

This means, with the proposed change, that if you have Stack A and Stack B requesting certificates on `sub.domain.com` when Stack A gets deleted it deletes the record that is also valid for Stack B, is this safe? what happens when the certificate in Stack B renews?

**Comment by skinny85** [comment]
> Different certificates using the same domain name share the same Route 53 record for validation.
> 
> This means, with the proposed change, that if you have Stack A and Stack B requesting certificates on `sub.domain.com` when Stack A gets deleted it deletes the record that is also valid for Stack B, is this safe? what happens when the certificate in Stack B renews?

@netroy can you respond to this question?

**Comment by netroy** [comment]
What @jogold mentioned seems right. deletion of the records when Stack A is destroyed, won't affect the certificates in Stack B right away. but, will most definitely break the automatic-renewal process.

I tried various scenarios, & these are the outcomes
* Without this fix, If I deploy a stack with a hosted-zone & a `DNSValidatedCertificate`, stack deletion fails because route53 doesn't allow deleting the hosted zone.
* With this fix, If I deploy 2 stacks, each with a cert for the same domain, the first stack can be destroyed without any errors. but, the second one can't be destroyed because it fails at destroying the record that has already been destroyed.

As someone with a stack containing a hosted-zone & a cert, I need this fix. But, I'm not sure if this fix would be helpful for everyone.

Another possible fix, that I can think off, would be change how hosted-zones are destroyed.
If we could delete all records in the zone before destroying the CF resource, that would also fix this issue (I think).

@skinny85 @jogold if you have alternative solutions that work better, please let me know. I can update this PR.

**Comment by jogold** [comment]
> As someone with a stack containing a hosted-zone & a cert

Can you explain why you chose to have both the hosted zone and certificate in the same stack? Usually the hosted zone is part of some sort of "infrastructure" stack and then your "app" stacks create certificates for their needs.

**Comment by netroy** [comment]
> Can you explain why you chose to have both the hosted zone and certificate in the same stack? 
In my case, the hosted-zones are in a shared "infrastructure" stack, as you recommend.
But, because we share some certificates across multiple-stacks (i.e. website stack, backend stack, etc), we decided to put wildcard certs in the shared stack as well.
I might be able to change the certs not be wildcard, & then move them to the "app" stacks. 
But, for someone who needs wildcard certs, or certs for the same domain, it **might** be an issue that a DNS-validated cert doesn't clean up the records it creates.

Let me think a bit more about this, & get back to you folks.
If I manage to get our setup work without shared wildcard certs, I'll close this PR.

**Comment by jogold** [comment]
> because we share some certificates across multiple-stacks

Certificates are free. I would personally create them in the different stacks. You can even create the same wildcard certificate in each stack (you can have multiple certificates on the same domain name in ACM).

**Comment by netroy** [comment]
@jogold I went with your suggestion of moving certs to "app" stacks & provisioning redundant certs instead. This works well for me.
Should I close the PR? or, 
Should I remove the last commit & change the PR title?

**Comment by netroy** [comment]
@jogold do you have a preference for keeping the other changes? if not, I can close the ticket.

**Comment by jogold** [comment]
> @jogold do you have a preference for keeping the other changes? if not, I can close the ticket.

@skinny85 your call...

**Pull request closed without merging**
