### PR TITLE
chore(ubergen): switch to ubergen.exclude as a filter instead of private

### PR DESCRIPTION
**Pull request by nija-at**
Currently, ubergen excludes packages that are marked as 'private'.
In v2, all packages under `@aws-cdk/` will be marked as 'private'.
This will mean that 'monocdk' and 'aws-cdk-lib' modules will have no
packages included.

Introduce another field `ubergen.exclude` in `package.json` that will be
explicitly exclude packages from the monolithic modules.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by NetaNir — COMMENTED** [review]
Adding the exclude in every package makes it hard to track which package should be included in monocdk and which shouldn't. I would rather have an array of all excluded packages in `ubergen` so there will be one centralized location to track these.

**Comment by nija-at** [comment]
> Adding the exclude in every package makes it hard to track which package should be included in monocdk and which shouldn't. I would suggest adding an array of all excluded packages in `ubergen` so there will be one centralized location to track these.

I don't see the value of creating another location for this configuration. This is where we put package configuration. 
To find the list of packages excluded, a simple `grep` or `find + grep` will get you what you need.
This is not different from what we have currently.

**Review by rix0rrr — APPROVED** [review]
I don't necessarily mind, but isn't this `exclude` list better suited in the `package.json` of `aws-cdk-lib` itself?

**Comment by nija-at** [comment]
> I don't necessarily mind, but isn't this `exclude` list better suited in the `package.json` of `aws-cdk-lib` itself?

Maybe. It's not clear.
This will have to be 2 lists - one in `aws-cdk-lib` and one in `monocdk`, unless we special case `monocdk` on the v2 branch to not fail if it didn't match any packages. 
It might be useful to know if a package is going to be included in `ubergen` (in the future), so we can enforce any linter rules or standards that it must follow at build/test time.

**Pull request merged**
