### PR TITLE
fix(elasticsearch): 'r6gd' not marked as supported type for instance storage

### LINKED ISSUE #14773: (aws-elasticsearch): Can't set up r6gd with instance type storage
### Reproduction Steps

```
        const domain = new Domain(this, "Resource" + domainName, {
            domainName,
            version: ElasticsearchVersion.of("7.9"),
            capacity: {
                dataNodeInstanceType: "r6gd.large.elasticsearch",
                dataNodes: this.isMainState() ? 3 : 1
            },
            ...
        });

```

### Error I get:

```
Error: EBS volumes are required when using instance types other than r3 or i3.
    at new Domain (/home/circleci/repo/node_modules/@aws-cdk/aws-elasticsearch/lib/domain.js:589:19)
    at StateStack.addElasticSearch (/home/circleci/repo/state/template.js:134:24)
    at new StateStack (/home/circleci/repo/state/template.js:30:14)
    at /home/circleci/repo/cdkapp.js:31:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Fix:

Here:
https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-elasticsearch/lib/domain.ts#L1475
image

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ofirnk**
According to https://aws.amazon.com/elasticsearch-service/pricing/ it's now supported .

Fixes #14773

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ofirnk** [comment]
@iliapolo Checks are green :heavy_check_mark:

**Review by BenChaimberg — DISMISSED** [review]
Please also add to the assertion on line 1457 that R6GD instance types do not support EBS (from https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-instance-types.html)

**Comment by ofirnk** [comment]
Validate PR ci looks lost in cloud space.. any way to rerun it?

**Comment by ofirnk** [comment]
Merge?

**Review by BenChaimberg — APPROVED** [review]

**Pull request merged**
