### PR TITLE
feat(cli): added .env support

### PR DESCRIPTION
**Pull request by jdrydn**
Added `.env` support for the CLI, so developers can create a `.env` file in the root of their project containing `AWS_PROFILE` or other AWS credentials & have the CLI respect those options.

Also added `CDK_APP`, `CDK_DEBUG` & `CDK_PROFILE` env var support, for dedicated CDK options. Can easily be extended though.

I'm aware there should also be accompanying docs for this - happy to write them if someone can direct me to the repo/file to edit!

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jdrydn** [comment]
> ### AWS CodeBuild CI Report
> * CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
> * Commit ID: [ffd7649](https://github.com/aws/aws-cdk/commit/ffd764931a2c70deb7cc8c515eed2bf8799bff44)
> * Result: FAILED
> * [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f642746b-8f10-4611-8c85-f44bc3fa1119%2Fbuild.log) (available for 30 days)
> 
> _Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)_

> ```
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @aws-cdk/aws-iot-actions@1.129.0.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> ```

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Can you point me to prior art for conventions like this? 

I'm not too keen on adding new dependencies to the CLI, by the way.

**Comment by jdrydn** [comment]
> Can you point me to prior art for conventions like this?

I think this issue <https://github.com/motdotla/dotenv/issues/89> likely serves the best examples - essentially placing `import 'dotenv/config'` as early as possible loads in the `.env` file in the current working directory. Perfect for using AWS environment credentials or setting an AWS profile.

> I'm not too keen on adding new dependencies to the CLI, by the way.

I understand where you're coming from - new dependencies include new risks. I can only counter with [25k+ dependents on NPM](//npm.im/dotenv) (and that's just the public ones!) & my own personal vote of confidence in `dotenv`- been using this dependency for just over 5 years in plenty of public (& private) projects. [Alternatives exist](https://www.npmjs.com/search?q=env%20file) but are not as popular. To avoid any additional dependencies you're looking at ~copying~ recreating an env file parser, with tests etc.

**Comment by rix0rrr** [comment]
Ultimately I'm not inclined to merge this. The same could be achieved with wrapper scripts around the `cdk` shell, or a more principled way of handling config through environment variables in the CDK (other than the 3 vars you handcoded here), and then running CDK with `node -r dotenv/config` if you prefer to load them from a `.env` file.

I'm not opposed to the convention but there are other ways to achieve the same goal, and this method doesn't feel like it's going to benefit enough users to be worth it.

**Pull request closed without merging**
