### PR TITLE
docs(aws-glue): what format to use w/ cloudfront 

### PR DESCRIPTION
**Pull request by naseemkullah**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by naseemkullah** [comment]
> Hi @naseemkullah! Can you provide some documentation as to how you know that this is the correct approach for CloudFront logs? It seems like the main difference is the type of the property `serializationLibrary`.
> 
> At the end of the day, what I'd like to do here is to provide a static method like `DataFormat.CLOUDFRONT_LOGS` instead of appending this functionality on to other methods. Does that sound like something you'd like to add?

that sounds good, what would that look like?

**Comment by kaizen3031593** [comment]
> > Hi @naseemkullah! Can you provide some documentation as to how you know that this is the correct approach for CloudFront logs? It seems like the main difference is the type of the property `serializationLibrary`.
> > At the end of the day, what I'd like to do here is to provide a static method like `DataFormat.CLOUDFRONT_LOGS` instead of appending this functionality on to other methods. Does that sound like something you'd like to add?
> 
> that sounds good, what would that look like?

I'm not sure. The problem we are trying to solve here is making sure that using Cloudwatch Logs as a data format is accessible and intuitive for the CDK user. Your attempt is a strong first effort, but I feel like there's more to be done. Whether that's creating a new static method called `DataFormat.CLOUDFRONT_LOGS` or clearly documenting `DataFormat.TSV` inline and in the README, its up to you. Our goal is that if a user wants to specify Cloudwatch Logs as a data format, they can find out how to do so relatively easily.

I think the first question is if there is more to be done re: adding additional Serde parameters. If that is necessary, then we may have to expose that in the `glue.Table L2` as well. It gets complicated...

**Comment by mattiamatrix** [comment]
I am having a similar issue with CloudTrail logs, I'd like to create a _cloudtrail_ table with CDK but the result that I obtain is different than the [suggested SQL statement](https://docs.aws.amazon.com/athena/latest/ug/cloudtrail-logs.html#create-cloudtrail-table-ct).

In the specific case, I can't add `serialization.format=1` with the L2 construct Table.

**Comment by TheRealAmazonKendra** [comment]
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

**Comment by naseemkullah** [comment]
> This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

Abandoned by the reviewer you mean? This documentation improvement is based on real world experience setting up log querying in Athena, please reconsider opening. Having the contributor reopen a duplicate PR is an unnecessary hoop

**Pull request closed without merging**
