### PR TITLE
feat(ec2): Add VPC endpoint for RDS

### LINKED ISSUE #12402: (ec2): Add RDS VPC interface endpoints
Add RDS VPC interface endpoints

### Use Case

VPC interface endpoints are supported for RDS, but don't exist in CDK:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/vpc-interface-endpoints.html

### Proposed Solution

Add support for RDS VPC interface endpoints

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by bcelenza**
Adds VPC endpoint support for RDS. Fixes #12402

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by NetaNir — DISMISSED** [review]

**Review by NetaNir — APPROVED** [review]

**Review by rix0rrr — APPROVED** [review]

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]

**Review by rix0rrr — APPROVED** [review]

**Comment by bcelenza** [comment]
What is the status here? This has become incredibly painful for what was a simple 1-line change. :(

**Comment by rix0rrr** [comment]
It is not even clear to me why this has become so painful.

**Comment by rix0rrr** [comment]
Oh I remember. It's because static initialization of an additional token messed up something in the APIGatewayV2 module.

Thanks for exposing that bug! I think I can fix your PR by rebasing some commits.

**Comment by rix0rrr** [comment]
There we go.

**Review by rix0rrr — DISMISSED** [review]

**Comment by bcelenza** [comment]
Thanks @rix0rrr! I'll give this an update with master and hopefully the great merge train will proceed. :)

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
