### PR TITLE
fix(custom-resources): support region for AwsCustomResource

### LINKED ISSUE #4292: AwsCustomResource cannot access resources in other regions
I've tried using AwsCustomResource to publish to a sns topic in a different region. It fails with the error "Invalid parameter: TopicArn". When I try the same with awscli I get the same error.

It looks like that could be solved by letting the lambda function use the region where the sns topic is located. Unfortunately I see no way of either changing the lambda function on the fly or setting AWS_DEFAULT_REGION as environment variable to it.

It would be great if lambda could "guess" which region to use by analysing the parameters. But being able to provide the proper region would be enough for me.

### Reproduction Steps

Create an sns topic in region A and give permission to be accessed by others

```typescript
export class BaseStack extends cdk.Stack {
    testTopic: sns.ITopic

    constructor(app: cdk.App, id: string, props?: cdk.StackProps) {
        super(app, id, props)

        this.testTopic = new sns.Topic(this, "TestTopic", {
            topicName: "test",
            displayName: "test"
        });

        let policy = new iam.PolicyStatement()
        policy.addAnyPrincipal()
        policy.addAllResources()
        policy.addActions("sns:Publish")

        this.testTopic.addToResourcePolicy(policy)
    }
}
```

Create the custom resource in region B

```typescript
export class TestStack extends cdk.Stack {

    constructor(app: cdk.App, id: string, props?: cdk.StackProps) {
        super(app, id, props)

        const snsPublish = new custom.AwsCustomResource(this, "SnsPublish", {
            onUpdate: {
                service: "SNS",
                action: "publish",
                parameters: {
                    Message: "Hello From another region",
                    TopicArn: "arn:aws:sns:eu-west-1:XXXXXXXXXXXX:test",
                },
                physicalResourceId: "test",
            },
        });
    }
}
```

### Environment

  - **CDK CLI Version:** 1.9.0 (build 30f158a)
  - **Module Version:** 1.9.0
  - **OS:** all
  - **Language:** TypeScript

### PR DESCRIPTION
**Pull request by jogold**
Allow to specify region for AWS API calls in `AwsCustomResource`

Remove gitignored file `lib/sdk-api-metadata.json`.

Closes #4292

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by konstantinj** [comment]
@eladb I'm trying to send messages to a shared sns topic in our main account. Idea is that all subaccounts can send there from all regions. We have several subscriptions in the main account in one region which is our central hub basically. Alternative would be to have from thios one region subscriptions to many sns topics in different region. But I guess that would be the exact same problem. I'm already querying other region endpoints in many of my lambda functions e.g. for peering connections I need this since I need to assume a role from another account to accept it. Actually I would like to do the peerings also in a custom resource so I can also accept the connections right away and be able to make connections to many other accounts/regions.

**Comment by konstantinj** [comment]
in #1796 @rix0rrr  says "writing a Custom Resource to do a cross-region call". So I guess to be able to do this, this PR is needed.

**Comment by jogold** [comment]
@eladb I understand the request to be able to publish to a topic in another region and I can imagine use cases for this

Your call... if you don't want to support this I'll refactor this PR to only include the additional test on `apiVersion`.

**Comment by eladb** [comment]
I don't have dire objections... Maybe we can just add some warnings in the documentation of this property and explain to people that this can have implications on their blast radius...

**Pull request merged**
