### PR TITLE
fix(ecspatterns): honor name in createLoadBalancer()

### LINKED ISSUE #8464: [ecs-patterns] ApplicationLoadBalancerProps "name" doesnt work for ApplicationMultipleTargetGroups service pattern
when supplying **name** attribute on ApplicationLoadBalancerProps while creating new ecspatterns.ApplicationMultipleTargetGroupsEc2Service(..), the **name** is not reflected in the created LoadBalancer.

### Reproduction Steps

Create a MultiTargetGroupLoadBalancer and supply a ApplicationLoadBalancerConfig like so:

```
new ecspatterns.ApplicationMultipleTargetGroupsEc2Service(this, "someResourceId", {
  ...
  loadBalancers: {
    ... 
    name: "MyLoadBalancerName"
  }
});

```

**MyLoadBalancerName** is not set for the created LB.

### Proposed Solution

set **loadBalancerName** attribute to **application-multiple-target-groups-service-base.ts** (Line 517+)

```
  private createLoadBalancer(name: string, publicLoadBalancer?: boolean): ApplicationLoadBalancer {
    const internetFacing = publicLoadBalancer !== undefined ? publicLoadBalancer : true;
    const lbProps = {
      loadBalancerName: name,
      vpc: this.cluster.vpc,
      internetFacing,
    };
    
   return new ApplicationLoadBalancer(this, name, lbProps);
  }

```

I would do it myself but your current master fails on:
docker build -t aws-cdk .

So i cant fire up a dev environment currently. 

### Environment

  - **Framework Version: 1.44.0 (build 1cd832b)**

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by logemann**
as requested the PR for issue #8464 

Closes #8464 

----
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by logemann** [comment]
any progress on this? Right now i have 3 LBs with totally cryptic names because of that bug. Hard to tell for which environment which LB is for.....

**Comment by iamhopaul123** [comment]
Hello @logemann! So sorry for the delay. Nice fix! Thank you so much for that. Could you add unit tests for this feature and could you fix the NLB one as well?

**Comment by logemann** [comment]
dont think i can find the time the next weeks.

**Comment by iamhopaul123** [comment]
hello @logemann got it! no worries at all. Would you mind adding the unit test so that the PR linter could pass?

**Pull request closed without merging**
