### PR TITLE
feat(quicksight): QuickSight resources and import functionality

### LINKED ISSUE #274: aws-cdk-cloudformation-diff: thinks that change in dependencies destroys the resource
Example:

```
[~] ☢️ Destroying DatabaseInstance2AA380DEE (type: AWS::RDS::DBInstance)
 └─ [~] DependsOn:
     ├─ [-] Old value: ["VPCIGWB7E252D3"]
     └─ [+] New value: ["VPC06C5F037","VPCIGWB7E252D3","VPCVPCGW99B986DC","VPCPublicSubnet1SubnetB4246D30","VPCPublicSubnet1RouteTableFEE4B781","VPCPublicSubnet1RouteTableAssociatioin249B4093","VPCPrivateSubnet1Subnet8BCA10E0","VPCPrivateSubnet1RouteTableBE8A6027","VPCPrivateSubnet1RouteTableAssociatioin77F7CA18","VPCPublicSubnet2Subnet74179F39","VPCPublicSubnet2RouteTable6F1A15F1","VPCPublicSubnet2RouteTableAssociatioin766225D7","VPCPrivateSubnet2SubnetCFCDAA7A","VPCPrivateSubnet2RouteTable0A19E10E","VPCPrivateSubnet2RouteTableAssociatioinC31995B4"]
```

### PR DESCRIPTION
**Pull request by Disciple153**
Developing QuickSight resources with CDK is currently unnecessarily complicated due to the  fact the there is no way to create new QuickSight Analyses, Dashboards, Templates, or Themes without manually gathering data about existing resources and loading them into the QuickSight CfnResources. This PR solves this complexity by allowing QuickSight Resources to be imported and then used as dependencies. This is easier than the current solution because when a CDK QuickSight Resource is used as a dependency, complex objects are automatically mapped from the SDK objects to their CDK/CFN counterparts. This significantly reduces the amount of code that developers need to write to create QuickSight resources.

Addresses #19212
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by padaszewski** [comment]
+1!

**Comment by Disciple153** [comment]
I am currently getting an error in my integ test where the dummy value (undefined) is being returned, where an error should be thrown by my context provider instead. I suspect that my ContextProviders are not set up correctly, and that the default ContextProvider is being used instead, but I'm not sure how to correctly configure my ContextProviders. Any help solving this problem would be greattly appreciated.

**Relevant files:**
- Calls to ContextProviders:
  - [packages/@aws-cdk/aws-quicksight/lib/](https://github.com/Disciple153/aws-cdk/tree/quicksight_with_context/packages/%40aws-cdk/aws-quicksight/lib)*: <Resource>.fromId().Import.<resource>()
- Integ test:
  - [packages/@aws-cdk/aws-quicksight/test/integ.quicksight.ts](https://github.com/Disciple153/aws-cdk/blob/quicksight_with_context/packages/%40aws-cdk/aws-quicksight/test/integ.quicksight.ts)
- ContextProviders:
  - [packages/aws-cdk/lib/context-providers/quicksight/](https://github.com/Disciple153/aws-cdk/tree/quicksight_with_context/packages/aws-cdk/lib/context-providers/quicksight)*

**Error:**
```bash
/home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/lib/template.js:98
                        throw Error(`No Template found in account ${contextProps.account} and region ${contextProps.region} with id ${contextProps.templateId}`);
                              ^

Error: No Template found in account 732958832353 and region us-west-2 with id test-template
    at Import.get template [as template] (/home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/lib/template.js:98:31)
    at Import.get templateArn [as templateArn] (/home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/lib/template.js:157:29)
    at new Analysis (/home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/lib/analysis.js:40:53)
    at main (/home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/test/integ.quicksight.js:184:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Disciple153** [comment]
> I am currently getting an error in my integ test where the dummy value (undefined) is being returned, where an error should be thrown by my context provider instead. I suspect that my ContextProviders are not set up correctly, and that the default ContextProvider is being used instead, but I'm not sure how to correctly configure my ContextProviders. Any help solving this problem would be greatly appreciated.
> 
> **Relevant files:**
> 
>     * Calls to ContextProviders:
>       
>       * [packages/@aws-cdk/aws-quicksight/lib/](https://github.com/Disciple153/aws-cdk/tree/quicksight_with_context/packages/%40aws-cdk/aws-quicksight/lib)*: .fromId().Import.()
> 
>     * Integ test:
>       
>       * [packages/@aws-cdk/aws-quicksight/test/integ.quicksight.ts](https://github.com/Disciple153/aws-cdk/blob/quicksight_with_context/packages/%40aws-cdk/aws-quicksight/test/integ.quicksight.ts)
> 
>     * ContextProviders:
>       
>       * [packages/aws-cdk/lib/context-providers/quicksight/](https://github.com/Disciple153/aws-cdk/tree/quicksight_with_context/packages/aws-cdk/lib/context-providers/quicksight)*
> 
> 
> **Error:**
> 
> ```shell
> /home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/lib/template.js:98
>                         throw Error(`No Template found in account ${contextProps.account} and region ${contextProps.region} with id ${contextProps.templateId}`);
>                               ^
> 
> Error: No Template found in account 732958832353 and region us-west-2 with id test-template
>     at Import.get template [as template] (/home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/lib/template.js:98:31)
>     at Import.get templateArn [as templateArn] (/home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/lib/template.js:157:29)
>     at new Analysis (/home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/lib/analysis.js:40:53)
>     at main (/home/eppercan/documents/opensource/aws-cdk/packages/@aws-cdk/aws-quicksight/test/integ.quicksight.js:184:16)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> (The above error should have been thrown from the [TemplateContextProviderPlugin](https://github.com/Disciple153/aws-cdk/blob/c8282c84b5240ddb107282b18baaecdabb48ba12/packages/aws-cdk/lib/context-providers/quicksight/templates.ts#L30), not from [Template.fromId()](https://github.com/Disciple153/aws-cdk/blob/c8282c84b5240ddb107282b18baaecdabb48ba12/packages/%40aws-cdk/aws-quicksight/lib/template.ts#L178))

I'm still having this problem

**Comment by TheRealAmazonKendra** [comment]
The bots are out of control... I did this. Putting up a fix ASAP.

**Comment by TheRealAmazonKendra** [comment]
Manually cancelled the linter for now.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
Sorry for the massive spam on this. I just pushed a fix so I'll watch and make sure it doesn't start looping through the automations again.

**Comment by TheRealAmazonKendra** [comment]
Looks like I got it fixed.

**Comment by moltar** [comment]
What happened @Disciple153? I was looking forward to this PR! :)

**Comment by Disciple153** [comment]
> What happened @Disciple153? I was looking forward to this PR! :)

It's still coming, but after talking to the CDK team, it was decided that this construct will start as a self-published resource. 

I will let you know when it becomes available.

Thank you for your interest!

**Comment by moltar** [comment]
@Disciple153 Please share your repo, I am interested in collaborating. This repo is too noisy and too complicated to foster drive-by collaboration. :)

**Comment by OperationalFallacy** [comment]
We experienced a similar issue. With the frequent changes that data engineers want to make in the Quicksight UI, it's challenging to define Quicksight resources directly from the code.

We addressed this with a load & transform & deploy method. We crafted functions such as `prepareDataSet` which accept a dataset definition and modify it to align with `CfnDataSetProps`.

For instance, the snippet below uses `object-mapper` library to map and perform simple transformations like updating account IDs and environments.

```javascript
const relationalTablePropertyMap = {
  "RelationalTable.Name": "relationalTable.name",
  "RelationalTable.DataSourceArn": {
    key: "relationalTable.dataSourceArn",
    transform: function (value: string) {
      return replaceAccountAndEnv(value, awsAccount, environment);
    },
  },
  "RelationalTable.InputColumns[].Type": "relationalTable.inputColumns[].type",
  "RelationalTable.InputColumns[].Name": "relationalTable.inputColumns[].name",
};
```

This method proved effective for us in managing an extensive Quicksight setup. Data engineers develop via the Quicksight UI, then use a pipeline for deploying across all environments, including development.

It takes less than hour to add new datasets, mostly waiting for PR review and the pipeline to finish.

**Comment by moltar** [comment]
> It's still coming, but after talking to the CDK team, it was decided that this construct will start as a self-published resource.

@Disciple153 What's the progress on this? Thanks!

**Comment by Disciple153** [comment]
@moltar Sorry to disappoint, but unfortunately I haven't been able to work on this in quite a while due to changing priorities from my manager. At this point, I would recommend pulling my PR and using a custom build of CDK. I would really like to finish this at some point, but it will take a lot more work to get this to a quality product with the introduction of the "definition" parameter in the Quicksight SDK, especially since the "definition" parameter is so obnoxious to work with.

**Pull request closed without merging**
