### PR TITLE
fix: Upgrade yaml version as a suggestion from GitHub Advisory

### PR DESCRIPTION
**Pull request by msdevanms**
Update package.json - Upgrade yaml version as a suggestion from GitHub Advisory [GHSA-f9xv-q969-pqx4](https://github.com/advisories/GHSA-f9xv-q969-pqx4)

> Upgrade yaml version
>
> Security vulnerability fix
> important design decisions you made. 
>
> Remember to follow the [CONTRIBUTING GUIDE] and [DESIGN GUIDELINES] for any
> code you submit.
>
> [CONTRIBUTING GUIDE]: https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md
> [DESIGN GUIDELINES]: https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md

Closes #<issue number here>.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by bahrmichael** [comment]
@msdevanms would you mind editing the commit message from "Upgrade yaml version as a suggestion from GitHub Advisory" to "fix: upgrade yaml version as a suggestion from GitHub Advisory"? If your IDE has no support for editing a commit, you could try to rebase interactively and edit the message there. If that doesn't work for you, I can add another PR with an update commit message to replace this.

**Comment by mrgrain** [comment]
Closing since the advisory has been updated to correctly reflect affected versions (which this one isn't) and the upgrade to v2 of yaml isn't trivial.

**Comment by bahrmichael** [comment]
@mrgrain What are your plans moving forward with this vulnerability?

**Comment by mrgrain** [comment]
@bahrmichael The version we use `1.10.2` is not effected by this. The original published advisory was incorrect and has been amended. See https://github.com/advisories/GHSA-f9xv-q969-pqx4

**Comment by bahrmichael** [comment]
Much appreciated! Thank you :)

**Pull request closed without merging**
