### PR TITLE
chore(region-info): Init Spain and Zurich

### PR DESCRIPTION
**Pull request by watany-dev**
fixes https://github.com/aws/aws-cdk/issues/23619

Note:
At first I intended to target only Spain; setting CLOUDWATCH_LAMBDA_INSIGHTS_ARNS 1.0.178.0 revealed that I needed Zurich. We did this as well.

### CODE REVIEW

**Comment by kaizencc** [comment]
Hi @watany-dev, I'm going to close this one because a few PRs have beat you to it:

- register eu-central-2: #24110
- register eu-south-2: #24121
- add insights versions: #23836

They're still open, because there's a bit of a dependency thing happening, but I'm going to give preference to what came first.

**Comment by watany-dev** [comment]
@kaizencc 

That is unfortunate. To break these dependencies, it would be a good idea to do a region init without the layer first!

**Comment by kaizencc** [comment]
@watany-dev what do you mean? Not sure how we are breaking dependencies?

**Comment by watany-dev** [comment]
@kaizencc 
No, sorry, I read the three PRs again and it seems I was mistaken.

**Pull request closed without merging**
