### PR TITLE
chore(config): add 3 new resource types

### PR DESCRIPTION
**Pull request by mazyu36**
Add 3 new resource types:

Ref: [AWS Config now supports 3 new resource types](https://aws.amazon.com/about-aws/whats-new/2024/12/aws-config-3-new-resource-types/)

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by nmussy — CHANGES_REQUESTED** [review]
I compared `rule.ts` with the documentation, and found these configs are also missing:

* `AWS::AppConfig::ExtensionAssociation`
* `AWS::Athena::DataCatalog`
* `AWS::Athena::WorkGroup`
* `AWS::Cognito::IdentityPool`
* `AWS::Cognito::UserPool`
* `AWS::Cognito::UserPoolClient`
* `AWS::Cognito::UserPoolGroup`
* `AWS::Config::ConfigurationRecorder`
* `AWS::Detective::Graph`
* `AWS::DMS::Certificate`
* `AWS::DMS::ReplicationInstance`
* `AWS::DMS::ReplicationTask`
* `AWS::EC2::NetworkInsightsAccessScope`
* `AWS::EC2::NetworkInsightsAnalysis`
* `AWS::EC2::VPCBlockPublicAccessOptions`
* `AWS::EKS::FargateProfile`
* `AWS::Evidently::Segment`
* `AWS::GroundStation::DataflowEndpointGroup`
* `AWS::IAM::OIDCProvider`
* `AWS::ImageBuilder::ImageRecipe`
* `AWS::Lambda::Alias`
* `AWS::M2::Environment`
* `AWS::MediaConnect::Gateway`
* `AWS::MemoryDB::SubnetGroup`
* `AWS::MSK::ClusterPolicy`
* `AWS::MSK::VpcConnection`
* `AWS::OpenSearchServerless::VpcEndpoint`
* `AWS::Redshift::EndpointAccess`
* `AWS::Redshift::EndpointAuthorization`
* `AWS::SageMaker::EndpointConfig`
* `AWS::SageMaker::NotebookInstanceLifecycleConfig`
* `AWS::SSM::Document`
* `AWS::Transfer::Profile`

There is also a typo for `AWS::IoTwinMaker::::Workspace`, which should be `AWS::IoTTwinMakerWorkspace`

Finally, it seems like `AWS::EventSchemas::Registry` and `AWS::IoTTwinMaker::ComponentType` are gone from [Supported Resource Types for AWS Config](https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html), so it might be worth deprecating it? Unsure what happened to it

**Comment by mazyu36** [comment]
@nmussy 
Thank you for the review. I'll investigate further.

**Review by kaizencc — COMMENTED** [review]
We gotta start thinking about generating this class from the doc page @nmussy linked or some other source of truth 😂

In the meantime there's no way we need to have a static property for _every_ single valud resource type... the whole point of an enum-like class is that you can use `of` and define whatever you want.

**Comment by mazyu36** [comment]
@kaizencc 
Thanks for your comments.
I agree there could be endless fixes, so I think I'll close this PR.
However, I felt we should fix the typo that @nmussy pointed out, so I've created a separate PR for that. #32655

> There is also a typo for AWS::IoTwinMaker::Workspace, which should be AWS::IoTTwinMaker::Workspace

**Pull request closed without merging**
