### PR TITLE
feat(sns): support topic's x-ray tracing configuration

### LINKED ISSUE #24187: sns: support SNS's tracing configuration
### Describe the feature

Update SNS Topic construct/props to allow enabling active tracing.

Active tracing was recently announced. Below are a couple of relevant links
- https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-sns-x-ray-active-tracing-visualize-analyze-debug-application-performance/
- https://docs.aws.amazon.com/xray/latest/devguide/xray-services-sns.html
- https://docs.aws.amazon.com/sns/latest/dg/sns-active-tracing.html

### Use Case

Support SNS Topic's new support for active tracing

### Proposed Solution

_No response_

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.62.0

### Environment details (OS name and version, etc.)

macOS

### PR DESCRIPTION
**Pull request by humanzz**
this change introduces support for the topic's x-ray tracing configuration announced in https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-sns-x-ray-active-tracing-visualize-analyze-debug-application-performance/

Closes #24187

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by humanzz** [comment]
I've raised some concerns about the DX, and how it's not ideal due to having to define X-Ray resource policies which I was hoping can be automatically handled by CDK in https://github.com/aws/aws-cdk/issues/24187#issuecomment-1432273862

I have not found a way, but am open for suggestions. Otherwise, the need to setup an X-Ray resource policy is included in the README's new section about X-Ray.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
So, I'm putting this into request changes because I'm thinking about the Resource Policy problem and if we can solve that so I want to put a hold on anyone potentially approving this just yet.

**Comment by humanzz** [comment]
@TheRealAmazonKendra any updates on this?

**Comment by Yehonal** [comment]
Waiting for this PR to have XRay Active Tracing on SNS since we need to enable it via CDK and not manually.

What's the status here? it's been 1 year already

**Pull request closed without merging**
