### PR TITLE
fix(aws-redshift): redshift multiple simultaneous tableColumns updates are unordered

### LINKED ISSUE #20495: @aws-cdk/aws-redshift : Table; new tableColumns ordering not preserved on UPDATE
### Describe the bug

When using the `Table` construct in the `@aws-cdk/aws-redshift` module, if you have a table that already exists, then you attempt to modify that table by adding more than one column, then the ordering of those columns is not guaranteed. It works correctly when creating tables because the entire operation is run in one `CREATE TABLE` SQL statement, however the addition of more than 1 new column at a time will create the columns out of order in a potentially erratic and unpredictable manner. The reason for this is because the addition of new columns is done with parallel asynchronous calls of `ALTER TABLE <tableName> ADD COLUMN <columnName> <dataType>` SQL statements. This can be seen [here](https://github.com/aws/aws-cdk/blob/f334060fca02e928bc4f5fdcfd45244060731d78/packages/%40aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts#L95-L100) executed where the `ALTER TABLE` statements are added to an array and then [here](https://github.com/aws/aws-cdk/blob/f334060fca02e928bc4f5fdcfd45244060731d78/packages/%40aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts#L143) where those statements are executed in an asynchronous fashion against the redshift data API. So whichever request arrives first to the API wins instead of the statements being executed as the developer would expect, being the order they specified in their CDK code.

### Expected Behavior

As a user of the Typescript version of this library, Arrays in typescript come ordered (as they do in most languages) so when I have an ordered array of column definitions, my expectation is that that order is preserved when applied to my table and that the columns in my CDK code match the columns in my Redshift table in terms of data type and ordering.

### Current Behavior

Currently, if I have a table and add more than one new column to that table at a time, the order of those columns will at random not match with the order I place them in my `tableColumns` array, even between deployments to different isolated environments that utilized the same templates.

### Reproduction Steps

If you only add 2 or 3 columns then there is a chance that they just happen to resolve in the correct order. I have added 10 here and am able to reproduce this bug every time I run it (ran 4 times). The code below worked for me as-is.

1. With the CDK, create a Redshift Cluster and a table inside of that Redshift Cluster.
2. With the CDK, Add a table to that redshift cluster with at least 1 column in it.

```ts
import {
  Cluster,
  ClusterType,
  NodeType,
  Table,
} from '@aws-cdk/aws-redshift';
import { Vpc } from '@aws-cdk/aws-ec2';
import * as cdk from '@aws-cdk/core';

const APP = new cdk.App();

class RedshiftStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);
    const vpc = new Vpc(this, 'RedshiftVpc');
    const databaseName = 'testdatabase';
    const cluster = new Cluster(this, databaseName, {
      clusterName: 'testcluster',
      clusterType: ClusterType.SINGLE_NODE,
      defaultDatabaseName: databaseName,
      masterUser: {
        masterUsername: 'admin_user',
      },
      nodeType: NodeType.DC2_LARGE,
      publiclyAccessible: false,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      vpc: vpc,
    });
    new Table(this, 'TestTable', {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      cluster,
      databaseName,
      tableName: 'public.test',
      tableColumns: [
        {
          name: 'column_1',
          dataType: 'TEXT',
        },
      ],
    });
  }
}

new RedshiftStack(APP, 'RedshiftStack', {});

```

3. Deploy the changes from the above 2 steps.

- `npm run build && cdk deploy RedshiftStack` 

4.. Add 10 new columns to that original table.

```ts
import {
  Cluster,
  ClusterType,
  NodeType,
  Table,
} from '@aws-cdk/aws-redshift';
import { Vpc } from '@aws-cdk/aws-ec2';
import * as cdk from '@aws-cdk/core';

const APP = new cdk.App();

class RedshiftStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);
    const vpc = new Vpc(this, 'RedshiftVpc');
    const databaseName = 'testdatabase';
    const cluster = new Cluster(this, databaseName, {
      clusterName: 'testcluster',
      clusterType: ClusterType.SINGLE_NODE,
      defaultDatabaseName: databaseName,
      masterUser: {
        masterUsername: 'admin_user',
      },
      nodeType: NodeType.DC2_LARGE,
      publiclyAccessible: false,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      vpc: vpc,
    });
    new Table(this, 'TestTable', {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      cluster,
      databaseName,
      tableName: 'public.test',
      tableColumns: [
        {
          name: 'column_1',
          dataType: 'TEXT',
        },
        {
          name: 'column_2',
          dataType: 'TEXT',
        },
        {
          name: 'column_3',
          dataType: 'TEXT',
        },
        {
          name: 'column_4',
          dataType: 'TEXT',
        },
        {
          name: 'column_5',
          dataType: 'TEXT',
        },
        {
          name: 'column_6',
          dataType: 'TEXT',
        },
        {
          name: 'column_7',
          dataType: 'TEXT',
        },
        {
          name: 'column_8',
          dataType: 'TEXT',
        },
        {
          name: 'column_9',
          dataType: 'TEXT',
        },
        {
          name: 'column_10',
          dataType: 'TEXT',
        },
        {
          name: 'column_11',
          dataType: 'TEXT',
        },
      ],
    });
  }
}

new RedshiftStack(APP, 'RedshiftStack', {});
```

6. Deploy the changes from that step.

- `npm run build && cdk deploy RedshiftStack` 

7. Observe the chaotic ordering of those new columns.

You would expect to query the redshift database and see the columns in the numeric order matching what is laid out above in the `tableColumns` array, however you will get something more like this:

```SQL
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'test' AND table_schema = 'public'
ORDER BY ordinal_position ASC
;
/* 
-- This is the actual order of the columns after running the exact above code snippets
column_name |
------------+
column_1    |
column_4    |
column_7    |
column_6    |
column_10   |
column_5    |
column_11   |
column_9    |
column_2    |
column_3    |
column_8    |
*/
```

Feel free to edit the stack, remove the new columns, then read-add them and get a whole new order! I did exactly that and on the second attempt got the following column order:

```SQL
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'test' AND table_schema = 'public'
ORDER BY ordinal_position ASC
;
/* 
-- This is the actual order of the columns after running the exact same above code snippets a second time!
column_name |
------------+
column_1    |
column_5    |
column_11   |
column_9    |
column_2    |
column_4    |
column_7    |
column_10   |
column_3    |
column_8    |
column_6    |
*/
```

### Possible Solution

There are 2 ways to solve this as I see it.

1. Synchronize the async calls to `executeStatement()` performed [here](https://github.com/aws/aws-cdk/blob/f334060fca02e928bc4f5fdcfd45244060731d78/packages/%40aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts#L143).

So instead of:

```ts
await Promise.all(alterationStatements.map(statement => executeStatement(statement, tableAndClusterProps)));
```

it'd be more like:

```ts
// You really cannot use the `map` or `forEach` with
// `async`/`await` and expect things to run "in order"
for (let index = 0; index < alterationStatements.length; index++) {
  await executeStatement(alterationStatements[index], tableAndClusterProps);
}
```

This will take a while to execute and require many round trips to the API, but it would "work".

2. Or perhaps even better in my opinion, run the calls all together using the [BatchExecuteStatement](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-redshift-data/classes/batchexecutestatementcommand.html) endpoint to group all of the statements together in one transaction, run in order by the redshift-data API. Currently the `Table` construct only leverages the [ExecuteStatement](https://github.com/aws/aws-cdk/blob/75bfce70dbc57fe688c96b3c5cbb67fc4e6fcc56/packages/%40aws-cdk/aws-redshift/lib/private/database-query-provider/redshift-data.ts#L14) endpoint on the redshift-data API. The shape of the output and response from the batch endpoint matches that of the regular execute endpoint:

```JSON
// From BatchExecuteStatement
{
  "ClusterIdentifier": "testcluster",
  "CreatedAt": "2022-05-25T09:02:55.390000-05:00",
  "Database": "testdatabase",
  "DbUser": "admin_user",
  "Id": "a0836ead-c510-4ffc-941c-d3a8f5be3daa"
}
// From ExecuteStatement
{
  "ClusterIdentifier": "testcluster",
  "CreatedAt": "2022-05-25T09:03:41.297000-05:00",
  "Database": "testdatabase",
  "DbUser": "admin_user",
  "Id": "0eddb16c-510a-4a9d-afe2-722db7998ed8"
}
```

and the subsequent call made to [waitForStatementComplete](https://github.com/aws/aws-cdk/blob/75bfce70dbc57fe688c96b3c5cbb67fc4e6fcc56/packages/%40aws-cdk/aws-redshift/lib/private/database-query-provider/redshift-data.ts#L18-L34) could remain unchanged as well. The shape of the response on DescribeStatement changes slightly for the case when one describes a batch execute statement, but not in a way that would break the API response to this function.

```JSON
// DescribeStatement for BatchExecuteStatement
{
  "ClusterIdentifier": "testcluster",
  "CreatedAt": "2022-05-25T09:02:55.390000-05:00",
  "Duration": 252031968,
  "HasResultSet": true,
  "Id": "a0836ead-c510-4ffc-941c-d3a8f5be3daa",
  "RedshiftPid": 1076886687,
  "RedshiftQueryId": 0,
  "ResultRows": -1,
  "ResultSize": -1,
  "Status": "FINISHED",
  "SubStatements": [
    {
      "CreatedAt": "2022-05-25T09:02:55.556000-05:00",
      "Duration": 252031968,
      "HasResultSet": true,
      "Id": "a0836ead-c510-4ffc-941c-d3a8f5be3daa:1",
      "QueryString": "SELECT COUNT(*) FROM public.test",
      "RedshiftQueryId": 478136,
      "ResultRows": 1,
      "ResultSize": 20,
      "Status": "FINISHED",
      "UpdatedAt": "2022-05-25T09:02:56.393000-05:00"
    }
  ],
  "UpdatedAt": "2022-05-25T09:02:56.455000-05:00"
}
// DescribeStatement for ExecuteStatement
{
  "ClusterIdentifier": "testcluster",
  "CreatedAt": "2022-05-25T09:03:41.297000-05:00",
  "Duration": 7063568,
  "HasResultSet": true,
  "Id": "0eddb16c-510a-4a9d-afe2-722db7998ed8",
  "QueryString": "SELECT COUNT(*) FROM public.test",
  "RedshiftPid": 1076788377,
  "RedshiftQueryId": 478146,
  "ResultRows": 1,
  "ResultSize": 20,
  "Status": "FINISHED",
  "UpdatedAt": "2022-05-25T09:03:41.893000-05:00"
}
```

The only difference would be the existence of the `SubStatements` attribute on a batch statement. In effect though, you could just replace the use of the `executeStatement` endpoint entirely with the `batchExecuteStatement` one, and change one of the input properties from `Sql: string` to `Sqls: string[]` and viola, done. Of course you would need to update everywhere that calls `executeStatement` to pass in an array of strings not a string, but this would be pretty trivial to fix. The BatchExecuteStatement supports sending 1 or more SQL statements, so it would be compatible with the rest of the single-statement redshift-data API calls as well.

### Additional Information/Context

Happy to raise the Pull Request here for this one myself. Would love to know your thoughts on switching from the ExecuteStatement command to the BatchExecuteStatement command as that seems like the best way forward here in my opinion.

Here is my `package.json` if that helps

```JSON
{
  "name": "src",
  "version": "0.1.0",
  "bin": {
    "src": "bin/src.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk --profile sandbox",
    "lint": "eslint bin/src.ts lib/*.ts",
    "lint-fix": "eslint bin/src.ts lib/*.ts --fix"
  },
  "devDependencies": {
    "@aws-cdk/assert": "1.137.0",
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "@typescript-eslint/eslint-plugin": "^5.9.0",
    "@typescript-eslint/parser": "^5.9.0",
    "aws-cdk": "2.1.0",
    "eslint": "^8.6.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-cdk": "^1.6.0",
    "eslint-plugin-import": "^2.25.4",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "@aws-cdk/aws-ec2": "1.137.0",
    "@aws-cdk/aws-glue": "1.137.0",
    "@aws-cdk/aws-iam": "1.137.0",
    "@aws-cdk/aws-kms": "1.137.0",
    "@aws-cdk/aws-redshift": "1.137.0",
    "@aws-cdk/aws-s3": "1.137.0",
    "@aws-cdk/core": "1.137.0",
    "source-map-support": "^0.5.16"
  }
}
```

I did have `eslint` set up as you can see above but that is not required for reproducing this bug.

### CDK CLI Version

2.1.0 (build f4f18b1)

### Framework Version

_No response_

### Node.js Version

v16.15.0

### OS

macOS 12.3.1 (21E258)

### Language

Typescript

### Language Version

TypeScript (3.9.10)

### Other information

- [here](https://zellwk.com/blog/async-await-in-loops/) is an article on why this happens out of order when doing `await Promise.all(array.map())`. (there are many such articles out there if you do some light googling)

here is a small nodejs program you can run to see this mess in action for yourself:

```js
/**
 * async "sleep" function to sleep form some number of miliseconds
 * @param {number} ms - The number of miliseconds to sleep for.
 * @return {Promise<void>} - The words of politicians
 */
function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

/**
 * Random int, returns a random integer from 0 to 2
 * @return {number} - The random number
 */
function randint() {
  return Math.floor(Math.random() * (3 - 0) + 0);
}

/**
 * "Print It"
 * Log an output to the console with a random delay from 0 - 2 miliseconds. This
 * imitates a very small potential delay in reaching the API.
 * @param {string} it - The "it" to print in "print it"
 * @return {void}
 */
async function printIt(it) {
  await sleep(randint());
  await console.log(it);
};

/**
 * This is the "print all" function intended to print all of the things in an
 * array. It is written to mirror what happens in the Table construct when an
 * update is called to add an array of columns to a table.
 * @param {string[]} cols - The names of the columns to add to the table.
 * @return {Promise<void>} - Nothing really.
 */
function printAll(cols) {
  return Promise.all(cols.map((col) => printIt(col)))
}

/**
 * This is the "print all" function intended to print all of the things in an
 * array. It is written to show what _should_ be happening when one tries to
 * update a table using an array of columns
 * @param {string[]} cols - The names of the columns to add to the table.
 * @return {Promise<void>} - Nothing really.
 */
async function betterPrintAll(cols) {
  for (let index = 0; index < cols.length; index++) {
    await printIt(cols[index]);
  }
}

/**
 * An ordered array of columns
 */
const cols = [
  'ALTER TABLE gorilla.nems ADD COLUMN bing TEXT',
  'ALTER TABLE gorilla.nems ADD COLUMN bong TEXT',
  'ALTER TABLE gorilla.nems ADD COLUMN eff TEXT',
  'ALTER TABLE gorilla.nems ADD COLUMN ya_life TEXT',
]

/** Runs the 2 print statements to compare output */
async function main() {
  console.log("Here is the printAll() funciton, and it is rarely in order. I will run it 3 times and expect 3 different outputs.")
  console.log("#1")
  await printAll(cols);
  console.log("#2")
  await printAll(cols);
  console.log("#3")
  await printAll(cols);
  console.log("")
  console.log("Here is the betterPrintAll() function. I will run it 3 times and it will be in the same, correct order every time.")
  console.log("#1")
  await betterPrintAll(cols);
  console.log("#2")
  await betterPrintAll(cols);
  console.log("#3")
  await betterPrintAll(cols);
}

main();
```

### PR DESCRIPTION
**Pull request by Romanmc72**
# Description

This bug was identified while attempting to deploy a change to a redshift table using the CDK. The attempted change was adding more than 1 column at a time to an existing, cdk-controlled redshift table. The bug is that the ordering of the columns is not preserved when the new columns are added to the table.

## Why Does This Happen

Given the existing Table construct code uses the `executeStatement` aws sdk redshift-data API endpoint wrapped in a `Promise.all()`, the column ordering was coming out at seemingly random because the `ALTER TABLE` statements were run in parallel against the API, and whichever requests arrived first happened first (as opposed to them happening in the order specified by the developer in the `Table` construct).

## Possible Solutions

1. Instead of using `Promise.all(statements.map(executeStatement()))` to execute the API calls, run them in a `for (...) { await executeStatement() }` loop to guarantee that the statements are run in order
2. Instead of using the `executeStatement()` aws sdk redshift-data API endpoint, use the `batchExecuteStatement()` endpoint to run all of the statements in one transaction, in order.

## Chosen Solution

I chose to implement the `batchExecuteStatement()` API call instead of simply adding a for loop.

### Pros

- This approach uses fewer round trips to the API than a synchronous for loop would
- It is compatible with the existing statements that only contain 1 SQL statement (`batchExecuteStatement()` can run 1 - 40 SQL statements at a time)

### Cons

- It did require changing all of the other places where SQL was executed as 1 statement from strings `'CREATE ...'` to arrays of string `['CREATE ...']` (resulting in more to review)
- There is a 40 statement limit per batch, so I needed to add a loop anyway that checked the length of the incoming statements array and split it into chunks of 40 at a time

## Tests

Based on what I can gather from the required tests to run (linting, unit, and integration tests should all pass), I ran those using the following from this directory `packages/@aws-cdk/aws-redshift` after successfully building with `../../../scripts/buildup`.

tests:

`yarn test` - PASS
`yarn lint` - PASS
`yarn integ` - PASS

## Issues

- The detailed report in the bug in question: fixes #20495

----

### All Submissions:

* [ Y ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ N ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ / ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ Y ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by peterwoodworth** [comment]
Thanks a bunch for this @Romanmc72,

We should be able to review this in the next week or two 🙂

**Comment by HsiehShuJeng** [comment]
From the perspective of crafting a function that can add new columns into an existing table in sequence as a developer intends, this is great work, @Romanmc72 
And from the point of view in the flow of data analysis, is it possible to hear from you that a specific scenario where newly-added columns in sequence as an executor (developers, analysts, etc.) intends is indeed required?
Take Table A as example:
| col_A| col_B|
| --- | --- |
| string | numeric|


Say, `col_c`, `col_d`, and `col_e` are required to be added into the existing table. Since how the function is define as you already figured out, it might be
| col_A| col_B| col_c | col_e | col_d |
| --- | --- | --- | --- | --- |
| string | numeric| string | string | timestamp |

or 

| col_A| col_B| col_c | col_d | col_e |
| --- | --- | --- | --- | --- |
| string | numeric| string | timestamp | string |

When an analyst, or related role, intends to query this updated table, he/she needs to specify which column he/she wants to see as the following:
```sql
SELECT col_d, col_e
FROM Table_A
.
.
.
```
No matter what order the new columns are added, subsequent queries won't be affected, at least those that need to be specified specifically. So there are 2 things I want to feedback:
1. In what scenario, newly-added columns into an existing table is indeed required as an infra maintainer wants ?
2. Integrating the work and the above statement, would leaving an argument as a boolean type for CDK developers to choose whether they want to keep the order be better if the scenario indeed existed?

**Comment by HsiehShuJeng** [comment]
# Brief
After some experiment, it can be concluded, from [this snippet](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts#L95-L100) and [this snippet](https://github.com/aws/aws-cdk/blob/fd5808f47111c0f72050f60e414df7f3f4ded6aa/packages/%40aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts#L143), that adding (updating) columns of an existing table might not be the order which an infra developer declares in a CDK application. The original set of columns won't be changed.  
# Conclusion
1. Once again, **in what scenario, users (such as analysts) will encounter error if added columns are not ordered as the CDK application intends**.  
    _Within the scenario that a query needs to be specific, i.e., columns need to be specified, the current implementation won't affect users (query executor). If a scenario that the nature of the current implementation will affect users indeed exist, then the suggestion and implementation by @Romanmc72 should be considered seriously._
2. Based on the previous statement, review on this implementation with more care on TS/JS or tests possibly needs to be conducted.  

# Experimental steps
1. Create a table with 6 columns
    Screen Shot 2022-06-13 at 7 48 36 AM
   ```typescript
   import * as cdk from 'aws-cdk-lib';
   import * as ec2 from 'aws-cdk-lib/aws-ec2';
   import * as redshift_alpha from '@aws-cdk/aws-redshift-alpha';import { Construct } from 'constructs';
   .
   .
   .
   const vpc = ec2.Vpc.fromLookup(this, 'defaultVpc', { isDefault: true });
   const rfRole = new RedshiftIamRole(this, 'RedshiftIam');
   const cluster = new redshift_alpha.Cluster(this, 'Redshift', {
   clusterName: 'scott-experiment',
   clusterType: redshift_alpha.ClusterType.SINGLE_NODE,
      masterUser: {
         masterUsername: 'admin'
      },
      vpc,
      vpcSubnets: {
         subnets: vpc.publicSubnets
      },
      publiclyAccessible: true
    });
   new redshift_alpha.Table(this, 'TestTable', {
      cluster: cluster,
      tableName: 'users',
      tableColumns: [
         {
            name: 'userid',
            dataType: 'integer'
         },
        {
          name: 'username',
          dataType: 'char(8)'
        },
        {
          name: 'firstname',
          dataType: 'varchar(30)'
        },
        {
          name: 'lastname',
          dataType: 'varchar(30)'
        },
        {
          name: 'city',
          dataType: 'varchar(30)'
        },
        {
          name: 'state',
          dataType: 'char(2)',
        }
      ],
      databaseName: 'dev'
    });
    cluster.connections.allowDefaultPortFromAnyIpv4('Open to the world');
    new cdk.CfnOutput(this, 'Cluster', {
      value: cdk.stringToCloudFormation(cluster.secret?.secretName!),
      description: 'The name of the secret attached to the cluster.'
    });
    new cdk.CfnOutput(this, 'SocketAddress', {
      value: cluster.clusterEndpoint.socketAddress,
      description: '\n"HOSTNAME\":\"PORT\" for the cluster'
    });
   ```  
4. Update the table with 10 columns, i.e., adding 4 columns.
     Screen Shot 2022-06-13 at 7 53 07 AM

    ```typescript
    new redshift_alpha.Table(this, 'TestTable', {
      cluster: cluster,
      tableName: 'users',
      tableColumns: [
        {
          name: 'userid',
          dataType: 'integer'
        },
        {
          name: 'username',
          dataType: 'char(8)'
        },
        {
          name: 'firstname',
          dataType: 'varchar(30)'
        },
        {
          name: 'lastname',
          dataType: 'varchar(30)'
        },
        {
          name: 'city',
          dataType: 'varchar(30)'
        },
        {
          name: 'state',
          dataType: 'char(2)',
        },
        {
          name: 'email',
          dataType: 'varchar(100)'
        },
        {
          name: 'phone',
          dataType: 'char(14)'
        },
        {
          name: 'likesports',
          dataType: 'boolean'
        },
        {
          name: 'likeheatre',
          dataType: 'boolean'
        }
      ],
      databaseName: 'dev'
    });
    ```
5. Update the table with 13 columns, i.e., adding 3 columns.
    Screen Shot 2022-06-13 at 7 59 14 AM

   ```typescript
   new redshift_alpha.Table(this, 'TestTable', {
      cluster: cluster,
      tableName: 'users',
      tableColumns: [
        {
          name: 'userid',
          dataType: 'integer'
        },
        {
          name: 'username',
          dataType: 'char(8)'
        },
        {
          name: 'firstname',
          dataType: 'varchar(30)'
        },
        {
          name: 'lastname',
          dataType: 'varchar(30)'
        },
        {
          name: 'city',
          dataType: 'varchar(30)'
        },
        {
          name: 'state',
          dataType: 'char(2)',
        },
        {
          name: 'email',
          dataType: 'varchar(100)'
        },
        {
          name: 'phone',
          dataType: 'char(14)'
        },
        {
          name: 'likesports',
          dataType: 'boolean'
        },
        {
          name: 'likeheatre',
          dataType: 'boolean'
        },
        {
          name: 'likeconcerts',
          dataType: 'boolean'
        },
        {
          name: 'likejazz',
          dataType: 'boolean'
        },
        {
          name: 'likeclassical',
          dataType: 'boolean'
        }
      ],
      databaseName: 'dev'
    });
   ```

**Comment by Romanmc72** [comment]
Thanks for the feedback @HsiehShuJeng . After considering your point as to whether or not the column order matters, I think you are correct. There is not a truly "mission critical" use case that I can imagine where the column order breaks things. There are cases where it makes life more annoying and it makes your infrastructure as code not as "repeatable". After thinking on it, to get this to be fully column-order-guaranteed we would need to add a few more enhancements to track the current column order in order and to raise an error whenever columns are inserted in the middle of the table definition or shuffled around to a different order (because redshift does not support adding columns anywhere except at the end). Adding a flag to let the developer decide whether or not column order matters to them makes some sense to me, but I am also aligned to the idea that the ordering of columns *should* never matter given you can (and should) specify column order on every operation whether it be `SELECT`, `INSERT`, `COPY`, etc... If we got the route of declaring that the CDK folks do not consider column order in Redshift an actual thing that matters (which it is a thing and it does matter to some folks) then we should include that in the official documentation on the reference guide for the table construct in redshift.

This issue arose for me when I added 10 columns to a table that already had +600 columns (600 columns!? isn't that bad design? of course. my choice? absolutely not. you cannot always control how data comes to you). Before I added the 10 new columns, I was just running `COPY schema.table FROM s3://... IAM_ROLE ... FORMAT CSV` which worked great. Now my only option is to add the list of all +610 of the columns, in order to my `COPY` command for it to work. So is it "mission critical" no. Is it super annoying and does not work as I expected it? I would say so, yes.

**Comment by Romanmc72** [comment]
We can close this if it is deemed unnecessary by the CDK team.

**Comment by pahud** [comment]
> We can close this if it is deemed unnecessary by the CDK team.

I am not sure if this is necessary or critical but we welcome people to vote up this PR if you have similar scenario like this. For now I suggest we close this PR as it seems not really a bug. @peterwoodworth wdyt?

**Comment by peterwoodworth** [comment]
If this PR isn't planning on being worked on soon then we can close this out. We're still tracking the issue in https://github.com/aws/aws-cdk/issues/20495 🙂

**Pull request closed without merging**
