### PR TITLE
feat(pipelines): add PolicyStatements to CodeBuild project role

### PR DESCRIPTION
**Pull request by luisantonioa**
Fixes aws/aws-cdk#9163

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by srethira** [comment]
Any update on this issue?

**Comment by luisantonioa** [comment]
> 
> 
> Any update on this issue?

It has been approved.. but then is out of date. I click Update branch and then it needs an approval again.. and the cycle continues :(

**Comment by rix0rrr** [comment]
The problem it's not merging is not because it's out of date. It's because the build is failing.

**Comment by luisantonioa** [comment]
> 
> 
> The problem it's not merging is not because it's out of date. It's because the build is failing.

I couldn't tell why it was failing. Thanks for the fix and the merge. I wish I had more time to have sorted it out earlier, but was confused by the 2 previous approvals.

**Comment by luisantonioa** [comment]
I copied the test from: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/test/builds.test.ts#L14

Should that test have the same change applied?

**Pull request merged**
