### PR TITLE
fix(lambda): erroneous inline code support for ruby

### LINKED ISSUE #6302: Lambda Ruby Runtime doesn't Support ZipFile
This implies that the Lambda Ruby runtime supports `ZipFile` (aka inline code).  https://github.com/aws/aws-cdk/blob/a1cd7432eb817a0a9361c907445c01eea4cb1321/packages/%40aws-cdk/aws-lambda/lib/runtime.ts#L50

However, when deploying a function like this

```typescript
new lambda.Function(stack, 'foobar', {
  code: new lambda.InlineCode('def handler(event:, context:) ; "success" ; end'),
  handler: 'index.handler',
  timeout: cdk.Duration.seconds(15),
  runtime: lambda.Runtime.RUBY_2_5
});
```

I get the following error from CloudFormation 

```
 19/52 | 9:14:58 PM | CREATE_FAILED        | AWS::Lambda::Function            | foobar (foobarF27D68A9) ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, nodejs12.x, python2.7, python3.6, python3.7.
```

The [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html) are also mentioning just nodejs and python 

### Environment

  - **CLI Version 1.22.0 (build 309ac1b)**

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nija-at**
## Commit Message
fix(lambda): erroneous inline code support for ruby (#6365)

See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile

fixes #6302

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by iliapolo** [comment]
@nija-at Can we add some kind of test? 

https://github.com/aws/aws-cdk/pull/6365/checks?check_run_id=455627583

I would imagine the following code should fail on instantiation, right?

```typescript
new lambda.Function(stack, 'foobar', {
  code: new lambda.InlineCode('def handler(event:, context:) ; "success" ; end'),
  handler: 'index.handler',
  timeout: cdk.Duration.seconds(15),
  runtime: lambda.Runtime.RUBY_2_5
});
```

**Comment by nija-at** [comment]
> I would imagine the following code should fail on instantiation, right?

Yes, this would previously fail on `cdk deploy` but would now fail earlier.

> can we add some kind of test?

There's no 'useful' test I can think of. Suggestions?

**Comment by iliapolo** [comment]
> There's no 'useful' test I can think of. Suggestions?

I guess that depends where exactly the code will fail. But my suggestion is to add a validation in the `lambda.Function` constructor:

```typescript
if (props.code instanceof InlineCode && !props.runtime.supportsInlineCode) {
  throw new ...
}
```

And then simply add a test to [test.function.ts](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-lambda/test/test.function.ts). 

WDYT?

**Comment by iliapolo** [comment]
@nija-at I guess an even simpler test would be:

```
const rubyRuntime = lambda.Runtime.RUBY_2_5;
assert !rubyRuntime.supportsInlineCode 
```

That is assuming we have a test further down the line that validates we fail when defining inline code with an unsupported runtime.

**Comment by nija-at** [comment]
@iliapolo - sorry, but I don't find these to be useful tests. They are not testing any cyclomatic complexity. 
How would such a test have prevented this in the first place? The person who did this erroneously, would also erroneously add the test.

The only valuable test would be an integration test that attempts to deploy a stack and checks that the deployment succeeds. Unfortunately, we don't have a mechanism in place to do this during PR or pipeline builds.

**Pull request merged**
