### PR TITLE
feat(aws-s3-deployment): Define the log group for the lambda deployment function

### PR DESCRIPTION
**Pull request by miguel-a-calles-mba**
AWS will automatically create a log group for the lambda function after its first execution. This log group is not managed by CloudFormation. This PR aims to create the log group so CloudFormation can manage it.

BREAKING CHANGE:
* **aws-s3-deployment:** CloudFormation may rollback if the log group already exists. Delete the log group before deploying with this update.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by otaviomacedo** [comment]
Hi, @miguel-a-calles-mba

Thanks for contributing. Can you please just check the integration test error:

> @aws-cdk/aws-s3-deployment: Error: Some stacks have changed. To verify that they still deploy successfully, run: 'yarn integ integ.bucket-deployment-cloudfront.js integ.bucket-deployment.js'

**Comment by miguel-a-calles-mba** [comment]
@otaviomacedo, will do. Thanks.

**Comment by otaviomacedo** [comment]
@miguel-a-calles-mba another thing: `aws-s3-deployment` is a stable module, so we should not introduce any breaking changes to it. And this will break pretty much every stack that uses this construct. Is there a strong reason to use the CloudFormation managed log group?

**Comment by miguel-a-calles-mba** [comment]
I can set the CloudWatch log group lifecycle rule for the auto-generated log group outside of CDK.

**Pull request closed without merging**
