### PR TITLE
fix(aws-eks): kubectlEnabled: false conflicts with addNodegroup

### PR DESCRIPTION
**Pull request by pahud**
fix(aws-eks): kubectlEnabled: false conflicts with addNodegroup

This PR allows `cluster.addNodegroup()` when `kubectlEnabled` is `false`

Closes: #7993 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
This PR is still failing the test. I am still trying to figure it out.

圖片

**Comment by pahud** [comment]
Hi @eladb 

Now according to the test, the test statement will not create 

**Custom::AWSCDK-EKS-KubernetesResource Cluster/AwsAuth/manifest/Resource**
and
**AWS::CloudFormation::Stack @aws-cdk--aws-eks.KubectlProvider.NestedStack**

```ts
    // GIVEN
      const { stack } = testFixture();

      // WHEN
      new eks.Cluster(stack, 'MyCluster', {
        clusterName: 'my-cluster-name',
      });
```

So we will lose one AssumeRole policy for the `KubectlProviderHandlerServiceRole`.

Do you think it's safe to simply remove this statement from the test expection?

**Comment by eladb** [comment]
> Do you think it's safe to simply remove this statement from the test expection?


yes

**Comment by pahud** [comment]
Hi @eladb  tests all passed please review and approve again. Thanks.

**Pull request merged**
