### PR TITLE
chore: yarn upgrade

### PR DESCRIPTION
**Pull request by comcalvi**
woops, this is the wrong change: see https://github.com/aws/aws-cdk/pull/19454 for the actual change.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by Chriscbr — APPROVED** [review]

**Review by kaizen3031593 — APPROVED** [review]

**Comment by yuth** [comment]
Don't we need to pin the `aws-sdk-js` version to `2.1093.0` instead of updating the `yarn.lock` as the lock file is development time only.

**Comment by polothy** [comment]
Looking at the build log:

```
aws-cdk: In package package.json
aws-cdk: - [bundle/outdated-attributions] THIRD_PARTY_LICENSES is outdated (fixable)
aws-cdk: Error: Some package.json files had errors
aws-cdk:     at main (/codebuild/output/src901086373/src/github.com/aws/aws-cdk/tools/@aws-cdk/pkglint/bin/pkglint.js:30:15)
aws-cdk:     at Object.<anonymous> (/codebuild/output/src901086373/src/github.com/aws/aws-cdk/tools/@aws-cdk/pkglint/bin/pkglint.js:33:1)
aws-cdk:     at Module._compile (internal/modules/cjs/loader.js:999:30)
aws-cdk:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
aws-cdk:     at Module.load (internal/modules/cjs/loader.js:863:32)
aws-cdk:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
aws-cdk:     at Module.require (internal/modules/cjs/loader.js:887:19)
aws-cdk:     at require (internal/modules/cjs/helpers.js:74:18)
aws-cdk:     at Object.<anonymous> (/codebuild/output/src901086373/src/github.com/aws/aws-cdk/tools/@aws-cdk/pkglint/bin/pkglint:2:1)
aws-cdk:     at Module._compile (internal/modules/cjs/loader.js:999:30)
aws-cdk: Error: pkglint exited with error code 1
```

So, maybe just need to run [pkglint locally](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#linters)?

**Comment by polothy** [comment]
Well, I couldn't get it to run locally.  But thanks for this effort, getting SSO support will be absolutely wonderful, cannot wait 😄

**Comment by comcalvi** [comment]
closing this in favor of https://github.com/aws/aws-cdk/pull/19454

**Pull request closed without merging**
