### PR TITLE
fix(lambda-python): asset hash is non-deterministic

### LINKED ISSUE #12684: (aws-lambda-python): skip build lambda for all  cdk commands
Is it possible to avoid to rebuild lambda at every cdk diff or cdk deploy if no updates are made on them?

### Use Case

Every time that i need to change a single configuration parameter on a stack, all lambdas are rebuilt with docker and it takes too much time to deploy a single stack

### Proposed Solution

Implement an hash check between lambda version or a flag that enable or disable lambda build

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### LINKED ISSUE #12770: (aws-lambda-python): Change assetHashType to cdk.AssetHashType.SOURCE
I noticed that my lambda layers get rebuild everytime I run the cdk.

Becaus the current implementation defines `cdk.AssetHashType.BUNDLE` it has some side effects if dependencies change. I can mitigate the side effects by specifining the versions in the `requirements.txt` e.g. `pandas==1.1.*` but still it always bundles the layer even if nothing changes.

I would propose to change the `assetHashType` to `SOURCE` especially because `BUNDLE` is deprecated and the suggested change to `OUTPUT` would still have the described side effects mentioned above.

https://github.com/aws/aws-cdk/blob/7dc45b2d8fc2f63497adb624fdfe4207c4eca269/packages/%40aws-cdk/aws-lambda-python/lib/bundling.ts#L65

That would also solve #12684

### PR DESCRIPTION
**Pull request by eladb**
When a Python handler uses external dependencies, the hash calculated on the output is non-determinstic due to the fact that it includes timestamps. To resolve that, change the asset hash strategy to `SOURCE` which means that the bundle will only be re-created if one of the source files changes.

Additionally, the Python image hash, which is also included in the asset hash (to ensure that if the build image changes, the bundle is invalidated) included the absolute path for the `Dockerfile`. This caused the image hash itself to change every time the image was built on a different system. To fix this, we stage the dependency files & dockerfile into a temp directory and build the image from there.

Fixes #12770
Fixes #12684

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by iliapolo — COMMENTED** [review]
This means effectively forcing users to modify their `requirements` in order to push an updated version of a dependency. Maybe make this configurable?

**Comment by eladb** [comment]
> This means effectively forcing users to modify their requirements in order to push an updated version of a dependency. Maybe make this configurable?

What do you mean by configurable? What kind of API would you imagine? `deployOnEveryUpdate`? This conflicts with one of the foundational tenets we have in the CDK which says that only when the source changes your app changes. We have multiple places in our tooling (CLI/CDK pipelines) which rely on that tenet.

Technically, they don't need to modify `requirements.txt`, just to change something in their source. So they can just add a comment somewhere and bump a random value in order for their bundle to be recreated.

Let me know how do you propose to model this.

**Review by iliapolo — APPROVED** [review]
> This conflicts with one of the foundational tenets we have in the CDK which says that only when the source changes your app changes.

Yeah, and I'm all for it. But we do have this option of using `OUTPUT`, which presumably addresses changes in dependencies (?). I'm just wondering if should address the use case of users explicitly not locking their dependencies, expecting them to update on build, which is what happens now. 

As far as API, yeah something like `deployOnEveryUpdate`, or maybe even straight up expose `hashType` for advanced users. I can try to come up with something less awkward if you choose to pursue it. But i'm also good with using `SOURCE` for now and possibly extending later. 

Added `do-not-merge`.

**Comment by fsmanuel** [comment]
@eladb thanks for working on this!
@iliapolo I can partially understand your concerns. As I tried to explain in #12770 I'm worried about the current side effects.

I think the best solution would be to allow to set `assetHashType` via `PythonFunctionProps` and `PythonLayerVersionProps`. We can stick to the current behavior but make it possible to change it to `SOURCE` if desired.

**Comment by eladb** [comment]
I'll add a way to control this, but I think the default should be `SOURCE`

**Pull request merged**
