### PR TITLE
feat(ec2): imported SecurityGroups don't create egress rules

### PR DESCRIPTION
**Pull request by ayazhussein**
Security Groups are created with `allowAllOutbound: true` by default, and so imported security groups default to that as well. This means that no egress rules will be created for them, because that will undo the default of allowAllOutbound.

This can be configured by setting `allowAllOutbound: false` upon importing.

### CODE REVIEW

**Comment by ayazhussein** [comment]
attempt to fix #3355

**Comment by rix0rrr** [comment]
Not 100% opposed, but is adding ingress and egress rules to the securitygroup directly not good enough?

**Comment by ayazhussein** [comment]
true, adding to security group is good but since manipulating default security group, it would be easier or more friendly to be able to add only one-way security group instead of two-ways

ex:

```javascript
const asg = new AutoScalingGroup(this, `AutoScalingGroup`, {...props})
// connection one-way
asg.connections.allowFrom(Peer.anyIpv4(), Port.allTraffic(), "bla bla", true)
// security group way
asg.connections.securityGroups[0].addIngressRule(Peer.anyIpv4(), Port.allTraffic(), "bla bla", true)
```

another solution would be to have a defaultSecurityGroup on connections obj so it would easier to add ingress/egress rules to the generated security group

**Comment by rix0rrr** [comment]
> adding the egress rule that was generated removes the default all outbound rule

Wait, this shouldn't be happening. There is an "allowAllOutbound" property on a security group that makes it so that adding egress rules becomes a no-op (or at least it should be).

Can you confirm that that behavior is broken?

**Comment by ayazhussein** [comment]
The issue appears when there is an existing Security group outside aws-cdk and you import it.

ex: 
```javascript
const existingSg = SecurityGroup.fromSecurityGroupId(this, "demoSG", "sg-1234567");

const asg = new AutoScalingGroup(this, `AutoScalingGroup`, {...props})

asg.connections.allowFrom(existingSg, Port.tcp(22), "ssh from demo instances")
```
this will create ingress/egress rule and the issue is that if "demoSG" has all traffic/all ports to 0.0.0.0/0 (being default security group egress rule), Cloudformation removes it and adds the new egress rule only, which is an issue in an existing infrastructure

**Comment by rix0rrr** [comment]
Yep, I got you. I think the proper solution will be to allow specifying that attribute when importing the SG then.

**Comment by ayazhussein** [comment]
How would that work?

**Comment by rix0rrr** [comment]
I think `SecurityGroup.fromSecurityGroupId()` would take an additional (optional) struct like this:

```ts
interface SecurityGroupImportOptions {
  /**
   * Whether the security group has been created to allow all outbound traffic.
   *
   * Unless set to `false`, no new outbound rules will be added to the security group.
   * 
   * @default true
   * @experimental
   */
  allowAllOutbound?: boolean;
}

class SecurityGroup {
  public static fromSecurityGroupId(scope: Construct, id: string, securityGroupId: string, options: SecurityGroupImportOptions = {}): ISecurityGroup {
   // ...
  }
}
```

Marking the property `@experimental` as I'm not sure yet whether I want it to be called `allowAllOutbound` or something like `ignoreEgressRules`.

**Comment by rix0rrr** [comment]
@ayazhussein will this satisfy your use case as well?

**Comment by ayazhussein** [comment]
@rix0rrr Hi, I couldn't test because of the build failing 
```
error: [awslint:from-signature:@aws-cdk/aws-ec2.SecurityGroup.fromSecurityGroupId] invalid method signature for fromXxx method  (expected="3",actual="4")
```

**Comment by ayazhussein** [comment]
yes, it is working great, no more `CfnSecurityGroupIngress`

**Comment by jogold** [comment]
Hey @rix0rrr 

FYI this change is "infrastructure" breaking because it deletes existing `AWS::EC2::SecurityGroupEgress` resources for stacks with imported security groups. I just encountered the case in one my stacks after upgrading to v1.6.0. This should be documented in the CHANGELOG.

**Comment by jogold** [comment]
Also this doesn't cover the case of imported clusters/instances in `@aws-cdk/aws-rds` where the `allowAllOutbound` prop in not exposed in the `fromDatabaseInstanceAttributes`/`fromDatabaseClusterAttributes`.

**Pull request merged**
