### PR TITLE
fix(lambda): imported Function still has region and account from its Stack, instead of its ARN

### LINKED ISSUE #18228: (aws-codepipelines-actions): Cannot set region on LambdaInvokeAction
### What is the problem?

`LambdaInvokeAction` does not accept region as a parameter. I have a CodePipeline that needs to invoke a function in a different region. I was hitting errors due to the LambdaInvokeAction assuming the region is the same as the CodePipeline, but it worked when I manually set the region in the action configuration in the AWS console. According to the [documentation](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-Lambda.html) this property can be defined in Cloudformation so it’s not clear why it’s not supported in CDK. I noticed that `LambdaInvokeActionProps` extends the `CommonActionProps` interface rather than the `ActionProperties` interface which does include the `region` field.

### Reproduction Steps

Created a Codepipeline stack in `us-west-2` with a stage containing a `LambdaInvokeAction` that needed to invoke a function in `us-east-1`.

### What did you expect to happen?

I expected to be able to define the region for the action to invoke the lambda.

### What actually happened?

The action had a region of us-west-2 and I could only change the region manually in the console.

### CDK CLI Version

1.108.0

### Framework Version

_No response_

### Node.js Version

14.16.1

### OS

Mac OS Big Sur (11.6)

### Language

Typescript

### Language Version

4.5.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by skinny85**
Fixes #18228

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by kaizen3031593 — APPROVED** [review]
🎉 thanks @skinny85

**Comment by jhoscar1** [comment]
@skinny85 I'm seeing that this was released in the 2.x version of cdk. Is it possible to get this released in 1.x or is there a plan to?

**Comment by skinny85** [comment]
@jhoscar1 looks like this just barely missed the release window for `v1.138.0`. There will be a new release (`v1.139.0`) next week, and then this will be included in that one for sure.

**Comment by jhoscar1** [comment]
Great, thanks!

**Comment by cbm-gplassard** [comment]
Hello, I think this breaks some of my usages when used in conjunction with `cdk.ScopedAws`  & the aws-events package (at least in unit tests)

```typescript
const lambdaFunction = lambda.Function.fromFunctionArn(this, 'Lambda', `arn:aws:lambda:${new cdk.ScopedAws(this).region}:${new cdk.ScopedAws(this).accountId}:function:${functionName}`);

const pipeline = new codepipeline.Pipeline(this, 'Codepipeline', {
      artifactBucket: "",
      pipelineName: "pipeline"
    });

pipeline.onStateChange('Notify', {target: new eventsTarget.LambdaFunction(lambdaFunction)});
```
```
Cannot create a cross-account or cross-region rule for an imported resource (create a stack with the right environment for the imported resource)
      at Rule.obtainMirrorRuleScope (node_modules/@aws-cdk/aws-events/lib/rule.ts:326:11)
      at Rule.addTarget (node_modules/@aws-cdk/aws-events/lib/rule.ts:170:38)
      at Pipeline.onEvent (node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:91:10)
      at Pipeline.onStateChange (node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:101:23)
```

It used to work with cdk 1.138.0

I can try to create a clean reproducer if you want

**Comment by skinny85** [comment]
@cbm-gplassard when you say this used to work, do you mean it used to `synth` / `deploy` in the previous CDK version, or do you mean it deployed, and the Function was actually invoked each time the pipeline's state changed? Because I have a feeling that wouldn't work anyway in the old version of the CDK.

**Comment by cbm-gplassard** [comment]
Hello @skinny85 ,
the stack was deployed & the function was correctly invoked.

I created a sample reproducer stack : https://github.com/cbm-gplassard/cdk-lambda-events-reproducer (one branch with cdk 1.138.0 and another with 1.139.0)

**Comment by skinny85** [comment]
@cbm-gplassard  I wonder - are you experiencing the same issue as described in https://github.com/aws/aws-cdk/issues/18405?

If so, can we consolidate the conversation there?

**Comment by cbm-gplassard** [comment]
Seems like the same issue, indeed! :+1:

**Pull request merged**
