### PR TITLE
feat(lambda): inline code for Python 3.8

### LINKED ISSUE #6503: Lambda: support inline code for Runtime.PYTHON_3_8
The CloudFormation documentation seems to imply that *all* node.js and Python runtimes support inline code. We should verify this and correctly enable the flags in those cases.

In particular, it appears PYTHON_3_8 should support inline code but this is prohibited by the current code.

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by christophgysin**
fixes #6503 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by nija-at — COMMENTED** [review]
Thanks for submitting this PR!

Can you run the following command and paste the output as a comment?

```
cdk deploy -a test/integ.runtime.inlinecode.js
```

**Comment by christophgysin** [comment]
@nija-at Sure. I usually just run:
```
$ y integ integ.runtime.inlinecode.js
yarn run v1.22.10
$ cdk-integ integ.runtime.inlinecode.js
Synthesizing integ.runtime.inlinecode.js.
Selected stack: aws-cdk-lambda-runtime-inlinecode
Deploying integ.runtime.inlinecode.js...
Deployment succeeded, updating snapshot.
Cleaning up.
Done in 54.63s.
```
But in case you need to full output:

```
$ cdk deploy -a test/integ.runtime.inlinecode.js
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬────────────────────────────────┬────────┬────────────────┬──────────────────────────────┬───────────┐
│   │ Resource                       │ Effect │ Action         │ Principal                    │ Condition │
├───┼────────────────────────────────┼────────┼────────────────┼──────────────────────────────┼───────────┤
│ + │ ${NODEJS_10_X/ServiceRole.Arn} │ Allow  │ sts:AssumeRole │ Service:lambda.amazonaws.com │           │
├───┼────────────────────────────────┼────────┼────────────────┼──────────────────────────────┼───────────┤
│ + │ ${NODEJS_12_X/ServiceRole.Arn} │ Allow  │ sts:AssumeRole │ Service:lambda.amazonaws.com │           │
├───┼────────────────────────────────┼────────┼────────────────┼──────────────────────────────┼───────────┤
│ + │ ${PYTHON_2_7/ServiceRole.Arn}  │ Allow  │ sts:AssumeRole │ Service:lambda.amazonaws.com │           │
├───┼────────────────────────────────┼────────┼────────────────┼──────────────────────────────┼───────────┤
│ + │ ${PYTHON_3_6/ServiceRole.Arn}  │ Allow  │ sts:AssumeRole │ Service:lambda.amazonaws.com │           │
├───┼────────────────────────────────┼────────┼────────────────┼──────────────────────────────┼───────────┤
│ + │ ${PYTHON_3_7/ServiceRole.Arn}  │ Allow  │ sts:AssumeRole │ Service:lambda.amazonaws.com │           │
├───┼────────────────────────────────┼────────┼────────────────┼──────────────────────────────┼───────────┤
│ + │ ${PYTHON_3_8/ServiceRole.Arn}  │ Allow  │ sts:AssumeRole │ Service:lambda.amazonaws.com │           │
└───┴────────────────────────────────┴────────┴────────────────┴──────────────────────────────┴───────────┘
IAM Policy Changes
┌───┬────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│   │ Resource                   │ Managed Policy ARN                                                             │
├───┼────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${NODEJS_10_X/ServiceRole} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
├───┼────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${NODEJS_12_X/ServiceRole} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
├───┼────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${PYTHON_2_7/ServiceRole}  │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
├───┼────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${PYTHON_3_6/ServiceRole}  │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
├───┼────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${PYTHON_3_7/ServiceRole}  │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
├───┼────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${PYTHON_3_8/ServiceRole}  │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
└───┴────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
aws-cdk-lambda-runtime-inlinecode: deploying...
aws-cdk-lambda-runtime-inlinecode: creating CloudFormation changeset...
[██████████████████████████████████████████████████████████] (14/14)










 ✅  aws-cdk-lambda-runtime-inlinecode

Outputs:
aws-cdk-lambda-runtime-inlinecode.NODEJS10XfunctionName = aws-cdk-lambda-runtime-inlinecod-NODEJS10XF3831960-14GQIIBXIKINR
aws-cdk-lambda-runtime-inlinecode.NODEJS12XfunctionName = aws-cdk-lambda-runtime-inlinecod-NODEJS12X8B8075A4-I84RMI2TIGSS
aws-cdk-lambda-runtime-inlinecode.PYTHON27functionName = aws-cdk-lambda-runtime-inlinecode-PYTHON27F8E941FA-1J3D8TQL3PZ2Y
aws-cdk-lambda-runtime-inlinecode.PYTHON36functionName = aws-cdk-lambda-runtime-inlinecode-PYTHON364935EF15-1SQ6ABF8NE108
aws-cdk-lambda-runtime-inlinecode.PYTHON37functionName = aws-cdk-lambda-runtime-inlinecode-PYTHON37D3A10E04-1EUEQHKH1EP4W
aws-cdk-lambda-runtime-inlinecode.PYTHON38functionName = aws-cdk-lambda-runtime-inlinecode-PYTHON38A180AE47-13DJCPBTHIYF3

Stack ARN:
arn:aws:cloudformation:*******:**********:stack/aws-cdk-lambda-runtime-inlinecode/7d2231a0-6564-11eb-97c6-0ae9a88ea315
```

**Review by nija-at — APPROVED** [review]
Nice!

**Comment by christophgysin** [comment]
@nija-at Is there something I can do to satisfy the PR linter? It expects a change to the README, but I don't think this change needs documentation?

**Pull request merged**
