### PR TITLE
chore(eks): support EKS service link role

### LINKED ISSUE #7634: Use only Service Linked Role for EKS clusters
## :question: General Issue

Amazon EKS now supports service link roles
https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-eks-supports-service-linked-roles/?nc1=h_ls

According to the [eks user guide](https://docs.aws.amazon.com/eks/latest/userguide/service_IAM_role.html)

> Prior to April 16, 2020, AmazonEKSServicePolicy was also required and the suggested name was eksServiceRole. With the AWSServiceRoleForAmazonEKS service-linked role, that policy is no longer required. 

`eksctl` just released `0.18.0` and removed the `AmazonEKSServicePolicy` from the cluster role.

https://github.com/weaveworks/eksctl/pull/2079

I was wondering if it's safe just remove this policy from the cluster role?

https://github.com/aws/aws-cdk/blob/1ee629e418fccec30b8a94e43682ed2c47ddd8da/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L371

### Environment

  - **CDK CLI Version:**  1.35.0
  - **Module Version:**  aws-eks
  - **OS:**  mac os x
  - **Language:**  all

### PR DESCRIPTION
**Pull request by pahud**
### Commit Message

core(eks): support EKS service link role

Prior to April 16, 2020, `AmazonEKSServicePolicy` was required for EKS cluster IAM role. With the new `AWSServiceRoleForAmazonEKS` service-linked role, that policy is no longer required.

This PR removes the `AmazonEKSServicePolicy` from the cluster role.

Closes #7634 

### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eladb** [comment]
@pahud this seems like it's mainly about removing `AmazonEKSServicePolicy`. Should we scope the PR down to this change first?

**Comment by eladb** [comment]
@pahud Can you include some details in the commit message about how this change resolves the issue?

**Comment by pahud** [comment]
> @pahud Can you include some details in the commit message about how this change resolves the issue?

OK. Done.

**Comment by stefanolczak** [comment]
After this change it's impossible to update EKS clusters ( from AWS console or CDK ) deployed before 16th of April because the update requires the AmazonEKSServicePolicy in cluster IAM role. AWS returns an error: 
```
Role with arn: arn:aws:iam::XXXXX:role/staging-eks-cluster-StagingEksClusterRole7CDF300A-1D3OQMFWTZVW8, could not be assumed because it does not exist or the trusted entity is not correct
```

To make it work the policy has to be added manually to the IAM role or the cluster has to be deployed from scratch. Unfortunately it causes a drift in cloudformation templates generated by CDK.

**Pull request merged**
