### PR TITLE
fix(apigateway): race condition exists between stage and cfnaccount in specrestapi

### LINKED ISSUE #18925: (aws-apigateway): race condition between Stage and CfnAccount on SpecRestApi
### What is the problem?

When cloudWatchRole is enabled, a CfnAccount is created for it. Since there is no explicit dependency between the the stages and the account, CloudFormation may deploy them in the wrong order, causing the deployment to fail.

Add an explicit dependency between Stages (whether defined by the user or created automatically) and the CloudWatch CfnAccount, if it exists.

This PR solved it for the RestApi https://github.com/aws/aws-cdk/pull/18011 but not entirely for the SpecRestApi.

Currently when we instantiate a SpecRestApi the class will first create the Deployment and the Stage

https://github.com/aws/aws-cdk/blob/5dd8e50bc2eb137183fcde4b37f3dd84f6763ae4/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L651-L660

then attach the Stage to the API

https://github.com/aws/aws-cdk/blob/5dd8e50bc2eb137183fcde4b37f3dd84f6763ae4/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L560-L565

The problem is that when calling the `_attachStage` the cloudwatchAccount does not exist yet, so it does not create the dependency between each other (as in RestApi)

 https://github.com/aws/aws-cdk/blob/5dd8e50bc2eb137183fcde4b37f3dd84f6763ae4/packages/%40aws-cdk/aws-apigateway/lib/stage.ts#L258-L263

If my understanding is correct, we would just need to swap the calls, first create the cloudwatchAccount then create the deployment and stage.

### Reproduction Steps

Create a SpecRestApi and deploy the stack all at once.

### What did you expect to happen?

Deployment to complete.

### What actually happened?

When creating a SpecRestApi the race condition still happens

### CDK CLI Version

1.142.0 (build 5dd8e50)

### Framework Version

1.142.0

### Node.js Version

17.3.0

### OS

macOS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by nwinans**
This PR is based off of #18011, which fixed a race condition between RestApi stages and CloudWatch roles. The mentioned PR fixed the issue for RestApi, but not SpecRestApi, which this PR aims to fix. 

The fix was largely implemented in RestApiBase. Since SpecRestApi inherits the same RestApiBase as RestApi, all we need to do is swap the order of resource creation so that the CloudWatch role is created before the RestApi stage, and can be attached correctly. 

This PR also updates the integration tests to reflect the new dependency RestApi stage has on RestApi account. 

Fixes #18925

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nwinans** [comment]
I think an exemption to the linter error should be granted for this package. The actual integration tests themselves don't need to be touched given the nature of the bug fix, but the relevant integration test snapshots have been updated to reflect the behavior of the API.

**Comment by TheRealAmazonKendra** [comment]
> I think an exemption to the linter error should be granted for this package. The actual integration tests themselves don't need to be touched given the nature of the bug fix, but the relevant integration test snapshots have been updated to reflect the behavior of the API.

That't reasonable. Providing the exemption.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Given the limited updates to the integ test  output, it doesn't look like the tests were actually run. Please revert the output of the integ tests and then run `yarn integ --update-on-failed` and commit the output.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
