### PR TITLE
chore: lint against constructing lambda handlers

### PR DESCRIPTION
**Pull request by MrArnoldPalmer**
Adds a custom lint rule that bans construction of constructs that create
lambda handlers. This is to be used within `aws-cdk-lib` to push authors
towards using our standard way of vending handlers using codegen tools
in @aws-cdk/handler-framework.

NOTE: depends on https://github.com/aws/aws-cdk/pull/28251

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by kaizencc — APPROVED** [review]
Approving since the dependency is merged. Looks like the build is failing though so gotta address that too

**Comment by MrArnoldPalmer** [comment]
working on a small bug here that needs to be addressed for relative imports within `aws-cdk-lib`.

**Comment by paulhcsun** [comment]
@MrArnoldPalmer it looks like https://github.com/aws/aws-cdk/pull/28251 has been merged. If you're still working on this could you have a look at the merge conflicts so that this PR can be merged?

**Review by paulhcsun — CHANGES_REQUESTED** [review]
@MrArnoldPalmer looks like a couple integ tests in `@aws-cdk/aws-s3objectlambda-alpha` violate the new linter rule. Could you have a look and update those files?

**Comment by paulhcsun** [comment]
Closing this PR for staleness, please open a new PR if you'd like to continue working on this.

**Pull request closed without merging**
