### PR TITLE
chore(scripts): pass higher memory limit in `buildup` and `builddown`

### LINKED ISSUE #24932: contributing: buildup failing on Gitpod
### Describe the bug

When launching a gitpod instance with aws-cdk, the buildup fails at the aws-cdk-lib package. 

### Expected Behavior

Successful buildup when starting up Gitpod.

### Current Behavior

Error with following JS stacktrace:

<--- Last few GCs --->

[1947:0x51be1d0]   219838 ms: Mark-sweep (reduce) 4035.7 (4105.8) -> 4034.8 (4106.1) MB, 2600.4 / 0.0 ms  (average mu = 0.081, current mu = 0.008) allocation failure scavenge might not succeed
[1947:0x51be1d0]   222069 ms: Mark-sweep (reduce) 4035.9 (4103.1) -> 4035.2 (4104.3) MB, 2024.8 / 0.0 ms  (average mu = 0.086, current mu = 0.092) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa3ad50 node::Abort() [/usr/bin/node]
 2: 0x970199 node::FatalError(char const*, char const*) [/usr/bin/node]
 3: 0xbba90e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xbbac87 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xd76ea5  [/usr/bin/node]
 6: 0xd77a2f  [/usr/bin/node]
 7: 0xd8586b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 8: 0xd8942c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
 9: 0xd57b0b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
10: 0x10a015f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
11: 0x1449379  [/usr/bin/node]
Aborted
Error: /workspace/aws-cdk/tools/@aws-cdk/cdk-build-tools/node_modules/jsii/bin/jsii --silence-warnings=reserved-word --add-deprecation-warnings --compress-assembly '--strip-deprecated /workspace/aws-cdk/deprecated_apis.txt' exited with error code 134
Build failed.!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error: last command failed. fix problem and resume by executing: /workspace/aws-cdk/scripts/foreach.sh
directory:    /workspace/aws-cdk/packages/aws-cdk-lib

### Reproduction Steps

Going to [Contributing](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and starting up a Gitpod instance leads to the issue.

### Possible Solution

The error is some sort of out of memory error, so could the issue be due to the limited amount of memory on the Gitpod instances, or perhaps something worse? I've tried using the 8 GB and 16 GB RAM instances with the same end results. Obviously the current builds are succeeding, so I am guessing it's something Gitpod specific in this case. 

### Additional Information/Context

_No response_

### CDK CLI Version

-

### Framework Version

_No response_

### Node.js Version

14.21.3

### OS

Ubuntu 22.04.2 LTS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by laurelmay**
This follows the pattern in #24425 which seems to especially happen
after #24376 when running these scripts.

Closes #24932

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hoegertn** [comment]
Shouldn't this be 8192?

Also this means that gitpod no longer works

**Comment by mrgrain** [comment]
> Shouldn't this be 8192?
> 
> Also this means that gitpod no longer works 

@hoegertn Do you know how increasing the memory limit "breaks" gitpod? Is there a safe number?

**Comment by hoegertn** [comment]
Breaking might not be the "right" word but a default GitPod env has 8GB of RAM (https://www.gitpod.io/docs/configure/workspaces/workspace-classes)

So maxing out on that limit might not be a good idea.

"No longer working was too hard" I remembered lower limits on GitPod, my fault.

**Comment by mrgrain** [comment]
> Breaking might not be the "right" word but a default GitPod env has 8GB of RAM (https://www.gitpod.io/docs/configure/workspaces/workspace-classes)
> 
> So maxing out on that limit might not be a good idea.
> 
> "No longer working was too hard" I remembered lower limits on GitPod, my fault.

Thanks for clarification! I meant to look at the gitpod setup this week and will try and see if there's a better value for it.

**Comment by mrgrain** [comment]
6GB aka 6144 seems to work as well.

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks good! Thanks!

**Comment by TheRealAmazonKendra** [comment]
I also just want to provide an FYI in case anyone is unaware and checking out this PR, if you don't need a stateful buildup or builddown, you can use `lerna exec --stream --include-dependencies --scope=<package-name> yarn build` for buildup or `lerna exec --stream --include-dependents --scope=<package-name> yarn build` for builddown. It's fast enough on my machine that I don't typically care about the loss of ability to restart the build from the failed package.

**Pull request merged**
