### PR TITLE
fix(autoscaling): EbsDeviceVolumeType.IO2 is not a valid CloudFormation value

### LINKED ISSUE #16027: (autoscaling): EbsDeviceVolumeType.IO2 is not a valid CloudFormation value
AWS::AutoScaling::LaunchConfiguration BlockDevice supports the following values for property VolumeType (see [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig-blockdev-template.html#cfn-as-launchconfig-blockdev-template-volumetype)):

> Valid Values: standard | io1 | gp2 | st1 | sc1 | gp3

In CDK, values IO2 is also defined as a possible value in [enum EbsDeviceVolumeType](https://github.com/aws/aws-cdk/blob/bb5d5874098b4b1047a29b6697e5e3a65f349ff0/packages/%40aws-cdk/aws-autoscaling/lib/volume.ts#L188).

However, this value is not valid at the moment and should be removed.

### Reproduction Steps

```ts
const vpc = ec2.Vpc.fromLookup(this, 'MyVPC', {
  isDefault: true,
})

new autoscaling.AutoScalingGroup(this, 'MyAutoScalingGroup', {
  blockDevices: [
    {
      deviceName: '/dev/sda1',
      volume: {
        ebsDevice: {
          deleteOnTermination: true,
          volumeType: autoscaling.EbsDeviceVolumeType.IO2,
        }
      },
    }
  ],
  vpc,
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.SMALL),
  machineImage: new ec2.AmazonLinuxImage(),
});
```

### What did you expect to happen?

Deployment of AutoScalingGroup should be successfully.

### What actually happened?

Deployment failed with error:

> io2 is invalid. Valid volume types are: standard, io1, gp2, st1, sc1, gp3 (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: e5dd0928-b959-4e36-beed-91b7b2ba1f6a; Proxy: null)

### Environment

  - **CDK CLI Version  : 1.118.0
  - **Framework Version: 1.118.0
  - **Node.js Version: v14.16.0
  - **OS               :  macOS
  - **Language (Version):  all

### Other

Originally mentioned in issue #14685. I will submit a short PR and remove value IO2 as proposed for GP3 in the original issue.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jumic**
Remove value IO2 from enum EbsDeviceVolumeType because it is not supported in CloudFormation.

Fixes #16027.

Please double-check before approving: Value from enum is removed which could potentially be a breaking change. However, it's an invalid value. Therefore, it should be correct to remove it.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jumic** [comment]
PR Linter failed with "Fixes must contain a change to a test file". Could we skip this for this issue? I think there is no test case that make sense here.

**Comment by peterwoodworth** [comment]
Thanks! But closing for reason mentioned in the issue

**Comment by peterwoodworth** [comment]
Looks like the build is failing.

@rix0rrr I'll leave this issue to you. tl;dr PR #12074 created the io2 option in [`ec2`'s](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.EbsDeviceVolumeType.html) and [`Autoscaling`'s](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.EbsDeviceVolumeType.html) enums `EbsDeviceVolumeType`, however this only should have been created in the `ec2` enum because [io2 isn't supported for autoscaling.](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig-blockdev-template.html#cfn-as-launchconfig-blockdev-template-volumetype)

**Comment by jumic** [comment]
I fixed the build by adding the change to the breaking changes file.
Do I also have to declare this PR as a breaking change? From a technical point of view, it is a breaking change, because the value will be removed. However, this value was never supported. Therefore, I'm not sure how it will be handled.

**Review by rix0rrr — APPROVED** [review]
You are right. Let's allow the breaking change for now, we can always roll back if it causes problems.

**Pull request merged**
