### PR TITLE
feat(codepipeline): final form of the CodeBuild Pipeline action

### PR DESCRIPTION
**Pull request by skinny85**
BREAKING CHANGE: the output and extraOutputs properties of the CodeBuildAction were merged into one property outputs.

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by eladb** [comment]
I am failing to understand why we continuously make this API less ergonomic. This change goes against our design tenet to optimize for the common case. I’d argue that 99% of pipeline actions would have a single output. Can you please provide the motivation for this change?

**Comment by rix0rrr** [comment]
When given the choice between:

```ts
interface {
  things: string[];
}
```

And:

```ts
interface {
  thing: string;

  moreThings?: string[];
}
```

I would also prefer the first one. Why would you purpose introduce that kind of shape irregularity? 

For one thing, it assumes it will always be a human supplying the input values, not any kind of higher-level code. I made the same mistake with CompositePrincipal, and immediately a user complained because they had to jump through hoops to add a higher-level abstraction over it: https://github.com/awslabs/aws-cdk/issues/2327

Given that the cost is having to type an additional `[ ]`, I don't think it's too bad.

**Comment by eladb** [comment]
it’s all about API ergonomics. If in 99% of the cases actions will have a single output, having to pass in an array is less comfortable. In some languages (ahm java) it’s even annoying. We should constantly think about the common case and optimize for it. 

If this was the only case, then okay, but I feel we have been continuously making our pipelines API less ergonomic (artifacts, etc) and I wanted to call out that this is not the right direction.

The CDK is all about the developer experience. More verbosity and ceremony creates friction and redundant boilerplate for customers, and we should avoid them as much as possible. 

I am curious what is the motivation behind this change.

**Comment by skinny85** [comment]
Rebased to solve conflicts.

**Pull request merged**
