### PR TITLE
feat(core): CfnResource dependency methods

### PR DESCRIPTION
**Pull request by jusdino**
Reopening #20419 from a personal fork to allow maintainer edits. @comcalvi :wave: 

Add some new methods to allow a minimal interface for viewing and editing resource-to-resource dependencies that mirrors the behavior of CfnResource.addDependsOn().

Related to #20418 - details for justification are there

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jusdino** [comment]
There seems to be some sort of consistency issue in the GitHub checks for *PR Linter* but hopefully it'll sort itself out when you push your commit.

**Comment by comcalvi** [comment]
getting an access denied from the new fork @jusdino...are maintainer edits enabled?

**Comment by jusdino** [comment]
Weird:
image

I have the box checked :confused:

**Comment by jusdino** [comment]
I just invited you directly as a collaborator on my fork, in case that helps.

**Comment by comcalvi** [comment]
Yep, that works. Thanks for all your hard work on this PR!

**Review by comcalvi — APPROVED** [review]

**Pull request merged**
