### PR TITLE
feat(ec2): add r6i instances

### PR DESCRIPTION
**Pull request by robertd**
New R6I instances just got released:

https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-ec2-r6i-instances/

Docs have already been updated:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instancetype

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
Hi @neilkuan @dwchiang @ChenKuanSun are you interested to take a look as an initial review? Please leave a review comment with "LGTM" if you think it's good with you.

Thanks.

**Review by neilkuan — COMMENTED** [review]
LGTM

**Comment by ChenKuanSun** [comment]
LGTM

**Review by clarencetw — COMMENTED** [review]
LGTM

**Review by ChenKuanSun — COMMENTED** [review]
LGTM

added instances check https://github.com/aws/aws-cdk/pull/17675

**Comment by pahud** [comment]
Hi @njlynch we have 3 community approving reviews. Can you take a look?

**Comment by neilkuan** [comment]
Hi @robertd, Can you also add testing in `packages/@aws-cdk/aws-ec2/test/instance.test.ts` at this PR?!

**Comment by pahud** [comment]
@njlynch wdyt?

**Review by njlynch — APPROVED** [review]

**Pull request merged**
