### PR TITLE
fix(aws-iam): generate warning when using addManagedPolicy on an imported Role

### PR DESCRIPTION
**Pull request by gshpychka**
Related issue:
https://github.com/aws/aws-cdk/issues/8307

### CODE REVIEW

**Comment by gshpychka** [comment]
Please advise the proper way to test warning generation.

**Comment by gshpychka** [comment]
@rix0rrr Not sure how to proceed - please advise

**Comment by gshpychka** [comment]
@nija-at  what do I have to do to have this merged?

**Comment by TheRealAmazonKendra** [comment]
@gshpychka Thank you for making this change. A test for this would be something along the lines of:
```
Annotations.fromStack(stack).hasWarning('/Path/To/Node', 'warning message');
```

**Comment by Lanayx** [comment]
For some reason this warning is not properly displayed in console I only see the following

`[Warning at /CdktestStack/myRoleId] [object Object]`

**Pull request closed without merging**
