### PR TITLE
feat(opensearchservice): When a Domain has enforceHttps true, set the connections defaultPort

### LINKED ISSUE #16251: (aws_cdk.aws_elasticsearch): Set connections defaultPort when enforceHttps is true
When a VPC is used with an elasticsearch Domain, the resulting connections object does not have a default port. However, when enforceHttps is set, we know communications will be over port 443.

### Use Case

So I don't have to manually specify a port when setting up VPC connections to the Domain.

### Proposed Solution

Include a defaultPort when constructing the connections object if enforceHttps is true.

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by SamStephens**
For an Opensearch domain, if enforceHttps is enabled, set the defaultPort for the connections object of the domain, as we know it communicates over 443 in this scenario.

I also took the liberty of correcting a test title while I was in the code, I hope it's okay coupling that fix with this change.

closes #16251

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

It doesn't seem that an integration test is a good fit here, as this simply changes/simplifies how you'll create a connection to a Domain. I'm happy to be corrected however and will add one if asked.

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by corymhall — COMMENTED** [review]
@SamStephens does it make  sense to also set the default port if `enforceHttps` is not set? I can't find much information on ports with opensearch except for [this](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-resources.html) which mentions only 80 & 443.

thoughts?

**Comment by SamStephens** [comment]
> @SamStephens does it make sense to also set the default port if `enforceHttps` is not set? I can't find much information on ports with opensearch except for [this](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-resources.html) which mentions only 80 & 443.
> 
> thoughts?

Sorry, I should have explained my rational here. My take is that if `enforceHttps` is `false`, the cluster listens on ports 80 and 443, so it doesn't make sense to have a singular default port.

Also, PR linting is failing because I've not made a change to a README file. I'm not sure what to do about this, as this is such a minor feature I'm not sure it belongs in the [Opensearch Service README](https://github.com/aws/aws-cdk/blob/4537b3fc1b726dd8cbaadd0c52c35b6f31328e3d/packages/%40aws-cdk/aws-opensearchservice/lib/domain.ts), which doesn't even describe the enforceHttps option, let alone this minor consequence of it.

**Review by corymhall — APPROVED** [review]
> Sorry, I should have explained my rational here. My take is that if enforceHttps is false, the cluster listens on ports 80 and 443, so it doesn't make sense to have a singular default port.

gotcha, that makes sense.

**Comment by SamStephens** [comment]
Thanks @corymhall !

**Pull request merged**
