### PR TITLE
chore: remove packaging prerequisites requirements from build

### PR DESCRIPTION
**Pull request by NetaNir**
Split the prerequisites check for `pack` and `build`. Executing `build` does not execute pack, which means it does not require the tools for packaging (`mvn`, `python`, `.Net`, `java`) to be installed locally.

This PR splits `check-prerequisites` into two separate scripts, `check-build-prerequisites` and `check-pack-prerequisites`. 

For build check:
* `node`
* `yarn`
* `docker` (arguable, but fine)

For pack check:
* all build prerequisites
* `mvn`
* `java`
* `.Net`
* `python`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by RomainMuller — APPROVED** [review]

**Review by nija-at — CHANGES_REQUESTED** [review]
How about instead changing `check-prerequisites` to take a parameter instead, say 'stage'?
This can be set to 'build' or 'pack'.

This way if a pre-requisite is needed for multiple stages, we can avoid duplicating this across multiple scripts. And keep the min versions consistent.

A script called `check-prerequisites.sh` that does nothing but simply has bash functions doesn't make much sense.

**Comment by NetaNir** [comment]
@nija we can definitely make it better, honestly I just wanted to remove all of the heavy tools from the build requirements, as I think this is a huge blocker for contributing to the cdk. 

I will come back to this soon.

**Comment by rix0rrr** [comment]
I agree that it could maybe be factored some more, there's a lot of repetition now.

Don't mind 2 entry-level scripts that use functions from another script. I kind of like the straightforwardness of everything.

This is better than what we had, so why not move forward an inch (instead of a mile?)

**Review by nija-at — COMMENTED** [review]
> The check-prerequisites.sh is a util file, I agree it can be named better. Let me know if changing the name of the `check-prerequisites.sh` file to `check-prerequisites-util.sh` is sufficient and I will make the change.

I would just get rid of the `check-prerequisites.sh` file and duplicate the 6ish lines of code in both files. It's not that much to keep in a common bash file.

However, if you want to keep it as a separate file, I would call it `prerequisites.bash` where `.bash` suffix indicates that it's not a script. Also, make sure to remove the 'x' flag so that it's no longer an executable.

**Comment by NetaNir** [comment]
@nija-at removed the util file.

**Review by nija-at — APPROVED** [review]

**Pull request merged**
