### PR TITLE
feat(ec2): add m6i instances

### PR DESCRIPTION
**Pull request by robertd**
https://aws.amazon.com/about-aws/whats-new/2021/08/amazon-ec2-m6i-instances/

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by peterwoodworth** [comment]
Hey @robertd,

Do you know if these changes automatically implemented in CloudFormation? Or, have you successfully deployed a stack with an m6i instance? Thanks

**Comment by robertd** [comment]
@peterwoodworth Yeah... `m6i` instances are being generated properly. I guess docs `CloudFormation` docs haven't been updated yet (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instancetype). I guess I can track down the repo and submit PR there too.

image

```bash
ssm-user@ip-[redacted]:/var/snap/amazon-ssm-agent/4662$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
Stepping:                        6
CPU MHz:                         3503.124
BogoMIPS:                        5799.97
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       48 KiB
L1i cache:                       32 KiB
L2 cache:                        1.3 MiB
L3 cache:                        54 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fx
                                 sr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology no
                                 nstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse
                                 4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_l
                                 m abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adj
                                 ust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflu
                                 shopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd i
                                 da arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bita
                                 lg avx512_vpopcntdq rdpid md_clear flush_l1d arch_capabilities
```

**Comment by robertd** [comment]
@peterwoodworth Do you think we can squeeze this in the `1.120.0` release?

**Review by peterwoodworth — COMMENTED** [review]
Why is the @ stability tag necessary here?

**Comment by peterwoodworth** [comment]
Looks good to me otherwise, I'll leave to @njlynch for final review

**Comment by robertd** [comment]
> Why is the @ stability tag necessary here?

@peterwoodworth  I have no idea how that got there 😄 .... removed.

**Review by njlynch — APPROVED** [review]

**Comment by robertd** [comment]
Whoops... You'll have to re-approve it again @njlynch. Sorry about that 😄 ... I thought I was merging-in updates from my other pending PRs. My bad 😅

**Review by njlynch — APPROVED** [review]

**Pull request merged**
