### PR TITLE
feat(applicationautoscaling): Add KAFKA to ServiceNamespace

### PR DESCRIPTION
**Pull request by bracki**
Add `KAFKA` to ServiceNamespace. This allows targeting MSK's autoscaling feature.

Fixes https://github.com/aws/aws-cdk/issues/11366

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by NetaNir — DISMISSED** [review]

**Comment by iwt-janbrauer** [comment]
Apparently I have to add something to a README, which doesn't make sense in this case. 
Can you take a look @NetaNir? I fixed the other issues.

**Comment by NetaNir** [comment]
@Mergifyio refresh

**Comment by NetaNir** [comment]
@Mergifyio refresh

**Comment by NetaNir** [comment]
@Mergifyio update

**Review by NetaNir — APPROVED** [review]

**Comment by NetaNir** [comment]
@Mergifyio refresh

**Comment by NetaNir** [comment]
@Mergifyio update

**Pull request merged**
