### PR TITLE
feat(cfnspec): cloudformation spec v51.0.0

### PR DESCRIPTION
**Pull request by robertd**
Closes #17943.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
Just checking to see why is #17943 failing to build properly. I cannot replicate this on my Mac.

**Comment by robertd** [comment]
I do see that docs are completely missing `Type` property... 
image

**Comment by robertd** [comment]
Actually... examples are missing too... 
image

**Comment by robertd** [comment]
Hmm... AWS Lex docs are nowhere to be found in https://github.com/awsdocs/aws-cloudformation-user-guide/ repo, but they are present on the AWS User Guide page: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Lex.html

**Comment by skinny85** [comment]
Thanks for your work on this @robertd! Two things:

1. Let's just remove the incorrect Property types, instead of guessing they are a string.
2. Can you check whether you can now remove the patches introduced in the previous PR (https://github.com/aws/aws-cdk/pull/17844)?

Thanks,
Adam

**Comment by robertd** [comment]
> 1. Let's just remove the incorrect Property types, instead of guessing they are a string.

Removing the `Type` property altogether from `AWS::Lex::BotAlias.TextLogDestination` throws an error.

image


> 2. Can you check whether you can now remove the patches introduced in the previous PR ([feat(cfnspec): cloudformation spec v50.0.0 #17844](https://github.com/aws/aws-cdk/pull/17844))?

Removed `AWS::Evidently` patches introduced in #17844. Build and test passed on my machine. Pushed fd37bf899102.

**Comment by skinny85** [comment]
> > 1. Let's just remove the incorrect Property types, instead of guessing they are a string.
> 
> Removing the `Type` property from `AWS::Lex::BotAlias.TextLogDestination.Properties.CloudWatch` still throws an error. It looks like `Type` (or `PrimitiveType`) is a required param. Should I instead remove `AWS::Lex::BotAlias.TextLogDestination` section altogether?
> 
> image


Sure, that should work.

**Comment by robertd** [comment]
@skinny85 Done. Build is passing now. 👍 
 
1) Should we make a note (GH Issue) to revisit this in the future cfnspec bumps?
2) I see bunch of other patches that are probably not needed anymore. Should we clean these up at some point?
3) Can you point me to the "official cfnspec patching how-to documentation" (if it exists). I'd like to learn more about the it :).

**Review by rix0rrr — APPROVED** [review]

**Comment by dontirun** [comment]
It looks like like v60.0.0 of the spec supports this property properly

image

**Pull request merged**
