### PR TITLE
feat(ecs): add a service extension interface to ECS services

### LINKED ISSUE #13234: (ecs): add a service extension interface to ECS services
I'd like ECS services to have an extension interface similar to `TaskDefinition.addExtension` and `ITaskDefinitionExtension`.

### Use Case

I want to create packaged sets of modifications for ECS services. For instance, I may have a standard set of service discovery options or scaling policies that I want to apply to a service. I would like the option to create these packaged modifications in a way that works on either or both of Fargate and EC2 services.

### Proposed Solution
Add an `IServiceExtension` interface and an `addExtension` method to `BaseService`. Users could then implement an `IServiceExtension` and provide it as a parameter to the service's `addExtension` method.

```ts
class MyStandardScaling implements ecs.IFargateServiceExtension, ecs.IEc2ServiceExtension {
  extend(service: ecs.FargateService | ecs.Ec2Service): void {
    service.autoScaleTaskCount({
      maxCapacity: 100,
      minCapacity: 2,
    }).scaleOnCpuUtilization('Target40', {
      targetUtilizationPercent: 40,
    });
  }
}

service.addExtension(new MyStandardScaling());
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by misterjoshua**
Adds an `addExtension()` method to each of `FargateService` and `Ec2Service` that allows the user to create and apply packaged sets of modifications to the services.

Closes #13234

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by misterjoshua** [comment]
@nathanpeck Hey. I was wondering what you thought of applying some of your L3 service extension ideas to the L2 ECS constructs. I really like the approach and I think we can generalize it enough to make it work at L2. I took a crack at such an interface in this PR.

After #13240, we'll be able to create an L3 tool to add the default container after a service is created via an extension (like how we add containers to your module's service description)

After #13230 is in, I imagine that we could conceivably reduce AppMesh support to a Fargate service extension.

Thanks

**Comment by nathanpeck** [comment]
We considered something similar to this as an alternate to building a higher level extensions pattern. However there are a some significant downsides to this. The main issue is that the level two constructs underneath are intended to have minimal mutability. (See my other comment here: https://github.com/aws/aws-cdk/pull/13230#issuecomment-786809334) So in order to make this work we'd have to make changes to the L2 constructs which will end up introducing a lot of unintended side effects due to the existing expectations of immutability.

The other challenge that I ran into is that extensions often need a way to be aware of each other so that they can make better decisions about their own configuration. For example with App Mesh in specific, when you add App Mesh to a task it needs to change how the task container `dependsOn` startup order works. You need to build a container dependency tree to ensure that containers start in the right order, otherwise some containers may attempt to start before the Envoy Proxy is up and running, creating a race condition failure.

I think there is definitely room for a simpler extension interface that solves simple use cases like the example you have of packaging up an autoscaling config and reusing it. I think we will see problems with some of the deeper things like App Mesh though.

**Comment by misterjoshua** [comment]
> We considered something similar to this as an alternate to building a higher level extensions pattern. However there are a some significant downsides to this. The main issue is that the level two constructs underneath are intended to have minimal mutability. (See my other comment here: [#13230 (comment)](https://github.com/aws/aws-cdk/pull/13230#issuecomment-786809334)) So in order to make this work we'd have to make changes to the L2 constructs which will end up introducing a lot of unintended side effects due to the existing expectations of immutability.
> 
> The other challenge that I ran into is that extensions often need a way to be aware of each other so that they can make better decisions about their own configuration. For example with App Mesh in specific, when you add App Mesh to a task it needs to change how the task container `dependsOn` startup order works. You need to build a container dependency tree to ensure that containers start in the right order, otherwise some containers may attempt to start before the Envoy Proxy is up and running, creating a race condition failure.

> I think there is definitely room for a simpler extension interface that solves simple use cases like the example you have of packaging up an autoscaling config and reusing it. I think we will see problems with some of the deeper things like App Mesh though.

Sounds reasonable on the assumption of non-mutability.

> I think there is definitely room for a simpler extension interface that solves simple use cases like the example you have of packaging up an autoscaling config and reusing it.

In terms of a simpler extension interface, what do you have in mind? I don't mind making adjustments or going back to the drawing board so as to at least create the reusable configuration part - that's the part I truly care about. For instance, what about generalizing the extension interface to `IService`, rather than splitting between `IFargateServiceExtension` and `IEc2ServiceExtension`?

**Comment by nathanpeck** [comment]
So after discussing it with the team we are going to close this PR because it would add more logic to the L2 construct, while our design goal is to implement higher level logic at L3 instead. One of our goals is to keep the L2 constructs from getting too bloated, so they don't get unwieldily, and implement this type of extension behavior as an L3 construct, in the aws-containers/ecs-service-extensions namespace instead.

**Pull request closed without merging**
