### PR TITLE
feat(ec2): instance support passing IAM instance profile

### LINKED ISSUE #8348: Allow passing an IAM Instance Profile to ec2.Instance
Currently ec2.Instance is creating the IamProfile internally, it isn't possible to inject a pre-constructed one. It is possible to inject the a role, but when re-using the same role for several instances, a separate instance profile is being created for each of them.

https://github.com/aws/aws-cdk/blob/bd616d4732d8602c0938f02f27638eefd5ec2b0e/packages/%40aws-cdk/aws-ec2/lib/instance.ts#L277

### PR DESCRIPTION
**Pull request by phuhung273**
### Issue # (if applicable)

Closes #8348 

### Reason for this change

- Use only 1 IAM instance profile for multiple instances
- Passing role create too many instance profile

### Description of changes

- `ec2.Instance` support `instanceProfile` param

### Description of how you validated changes

- unit test
- integ test

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by GavinZZ — APPROVED** [review]
Thank you! I can't believe we don't support instance profile until now.

**Comment by GavinZZ** [comment]
@mergify update

**Review by GavinZZ — DISMISSED** [review]

**Review by GavinZZ — DISMISSED** [review]

**Comment by phuhung273** [comment]
@GavinZZ thanks for your review. I dont know why CodeQL stuck at this snippet now
```js
part = `"${part.replace(/"/g, '\\"')}"`;
```
Can confirm this line exists in other generated integ test snapshot.

**Comment by phuhung273** [comment]
Found 2 related PRs/issues
- https://github.com/aws/aws-cdk/pull/31658
- https://github.com/aws/aws-sdk-js-v3/issues/6623

**Review by GavinZZ — APPROVED** [review]

**Comment by GavinZZ** [comment]
I'll reach out internally to see what the CodeCov issue is.

**Comment by GavinZZ** [comment]
I'll reach out internally to see what the CodeCov issue is.

**Comment by GavinZZ** [comment]
@phuhung273 I synced with my team and there's some issue with a flaky test in the Code coverage test suite. We're working on a fix, please wait patiently and will update you soon.

**Comment by phuhung273** [comment]
Thanks so much @GavinZZ, please take your time

**Review by GavinZZ — APPROVED** [review]

**Pull request merged**
