### PR TITLE
fix(ec2): can't add non-default routes to subnets

### LINKED ISSUE #5321: [vpc] Add route fails when specifying destinationCidrBlock
Adding a route via `Subnet.addRoute` fails when `destinationCidrBlock` is specified.

The [code](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ec2/lib/vpc.ts#L1399) uses `options.destinationCidrBlock` for the `destinationIpv6CidrBlock` property which results in both properties in the CFN template.

### Reproduction Steps

```
const vpcA = new ec2.Vpc(this, 'VPCA');
const vpcB = new ec2.Vpc(this, 'VPCB');

const vpcPeering = new ec2.CfnVPCPeeringConnection(this, 'VPCAPeer', {
  vpcId: vpcA.vpcId,
  peerVpcId: vpcB.vpcId
});

vpcA.privateSubnets.forEach(pSubnet => {
  (pSubnet as ec2.Subnet).addRoute(`${pSubnet.node.id}PeerRoute`, {
    destinationCidrBlock: processingVpc.vpcCidrBlock,
    routerType: ec2.RouterType.VPC_PEERING_CONNECTION,
    routerId: vpcPeering.ref,
  })
});
```

### Error Log

`CREATE_FAILED Exactly one of DestinationCidrBlock and DestinationIpv6CidrBlock must be specified and not empty`

The generated CFN template contains both properties.

```
...snip
  "VPCAPeerRoute": {
    "Type": "AWS::EC2::Route",
    "Properties": {
      "DestinationCidrBlock": {
        "Fn::GetAtt": [
          "VPCAB98067BE",
          "CidrBlock"
        ]
      },
      "DestinationIpv6CidrBlock": {
        "Fn::GetAtt": [
          "VPCAB98067BE",
          "CidrBlock"
        ]
      }
    }
  }
...snip
```

### Environment

  - **CLI Version      :1.18.0**
  - **Framework Version: 1.18.0**
  - **OS               :macOS**
  - **Language         :TypeScript**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ialford**
Update the `destinationCidrBlockIPV6` to use the proper options and not duplicate `destinationCidrBlock`

fixes #5321 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
Hi Ian,

Could you add a test? This might help you:

https://docs.aws.amazon.com/cdk/latest/guide/testing.html

You can also have a peek at the other tests in the same package to get inspiration.

**Comment by ialford** [comment]
> Hi Ian,
> 
> Could you add a test? This might help you:
> 
> https://docs.aws.amazon.com/cdk/latest/guide/testing.html
> 
> You can also have a peek at the other tests in the same package to get inspiration.

Hi @rix0rrr - I was thinking of adding the unit test for this into the VPC unit tests, does that make sense to you as the right place?

**Comment by ialford** [comment]
@rix0rrr - I've added a test to validate the removal of the `DestinationIPv6CidrBlock` which is what the bug was identifying. Please let me know if you need anything else.

**Comment by rix0rrr** [comment]
Hi @ialford,

`{}` represents an object with no properties, but you seem to be using it as a kind of "wildcard" property, which it does not actually represent. The test is currently testing that a resource with invalid properties is NOT created. It succeeds, but not because of the code you changed.

You can check whether a test is a good test by running it WITHOUT your proposed code change (in which case it should fail) and again WITH your proposed code change (in which case it should succeed). By doing that, you know the test is actually testing the code change and not just passing by accident.

I would propose changing it to the following:

```ts
    'Can add an IPv6 route'(test: Test) {
      // GIVEN
      const stack = getTestStack();

      // WHEN
      const vpc = new Vpc(stack, 'VPC');
      (vpc.publicSubnets[0] as PublicSubnet).addRoute('SomeRoute', {
        destinationIpv6CidrBlock: '2001:4860:4860::8888/32',
        routerId: 'router-1',
        routerType: RouterType.NETWORK_INTERFACE
      });

      // THEN

      expect(stack).to(haveResourceLike("AWS::EC2::Route", {
        DestinationIpv6CidrBlock: '2001:4860:4860::8888/32',
        NetworkInterfaceId: 'router-1'
      }));

      test.done();
    },
```

**Comment by ialford** [comment]
> Hi @ialford,
> 
> `{}` represents an object with no properties, but you seem to be using it as a kind of "wildcard" property, which it does not actually represent. The test is currently testing that a resource with invalid properties is NOT created. It succeeds, but not because of the code you changed.
> 
> You can check whether a test is a good test by running it WITHOUT your proposed code change (in which case it should fail) and again WITH your proposed code change (in which case it should succeed). By doing that, you know the test is actually testing the code change and not just passing by accident.
> 
> I would propose changing it to the following:
> 
> ```ts
>     'Can add an IPv6 route'(test: Test) {
>       // GIVEN
>       const stack = getTestStack();
> 
>       // WHEN
>       const vpc = new Vpc(stack, 'VPC');
>       (vpc.publicSubnets[0] as PublicSubnet).addRoute('SomeRoute', {
>         destinationIpv6CidrBlock: '2001:4860:4860::8888/32',
>         routerId: 'router-1',
>         routerType: RouterType.NETWORK_INTERFACE
>       });
> 
>       // THEN
> 
>       expect(stack).to(haveResourceLike("AWS::EC2::Route", {
>         DestinationIpv6CidrBlock: '2001:4860:4860::8888/32',
>         NetworkInterfaceId: 'router-1'
>       }));
> 
>       test.done();
>     },
> ```

Hi @rix0rrr - I added the test that you suggested as well as created a test for explicitly adding an IPv4 Route. I also moved them to run under the VPC suite of tests, since that is where the rest of the subnet-related tests run.

I removed the test I originally submitted as well - I believe that the error handling [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1393) handles the logic that I was testing originally.

**Pull request merged**
