### PR TITLE
feat(elasticloadbalancingv2-targets): update AlbTarget constructor to accept interface IApplicationLo…

### PR DESCRIPTION
**Pull request by SarthakPaneru**
…adBalancer (#27466)

> I changed the constructor as discussed in the issue
>
> Describe the reason for this change, what the solution is, and any
> important design decisions you made. 
>
> Remember to follow the [CONTRIBUTING GUIDE] and [DESIGN GUIDELINES] for any
> code you submit.
>
> [CONTRIBUTING GUIDE]: https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md
> [DESIGN GUIDELINES]: https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md

Closes#27466.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by SarthakPaneru** [comment]
Exemption Request

**Comment by vinayak-kukreja** [comment]
> Exemption Request

Hey could you tell me why this needs to be exempted?

**Comment by vinayak-kukreja** [comment]
I do not believe this needs to be a `feat`. Could you align the title as per [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

**Comment by vinayak-kukreja** [comment]
Could you also update the PR body formatting? It looks like it has part of the title and is not descriptive :)

**Comment by vinayak-kukreja** [comment]
We will also not able to accept a PR from `main` branch on your fork. Could you follow steps [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request) and make this contribution from another branch on your fork?

**Comment by SarthakPaneru** [comment]
I have created new PR #27516 @vinayak-kukreja, will you look into it?

**Pull request closed without merging**
