### PR TITLE
fix(s3-deployment): lambda "src" not included in published module

### LINKED ISSUE #4404: In v1.12.0 aws-s3-deployment references non-distributed file
[This change released in v1.12.0](https://github.com/aws/aws-cdk/commit/5225306c4a83d78593c1c0a04367c845b6817be4#diff-85982f660b9fcd1e9212d53d05253681) references `./lambda/src`, however that directory is excluded from being included in the package distribution [in the .gitignore file here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3-deployment/.npmignore#L16).

### Reproduction Steps

Create an s3 deployment with CDK as normal. The console should log something like:

### Error Log

```
Error: ENOENT: no such file or directory, scandir '/home/vsts/work/1/dist/cdk/node_modules/@aws-cdk/aws-s3-deployment/lambda/src'
    at Object.readdirSync (fs.js:790:3)
    at calcSourceHash (/home/vsts/work/1/dist/cdk/node_modules/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts:151:25)
    at new BucketDeployment (/home/vsts/work/1/dist/cdk/node_modules/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts:83:24)
    at new WebosAppCdkStack (/home/vsts/work/1/cdk/lib/webos-app-cdk-stack.ts:111:5)
    at Object.<anonymous> (/home/vsts/work/1/cdk/bin/webos-app-cdk.ts:57:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :** 1.12.0
  - **Framework Version:** 1.12.0
  - **OS               :** Ubuntu Linux
  - **Language         :** TypeScript

### Other

Either include the source code directory or implement the hash check differently.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
As of v1.12.0, we customized the calculation of the custom resource hash
to use the contents of the "src" directory instead of the bundle.zip itself
in order to keep it deterministic (the bundle is created during build by
pulling in external dependencies and includes compiled python files which
caused it have a different hash in each build).

However, the "lambda/src" directory was explicitly excluded from the
module's tarball (in .npmignore), so when this module was used in production,
it could not find "lambda/src" in order to calculate the hash.

This fixes #4404 by removing `lambda/src` from `.npmignore`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nija-at** [comment]
What tests are we missing that would have caught this?

**Comment by eladb** [comment]
> What tests are we missing that would have caught this?

https://github.com/aws/aws-cdk/issues/4448

**Comment by areejcluntun** [comment]
After updating, cdk still seem to be looking for `'node_modules/@aws-cdk/aws-s3-deployment/lambda/src'` when deploying and not finding it. The folder `'@aws-cdk/aws-s3-deployment/lambda'` seem to contain a `bundle.zip` and updating npm still doesn't solve the problem. am I missing something? 

`ENOENT: no such file or directory, scandir '/cdk/node_modules/@aws-cdk/aws-s3-deployment/lambda/src'`

**Comment by eladb** [comment]
@areejcluntun I have verified that this is fixed in v1.13.1 - can you please nuke your `node_modules` directory and reinstall all modules to make sure you get the latest version?

**Comment by areejcluntun** [comment]
Yes, I have updated to the latest version yesterday and it works! Thank you so much!

**Comment by chardydev** [comment]
> As of v1.12.0, we customized the calculation of the custom resource hash
to use the contents of the "src" directory instead of the bundle.zip itself
in order to keep it deterministic

Related to the above change (I think)-- as of 1.12.0 I'm now seeing a different hash for the same set of files when they're in a different directory.  Is that by design? It's causing problems for us with some tests running in CI.

**Comment by eladb** [comment]
Can you please raise a separate issue with a repro?

**Pull request merged**
