### PR TITLE
fix(appsync): rds data source configured with cluster arn

### PR DESCRIPTION
**Pull request by BryanPan342**
Lazily add a formatted cluster arn to the RdsHttpEndpointConfig. Before we were just adding the cluster id, but the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-datasource-rdshttpendpointconfig.html) call for the Cluster Arn instead. 

Fixes: #11536

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by BryanPan342** [comment]
@MrArnoldPalmer Not sure what the issue is with the check, but if you can point me in the right direction I can fix it

**Comment by MrArnoldPalmer** [comment]
@Mergifyio update

**Comment by MrArnoldPalmer** [comment]
@BryanPan342 we had an issue with codebuild log comments not being published. I refreshed to trigger a rebuild as this should be fixed.

**Review by MrArnoldPalmer — APPROVED** [review]
👍🏻 TY @BryanPan342 !!

**Pull request merged**
