### PR TITLE
chore(events): add sqsparameters for event targets (#3735)

### LINKED ISSUE #3735: Not able to use FIFO SQS queues as target for CloudWatch events construct
### What is the problem?
When using FIFO SQS queues as a target in CloudWatch events, the field messageGroupId is required. Even though messageGroupId is mentioned when creating an SQS queue target, this field is not present in the generated CloudFormation template

### Reproduction Steps
    import cdk = require('@aws-cdk/core');
    import events = require('@aws-cdk/aws-events');
    import sqs = require('@aws-cdk/aws-sqs');
    import targets = require('@aws-cdk/aws-events-targets');

    export class SampleCloudWatchStack extends cdk.Stack {
      constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        // The code that defines your stack goes here
        const deadQueue: sqs.DeadLetterQueue = {
          maxReceiveCount: 20,
          queue: new sqs.Queue(this, 'MyDeadQueue', {
            contentBasedDeduplication: false,
            fifo: true,
            queueName: 'MyDeadQueue.fifo'
          })
        };

        const queue: sqs.Queue = new sqs.Queue(this, 'MyQueue', {
          contentBasedDeduplication: true,
          deadLetterQueue: deadQueue,
          fifo: true,
          queueName: 'MyQueue.fifo'
        });

        const target0: targets.SqsQueue = new targets.SqsQueue(queue, {
          message: events.RuleTargetInput.fromObject({
            id: events.EventField.eventId
          }),
          messageGroupId: 'my_queue'
        });

        const rule: events.Rule = new events.Rule(this, 'MyRule', {
          description: 'This is just a sample rule',
          enabled: true,
          ruleName: 'MyRule',
          schedule: events.Schedule.expression('cron(30 9 ? * MON-FRI *)'),
          targets: [target0]
        });
      }
    }

### Verbose Log
    SampleCloudWatchStack: deploying...
    SampleCloudWatchStack: creating CloudFormation changeset...
     0/3 | 7:16:16 PM | UPDATE_IN_PROGRESS   | AWS::Events::Rule     | MyRule (MyRuleA44AB831) 
     1/3 | 7:16:46 PM | UPDATE_FAILED        | AWS::Events::Rule     | MyRule (MyRuleA44AB831)
    Parameter(s) SqsParameters must be specified for target: Target0. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException)
            new Rule (/Users/gpratyush/Personal/AWS/sample-cloud-watch/node_modules/@aws-cdk/aws-events/lib/rule.ts:101:22)

### Environment

  - **CDK CLI Version:** 1.4
  - **Module Version:** 1.4
  - **OS:** OS X
  - **Language:** TypeScript

### PR DESCRIPTION
**Pull request by pratyush05**
add sqsparameters for event targets to avoid error when using fifo sqs queue as targets (fixes #3735)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eladb** [comment]
I was expecting to see some additions to the @aws-cdk/aws-event-targets library to support at the L2 level? @nija-at can you follow up please?

**Comment by nija-at** [comment]
@elad

It looks like the `aws-event-targets` library already supports this. https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events-targets/lib/sqs.ts#L68

**Comment by eladb** [comment]
Oh my god this is so ugly. Maybe worth fixing now...

**Comment by nija-at** [comment]
@eladb -- what are you pointing out as ugly? The call to `Object.assign()`?

I have some improvements that I've addressed here - https://github.com/aws/aws-cdk/pull/3811. Jump in and comment where you think needs improvement/fixing.

**Comment by eladb** [comment]
Yes, Object.assign is definitely an anti-pattern.  I wonder how we approved this CR...

**Comment by nija-at** [comment]
Fixed in https://github.com/aws/aws-cdk/pull/3811

**Pull request merged**
