### PR TITLE
chore(docs): ensure code snippets in aws-lambda README compile

### PR DESCRIPTION
**Pull request by BenChaimberg**
Update README in aws-lambda package to pass strict Rosetta compilation, ie., all the Typescript snippets in the README compile successfully. Also follows convention for unscoped usage of all local names (anything from the aws-lambda package) and scoped usage of all other names.

In particular:
- removes many `lambda.` qualifiers
- creates a "default" fixture with a stack already created (accessible as `this`) and lots of names from the package already supported
- creates a "function" fixture that includes an already-built function (accessible as `fn`)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by nija-at — COMMENTED** [review]
Not super familiar with the options available for rosetta but is there a way to fail build if a fixture and/or snippet fails to compile?

If not, this is going to be broken (again) as soon you look the other way.

**Comment by BenChaimberg** [comment]
Yes, there is [the `--strict` flag](https://github.com/aws/jsii/blob/e84e70f5549a6a0382591aa7a735086fa3e65154/packages/jsii-rosetta/bin/jsii-rosetta.ts#L118-L124) that will cause rosetta to exit unsuccessfully if a snippet fails to compile. It is also available to be configured [via the package.json](https://github.com/aws/jsii/tree/main/packages/jsii-rosetta#enforcing-compilability). However, since we [previously decided not to compile snippets during build](https://github.com/aws/aws-cdk/pull/11273#discussion_r520466255), this would only cause a failure [during packing/release](https://github.com/aws/aws-cdk/blob/4439763a0574d2007b1ef64779ecfdcf1e01c9fd/pack.sh#L41-L46), not during PR build. We could revisit this decision since, by my understanding, rosetta uses the already-existing jsii manifest to discover code snippets and doesn't re-compile. Alternatively, we could add it to [the linting step](https://github.com/aws/aws-cdk/blob/master/tools/cdk-build-tools/lib/lint.ts), which wouldn't affect the watch command.

**Comment by nija-at** [comment]
Awesome diving deep into some previously made decisions to figure this out!

I would suggest that we do the suggestion from [this comment](https://github.com/aws/aws-cdk/pull/11273#discussion_r520466255) you referred above.

> make it a separate npm script for developers to run, OR only do this conditionally under an environment variable

Add an npm script, say executed via `yarn rosetta`, for each of our packages that does the build and an additional environment variable that is enabled as part of [PR build](https://github.com/aws/aws-cdk/blob/master/buildspec-pr.yaml).
Adding it to PR build is important; we want contributors (from the team and outside) to fix the code snippets as part of their PR. Failing at the 'pack' step in our build pipeline makes it the oncall's problem.

The third missing piece would be to use a `package.json` entry which enables (or disables) rosetta compilation for packages as we start fixing existing snippets.

Doing these first (as a separate PR) before fixing up the actual code snippets will guarantee that your work here continues to be used, and doesn't regress in the next change to these files.

----

Adding an npm script to all of our 200+ packages in not as hard as it sounds. If you didn't know already, we have [pkglint](https://github.com/aws/aws-cdk/blob/master/tools/pkglint/lib/rules.ts) for that very use. Modify the rule once and run `yarn pkglint` from the root of the repo to fix all relevant packages.

Happy to chat about how I would approach other things I've mentioned above.

**Comment by BenChaimberg** [comment]
This sounds like a good plan! Most of this is already in place and can leverage the "strict" metadata entry in the package.json, as described above. However, there seem to be some bugs in rosetta that cause this entry to be ignored. Opened aws/jsii#2861 which, upon fix, should unblock this work.

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
