### PR TITLE
docs: recommend lambda runtime nodejs14.x

### PR DESCRIPTION
**Pull request by trivikr**
### Description
Follow-up to https://github.com/aws/aws-cdk/pull/12807

Reasons for recommending NODEJS_14_X:
* Node.js 12.x went LTS in October 2019, and has been actively supported since October 2020.
* Node.js 14.x went LTS in October 2020, and is now actively supported LTS version.

Lambda added support for Node.js 14.x runtime on [2021-02-03](https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/)

### Testing

Verified that all changes in README are either:
* Direct calls to `lambda.Function`
* Indirect calls, like through `cloudfront.experimental.EdgeFunction`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nija-at** [comment]
As far as I know, CloudFormation does not yet support the `ZipFile` property for Node14. (needs to be confirmed)

If this is this case, `Code.fromInline()` API will not work for Node14. Should we be recommending Node14?

**Review by nija-at — CHANGES_REQUESTED** [review]
see https://github.com/aws/aws-cdk/pull/13226#issuecomment-786029199

**Comment by gliptak** [comment]
Just checked and `nodejs14.x ZipFile` still shows:

Resource handler returned message: "Invalid request provided: The ZipFile attribute is not supported for the runtime 'nodejs14.x'"

**Comment by gliptak** [comment]
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/80

**Comment by gliptak** [comment]
`NodeJS 14.x` became supported https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

**Comment by nija-at** [comment]
Closing this pull request. Please submit a new pull request when support for CloudFormation inline is available.

**Pull request closed without merging**
