### PR TITLE
fix(iam): missing validation for actions added post instantiation of a policy statement

### PR DESCRIPTION
**Pull request by VarunWachaspati**
## Bug Description
The validation for actions/nonActions currently only exists in the constructor of the PolicyStatement class as shown below - 
https://github.com/aws/aws-cdk/blob/56ba2ab2c2d9240b76ece17c3296488a63f0b232/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L88-L95

The above validation is missing when we add an action/nonAction post instantiation of the IAM policy statement leading to discrepancy in the behaviour.
The following snippet doesn't throw any error - 
```typescript
const statement = new iam.PolicyStatement({ resources: ['*'] });
statement.addActions('action');
statement.addNonActions('nonaction');
```
## Solution
- Refactored the validation in the constructor into a separate private method called `validatePolicyActions()`
- Executing this new validation method in the `addActions()` and `addNonActions()`
- Fixed existing unit tests which assumed the above behaviour

fixes https://github.com/aws/aws-cdk/issues/21821

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by VarunWachaspati** [comment]
Need some guidance in fixing the following failing unit test. 

https://github.com/aws/aws-cdk/blob/1a37331cbdaf19937369b42c7e5cd72270f28993/packages/%40aws-cdk/aws-iam/test/policy-document.test.ts#L324-L336

As per my understanding, `Lazy.list(...)` token should evaluate to `true` when passed to `cdk.Token.isUnresolved()`, but for some unknown reason it is evaluating to `false` instead. Thus causing the above unit test to fail.
https://github.com/aws/aws-cdk/blob/1a37331cbdaf19937369b42c7e5cd72270f28993/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L232

Is this is a bug `Token.isUnresolved()` method by any chance?

**Comment by TheRealAmazonKendra** [comment]
> Need some guidance in fixing the following failing unit test.
> 
> https://github.com/aws/aws-cdk/blob/1a37331cbdaf19937369b42c7e5cd72270f28993/packages/%40aws-cdk/aws-iam/test/policy-document.test.ts#L324-L336
> 
> As per my understanding, `Lazy.list(...)` token should evaluate to `true` when passed to `cdk.Token.isUnresolved()`, but for some unknown reason it is evaluating to `false` instead and throwing an error as per the below logic.
> 
> https://github.com/aws/aws-cdk/blob/1a37331cbdaf19937369b42c7e5cd72270f28993/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L232-L233
> 
> 
> Thus causing the above unit test to fail.
> Is this is a bug `Token.isUnresolved()` method by any chance?

You don't seem to have any tokens in

> Need some guidance in fixing the following failing unit test.
> 
> https://github.com/aws/aws-cdk/blob/1a37331cbdaf19937369b42c7e5cd72270f28993/packages/%40aws-cdk/aws-iam/test/policy-document.test.ts#L324-L336
> 
> As per my understanding, `Lazy.list(...)` token should evaluate to `true` when passed to `cdk.Token.isUnresolved()`, but for some unknown reason it is evaluating to `false` instead and throwing an error as per the below logic.
> 
> https://github.com/aws/aws-cdk/blob/1a37331cbdaf19937369b42c7e5cd72270f28993/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L232-L233
> 
> 
> Thus causing the above unit test to fail.
> Is this is a bug `Token.isUnresolved()` method by any chance?

You've created a token list but then are evaluating each individual token as a string. The formatting for list vs string are different.

**Comment by VarunWachaspati** [comment]
Thank you so much @TheRealAmazonKendra for helping out. 
I have updated the PR accordingly now and all existing tests are passing.
Since this was primarily a refactor, I didn't add any additional tests. But if anything else is required please let me know.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by VarunWachaspati** [comment]
Hi @TheRealAmazonKendra
Can we merge this PR?
If not, please let me know the next steps.

**Comment by VarunWachaspati** [comment]
Bumping up for visibility.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — COMMENTED** [review]
Please make sure that your PR title confirms to the conventional commit standard (fix, feat, chore) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request)).

Additionally, we need test cases for failure cases. The tests in this PR only covers success cases.

**Comment by VarunWachaspati** [comment]
Sorry for the delay.
- Changed the title of the PR to the best of my knowledge to reflect the nature of the bug being fixed, if it doesn't cut it please do let me know.
- Added a failure unit test case asserting that we throw an error whenever an invalid `action` is being added to the policy statement post instantiation it throws an error.
- Can you please guide me in adding an integration test for this change? I wasn't able to figure it out.

**Comment by Naumel** [comment]
> (...)
>     * Can you please guide me in adding an integration test for this change? I wasn't able to figure it out.

Hello, have you looked at https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md already?

**Comment by VarunWachaspati** [comment]
Yes, I did. I was confused regarding what kind of integration should I be adding in this case, since this PR fixes a validation check that was previously missed. I have added unit tests to assert the validation.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
