### PR TITLE
feat: the assertions module is now stable!

### PR DESCRIPTION
**Pull request by nija-at**
In addition, fix up CDKv2 init templates to not refer to the alpha
version of this module.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nija-at** [comment]
@njlynch - Besides changing the `stability` and `maturity` keys in `package.json`, anything else needs to be done to graduate an alpha module to stable in CDKv2?

**Comment by nija-at** [comment]
@corymhall - I believe these are all the references to assertions alpha in the init templates. Let me know if I missed anything.

**Review by rix0rrr — APPROVED** [review]

**Comment by njlynch** [comment]
> Besides changing the `stability` and `maturity` keys in `package.json`, anything else needs to be done to graduate an alpha module to stable in CDKv2?

I believe we'll also need to update the `UbergenPackageVisibility` rules:

https://github.com/aws/aws-cdk/blob/master/tools/%40aws-cdk/pkglint/lib/rules.ts#L1586-L1603

**Comment by eladb** [comment]
🚀 Congrats!

**Review by njlynch — APPROVED** [review]

**Pull request merged**
