### PR TITLE
feat(aws-apigateway): add support for multi-value query-parameters in apigw sfn integration

### PR DESCRIPTION
**Pull request by MacMannes**
----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by HBobertz** [comment]
Commenting this for visibility while I review this pr. This seems to be adding support for a field that was removed in v2 of api GW's payload format. https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format

Current implementation in v2 bakes both singular and multi query strings into the queryStringParameters. 

Do you need to rely on v1 of this payload? Regardless as I am new to this team I am unsure if this is something we would normally add backwards compatibility for. I will sync with a more senior engineer on this pr today

**Comment by HBobertz** [comment]
Can you provide additional context on the change and the purpose behind it?

**Comment by MacMannes** [comment]
> Can you provide additional context on the change and the purpose behind it?

We are using API gateway v1 in our projects. This was the first time I used the step functions integration and I couldn't get the integration to work with multi value query parameters, because only one of the values are returned in the query parameters field (don't now if it's the first value or the last value).

I thought I could solve this by passing the multivaluequeryparameters field to the input of the step functions integration. But maybe it makes more sense to do it like the V2 implementation? So just join multiple values with a comma? It's cleaner and easier to understand. I can change my PR if you'd like.

I don't know I it's possible for my team to migrate to the V2 implementation, but I will look into that and discuss it with my team members.

**Comment by MacMannes** [comment]
@HBobertz I changed my PR.

I removed the `multivaluequerystring` field and duplicate query strings are now combined with commas and included in the `querystring` field. I think this implementation is more in the line of the v2 implementation, looks clearer and it also means less code in the Step Function when you want to check for query parameters.

**Comment by HBobertz** [comment]
@MacMannes Awesome! Love the updated implementation. Would you be able to provide a dedicated integ test for this?

**Comment by MacMannes** [comment]
@HBobertz Yes, I will do that. I'll have to look into how I can make a dedicated integration test first, but the document for making integ tests gives some hints, so I think I can figure it out.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Putting this into changes requested to reflect the status.

**Comment by TheRealAmazonKendra** [comment]
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

**Pull request closed without merging**
