### PR TITLE
feat(pipelines): allow switching to one CodeBuild action for same-typed assets

### PR DESCRIPTION
**Pull request by hoegertn**
This PR refactors the Asset Stage of the CDK pipeline so that only one FileAsset and one DockerAsset Action are created that are uploading all assets of the respective type.

The main benefit of this is improved performance as uploading in parallel does not save enough time to compensate slower startups of multiple CodeBuilds.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Totally don't mind this change, but I had hoped it would be pluggable.

Probably this needs the `AssetPublishing` class to implement some common interface with two default implementations where the user can pick between, and we default to the legacy one.

**Comment by hoegertn** [comment]
@rix0rrr I added a flag to select the publishing style

**Comment by jakejscott** [comment]
I'm currently running into an issue where there's too many codebuilds running at the same time to upload assets:

```
Action execution failed
Error calling startBuild: Cannot have more than 5 builds in queue for the account (Service: AWSCodeBuild; Status Code: 400; Error Code: AccountLimitExceededException; Request ID: 05ba326d-20e0-44e5-8375-1a82fc960927; Proxy: null)
```

I'm assuming this PR will help solve this problem so 👍

**Comment by mwiarda-fette** [comment]
> I'm currently running into an issue where there's too many codebuilds running at the same time to upload assets:
> 
> ```
> Action execution failed
> Error calling startBuild: Cannot have more than 5 builds in queue for the account (Service: AWSCodeBuild; Status Code: 400; Error Code: AccountLimitExceededException; Request ID: 05ba326d-20e0-44e5-8375-1a82fc960927; Proxy: null)
> ```
> 
> I'm assuming this PR will help solve this problem so 👍
> 
> assets



> I'm currently running into an issue where there's too many codebuilds running at the same time to upload assets:
> 
> ```
> Action execution failed
> Error calling startBuild: Cannot have more than 5 builds in queue for the account (Service: AWSCodeBuild; Status Code: 400; Error Code: AccountLimitExceededException; Request ID: 05ba326d-20e0-44e5-8375-1a82fc960927; Proxy: null)
> ```
> 
> I'm assuming this PR will help solve this problem so 👍
> 
> assets

@jakejscott did you solve your issue with codebuild? We face the same thing. Since a few days our build pipeline just refuses to work...

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]

**Comment by jakejscott** [comment]
Thanks for the work on this, much appreciated :-)

**Comment by HeskethGD** [comment]
Unless I'm missing it, the README or docs don't seem to be very explicit as to which resource the singlePublisherPerType attribute should be set on. Perhaps it could be clarified as to how to implement this.

**Pull request merged**
