### PR TITLE
feat(toolkit): add '--reuse-asset' option

### LINKED ISSUE #1916: toolkit: need a way to avoid building assets
Right now I can't rebuild our superchain image.

Not to mention that when I'm changing something unrelated, it takes half an hour to build this Docker image even though I don't really *want* to update it, I actively can't because there's a problem with the PGP keyservers that the build process wants to download keys from, and the build fails halfway through.

I cannot fix our deployment pipeline because of this issue.

### PR DESCRIPTION
**Pull request by rix0rrr**
Reusing assets avoids rebuilding an asset and just reuses the currently
deployed one. Especially helpful for Docker containers that take a long
time to build.

Fixes #1916

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by rix0rrr** [comment]
I actually had `--no-build`, but `yargs` forces interpretation of the `--no-` prefix to make the thing boolean. So I had to change the name.

And ultimately, I prefer the name to be positive, so you don't have the problem with double negatives.

**Comment by eladb** [comment]
you just specify `build` as a boolean option with a default `true`. it is also common to indicate in the description to use `--no-build` to disable.

--build and --no-build feel much more forward looking and less a hack than the current approach.

**Comment by rix0rrr** [comment]
So you propose to either build *all* assets or *no* assets?

Wouldn't have helped me in my case though, where I *did* want to update a Lambda but *did not* want to rebuild the Docker image.

I explicitly chose for selective control over which asset gets reused.

**Comment by rix0rrr** [comment]
And I agree with the "hack" terminology insofar as that the `id` is unpredictable. What I *actually* wanted was to reuse/not reuse by construct path, including glob support; but the metadata didn't have the construct path and I wanted to get a fix to the pipeline out, so I opted for selecting by the identifier that was already there.

**Comment by eladb** [comment]
got it. So how about `--build-exclude` instead of `reuse-assets`? I really think the terminology should be around "build".

**Pull request merged**
