### PR TITLE
fix(appsync): Source APIs are not auto-merged by default

### LINKED ISSUE #26986: `aws-appsync`: "Auto-merge failed" when creating Merged AppSync API with Source API merge type set `AUTO_MERGE`
### Describe the bug

Hi and thank you for your work on the library!

Merged API Execution Role does not automatically merge the Source API, even with `merge_type=appsync.MergeType.AUTO_MERGE`.
If I understood correctly, the policy added to this role only allows [`appsync:SourceGraphQL`](https://github.com/aws/aws-cdk/blob/408f1f663ee300a783e36a35b5f103a514d8c12e/packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts#L727C7-L727C7).

### Expected Behavior

Creating Merged AppSync API should, by default and when `merge_type` is specifically set as `AUTO_MERGE`, automatically merge Source AppSync APIs.

### Current Behavior

Default behaviour for Source APIs does not work. Manually setting `merge_type` to `AUTO_MERGE` also does not work.

### Reproduction Steps

```
endpoint1_lambda = lambda_.Function(
    self,
    id="endpoint1-lambda",
    function_name="endpoint1-lambda",
    runtime=lambda_.Runtime.PYTHON_3_11,
    handler="app.lambda_handler",
    code=lambda_.Code.from_asset(
        "./lambda_functions/endpoint1",
    ),
)

source_api_1 = appsync.GraphqlApi(
    self,
    id="source-api-1",
    name="source-api-1",
    definition=appsync.Definition.from_schema(
        appsync.SchemaFile.from_asset(
            "./graphql_schemas/sourceApi1.graphql"
        )
    ),
)
endpoint1_lambda_ds = appsync.LambdaDataSource(
    self,
    id="endpoint1-lambda-ds",
    lambda_function=endpoint1_lambda,
    api=source_api_1,
)

appsync.Resolver(
    self,
    id="endpoint1-resolver",
    api=source_api_1,
    type_name="Query",
    field_name="endpoint1",
    data_source=endpoint1_lambda_ds,
    code=appsync.Code.from_asset(
        "./asd_cdk/graphql_unit_resolvers/base.js",
    ),
    runtime=appsync.FunctionRuntime.JS_1_0_0,
)

merged_api = appsync.GraphqlApi(
    self,
    id="merged-api",
    name="merged-api",
    definition=appsync.Definition.from_source_apis(
        source_apis=[
            appsync.SourceApi(
                source_api=source_api_1,
                merge_type=appsync.MergeType.AUTO_MERGE, # this doesn't work
            )
        ],
    ),
)
```

### Possible Solution

Manually creating Execution Role fixes the issue:
```
...
merged_api = appsync.GraphqlApi(
    self,
    id="merged-api",
    name="merged-api",
    definition=appsync.Definition.from_source_apis(
        source_apis=[
            appsync.SourceApi(
                source_api=source_api_1,
                merge_type=appsync.MergeType.AUTO_MERGE,
            )
        ],
        merged_api_execution_role=iam.Role( # <=====
            self,
            id="merged-api-execution-role",
            assumed_by=iam.ServicePrincipal("appsync.amazonaws.com"),
            inline_policies={
                "appsync": iam.PolicyDocument(
                    statements=[
                        iam.PolicyStatement(
                            resources=["*"],
                            actions=["appsync:*"],
                        )
                    ]
                )
            },
        ),
    ),
)
```

### Additional Information/Context

Extending [allowed list of actions](https://github.com/aws/aws-cdk/blob/408f1f663ee300a783e36a35b5f103a514d8c12e/packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts#L729C9-L729C44) should fix the issue. `['appsync:*]` instead of `['appsync:SourceGraphQL']`?

### CDK CLI Version

2.94.0 (build 987c329)

### Framework Version

_No response_

### Node.js Version

v18.16.0

### OS

MacOS

### Language

Python

### Language Version

Python (3.11.5)

### Other information

CleanShot 2023-09-02 at 16 40 45@2x

### PR DESCRIPTION
**Pull request by frixaco**
Creating Merged API does not auto-merge Source API's because it's Execution Role doesn't have enough permissions.
Gives broader (`appsync:*`) set of permissions for Merged API Execution Role to fix the issue.

Closes #26986.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mrgrain** [comment]
@jumic Can you have a look at this?

**Review by rix0rrr — CHANGES_REQUESTED** [review]
`appsync:*` is probably too much. Can you enumerate the necessary permissions?

**Comment by frixaco** [comment]
Hi @rix0rrr. Yep, I can do that. I'll update permissions with only required ones.

**Comment by jumic** [comment]
@ndejaco2 also replied in the PR regarding wrong permissions:
https://github.com/aws/aws-cdk/pull/26895#discussion_r1316461131

Please also check this comment. 

I'm on vacation without notebook, so I can't test any fixes.

**Comment by ndejaco2** [comment]
I am hoping to submit a change that will fix the bugs introduced here as well as refactor the change so that the source api association is itself an L2 construct that can also be used outside the merged api definition in case teams do that in different stacks. I plan to send a PR for this shortly.

**Comment by ndejaco2** [comment]
I sent PR which will better address this: https://github.com/aws/aws-cdk/pull/27121

**Comment by mrgrain** [comment]
Closing in favor of https://github.com/aws/aws-cdk/pull/27121

**Pull request closed without merging**
