### PR TITLE
fix(ec2): NAT provider's default outbound rules cannot be disabled

### LINKED ISSUE #12673: (ec2): allowAllOutbound on default security group should mimic allowAllTraffic on NAT instance
Setting `allowAllTraffic` to `false` in `ec2.NatProvider.instance` should set `allowAllOutbound` on the default security group created for the NAT instance.

### Reproduction Steps

```js
ec2.NatProvider.instance({
      instanceType: new ec2.InstanceType('t2.micro'),
      keyName: key.name,
      allowAllTraffic: false,
})
```
### What did you expect to happen?

Default security group associated with NAT instance disallows all outbound connections.

### What actually happened?

All outbound connections are allowed on the default security group.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by hedrall**
`allowAllTraffic` only applies to inbound traffic, but it should also apply to outbound traffic. 

Deprecate it and add a new enum-based property, `defaultAllowedTraffic`, which also allows controlling outbound traffic rules. There is no option to allow inbound but not outbound because there is no use case for that.

Fix #12673

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Needs a test.

**Comment by hedrall** [comment]
@rix0rrr 
Sorry for the delay.
I have added the test and hope you will check it out.

**Review by rix0rrr — DISMISSED** [review]
You know what, I'm sorry.

I did not parse this PR properly the last time I looked at it because the PR body was very sparse. I'd like a PR body to explain the problem and the solution properly so that it can be read and understood in isolation. For example, I'd like the PR body to have read:

*`allowAllTraffic` only applies to inbound traffic, but it should also apply to outbound traffic. Change it so `allowAllTraffic: false` disables all outbound traffic as well*

This concisely describes the proposed change, and also writing it all out makes it immediately clear that this change will be BREAKING for everyone currently using `allowAllTraffic: false` but not having created outbound rules (because with the current code they wouldn't have had to). It is therefore also clear that it is not safe to change the meaning of this flag.

I will agree with you that the flag is ill-named, and SHOULD do what you propose it does based on its name... but it does not currently do that and changing it is not safe.

I would therefore propose a better change is the following:

* Add new (optional) flags `allowAllInbound`/`allowAllOutbound`, defaults to `true`. Make these control the inbound/outbound behavior.
* Deprecate `allowAllTraffic`, and say it has been replaced with `allowAllInbound`. If it has been supplied it should be treated as if `allowAllInbound` has been specified.

Whether or not there should be a new flag which controls both `allowAllInbound` and `allowAllOutbound` is a different question. That's one of ergonomics, which we can tackle later.

------

Another alternative deprecation-plus-replacement I could see is something like:

```
defaultAllowAll: Traffic.OUTBOUND_ONLY,
defaultAllowAll: Traffic.INBOUND_AND_OUTBOUND,
defaultAllowAll: Traffic.NONE,
```

Or similar, so we don't have to have 2 boolean flags.

Whatever we choose, it's going to have to involve a new parameter as the change cannot be breaking existing infrastructure.

**Comment by hedrall** [comment]
@rix0rrr
Thank you for your review.
I'm sorry that I didn't take many things into consideration.

I tried to fix it using enum like class, but is this the right way to do the part you mentioned?

**Review by rix0rrr — APPROVED** [review]

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
