### PR TITLE
feat(eks): cluster tagging (#4995)

### LINKED ISSUE #4995: [aws-eks] Cluster Tags
To create tags with cluster.

### Use Case

Amazon EKS support resource tags, however, `aws-eks` doesn't support it at this moment.
https://docs.aws.amazon.com/eks/latest/userguide/eks-using-tags.html

cloudformation not yet to support it
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html

However, API/SDK/CLI support it
https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html

### Proposed Solution

To provide the tags property in the [ICluster](https://github.com/aws/aws-cdk/blob/a257d4d07f11cba666a7dd1b8005736ca7113bc3/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L24-L87) interface and implement the cluster tagging in the [Cluster](https://github.com/aws/aws-cdk/blob/a257d4d07f11cba666a7dd1b8005736ca7113bc3/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L233-L624) class with `custom-resources`.

Does it make any sense?

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by choryuidentify**
Fixes #4995

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by otaviomacedo — APPROVED** [review]

**Comment by robertd** [comment]
@choryuidentify This doesn't really apply tags on the cluster itself... Also, I'm not seeing `tags` property on the constructor for the Fargate cluster.

image

image

**Comment by choryuidentify** [comment]
> @choryuidentify This doesn't really apply tags on the cluster itself... Also, I'm not seeing `tags` property on the constructor for the Fargate cluster.
> 
> Edit: I'm using 2.8.0. Let me check if this functionality got ported to cdk 2.x really quick.
> 
> Edit 2: Yep... it did in 2.7.0.

I tested it now with aws-cdk 2.80 and @aws-cdk/aws-eks 1.139.0

```typescript
new eks.Cluster(this, 'test-cluster', {
  version: KubernetesVersion.V1_21,
  tags: {
    "foo": "bar"
  }
})
```

...and result looks good (I didn't deploy now)

I can see the 'tags' on cluster constructor

```yaml
  testcluster29C11904:
    Type: Custom::AWSCDK-EKS-Cluster
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454
          - Outputs.SampleStackawscdkawseksClusterResourceProviderframeworkonEvent06FEB728Arn
      Config:
        version: "1.21"
        roleArn:
          Fn::GetAtt:
            - testclusterRoleF0736E25
            - Arn
        resourcesVpcConfig:
          subnetIds:
            - Ref: testclusterDefaultVpcPublicSubnet1Subnet0CB1FE0A
            - Ref: testclusterDefaultVpcPublicSubnet2Subnet2D94C923
            - Ref: testclusterDefaultVpcPrivateSubnet1Subnet570845A0
            - Ref: testclusterDefaultVpcPrivateSubnet2Subnet7AFA8EC9
          securityGroupIds:
            - Fn::GetAtt:
                - testclusterControlPlaneSecurityGroupC4E3812B
                - GroupId
          endpointPublicAccess: true
          endpointPrivateAccess: true
        tags:
          foo: bar
```

Did you upgrade @aws-cdk/aws-eks of the project?

**Comment by robertd** [comment]
@choryuidentify I'm using cdk 2.8.0 ... and I'm seeing tags being propagated to `Custom::AWSCDK-EKS-Cluster`. Given that tags are supported on [AWS::EKS::Cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html)... something tells me that the custom resource doesn't propagate them properly.

image

**Comment by choryuidentify** [comment]
> @choryuidentify I'm using cdk 2.8.0 ... and I'm seeing tags being propagated to `Custom::AWSCDK-EKS-Cluster`. Given that tags are supported on [AWS::EKS::Cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html)... something tells me that the custom resource doesn't propagate them properly.

I tested it latest CDK and library. It deployed with tags successfully. Please double check your '@aws-cdk/aws-eks' version inside NPM 'package.json'.
CDK version and other module's version are can be different, because module versions are not following CDK version.

package.json
```json
{
  "name": "testcdk",
  "version": "0.1.0",
  "bin": {
    "testcdk": "bin/testcdk.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/aws-eks": "^1.139.0",
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-cdk": "2.8.0",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "aws-cdk-lib": "2.8.0",
    "constructs": "^10.0.0"
  }
}
```

testcdk-stack.ts
```typescript
import { Stack, StackProps } from 'aws-cdk-lib';
import * as eks from 'aws-cdk-lib/aws-eks';
import { KubernetesVersion } from 'aws-cdk-lib/aws-eks';
import { Construct } from 'constructs';

export class TestcdkStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    new eks.Cluster(this, "testCluster", {
      version: KubernetesVersion.V1_21,
      defaultCapacity: 0,
      tags: {
        "foo": "bar",
        "and": "more",
        'other': 'tags'
      }
    })
  }
}
```

Result

**Comment by robertd** [comment]
I’m using projen.  But I’ll try using CDK directly. Also I noticed in your
package.json you’re using 2.8.0 for CDK and and 1.139.0 for eks module.

**Comment by choryuidentify** [comment]
@robertd Sorry, Please check my reply again in GitHub. I edited my message several times, and I removed wrong suggestion.

**Comment by robertd** [comment]
Ah. That makes sense. :)

**Comment by robertd** [comment]
@choryuidentify Must be something on my end, but I'm using 2.8.0 w/ projen.  image

**Comment by robertd** [comment]
@choryuidentify tags started propagating after full cleanup... something got stale on my end.
image

**Comment by choryuidentify** [comment]
Nice!

**Pull request merged**
