### PR TITLE
 fix(core): turn validation errors into metadata errors 

### LINKED ISSUE #2076: DnsValidatedCertificate reports DNS zone example.com to be non-authoritative
When requesting a DnsValidatedCertificate using an imported HostedZone (imported with `HostedZoneProvider.findAndImport`) not previously saved in cdk.context.json, validation fails with error `DNS zone example.com is not authoritative for certificate domain name cdn.mydomain.com`

Same error is present when requesting the certificate for the root domain name:

```typescript
new DnsValidatedCertificate(stack, 'MyCertificate', {
    domainName: 'mydomain.com',
    hostedZone,
});
```

results in: `DNS zone mydomain.com is not authoritative for certificate domain name mydomain.com`

### PR DESCRIPTION
**Pull request by rix0rrr**
Validation errors are currently turned into exceptions. This causes
issues where missing context values lead to validation errors (such as
in the case of `DnsValidatedCertificate`): the error would have been
solved by retrieving the context value, but because an exception is
thrown the CLI stops immediately and doesn't re-execute.

I feel it also makes sense to treat these errors as construct errors,
as opposed to exceptions which I feel should be more "you're misusing
the API" kind of errors, rather than "something is wrong somewhere"
kind of errors.

The change I made is the smallest change to achieve the desired effect.
If we agree that we want this change, it would probably be better to
do it differently, just have `.validate()` implementors call
`this.node.addError()` immediately.

Fixes #2076.

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by eladb** [comment]
I’d expect this to fail many unit tests that rely on validate throwing. Also, I like the guarantee we provide today that synthesize won’t be called if validation failed because then constructs May have invalid data when they synthesize (E.g. pipeline can assume there will at least be a single stage).

**Comment by rix0rrr** [comment]
> I like the guarantee we provide today that synthesize won’t be called if validation failed

That's a good point. We can still provide that guarantee though.

**Comment by rix0rrr** [comment]
> I like the guarantee we provide today that synthesize won’t be called if validation failed

Yep, got some rendering that errors out. But how is it that `skipValidation: true` doesn't run into the same issue? Probable answer: it would have, but our tests just haven't encountered it yet?

**Comment by rix0rrr** [comment]
Hmm. I still feel metadata errors are the "correct" solution, but this is indeed a harder change than it seems at first sight.

**Comment by eladb** [comment]
When a test used skipValidation it explicit acknowledges that it’s aware of the resulting behavior

**Comment by eladb** [comment]
Perhaps short term we can just special case the dummy value so that validation will not fail

**Comment by eladb** [comment]
Let's punt this for now

**Pull request closed without merging**
