### PR TITLE
refactor(ecs): refactor addPortMapping method

### LINKED ISSUE #24170: (ecs): small refactor for PortMapping ease of change
### Describe the feature

Sorry if I have the wrong category for the Issue or the wrong place for the discussion!

While looking at Issue #23509, I was surprised by the following `addPortMappings` conditional branch.

https://github.com/aws/aws-cdk/blob/de097ee9b40c983d733d31c420389933ea32f6d6/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L567-L607

The ContainerDefinition class is responsible for many of the responsibilities, and many if statements are added to verify PortMapping's sanity.

I feel that by writing down if statements like this, we lose the ease of modification.

Therefore, I would like to refactor it so that many contributors can easily modify it here in a way that does not affect the existing system!

### Use Case

ECS is a very widely used service, and I believe it is a service that will continue to see many bug fixes and feature additions.

I think that every time we add more properties in the future, we will make it harder to make changes by making miscellaneous changes!

I want to make it easy for many developers to contribute to this project!

### Proposed Solution

I think `ContainerDefinition` has too many responsibility.

An if statement is written in `addPortMappings` that assumes all contexts.

https://github.com/aws/aws-cdk/blob/de097ee9b40c983d733d31c420389933ea32f6d6/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L567-L607

For example, this nested if statement is also commented as Sevice Connect logick, but now I don't know what the decision logic is for.

https://github.com/aws/aws-cdk/blob/de097ee9b40c983d733d31c420389933ea32f6d6/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L578-L606

So, I suggest creating a PortMap or similarly named class (I think it would be a Value Object) like below.

```ts
export class PortMap {
  readonly portmap: PortMapping;
  readonly namedPorts: Map<string, PortMapping>;
  readonly networkMode: NetworkMode;

  constructor(pm: PortMapping, np: Map<string, PortMapping>, nwm: NetworkMode) {
    this.portmap = pm;
    this.namedPorts = np;
    this.networkMode = nwm;
    this.hasRequiredProp();
    this.canServiceConnect();
  }

  private hasRequiredProp() {
    if ( this.portmap.name == '') {
      throw new Error('Port mapping name cannot be an empty string.');
    }
  }
  private canServiceConnect() {
    // validation
  }
  private addNamedPort() {
    // return new NamedPort(Don'n change curret taskdef propertiy)
  }
}
```

I thought it would make for a more prospective code by taking the responsibility for checking the sanity of PortMapping related properties out of the picture!

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.64.0

### Environment details (OS name and version, etc.)

macOS Monterey

### PR DESCRIPTION
**Pull request by bun913**
This PR...

- Refactor ecs.ContainerDefintion.addPortMapping method
- The addPortMapping method had many if statements and it was difficult to understand what was being determined.
- It was also difficult to make changes.
- Therefore, I divided the classes by interest to improve visibility.

Closes #24170 .

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
My eyeballs thank you for this refactor. Two asks: Could you add some unit test coverage for the new public functions you've created? Could you run an integ with `--force` that uses this to ensure that everything deploys correctly? If the second ask is a hassle, I can also run it.

**Comment by bun913** [comment]
> Could you run an integ with `--force` that uses this to ensure that everything deploys correctly? If the second ask is a hassle, I can also run it.

Thank you for advice!
I'll do both things.

**Comment by bun913** [comment]
@TheRealAmazonKendra 

> Could you add some unit test coverage for the new public functions you've created? Could you run an integ with --force that uses this to ensure that everything deploys correctly? If the second ask is a hassle, I can also run it.

Sorry for I can't do integ test because of cost problem.(My Environment turn on Config.So it costs highly.)

Could you do integ test?(I prepare my environment for running integ test by next pull request.)

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra
> 
> > Could you add some unit test coverage for the new public functions you've created? Could you run an integ with --force that uses this to ensure that everything deploys correctly? If the second ask is a hassle, I can also run it.
> 
> Sorry for I can't do integ test because of cost problem.(My Environment turn on Config.So it costs highly.)
> 
> Could you do integ test?(I prepare my environment for running integ test by next pull request.)

Totally understandable. I'll run them today.

**Comment by TheRealAmazonKendra** [comment]
Two of the tests failed but I suspect it's not actually because of your change. I'm troubleshooting these now.

**Comment by bun913** [comment]
@TheRealAmazonKendra 

OK. Thank you for teach me.

Please let me know which test failed and I will investigate on my end.

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra
> 
> OK. Thank you for teach me.
> 
> Please let me know which test failed and I will investigate on my end.

Looks like these failures are unrelated. I'll fix them in a separate PR. One needs a test configuration change and the other is failing on deletion likely due to not deleting the resources in the correct order. But, that's in a test that isn't impacted by this change.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
