### PR TITLE
feat(stepfunctions-tasks): add `AutoTerminationPolicy` to `EmrCreateCluster` 

### PR DESCRIPTION
**Pull request by jacobfi**
Auto-termination is supported with Amazon EMR versions 5.30.0 and 6.1.0 and later.
This change enables CDK users to specify an auto-termination policy on EMR clusters created through the aws-stepfunctions task EmrCreateCluster.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by kaizen3031593 — APPROVED** [review]
🎉 Thanks for the contribution @jacobfi!

**Comment by kaizen3031593** [comment]
@jacobfi to merge this, we need to get past this error:

```bash
The merge-queue pull request can't be update
Details: `Pull request can't be updated with latest base branch changes

Mergify needs the author permission to update the base branch of the pull request.
audienceproject needs to authorize modification on its head branch.
err-code: C1535`
```

**Comment by jacobfi** [comment]
> @jacobfi to merge this, we need to get past this error:
> 
> ```shell
> The merge-queue pull request can't be update
> Details: `Pull request can't be updated with latest base branch changes
> 
> Mergify needs the author permission to update the base branch of the pull request.
> audienceproject needs to authorize modification on its head branch.
> err-code: C1535`
> ```

> Thank you for contributing! Your pull request will be updated from master and then merged automatically (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).

Hi @kaizen3031593 

Thank you for approving the PR.

I would love to give your mergify bot access to the fork, but I can't seem to make it work. I have followed the link to the Github doc explaining how, but the option of "Allow edits from maintainers" is nowhere to be seen on this PR.

I can add people and teams manually to access the fork, but I don't know which users/teams to add. Can you help with that?
I can find some users with the name 'mergify' but something tells me that's not your bot.

**Comment by jacobfi** [comment]
@kaizen3031593 
I have added you as admin on the fork.

**Comment by kaizen3031593** [comment]
@jacobfi unfortunately that doesn't help. We really need that "allow edits from maintainers" tag to be set. I can think of two things to do: perhaps somewhere in your settings you have set something to never allow this option? Alternatively you can try to open a new pull request and there should be a button that says "allow edits from maintainers" that is _by default_ set to true. See if that's the case for you, and if so, you can just open a new PR with that tag already set.

**Comment by jacobfi** [comment]
Hello @kaizen3031593 
I think I found a solution by transfering the repository to my own Github user.
You can proceed with the merge - it should work now!

**Review by kaizen3031593 — APPROVED** [review]

**Comment by redflag-cloud** [comment]
still get the error:

`Resource handler returned message: "Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: The field "AutoTerminationPolicy" is not supported by Step Functions at /States/CreateEMRCluster/Parameters' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: 9643a99d-1315-4689-8526-f24fa00edf39; Proxy: null)"`

Best Regards,

**Pull request merged**
