### PR TITLE
feat(s3): adds objectSizeLessThan property for s3 lifecycle rule

### PR DESCRIPTION
**Pull request by daschaa**
Fixes (other half - see #20425) of #20372.
This implements the `objectSizeLessThan` property for a S3 lifecycle rule.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by comcalvi — DISMISSED** [review]
Nice work!

**Comment by daschaa** [comment]
> Nice work!

Thank you! ❤️ 
Unfortunately the review was dismissed because of changes. Could you add your review again? Thanks in advance 😊

**Review by comcalvi — APPROVED** [review]
woops, made some merge conflicts there. Should be clear now

**Comment by daschaa** [comment]
@comcalvi I fixed a linting error I accidentally introduced 🫣 Could you review it again please? 😊

**Review by comcalvi — APPROVED** [review]

**Pull request merged**
