### PR TITLE
feat(eks): support updateConfig properties for managed node groups

### PR DESCRIPTION
**Pull request by kishiel**
This is a duplicate of [PR 27320](https://github.com/aws/aws-cdk/pull/27320) but on a new branch in my repo.

This change enables nodegroups to configure updateConfig properties which will allow nodegroups to upgrade more than 1 instance at a time.  The default value of 1 results in slow deployment times which prevented my service pipelines from quickly delivering fixes to my customers.  This change allows each nodegroup to specify a maximum count of instances, or percent, which can be upgraded in parallel.

### CODE REVIEW

**Review by lpizzinidev — APPROVED** [review]
Thanks for opening a new PR 👍
Extra note: I would change the title to `feat(eks): support updateConfig properties for managed node groups`

**Comment by kishiel** [comment]
Title changed based on your suggestion.

**Review by sumupitchayan — APPROVED** [review]
Thanks for you contribution!

**Comment by vinayak-kukreja** [comment]
Apologies, looks like this did not auto merge. Tracking to merge.

**Comment by vinayak-kukreja** [comment]
@Mergifyio update

**Review by sumupitchayan — APPROVED** [review]

**Pull request merged**
