### PR TITLE
fix(core): custom resource provider NODEJS_12 now looks like Lambda's NODEJS_12_X, add Node 14

### PR DESCRIPTION
**Pull request by robertd**
Purpose of this PR is to align `runtime` options for custom resource providers with `aws-lambda` runtime options.

New selections include `NODEJS_12_X` and `NODE_JS_14_X`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
@rix0rrr Please review. Thanks!

**Review by rix0rrr — APPROVED** [review]

**Comment by viniciuskneves** [comment]
Hey @robertd, Lambda Edge doesn't support Node 14 yet, right?

Docs are here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html#lambda-requirements-lambda-function-configuration

I tried it myself and got an error message when deploying.

**Comment by robertd** [comment]
@viniciuskneves You're correct... Lambda@Edge doesn't but custom resource lambda does (inline version).

image

image

@nija-at @rix0rrr @njlynch Any thoughts on how to handle this catch 22?

Should we revert custom resource to use Node 12 only? Or should we put checks in place for Lambda@Edge since it's experimental feature at the moment?

**Comment by nija-at** [comment]
@viniciuskneves & @robertd - could you open an issue for this?

**Comment by nija-at** [comment]
Oops, I see you already have - https://github.com/aws/aws-cdk/issues/13551

**Pull request merged**
