### PR TITLE
fix(appsync): revert to allow resolver creation from data source

### LINKED ISSUE #11522: [aws-appsync] Deploy fails when trying to change datasource
When trying to remove a datasource and create a new one, the deploy fails with the message: **Only one resolver is allowed per field.** 

### Reproduction Steps

The first step is to deploy a stack with a simple data source:

```
const api = new appsync.GraphqlApi(this, 'Api', {
      name: 'demo',
      schema: appsync.Schema.fromAsset('src/schema.graphql'),
});
const lambdaFunction = new lambda.Function(this, 'lambdaId', {
      runtime: lambda.Runtime.NODEJS_12_X,
      code: lambda.Code.fromAsset('src'),
      handler: 'main.handler',
});
const lambdaDS = api.addLambdaDataSource('lambdaDS', lambdaFunction);
lambdaDS.createResolver({
      typeName: 'Query',
      fieldName: 'getDemos',
      requestMappingTemplate: appsync.MappingTemplate.lambdaRequest(),
      responseMappingTemplate: appsync.MappingTemplate.lambdaResult()
})
```
then when trying to change the datasource, deploying this: 
```
const api = new appsync.GraphqlApi(this, 'Api', {
      name: 'demo',
      schema: appsync.Schema.fromAsset('src/schema.graphql'),
});
const otherDS = api.addNoneDataSource('otherDS')
otherDS.createResolver({
      typeName: 'Query',
      fieldName: 'getDemos',
      requestMappingTemplate: appsync.MappingTemplate.fromString('{}'),
      responseMappingTemplate: appsync.MappingTemplate.fromString(JSON.stringify([{id: '1', version: '1.0'}]))
})
```
it fails.

### What did you expect to happen?
it should update the datasource and resolver, but apparently it's not deleting the old resolver (or not doing it in order), and the deploy is failing

I was trying to update the resolver, but it only works when I deploy twice, first time deleting the old one, and the second time creating the new one
### What actually happened?
Deploy fails with message **Only one resolver is allowed per field.**

Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: 3ab24c35-8cae-43c7-9abd-a506f6879f0c; Proxy: null)

### Environment

  - **CDK CLI Version: 1.74.0**
 
  - **Node.js Version:10.16.2** 
  - **OS: macos 10.15.7**
  - **Language: javascript** 

### Other

--- 

This is :bug: Bug Report

### LINKED ISSUE #12635: (aws-appsync) Upgrading from v1.70.0 to 1.85.0 resulted in AppSync GraphQL endpoints not being wired-up correctly
We had an existing, working AppSync GraphQL service that was deployed using CDK v1.70.0.

I reviewed all the release notes from v1.70.0 to v1.85.0 yesterday and did not spot anything that would cause a breaking change to this deployment. I therefore upgraded to CDK v1.85.0 yesterday but found that it had not wired-up any of the Query or Mutation Resolvers to the Lambda Data Source that we use.

I then reverted to v1.70.0 but found that it had not fixed the issue I spotted. I finally undeployed and then re-deployed to get the service back to normality.

Could this be a bug in the CDK or have I missed something in the release notes that I am supposed to follow first?

### Reproduction Steps

Described above.

### What did you expect to happen?

My AppSync GraphQL service to be deployed correctly.

### What actually happened?

None of our Query or Mutation Resolvers to the Lambda Data Source that we use were wired-up.

### Environment

  - **CDK CLI Version  : v1.85.0**
  - **Framework Version: v1.85.0**
  - **Node.js Version: 12.14.1**
  - **OS               : Run in CircleCI using image circleci/node:12.14.1**
  - **Language (Version): TypeScript (4.1.3)**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by BryanPan342**
* Revert to old behavior of allowing a data source to create a resolver as UNIT resolvers stem from data sources.
* Maintaining new behavior of having `GraphqlApi` create resolvers as PIPELINE resolvers stem from the `GraphqlApi` itself

Fixes #12635
Fixes #11522

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by BryanPan342** [comment]
@p0wl @asnaseer-resilient it was best to keep both functionality as PIPELINE resolvers should be tied to a GraphqlApi as well

**Comment by p0wl** [comment]
Nice! Thanks!!

**Review by p0wl — APPROVED** [review]

**Comment by p0wl** [comment]
Anything that I/we can do to get this merged? This is blocking us quite a bit.

**Comment by BryanPan342** [comment]
> Anything that I/we can do to get this merged? This is blocking us quite a bit.

I think we are just waiting on a maintainer to accept these changes. @MrArnoldPalmer this seems like a `p0` bug so would be nice to have merged into the next release

**Comment by MrArnoldPalmer** [comment]
Hey @BryanPan342, added a question to the original issue https://github.com/aws/aws-cdk/issues/12635#issuecomment-782286027. Respond here or there, either way.

**Review by MrArnoldPalmer — APPROVED** [review]
💯 ty @BryanPan342 !

**Comment by smacintyre** [comment]
This is a breaking change. Broke all my revolvers. How do we work around this?

Feeling a little disappointed that:
* This wasn't documented as a breaking change
* The documentation is out of date

**Pull request merged**
