### PR TITLE
chore(apigatewayv2): move lambda and http proxy integrations to the 'integrations' module

### PR DESCRIPTION
**Pull request by nija-at**
We now have a `@aws-cdk/aws-apigatewayv2-integrations` module that is
intended to hold all integration of HTTP APIs with other services.

In line with this, move `LambdaProxyIntegration` and
`HttpProxyIntegration` classes to this module.

BREAKING CHANGE: `LambdaProxyIntegration` and `HttpProxyIntegration`
classes have moved to the `@aws-cdk/aws-apigatewayv2-integration` module.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ayush987goyal** [comment]
I was about to implement it :D

**Comment by nija-at** [comment]
> I was about to implement it :D

Haha. Sorry, I wasn't aware.

**Comment by ayush987goyal** [comment]
@nija-at Could we please update the README of the integration package with these new integrations? Also, there is one nested header issue in README of the apigatewayv2 module readme [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html#metrics) which we can probably add here.

**Comment by nija-at** [comment]
> @nija-at Could we please update the README of the integration package with these new integrations? Also, there is one nested header issue in README of the apigatewayv2 module readme [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html#metrics) which we can probably add here.

Good call. Updated the README.

**Review by ayush987goyal — APPROVED** [review]

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
