### PR TITLE
feat(ssm): implement ssm automation and command documents

### LINKED ISSUE #4030: allow creation of ssm documents
### General Information
* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

### Description
Currently to create a ssm document in cdk you can only use a json object as the content

### Proposed Solution
allow creating of ssm documents in cdk. ability to generate a full document with parameters etc 

### Other information
I believe this is not on the roadmap for the ssm team but want to capture this so more eyes are on it

### LINKED ISSUE #7710: Be able to target SSM RunCommand with aws-events.Rule
Hello,

It seems that we can't target an SSM Run Command with Events > **class Rule (construct)**  : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.IRuleTarget.html

It's not obtainable from Ssm : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.RuleTargetConfig.html

### Use Case

I want to create scheduled Events Rule to Target an SSM RunCommand to call a Document, for example, to RunShellScript on my target(s) identified with Tags.

### Proposed Solution

Be able to configure SSM Run COmmand in Events.Rule, Yaml example : 

```
  TargetsProperties:
    - Arn: "arn:aws:ssm:{{environment_config.region}}::document/AWS-RunShellScript"
      Id: "1"
      Input: "{
      \"commands\":[ echo "Hello World" ]
      }"
      RoleArn: !stack_output ecs-host-cloudwatch-events-iam-role::RoleArn
      RunCommandParametersProperties:
        - Key: tag:UpdateECSAgent
          Values:
            - "true"

```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by NathanTCz**
Implemented `IDocument`. Currently only `Automation` and `Command` document types are supported, with the following two new constructs:
* `AutomationDocument`
* `CommandDocument`

This PR is related to and blocks #22636

closes #4030

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
Will reply on this shortly.

**Comment by NathanTCz** [comment]
@TheRealAmazonKendra any feedback here?

**Comment by TheRealAmazonKendra** [comment]
Hi @NathanTCz my apologies for taking so long to get back to this. I was unexpectedly out for quite some time. In addition to that, I was back and forth on how to respond to this PR. It's large enough that I would typically require an RFC for it, but then again, you did this work at my suggestion (which I expected to be much much smaller than this).

Per our typical standards, this PR is too big, but I know that implementing this functionality wasn't actually your original goal. So, I'm wondering if you'd be fine going the RFC route so that we can ensure we get this design correct before moving forward with implementation. If not, I think we owe it to you to review this anyway but I'm afraid we'll end up with an excessive amount of back and forth on it.

On the other hand, maybe we can break this up and start with just `IDocument` and then build the additional types of documents from there? I _believe_ that's the type we'd use in an event target anyway.

What are your thoughts here?

**Comment by NathanTCz** [comment]
Hi @TheRealAmazonKendra, thanks for getting back on this one and for the feedback. I'm happy to move forward in whatever way you all see fit.

I think it probably makes the most sense to pair this PR down to just the `IDocument` implementation. That would open the door for a lot of other things outside of the extra document implementations also in this PR. To be honest, I only included those because I ultimately need them implemented as well. However, we can decide the best implementation for those in another PR. 

Let me know the best way to move forward with this one. I can pull out everything but `IDocument` in this branch, or close this PR and open another with just that code. Either way, thanks for the feedback!

**Pull request closed without merging**
