### PR TITLE
chore(apprunner-alpha): add runtimes PYTHON_311 and NODEJS_18

### LINKED ISSUE #30146: (aws-apprunner-alpha): missing apprunner runtime Python_311
### Describe the bug

Apprunner supports two Python Runtimes: 3 and 311 as documented here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apprunner-service-codeconfigurationvalues.html

PYTHON_311 is missing from https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-apprunner-alpha/lib/service.ts#L210

### Expected Behavior

It is expected that the CDK should make all supported runtimes available.

### Current Behavior

It only supports Python_3  (this translates to the extremely old Python 3.8)

### Reproduction Steps

apprunner_alpha.Service(
    self,
    "My Web Site",
    instance_role=web_instance_role,
    source=apprunner_alpha.Source.from_git_hub(
        repository_url="",
        branch="main",
        configuration_source=apprunner_alpha.ConfigurationSourceType.API,
        code_configuration_values=apprunner_alpha.CodeConfigurationValues(
            **runtime=apprunner_alpha.Runtime.PYTHON_3,**
            port="5000",
            start_command="",
            build_command="",
            environment_variables={},
        ),
        connection=apprunner_alpha.GitHubConnection.from_connection_arn(
            web_github_arn
        ),
    ),
)

### Possible Solution

  /**
   * Python 3.11
   */
  public static readonly PYTHON_311 = Runtime.of('PYTHON_311')

### Additional Information/Context

_No response_

### CDK CLI Version

2.140.0

### Framework Version

_No response_

### Node.js Version

v20.9.0

### OS

Ubuntu

### Language

Python

### Language Version

Python 3.11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mellevanderlinde**
### Issue # (if applicable)

Closes #30146.

### Reason for this change

Runtimes Python 3.11 and NodeJS 18 were missing.

### Description of changes

Runtimes Python 3.11 and NodeJS 18 were added.

### Description of how you validated changes

No tests were added, as it seems not required for this type of change.

### Checklist
- [*] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mellevanderlinde** [comment]
I'd like to request an "Exemption Request" as this change might not require changes to a README and tests. Happy to hear your thoughts on this

**Review by TheRealAmazonKendra — DISMISSED** [review]

**Comment by mellevanderlinde** [comment]
@TheRealAmazonKendra It seems like the other (very similar) PR has been closed (i.e., not merged) (see https://github.com/aws/aws-cdk/pull/30156). Does that by any chance mean that this PR can move forward?

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks good! Thanks!

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
