### PR TITLE
feat(ec2): add g6 instance

### LINKED ISSUE #30683: (module name): (short issue description)
### Describe the feature

Need G6 EC2 Instance support

### Use Case

Need to provision ECS EC2 while using G6 instance

### Proposed Solution

_No response_

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

^2.1.0

### Environment details (OS name and version, etc.)

mac 14.5

### PR DESCRIPTION
**Pull request by mellevanderlinde**
### Issue # (if applicable)

Closes #30683 

### Reason for this change

G6 instances are not yet supported by CDK L2

### Description of changes

Added G6 instance class

### Description of how you validated changes

Added `g6` to existing unit test

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mellevanderlinde** [comment]
Would this change qualify for an "Exemption Request"?

**Review by msambol — APPROVED** [review]
LGTM but can you please change the title to `feat`.

**Comment by msambol** [comment]
> Would this small change qualify for an "Exemption Request"? An integration test might not be required for adding an instance class

Yeah, no integration test is needed here.

**Review by scanlonp — APPROVED** [review]
Thanks for adding this @mellevanderlinde! 

This does not need an integ test or readme update, I'll throw the labels on.

**Pull request merged**
