### PR TITLE
feat(ecs-patterns) add idle timeout to multi alb fargate and ec2 services

### LINKED ISSUE #12913: ApplicationLoadBalancedFargateService CDK construct: currently there is no way to specify idleTimeout for the load balancer
Hello.

Currently there is no way to specify an idleTimeout for the load balancer if we create an ApplicationLoadBalancedFargateService.
Even though we do have such option when we are creating an ApplicationLoadBalancer directly via the ApplicationLoadBalancer construct.

I suggest to implement such option for the ApplicationLoadBalancedFargateService as it is needed very much.

### Use Case

I'm using a Fargate service to run a docker container with a 3rd party library that provides http endpoint. This library can take longer than 1 minute to respond (depending on the input) even on the most performant configuration. In that case I'm receiving a 504 Gateway Time-out error from the load balancer. That's why I need a way to specify the idleTimeout for the ApplicationLoadBalancedFargateService.

### Proposed Solution

To add a set of load balancer related configuration options to the ApplicationLoadBalancedFargateServiceProps.

### Other
Related to the support case 7958289501

Regards,
Anton.

### PR DESCRIPTION
**Pull request by michaeldrey**
This PR exposes the idleTime property for both EC2 and Fargate **multi** ALB services. [Per the CFN specs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattributes.html), I have set the idleTimeout to default to 60 seconds, and it cannot exceed 4000 seconds.

If no value is provided we set the value to undefined. We do this because:

1. The default value is set for the user via the CFN. The behavior for the property is to either add a value or leave it undefined and let CFN set the default.[ See here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts#L102)

2. Setting a default causes snapshot tests to fail for dependent services as we're adding a new attribute to the cloudformation.

A README entry has been created for this property.

Relates to
#21221
#21261

closes #12913
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by michaeldrey** [comment]
Do not merge until #21261 is completed.

**Review by TheRealAmazonKendra — DISMISSED** [review]
Just assigning this to myself and marking it as changes requested to indicate to my team mates that we're already engaging on this, now split into mulitple PRs.

**Comment by michaeldrey** [comment]
@Mergifyio update

**Comment by michaeldrey** [comment]
@mergifyio update

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
