### PR TITLE
fix(core): asset used in multiple Stages is only bundled in the first Stage

### LINKED ISSUE #10877: [pipelines] 1.67.0 breaks custom asset bundling when using multiple pipelines
After updating to CDK 1.67.0, my custom asset bundling logic no longer works while using multiple pipelines. This bundling logic uses the `BundlingOptions` construct to move the lambda function handler to a nested folder structure. When executing `cdk synth` on the new CDK version, only the first pipeline defined in `app.py` uses the bundling logic, and the other copies the code from the path without modifying it.

If I revert back to 1.66.0 I no longer see this behavior, with no other code changes. Both pipelines produce the correct artifacts using the older CDK version.

### Reproduction Steps

I have stripped down my code to provide a minimal example, and have posted it [here](https://github.com/danielfrankcom/aws-cdk-bug-report).

Running `cdk synth` against this code produces 2 assemblies in `cdk.out`, where each assembly has an asset representing the lambda function. The `cdk synth` output can also be seen by running the pipeline on AWS, although it is easier to test locally.

### What did you expect to happen?

I expected both assets in the `cdk.out` directory to contain the bundled directory structures.

Both assets should contain a directory structure that looks like the following:

```
asset.1234
  - entry.py
  - lib
    - function
      - function.py
```

### What actually happened?

Only the first pipeline declared in `app.py` has the bundled directory structure.

The second asset is bundled using the default settings, which ignore the custom bundling logic.

```
asset.1234
  - function.py
```

### Environment

  - **CLI Version      :** 1.67.0 (build 2b4dd71)
  - **Framework Version:** 1.67.0
  - **Node.js Version:** v12.18.4
  - **OS               :** WSL2 in Windows 10 (same behavior occurs in CodeBuild)
  - **Language (Version):** Python 3.8

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
Always stage assets in the outdir of the top level Stage/App.

Closes #10877

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@rix0rrr what about this simple fix?

**Comment by jogold** [comment]
@misterjoshua why do I need to update the integ tests in `aws-lambda-python` after the change in `core` here?

**Comment by rix0rrr** [comment]
I'm brewing something myself as well. Thanks for providing your take, once I'm done I'm going to compare and contrast :).

**Comment by misterjoshua** [comment]
> @misterjoshua why do I need to update the integ tests in `aws-lambda-python` after the change in `core` here?

I'll take a look.

**Comment by misterjoshua** [comment]
@jogold It looks like the emitted asset changed from the pip install in a recent version of the sam build containers in question. This looks like it's blocking #10958 now too.

**Comment by misterjoshua** [comment]
> @jogold It looks like the emitted asset changed from the pip install in a recent version of the sam build containers in question. This looks like it's blocking #10958 now too.

@jogold We've merged a fix which I hope should help.

**Comment by jogold** [comment]
Closing in favor of #11008

**Pull request closed without merging**
