### PR TITLE
fix(cfnspec): IoT timestamp type by overwriting with patch

### LINKED ISSUE #22732: (@aws-cdk/aws-iot): CfnLocationAction asks for Date type despite spec wanting Timestamp type
### Describe the bug

The `iot.CfnTopicRule` construct now supports an action called `LocationAction` ([link to CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-locationaction.html)).

The `LocationAction` entity has a property called [`Timestamp`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-action.html#cfn-iot-topicrule-locationaction-timestamp) which [according to the CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-timestamp.html) is supposed to be of type `AWS::IoT::TopicRule Timestamp` and have shape:

```json
{
  "Unit": String,
  "Value": String
}
```

At present, in version `1.179.0` the property has incorrect type of `Date`, which causes the synth step to fail.

### Expected Behavior

The resource should have the correct type and allow to deploy correctly.

### Current Behavior

Error:
```
cdk-stack.ts(114,17): error TS2322: Type '{ value: string; unit: string; }' is not assignable to type 'Date | IResolvable'.
  Object literal may only specify known properties, but 'value' does not exist in type 'Date | IResolvable'
```

Screenshot 2022-11-01 at 15 26 20

### Reproduction Steps

```ts
import * as cdk from "@aws-cdk/core";
import * as iot from "@aws-cdk/aws-iot";
import * as iam from "@aws-cdk/aws-iam";

export class cdkStack extends cdk.Stack {
  constructor(
    scope: cdk.Construct,
    id: string,
    props?: cdk.StackProps,
  ) {
    super(scope, id, props);

    const role = new iam.Role(this, "iot-tracker-role", {
      assumedBy: new iam.ServicePrincipal("iot.amazonaws.com"),
      description: "IAM Role that allows IoT Core to update a Tracker",
      inlinePolicies: {
        allowTracker: new iam.PolicyDocument({
          statements: [
            new iam.PolicyStatement({
              resources: [
                `arn:aws:geo:${cdk.Stack.of(this).region}:${
                  cdk.Stack.of(this).account
                }:tracker/tracker_location_workshop`,
              ],
              actions: ["geo:BatchUpdateDevicePosition"],
            }),
          ],
        }),
      },
    });

    // Create an IoT Topic Rule that will send the location updates to Location Service
    const topicRule = new iot.CfnTopicRule(this, "TopicRule", {
      ruleName: "assetTrackingRule",
      topicRulePayload: {
        sql: `SELECT * FROM 'iot/trackedAssets'`,
        awsIotSqlVersion: "2016-03-23",
        actions: [
          {
            location: {
              deviceId: "${deviceID}",
              latitude: "${longitude}",
              longitude: "${latitude}",
              roleArn: role.roleArn,
              timestamp: {
                value: "${timestamp()}",
                unit: "MILLISECONDS",
              },
              trackerName: "tracker_location_workshop",
            },
          }
        ],
      },
    });
  }
}
```

### Possible Solution

Change the type to the correct one.

### Additional Information/Context

Adding this manual override to the resource allows to deploy correctly, proving that the resource is mistyped in CDK:
```ts
topicRule.addOverride("Properties.TopicRulePayload.Actions.0", {
      Location: {
        DeviceId: "${deviceID}",
        Latitude: "${longitude}",
        Longitude: "${latitude}",
        RoleArn: role.roleArn,
        Timestamp: {
          Value: "${timestamp()}",
          Unit: "MILLISECONDS",
        },
        TrackerName: "tracker_location_workshop-ok",
      },
    });
```

### CDK CLI Version

2.41.0

### Framework Version

_No response_

### Node.js Version

16.15.0

### OS

Linux / macOS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sthuber90**
This PR provides a patch for the CloudFormation `Timestamp` property in AWS IoT. Here, a timestamp does not reflect a date but is an object, consisting of a `Unit` and `Value` property. By patching the IoT spec, renaming the `Timestamp` property type, the problem gets resolved.

Closes #22732

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by sthuber90** [comment]
Exemption Request

As the tests for cfnspec are generated I don't see the need to add custom unit or integration test logic. Let me know if you'd still like me to add tests and where you'd want them

**Comment by sthuber90** [comment]
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Fixes must contain a change to a test file.
> ❌ Fixes must contain a change to an integration test file and the resulting snapshot.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.
> 
> If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

I thought I followed the comment and asked for an `Exemption Request` request. Any help to fix the PR linter is appreciated

**Comment by sthuber90** [comment]
Ok, so after multiple iterations and trying different approaches (see commit history) it's become apparent that CDK does not like me renaming the `Timestamp` property to avoid breaking changes. The solution now is to keep the `Timestamp` property, even though it's no longer used, and add the custom `IotTimestamp` and use that one in the `LocationActionProperty`. See [build log](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cfee7f0c-a378-4428-b12b-758b28021ee2%2Fbuild.log) with failure message. 

I don't think it's so ideal as this will result in the `TimestampProperty` and `IotTimestampProperty` being created thereby duplicating the code.

**Comment by sthuber90** [comment]
@TheRealAmazonKendra  or @corymhall does it makes sense that one of you reviews the PR since your also involved in another PR from me related to IoT?

**Comment by corymhall** [comment]
> @TheRealAmazonKendra or @corymhall does it makes sense that one of you reviews the PR since your also involved in another PR from me related to IoT?

@sthuber90 let me check with the team on this one. I'm not sure the approach that we want to take.

**Pull request closed without merging**
