### PR TITLE
feat(cli): cdk watch --concurrency

### LINKED ISSUE #21597: (cli): add `cdk watch --concurrency N`
### Describe the feature

I'd like the new `--concurrency` option from #20345 to support `cdk watch` mode.

### Use Case

In watch mode, I'd like my multi-stack apps to deploy stacks concurrently.

### Proposed Solution

I have opened #21598.

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

### PR DESCRIPTION
**Pull request by misterjoshua**
This PR adds #20345's `--concurrency` to `cdk watch` mode. Given that `cdk watch` is a wrapper around `deploy`, this is a simple matter of passing the `concurrency` option along.

Fixes #21597

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — APPROVED** [review]

**Comment by misterjoshua** [comment]
@TheRealAmazonKendra There is a strange new error from the CI. I'm not sure what could have caused this. I am re-running the build locally to see if I can find an obvious cause.

```
@aws-cdk/integ-runner: Validating circular imports
@aws-cdk/integ-runner: Validating resources
@aws-cdk/integ-runner: Validating attributions
@aws-cdk/integ-runner: Build times for @aws-cdk/integ-runner: Total time (26.7s) | /codebuild/output/src371907408/src/github.com/aws/aws-cdk/node_modules/typescript/bin/tsc (11.8s)
@aws-cdk/integ-runner: $ cdk-test
@aws-cdk/integ-runner: PASS test/runner/integration-tests.test.js
@aws-cdk/integ-runner: PASS test/runner/private/integ-manifest.test.js
@aws-cdk/integ-runner: PASS test/runner/integ-test-suite.test.js
@aws-cdk/integ-runner: PASS test/runner/private/cloud-assembly.test.js
@aws-cdk/integ-runner: PASS test/runner/snapshot-test-runner.test.js
@aws-cdk/integ-runner: PASS test/runner/integ-test-runner.test.js
@aws-cdk/integ-runner: FAIL test/workers/integ-worker.test.js
@aws-cdk/integ-runner:   â— test runner â€º has snapshot
@aws-cdk/integ-runner:     expect(received).toEqual(expected) // deep equality
@aws-cdk/integ-runner:     - Expected  - 1
@aws-cdk/integ-runner:     + Received  + 6
@aws-cdk/integ-runner:     - Array []
@aws-cdk/integ-runner:     + Array [
@aws-cdk/integ-runner:     +   Object {
@aws-cdk/integ-runner:     +     "discoveryRoot": "test/test-data",
@aws-cdk/integ-runner:     +     "fileName": "test/test-data/xxxxx.test-with-snapshot.js",
@aws-cdk/integ-runner:     +   },
@aws-cdk/integ-runner:     + ]
@aws-cdk/integ-runner:       150 |     ]));
@aws-cdk/integ-runner:       151 |
@aws-cdk/integ-runner:     > 152 |     expect(results).toEqual([]);
@aws-cdk/integ-runner:           |                     ^
@aws-cdk/integ-runner:       153 |   });
@aws-cdk/integ-runner:       154 |
@aws-cdk/integ-runner:       155 |   test('deploy failed', () => {
@aws-cdk/integ-runner:       at Object.<anonymous> (test/workers/integ-worker.test.ts:152:21)
@aws-cdk/integ-runner: PASS test/workers/snapshot-worker.test.js
@aws-cdk/integ-runner: =============================== Coverage summary ===============================
@aws-cdk/integ-runner: Statements   : 81.1% ( 571/704 )
@aws-cdk/integ-runner: Branches     : 71.94% ( 377/524 )
@aws-cdk/integ-runner: Functions    : 81.1% ( 103/127 )
@aws-cdk/integ-runner: Lines        : 81.21% ( 549/676 )
@aws-cdk/integ-runner: ================================================================================
@aws-cdk/integ-runner: Test Suites: 1 failed, 7 passed, 8 total
@aws-cdk/integ-runner: Tests:       1 failed, 63 passed, 64 total
@aws-cdk/integ-runner: Snapshots:   0 total
@aws-cdk/integ-runner: Time:        4.398 s
@aws-cdk/integ-runner: Ran all test suites.
@aws-cdk/integ-runner: Error: /codebuild/output/src371907408/src/github.com/aws/aws-cdk/node_modules/jest/bin/jest.js exited with error code 1
@aws-cdk/integ-runner: Tests failed. Total time (5.4s) | /codebuild/output/src371907408/src/github.com/aws/aws-cdk/node_modules/jest/bin/jest.js (5.4s)
@aws-cdk/integ-runner: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@aws-cdk/integ-runner: error Command failed with exit code 1.
@aws-cdk/integ-runner: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@aws-cdk/integ-runner: error Command failed with exit code 1.
@aws-cdk/integ-runner: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build+test exited 1 in '@aws-cdk/integ-runner'
```

**Comment by misterjoshua** [comment]
@TheRealAmazonKendra I see that in #20149, @skinny85 had the exact same error. You may be right that this is a transient issue. A retry may fix the problem.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio requeue

**Comment by TheRealAmazonKendra** [comment]
We've seen a bit of this error and I'm not sure what the cause is, but it's definitely not your change so let's see if this corrects itself on update.

**Pull request merged**
