### PR TITLE
feat(lambda): Migrate away from NODEJS_10_X and NODEJS_12_X to NODEJS_14_X

### LINKED ISSUE #19992: custom_resources: Node version 12 out of support
### Describe the bug

custom_resources builds a NodeJs lambda @ v12 of node which is out of support in 11 days.

### Expected Behavior

custom_resources should track LTS

### Current Behavior

tracks maintenance/deprecated version

### Reproduction Steps

use module

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

all

### Framework Version

all

### Node.js Version

12

### OS

all

### Language

Typescript

### Language Version

3.8.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by robertd**
Screen Shot 2022-06-01 at 9 08 18 PM

Closes #20568
Closes #19992
Closes #20474

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
This is a very chunky PR 🤣

- Migrated away (tests, docs, internal use) from NODEJS_10_X to NODEJS_16_X
- Migrated away (tests, docs, internal use) from NODEJS_12_X to NODEJS_16_X
- Migrated away (tests, docs, internal use) from NODEJS_14_X to NODEJS_16_X
- Added `nodejs16` to CustomResources
- Updated integration tests across the board. Some integ tests introduced destructive changes (expected with change of nodejs runtime)

P.S. See you again when `nodejs20.x` becomes a thing 🤣 
P.S.S. I need an extra pair of eyes on this PR since it touched too many modules at once (cc @pahud @jogold @rix0rrr)

**Comment by robertd** [comment]
Affected packages

```bash
@aws-cdk-containers/ecs-service-extensions
@aws-cdk/aws-amplify
@aws-cdk/aws-apigateway
@aws-cdk/aws-apigatewayv2-authorizers
@aws-cdk/aws-apigatewayv2-integrations
@aws-cdk/aws-appsync
@aws-cdk/aws-autoscaling-hooktargets
@aws-cdk/aws-chatbot
@aws-cdk/aws-cloudformation
@aws-cdk/aws-cloudfront
@aws-cdk/aws-cloudtrail
@aws-cdk/aws-codedeploy
@aws-cdk/aws-codepipeline-actions
@aws-cdk/aws-cognito
@aws-cdk/aws-config
@aws-cdk/aws-dynamodb-global
@aws-cdk/aws-dynamodb
@aws-cdk/aws-ec2
@aws-cdk/aws-ecs
@aws-cdk/aws-eks
@aws-cdk/aws-events-targets
@aws-cdk/aws-globalaccelerator-endpoints
@aws-cdk/aws-glue
@aws-cdk/aws-iam
@aws-cdk/aws-iot-actions
@aws-cdk/aws-iot
@aws-cdk/aws-iotevents-actions
@aws-cdk/aws-kinesisfirehose-destinations
@aws-cdk/aws-kinesisfirehose
@aws-cdk/aws-lambda-destinations
@aws-cdk/aws-lambda-event-sources
@aws-cdk/aws-lambda-nodejs
@aws-cdk/aws-lambda-python
@aws-cdk/aws-lambda
@aws-cdk/aws-logs-destinations
@aws-cdk/aws-logs
@aws-cdk/aws-msk
@aws-cdk/aws-opensearchservice
@aws-cdk/aws-rds
@aws-cdk/aws-redshift
@aws-cdk/aws-route53-targets
@aws-cdk/aws-route53
@aws-cdk/aws-s3-deployment
@aws-cdk/aws-s3-notifications
@aws-cdk/aws-s3
@aws-cdk/aws-s3objectlambda
@aws-cdk/aws-secretsmanager
@aws-cdk/aws-ses-actions
@aws-cdk/aws-ses
@aws-cdk/aws-sns-subscriptions
@aws-cdk/aws-stepfunctions-tasks
@aws-cdk/cloudformation-include
@aws-cdk/core
@aws-cdk/custom-resources
@aws-cdk/integ-runner
@aws-cdk/integ-tests
@aws-cdk/lambda-layer-awscli
@aws-cdk/pipelines
@aws-cdk/triggers
aws-cdk-lib
aws-cdk
```

**Review by jogold — APPROVED** [review]
Nice!

(maybe check that nodejs16.x is available in all regions)

**Comment by robertd** [comment]
> Nice!
> 
> (maybe check that nodejs16.x is available in all regions)

@jogold 
> The Node.js 16 runtime is available in all [Regions where Lambda is available](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/), except for the AWS China Region (Beijing) Region, operated by Sinnet and AWS China (Ningxia) Region, operated by NWCD"s.

**Comment by rix0rrr** [comment]
> The Node.js 16 runtime is available in all [Regions where Lambda is available](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/), except for the AWS China Region (Beijing) Region, operated by Sinnet and AWS China (Ningxia) Region, operated by NWCD"s.

Oh oops. This is a bit of a blocker. We can't really afford to break Chinese (or GovCloud) customers 😔

**Comment by robertd** [comment]
@rix0rrr Got it. We can put this PR in the backlog and revisit it once GovCloud and Chinese regions catch up.

**Comment by robertd** [comment]
It looks like `main` replaced `master` branch in the meantime... I'll have to update this PR to reflect new origin.

**Comment by robertd** [comment]
I'm planning on starting over on this PR when time permits... to many changes happening at the same time for this PR to stay clean (master to main switchover, yarn-integ updates, nodejs16 to nodejs14 "dowgrade"... etc).

**Comment by alexherriott** [comment]
@robertd  do you know when will node16 support be available? date / release?

**Comment by alexherriott** [comment]
thanks Robert
what mean is when will CDK update all its runtimes to use node16.

**Comment by robertd** [comment]
Ah gotcha… That would be a gigantic PR effort (like this one). Sometime soon I guess :)

**Comment by robertd** [comment]
Also, we need to check and see if nodejs16 is available in all regions.

**Pull request closed without merging**
