### PR TITLE
feat(elasticloadbalancingv2): client keepalive for ALB

### LINKED ISSUE #29503: elasticloadbalancingv2: client keep alive
### Describe the feature

We can configure client keepalive duration for ALB by AWS CDK.

### Use Case

[ALB now supports  configuring HTTP client keepalive duration](https://aws.amazon.com/jp/about-aws/whats-new/2024/03/application-load-balancer-http-keepalive-duration/) but CDK cannot configure that.

### Proposed Solution

_No response_

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.132.0

### Environment details (OS name and version, etc.)

irrelevant

### PR DESCRIPTION
**Pull request by badmintoncryer**
### Issue # (if applicable)

Closes #29503.

### Reason for this change

[ALB supports configuring client keepalive duration](https://aws.amazon.com/jp/about-aws/whats-new/2024/03/application-load-balancer-http-keepalive-duration/) but AWS CDK cannot do that.

### Description of changes

Add `clientKeepAlive` properties to `ApplicationLoadBalancerProps`.

```ts
      new elbv2.ApplicationLoadBalancer(stack, 'LB', {
        vpc,
        clientKeepAlive: Duration.seconds(250),
      });
```

### Description of how you validated changes

I've added both integ and unit tests

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Looks good 👍
Left some suggestions for minor adjustments

**Comment by badmintoncryer** [comment]
@lpizzinidev Thank you for your review! I have adderssed your comments.

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍

**Review by GavinZZ — DISMISSED** [review]
LGTM, thanks for contributing

**Comment by badmintoncryer** [comment]
@GavinZZ Thank you for your review!
Mergify job seems to be failed. Could you please resolve it?

**Comment by badmintoncryer** [comment]
@GavinZZ I have resolved conflict. Could you please re-review this?

**Review by GavinZZ — APPROVED** [review]

**Comment by badmintoncryer** [comment]
@GavinZZ Why does this Mergify job fail? Is there something wrong with how I create my PR?

**Comment by GavinZZ** [comment]
I'm unsure either, will monitor this PR and see the latest error if it happens again.

**Comment by badmintoncryer** [comment]
@GavinZZ Thanks!

**Pull request merged**
