### PR TITLE
fix(custom-resource-handlers): better fallback for require failures

### LINKED ISSUE #30067: (custom-resources): Package does not exist
### Describe the bug

I'm trying to use `AwsCustomResource` from Python for a couple of actions on `@aws-sdk/client-cognito-identity-provider`, and deployment keeps failing with errors like:

```
Received response status [FAILED] from custom resource. Message returned:
Package @aws-sdk/client-cognito-identity-provider does not exist. (RequestId: 99b79a89-1a17-4acf-864c-84b3ac3e5664)
```

### Expected Behavior

The affected resource (see repro steps below) should deploy successfully and create a user in the provided Cognito user pool.

### Current Behavior

I'm getting the above mentioned error message and the resource fails to create (or rollback/delete). Also tried providing the service name as `CognitoIdentityServiceProvider` but this gave the same error message (with `@aws-sdk/client-cognito-identity-provider` package name)

Possibly this may be intermittent, as I managed to get the stack to deploy (update existing to add this resource) at least once? But now facing the error consistently.

### Reproduction Steps

Given Python CDK construct with a resource something like:

```python
AwsCustomResource(
    self,
    "AwsCustomResource-CreateUser",
    on_create=AwsSdkCall(
        action="adminCreateUser",
        parameters={
            "UserPoolId": ...,
            "Username": ...,
            "MessageAction": "SUPPRESS",
            "TemporaryPassword": ...,
        },
        physical_resource_id=PhysicalResourceId.of(
            f"AwsCustomResource-CreateUser-{...}"
        ),
        service="@aws-sdk/client-cognito-identity-provider",
    ),
    on_delete=AwsSdkCall(
        action="adminDeleteUser",
        parameters={
            "UserPoolId": ...,
            "Username": ...,
        },
        service="@aws-sdk/client-cognito-identity-provider",
    ),
    policy=AwsCustomResourcePolicy.from_sdk_calls(
        resources=AwsCustomResourcePolicy.ANY_RESOURCE
    ),
    install_latest_aws_sdk=True,
)
```

...Try to deploy the stack

### Possible Solution

🤷‍♂️

### Additional Information/Context

Originally observed on CDK v1.126.0, so tried upgrading to 2.140.0 but it didn't help.

### CDK CLI Version

2.140.0

### Framework Version

2.140.0

### Node.js Version

20.9.0

### OS

macOS 14.4.1

### Language

Python

### Language Version

Python 3.12.1

### Other information

Seems possibly related to #28005, which was closed due to inactivity but raised against an older CDK version.

### PR DESCRIPTION
**Pull request by glitchassassin**
### Issue # (if applicable)

Closes #30067.

### Reason for this change

Fallback to existing AWS SDK import misses a rare/flaky edge case where the npm install passes, but the subsequent `require` fails

### Description of changes

Fall back to the pre-existing AWS SDK if requiring the latest version fails

### Description of how you validated changes

- Fixed no-op test "installs the latest SDK"
- Added test "falls back to installed sdk if require fails"

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by glitchassassin** [comment]
...and it seems the pr-linter-exception-labeler action may be broken too - it's failing with an error

**Comment by GavinZZ** [comment]
@glitchassassin Thanks for drafting the PR. The CodeBuild CI failed because you updated the custom resource handler file, which means the code hash of the handler file changes. This results in all these integration tests that uses this custom resource when comparing the snapshots.

What you can do is to look at the [build log](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=203a8956-75d7-4db8-b1f5-1750618f848d%2Fbuild.log) and search for `!!!!!!!!`. You should then see a list of failed integration tests. For each failed tests, you can run `yarn integ aws-elasticloadbalancingv2/test/integ.alb.oidc --update-on-failed` (replace the path with the actual test).

**Comment by glitchassassin** [comment]
Thanks Gavin. I ran the integration tests like this and then committed the results:

```bash
yarn integ custom-resources/test/aws-custom-resource/integ.aws-custom-resource.js --disable-update-workflow --update-on-failed
```

I got a SUCCESS message locally for most of them. A few failed with an error similar to this:

```
The stack named LogGroupDefaultTestDeployAssert353EE07A failed to deploy: CREATE_FAILED (The following resource(s) failed to create: [AwsApiCallCloudWatchLogsdescribeResourcePolicies]. ): Response object is too long.
```

I pushed up the changes for the ones that passed, but it looks like CodeBuild is still failing all of those integration tests. Have I missed a step?

**Comment by GavinZZ** [comment]
Prior to running the integ tests, did you run `yarn build` in `npx lerna run build --scope=@aws-cdk/custom-resource-handlers` and `npx lerna run build --scope=aws-cdk-lib` to make sure the correct lambda handler file is used in integ tests?

**Comment by glitchassassin** [comment]
I'm pretty sure I did, but just in case, I re-ran the build and tried the integration tests again. I'm not seeing any differences.

I noticed that on some of them (e.g. aws-elasticloadbalancingv2/test/integ.alb.oidc.js) the build reports "destructive changes" because I provided a different hosted zone/domain name per framework-integ/README.md. I'm not sure how to resolve this.

**Comment by GavinZZ** [comment]
For the breaking changes, using `integ.alb.oidc` test as an example, I saw the `template.json` and `assets.json` are modified manually. That could cause breaking changes.

**Comment by glitchassassin** [comment]
yes, those changes were generated by following these steps to set the hosted zone:

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/framework-integ/README.md#error-for-this-test-you-must-provide-your-own-hostedzoneidhostedzonenamedomainname

**Comment by pahud** [comment]
Hi @glitchassassin 

I'll open your PR branch later today and run the integ tests from my IDE. You can reach out to me on cdk.dev if you need any discussion around the PR contribution. I am more than happy to help.

**Comment by pahud** [comment]
Hi @glitchassassin 

I have created a PR to your branch to update the integ tests
https://github.com/glitchassassin/aws-cdk/pull/2

Can you merge my PR to your branch and this PR should update immediately. Let's see if the CI would pass.

**Comment by pahud** [comment]
OK looks like your PR got new integ error

```
@aws-cdk-testing/framework-integ:   CHANGED    custom-resources/test/aws-custom-resource/integ.aws-custom-resource-dynamodb 1.258s
@aws-cdk-testing/framework-integ:       Resources
@aws-cdk-testing/framework-integ: [~] AWS::Lambda::Function AWS679f53fac002430cb0da5b7982bd22872D164C4C 
@aws-cdk-testing/framework-integ:  â””â”€ [~] Code
@aws-cdk-testing/framework-integ:      â””â”€ [~] .S3Key:
@aws-cdk-testing/framework-integ:          â”œâ”€ [-] 4c349b026f9dadd9a6737d4682c2da3e53101244798442ccec89ee0a0bd96f26.zip
@aws-cdk-testing/framework-integ:          â””â”€ [+] 107e4ea7fe26b0049a79003e5710556207812d452795845039064ba20e7b7d56.zip
@aws-cdk-testing/framework-integ:   CHANGED    custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena 1.381s
@aws-cdk-testing/framework-integ:       Resources
@aws-cdk-testing/framework-integ: [~] AWS::Lambda::Function AWS679f53fac002430cb0da5b7982bd22872D164C4C 
@aws-cdk-testing/framework-integ:  â””â”€ [~] Code
@aws-cdk-testing/framework-integ:      â””â”€ [~] .S3Key:
@aws-cdk-testing/framework-integ:          â”œâ”€ [-] 4c349b026f9dadd9a6737d4682c2da3e53101244798442ccec89ee0a0bd96f26.zip
@aws-cdk-testing/framework-integ:          â””â”€ [+] 107e4ea7fe26b0049a79003e5710556207812d452795845039064ba20e7b7d56.zip
@aws-cdk-testing/framework-integ:   UNCHANGED  custom-resources/test/aws-custom-resource/integ.aws-custom-resource-ssm 1.368s
@aws-cdk-testing/framework-integ:   UNCHANGED  custom-resources/test/aws-custom-resource/integ.invoke-function-payload 1.276s
@aws-cdk-testing/framework-integ:   UNCHANGED  custom-resources/test/aws-custom-resource/integ.cross-account-assumeRole 1.506s
@aws-cdk-testing/framework-integ:   CHANGED    custom-resources/test/aws-custom-resource/integ.aws-custom-resource 1.662s
@aws-cdk-testing/framework-integ:       Resources
@aws-cdk-testing/framework-integ: [~] AWS::Lambda::Function AWS679f53fac002430cb0da5b7982bd22872D164C4C 
@aws-cdk-testing/framework-integ:  â””â”€ [~] Code
@aws-cdk-testing/framework-integ:      â””â”€ [~] .S3Key:
@aws-cdk-testing/framework-integ:          â”œâ”€ [-] 4c349b026f9dadd9a6737d4682c2da3e53101244798442ccec89ee0a0bd96f26.zip
@aws-cdk-testing/framework-integ:          â””â”€ [+] 107e4ea7fe26b0049a79003e5710556207812d452795845039064ba20e7b7d56.zip
```

and

```
@aws-cdk-testing/framework-integ:   CHANGED    aws-synthetics/test/integ.canary-auto-delete-lambda 4.905s
@aws-cdk-testing/framework-integ:       Resources
@aws-cdk-testing/framework-integ: [~] AWS::Lambda::Function AWS679f53fac002430cb0da5b7982bd22872D164C4C 
@aws-cdk-testing/framework-integ:  â””â”€ [~] Code
@aws-cdk-testing/framework-integ:      â””â”€ [~] .S3Key:
@aws-cdk-testing/framework-integ:          â”œâ”€ [-] 746da84b10e215c552e68b6d2061024e4429f0386f43a35ef5e4d2940655692e.zip
@aws-cdk-testing/framework-integ:          â””â”€ [+] 107e4ea7fe26b0049a79003e5710556207812d452795845039064ba20e7b7d56.zip
@aws-cdk-testing/framework-integ:   UNCHANGED  pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step 1.233s
@aws-cdk-testing/framework-integ:   CHANGED    custom-resources/test/aws-custom-resource/integ.aws-custom-resource-vpc 3.48s
@aws-cdk-testing/framework-integ:       Resources
@aws-cdk-testing/framework-integ: [~] AWS::Lambda::Function AWS679f53fac002430cb0da5b7982bd22872D164C4C 
@aws-cdk-testing/framework-integ:  â””â”€ [~] Code
@aws-cdk-testing/framework-integ:      â””â”€ [~] .S3Key:
@aws-cdk-testing/framework-integ:          â”œâ”€ [-] 4c349b026f9dadd9a6737d4682c2da3e53101244798442ccec89ee0a0bd96f26.zip
@aws-cdk-testing/framework-integ:          â””â”€ [+] 107e4ea7fe26b0049a79003e5710556207812d452795845039064ba20e7b7d56.zip
```

You'll need to re-run all the CHANGED integ tests and update all their snapshots.

I can't run all of them for you. Please reach out to me on cdk.dev slack if you need any help I can show you how to do that with a video.

**Comment by glitchassassin** [comment]
not abandoned; still working through integration test issues

**Comment by glitchassassin** [comment]
Cross-posting from the Slack discussion:

I'm not sure there's a good way to test these changes in an integration test, as it's the handler source code that is changing. There is a unit test for the change, but I'm not sure how to force the error in an integration test scenario. Any suggestions, or should I request an exemption?

**Pull request closed without merging**
