### PR TITLE
feat(cli): parallel asset publishing

### LINKED ISSUE #19193: (assets): publish Assets in parallel
### Description

Right now, we publish the Assets serially. This is slow if the customer's App contains many Assets (it's visible with as little Assets as 10).

### Use Case

CDK Apps with many (10+) Assets.

### Proposed Solution

We should switch to publishing the Assets in parallel, instead of serially. The tricky part of this will be making sure the Asset publishing progress messages are handled correctly.

### Other information

_No response_

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by misterjoshua**
Adds parallel asset publishing. In a 60-asset/60-Lambda test project, this change decreases the total hot-swap time from 57 seconds to 18 seconds.

Fixes #19193

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by misterjoshua** [comment]
Here's what publishing looks like on my test project:

**Parallel Asset Publishing (18 seconds)**

https://user-images.githubusercontent.com/644092/158005966-ff40d9e3-543a-45d8-8f21-88b0a9976295.mp4

**Comment by brianfrantz** [comment]
It appears that this change has exposed a race condition when publishing multiple ECS images from a Mac.  It is causing our deployments to fail with:

`[83%] fail: docker login --username AWS --password-stdin https://285872988623.dkr.ecr.us-east-1.amazonaws.com exited with error code 1: Error saving credentials: error storing credentials - err: exit status 1, out: The specified item already exists in the keychain.`

It appears that this issue is caused by a combination of the CDK performing a “docker login” on each published asset, along with specific logic in the docker project for storing credentials in the OSX keychain.

The source code for [docker-credentials-osxkeychain](https://github.com/docker/docker-credential-helpers/blob/master/osxkeychain/osxkeychain_darwin.go#L35) doesn’t update existing OSX keychain entries if present.  Instead it always does a [SecKeychainAddInternetPassword](https://developer.apple.com/documentation/security/1393322-seckeychainaddinternetpassword) call, which fails if the entry is already in the keychain.  That error isn’t caught and handled.  Instead the code attempts to avoid this issue by deleting the entry in the keychain before each add attempt.  This logic works fine for the normal use case of doing a single login and then making multiple authenticated docker calls (single-threaded or in parallel).  In fact, the logic has been in place for five-plus years.

Unfortunately, the [CDK calls “docker login” before each “docker push” call](https://github.com/aws/aws-cdk/blob/master/packages/cdk-assets/lib/private/handlers/container-images.ts#L19) instead of once for the batch.  Two publish calls started at the same time will (most of the time) result in a credentials sequence of “delete, delete, add, add” such that the second add will fail because the first add created the entry.

The best method for fixing this issue in the CDK would involve refactoring the publishing code to perform a single “docker login” for the batch of container assets.  Unfortunately this would be a significant redesign as the logic is shared between lambda assets and container assets.

Another option might be to catch the failed login and try again after a small delay, with or without detecting the specific error message.  This doesn’t feel super clean, but is less effort and is less likely to cause side effects.  That said, while it should work fine for small numbers of container assets, it may become problematic when there are many publish calls all logging in and retrying all at once.

**Comment by misterjoshua** [comment]
> Unfortunately, the [CDK calls “docker login” before each “docker push” call](https://github.com/aws/aws-cdk/blob/master/packages/cdk-assets/lib/private/handlers/container-images.ts#L19) instead of once for the batch. Two publish calls started at the same time will (most of the time) result in a credentials sequence of “delete, delete, add, add” such that the second add will fail because the first add created the entry.
> 
> The best method for fixing this issue in the CDK would involve refactoring the publishing code to perform a single “docker login” for the batch of container assets. Unfortunately this would be a significant redesign as the logic is shared between lambda assets and container assets.

I wonder whether we could track logins [here](https://github.com/aws/aws-cdk/blob/master/packages/cdk-assets/lib/private/docker.ts#L66) so we can only run `docker login` the first time login is called for a given endpoint. cc @rix0rrr any ideas?

**Comment by mitchlloyd** [comment]
This is blocking my upgrade to CDK 2. Is there a workaround for this issue? If not, perhaps this change could be rolled back until it's fixed?

**Comment by misterjoshua** [comment]
@mitchlloyd @brianfrantz I've created a dedicated bug report issue to track this issue: [#20116](https://github.com/aws/aws-cdk/issues/20116)

I've also proposed a change that seems to resolve this problem on a mac I can access. [#20117](https://github.com/aws/aws-cdk/pull/20117). It would benefit from your review and testing.

**Pull request merged**
