### PR TITLE
fix(cli): remove --role-arn option from global and make it available to the commands that require it

### LINKED ISSUE #17150: (cdk): diff ignores --role-arn
### What is the problem?

`cdk --role-arn arn:aws:iam::123:role/xxx diff` still tries to assume the default `cdk-hnb659fds-deploy-role-123-us-xxx` role. We want to use custom limited roles and this limitation means we are forced to give `diff` users full access to target accounts with the deploy role.

I believe the problem is with this line:

https://github.com/aws/aws-cdk/blob/74776f393462f7e7d23cb1953ef786a823adc896/packages/aws-cdk/lib/cdk-toolkit.ts#L104

It needs to pass along `args.roleArn` to [`prepareSdkFor()`](https://github.com/aws/aws-cdk/blob/74776f393462f7e7d23cb1953ef786a823adc896/packages/aws-cdk/lib/api/cloudformation-deployments.ts#L255) just like `bootstrap` and `deploy` commands do. 

### Reproduction Steps

Setup a profile that cannot assume the deploy role, but can assume another role that has access to read stacks (`xxx` in this example). Use:

```
cdk --role-arn arn:aws:iam::123:role/xxx diff
```

### What did you expect to happen?

I would expect CDK to assume the role I asked it to assume and successfully print a diff.

### What actually happened?

```
Could not assume role in target account using current credentials (which are for account 123) User: arn:aws:sts::123:assumed-role/instance-role/i-123 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123:role/cdk-hnb659fds-deploy-role-123-us-west-2 . Please make sure that this role exists in the account. If it doesn't exist, (re)-bootstrap the environment with the right '--trust', using the latest version of the CDK CLI.
```

### CDK CLI Version

1.129.0

### Framework Version

1.121.0

### Node.js Version

16.12.0

### OS

macOS Big Sur

### Language

Python

### Language Version

3.8

### Other information

Also reported on StackOverflow https://stackoverflow.com/questions/68422581/cdk-diff-with-read-only-permissions-what-is-a-good-way

### PR DESCRIPTION
**Pull request by ntachukwu**
`cdk --role-arn` is a global option which means it shows up as an option for every command, which isn't accurate.

The option should only be available for `cdk bootstrap`, `cdk deploy`, `cdk import`, `cdk watch` and `cdk destroy`

closes aws/aws-cdk-cli#634 

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by comcalvi — COMMENTED** [review]
before I approve this, can you explain why `role-arn` isn't used in `cdk diff` @peterwoodworth?

**Comment by peterwoodworth** [comment]
@comcalvi [according to Cory](https://github.com/aws/aws-cdk/issues/17150#issuecomment-1172300893):

> cdk diff now assumes the lookup bootstrap role which has read only permissions

I wasn't able to find where in the code that occurred though, but I can verify that passing in a dummy role still successfully executes diff.

Additionally, the way `--role-arn` works for `deploy` and `destroy` is that it gets passed to the API calls `createChangeSet` or `DeleteStack`. `diff` uses `describeStacks` which has no option to pass a role

**Comment by peterwoodworth** [comment]
Also do you know if we have tests for our CLI commands?

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
I've run this through our test pipeline and it succeeded and I'll exempt integ tests, but we do have unit tests for our CLI so this should be tested there.

**Pull request closed without merging**
