### PR TITLE
feat(servicediscovery): add L2 constructs

### PR DESCRIPTION
**Pull request by jogold**
This is a proposal for L2 constructs for `aws-servicediscovery`.

The main idea is that there's only one `Namespace` construct that generalizes the HTTP, Public DNS and Private DNS namespaces. The `Service` and `Instance` constructs offer validation based on the namespace type and an easier API than the CF one.

Tests and docs are missing. This is a WIP but I would be glad to have a first review on the implementation.

The ultimate goal is to provide service discovery integration for ECS/Fargate (need this in my projects).

PS: I'm new here and still discovering the code base, guidelines and standards.

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by eladb** [comment]
@SoManyHs @rix0rrr can you guys shepherd this?

**Comment by rix0rrr** [comment]
Thanks for the work @jogold!

Unfortunately, your submission of this change happens to coincide with some work on our end on the same L2 library. We're going to have a look and try to merge them to get the best of both worlds.

In the mean time, I'd hate to see you put in a lot of effort trying to get this PR to build if we're not going to merge it wholesale anyway. Please stay tuned, we're on it!

**Comment by jogold** [comment]
OK, got it. Thanks for the feedback.

PS: it's not building due to the dev dependency added on elbv2 needed in my tests. The rest should be fine.

**Comment by eladb** [comment]
Hey, this is going to be superseded by #1804. Closing for now. Would love your feedback on that PR.

**Comment by jogold** [comment]
OK, I will have look at it.

**Comment by eladb** [comment]
Thanks so much!

**Pull request closed without merging**
