### PR TITLE
fix(custom-resources): corrected the AWS SDK v2 to v3 mapping for memorydb service.

### LINKED ISSUE #31755: (custom-resources): Package @aws-sdk/client-memory-db does not exist
### Describe the bug

I'm using ` AwsCustomResource` from typescipt to perform an `AwsSdkCall`
with the memorydb service. I set the `AwsSdkCall.service` to be '@aws-sdk/client-memorydb' when creating the custom resource. However this server gets incorrectly mapped to  '@aws-sdk/client-memory-db' for which no package exists. 

This causes the deployment of the custom resource to fail. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

The custom resource should deploy successfully

### Current Behavior

The deployment fails with error message from the lambda
`Error: Package @aws-sdk/client-memory-db does not exist.`
 at qe (/var/task/index.js:1:125653)
    at Object.De (/var/task/index.js:1:126372)
    at le (/var/task/index.js:1:127784)
    at Runtime.He [as handler] (/var/task/index.js:1:127887)
    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)

### Reproduction Steps

Use this custom resource construct to reproduce

```
new AwsCustomResource(this, 'UpdateCluster', {
      timeout: cdk.Duration.minutes(1),
      installLatestAwsSdk: false,
      onUpdate: {
        service: '@aws-sdk/client-memorydb',
        action: 'UpdateCluster',
        parameters: {
          ClusterName: <REPLACE_WITH_MEMORYDB_CLUSTER_NAME>,
          Engine: 'valkey',
        },
        physicalResourceId: PhysicalResourceId.of(`${id}-${this.node.addr.slice(0, 16)}`),
      },
      policy: AwsCustomResourcePolicy.fromStatements([
        new cdk.aws_iam.PolicyStatement({
          effect: cdk.aws_iam.Effect.ALLOW,
          actions: ['memorydb:UpdateCluster'],
          resources: ['*'],
        }),
      ]),
    });
  }
```

### Possible Solution

The entry here https://github.com/aws/aws-cdk/blob/78a7182c2a262fe4f635deb103be8757e5a20efc/packages/%40aws-cdk/aws-custom-resource-sdk-adapter/lib/sdk-v2-to-v3.json#L94
appears to be incorrect. The package name  in AWS Javascript SDK v3 for MemoryDB is " @aws-sdk/client-memorydb" and not
"@aws-sdk/client-memory-db"
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/memorydb/

### Additional Information/Context

_No response_

### CDK CLI Version

2.155.0

### Framework Version

_No response_

### Node.js Version

v20

### OS

MacOSX

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ashishdhingra**
### Issue # (if applicable)

Closes #31755.

### Reason for this change
Per [MemoryDBClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/memorydb/), the service name is `memorydb` (not `memory-db`) with package name as `@aws-sdk/client-memorydb`. However, `sdk-v2-to-v3.json` is using wrong `v3` service name for `memorydb`, which is causing failure to load package. Refer https://github.com/aws/aws-cdk/issues/31755#issuecomment-2414930902 for more details.

### Description of changes
Corrected the mapping for `v3` service name for `memorydb` in the `sdk-v2-to-v3.json`. Unsure if `packages/aws-cdk-lib/custom-resources/lib/helpers-internal/sdk-v2-to-v3.json` is used now, but modifying it anyway.

### Description of how you validated changes
N/A

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by comcalvi — CHANGES_REQUESTED** [review]
Please add an integration test for this one that uses the reproduction: https://github.com/aws/aws-cdk/issues/31755

**Comment by ashishdhingra** [comment]
> Please add an integration test for this one that uses the reproduction: #31755

@comcalvi Added integration test for AWS customer resource for `memorydb` service. I rebased from `main`, now integration tests are failing with changed snapshots. Please advise.

**Comment by ashishdhingra** [comment]
Looks like the below files are auto-generated from [scripts/update-sdkv3-parameters-model.ts](https://github.com/aws/aws-cdk/blob/f9d6eefd52d5bdc63ff2be844f567e8f1d0b4258/scripts/update-sdkv3-parameters-model.ts#L96-L98):
- [packages/@aws-cdk/aws-custom-resource-sdk-adapter/lib/sdk-v2-to-v3.json](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-custom-resource-sdk-adapter/lib/sdk-v2-to-v3.json)
- [packages/aws-cdk-lib/custom-resources/lib/helpers-internal/sdk-v2-to-v3.json](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/custom-resources/lib/helpers-internal/sdk-v2-to-v3.json)

Need to figure out how to correct the mapping.

**Comment by ashishdhingra** [comment]
Abandoning this PR in favor of https://github.com/aws/aws-cdk/pull/31874.

**Pull request closed without merging**
