### PR TITLE
feat(ecs): add function to grant run permissions to task definition

### PR DESCRIPTION
**Pull request by jusdino**
Adding a `grantRun(IGrantable)` method to `aws-ecs.TaskDefinition` to make it easier to set up permissions for running task definitions. I'm not super familiar with the case where `executionRole` is undefined, but I believe leaving that role off the PolicyStatement is the best behavior in that case. Hopefully somebody can sanity check me there. This method is a touch more complicated than I initially planned so it can gracefully handle the case where `.addContainer()` causes `executionRole` to be created _after_ a `grantRun()` was already called (this case is included in the new tests).

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thank you for your contribution. This change requires a README change. Also, please ensure the PR title and body follow our [pull request guidelines](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md#step-4-pull-request) in our Contributing Guide.

**Review by TheRealAmazonKendra — DISMISSED** [review]
@jusdino Looks like the build is failing due to the spacing in the README. Also, please allow us to push to your branch or mergify will not be able to rebase and merge this once it's approved.

**Comment by jusdino** [comment]
> Also, please allow us to push to your branch or mergify will not be able to rebase and merge this once it's approved.
So I have not figured out how to allow that when opening a pull request from my org into another. Would you happen to know or have a reference I can go look at?

**Review by TheRealAmazonKendra — DISMISSED** [review]

**Comment by TheRealAmazonKendra** [comment]
> > Also, please allow us to push to your branch or mergify will not be able to rebase and merge this once it's approved.
> 
> So I have not figured out how to allow that when opening a pull request from my org into another. Would you happen to know or have a reference I can go look at?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by jusdino** [comment]
> > > Also, please allow us to push to your branch or mergify will not be able to rebase and merge this once it's approved.
> > 
> > 
> > So I have not figured out how to allow that when opening a pull request from my org into another. Would you happen to know or have a reference I can go look at?
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Well, shoot. That is specifically for *user-owned forks*, which this is not. I guess, if I can't allow you to push to my branch on an *organization-owned fork*, I'll have to make sure to fork to my personal user in the future. Does this prevent you from merging this PR? I'm trying to keep updating the branch fairly frequently in the meantime.

**Comment by jusdino** [comment]
Yeah, @TheRealAmazonKendra, it looks like I can't let you push back to my branch in the org-owned fork so I did as you suggested and opened a new PR from a personal fork.

**Pull request closed without merging**
