### PR TITLE
chore: add condition to bootstrap file publish role

### PR DESCRIPTION
**Pull request by scanlonp**
Adds a condition to restrict s3 permissions on the file publish role.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by scanlonp** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
Submitted to CLI pipeline

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks right. Approving pending test pipeline success. I've added the do-not-merge label in the meantime. Feel free to remove once we've verified all the test results.

**Comment by scanlonp** [comment]
Succeeding in the test pipeline.

**Comment by scanlonp** [comment]
@Mergifyio update

**Pull request merged**
