### PR TITLE
test(autoscaling): add tests for Schedule.cron specifying with either day or weekday

### PR DESCRIPTION
**Pull request by go-to-k**
I was trying to fix [this bug](https://github.com/aws/aws-cdk/issues/27256), but [this revert PR](https://github.com/aws/aws-cdk/pull/27284) could cover it.

So I added the test cases for the bug fix.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — APPROVED** [review]
Nice 👍

**Comment by TheRealAmazonKendra** [comment]
A PR just adding test cases? Yesssssss!

**Review by TheRealAmazonKendra — APPROVED** [review]

**Comment by go-to-k** [comment]
@TheRealAmazonKendra 

`Queue: Embarked in merge queue` was failed. Can you handle this?

**Comment by scanlonp** [comment]
@Mergifyio update

**Review by vinayak-kukreja — APPROVED** [review]
Thank you for your contribution. Apologies for the delay in merging this PR.

**Pull request merged**
