### PR TITLE
feat(pipelines): temporarily disable self-mutation

### PR DESCRIPTION
**Pull request by tomas-mazak**
The self-mutation feature of the `CdkPipeline` might at times get in the way of the pipeline development workflow. Each change to the pipeline must be pushed to git, otherwise, after the pipeline was updated using `cdk deploy`, it will automatically revert to the state found in git.

To make the development more convenient, the self-mutation feature can be turned off temporarily, by passing `selfMutating: false` property, example:

```ts
const pipeline = new CdkPipeline(this, 'Pipeline', {
  selfMutating: false,
  ...
});
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
I see the use for disabling updatePipeline, but what's your use case for disabling dependent stacks?

We need that autoselect feature to deploy support stacks.

**Comment by tomas-mazak** [comment]
Yeah, that use-case for not updating dependent stacks might not be that strong, I've experienced an issue when I was working on the dependent stack (did not change to the pipeline itself), deploying from my laptop, but the pipeline always reverted the stack to the "git" version... I thought that being able to provide `--exclusively` param would be helpful then, but now thinking about it, simply disabling the UpdatePipeline stage would do as well.

Anyways, I still think the ability to disable self-mutation while developing would be really useful. If you agree with that but not happy with this approach, I am happy to implement it differently, for example by exposing a boolean flag, like `disableSelfMutation` or so. What do you think?

**Comment by rix0rrr** [comment]
Let's do:

```ts
  /**
   * Whether the pipeline will update itself
   *
   * This needs to be set to `true` to allow the pipeline to reconfigure
   * itself when assets or stages are being added to it, and `true` is the
   * recommended setting.
   *
   * You can temporarily set this to `false` while you are iterating 
   * on the pipeline itself and prefer to deploy changes using `cdk deploy`.
   *
   * @default true
   */
  readonly selfMutating?: boolean;
```

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Provided feedback in a comment, need to hit "Request changes" to remove this from my TODO list :).

**Comment by tomas-mazak** [comment]
@rix0rrr thanks for the feedback! I've update the PR in accordance with your suggestions, could you please have a look? I've updated he PR title and description too, for context, I am copying the old description below:

---

Currently, the `UpdatePipeline` stage is created inside the `CdkPipeline` class code and cannot be customized in any way. However, there are use cases where it might be useful to have more control over this stage, for example:

* adding `--exclusively` argument to the `cdk deploy` command, to ensure dependent stacks are not updated by UpdatePipeline stage
* making the UpdatePipeline stage no-op while developing the pipeline (otherwise every change needs to be pushed to git, as this stage updates the pipeline to the version found in git by default)

This PR exposes the `updatePipelineAction` in a similar way as `sourceAction` or `synthAction` are exposed.

Example:

```ts
const cdkPipeline = new CdkPipeline(this, 'CdkPipeline', {
  pipelineName: 'MyPipeline',
  cloudAssemblyArtifact,
  sourceAction: new codepipeline_actions.GitHubSourceAction(...),
  synthAction: SimpleSynthAction.standardNpmSynth(...),
  updatePipelineAction: new UpdatePipelineAction(nestedPipelineStack, 'UpdatePipeline', {
      cloudAssemblyInput: cloudAssemblyArtifact,
      pipelineStackName: pipelineStack.stackName,
      buildCommands: [`cdk -a . deploy ${pipelineStack.stackName} --require-approval=never --verbose --exclusively`],
  }),
});
```

**Review by rix0rrr — APPROVED** [review]

**Comment by stephankaag** [comment]
@tomas-mazak @rix0rrr Is it expected behavior that `selfMutating` can not be re-enabled after being disabled?

When the SelfMutate stage is gone, the stage is not added again when `selfMutating` is set to `true` again. This because the pipeline no longer updates itself :-) 

Not sure if that is as intended?

**Comment by tomas-mazak** [comment]
> @tomas-mazak @rix0rrr Is it expected behavior that `selfMutating` can not be re-enabled after being disabled?
> 
> When the SelfMutate stage is gone, the stage is not added when `selfMutating` is set to `true` again. This because the pipeline no longer updates itself :-)
> 
> Not sure if that is as intended?

Not sure how it could work otherwise :) To re-enable, it, after setting it back to `selfMutating: true`, you need to update the pipeline from outside (typically using `cdk deploy`) and from then on, it will become self-mutating again. Bottom line is that you should only use that setting if you have a specific use-case for it (for me it is to be able to iterate faster over the pipeline when developing).

**Pull request merged**
