### PR TITLE
fix(eks): update private ecr repo url regex

### PR DESCRIPTION
**Pull request by natekruse-aws**
### Reason for this change

The regex for private ECR repos currently excludes some supported URLs in AWS regions. Updating the regex to be more inclusive of all AWS regions.

### Description of changes

Modified private ECR repo URL to be domain agnostic.

### Description of how you validated changes

All existing tests pass: 
- `npx cdk -a test/aws-eks/test/integ.eks-helm-asset.js deploy --all`
- `yarn test aws-eks`
- `yarn integ --directory test/aws-eks/test`

Manually updated lambda function highside to verify change works in isolated regions as well.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by natekruse-aws** [comment]
Exemption Request

Integ test changes not required due to how small the change is. Existing tests still work.

**Comment by shikha372** [comment]
No change flagged in integration test due to modification in private repo, but there are manual integration steps defined to check for private repo [here](https://github.com/natekruse-aws/aws-cdk/blob/fix-ecr-repo-regex/packages/%40aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.ts#L65).
Also, asked user to add unit tests to verify that this is working for all expected domains.

**Comment by shikha372** [comment]
verified that there is no change in integration snapshot with `yarn integ` under `aws-cdk/packages/@aws-cdk-testing/framework-integ/test`.

Manually verified the changes for private repo with deployment in `us-east-1`
```
// there is no opinionated way of testing charts from private ECR, so there is description of manual steps needed to reproduce:
    // 1. `export AWS_PROFILE=youraccountprofile; aws ecr create-repository --repository-name helm-charts-test/s3-chart --region YOUR_REGION`
    // 2. `helm pull oci://public.ecr.aws/aws-controllers-k8s/s3-chart --version v0.1.0`
    // 3. Login to ECR (howto: https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html )
    // 4. `helm push s3-chart-v0.1.0.tgz oci://YOUR_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/helm-charts-test/`
    // 5. Change `repository` in above test to oci://YOUR_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/helm-charts-test
    // 6. Run integration tests as usual
```

Results: 

Verifying integration test snapshots...

```
  CHANGED    aws-eks/test/integ.eks-helm-asset 1.447s
      Resources
[~] Custom::AWSCDK-EKS-HelmChart Clustercharttestocichart9C188967 
 └─ [~] Repository
     ├─ [-] oci://public.ecr.aws/aws-controllers-k8s/s3-chart
     └─ [+] oci://<account>.dkr.ecr.us-east-1.amazonaws.com/helm-charts-test/s3-chart


Running in parallel across regions: us-east-1, us-east-2, us-west-2
Running test /Users/shikagg/aws-cdk/packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js in us-east-1
  SUCCESS    aws-eks/test/integ.eks-helm-asset-aws-cdk-eks-helm/DefaultTest 1390.33s
       NO ASSERTIONS
```

**Review by shikha372 — APPROVED** [review]

**Comment by shikha372** [comment]
@mergifyio update

**Pull request merged**
