### PR TITLE
[lambda] specify multiple folders as a single lambda asset

### PR DESCRIPTION
**Pull request by ahzia**
Motivation: Right now in order to define a lambda function you need to set where the code resides, e.g. code: lambda.Code.asset('lambda'). Sometimes you would like to define multiple folders, for example, the actual code and node_modules, although packing can be done as a preprocessing step before actually running CDK deploy, it would be cleaner to do it as part of the lambda configuration.
Design aspect:
added a new function `fromMultiAsset` which takes an array of paths and archives it inside a zip file, then it calls AssetCode() and passes this new file.

closes https://github.com/aws/aws-cdk/issues/984
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
I'm sorry, this is not what assets are for, and CDK is not a build tool. If you have a complex asset build step, write a shell script that will assemble your asset from your various source locations into a single directory, then reference that in your CDK app. Either that, or use the [aws-lambda-nodejs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html) module.

**Comment by ahzia** [comment]
> I'm sorry, this is not what assets are for, and CDK is not a build tool. If you have a complex asset build step, write a shell script that will assemble your asset from your various source locations into a single directory, then reference that in your CDK app. Either that or use the [aws-lambda-nodejs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html) module.
Thanks for your reply @rix0rrr
My solution was based on the issue [#984](https://github.com/aws/aws-cdk/issues/984) which is active since 2018 and many people have reached the same issue since then, it was labeled as P1 and feature/enhancement.
kindly take a look at the issue.

**Comment by kellertk** [comment]
@rix0rrr If we don't want to implement this we should close #984 as well.

**Comment by ahzia** [comment]
Closed this and opened a [new Pull for this](https://github.com/aws/aws-cdk/pull/21644):

**Pull request closed without merging**
