### PR TITLE
feat(eks): added support for EKS version 1.28

### PR DESCRIPTION
**Pull request by khushail**
Similar to this (https://github.com/aws/aws-cdk/pull/25897), added support for EKS 1.28

Resolves (https://github.com/aws/aws-cdk/issues/27500)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by cristianmagana** [comment]
@khushail was there an eta for this? Would be interested in contributing if possible.

**Comment by endersonmaia** [comment]
I assume this PR depends on that: https://github.com/cdklabs/awscdk-asset-kubectl/pull/450

**Comment by khushail** [comment]
@endersonmaia ,your assumption is correct.
@cristianmagana , I am done with my PR but would need[ this PR ](https://github.com/cdklabs/awscdk-asset-kubectl/pull/450)to be merged before that.

**Comment by pahud** [comment]
https://github.com/cdklabs/awscdk-asset-kubectl/pull/450 it's merged!

**Comment by dougalrea** [comment]
Is there anything else blocking this? Would be great to get 1.28 support in CDK for those of us needing to migrate away from soon-to-be deprecated versions

**Comment by khushail** [comment]
Exemption Request

**Comment by michelesr** [comment]
If you don't want to be blocked on this you can use `KubernetesVersion.of("1.28")` in your project, and update the kubectl layer, to move your cluster to 1.28.

**Comment by sumupitchayan** [comment]
@khushail can you figure out how to get the build to succeed? Looks like maybe the import statements might be incorrect?

**Comment by khushail** [comment]
> @khushail can you figure out how to get the build to succeed? Looks like maybe the import statements might be incorrect?

Sure, I will take a look.

**Pull request closed without merging**
