### PR TITLE
docs(apigatewayv2): fix incorrect response type enum

### PR DESCRIPTION
**Pull request by Albert-Gao**
@iRoachie 

I think this is the proper type here?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by iRoachie — APPROVED** [review]
Good catch

**Comment by iRoachie** [comment]
To pass the lint. You need to change your PR title from `fix` to `docs`. `fix` expects changes to code and corresponding tests

**Comment by Albert-Gao** [comment]
@iRoachie Thanks! Fixed :)

**Comment by iRoachie** [comment]
cc @nija-at @rix0rrr

**Review by nija-at — APPROVED** [review]
Nice!

Thanks for the PR @Albert-Gao and picking up a review on this @iRoachie 

Approved.

**Pull request merged**
