### PR TITLE
feat(cloudfront): distribution ARN property

### LINKED ISSUE #32530: cloudfront: expose ARN for `Distribution`
### Describe the feature

It would be great if we could get ARN of a [CloudFront distribution L2](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.Distribution.html) construct.

### Use Case

easily get ARN of a distribution.

### Proposed Solution

add `IDistribution.distributionArn` property. We already have a function to calculate it.
https://github.com/aws/aws-cdk/blob/bf026bdd8557305d427510af49f1bc538d439cb6/packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts#L7-L14

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.170.0

### Environment details (OS name and version, etc.)

macOS

### PR DESCRIPTION
**Pull request by nmussy**
### Issue # (if applicable)

Closes #32530

### Reason for this change

Give the user access to a distribution's ARN via the existing `distributionId` value.

### Description of changes

Implemented by proxying the existing `formatDistributionArn` function via a getter method.

### Description of how you validated changes

Unit tests were added for both created and imported distributions.

Additionally, missing coverage for `Distribution.fromDistributionAttributes` was added, by copying the existing unit test for `CloudFrontWebDistribution.fromDistributionAttributes`.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nmussy** [comment]
Exemption Request:
* A unit test should be sufficient, given there is no real added feature, just a getter method that uses an already relied upon function.
* The generated documentation should also be sufficient, adding an example on how to access a property would add needless noise

**Review by tmokmss — APPROVED** [review]
Nice, thanks! 😄

**Comment by tmokmss** [comment]
I found a typo in the PR title btw (`cloudfornt`)

**Comment by nmussy** [comment]
> I found a typo in the PR title btw (`cloudfornt`)

Whoops, thanks. I thought the PR linter checked for existing packages?

**Review by godwingrs22 — APPROVED** [review]
LGTM. Thanks @nmussy for the contribution.

**Pull request merged**
