### PR TITLE
fix(core): bundling skipped with --exclusively option and stacks under stage

### LINKED ISSUE #12898: (aws-cdk): asset bundling skipped when using --exclusively option
Asset bundling is currently broken when using the `--exclusively` option during deploy. 

In our case we have an `aws-lambda-nodejs` with [forceDockerBuild](https://github.com/aws/aws-cdk/blob/98ab29206903a235331a9a0b4b38a5e6ad6d89dc/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L190) set to true (but it shouldn't matter).

However, due to the following check the bundling never happens when e.g. running `cdk deploy --exclusively 'MyStack'` -
as in it will skip the bundling step completely.

Concretely, this minimatch evaluates to `false` for any given stack name, except when using `--all` which evaluates to the wildcard `*` satisfying anything.
https://github.com/aws/aws-cdk/blob/9417b0211eb2939f5a853751333f7941d9dd99f8/packages/%40aws-cdk/core/lib/asset-staging.ts#L164

That is because `Stack.of(this).stackName` is not resolved at this point. The screenshot shows the output of running with `--all` (bundlingStacks contains `[*]`) against the unresolved stack name:

image

Tested on Linux and Windows and CDK 1.88.

--- 

This is :bug: Bug Report

### LINKED ISSUE #15346: (core/aws-lambda-nodejs/cli): confusing NodejsFunction+Stage+exclusive-cli-flag behaviour
When deploying using all of the following, the asset for the Lambda function is a zip of the root of the project, not the asset as expected:

- a stack containing a `@aws-cdk/aws-lambda-nodejs.NodejsFunction` Lambda function
- attaching the stack I'm deploying to a `@aws-cdk/core.Stage` rather than to a `@aws-cdk/core.App`
- using the `-e` (exclusive) flag to the synth or deploy commands

Based on my testing, not doing any one of these things results in the expected behaviour where the asset is the expected thing.

See dummy project here https://github.com/isotoma/cdk-nodejsfunction-asset-size-debugging to show my testing and why I have ended up where I have.

I happened to find this because a real project uploaded the whole project root as the source asset for the Lambda, which ended up being over Lambda's 250MB limit.

### Reproduction Steps

See https://github.com/isotoma/cdk-nodejsfunction-asset-size-debugging, and the branches listed in the readme, and the behaviour shown in the Github CI.

### What did you expect to happen?

- Use of the `-e` CLI flag should not affect the built asset
- Use of a `Stage` should not affect the built asset

### What actually happened?

- I would not expect the whole project directory to ever be zipped and uploaded to the assets bucket.

### Environment

  - **CDK CLI Version  :** 1.110.1 (also affects >= 1.102.0, because that's where the feature to deploy stacks from stages arrived, see https://github.com/aws/aws-cdk/pull/14379. Believe earlier versions did not have this feature.)
  - **Framework Version:** 1.110.1
  - **Node.js Version:**  v14.17.0
  - **OS:** Linux
  - **Language (Version):**  Typescript 4

### Other

I am mildly suspicious of switches in `context` in `cdk.json`, but for no real reason, and have no guesses as to what might actually be wrong.

Happy to try other things with my dummy project if useful.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
We were comparing bundling stacks of the form `Stage/Stack` with stack
names of the form `Stage-Stack`.

For stacks with `NodejsFunction`s this leads to assets containing the whole CDK project because
when bundling is skipped the asset references the source directory which is the project root.

Closes #12898
Closes #15346

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — APPROVED** [review]

**Comment by moltar** [comment]
@jogold you are my hero! Thank you 🙏 we've been pained by this way too long.

**Comment by slaskowski-transactionlink** [comment]
@moltar What i case of glob patterns like `*/Stack1`? It will not work. Also for custom stack names it will be even worse and can break `**/*` deploys if im right

**Comment by slaskowski-transactionlink** [comment]
Ive resolved it locally for once and the issue is that we take `stackName` prop instead of the logical path of stack hence the issue. Please reconsider this solution

**Comment by jogold** [comment]
@slaskowski-transactionlink can you open an issue once this is released with the next version if you still experience problems?

**Comment by slaskowski-transactionlink** [comment]
@jogold cant we just reopen #12898 since its not fixed?

**Comment by jogold** [comment]
> @jogold cant we just reopen #12898 since its not fixed?

I can't reopen issues (no write access to this repo)

How did you test `*/Stack1` with the fix from this PR?

**Comment by slaskowski-transactionlink** [comment]
@jogold ok i created new issue see #17717

**Pull request merged**
