### PR TITLE
chore(codepipeline-actions): change the name of the ServiceCatalogDeployAction

### PR DESCRIPTION
**Pull request by skinny85**
The `ServiceCatalogDeployAction` was an experimental Action in the codepipeline-actions module.
Stabilize it by renaming it `ServiceCatalogDeployActionBeta1`.
Also, remove the unused dependency between this module,
and service catalog module.

BREAKING CHANGE: the Action `ServiceCatalogDeployAction` has been renamed to `ServiceCatalogDeployActionBeta1`
* **codepipeline-actions**: the type `ServiceCatalogDeployActionProps` has been renamed to `ServiceCatalogDeployActionBeta1Props`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by NetaNir — COMMENTED** [review]
@skinny85 thank you so much for leading the way on this! I was thinking that real life example will be the best way to decide on a naming scheme.  

_(summarizing the change in this PR for the sake of discussion)_

There is one preview API introduced in this PR, compose of two parts, the method `ServiceCatalogDeployActionPreview` and it's props that are also named as Preview: `ServiceCatalogDeployActionPreviewProps`. 

In the original RFC we discussed a few requirements for the naming scheme of Preview APIs:
> some relevant discussion [here](https://github.com/aws/aws-cdk-rfcs/pull/279#discussion_r549109242)

1. Should include a version indicator, e.g `xxx1`. This is required so we can introduce additional preview versions before the final version. 
2. Should reflect the experimental nature of the API. The motivation being that while we are not going to introduce a non backward compatible changes, these API are not fully baked, might include bugs and will be deprecated (if only to introduce an identical API under the final name).
3. Minimal "visual noise" (term stolen from @rix0rrr).

Adding all the above and applying it on the `ServiceCatalogDeployAction` API, I can think of a few options, please do add alternatives if any comes to mind:  


1. `ServiceCatalogDeployActionBeta1` - `beta` is a good candidate as it is a widely used term and will resonate with users as a "non final version of the API".  It does however misses on the "visual noise" aspect. 
2. `ServiceCatalogDeployActionX1` - I was on the fence for this one when it was initially suggested, mainly because I thought it will not convey the idea behind the preview APIs concept. But I can see "The AWS CDK X APIs" section in our docs, and it also sound nice, e.g  "What are the X APIs?".  I think this can be less cumbersome than other options both from a coding perspective and "verbal simplicity" (easier to refer to, I can't think of a better way to phrase this.).
3. `ServiceCatalogDeployActionPre1` - Not sure this one actually adds value over `beta`. On one hand, `Pre` is for `Preview`, so it has the advantage of consistency, on the other hand, `Pre` does not have the same "familiar concept" advantage of `beta` . Adding it here in case someone really loves it. 

I think Im leaning towards 2, what do you think?

**Comment by skinny85** [comment]
> In the original RFC we discussed a few requirements for the naming scheme of Preview APIs:
> 
> > some relevant discussion [here](https://github.com/aws/aws-cdk-rfcs/pull/279#discussion_r549109242)
> 
> 1. Should include a version indicator, e.g `xxx1`. This is required so we can introduce additional preview versions before the final version.
> 2. Should reflect the experimental nature of the API. The motivation being that while we are not going to introduce a non backward compatible changes, these API are not fully baked, might include bugs and will be deprecated (if only to introduce an identical API under the final name).
> 3. Minimal "visual noise" (term stolen from @rix0rrr).
> 
> Adding all the above and applying it on the `ServiceCatalogDeployAction` API, I can think of a few options, please do add alternatives if any comes to mind:
> 
> 1. `ServiceCatalogDeployActionBeta1` - `beta` is a good candidate as it is a widely used term and will resonate with users as a "non final version of the API".  It does however misses on the "visual noise" aspect.
> 2. `ServiceCatalogDeployActionX1` - I was on the fence for this one when it was initially suggested, mainly because I thought it will not convey the idea behind the preview APIs concept. But I can see "The AWS CDK X APIs" section in our docs, and it also sound nice, e.g  "What are the X APIs?".  I think this can be less cumbersome than other options both from a coding perspective and "verbal simplicity" (easier to refer to, I can't think of a better way to phrase this.).
> 3. `ServiceCatalogDeployActionPre1` - Not sure this one actually adds value over `beta`. On one hand, `Pre` is for `Preview`, so it has the advantage of consistency, on the other hand, `Pre` does not have the same "familiar concept" advantage of `beta` . Adding it here in case someone really loves it.
> 
> I think Im leaning towards 2, what do you think?

Thanks for the review @NetaNir. I went with option nr 1. I think `ServiceCatalogDeployActionX1` looks weird, and "Beta" is not much more "noise", especially verbally, compared to "X", to justify this more cryptic way of naming.

Submitted a new revision, would appreciate another look!

**Comment by iliapolo** [comment]
I agree that option 3 doesn't really give any additional value. 

As far as the other two, while I do like the sound of CDK `X` API's, I think it's less clear and isn't much of a visual noise reduction over `beta`. So my vote goes for beta as well.

**Comment by NetaNir** [comment]
I agree with the advantage of clarity  for `xxxBeta1`. But, let me try and pitch the X suffix again: I think it sound better, from a "marketing" perspective. It's easier to refer to: "The X APIs". Its disadvantage of not being an industry wide term can also be viewed as an advantage as it means that there will be no assumption made on what does it mean in the context of the AWS CDK, we get to define it.

**Comment by skinny85** [comment]
> I agree with the advantage of clarity for `xxxBeta1`. But, let me try and pitch the X suffix again: I think it sound better, from a "marketing" perspective. It's easier to refer to: "The X APIs". Its disadvantage of not being an industry wide term can also be viewed as an advantage as it means that there will be no assumption made on what does it mean in the context of the AWS CDK, we get to define it.

I actually think "X APIs" sound weird, like we're doing R-rated APIs in CDK 🙂. So I don't see their advantage from a marketing perspective.

Talking about "Beta APIs" seems very natural to me in comparison.

**Comment by NetaNir** [comment]
I can't argue with that. `beta` it is

**Review by NetaNir — APPROVED** [review]

**Pull request merged**
