### PR TITLE
docs(eks): add documentation about add-ons

### PR DESCRIPTION
**Pull request by badmintoncryer**
### Issue # (if applicable)

None

### Reason for this change

Addon L2 construct is added by #30576 but there is no documentation about it in the README.md.

### Description of changes

Add Add-ons documentation to README.md

### Description of how you validated changes

None

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by scanlonp — COMMENTED** [review]
Good find. Not sure why this was not included, maybe because it was an implementation detail for EKS Pod Identity Agent, but probably should be in the readme.

Is there a reason for the location of this section? Just curious how it fits with the other resources.

Also lets add a link to the section from the table of contents.

**Comment by badmintoncryer** [comment]
@scanlonp Thank you for your review! 

> Is there a reason for the location of this section?

There isn't any specific reason, but could you please let me know if there's a more appropriate place for the description?

**Comment by scanlonp** [comment]
I think it's fine where it is. No real preference!

**Review by scanlonp — APPROVED** [review]
Nice add. Thanks!

**Comment by badmintoncryer** [comment]
@mergify update

**Review by scanlonp — APPROVED** [review]

**Pull request merged**
