### PR TITLE
feat(redshift): add missing current generation RA3 NodeTypes

### LINKED ISSUE #12783: (redshift): Missing current generation NodeTypes
I would like to expand the available `NodeTypes` to include all current generation node types.

### Use Case

Deploy any of the available, current generation Redshift node types.

e.g.  `ra3.xplus`

```python
from aws_cdk import aws_redshift as rs
...
cluster = rs.Cluster(
    self, "RedshiftCluster",
    master_user=rs.Login(master_username="someadmin"),
    node_type=rs.NodeType.RA3_XLPLUS,
)

```

### Proposed Solution

Add missing, current generation node types (`ra3.xlplus` & `ra3.4xlarge`) to [cluster.ts@NodeType#L18-47](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-redshift/lib/cluster.ts#L18-L47)

### Other

```
  /**
   * ra3.xlplus
   */
  RA3_XLPLUS = 'ra3.xlplus',
  /**
   * ra3.4xlarge
   */
  RA3_4XLARGE = 'ra3.4xlarge',
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by mbeacom**
Adds the missing Redshift RA3 NodeTypes (ra3.xlplus, ra3.4xlarge).

closes #12783

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mbeacom** [comment]
@njlynch Will this PR require a README.md update or is this similar to the update made in: https://github.com/aws/aws-cdk/pull/12710/ and qualify as `pr-linter/exempt-readme` / `pr-linter/exempt-test` ?

**Review by njlynch — APPROVED** [review]
Thanks for the contribution!

**Comment by mbeacom** [comment]
@njlynch Thank you! It appears the CodeBuild job failures are unrelated to these changes.  If there is anything I can do, please don't hesitate to let me know.

**Review by njlynch — APPROVED** [review]

**Comment by njlynch** [comment]
@Mergifyio refresh

**Pull request merged**
