### PR TITLE
fix(elasticloadbalancerV2): consistent logicalId for addTargetGroups (under feature flag)

### LINKED ISSUE #29496: ElasticLoadBalancerV2: migration to addAction() from addTargetGroups() fails because of logicalId change
### Describe the bug

We need to access functionality not available in the `ApplicationListener.addTargetGroups()` helper method (specifically, `ListenerAction.weightedForward()`). To do this, we've changed from

Old code
```
      this.httpsListener.addTargetGroups(this.serviceRoot, {
        conditions: [ListenerCondition.pathPatterns(this.injectionPaths)],
        priority: this.injectionPriority,
        targetGroups: [this.taskTargetGroup],
      });
```

New code

```
      this.httpsListener.addAction(this.serviceRoot, {
        action: ListenerAction.weightedForward(this.weightedTargetGroups),        
        conditions: [ListenerCondition.pathPatterns(this.injectionPaths)],
        priority: this.injectionPriority,
      });
```

However, when I do a cdk diff of the stack, I get

```
Resources
[-] AWS::ElasticLoadBalancingV2::ListenerRule UsQaQaUsWest26/ClipsServiceInstance/https/--clips-service-v3 httpsclipsservicev36BE2E78C destroy
[+] AWS::ElasticLoadBalancingV2::ListenerRule UsQaQaUsWest26/ClipsServiceInstance/https/--clips-service-v3RuleRule httpsclipsservicev3RuleRule772FC4D6 
```

I note that [https://github.com/aws/aws-cdk/blob/050a305d6be65df7e5f1e17668cbf512ead34d23/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L675-L676 ](https://github.com/aws/aws-cdk/blob/050a305d6be65df7e5f1e17668cbf512ead34d23/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L675-L676) is adding the `Rule` suffix to the logicalId, which is driving a replacement rather than update.

### Expected Behavior

We should be able to go from the helper method to the underlying support method without a logicalId change.

### Current Behavior

Because of the logicalId change, Cfn wants to replace our ListenerRules. Create before destroy means that Cfn tries to create a new ListenerRule with the same priority as the existing ListnerRule, which fails, blocking upgrade path.

### Reproduction Steps

Sigh. 

### Possible Solution

Add a feature flag for not adding the `Rule` suffix to the logicalId in the `addAction()` method.

### Additional Information/Context

_No response_

### CDK CLI Version

2.100.0 (build e1b5c77)

### Framework Version

_No response_

### Node.js Version

20.5.1

### OS

MacOS

### Language

TypeScript

### Language Version

5.3.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ahammond**
Convention is that `ListenerRule`s should have a logicalId with a `Rule` suffix. Follow convention while providing a feature flag to support people who already have resources deployed and need to stick with the legacy naming convention.

### Issue

Closes #29496
Related to PR #29513

### Reason for this change

Going forward, the `logicalId` produced should be consistent.

### Description of changes

Made logicalId consistent by default while providing a feature flag to enable backwards compat for apps which have pre-deployed infra.

### Description of how you validated changes

UTs applied.
`Exemption Request`: ITs are not required per docs

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ahammond** [comment]
`Exemption Request`: ITs are not required for this change, per docs.

**Comment by ahammond** [comment]
I'm not sure if this is considered a Breaking Change or not.

**Comment by TheRealAmazonKendra** [comment]
I think that we need to revert the previous change and combine these two using optional props, not feature flags. If you are defaulting to false, it's generally an indication that the change isn't quite right.

**Comment by TheRealAmazonKendra** [comment]
Alright, we reverted the other one so here are my thoughts on the path forward here. I totally get why you originally went the route that you did but we try to minimize the amount of feature flags we add and adding two here didn't feel right.

Upon looking through your code and this package, I noticed additional inconsistencies. In the `ApplicationListener` class we add `Rule` as a suffix in both `addAction` on line [294](https://github.com/aws/aws-cdk/blame/main/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L294) and in `addTargetGroups` on line  [322](https://github.com/aws/aws-cdk/blame/main/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L322). On the other hand, in the `ExternalApplicationListener` class we do not add `Rule` as a suffix on `addTargetGroups` on line [629](https://github.com/aws/aws-cdk/blame/main/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L629) but we do add it in `addAction` on line [675](https://github.com/aws/aws-cdk/blame/main/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L675).

What I'm thinking is this: what if we add an optional prop to these functions that is something to the extent of `overrideDefaultId`, or maybe something to indicate that it's a migration from on of the other functions, and use that to control whether or not `Rule` is added as a suffix. That way it's not a breaking change, and if nothing is added for that prop then we go with the current default. 

That prop name probably isn't very good, though, so I'm totally open to better names.

What do you think?

**Pull request closed without merging**
