### PR TITLE
feat(cli): `--all` flag to select all stacks

### LINKED ISSUE #3222: feature: cdk deploy --all
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [X] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
The "cdk deploy" command recently stopped deploying all stacks by default, which was often a handy behavior.  You can still pass glob patterns, like '*', to deploy all stacks, but it might be nice to also have an explicit "--all" flag you could pass.  Low priority, since the glob behavior works for this use case, but I suspect many users would expect an explicit "--all" option to be supported in addition to the glob support.

### PR DESCRIPTION
**Pull request by IsmaelMartinez**
Adding the --all option to deploy all stacks.

`cdk deploy --all` 

This is an alias of `*`. The previous command does the same as the following one:

`cdk deploy '*'` 

Closes #3222

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
> Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org). Please adjust title before merge.

Can someone re-trigger this? I have changed twice the title but can't see this triggering. PR should be ready now for review. Thanks

**Comment by Chriscbr** [comment]
I'm wondering if it might be better to have the command error instead if both "--all" and a list of stacks are provided. I feel like this could help catch user errors, considering that this implementation looks slightly different from how some other CLI tool operate (e.g. in Git, if you run `git add --all foo` then only `foo` will be added to your staged files, ignoring the flag).

**Comment by IsmaelMartinez** [comment]
> I'm wondering if it might be better to have the command error instead if both "--all" and a list of stacks are provided. I feel like this could help catch user errors, considering that this implementation looks slightly different from how some other CLI tools operate (e.g. in Git, if you run `git add --all foo` then only `foo` will be added to your staged files, ignoring the flag).
> 
> > Can someone re-trigger this? I have changed twice the title but can't see this triggering. PR should be ready now for review.
> 
> I think the title needs to be update to say "feat" instead of "feature"

Thanks. I will see when I got another bit of time to add the error message. Sounds reasonable.

**Comment by rix0rrr** [comment]
I'm not a big fan of this. We don't need this flag as `cdk deploy \*` already exists (as you yourself noted).

Where's the added benefit?

**Comment by IsmaelMartinez** [comment]
> I'm not a big fan of this. We don't need this flag as `cdk deploy \*` already exists (as you yourself noted).
> 
> Where's the added benefit?

Only created the PR because there is an open ticket. 

Happy to change the PR content to add the unit test for the * (was not existent before) and the documentation (if that is needed), but better also close the ticket also or another person might end up doing the same PR.

**Comment by Chriscbr** [comment]
Only my 2 cents, but the cdk design guidelines suggests:

> It's okay to enable multiple ways to achieve the same thing, in order to make it more natural for users who come from different mental models.

**Comment by IsmaelMartinez** [comment]
Hi @rix0rrr and @Chriscbr,

In my opinion, there are 3 options on this (on order of preference):

1. default to deploying all stacks if no list of stacks is provided. 
2. don't add the `--all` but document it and add unit test to it.
3. add the `--all` and add an exception if the user also provides the flag.
 
In my opinion, it is a bit strange that you need to provide an escaped * as an extra argument (or the list of stack names) if you got more than one stack in an app.

Saying that, it will be a change on functionality but it sort of makes more sense than the current behaviour. It is not that you need to provide your stack name if you only got one.

Let me know if you prefer to put this sort fo conversations in the ticket instead of in the PR. 

Ta

**Review by rix0rrr — DISMISSED** [review]
After having thought on it, I'm willing to accept this.

Please add an input to the CLI that if `--all` is provided, stack names are not allowed (and add a descriptive error message).

**Comment by IsmaelMartinez** [comment]
Hi @rix0rrr and @Chriscbr,

I pushed a few changes. Touched the "destroy" command also as it has the same flow/logic as the deploy and will otherwise work inconsistently.

I checked the `synth`, `list` and `diff` and they don't need the `--all` as that is their default behaviour  (if you don't specify a list of stacks, they just assume all.

Also, do you want me to edit the https://docs.aws.amazon.com/cdk/latest/guide/cli.html github to ensure this is in sync? Not sure if that automatically updates or you have an internal process to do this.

Thanks in advance!

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
