### PR TITLE
fix(s3): urlForObject does not consider explicit bucket region

### PR DESCRIPTION
**Pull request by cjihrig**
This commit updates `urlForObject()` to use the bucket's region instead of the stack's region when constructing the returned URL.

Fixes https://github.com/aws/aws-cdk/issues/14149

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by cjihrig** [comment]
Friendly ping @iliapolo.

**Review by peterwoodworth — COMMENTED** [review]
Thank you for submitting this PR! It looks good to me, however I haven't had the time to fully verify that it works. I'll get to that on Monday and assuming the PR is good I'll merge it then.

**Review by iliapolo — APPROVED** [review]
Looks good. @peterwoodworth I've added `do-not-merge` in case you still want to verify something here. Feel free to remove the label and let it merge.

**Review by peterwoodworth — APPROVED** [review]

**Comment by peterwoodworth** [comment]
Yup! it's good. Thank you for the contribution @cjihrig 😄

**Pull request merged**
