### PR TITLE
fix(secretsmanager): Secret requires KMS key for some same-account access

### PR DESCRIPTION
**Pull request by kaiz-io**
Fix for #15450 Previous code did not check if the account IDs were the different. This checks if CDK is able to resolve the account ids and they are different then fail otherwise let the user create a secret.

FYI first PR. Let me know if there is something that I missed.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by njlynch — DISMISSED** [review]
Thanks for the contribution, @kaizio !

The change itself looks good -- I think -- however, there are quite a bit of unintentional formatting changes that make it unclear what exactly has changed. Can you please clean up the diff so only the new/changed lines are present?

**Comment by kaizio** [comment]
Got it fixed @njlynch Thanks. Had a bad merge trying to bring some upstream changes in.

**Review by njlynch — DISMISSED** [review]
Looks good. I thought there was at least one test before though. Then again, that might have just be odd formatting. Can you please add a test for this new behavior?

**Comment by kaizio** [comment]
Added two test and renamed the one that was there before. I am testing for grant read without any KMS and one where I am using a different account. Is the way that I am overwriting the "stack" correct? Hard to find an example with search.

**Review by njlynch — APPROVED** [review]
Looks good!

**Pull request merged**
