### PR TITLE
chore(custom-resource): Using NODEJS_18_X with AwsCustomResource

### LINKED ISSUE #23989: (custom_resources.AwsCustomResource): Upgrade Node 14 to Node 16
### Describe the bug

When using AwsCustomResource, it uses NODEJS_14_X, but that is End-of-life in a few months: 2023-04-30

### Expected Behavior

I would expect the CDK to use a supported version of Node. 

### Current Behavior

In my case, I am using CDK to generate the Cognito user client secret, which internally uses AwsCustomResource:

https://github.com/aws/aws-cdk/blob/v2-release/packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts#L449

### Reproduction Steps

Use AwsCustomResource directly or any code that relies on it.

### Possible Solution

I suggest that it is upgraded to NODEJS_16_X.

### Additional Information/Context

_No response_

### CDK CLI Version

v2.63.0

### Framework Version

_No response_

### Node.js Version

16

### OS

Linux

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by WinterYukky**
Details will be given in due course.

Closes #23989.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by MrArnoldPalmer** [comment]
So unfortunately, we can't accept this as is. There are some regions that Node18 runtimes aren't available yet, notably China and GovCloud. We are working on building something to select the default runtime version based on the current region to address this. Thank you for the contribution though. If you're interested in setting up that region check mechanism, definitely reopen this PR otherwise I'll probably work on something later this week.

**Comment by WinterYukky** [comment]
Thanks for replying @MrArnoldPalmer .  
I will gladly accommodate the region check mechanism. However, I can’t  reopen this PR (permissions problem?), so I will open new same PR! Thank you.

**Comment by ArielPrevu3D** [comment]
Is there any way to revive this PR? China and GovCloud supports Node 18 as of April 12th.

https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-node-js-18-govcloud-regions/
https://www.amazonaws.cn/en/new/2023/amazon-lambda-adds-support-for-node-js-18-in-amazon-web-services-china-regions/

**Comment by WinterYukky** [comment]
Thank you @ArielPrevu3D for your comment. I'm working on reopening this PR right now 😉

**Comment by WinterYukky** [comment]
Reopen #25406

**Pull request closed without merging**
