### PR TITLE
feat(ecs-service-extensions): add ALB listener rule support

### LINKED ISSUE #10937: [ecs-service-extensions] add listener rules to a `ServiceDescription`
I'd like to expose a service produced via `ServiceDescription` through a pre-existing Application Load Balancer listener.

### Use Case
We often share application load balancers between services in single ECS clusters as a cost-saving measure. Because of this, I'd like support from the new ECS service extension paradigm for creating listener rules.

### Proposed Solution
I think that we could introduce an extension that produces both the target group and listener rules.

### Other
I've created a pull request that shows a detailed solution.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by misterjoshua**
This PR introduces an extension called `HttpLoadBalancerListenerRules` that allows users to expose their service through a load balancer via their own listener rules.

Closes #10937 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by misterjoshua** [comment]
@nathanpeck @MrArnoldPalmer Hey fellas. This PR is ready for review whenever you get a chance.

**Comment by nathanpeck** [comment]
Sorry for the delay on reviewing this PR. I'm still thinking about this problem, but I'm leaning more towards a higher level solution if possible. I feel like this extension is exposing too much of the underlying ALB API as is. I am leaning more towards making the existing HTTP Load Balancer extension smarter, so for example you can pass an existing ALB to it, and then pass a hostname or path to mount the service into that ALB on that host or path. Ideally people won't have to touch priorities and all that directly.

What do you think about publishing this extension as a separate NPM package? We can still link to it from the package readme as a compatible extension. Over time I want to encourage a third party ecosystem of extensions, in addition to the default built in extensions. The goal is for the default shipped extensions to be super simple API's to start with and then we can have more of the advanced things shipped independently, but linked to in the README for the package under "Advanced use cases" or something like that

**Comment by misterjoshua** [comment]
> Sorry for the delay on reviewing this PR. I'm still thinking about this problem, but I'm leaning more towards a higher level solution if possible. I feel like this extension is exposing too much of the underlying ALB API as is. I am leaning more towards making the existing HTTP Load Balancer extension smarter, so for example you can pass an existing ALB to it, and then pass a hostname or path to mount the service into that ALB on that host or path. Ideally people won't have to touch priorities and all that directly.

Indeed, that sounds like a nice user experience. If #11089 goes well, hopefully, we'll have the ability to do ALB lookup by tags soon, so importing the ALB may only get easier. Do you envision that service extensions from different CDK projects would be able to use the same ALB listener?

> What do you think about publishing this extension as a separate NPM package? We can still link to it from the package readme as a compatible extension. Over time I want to encourage a third party ecosystem of extensions, in addition to the default built in extensions. The goal is for the default shipped extensions to be super simple API's to start with and then we can have more of the advanced things shipped independently, but linked to in the README for the package under "Advanced use cases" or something like that

The NPM package shouldn't be a problem.

**Comment by misterjoshua** [comment]
@nathanpeck Hey. I've created a [separate NPM package](https://www.npmjs.com/package/@wheatstalk/ecs-service-extension-listener-rules) for this extension and [associated github repo](https://github.com/wheatstalk/ecs-service-extension-listener-rules).

Unfortunately, I couldn't implement a JSII module as ECS Service Extensions doesn't do JSII yet. But, this isn't a huge deal, as it only limits language portability and access to the nice JSII freebies like automatic backwards compatibility checking. I wonder if adding JSII to ECS Service Extensions is something we should be looking at doing.

Anyway, I'm ready to close this PR when you are.

**Comment by nathanpeck** [comment]
That's great. Yes JSII support is on the roadmap for this module. I'll reach out to you when we have it added in.

Unless you beat me to it I'll make a PR soon to add a new section to the official docs linking to other extensions, and include your third party package on the list

**Pull request closed without merging**
