### PR TITLE
feat(stepfunctions): add IntrinsicFunction class

### PR DESCRIPTION
**Pull request by w-haibara**
Add `IntrinsicFunction` class for generate [intrinsic function](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html) strings. This makes it possible to define functions more clearly.

When defining complex functions such as the following, programmers had to check the syntax by themselves.
```typescript
const fn = "States.Format('1={}, 2={}', States.JsonToString($.path1), States.Format('3={}', $.path2))";
```

By introducing this class, we can leave the complicated grammar checking to the interpreter.
```typescript
const fn = IntrinsicFunction.StatesForamt('1={}, 2={}',
      IntrinsicFunction.StatesJsonToString('$.path1'),
      IntrinsicFunction.StatesForamt('3={}', '$.path2'));
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by w-haibara** [comment]
@yamatatsu I created a PR instead of #18414.

**Comment by yamatatsu** [comment]
@w-haibara OK! Some works is needed, I think.

1. add line to `lib/index.ts` to export this class.
2. `yarn build` (and you can see some lint errors)
3. fix it!

**Comment by w-haibara** [comment]
@yamatatsu  Thank you for letting me know the work process.
I have fixed the following.
- add line to `lib/index.ts` to export this class.
- fix methods in IntrinsicFunction to camel case.
- fix definition of type `arg` in IntrinsicFunction.

**Comment by yamatatsu** [comment]
@kaizen3031593 
Do we need for merging this PR to implement smart API as [mapping-tenplate.ts in aws-appsync](https://github.com/yamatatsu/aws-cdk/blob/07081ed0b918ecd372b4437ff52a0b0b1ecd021d/packages/@aws-cdk/aws-appsync/lib/mapping-template.ts)?

**Comment by kaizen3031593** [comment]
HI @yamatatsu! Thanks for starting this PR! It looks similar to #18595, which also introduces intrinsic format helping. Looking at the two PRs, I think the API in #18595 is a bit smoother. If you agree, would you like to help me review the PR over there?

**Comment by w-haibara** [comment]
@kaizen3031593 Okay, I understand. I'm also interested in #18595.

**Pull request closed without merging**
