### PR TITLE
fix(cloudwatch): correct CompositeAlarm.fromCompositeAlarmName ARN format

### LINKED ISSUE #24594: aws-cloudwatch: Imported composite alarm ARN incorrect
### Describe the bug

It seems that the ARN used for CompositeAlarms is incorrectly generated when using `CompositeAlarm.fromCompositeAlarmName`. The resulting ARN has `/` as separator where as the actual alarm has `:`.

The whole thing is a bit wonky too:
- In reality, ARNs for `Alarm` and `CompositeAlarm` instances are equivalent, yet in CDK they are different
- There is no `Alarm.fromAlarmName`, even though `CompositeAlarm.fromCompositeAlarmName` exists
- The resulting type for either is `IAlarm` anyway, so the distinction between `Alarm` and `CompositeAlarm` is lost

Fix is trivial, but might require more rework to fix this all.

### Expected Behavior

I expected an ARN of the form:
> arn:aws:cloudwatch:eu-central-1:219189227975:alarm:NpayGatewayRegionalSyteCentral-Stack-RollbackAlarm

### Current Behavior

I got an ARN of the form:
> arn:aws:cloudwatch:eu-central-1:219189227975:alarm/NpayGatewayRegionalSyteCentral-Stack-RollbackAlarm

I tried using this as a rollback trigger, and got the error:
> RelativeId of a Rollback Trigger's ARN is incorrect

### Reproduction Steps

Call code as such:
```
const testAlarm = CompositeAlarm.fromCompositeAlarmName(this, 'alarm', `TestAlarm`);
console.log(testAlarm.alarmArn);
```

### Possible Solution

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-cloudwatch/lib/composite-alarm.ts#L76-L80

Pass in `arnFormat: ArnFormat.COLON_RESOURCE_NAME`.

Also below:

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-cloudwatch/lib/composite-alarm.ts#L93

Use `ArnFormat.COLON_RESOURCE_NAME`.

Suggest aligning these methods with `Alarm` class as well.

### Additional Information/Context

_No response_

### CDK CLI Version

2.68.0 (build 25fda51)

### Framework Version

_No response_

### Node.js Version

v19.7.0

### OS

Linux codespaces-3481fc 5.4.0-1104-azure #110~18.04.1-Ubuntu SMP Sat Feb 11 17:41:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Language

Typescript

### Language Version

Version 4.9.5

### Other information

_No response_

### PR DESCRIPTION
**Pull request by nakedible-p**
Fixes #24594.

### CODE REVIEW

**Comment by nakedible-p** [comment]
Exemption Request: Fix is in resource import, which isn't visible in stack output except if doign some other usage.

All in all, not sure what is the best way to test the fix, as there were no tests for the original functionality (which is obviously why it was broken in the first place).

Somebody more knowledgeable could give me a hint.

**Comment by ayush987goyal** [comment]
@nakedible-p Can you mark this PR ready for review?

@pahud Can we create an exemption for the linter?

**Comment by pahud** [comment]
Hi

>Fixes must contain a change to an integration test file and the resulting snapshot.

You will need to submit an integration test file change and re-generate the snapshot. 

> If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing Exemption Request and/or Clarification Request.

And I see some file conflicting you will need to resolve to pass the check before the maintainers can come in for initial review.

**Comment by nakedible-p** [comment]
Hi Pahud

Pull request now marked ready for review.

And as explained above, I don't know how to get the integration test thing fixed, as there are no integration tests for imports in this module.

> Exemption Request: Fix is in resource import, which isn't visible in stack output except if doing some other usage.
>
> All in all, not sure what is the best way to test the fix, as there were no tests for the original functionality (which is obviously why it was broken in the first place).
> 
> Somebody more knowledgeable could give me a hint.

The fix is trivial, but I do need assistance on how to write a test that didn't exist in the first place.

**Comment by ayush987goyal** [comment]
@nakedible-p You can refer the following examples:

1. DDB: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-dynamodb/test/dynamodb.test.ts#L2132
2. S3: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3/test/bucket.test.ts#L794

**Comment by nakedible-p** [comment]
Neither of those is an integration test (`integ.*.ts`) and the linter wants me to add an integration test.

**Comment by ayush987goyal** [comment]
@nakedible-p We should add this change for `IAlarm` as well to make it a consistent experience.

Regarding integration tests, you can refer [this guide](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md) and an example [here](https://github.com/aws/aws-cdk/blob/a6abb451ce325def7bc8b129a560bbe7e85c12b5/packages/%40aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.ts)

On a high level it could look like what we have below where we create two stacks (one producer and one consumer)

```ts
import * as cw from 'aws-cdk-lib/aws-cloudwatch';
import * as cdk from 'aws-cdk-lib/core';
import { ExpectedResult, IntegTest } from '@aws-cdk/integ-tests-alpha';

const ALARM_NAME = "SomeAlarmName";
const COMPOSITE_ALARM_NAME = "SomeCompositeAlarmName";

class ProducerStack extends cdk.Stack {

  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const alarm = new cw.Alarm(this, "SomeAlarm", {...});

    const compositeAlarm = new cw.CompositeAlarm(this, "SomeCompositeAlarm", {...});
  }
}

class ConsumerStack extends cdk.Stack {

  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const importedAlarm = cw.Alarm.fromAlarmName(this, "ImportedSomeAlarm", ALARM_NAME);
    const importedCompositeAlarm = cw.CompositeAlarm.fromCompositeAlarmName(this, "ImportedSomeAlarm", COMPOSITE_ALARM_NAME);

    // create a new composite alarm from the two imported alarms above.
    const compositeAlarm = new cw.CompositeAlarm(this, "SomeCompositeAlarm", {...});
  }
}

const app = new cdk.App();
const producerStack = new ProducerStack(app, 'alarm-import-producer-integ');
const consumerStack = new ConsumerStack(app, 'alarm-import-consumer-integ');
consumerStack.addDependency(producerStack);

const testCase = new IntegTest(app, 'ImportAlarms', {
  testCases: [producerStack, consumerStack],
});

// Add assertions here that the new compositeAlarm in consumerStack exists.
testCase.assertions
  .awsApiCall('CloudWatch', 'DescribeAlarms', {...})
  .expect(ExpectedResult.objectLike(...));
```

**Comment by nakedible-p** [comment]
To clarify:

- I'm happy to spend the 15 minutes it takes to make an obvious fix to an obvious bug.
- I'm happy to spend the 30 minutes to write a simple regression test case that didn't exist for the feature.
- I'm happy to spend 30 minutes more to cross the t's and dot the i's to get a pull merged.

I'm not interested in:

- Spending hours figuring out where or how I need to run `yarn integ` when the docs do not really give a clue
- Spending hours ensuring the test suite passes in GitHub Codespaces when it mysteriously freezes mid-run
- Spending hours building a comprehensive test suite for a feature that had no tests at all
- Spending hours refactoring also Alarm to match the API of CompositeAlarm when they were inconsistent to start with

If you can help me in exactly what commands I need to run on a freshly checked out repository in order to run integration tests on `packages/aws-cdk-lib/aws-cloudwatch`, I can add a simple integration test which includes the composite alarm name and ARN in the generated stack, so the snapshot will catch any inadvertent changes. Otherwise, I'm happy to leave this work continued by someone else.

(Sorry, no coffee this morning yet)

**Comment by ayush987goyal** [comment]
I agree and that's why I requested @pahud to override that pr-rule for this change since I have typically not seen any service module having integ-tests for importing resources. I provided the above reference since you said you needed some assistance in writing them. 

I am okay in not having integ-tests for this change and have appropriate coverage with just unit-tests. But I would really love to see the same API added to Alarm to be consistent even though they were not consistent to being with. Then again this is not something which should block this fix to be merged but a mere request.

@pahud What are you thoughts on this?

**Comment by nakedible-p** [comment]
Hold your horses - after some coffee, I found out the following:
- All the integration tests for aws-cdk-lib have been moved to @aws-cdk-testing/framework-integ
- There's plenty of existing integration tests for Cloudwatch
- I can probably manage to run the integration tests now that I found out from the build logs how they are run
- Integration test documentation is woefully out of date on these

**Comment by nakedible-p** [comment]
How about it now?

- Added missing method on `Alarm`
- Added tests on `Alarm` as well
- Added tests on the ARN variants of import on both of them (so we know ARN parsing works)
- Added integration test for composite alarm which ensures the `alarmName` and `alarmArn` stay stable by exposing them as outputs from the stack

Also, it seems that it is already known that the integration tests document is out of date: #24958

**Review by ayush987goyal — APPROVED** [review]
LGTM! 
Thanks a lot for going the extra mile to add the functionality to Alarm and corresponding missing unit tests as well!

**Comment by nakedible-p** [comment]
Do I need to do something else to push this through, or will the AWS reviewers just pick this up when they have the time?

**Review by corymhall — APPROVED** [review]
Thanks for the PR!

**Comment by nakedible-p** [comment]
> refusing to allow a GitHub App to create or update workflow .github/workflows/yarn-upgrade.yml without workflows permission
> err-code: D813F

I think auto merge failed because of commit https://github.com/aws/aws-cdk/commit/c174a4979f5c150099fe8b6c499fa821bea63d8f

Should I manually update the branch, or will someone else handle it from here?

**Review by corymhall — APPROVED** [review]

**Pull request merged**
