### PR TITLE
chore(rds): add PG12.5 and deprecate PG9.5 and PG9.6

### PR DESCRIPTION
**Pull request by robertd**
Added PostgreSQL 12.5 version.

Also, I got a friendly email from AWS that some versions of PG will be forcefully updated, and I've decided to mark PG9.5 and 9.6 as deprecated. (Feb 2021 and Nov 2021 EOLs respectfully).

> Amazon RDS is starting the end of life process for PostgreSQL major version 9.5. We are doing this because the PostgreSQL community is planning to discontinue support for PostgreSQL 9.5 on February 11, 2021 [1].
> 
> Amazon RDS for PostgreSQL 9.5 will reach end of life on February 16, 2021 00:00:01 AM UTC. Amazon RDS for PostgreSQL 9.6 will reach end of life in late 2021. Hence, we strongly encourage you to upgrade your databases running PostgreSQL major version 9.5 to 12 or greater at your convenience before February 16, 2021. PostgreSQL 12 contains major innovations including JSON path queries per SQL/JSON specifications and pluggable table storage interface [2]. PostgreSQL 13 introduced parallel processing of indexes with the VACUUM command and improved duplicate data handling by B-tree indexes [3]. Both versions contain numerous fixes to various software defects in earlier versions of the database.
> 
> If you do not upgrade your databases before February 16, 2021, RDS will upgrade your PostgreSQL 9.5 databases to PostgreSQL 12 during a scheduled maintenance window between Feb 16, 2021 00:00:01 UTC and March 16, 2021 00:00:01 UTC. On March 16, 2021 00:00:01 AM UTC, any PostgreSQL 9.5 databases that remain will be upgraded to version 12 regardless of whether the instances are in a maintenance window or not.
> 
> You can initiate an upgrade of your database instance — either immediately or during your next maintenance window — to a newer major version of PostgreSQL using the AWS Management Console or the AWS Command Line Interface. The upgrade process will shut down the database instance, perform the upgrade, and restart the database instance. The database instance may be restarted multiple times during the upgrade process. While major version upgrades typically complete within the standard maintenance window, the duration of the upgrade depends on the number of objects within the database. To avoid any unplanned unavailability outside your maintenance window, we recommend that you first take a snapshot of your database and test the upgrade to get an estimate of the duration. To learn more about upgrading PostgreSQL major versions in RDS, review the Upgrading Database Versions page [4].
> 
> We want to make you aware of the following additional milestones associated with upgrading these databases that are reaching end of life.
> 
> Now through March 16, 2021 00:00:01 AM UTC - You can initiate upgrades of Amazon RDS for PostgreSQL 9.5 instances to PostgreSQL 12 or higher at any time.
> February 16, 2021 00:00:01 AM UTC - After this date and time, you cannot create new RDS instances with PostgreSQL major version 9.5 from either the AWS Console or the CLI. RDS will also automatically upgrade PostgreSQL 9.5 instances to version 12 within the earliest scheduled maintenance window that follows. Restoration of Amazon RDS for PostgreSQL 9.5 database snapshots will result in an automatic upgrade of the restored database to a still supported version at the time.
> March 16, 2021 00:00:01 AM UTC - RDS will automatically upgrade any remaining PostgreSQL 9.5 instances to version 12 whether or not they are in a maintenance window.
> Should you have any questions or concerns, the AWS Support Team is available on the community forums and via Premium Support [5].

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
I assume AuroraPostgresEngineVersion <= 9.6 is also affected... but I haven't received that email. Just let me know and I can deprecate those too.

**Review by skinny85 — APPROVED** [review]
Thanks for the contribution @robertd !

**Comment by robertd** [comment]
@skinny85 You're welcome... any thoughts on this?

> I assume AuroraPostgresEngineVersion <= 9.6 is also affected... but I haven't received that email. Just let me know and I can deprecate those too.

**Comment by skinny85** [comment]
> @skinny85 You're welcome... any thoughts on this?
> 
> > I assume AuroraPostgresEngineVersion <= 9.6 is also affected... but I haven't received that email. Just let me know and I can deprecate those too.

Let's wait for the email 🙂.

**Pull request merged**
