### PR TITLE
chore(cdk): update ADOT Lambda Layer ARNs 

### PR DESCRIPTION
**Pull request by vasireddy99**
Update ADOT Lambda Layer ARNs of latest release.

References - 

- https://github.com/aws-otel/aws-otel.github.io/pull/665
- https://github.com/aws-observability/aws-otel-lambda/pull/763
- https://github.com/aws-observability/aws-otel-lambda/pull/762

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by vasireddy99** [comment]
Exemption Request

**Review by scanlonp — DISMISSED** [review]
Looks good. Could you point me to the documentation that corresponds to which regions are enabled for each layer. I see that a number of regions are commented out, but there are more enabled than in the table from your documentation links. For example https://aws-otel.github.io/docs/getting-started/lambda/lambda-python has 16 regions but the table has 22.

**Comment by vasireddy99** [comment]
> Looks good. Could you point me to the documentation that corresponds to which regions are enabled for each layer. I see that a number of regions are commented out, but there are more enabled than in the table from your documentation links. For example https://aws-otel.github.io/docs/getting-started/lambda/lambda-python has 16 regions but the table has 22.

The doc you referred is correct -  https://aws-otel.github.io/docs/getting-started/lambda/lambda-python. thanks for the good catch. updated the fact-table. it should reflect the appropriate (16 regions) now :-)

**Review by scanlonp — CHANGES_REQUESTED** [review]
It looks like the last test in adot.test.ts is failing. Do you get this error locally?

**Comment by scanlonp** [comment]
@Mergifyio update

**Comment by vasireddy99** [comment]
> It looks like the last test in adot.test.ts is failing. Do you get this error locally?

image

tests are passing now

**Comment by scanlonp** [comment]
I cannot find where the build is failing. It looks like all the tests are passing. Let us see if retrying solves it.

**Comment by vasireddy99** [comment]
> I cannot find where the build is failing. It looks like all the tests are passing. Let us see if retrying solves it.

I have fixed the unit tests iin adot.test.ts, i guess this will pass now.

**Review by scanlonp — APPROVED** [review]
Looks good.

**Pull request merged**
