### PR TITLE
feat(rds): add copyTagsToSnapshot to the construct props for ServerlessCluster and ServerlessClusterFromSnapshot

### LINKED ISSUE #20968: (rds): ServerlessClusterProps is missing copyTagsToSnapshot
### Describe the bug

[DatabaseClusterProps.copyTagsToSnapshot](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseClusterProps.html#copytagstosnapshot) exists but [ServerlessClusterProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.ServerlessClusterProps.html) does not have this property.

The [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-copytagstosnapshot) does not suggest that this doesn't apply to Aurora Serverless.

### Expected Behavior

This compiles

```typescript
new rds.ServerlessCluster(scope, id, {
  copyTagsToSnapshot: true,
  engine: rds.DatabaseClusterEngine.auroraMysql({ version: rds.AuroraMysqlEngineVersion.VER_2_07_1 }),
  // …
})
```

and generates a CFT with

```yaml
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
       CopyTagsToSnapshot: true
       Engine: aurora-mysql
       EngineMode: serverless
       EngineVersion: 5.7.mysql_aurora.2.07.1
       # …
```

### Current Behavior

A TypeScript error that ServerlessClusterProps does not have copyTagsToSnapshot.

### Reproduction Steps

Try to `copyTagsToSnapshot: true` to the props when creating a `rds.ServerlessCluster`.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.30.0 (build 1529743)

### Framework Version

_No response_

### Node.js Version

v14.19.3

### OS

macOS 12.4 arm64

### Language

Typescript

### Language Version

TypeScript (4.7.4)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by SydneyUni-Jim**
In f7c628948e7f71df7a95cb00cdc2746e2e46dc03 copyTagsToSnapshot was added to DatabaseCluster and in 40a6ceb9983694a3645edd78167e93825a9049e9 it was added to DatabaseClusterFromSnapshot as well.

This does the same for ServerlessCluster and ServerlessClusterFromSnapshot.

The implementation and tests parallels the changes mentioned above.

fixes #20968

## Behaviour change

In parallel to copyTagsToSnapshot on DatabaseCluster and DatabaseClusterFromSnapshot, the default for copyTagsToSnapshot on ServerlessCluster and ServerlessClusterFromSnapshot is true.

Before this change, ServerlessCluster and ServerlessClusterFromSnapshot did not emit the CopyTagsToSnapshot property in the CloudFormation template. That resulted in the CopyTagsToSnapshot property being false.

My rationale for this behaviour change is to minimise the differences between DatabaseCluster[FromSnapshot] and ServerlessCluster[FromSnapshot], which are both realised as the same L1 construct.

Changing the CopyTagsToSnapshot property on an existing serverless RDS cluster introduces no interruption. Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-copytagstosnapshot

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by SydneyUni-Jim** [comment]
I haven't been able to run the integration tests. I'm confronted with an error, even with a clean pull from the repo.

```
Verifying integration test snapshots...

Error: ENOENT: no such file or directory, open '…/aws-cdk/packages/aws-cdk/lib/init-templates/v1/info.json'
  ERROR      integ.serverless-cluster 1.051s
      Command exited with status 1
Error: ENOENT: no such file or directory, open '…/aws-cdk/packages/aws-cdk/lib/init-templates/v1/info.json'
  ERROR      integ.serverless-cluster-no-vpc 1.056s
      Command exited with status 1
```

**Review by comcalvi — DISMISSED** [review]
Please add this new prop to an integ test (preferably an existing one) in this PR. Other than that, this looks pretty good.

There have been some recent changes to the init templates in cdk, can you make sure you're using the latest from main before you run the integ tests?

**Comment by SydneyUni-Jim** [comment]
Hi @comcalvi. I've updated the existing integ test snapshots to reflect the new default. I've also added setting a non-default to the existing integ tests.

**Review by TheRealAmazonKendra — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
