### PR TITLE
feat(appsync): add eventBridgeDatasource as L2 construct

### LINKED ISSUE #24809: AWS AppSync: add EventBridge as L2 datasource
### Describe the feature

This feature adds eventBridge as an L2 construct following the release of the [L1 construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_appsync.CfnDataSource.EventBridgeConfigProperty.html)

### Use Case

Customers should have an easy way to add EventBridge as a datasource alongside the current L2 datasource options.

### Proposed Solution

```ts
// datasource.ts
/**
 * Properties for an AppSync EventBridge datasource
 */
export interface EventBridgeDataSourceProps extends BackedDataSourceProps {
	/**
	 * The EventBridge function to call to interact with this data source
	 */
	readonly eventBridgeBus: IEventBus
}

/**
 * An AppSync datasource backed by a EventBridge function
 */
export class EventBridgeDataSource extends BackedDataSource {
	constructor(scope: Construct, id: string, props: EventBridgeDataSourceProps) {
		super(scope, id, props, {
			type: 'AWS_EVENTBRIDGE',
			eventBridgeConfig: {
				eventBridgeBusArn: props.eventBridgeBus.eventBusArn,
			},
		})
		props.eventBridgeBus.grantInvoke(this)
	}
}
```

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

0.00.0

### Environment details (OS name and version, etc.)

mac m1 mbp

### PR DESCRIPTION
**Pull request by mtliendo**
This is a solution for adding a new dataSource method as an L2 construct so that AppSync can send events directly to Amazon EventBridge. 

I'm currently abroad on hotel wifi and am having trouble downloading node_modules. If anyone could co-author tests for PR I would be super grateful🙏  My hope is that everything else looks good.

Closes #24809 .

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Please revert all formatting changes as well as the changes to `yarn.lock`. The formatting does not meet our formatting standards and package lock should not be manually updated unless a new dependency has been added.

**Comment by TheRealAmazonKendra** [comment]
I just noticed your note about looking for a co-author. Our core team won't have the capacity to contribute here but you may find some traction by posting in the cdk.dev slack channel. That community is fantastic and many of our contributors are in there.

**Comment by postsa** [comment]
Looking for this feature as well and I'd like to see this through. I created https://github.com/aws/aws-cdk/pull/25369 to push these changes along. If this looks reasonable and is still necessary I'll be happy to add integration tests and update the readme.

**Pull request closed without merging**
