### PR TITLE
fix(lambda-nodejs): esbuild preCompilation tsconfig precedence is wrong

### PR DESCRIPTION
**Pull request by ghost**
The current implementation of the `extractTsConfig` function overrides previously found compiler options by new ones in extended files.

So if you override parameters in your tsconfig.json that extends from a different one higher up in the project, the parameters in the base configuration file take precedence over those in the tsconfig that is specified for this specific build task.

This change turns around the importance of those parameters so that it matches the behaviour of tsc, where any parameters in the tsconfig override those of the tsconfigs it may extend from.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by SebastiaanSafeguard** [comment]
Exemption Request

There is no integration test affected by these changes.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
Please make sure that your PR title confirms to the conventional commit standard (fix, feat, chore) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request))

Additionally, is there an issue for this? We prefer to have those linked in the body of the PR for tracking.

**Comment by SebastiaanSafeguard** [comment]
> Additionally, is there an issue for this? We prefer to have those linked in the body of the PR for tracking.

No, the contribution guide doesn't say that it is required to create an issue first.

**Comment by TheRealAmazonKendra** [comment]
> > Additionally, is there an issue for this? We prefer to have those linked in the body of the PR for tracking.
> 
> No, the contribution guide doesn't say that it is required to create an issue first. Opening an issue would have taken me more time than change one single line in the code.

Yep, that's why we don't require it. We don't want to add busy work. I was just wondering so we could close the issue, if it existed, when this gets merged.

Please do take note of the comment about the title, though. In the [Pull Request section of our contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request), we have guidelines for how each title type should be written, specifically, in this case:

`fix: describe the bug (not the solution)`

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by MrArnoldPalmer — COMMENTED** [review]
Is there a chance that users actually rely on this behavior today? Because this is a stable module I just gotta ask the question, how likely is it that someone's app works as expected because they have nested tsconfig.json files with those higher up needing to take precedence? 😆 

Personally I lean towards taking this. @TheRealAmazonKendra ?

**Comment by TheRealAmazonKendra** [comment]
> Is there a chance that users actually rely on this behavior today? Because this is a stable module I just gotta ask the question, how likely is it that someone's app works as expected because they have nested tsconfig.json files with those higher up needing to take precedence? 😆
> 
> Personally I lean towards taking this. @TheRealAmazonKendra ?

Oh gosh, I didn't think about that. You're right, though, this would break anyone relying on that precedence. If we're going to make this change, which I tend to agree we should, we'll need to do this behind a feature flag.

**Comment by SebastiaanSafeguard** [comment]
That would mean that someone is using the preCompilation flag in the CDK to also do the type checking in their project, not just the bundling. The CDK would be the only time `tsc` is executed in their whole project (which wouldn't have `extends` if their weren't at least 3 tsconfig files), which also means that the people affected by this change are in one of the following situations:
1. not using an IDEA with built-in type checking
2. living with red squiggly lines and errors
3. not overriding any options that results in a different `tsc` output

That makes me wonder if it is really a good idea to, instead of fixing the current implementation, create a possibility to have a set of tsconfig.json files that do not [follow the reference](https://www.typescriptlang.org/tsconfig#extends) that is set by the official compiler of a language. Keeping it in place only means that the CDK needs documentation to explain erratic behaviour that stems from a previous implementation where the real behaviour does not match expectations.

The better case would be to rip off the bandaid and document in release notes that this was wrong and if people were relying on it, they should change their tsconfig files. Simply because they probably should, because if they ever change their tooling it _will_ be wrong.

**Review by MrArnoldPalmer — APPROVED** [review]
@SebastiaanSafeguard great points! I think you're right and there are cases where fixing a bug may change behavior but since the original was just incorrect, a FF isn't required. This seems like one of them considering everything you listed. The PR message here will go in release notes so that seems like a good enough explanation for anyone who does run into some breakage, but I kinda doubt that will occur based on this discussion.

**Pull request merged**
