### PR TITLE
feat(s3): use sse s3 by default

### PR DESCRIPTION
**Pull request by clueleaf**
S3 now encrypts all objects by default.
https://aws.amazon.com/blogs/aws/amazon-s3-encrypts-new-objects-by-default/

To be align with this behavior, I think we can make SSE-S3 as the default configuration.
(Though it seems like we can still make unencrypted buckets through CloudFormation, uploaded objects will be encrypted anyway.)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by clueleaf** [comment]
Apparently there are a bunch of services that are relying on s3 buckets, resulting in the need for updating hundreds of integ test files.
Before doing that, I want to make sure if I should go ahead or take another strategy.

**Comment by TheRealAmazonKendra** [comment]
This will very much be a breaking change. I think it may be a worthwhile one to make to match with the S3 behavior but I'm going to check in with the rest of the team for additional feedback. If you do move forward, it will need to be under a feature flag.

**Comment by clueleaf** [comment]
@TheRealAmazonKendra 
Thank you. Maybe we should close this pr for now and open an issue first?

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra Thank you. Maybe we should close this pr for now and open an issue first?

I've put a message in our team chat so we'll get back to you on this shortly. Also, if running the tests is a major burden but we want this change, I can assist. Just let me know.

**Pull request closed without merging**
