### PR TITLE
feat(eks): add k8s v1.22

### PR DESCRIPTION
**Pull request by robertd**
EKS 1.22 just got released

https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-1-22/

https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-eks-distro-eks-anywhere-kubernetes-1-22/

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `cdk-integ` to deploy the infrastructure and generate the snapshot (i.e. `cdk-integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
Hi @otaviomacedo (not sure why github bot didn't auto assign it to you 😄 )

**Comment by rix0rrr** [comment]
Does the `kubectl` client we bundle work with this server version?

**Review by comcalvi — APPROVED** [review]
Thanks for the submission, this looks great!

**Comment by robertd** [comment]
> Does the `kubectl` client we bundle work with this server version?

Sorry @rix0rrr I somehow missed this question. Answer is yes.

image

**Comment by damienpuig** [comment]
@robertd Are we certain the kubectl bundled works fine?

Upon updating (1.21 => 1.22 - No extensions/v1beta1 ressources) I am starting to get through Cloudwatch lambda logs:

```
 Cluster/AwsAuth/manifest/Resource/Default (ClusterAwsAuthmanifestFE51F8AE) Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=Ingress, Namespaced=true: no matches for kind "Ingress" in version "extensions/v1beta1"\n'
 ```
 ```
2022-04-08T11:39:47.580+02:00Copy[ERROR] Exception: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=Ingress, Namespaced=true: no matches for kind "Ingress" in version "extensions/v1beta1"\n'Traceback (most recent call last):  File "/var/task/index.py", line 14, in handler    return apply_handler(event, context)  File "/var/task/apply/__init__.py", line 69, in apply_handler    kubectl('apply', manifest_file, *kubectl_opts)  File "/var/task/apply/__init__.py", line 91, in kubectl    raise Exception(output) | [ERROR] Exception: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=Ingress, Namespaced=true: no matches for kind "Ingress" in version "extensions/v1beta1"\n' Traceback (most recent call last):   File "/var/task/index.py", line 14, in handler     return apply_handler(event, context)   File "/var/task/apply/__init__.py", line 69, in apply_handler     kubectl('apply', manifest_file, *kubectl_opts)   File "/var/task/apply/__init__.py", line 91, in kubectl     raise Exception(output)
-- | --
```

From the kubectl internal bootstrap command

```
[INFO]	2022-04-08T09:39:45.849Z Running command: ['kubectl', 'apply', '--kubeconfig', '/tmp/kubeconfig', '-f', '/tmp/manifest.yaml', '--prune', '-l', 'aws.cdk.eks/prune-<ID>']
```

**Comment by damienpuig** [comment]
Update: It is a compatibility issue during the pruning process - deactivating pruning worked fine for now

**Comment by robertd** [comment]
Link #15736

**Pull request merged**
