### PR TITLE
chore(bedrock): support Amazon Rerank 1.0 and Cohere Rerank 3.5 models

### PR DESCRIPTION
**Pull request by mazyu36**
Ref: [Amazon Bedrock now supports Rerank API to improve accuracy of RAG applications](https://aws.amazon.com/about-aws/whats-new/2024/12/amazon-bedrock-rerank-api-accuracy-rag-applications/)

```sh
% aws bedrock get-foundation-model --model-identifier amazon.rerank-v1:0 --region us-west-2

{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-west-2::foundation-model/amazon.rerank-v1:0",
        "modelId": "amazon.rerank-v1:0",
        "modelName": "Rerank 1.0",
        "providerName": "Amazon",
        "inputModalities": [
            "TEXT"
        ],
        "outputModalities": [


% aws bedrock get-foundation-model --model-identifier cohere.rerank-v3-5:0 --region us-west-2

{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-west-2::foundation-model/cohere.rerank-v3-5:0",
        "modelId": "cohere.rerank-v3-5:0",
        "modelName": "Rerank 3.5",
        "providerName": "Cohere",
        "inputModalities": [
            "TEXT"
```

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by badmintoncryer — APPROVED** [review]

**Review by GavinZZ — APPROVED** [review]

**Comment by mazyu36** [comment]
@Mergifyio update

**Comment by mazyu36** [comment]
@Mergifyio update

**Comment by mazyu36** [comment]
@mergifyio update

**Comment by mazyu36** [comment]
@Mergifyio refresh

**Pull request merged**
