### PR TITLE
feat(cli): support for environment specific local context json file - fixes #23911

### PR DESCRIPTION
**Pull request by mavwolverine**
I have added support for passing context variables through a file making reruns easier.

I have also ensured that values passed on command line, override the values passed in the json.

Closes aws/aws-cdk-cli#632 .

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by virajkanwade** [comment]
I have never worked on nodejs so not sure how to write or update any relevant tests. If someone could take that up, that would be great.

**Comment by peterwoodworth** [comment]
You can use [both `cdk.json` and `cdk.context.json`](https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_construct) to pass in and reference as context values - have you tried these methods out?

**Comment by virajkanwade** [comment]
@peterwoodworth  the objective here is maintaining and passing environment specific cdk.context.json. Separate files like cdk.context.dev.json, cdk.context.stage.json, cdk.context.prod.json.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thank you for your contribution! We are unable to provide a meaningful review until the build is passing.

**Comment by RichiCoder1** [comment]
> I can understand not accepting the PR since the build is failing. But not reviewing the change to take it forward when the contributor has explicitly mentioned it, I find a little demoralizing.

If you'd like to propose the change itself, I might recommend creating an RFC in https://github.com/aws/aws-cdk-rfcs and posting in the cdk.dev Slack. I'd encourage it too, as I'd be interested in this myself!

**Comment by TheRealAmazonKendra** [comment]
> > Thank you for your contribution! We are unable to provide a meaningful review until the build is passing.
> 
> @TheRealAmazonKendra Like I mentioned, I have no experience with NodeJS. So requesting someone to take it forward for writing the unit tests for the build to pass.
> 
> I can understand not accepting the PR since the build is failing. But not reviewing the change to take it forward when the contributor has explicitly mentioned it, I find a little demoralizing.

I missed that comment while scrolling through, so I apologize for not replying there. Didn't mean to ignore it.

Unfortunately, our core team doesn't have the capacity to contribute on issues that are p2's. However, if another community member would like to help on this, we certainly welcome that. I think @RichiCoder1's suggestion is a great one!

**Comment by karmabadger** [comment]
@aws-cdk-automation 
can you reopen this?

**Pull request closed without merging**
