### PR TITLE
v0.15.1

### PR DESCRIPTION
**Pull request by rix0rrr**
Fix the broken references to peerDependencies.

Also reverts the previously committed breaking change, so that we can release 0.15.1 instead of 0.16.0. The change will be reapplied after this release is out.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by rix0rrr** [comment]
Waiting for the build to give me some kind of green before I merge.

**Comment by rix0rrr** [comment]
We need another fix in here. The new YAML library fucks up in the face of colons.

**Comment by rix0rrr** [comment]
Y'all are very trustful

**Comment by skinny85** [comment]
> Y'all are very trustful

Well, you can't deploy anything right now, so it's not like we're risking much 😃

**Pull request merged**
