### PR TITLE
fix(lambda-python-alpha): pipenv lock -r is no longer supported

### LINKED ISSUE #28015: (aws-lambda-python-alpha):  Pipenv lock -r is no longer supported
### Describe the bug

When using a custom docker image for a PythonFunction that uses a Pipfile I am getting "Error: No such option: -r" for the ' pipenv lock -r > requirements.txt' command.  In my custom docker image I installed the latest version of pipenv which has since replaced 'pipenv lock -r' with 'pipenv requirements'. https://github.com/pypa/pipenv/issues/5253

### Expected Behavior

Using a custom docker image to bundle a PythonFunction with the latest version of pipenv successfully bundles the lambda function.

### Current Behavior

The CDK synth errors out with "Error: No such option: -r"

### Reproduction Steps

Use a custom docker image with the latest version of pipenv installed to bundle the PythonLambda function and try to synth. 

### Possible Solution

In packaging.ts update withPipenv(): Packaging with pipenv requirements.

### Additional Information/Context

The need for a custom docker image came from pytest not being installed on the default bundler image. However, the example on the documentation page (https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-lambda-python-alpha.ICommandHooks.html) shows the pytest command in beforeBundling. 

### CDK CLI Version

2.100.0

### Framework Version

_No response_

### Node.js Version

v18.16.0

### OS

Mac OS 

### Language

TypeScript, Python

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by stefanfreitag**
As part of the pipenv release 2022.8.13 the deprecated way of generating requirements ("pipenv install -r" or "pipenv lock -r") has been removed in favor of the "pipenv requirements" command.

See  #28015 for the motivation behind this change.

* [Reference to pipenv CHANGELOG](https://github.com/pypa/pipenv/blob/main/CHANGELOG.md#2022813-2022-08-13)
* [Refernce to relevant pipenv pull request](https://github.com/pypa/pipenv/pull/5200)

Closes #28015 .

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by stefanfreitag** [comment]
Clarification Request

Hi, I would love to get  feedback on two questions I have:
- I am not sure if "fix" is the correct category for this changes.  
  In sum, a deprecated and in newer pipenv versions removed configuration option is replaced by its successor.  Would there be a more appropriate category?
- The basic tests were updated, but I am unsure on the integration tests. According to the contribution guidelines I would need them. Would it be sufficient here to have the already existing integration tests executing successfully?

Thanks in advance,
Stefan

**Review by lpizzinidev — APPROVED** [review]
Thanks for the contribution!
Looks good to me 👍

> I am not sure if "fix" is the correct category for this changes.

I think that fix is the right tag for this PR.

> The basic tests were updated, but I am unsure on the integration tests.

I think that the [existing integration test](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-lambda-python-alpha/test/integ.function.pipenv.ts) should already provide coverage here.

**Comment by kaizencc** [comment]
This breaks users of old versions of `pipenv` that don't have `pipenv requirements`. Looks like the version we have in our provided Dockerfile is `pipenv==2022.4.8` because that is the latest that supports python3.6.

https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-lambda-python-alpha/lib/Dockerfile

CDK now officially only supports python3.8+ so we should update that to the latest version that supports 3.8. @stefanfreitag would you be willing to add that update to this PR? If not, I can circle back to it but I don't want to merge this PR before that update gets in.

**Comment by stefanfreitag** [comment]
Good morning @kaizencc, please let me check and come back to you.
I looked into pipenv 2022.4.8 but only in combination with python 3.11.6. Here "requirements" was already supported:

```shell
❯ pipenv --version
/home/stefan/temp/.venv/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:876: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
pipenv, version 2022.4.8

❯ python --version
Python 3.11.6

❯ pipenv
/home/stefan/temp/.venv/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:876: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Usage: pipenv [OPTIONS] COMMAND [ARGS]...

Options:
  --where                         Output project home information.
  --venv                          Output virtualenv information.
  --py                            Output Python interpreter information.
  --envs                          Output Environment Variable options.
  --rm                            Remove the virtualenv.
  --bare                          Minimal output.
  --man                           Display manpage.
  --support                       Output diagnostic information for use in
                                  GitHub issues.
  --site-packages / --no-site-packages
                                  Enable site-packages for the virtualenv.
                                  [env var: PIPENV_SITE_PACKAGES]
  --python TEXT                   Specify which version of Python virtualenv
                                  should use.
  --three                         Use Python 3 when creating virtualenv.
  --clear                         Clears caches (pipenv, pip).  [env var:
                                  PIPENV_CLEAR]
  -q, --quiet                     Quiet mode.
  -v, --verbose                   Verbose mode.
  --pypi-mirror TEXT              Specify a PyPI mirror.
  --version                       Show the version and exit.
  -h, --help                      Show this message and exit.


Usage Examples:
   Create a new project using Python 3.7, specifically:
   $ pipenv --python 3.7

   Remove project virtualenv (inferred from current directory):
   $ pipenv --rm

   Install all dependencies for a project (including dev):
   $ pipenv install --dev

   Create a lockfile containing pre-releases:
   $ pipenv lock --pre

   Show a graph of your installed dependencies:
   $ pipenv graph

   Check your installed dependencies for security vulnerabilities:
   $ pipenv check

   Install a local setup.py into your virtual environment/Pipfile:
   $ pipenv install -e .

   Use a lower-level pip command:
   $ pipenv run pip freeze

Commands:
  check         Checks for PyUp Safety security vulnerabilities and against
                PEP 508 markers provided in Pipfile.
  clean         Uninstalls all packages not specified in Pipfile.lock.
  graph         Displays currently-installed dependency graph information.
  install       Installs provided packages and adds them to Pipfile, or (if no
                packages are given), installs all packages from Pipfile.
  lock          Generates Pipfile.lock.
  open          View a given module in your editor.
  requirements  Generate a requirements.txt from Pipfile.lock.
  run           Spawns a command installed into the virtualenv.
  scripts       Lists scripts in current environment config.
  shell         Spawns a shell within the virtualenv.
  sync          Installs all packages specified in Pipfile.lock.
  uninstall     Uninstalls a provided package and removes it from Pipfile.
  update        Runs lock, then sync.
  verify        Verify the hash in Pipfile.lock is up-to-date.
```

**Comment by kaizencc** [comment]
Thanks for the research @stefanfreitag! I think we are good. If you are willing to take on the separate issue of upgrading the default version of pipenv to something sensible (3.8), please do!

**Review by kaizencc — APPROVED** [review]
Thanks :)

**Comment by stefanfreitagrwe** [comment]
@kaizencc Thanks for your feedback! Anything I need to do about the integrations tests for this PR (e.g. flagging as exemption request)?

**Comment by stefanfreitag** [comment]
@kaizencc Thanks for your feedback! Anything I need to do about the integrations tests for this PR (e.g. flagging as exemption request)?

**Pull request merged**
