### PR TITLE
chore(ec2): update Windows version enum list

### LINKED ISSUE #27019: (aws-cdk-lib/aws-ec2): (Request to update Windows Version enum list)
### Describe the feature

As per latest version of the CDK 2.94.0 (build 987c329) , whenever we are creating a Windows instance , there are few AMI version which are not available in the list of enums https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-ec2/lib/windows-versions.ts. 

Example : we don't have the Microsoft Windows Server 2019 Full Locale English with SQL Standard 2019 AMI provided by Amazon enum value. 

### Use Case

Instead of using LookupMachineImage , if we can have the updated list ,its easier to manage by directly referring to enum value. 

### Proposed Solution

Add a Enum value WINDOWS_SERVER_2019_ENGLISH_FULL_SQL_2019_Standard

example: 

export enum WindowsVersion {

WINDOWS_SERVER_2019_ENGLISH_FULL_SQL_2019_Standard : ''Windows_Server-2019-English-Full-SQL_2019_Standard'
}

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

CDK 2.94.0 (build 987c329

### Environment details (OS name and version, etc.)

Mac OS

### PR DESCRIPTION
**Pull request by msambol**
I took the output of the command below and found the missing ones by diffing this [file](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/lib/windows-versions.ts).

```bash
aws ssm get-parameters-by-path --path "/aws/service/ami-windows-latest" --region us-east-1 | jq '.Parameters | .[] | .Name' | grep Windows_Server
```

Closes #27019.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Thanks 👍
Values missing after a more recent check:
```
Windows_Server-2022-English-Core-EKS_Optimized-1.28
Windows_Server-2022-English-Full-EKS_Optimized-1.28
Windows_Server-2012_RTM-English-Full-Base
Windows_Server-2019-English-Full-SQL_2019_Standard
Windows_Server-2012_R2_RTM-English-Full-Base
Windows_Server-2019-English-Full-EKS_Optimized-1.28
Windows_Server-2019-English-Full-SQL_2019_Standard
Windows_Server-2019-English-Core-EKS_Optimized-1.28
```
I think it would be useful to keep together and order at least the `EKS_Optimized` by version number to improve a bit this file's readability and organization.

**Comment by msambol** [comment]
@lpizzinidev I added the missing ones and organized EKS optimized and then by year.

**Comment by msambol** [comment]
@lpizzinidev I'm getting this?
```
aws-cdk-lib: error: [awslint:docs-public-apis:aws-cdk-lib.aws_ec2.WindowsVersion.WINDOWS_SERVER_2022_JAPANESE_FULL_SQL_2022_ENTERPRISE] Public API element must have a docstring 
```
Didn't change anything significant, not sure what that's about??

**Review by lpizzinidev — APPROVED** [review]

**Review by vinayak-kukreja — APPROVED** [review]
This is great. Thank you @msambol for your contribution and thank you @lpizzinidev for reviewing this PR.

**Pull request merged**
