### PR TITLE
fix(dynamodb): grantTableListStreams() permissions have incorrect Resource

### LINKED ISSUE #9511: [@aws-cdk/aws-dynamodb] Synthesized CFN template
Adding a dynamoDB event source to lambda function results in lambda IAM role policy update to allow `dynamodb:ListStreams` on the `arn:aws:dynamodb:<region>:<accountID>:table/<tableName>/stream/*` resource instead of resource wildcard `"*"` as it should according to this documentation https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazondynamodb.html

### Reproduction Steps

```typescript
import * as dynamodb from '@aws-cdk/aws-dynamodb';
import * as lambda from '@aws-cdk/aws-lambda';
import { DynamoEventSource } from '@aws-cdk/aws-lambda-event-sources';

const table = new Table(...);
const function = new lambda.Function(...);

function.addEventSource(
        new DynamoEventSource(table, {
          startingPosition: lambda.StartingPosition.TRIM_HORIZON,
          batchSize: 10,
        })
      );
```

### What did you expect to happen?

Generate a CF template that has this statement in the IAM role policy attached to the lambda role: 

```json
{
  "Action": "dynamodb:ListStreams",
  "Effect": "Allow",
  "Resource":
    "*"
}
```
### What actually happened?

CF template was generated upon synthesizing CDK code with this statement in the lambda role policy:

```json
{
  "Action": "dynamodb:ListStreams",
  "Effect": "Allow",
  "Resource": {
    "Fn::Join": [
      "",
      [
        {
          "Fn::ImportValue": "DynamoTable:ExportsOutputFnGetAttTableCD117FA1ArnE2C8C204"
        },
        "/stream/*"
      ]
    ]
  }
},
```

### Environment

  - **CLI Version      :** 1.53.0 (build 6c326cb)
  - **Framework Version:** 1.53.0
  - **Node.js Version:** v12.13.0
  - **OS               :** macOS Catalina 10.15.5
  - **Language (Version):** TypeScript (3.8.3)

### Other

Documentation mismatch for what resource scoping should look like:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.Tutorial.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazondynamodb.html

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ayush987goyal**
This action does not support resource ARN patterns, only `*`.

Reference: https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazondynamodb.html

Fixes #9511

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ayush987goyal** [comment]
@skinny85 could you take a look at this?

**Comment by skinny85** [comment]
> @skinny85 could you take a look at this?

@ayush987goyal apologies! I somehow missed this PR. I'll take a look tomorrow, I promise!

**Review by skinny85 — APPROVED** [review]
Looks good to me!

@RomainMuller do you mind taking a look as well? I'd like to have 2 pairs of eyes for this change 🙂. Thanks!

**Review by RomainMuller — APPROVED** [review]
Thanks for taking care of this!

**Comment by RomainMuller** [comment]
@Mergifyio update

**Pull request merged**
