### PR TITLE
chore(rds): support for aurora mysql 2.07.9, 2.07.10, 2.11.4, 2.12.0 and deprecated versions

### PR DESCRIPTION
**Pull request by go-to-k**
This PR adds new versions and deprecated versions for Aurora MySQL.

- 2.07.9
  - https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.2079.html
- 2.07.10
  - https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.20710.html
- 2.11.4
  - https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.2114.html
- 2.12.0
  - https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.2120.html

Deprecated versions are written in the doc for Aurora MySQL version 2 is [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.20Updates.html).

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
I'm not sure that beta versions (`2.12.0.1` and `3.05.0.1`) should be added here.
1. If the version name changes post-beta, the variable will remain
2. Users who want to use beta versions can do it via the `AuroraMysqlEngineVersion.of()` method

**Comment by go-to-k** [comment]
@lpizzinidev 

I see, I removed them.

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍

**Review by scanlonp — CHANGES_REQUESTED** [review]
The docs say 2.07.* are available. What indicates that only 2.07.9 / .10 are supported?

Aside from that question, these look like great changes. Thank you!

**Comment by go-to-k** [comment]
@scanlonp 

According to the doc, it seems that all versions are deprecated without 2.07.9 / 10. Which should we believe?

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.20Updates.html

rds-mysql-ver

**Review by scanlonp — DISMISSED** [review]
Yes, that does look definitive. I added one small comment to version 2.11.0. Should be good to go!

**Comment by go-to-k** [comment]
@scanlonp 

Thanks to add docs! The CodeBuild occurred an error so I changed. Could you please approve again?

**Review by scanlonp — APPROVED** [review]

**Comment by go-to-k** [comment]
@scanlonp 

Thanks to approve, but the `Queue: Embarked in merge queue` failed. Could you please handle this?

```
The merge queue pull request can't be updated
Details:

Mergify doesn't have permission to update

For security reasons, Mergify can't update this pull request. Try updating locally.
GitHub response: refusing to allow a GitHub App to create or update workflow .github/workflows/request-cli-integ-test.yml without workflows permission
```

**Comment by scanlonp** [comment]
@Mergifyio update

**Review by scanlonp — APPROVED** [review]

**Pull request merged**
