### PR TITLE
feat(aws-cdk-lib): use new L1 codegen

### PR DESCRIPTION
**Pull request by mrgrain**
Replaces the existing `cfn2ts` code generator with the new `spec2cdk` generator based on `@cdklabs/typewriter` and the separately published service spec database `@aws-cdk/aws-service-spec`.

Other neccesary changes are:

- Lowered coverage threshold for branches to 35% since the newly generated code is more expressive. Arguably we should not include generated files in the coverage calculation, but that's a bigger change. 
- Asset hashes in `cfn-include` test changed due to props now being ordered alphabetic. I've manually verified that the templates are otherwise identical.
- Removing `port` property from `neptune-alpha` as this has been removed upstream and is not functional according to the service team.
- Switched `synthetics-alpha` tests to use `testDeprecated()` for anything using the `Canary`. This is due to the removal of the `deleteLambdaResourcesOnCanaryDeletion` prop in the CFN spec. The new codegen marks removed props as deprecated. We will replace this feature with a custom resource soon.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mrgrain** [comment]
Exempting from linter rules since passing all existing tests is proof this works.
No README change required either since this is an internal tool.

**Review by kaizencc — APPROVED** [review]

**Comment by bissli82** [comment]
@mrgrain any good reason why removing the port support is a necessity?

We use it and want to be able to customize neptune port, IMHO changing such functionality without backward compatibility damages Netpune credibility and functionality.

**Comment by mrgrain** [comment]
Hey @bissli82 Thanks for reaching out! Looks like Neptune now offers a replacement `DBPort` for this. 🎉 
LMK if you want to contribute this back in, otherwise I'll try to get to it this week.

Please also note that `aws-cdk/aws-neptune-alpha` is currently an experimental module does not guarantee backwards compatibility. However this call-out is entirely reasonable of you!

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html#cfn-neptune-dbcluster-port

image

**Comment by bissli82** [comment]
Thanks!
We use alpha since we don't want to work with L1 constructs, and are heavily invested in CDK.
Should we expect dbport available in alpha as well?

**Pull request merged**
