### PR TITLE
fix(kinesis): read permissions for stream do not include `kinesis:DescribeStreamConsumer`

### PR DESCRIPTION
**Pull request by watany-dev**
reopen [22727](https://github.com/aws/aws-cdk/pull/22727)
 
Grant Read(Write) Permission Action

"kinesis:DescribeStreamConsumer"
It appears that the following actions had already been added

"kinesis:SubscribeToShard",
ref. https://docs.aws.amazon.com/streams/latest/dev/tutorial-stock-data-kplkcl2-iam.html

Fixes https://github.com/aws/aws-cdk/issues/22184

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by watany-dev** [comment]
The reason the build is failing is because Firehose's integ test depends on Kinesis.
I have attempted to resolve this, but am getting an obscure error and am having trouble parsing it.

```bash
Subprocess exited with error 1
  FAILED     integ.delivery-stream.source-stream-integ.delivery-stream.source-stream (undefined/us-east-1) 8.534s
      Integration test failed: Error: Command exited with status 1

Test Results: 

Tests:    1 failed, 1 total
Error: Some integration tests failed!
    at main (/workspace/aws-cdk/packages/@aws-cdk/integ-runner/lib/cli.js:105:23)
/workspace/aws-cdk/packages/@aws-cdk/core/lib/private/refs.js:146
            throw e;
            ^

Error: Resolution error: Resolution error: Resolution error: Resolution error: Context value '@aws-cdk/core:target-partitions' should be a list of strings, got: "@aws-cdk/core:target-partitions".
```

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
This line is the issue 
```
@aws-cdk/aws-kinesisfirehose:             [+]     "kinesis:DescribeStreamConsumer",
```
The permission needs to be added to the failing test. Re-run that test with `--update-on-failed`.

**Comment by watany-dev** [comment]
The integ test seems to have passed successfully

**Comment by mrgrain** [comment]
Added `pr-linter/exempt-integ-test` since integ tests are updated and a change to a test case is not required here.

**Review by mrgrain — APPROVED** [review]
👍🏻

**Pull request merged**
