### PR TITLE
feat(ec2): support all Security Group protocols

### PR DESCRIPTION
**Pull request by rectalogic**
Protocol numbers must be used for all but a handful of protocols.

Issue #13403 was closed with an incorrect PR merge #13471. According to CFN docs only a handful of protocol names are supported, protocol numbers must be used for the rest.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule-1.html#cfn-ec2-security-group-rule-ipprotocol

This adds all protocol numbers to the enum.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hollanddd** [comment]
Great. This is the info I'm looking for. I think that `esp` and `ah` functions need to be there in order to surface the underlying properties

**Review by rix0rrr — APPROVED** [review]

**Comment by rectalogic** [comment]
> Great. This is the info I'm looking for. I think that `esp` and `ah` functions need to be there in order to surface the underlying properties although i acknowledge that their implementation is incorrect.

But are you going to make functions for every protocol? It seems unnecessary, users can just construct a Port as needed for all these obscure protocols:
```
new Port({
  protocol: Protocol.ESP,
  stringRepresentation: 'ESP',
});
```

**Comment by hollanddd** [comment]
[here](https://github.com/hollanddd/aws-cdk/commits/ec2-remove-protocol-cruft) are two commits to clean up the cruft from my original pr if you want to swipe them for your PR. First one removes the tests there were added and the second adds the protocols to the list of ignored docs in `package.json`

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Build fails

**Comment by rectalogic** [comment]
I don't have access to the failed logs so I don't know why build is failing
https://us-east-1.console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/AutoBuildProject89A8053A-LhjRyN9kxr8o:821211eb-de18-478d-be74-5f56c25b7516/view/new

**Comment by NetaNir** [comment]
@rectalogic the [comment](https://github.com/aws/aws-cdk/pull/13497#issuecomment-799708658) above includes the a link to the logs.

**Comment by rix0rrr** [comment]
image

**Comment by rectalogic** [comment]
It's failing because I removed the APIs added by the previous botched merge
```
API elements with incompatible changes:
err  - METHOD @aws-cdk/aws-ec2.Port.ah: has been removed [removed:@aws-cdk/aws-ec2.Port.ah]
err  - METHOD @aws-cdk/aws-ec2.Port.esp: has been removed [removed:@aws-cdk/aws-ec2.Port.esp]
```

**Comment by hollanddd** [comment]
It's addressed in #13593. Sorry for the confusion

**Comment by rix0rrr** [comment]
I think this PR is no longer necessary, right?

**Comment by rectalogic** [comment]
right

**Pull request closed without merging**
