### PR TITLE
feat(rds): support rolling instance updates to reduce downtime

### LINKED ISSUE #10595: [aws-rds] Minimize downtime during DBCluster updates
Minimize downtime during DB Cluster updates

### Current Status
The CfnDBInstance of DBCluster is currently loosely coupled.
That is, if there are multiple CfnDBInstances, Instance updates will occur at the same time because there is no dependency on them on Cloudformation.
Therefore, the cluster will not be available until the DBInstance update is complete.

### Proposal
Adds a dependency to CfnDBInstance.
As a result, one by one, RollingUpdate will be performed, and the only downtime will be the timing of the primary switch.
In other words, when there are two instances, it will take only two failover times to update. (A)
If we can create Dependency dynamically, it will take only a one-time failover time to update. (B)

I think primary failover times are faster than Instance updates. So I think it would be useful to include this feature.
However, the update time for Stack and the maintenance time for offline updates will increase.

What do you think about this proposal?
I'd like to hear your opinion.

### Proposal Solution (A)
https://github.com/aws/aws-cdk/blob/d95af009a8d59393d019620aa8878098ce0aed1d/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L734
Add `instance.node.addDependency(previous_instance);`

### Proposal Solution (B)
I think we need to use aws-sdk to determine if the current Instance is primary or replica, but I haven't thought about it in detail.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by spanierm42**
Support defining the instance update behaviour of RDS instances. This allows to switch between bulk (all instances at once) and rolling updates (one instance after another). While bulk updates are faster, they have a higher risk for longer downtimes as all instances might be simultaneously unreachable due to the update. Rolling updates take longer but ensure that all but one instance are not updated and thus downtimes are limited to the (at most two) changes of the primary instance.

We keep the current behaviour, namely a bulk update, as default.

This implementation follows proposal A by  @hixi-hyi  in issue #10595.

Fixes  #10595

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thank you for this change. For the most part it looks great, just a couple things before we can approve it. We need to have a README update for this new functionality and we also need an integration test. 

Additionally, I'm wondering if there's a use case for allowing the rolling update to be more configurable rather than just one at a time. Thoughts on that?

**Comment by spanierm42** [comment]
@TheRealAmazonKendra Thanks for the feedback. I indeed forgot to add both a documentation and an integration test.

Concerning more flexible update behaviors: I generally like the idea to add more flexibility. But I think we only have limited options in this case as RDS/Aurora does not support more sophisticated update behaviors as, for instance. E.g., I cannot state that at least "2 instances need to be running" or "at most 3 instances at a time can be updated". Thus, I think the option to choose an enum reflecting the most important options, `BULK` and `ROLLING` are a good start and easy to understand.
We might add `something like BLUE_GREEN` making sure that at most half of the instances are updated at a time thus further reducing the time to update while still making sure not all instances are getting updated. Or `KEEP_AT_LEAST_TWO_INSTANCES` making sure that at least two instances are always up and running while all others can be updated in a batch.
But as we lack support from CloudFormation for more sophisticated options, I would keep it simple and use enums here.

**Comment by spanierm42** [comment]
@TheRealAmazonKendra I added the missing documentation and integration test. Let me know if that fits your needs. Looking forward to hearing from you :)

**Review by TheRealAmazonKendra — APPROVED** [review]
Thank you for this contribution and for your edits on this! I hope you don't mind that I updated the README a bit.

**Comment by spanierm42** [comment]
@TheRealAmazonKendra Thanks for all your guidance and feedback. I highly appreciate your change in the `README.md` as I learned from that you prefer concise documentation and technical details (here, the dependencies between the instances, which I wanted to hide as implementation detail in the text).

**Pull request merged**
