### PR TITLE
fix(eks): Fix subnet tagging

### PR DESCRIPTION
**Pull request by foriequal0**
PR Linter insists on adding tests, but I think it is okay since there is already `creating a cluster tags the {private,public} VPC subnets` test.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by iliapolo** [comment]
@foriequal0 Could you explain what the problem you're trying to solve here? A link to the relevant issue if it exists would be great.

**Comment by foriequal0** [comment]
`Tags.of(subnet).add(...)` tags unnecessarily to all resources in a `ec2.Subnet` construct. Most of the resources in the construct don't need it, except `CfnSubnet`.
Commit `Don't add warnings if a subnet already has a tag` was my mistake. I'll remove it. I thought it could solve  warnings for an imported vpc which already have required tags.

**Comment by iliapolo** [comment]
@foriequal0 I understand the reasoning, but removing tags is a delicate operation, and is technically a breaking change, I also wonder if this might cause resource replacement.

Since it's not causing any harm, i'd rather err on the side of caution and not cause unexpected behavior.

Thanks

**Comment by foriequal0** [comment]
I understand that. I'll take a workaround for it.
```ts
Tags.of(pub).remove("kubernetes.io/role/elb", {
  excludeResourceTypes: [CfnSubnet.CFN_RESOURCE_TYPE_NAME],
});
Tags.of(priv).remove("kubernetes.io/role/internal-elb", {
  excludeResourceTypes: [CfnSubnet.CFN_RESOURCE_TYPE_NAME],
});
```

**Pull request closed without merging**
