### PR TITLE
feat(stepfunctions): support string and file definitions

### LINKED ISSUE #8146: StateMachine - support for definition string or JSON
When creating Step Functions [StateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.StateMachine.html) there is no possibility to provide already created definition string.

Also there is no way of creating [IChainable](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.IChainable.html) from definition string of JSON which would also solve the issue.

That would be extremely useful for our use-case, when it is more convenient to define initial flow steps in JSON file and then edit them programmatically.

When using low-level [CfnStateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.CfnStateMachine.html) there is no way of getting state machine ARN, so workaround is to construct it by hands, also we loose some helpers there.

### Use Case

1. We have JSON file template for creating EMR execution step functions taking care of: cluster creation, initialisation, error handling, and shutdown logic. 
1. Template is parsed and actual work steps are being added programmatically based on external configuration.
1. Also some project parts define whole flow in JSON file, and use CDK to create supporting resources only.

Having possibility to convert [IChainable](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.IChainable.html) to and from JSON would also help a lot for early state machine testing and debugging.

### Proposed Solution

a) Add JSON input support to [Chain](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.Chain.html) similar to one we have in [CustomState](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.CustomState.html) which does accept JSON as input, but works only for single state.

b) Add support for definitionString in [StateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.StateMachine.html) similar to one we have in [CfnStateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.CfnStateMachine.html)

c) Add support for definitionJson in [StateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.StateMachine.html) similar to one we have in [CustomState](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.CustomState.html) 

### Other

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by hoegertn**
This change to AWS CDK will allow for the easier design of workflows by using the workflow studio. The visual representation of workflows is more attractive and easier to understand for developers and business people. Additionally, this change will address related issues in the CDK, improving the overall functionality and user experience. Adding the definitionBody and definitionSubstitutions props and the union-like class DefinitionBody will make it easier to define workflows using this tool by allowing users to define workflows in different ways, such as from an external file or a string.

Closes #8146.
Refs: #18880

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

- [X] Base implementation
- [x] Unit tests
- [ ] Integ tests
- [x] Readme update

### CODE REVIEW

**Comment by hoegertn** [comment]
Tests will follow soon. Need to make sure I can compile as Gitpod now crashes with OOM errors after the restructure.

**Comment by hoegertn** [comment]
I am still working on it.

**Comment by hoegertn** [comment]
I was not able to run the integ test. Gitpod there errors about not finding some modules.

**Comment by mrgrain** [comment]
> I was not able to run the integ test. Gitpod threw errors about not finding some modules.

Exemption Request

**Comment by aidansteele** [comment]
@hoegertn This looks good, I hope to see it merged. I'm re-familiarising myself with CDK (I haven't used it for a while) so this might be a silly question: will it also work with state machine definitions authored in YAML? Or only JSON?

**Pull request closed without merging**
