### PR TITLE
feat(aws-cloudwatch): add support for non-widget fields in dashboard body

### PR DESCRIPTION
**Pull request by clareliguori**
Adding start, end, and periodOverride from https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by sam-goodwin** [comment]
Unit test?

**Comment by rix0rrr** [comment]
I don't understand the link between PR content and title. Title says something about widgets, content seems to be about adding a period to the dashboard.

**Comment by clareliguori** [comment]
Title refers to adding all remaining fields in dashboard body format other than widget, which is already supported

**Comment by rix0rrr** [comment]
Ohhh

**Pull request merged**
