### PR TITLE
chore(integ): delete every version in the bucket

### PR DESCRIPTION
**Pull request by umireon**
Use listObjectVersions to get all the versions and the delete markers.
Provide VersionId with deleteObjects to delete them.

Refs: #15137 and #14987 

@rix0rrr @MrArnoldPalmer @BenChaimberg 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by umireon** [comment]
I'll test if this change works within this week.

**Comment by rix0rrr** [comment]
Will `listObjectVersions` work against a bucket for which versioning is not enabled?

**Comment by umireon** [comment]
@rix0rrr I checked this and S3 returned `{ Key: "THEKEY", VersionId: "null" }` with S3 versioning never enabled.
I believe this PR should work but I need to test.
I'm fixing the type error now.

**Comment by umireon** [comment]
I've fixed the type error and this build will pass.

**Comment by umireon** [comment]
I'm working to keep the code concise.

**Review by rix0rrr — APPROVED** [review]

**Comment by umireon** [comment]
I am trying to run integ test to confirm that this change works.
I buildup the following packages to run `bootstrapping.integtest.ts`:
- `packages/aws-cdk`
- `packages/@aws-cdk/core`
- `packages/@aws-cdk/aws-ec2`
- `packages/@aws-cdk/aws-sns`
- `packages/@aws-cdk/aws-lambda`
- `packages/@aws-cdk/aws-ecr-assets`
- `packages/@aws-cdk/aws-cloudformation`

**Pull request merged**
