### PR TITLE
chore: change how we get regression testing artifacts

### PR DESCRIPTION
**Pull request by rix0rrr**
Mostly just describe the complexities and what we should *probably*
be doing for now.

Can't actually decide whether this is the best way to go. Would
appreciate a second pair of eyes.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by iliapolo** [comment]
@rix0rrr Summarizing our discussion. 

We agreed on the following:

#### Perform a bump before running integration tests on master.

It's a more accurate depiction of the released artifacts. Essentially simulating what would happen if we were to release the current commit on master. This also solves the problem of master version being the same as the published version, which can cause conflicts on installation.

#### Use previous version as the published version.

When we test against the OLD framework, what we really mean is to test against the PREVIOUS framework. We used to just install the latest from the `npm.js` by doing some magic with verdaccio. A clearer approach is to simply calculate what is the PERVIOUS version, and use it.

#### Always use version specifiers when installing packages.

Relates to the previous point, instead of using `latest` and having to configure verdaccio in various ways, we should just always use specific versions. Makes it less magical and easier to reason about.
   
#### No verdaccio magic.

As already mentioned, we currently have to pick and choose when to have verdaccio serve packages and when not to. We want to reach a flow that allows us to simply launch verdaccio as is and serve everything, without needing to hack it.

------------------------------------------------------

Lets break down the execution flow to make sure we get it right and don't miss anything:

### Master pipeline

#### Post Merge back

In this scenario, we run the tests after we already merged back the latest release to our master branch. This means that the version in `lerna.json` is the same as the version of the **latest published** framework. This is the normal most frequent scenario.

For discussion's sake, let's say this version is `1.20.0`.

##### New framework

- Bump version **==>** `1.20.0` to `1.21.0`
- Launch *Verdaccio* from the `dist` directory **==>** *Verdaccio* now serves version `1.21.0`.
- Fetch version from `lerna.json` **==>** `1.21.0`
- Install cli using said version **==>** Installs version `1.21.0` from *Verdaccio* 
- Install framework using said version **==>** Installs version `1.21.0` from *Verdaccio*.
- Calc previous version **==>** `1.20.0`
- Fetch integration tests from previous version **==>** Fetches tests of version `1.20.0` from `npm.js` 

  > This fetches from npm.js because *Verdaccio* serves version `1.21.0` (not `1.20.0`)

- Run said integration tests.

##### Old framework

- Bump version **==>** `1.20.0` to `1.21.0`
- Launch *Verdaccio* from the `dist` directory **==>** *Verdaccio* now serves version `1.21.0`.
- Fetch version from `lerna.json` **==>** `1.21.0`
- Install cli using said version **==>** Installs version `1.21.0` from *Verdaccio* 
- Calc previous version **==>** `1.20.0`
- Install framework using said version **==>** Installs version `1.20.0` from `npm.js`.

  > This fetches from npm.js because *Verdaccio* serves version `1.21.0` (not `1.20.0`)

- Fetch integration tests from previous version **==>** Fetches tests of version `1.20.0` from `npm.js` 

  > This fetches from npm.js because *Verdaccio* serves version `1.21.0` (not `1.20.0`)

- Run said integration tests.

#### Pre Merge back

In this scenario, we run the tests before we merged back the latest release to our master branch. This means that the version in `lerna.json` is less than the version of the **latest published** framework. This only happens in a small time window of post-release-pre-merge-back.

For discussion's sake, let's say the version on master is `1.20.0`, and the **latest published** version is 1.21.0

##### New framework

- Bump version **==>** `1.20.0` to `1.21.0`
- Launch *Verdaccio* from the `dist` directory **==>** *Verdaccio* now serves version `1.21.0`.

  > This could be a problem because version 1.21.0 is already published! ❌

- Fetch version from `lerna.json` **==>** `1.21.0`
- Install cli using said version **==>** Installs version `1.21.0` from *Verdaccio* 
- Install framework using said version **==>** Installs version `1.21.0` from *Verdaccio*.
- Calc previous version **==>** `1.20.0`
- Fetch integration tests from previous version **==>** Fetches tests of version `1.20.0` from `npm.js` 

  > This fetches from npm.js because *Verdaccio* serves version `1.21.0` (not `1.20.0`)

- Run said integration tests.

##### Old framework

- Bump version **==>** `1.20.0` to `1.21.0`
- Launch *Verdaccio* from the `dist` directory **==>** *Verdaccio* now serves version `1.21.0`.

  > This could be a problem because version 1.21.0 is already published! ❌

- Fetch version from `lerna.json` **==>** `1.21.0`
- Install cli using said version **==>** Installs version `1.21.0` from *Verdaccio* 
- Calc previous version **==>** `1.20.0`
- Install framework using said version **==>** Installs version `1.20.0` from `npm.js`.

  > This fetches from npm.js because *Verdaccio* serves version `1.21.0` (not `1.20.0`)

- Fetch integration tests from previous version **==>** Fetches tests of version `1.20.0` from `npm.js` 

  > This fetches from npm.js because *Verdaccio* serves version `1.21.0` (not `1.20.0`)

- Run said integration tests.

### What about Release Pipeline?

It will be exactly the same flow, except we don't need to `bump` in the release branch.

All in all, we should have something like:

+ test-new-framework.sh:

```bash
./test-cli-regression.sh ${version_from_lerna}
```

+ test-old-framework.sh:

```bash
./test-cli-regression.sh ${previous_version_of_version_from_lerna}
```

+ test-cli-regression.sh:

```bash
if [ ${branch} == 'master'] ;
  ./bump.sh
fi
// all steps are the same from here on out.
```

@rix0rrr Double check me? what do you think we should we do about the red points? trick verdaccio? I was really hoping to avoid that.

**Comment by rix0rrr** [comment]
> Perform a bump before running integration tests on master.

Yes. To distinguish between a "real" version and a fake-bumped version I propose we also switch to a version suffix, like `-pre` or `-rc` or `-test` or something.

Let's call this `CANDIDATE_VERSION`.

> Use previous version as the published version.

I would like to be more specific here.

Let's call this version `SUPPLANT_VERSION`, because that's effectively the one we're "replacing".

After we've calculated our `1.21.0-pre` version, we want to get the `SUPPLANT_VERSION` (the previously released version that matches the version we're currently testing). So in case of our `1.21.0-pre` version, that would be `1.20.0` (regardless of whether `1.21.0` has been released in the mean time or not).

We get it by listing the releases on GitHub, and installing the first one in reverse chronological order for which `semver` says it's older than `CANDIDATE_VERSION`.

(There is a timing issue here, since the GitHub releases API is probably paged it's possible that our desired `SUPPLANT_VERSION` is not on the first page of results -- I'm willing to ignore that for now and if we can't find such a version, just fail. The timing window will be large enough [months] that we probably don't need to care, and I don't care to get into proper paging there).

We *always* get the regressed tests to run by doing:

```
npm pack aws-cdk@$SUPPLANT_VERSION
```

That gets us the tarball we can extract to get the tests from.

We *always* install the CLI by doing:

```
npm install aws-cdk@$CANDIDATE_VERSION
```

For the framework version, I propose we introduce we introduce a new envvar `NPM_PACKAGE_SUFFIX`, and the tests will install the following:

```
npm install @aws-cdk/core${NPM_INSTALL_PACKAGE_SUFFIX}
```

We will set this as follows:

```
# In run-against-repo (empty because we have a symlinking npm wrapper here)
export NPM_INSTALL_PACKAGE_SUFFIX=

# In run-against-dist 
export NPM_INSTALL_PACKAGE_SUFFIX=@$(node -p 'require("/.build.json").version')

# In run-against-release (empty because we want the latest from NPM)
export NPM_INSTALL_PACKAGE_SUFFIX=

# In regression test, old framework
export NPM_INSTALL_PACKAGE_SUFFIX=@$SUPPLANT_VERSION

# In regression test, new framework
export NPM_INSTALL_PACKAGE_SUFFIX=@$CANDIDATE_VERSION
```

> This could be a problem because version 1.21.0 is already published! ❌

It's not. The new version with the same version will override the upstream one.

That's also why I was proposing to call it `1.21.0-rc`. ***However*** by the rules of semver I believe that `1.21.0 > 1.21.0-rc`, so there is a risk it would install an upstream dependency if we forgot to fix versions somewhere.

**Re your bumping location**

```
if [ ${branch} == 'master'] ;
  ./bump.sh
fi
```

I feel during testing is too late. We should do this as part of the build proper, so that the packages know about their  old versions. Otherwise the version will not be in the `.tgz`, `.nuget`, etc.

**Safety**

I would also like to add in an envvar `TEST_RUNNER` which can be one of `repo`, `dist`, `release`, which we can test in the test scripts.

We can then do the following:

1. If the var is not set, throw a descriptive error say you must run the script via one of the test runners.
2. In the regression test script, say that it *must* use the `dist` runner. As far as I can tell, we can't use any of the other 2 runners, so we should be clear and upfront about that.

**Comment by iliapolo** [comment]
@rix0rrr 

> It's not. The new version with the same version will override the upstream one. 

> That's also why I was proposing to call it 1.21.0-rc. However by the rules of semver I believe > that 1.21.0 > 1.21.0-rc, so there is a risk it would install an upstream dependency if we forgot to fix versions somewhere.

Cool, i'm ok with that. We already agreed that we need to use fixed versions everywhere, so assuming this holds sounds reasonable. 

Thanks for the more specific details. I think we have a solid plan 👍

**Comment by iliapolo** [comment]
Closing in favor of https://github.com/aws/aws-cdk/pull/8897

**Pull request closed without merging**
