### PR TITLE
Model Amazon States Language for creating Step Functions

### PR DESCRIPTION
**Pull request by adilosa**
Step Functions are defined in JSON, but CloudFormation's `AWS::StepFunctions::StateMachine` resource accepts definitions as plain strings. Developers must hand-craft escaped JSON strings inside their JSON/YAML template, possibly mixing in intrinsic `Fn::` functions or Jinja syntax as well – which gets a bit ugly. 

This PR adds object models which serialize to JSON according to the [Amazon States Language](https://states-language.net/spec.html). This makes authoring State Machines much nicer, as the compiler/IDE can help out with validation and syntax. Where possible, some remaining validation is also be done at runtime. 

```
new stepfunctions.cloudformation.StateMachineResource(Stack, "statemachine", {
    roleArn: role.arn,
    definitionString: new asl.StateMachine({
        startAt: "InitialState",
        states: new asl.States({
            InitialState: ...
        })
    }).definitionString()
});
```

### CODE REVIEW

**Comment by rix0rrr** [comment]
Yes, everything you're proposing sounds great.

I also think that the argument to a `stepfunctions.StateMachine` could maybe simply be a start state, and all other states could be discovered through object references?

What I don't like about that so much is that you're forced to specify your object graph backwards (can't refer to an object until it's been instantiated!), but on the other hand I also want compiler support and not stringly typed references everywhere.

**Comment by adilosa** [comment]
> What I don't like about that so much is that you're forced to specify your object graph backwards

Agreed. It can be somewhat mitigated by inlining task definitions for single-use tasks, but as soon as you have cycles in the graph it gets uglier. 

I was also considering a builder interface on the State Machine itself, for example: 

```
new StateMachine({...})
    .startAt(new PassState())
    .then(new TaskState())
    .then(new TaskState())
    .end();       
```

Keeps things less nested and visually closer to the resulting state machine diagram. Doesn't solve the State variable reuse ugliness though. I also haven't thought through a nice syntax for Choice and Parallel states yet.

**Comment by adilosa** [comment]
I mocked up both ideas using the "Job Status Poller" sample from the console as an example state machine. Feedback welcome!

<details><summary>State Machine Diagram</summary>

Job Status Poller

</details>


<details><summary>Example 1: Builder Pattern</summary>

```typescript
let retries = new asl.Retriers([
    new asl.Retrier({ errorEquals: [asl.ErrorCode.ALL], intervalSeconds: 1, maxAttempts: 3, backoffRate: 2 })
]);
let wait = new Wait("Wait X Seconds", { secondsPath: "$.wait_time" });

new StateMachine({})
    .startAt(new LambdaTask("Submit Job", {
        lambda: SubmitJobLambda,
        resultPath: "$.guid",
        retry: retries
    }))
    .next(wait)
    .next(new LambdaTask("Get Job Status", {
        lambda: CheckJobLambda,
        inputPath: "$.guid",
        resultPath: "$.status",
        retry: retries
    }))
    .next(new Choice("Job Complete?", {
        choices: [
            new If({ variable: "$.status", op: StringEquals: "FAILED" })
                .then(new Fail("Job Failed", { 
                    cause: "AWS Batch Job Failed", 
                    error: "DescribeJob returned FAILED" 
                }),
            new If({ variable: "$.status", op: StringEquals, value: "SUCCEEDED" })
                .then(new LambdaTask("Get Final Job Status", {
                    lambda: CheckJobLambda,
                    inputPath: "$.guid",
                    retry: retries
                })).end()
        ],
        default: wait
    }))
```

</details>

<details><summary>Example 2: State-to-State</summary>

```typescript
let retries = new asl.Retriers([
    new asl.Retrier({ errorEquals: [asl.ErrorCode.ALL], intervalSeconds: 1, maxAttempts: 3, backoffRate: 2 })
]);
let submitJob = new Task("Submit Job", {
    resource: "arn:aws:lambda:REGION:ACCOUNT_ID:function:SubmitJob",
    resultPath: "$.guid",
    retry: retries
});
let wait = new Wait("Wait X Seconds", { secondsPath: "$.wait_time" });
let jobStatus = new Task("Get Job Status", {
    resource: "arn:aws:lambda:REGION:ACCOUNT_ID:function:CheckJob",
    inputPath: "$.guid",
    resultPath: "$.status",
    retry: retries
});
let finalJobStatus = new Task("Get Final Job Status", {
    resource: "arn:aws:lambda:REGION:ACCOUNT_ID:function:CheckJob",
    inputPath: "$.guid",
    retry: retries
});
let fail = new Fail("Job Failed", { cause: "AWS Batch Job Failed", error: "DescribeJob returned FAILED" })
let isJobComplete = new Choice("Job Complete?", {
    choices: [
        new If({ variable: "$.status", op: StringEquals: "FAILED" })
            .then(fail),
        new If({ variable: "$.status", op: StringEquals, value: "SUCCEEDED" })
            .then(finalJobStatus)
    ],
    default: wait
})

new StateMachine({...}).startAt(submitJob);
submitJob.next = wait;
wait.next = jobStatus;
jobStatus.next = isJobComplete;
```
</details>

<details><summary>Example 3: State-to-State, Inlined</summary>

```typescript
let retries = new asl.Retriers([
    new asl.Retrier({ errorEquals: [asl.ErrorCode.ALL], intervalSeconds: 1, maxAttempts: 3, backoffRate: 2 })
]);
let wait = new Wait("Wait X Seconds", { secondsPath: "$.wait_time" });
new StateMachine({...}).startAt(
    new Task("Submit Job", {
        resource: "arn:aws:lambda:REGION:ACCOUNT_ID:function:SubmitJob",
        resultPath: "$.guid",
        retry: retries
    }).next(
        wait.next(
            new Task("Get Job Status", {
                resource: "arn:aws:lambda:REGION:ACCOUNT_ID:function:CheckJob",
                inputPath: "$.guid",
                resultPath: "$.status",
                retry: retries
            }).next(
                new Choice("Job Complete?", {
                    choices: [
                        new If({ variable: "$.status", op: StringEquals: "FAILED" })
                            .then(
                                new Fail("Job Failed", { cause: "AWS Batch Job Failed", error: "DescribeJob returned FAILED" })
                            ),
                        new If({ variable: "$.status", op: StringEquals, value: "SUCCEEDED" })
                            .then(
                                new Task("Get Final Job Status", {
                                    resource: "arn:aws:lambda:REGION:ACCOUNT_ID:function:CheckJob",
                                    inputPath: "$.guid",
                                    retry: retries
                                })
                                .end()
                            )
                    ],
                    default: wait
                })
            )
        )
    )
);
```

</details>

<details><summary>Final ASL Model</summary>
<p>

```typescript
new asl.StateMachine({
    comment: "A state machine that submits a Job to AWS Batch and monitors the Job until it completes.",
    startAt: "Submit Job",
    states: new asl.States({
        "Submit Job": new asl.TaskState({
            resource: "arn:aws:lambda:REGION:ACCOUNT_ID:function:SubmitJob",
            resultPath: "$.guid",
            next: "Wait X Seconds",
            retry: retries 
        }),
        "Wait X Seconds": new asl.WaitState({
            secondsPath: "$.wait_time",
            next: "Get Job Status"
        }),
        "Get Job Status": new asl.TaskState({
            resource: "arn:aws:lambda:REGION:ACCOUNT_ID:function:CheckJob",
            next: "Job Complete?",
            inputPath: "$.guid",
            resultPath: "$.status",
            retry: retries
        }),
        "Job Complete?": new asl.ChoiceState({
            choices: new asl.ChoiceRules(
                new asl.ChoiceRule({
                    comparisonOperation: new asl.StringEqualsComparisonOperation({
                        variable: "$.status",
                        value: "FAILED"
                    }),
                    next: "Job Failed"
                }),
                new asl.ChoiceRule({
                    comparisonOperation: new asl.StringEqualsComparisonOperation({
                        variable: "$.status",
                        value: "SUCCEEDED"
                    }),
                    next: "Get Final Job Status"
                })
            ),
            default: "Wait X Seconds"
        }),
        "Job Failed": new asl.FailState({
            cause: "AWS Batch Job Failed",
            error: "DescribeJob returned FAILED"
        }),
        "Get Final Job Status": new asl.TaskState({
            resource: "arn:aws:lambda:REGION:ACCOUNT_ID:function:CheckJob",
            inputPath: "$.guid",
            end: true,
            retry: retries
        })
    })
});
```

</p>
</details>

**Comment by rix0rrr** [comment]
Thanks for the amazing work of comparing potential syntaxes!

Here's the lens I'm looking at this through:

* Less indentation is better.
* Less repetition is better (=> changes should need to be made in only one location).
* I would like the code to visually look like what it's representing as much as possible (even though that's tricky in this case).

Based on those, I think I like alternatives (2)/(3) best, which are not all that dissimilar. And you can rewrite the indentation of (3) to look linear, like people do with Promises :).

Also, everything's complicated a bit because we have a cycle. But we have the same thing in programming languages, and we've figured out a way to write this structure without writing an explicit cyclic reference--the thing we're trying to express here is a `RepeatUntil` loop. Maybe it makes sense to encode that explicitly? Something like:

```
new Repeat({
  repeat: new Task("Wait", { ... }),
  until: new Task("GetStatus", { ... }),
  repeatChoice: new Choice(...),
  doneChoice: new Choice(...),
});
```

Or similar. That makes it so we can encode the rest of the steps in a nice flat sequence.

> `let submitJob = new Task("Submit Job", {`

In general in the CDK, string parameters in this position hold an "identifier" string, not a "human display string", and this string sure looks like it's intended for human display. I imagine the States Language conflates the two, and uses the same string to refer to a state as well as display it to the user...?

Since, in that model, people don't need to refer to the state by the identifier string anyway (because they can use objects for references), I think it might make sense to move it into the props object and call it something like `stateName`.

Somethings else that popped into my head: retries. Probably makes sense to set some default retry strategy (maybe at the state machine level?), and make it overridable per state?

**Comment by rix0rrr** [comment]
This PR is being superseded by work done elsewhere, will land shortly. Closing.

**Pull request closed without merging**
