### PR TITLE
feat(cli): decouple bootstrap  stack resource discovery from CF stack name

### PR DESCRIPTION
**Pull request by redbaron**
Previously `cdk deploy` was locating CDKToolkit stack by name. Sometimes name is not known upfront, for instance when bootstraping is done via StackSets.  

All `cdk deploy` needs to know is asset bucket and bootstrap version, these can be communicated via SSM parameters with a known names. 

This PR is made of individual patches gradually removing dependency on a CF stack name
from `cdk deploy` stage. `cdk bootstrap` is not affected and continues to use CF stack name.

Main user visible changes are:
- `toolkit-stack-name` CLI flag is accepted  in bootstrap command, but not in deploy anymore
- new optional `bootstrap-qualifier` param for `cdk deploy` command. It defaults to the value used by bootstrap CF template.
- bootstrap stack version bumped to 5. 

fixes: #11420

cc: @wulfmann 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by redbaron** [comment]
@rix0rrr , would you mind to take a look if you have time?

**Comment by rix0rrr** [comment]
Did not look at the code yet. Thanks for writing a comprehensive PR description, that really helps a lot. I immediately have some things to say about this:

* toolkit-stack-name CLI flag is accepted in bootstrap command, but not in deploy anymore

We can't do that.

* First of all: for stacks using the `LegacySynthesizer`, this will still be required, so we can't outright remove this.
* Second of all: we can't just remove command line flags because people might be using them in CI scripts and making the flag unrecognized will throw an error and break the CI pipeline. Best we can do is deprecate.

* new optional bootstrap-qualifier param for cdk deploy command. It defaults to the value used by bootstrap CF template.

Not sure I'm into this. We should strive to keep the CLI simple. The current mechanism for this is to have the app specify the bootstrap qualifier, and this can be done either in code or using context (either, again, in code, or in `cdk.json`). No CLI flag necessary.

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Thanks for submitting, but I think I disagree with the premise of the changes made here.

**Comment by redbaron** [comment]
@rix0rrr , thanks for looking into this.

This change focuses on a newly synthesized stacks, leaving legacy stacks out of scope. I am happy to make changes, leaving legacy behaviour as is.  My follow up comments are in the context of using it with new synth only.

> Well no. For DefaultSynthesized stacks, the asset bucket will be known by the CDK app and written to the asset manifest. cdk deploy does not need to know it.

In theory yes, but for some reason current code uses CDKToolkit output, not Cloud Assembly asset url to upload: https://github.com/aws/aws-cdk/blob/9417b0211eb2939f5a853751333f7941d9dd99f8/packages/aws-cdk/lib/assets.ts#L82

I didn't want to change that behaviour.

Another place where S3 bucket information is used is during template body upload if it is not set in cloud assembly: https://github.com/aws/aws-cdk/blob/9417b0211eb2939f5a853751333f7941d9dd99f8/packages/aws-cdk/lib/api/deploy-stack.ts#L350

If you think, that cloud assembly should be authoritative for asset location, then it is likely that there is no need to make use of `CDKToolkit` CF template at all and all the code to look it up can be removed. 

Only thing left would be version check, which can be switched to existing SSM parameter.

>>    toolkit-stack-name CLI flag is accepted in bootstrap command, but not in deploy anymore
> We can't do that.

I agree. Once we find a good way to move forward, I'll make sure that new behaviour kicks in only if not flag is specified.

> The current mechanism for this is to have the app specify the bootstrap qualifier, and this can be done either in code or using context (either, again, in code, or in cdk.json). No CLI flag necessary.

My understanding is that qualifier can be set during synth time (via context or in code), but is never persisted in cloud assembly as a first class value. Therefore when we come to `cdk deploy`, it should be able to deploy any cloud assembly artefact and for that it needs to know qualifier to at least check bootstrap stack version. Currently it has no other means to get qualifier other than asking users to provide it, because `cdk deploy` could be called with just an cloud formation artefact provided and nothing else.

**Comment by redbaron** [comment]
@rix0rrr , I'd appreciate your input on this.

**Comment by rix0rrr** [comment]
> In theory yes, but for some reason current code uses CDKToolkit output, not Cloud Assembly asset url to upload:

> Another place where S3 bucket information is used is during template body upload if it is not set in cloud assembly:

It's true. Both of these should not happen in case of a DefaultSynthesized stack, but the code won't know beforehand whether that's true or not.

I wonder if it would be helpful to return a dummy instance of `ToolkitInfo` which we'll return if we can't find the bootstrap stack.

If any of its members are called (such as `toolkitInfo.bucketName`) it can then throw a descriptive error message saying it needs to know the name of the bootstrap stack; basically, throw the same error as would be thrown today.

In case of a DefaultSynthesized stack, none of those members should ever need to be called (as all the information will be in the cloud assembly already) and so it's fine that we returned a dummy object.

Feels that is the best way to marry legacy deployments and modern deployments.

What do you think?

---------

>  it should be able to deploy any cloud assembly artefact and for that it needs to know qualifier to at least check bootstrap stack version

Hah! You are correct, I apparently didn't reason that all the way through 🤣 . I suppose adding the name of the SSM parameter to the Cloud Assembly manifest is the thing to do here. I'd prefer that over just the qualifier itself as it's functionally equivalent, but leaves more decisions open to the CDK App & the related synthesizer (which is where we prefer them).

There are like 2 or 3 locations where we have this version number in the manifest.

**Comment by rix0rrr** [comment]
This PR also probably closes https://github.com/aws/aws-cdk/issues/9053

**Comment by redbaron** [comment]
>  I suppose adding the name of the SSM parameter to the Cloud Assembly manifest is the thing to do here.

This is a best course of action IMHO, but I wasn't confident enough in making change to cloud assembly schema and bumping version. If you think it's relatively easy I can try.

**Comment by redbaron** [comment]
Maybe remove version check all together? Remove `toolkitInfo.bucketName` and  `toolkitInfo.bucketUrl` calls from `cdk deploy` and if anything fails, give a hint that we are expecting certain version of a bootstrap stack?

**Comment by rix0rrr** [comment]
> Maybe remove version check all together? 

I strongly believe in giving accurate and actionable error messages as much as we can. Having to replace it with a wishy-washy "something is wrong and it **might** be this" seems suboptimal.

Let me try and get you started...

**Comment by rix0rrr** [comment]
I added a commit to switch over to an SSM parameter name in the Cloud Assembly.

I think the next step would be to have `ToolkitInfo.lookup` always return an object and never fail there, but it may return an object that represents a "failed to find bootstrap stack" state, and which will throw if any of the members that require the bootstrap stack to have been found are called, with an appropriately descriptive error message (please don't throw errors of the form "bucket name not available" or something to that effect -- they will only be helpful to maintainers, not to users!)

I think that should do it. Feels like most of the other changes introduced in this PR could be backed out again. Let me know if I missed something!

**Comment by rix0rrr** [comment]
Superseded by #12594

**Pull request closed without merging**
