### PR TITLE
fix(dynamodb): add missing DynamoDB operations to enum

### PR DESCRIPTION
**Pull request by varju**
While trying to modernize some of my application's hand-rolled alarms, I discovered that the Operations enum doesn't include all of the operation names listed under "Dimensions for DynamoDB Metrics" in https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/metrics-dimensions.html

This PR adds this missing operation names to the enum.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
Hi @ChenKuanSun @neilkuan  are you able to take a first look at this one?

**Review by clarencetw — COMMENTED** [review]
SGTM

**Review by minche-tsai — APPROVED** [review]
LGTM

**Comment by varju** [comment]
I might need a bit of guidance here for polishing the PR. The linter was upset about my choice of "feat" in the title because there were no README updates. I don't see any existing docs relating to the Operations enum, and https://github.com/aws/aws-cdk/pull/11283 didn't touch any READMEs when adding the enum originally.

I've changed the title to "fix" to make the linter happy, but I'm not sure if this is cheating or if there are specific docs I should be improving.

**Review by skinny85 — APPROVED** [review]
Thanks for the contribution @varju!

**Pull request merged**
