### PR TITLE
Add @types/node as a dev dependency for TypeScript projects

### PR DESCRIPTION
**Pull request by ghost**
Add @types/node as a dev dependency for TypeScript projects as this is needed to access the process object used for getting environment vars.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eladb** [comment]
I am okay with adding this despite the fact that it is not normally needed. @RomainMuller what do you think? You were the one that removed them earlier.

**Comment by jogold** [comment]
If I might... I would say that as soon as you start working with assets you usually use `path.join()` (importing `path`) and then `@types/node` is required...

**Comment by Jerry-AWS** [comment]
Would that it were so simple, I guess. I didn't run into versioning issues myself because I have a near-current Node.js installed, so of course the latest `@types/node` module works perfectly with it. The note in the Dev Guide will have to do for now. 

Maybe there's a way we could provide the necessary type info for just `process` in one of the CDK packages, assuming that hasn't changed a lot since our minimum version of Node? 

Anyway, this isn't the PR we're looking for, so I'll close it.

**Comment by eladb** [comment]
@RomainMuller and I discussed this. @RomainMuller can you please follow up on this? I think we want to add this after all...

**Comment by eladb** [comment]
Superseded by https://github.com/aws/aws-cdk/pull/4947

**Pull request closed without merging**
