### PR TITLE
feat(sns): add validation of `displayName` for topic

### PR DESCRIPTION
**Pull request by sosomuse**
### Issue # (if applicable)

--

### Reason for this change

Display errors before deploying

### Description of changes

- Implement length check for displayName (maximum 100 characters long)
    - [AWS::SNS::Topic](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-displayname) 

### Description of how you validated changes

I added unit tests and confirmed all tests passed.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by sosomuse** [comment]
Exemption Request: Since this change only adds validation

**Review by go-to-k — CHANGES_REQUESTED** [review]
Thanks for this PR!

I think it is good to add the description to [the property in the props](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-sns/lib/topic.ts#L12-L16).

```diff
export interface TopicProps {
  /**
   * A developer-defined string that can be used to identify this SNS topic.
   *
+  * The display name must be maximum 100 characters long, including hyphens (-),
+  * underscores (_), spaces, and tabs.
+  *
   * @default None
   */
  readonly displayName?: string;
```

The above message is from the documentation available in [the CFn Guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-displayname).

**Comment by sosomuse** [comment]
@go-to-k 
Thank you for the review!
I have added the description for displayName.

**Comment by go-to-k** [comment]
@sosomuse 

Thanks! Finally, could you please change the PR title to "feat(sns): add validation of `displayName` for topic"?

**Comment by sosomuse** [comment]
@go-to-k 
Done. Thank you for the suggestion.

**Review by go-to-k — APPROVED** [review]
Nice @sosomuse . Approved!

**Review by xazhao — APPROVED** [review]
Looks good to me. Approving. Thanks for the contribution!

**Comment by sosomuse** [comment]
@Mergifyio update

**Pull request merged**
