### PR TITLE
feat(rds): support zero ACU for Aurora Serverless V2

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

Closes https://github.com/aws/aws-cdk/issues/32234.

### Reason for this change
Amazon Aurora Serverless v2 supports scaling to zero capacity.

Ref: https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-aurora-serverless-v2-scaling-zero-capacity/

### Description of changes
"Updated validation to permit zero as a value for `serverlessV2MinCapacity`.

### Description of how you validated changes
Fix unit tests and add an integ test.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by tehnrd** [comment]
Issue I created before seeing the PR

https://github.com/aws/aws-cdk/issues/32234

**Review by badmintoncryer — APPROVED** [review]

**Comment by AbrahamOEd** [comment]
Should there be validation for the engine type? It's only available on the following

`Aurora PostgreSQL 13.15+, 14.12+, 15.7+, and 16.3+, and Aurora MySQL 3.08+.`

**Comment by mazyu36** [comment]
@AbrahamOEd 
Thank you for your comment. I'd like to leave this to the maintainer's discretion.
Beyond this specific case, validation based on engine versions is generally not implemented.
If we add validation, it would likely require modifications every time a new version is added.

**Review by GavinZZ — DISMISSED** [review]

**Review by GavinZZ — APPROVED** [review]
I'll approve it. CloudFormation will validate it and since this seems to be something that could be changing fairly frequently, I think it makes sense to not validate it on CDK side.

**Comment by mazyu36** [comment]
@Mergifyio update

**Comment by mazyu36** [comment]
@GavinZZ 
Thank you as always!
Mergify encountered an error, so I merged main.
Could you please approve again?

**Review by GavinZZ — APPROVED** [review]

**Pull request merged**
