### PR TITLE
feat(sagemaker): add model hosting L2 constructs

### LINKED ISSUE #2809: sagemaker: Create L2 construct for Amazon SageMaker
There is currently only L1 support for Amazon SageMaker. Would be nice to have an L2 construct to support SageMaker notebook instances, models and endpoints.

This is being actively worked on in three phases 🚀:

- [x]  feat(sagemaker): add Model L2 construct
- [ ] feat(sagemaker): add EndpointConfig L2 construct
- [ ] feat(sagemaker): add Endpoint L2 construct

### PR DESCRIPTION
**Pull request by petermeansrock**
Based closely on PR #2888, this commit introduces the Endpoint L2
construct and the L2 constructs on which it depends, including Model and
EndpointConfig. Departures from PR #2888 include:
- EndpointConfig definition moved into its own L2 construct as one
  EndpointConfig resource may be shared by multiple Endpoints.
- An Endpoint-specific IEndpointProductionVariant interface was added to
  support "metric*" and "autoScale*" APIs per endpoint-variant
  combination.
- The Notebook construct was excluded from this new commit to limit
  changes to model hosting use-cases only.
- Feedback on the earlier PR has been incorporated into this new commit.

Fixes #2809

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by NetaNir** [comment]
Hi @petermeansrock!
Thank you for submitting this PR, we will review this week.

**Comment by petermeansrock** [comment]
After merging master into my fork, it looks like the AWS CodeBuild request failed due to an intermittent issue ([log link](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0c41b54e-3d50-4e33-bdb3-12f7c4bc68b2%2Fbuild.log):

```
[Container] 2020/03/11 21:18:48 Running command /bin/bash ./build.sh
=============================================================================================
installing...
yarn install v1.21.1
[1/5] Resolving packages...
[2/5] Auditing packages...
/usr/share/yarn/lib/cli.js:66929
            throw new (_errors || _load_errors()).ResponseError(_this3.reporter.lang('requestFailed', description), res.statusCode);
            ^

Error: Request failed "503 Service Unavailable"
```

Could a CDK developer re-run the build for me?

**Comment by petermeansrock** [comment]
As an FYI for subscribers, I'm in the process of merging the latest upstream changes into my fork and will create a new PR in the next day or two per the guidance received above. This original PR was never abandoned; I've simply been waiting for feedback from the CDK folks. Hopefully with a new PR, I can get better traction.

**Comment by petermeansrock** [comment]
I've created the new PR #20113 to replace this one.

**Pull request closed without merging**
