### PR TITLE
fix(cli): diff against multiple stacks do not always fail if any have a diff

### LINKED ISSUE #7492: CDK diff against multiple stacks does not fail
In our pipeline, trying to use this command to speed up deployments:
```shell
cdk diff --fail -e 'our-prefix-*'
```
If the command fails, then we loop through our stacks, run diff and deploy on each (we have many stacks in this project).

**The problem:** the diff command returns an exit code of `0` when the first stack **does have a diff**, but the second stack does **not have a diff**.  I assume the exit code is just being overwritten by the last diff executed.

### Reproduction Steps

* Create two stacks and prefix their names with `your-prefix-`
* Run `cdk ls` and deploy the stack listed at the end of the list
* Run `cdk diff --fail -e 'your-prefix-*'

You should get an exit code of `0` when it should be a `1` or non-zero.

### Error Log

N/A

### Environment

  - **CLI Version      :** 1.33.1
  - **Framework Version:** 1.33.1
  - **OS               :** macOS and Ubuntu (AWS CodeBuild Standard 4.0)
  - **Language         :** Python 3.7

### Other

My `cdk.context.json` has this:
```json
{
  "@aws-cdk/core:enableStackNameDuplicates": "true",
  "aws-cdk:enableDiffNoFail": "true"
}
```
I get same behavior with or without the `enableDiffNoFail` line.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by polothy**
### Commit Message
Currently, the diff command only remembers if there are any diffs
with the last stack that was diffed. So, if all of your stacks have
a diff except for the last one, the diff command would exit
successfully even if told to fail on diff.

This fix corrects the behavior so that if any of the stacks have
a diff, then the exit code would be non-zero if configured to do so.

fixes #7492
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by polothy** [comment]
Rebased the PR

**Comment by polothy** [comment]
> I think we should also add an integ test here. We recently converted the integ tests to be in jest, so it should be a bit easier to add one now.

That might be a little tricky for me.  I don't feel comfortable running integration tests against my work AWS account.  Feel like I got lucky getting unit tests working and figured out hah

@shivlaks are you interesting in writing the integration test?

**Comment by shivlaks** [comment]
@polothy sure thing, I'll see if I can pick that up later this week and bring this one home

**Comment by polothy** [comment]
Thanks for the assist and for the review!

**Comment by polothy** [comment]
@shivlaks any chance we can get this going again? 😄

**Comment by shivlaks** [comment]
@polothy thanks for the gentle prod - writing up that integ test this week

**Comment by polothy** [comment]
@shivlaks wondering if we can just merge as is? I'm not really seeing the advantage of integration test, because it isn't a problem with the diffing mechanism, just the flag for keeping track of changes over X stacks.

**Comment by shivlaks** [comment]
@polothy i'll try to get it in ahead of the next release. i'm less worried about the integ test for this specific change, but would like it to be there to prevent a regression in the future.

**Comment by polothy** [comment]
> i'll try to get it in ahead of the next release.

❤️ 

> i'm less worried about the integ test for this specific change, but would like it to be there to prevent a regression in the future.

Ah, gotchya.

Thanks again for commenting back and helping!

**Comment by polothy** [comment]
Yah! Thanks so much!

**Pull request merged**
