### PR TITLE
feat(docdb): add option to set the name of the generated Secret

### PR DESCRIPTION
**Pull request by markussiebert**
fixes: #17572
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by skinny85 — DISMISSED** [review]
Thanks for the contribution @markussiebert!

The code looks good, we're just missing two things:

1. Documentation in the ReadMe file of the module showing usage of this property (a one-line change to example code with a comment in the file is fine).
2. Unit tests (you can look at the existing unit tests in the module for inspiration).

Thanks,
Adam

**Comment by markussiebert** [comment]
@skinny85 sorry - don't know how to ask for a review the official way

**Comment by skinny85** [comment]
> @skinny85 sorry - don't know how to ask for a review the official way

For the future 🙂. You need to re-request my review (there's a button right next to my avatar in the top-right corner of the Pull Request web page).

**Review by skinny85 — APPROVED** [review]
Looks great @markussiebert, thanks for the contribution!

**Pull request merged**
