### PR TITLE
feat(lambda-dotnet): Add .NET Lambda support

### LINKED ISSUE #23236: (aws-lambda): Support for .NET Lambda functions with included bundling
### Describe the feature

This is a proposal to support .NET Lambda functions like what already exists for NodeJS, Python & Go. This construct will include the Lambda function definition with predefined bundling support locally or using a Docker container.

### Use Case

As a .NET developer I would like to build serverless Lambda application with .NET and deploy this application using AWS CDK. It is painful to design a build process which first need to build/test and package one or more Lambda functions in my project and then use `lambda.Code.fromAsset(path.join(__dirname, 'out', 'package.zip'))` to point to those packages. This has been beautifully solved with the `aws-lambda-go`, `aws-lambda-nodejs` and `aws-lambda-python` constructs and I would like to have the same experience with .NET.

### Proposed Solution

This functionality can implemented in a separate package called `aws-lambda-dotnet`. The code will look like this;

```
import * as dotnet from 'aws-cdk-lib/aws-lambda-dotnet';
...
new dotnet.DotNetFunction(this, 'WebApiFunction', {
  projectDir: 'src/Serverless.WebApi'
});
...
```

### Other Information

I have already got started with this in my [fork](https://github.com/vlesierse/aws-cdk/tree/feat/lambda-dotnet/packages/%40aws-cdk/aws-lambda-dotnet) and I'm happy to continue with implementing the integration tests, documentation, collecting design feedback and submit the PR.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.53.0

### Environment details (OS name and version, etc.)

macOS Monterey v12.6

### PR DESCRIPTION
**Pull request by vlesierse**
Adds support .NET Lambda functions as described in the issue #23236 and RFC Issue [aws/aws-cdk-rfcs/issues/469](https://github.com/aws/aws-cdk-rfcs/issues/469). This feature is introduced as new alpha package `@aws-cdk/aws-lambda-dotnet-alpha`

- [x] Code
- [x] Tests
- [x] Documentation

Closes #23236.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by kaizencc** [comment]
Hi @vlesierse, thanks for opening this PR. We're still debating this a bit internally but wanted to provide some update for you:

We're most likely going to figure out a way to help you release this as a self-published module. It's not that we don't want it, but we don't think it belongs in the aws-cdk repo, since it is not strictly an L2.

> But wait, what about `aws-lambda-python`, `aws-lambda-go`, `aws-lambda-nodejs`?

Good question -- we allowed those modules into the main cdk repo when we were still experimenting with what made sense to be included and what didn't. Looking back, we probably wish we had pulled them out into separate repositories, but they must continue to be included for legacy reasons. If we ever release a new major version of CDK, we'd likely move these modules out on their own.

So -- nothing actionable yet, but I didn't want to keep you hanging. In the meantime, I notice the build is failing, which is something that would need fixing anyways :) 

Cheers.

**Comment by vlesierse** [comment]
@kaizencc

Thank you for your transparency and providing an update and considerations the team is currently working with. Happy work on continuing bringing this feature to CDK in whatever form.

On the note of the build failing, any way to check this? The CodeBuild logs don't appears to be accessible and obviously it works on my machine ;-)

**Comment by vlesierse** [comment]
@kaizencc on the note of the failing build, it currently fails in the install phase in CodeBuild with `Error while executing command: npm config set unsafe-perm true. Reason: exit status 1`.
Is there something I can do to fix this? Looks not to be code related.

**Comment by kaizencc** [comment]
Hi @vlesierse, we are prepared to go forward with you on a separate cdklabs repository for lambda-dotnet. I've created it here: https://github.com/cdklabs/awscdk-lambda-dotnet. Feel free to create a PR on that repo (it might need some maintenance work that I'm doing right now) and/or contact me on cdk.dev if you need additional support.

**Comment by vlesierse** [comment]
> Hi @vlesierse, we are prepared to go forward with you on a separate cdklabs repository for lambda-dotnet. I've created it here: https://github.com/cdklabs/awscdk-lambda-dotnet. Feel free to create a PR on that repo (it might need some maintenance work that I'm doing right now) and/or contact me on cdk.dev if you need additional support.

@kaizencc that this greatly appreciated. I'll finished some cleanup, additional documentation and tests in a PR to the repository. Thank you!

**Comment by kaizencc** [comment]
Sounds great! I'm gonna close this PR since it's not going to get merged in to cdk proper, and see you on the cdklabs repo. @vlesierse note that the cdklabs repo is governed by projen so all project configuration goes into the `.projenrc.ts` file.

**Pull request closed without merging**
