### PR TITLE
feat(ecs): add function for adding secrets to containers after instantiating them

### LINKED ISSUE #18959: (aws-ecs): addSecret() for a ContainerDefinition
### Description

Similar to addEnvironment() I'd like to add an addSecret() method.

### Use Case

I'm using Aspects to configure third-party services on ECS services.  For example, setting environment variables and secrets for a logging solution.

Today I'm using an escape hatch to add additional Secrets.

### Proposed Solution

```typescript
const container = taskDefinition.addContainer('nginx', {
  image: ecs.ContainerImage.fromRegistry('nginx'),
});

container.addSecret('SECRET_1', ecs.Secret.fromSecretsManager(secret));
container.addSecret('SECRET_2', ecs.Secret.fromSecretsManager(secretField, 'password'));
```

### Other information

Have written code for this and I will link soon.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by FlorinAsavoaie**
### Description

Similar to `addEnvironment()`, an `addSecret()` method is useful to add secrets to ECS Containers after instantiating them via the constructor.

### Use Case

The most important use-case is when writing Task Definition Extensions or Aspects to augment ECS services. For example, setting environment variables and secrets for a logging or monitoring solution.

Right now, this can be done only using Escape Hatches and there is no higher level functionality to obtain this behaviour.

### Proposed Solution

```typescript
const container = taskDefinition.addContainer('nginx', {
  image: ecs.ContainerImage.fromRegistry('nginx'),
});

container.addSecret('SECRET_1', ecs.Secret.fromSecretsManager(secret));
container.addSecret('SECRET_2', ecs.Secret.fromSecretsManager(secretField, 'password'));
```

closes #18959

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by FlorinAsavoaie** [comment]
Well, the problem with the tests failing seems to be that I added more secrets to the same Integration tests that were already testing using secrets. Can we let it go like this or shall I create new integration tests for this use-case? Kind of seems like a waste...

**Comment by FlorinAsavoaie** [comment]
Well, the problem with the tests failing seems to be that I added more secrets to the same Integration tests that were already testing using secrets. Can we let it go like this or shall I create new integration tests for this use-case? Kind of seems like a waste...

Ping @madeline-k . Sorry for the ping, I just noticed you reviewed an initial PR that was made a while ago for the same feature but never got merged. I made sure I looked into the issues that were raised in that PR and followed the advice you gave there.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Please make sure that your PR title confirms to the conventional commit standard (fix, feat, chore) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request)).

Additionally, please make sure that your PR body describes the problem the PR is solving, and the design approach and alternatives considered. Explain why the PR solves the problem. A link to an issue is helpful, but does not replace an explanation of your thought process.

**Comment by Naumel** [comment]
@Mergifyio update

**Comment by FlorinAsavoaie** [comment]
Hey Kendra,

Since my PR was created, the integration tests suffered some changes because of some chore so there were conflicts with the integration tests I changed. I rebased but apparently the tests are now failing. I'm working on it.

Thanks for the feedback and I apologise for doing it wrong.

I updated the PR description. I think the title corresponds with the documentation, as far as I can tell. I checked a few other PRs that were recently merged and it seems quite similar, not sure if I'm missing anything. Is everything ok now from this perspective?

**Comment by FlorinAsavoaie** [comment]
I don't get how the tests are now passed but earlier they weren't. I guess we're good?

**Comment by TheRealAmazonKendra** [comment]
> Hey Kendra,
> 
> Since my PR was created, the integration tests suffered some changes because of some chore so there were conflicts with the integration tests I changed. I rebased but apparently the tests are now failing. I'm working on it.
> 
> Thanks for the feedback and I apologise for doing it wrong.
> 
> I updated the PR description. I think the title corresponds with the documentation, as far as I can tell. I checked a few other PRs that were recently merged and it seems quite similar, not sure if I'm missing anything. Is everything ok now from this perspective?

For the title, we basically want PR titles that are descriptive in a way that would be useful in the changelog. In this case, I'll edit to provide an example. But, instead of just listing the function name, I would describe the functionality you're adding.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
