### PR TITLE
feat(kms): support fromLookup in KMS key to get key by alias name

### LINKED ISSUE #8822: [KMS] Add Alias.fromLookup()
Add ability to lookup full KMS key object by alias name so we can retrieve the target kms key ARN.

### Use Case

See issue 5953 (https://github.com/aws/aws-cdk/issues/5953). 

kms.Alias.fromAliasName(this, 'myKey', 'alias/myTestKey'), returns aliasName, which is great. But then I would like to get a Key ARN from that alias name.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by jumic**
Add method `fromLookup` in KMS key which provides the option to get a KMS key including its key id by an alias name.
In some cases, aliases can't be used because access to the underlying key id is necessary. In this case, the `fromLookup` method can be used.

The following packages were changed:
- @aws-cdk/aws-kms: introduce new `fromLookup` method
- @aws-cdk/cx-api: new KeyContextResponse
- @aws-cdk/cloud-assembly-schema: new ContextProvider KEY_PROVIDER and KeyContextQuery
- aws-cdk: implementation of key ContextProvider

Closes #8822 

-----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jumic** [comment]
Note: Version of cloud-assembly-schema was increased. --> Check/update version again when this PR will be merged.

**Comment by njlynch** [comment]
Thanks so much for submitting this pull request. I am marking this pull request as `p2`, which means that we are unable to work on it immediately, but it's definitely still on our radar.

We use +1s to help prioritize our work, and are happy to revaluate this pull request based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by argenstijn** [comment]
+1

**Review by njlynch — APPROVED** [review]
Thanks for this contribution!

**Comment by aws-codecatalyst-sample** [comment]
Is it possible to support Alias name and Alias ARN? so we can lookup Alias in different account

**Pull request merged**
