### PR TITLE
fix(apigateway): serialization exception with step functions integration

### PR DESCRIPTION
**Pull request by jogold**
Using single quotes (`'`) in the body results in a serialization
exception from API Gateway (`com.amazon.coral.service#SerializationException`).

This is because `$util.escapeJavaScript()` turns regular single quotes
into escaped ones that are not valid in JSON. The solution is to replace
escaped single quotes back to regular single quotes after escaping the
string.

See https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#util-template-reference

image

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@TheRealAmazonKendra ping 😃

**Comment by jogold** [comment]
@TheRealAmazonKendra can you review this fix?

**Comment by jogold** [comment]
> @TheRealAmazonKendra can you review this fix?

yes/no?

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks good. Thanks for the contribution and apologies for it taking me so long to circle back to this.

**Pull request merged**
