### PR TITLE
feat(ecs-patterns) expose ALB idleTimeout property

### LINKED ISSUE #12913: ApplicationLoadBalancedFargateService CDK construct: currently there is no way to specify idleTimeout for the load balancer
Hello.

Currently there is no way to specify an idleTimeout for the load balancer if we create an ApplicationLoadBalancedFargateService.
Even though we do have such option when we are creating an ApplicationLoadBalancer directly via the ApplicationLoadBalancer construct.

I suggest to implement such option for the ApplicationLoadBalancedFargateService as it is needed very much.

### Use Case

I'm using a Fargate service to run a docker container with a 3rd party library that provides http endpoint. This library can take longer than 1 minute to respond (depending on the input) even on the most performant configuration. In that case I'm receiving a 504 Gateway Time-out error from the load balancer. That's why I need a way to specify the idleTimeout for the ApplicationLoadBalancedFargateService.

### Proposed Solution

To add a set of load balancer related configuration options to the ApplicationLoadBalancedFargateServiceProps.

### Other
Related to the support case 7958289501

Regards,
Anton.

### PR DESCRIPTION
**Pull request by michaeldrey**
This PR exposes the idleTime property for both EC2 and Fargate, and the MultiTargetGroup ALB services. [Per the CFN specs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattributes.html), I have set the idleTimeout to default to 60 seconds, and it cannot exceed 4000 seconds.

If no value is provided we set the value to undefined. We do this because:
1. The default value is set for the user via the CFN. The behavior for the property is to either add a value or leave it undefined and let CFN set the default.[ See here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts#L102)
2. Setting a default causes snapshot tests to fail for dependent services as we're adding a new attribute to the cloudformation.

In addition to this, I've updated all the Integ tests to a working state (would not build otherwise) and added working tests for all cases listed above.

Lastly I've added two examples to the README.

closes #12913
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thank you for your contribution. This looks like really excellent work (and includes everything I ever ask for in terms of tests and documentation updates. 120 files, however, makes it hard to provide a meaningful and thorough review. Could you please split this up into multiple PRs so that we can review them more effectively?

**Comment by michaeldrey** [comment]
@TheRealAmazonKendra Thanks for the quick response!

You have a great point, this has kind of snowballed a bit. I will begin splitting this out into the PR's you've suggested

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra Thanks for the quick response!
> 
> You have a great point, this has kind of snowballed a bit. I will begin splitting this out into the PR's you've suggested

Thank you! I know it can be kind of a pain in the ass to split up a PR once you've got it all prepared. I appreciate your efforts here.

**Comment by TheRealAmazonKendra** [comment]
@michaeldrey Do you plan to make any updates to this PR or just the other two that came out of this? If the latter, let's close this one so we don't have extra PRs open that we're not going to review.

**Comment by michaeldrey** [comment]
@TheRealAmazonKendra I'll close this one as the other two capture all the features in this PR.

**Pull request closed without merging**
