### PR TITLE
fix(tooling): update vscode devcontainer image

### PR DESCRIPTION
**Pull request by RichiCoder1**
The `latest` tag of the `jsii/superchain` image has long been deprecated. This aligns the devcontainer image with the one used for gitpod.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
Agree and LGTM. Did you try it in your VSCode local and if possible, GitHub Codespaces?

**Comment by RichiCoder1** [comment]
> Agree and LGTM. Did you try it in your VSCode local and if possible, GitHub Codespaces as well?

Both VSCode Local and GH Codespaces are showing the correct versions of Node and NPM (e.g. the same as gitpod)

**Comment by pahud** [comment]
Works great in my Codespaces as well. I think it's ok to approve and merge. cc @skinny85 wdyt?

**Review by skinny85 — APPROVED** [review]
Thanks for the contribution @RichiCoder1!

**Pull request merged**
