### PR TITLE
fix(servicediscovery): apply routingPolicy if set

### PR DESCRIPTION
**Pull request by danilobuerger**
When explicitly setting a `routingPolicy`, if was being silently ignored and replaced by the default. This PR fixes this and allow setting the `routingPolicy` to the specified value.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by danilobuerger** [comment]
I am unable to run a real integration test

**Comment by corymhall** [comment]
@danilobuerger is there an associated issue for this?

**Comment by danilobuerger** [comment]
I don't see any requested changes and therefor don't know how to further help this along.

**Comment by TheRealAmazonKendra** [comment]
> I am unable to run a real integration test

Why are you unable to run real integration tests? The changes requested on this are the requirement to write and run an integration test to prove the fix.

**Comment by danilobuerger** [comment]
I can't create an aws account for this. As per contributing guidelines:

> If you are working on a PR that requires an update to an integration test and you are unable to run the cdk-integ tool to perform a real deployment, please call this out on the pull request so a maintainer can run the tests for you.

So i stated this as requested.

**Pull request closed without merging**
