### PR TITLE
fix(stepfunctions-tasks): migrate from deprecated batch properties

### LINKED ISSUE #18993: (stepfunctions-task): BatchSubmitJob uses deprecated (and thereby ignored) container overrides API
### What is the problem?

A `BatchSubmitJob` task allows configuration via an instance of `BatchSubmitJobProps`, which itself allows configuration overrides on the running container via an instance of `BatchContainerOverrides`.

Unfortunately, AWS Batch's submit job [has deprecated the `containerOverrides` structure](https://docs.aws.amazon.com/batch/latest/userguide/troubleshooting.html#override-resource-requirements) and now ignores it in favor of the defaults specified in the `JobDefinition`.

Neither the current [V1](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-stepfunctions-tasks.BatchContainerOverrides.html) nor [V2](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.BatchContainerOverrides.html) CDK expose this new structure, nor does the CDK synthesis translate the old container overrides structure into the new structure.

### Reproduction Steps

This can not plausibly be an SSCCE, but the batch submit job definition does look like, for example:
```
    const aTask = new tasks.BatchSubmitJob(this, 'Run a task', {
        jobDefinitionArn: jobArn,
        jobName: 'jobName',
        jobQueueArn: jobQueueArn,
        containerOverrides: {
            vcpus: 16,
            memory: 32678
        },
        resultPath: '$.Result'
    });
```

### What did you expect to happen?

That, if the hypothetical job definition specifies a vCPU of 2, and a memory of 4,096, that the reproduction example would start a container with a vCPU of 16. and a memory of 32,768

### What actually happened?

I will attach a screen shot of what the console shows in this situation, but in the continued hypothetical case, the container is launched with the job definition's default of a vCPU of 2 and memory of 4,096.

### CDK CLI Version

1.116.0

### Framework Version

_No response_

### Node.js Version

14.18.0

### OS

macOS 11.6.3

### Language

Typescript

### Language Version

3.8.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by peterwoodworth**
fixes #18993 + update integ tests

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by kaizen3031593** [comment]
@peterwoodworth  Since `batch` is an experimental module, I wonder if we should just remove the `containerOverrides` option entirely (since that was what was done on the batch side). Perhaps we can expose those properties as an alternative to `containerOverrides`

**Comment by peterwoodworth** [comment]
I had considered that @kaizen3031593, and actually went with deprecating the properties at first in exchange for what you proposed - but since this change is within the stepfunctions-tasks module I had decided to stick with the easier change at first to see what you would say.

Still, since this change is within a stable module that would require deprecation instead of outright removal, right?

**Comment by kaizen3031593** [comment]
Whoops I thought this was in `batch`. My bad, you're right.

**Comment by peterwoodworth** [comment]
Let me know if you'd like me to go with deprecation 👍🏻

**Review by kaizen3031593 — APPROVED** [review]
Looks good!

**Pull request merged**
