### PR TITLE
fix(lambda-event-sources): event source property maxConcurrency is not token-aware

### LINKED ISSUE #27796: (lambda-event-sources): Providing a Token for the maxConcurrency results in a runtime error
### Describe the bug

When providing a numeric token for the maxConcurrency it results in a runtime error

### Expected Behavior

It should not error when provided with a numeric token 

### Current Behavior

Providing a token currently results in a runtime error

```
jsii.errors.JavaScriptError: 
  @jsii/kernel.RuntimeError: Error: maxConcurrency must be between 2 and 1000 concurrent instances
```

### Reproduction Steps

```

event_source.SqsEventSource(queue=queue, batch_size=batch_size,
                            max_concurrency=Token.as_number(ssm.StringParameter.value_for_string_parameter(self, "max_concurrency"))))
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.103.1

### Framework Version

_No response_

### Node.js Version

v16.20.1

### OS

Linux

### Language

Python

### Language Version

Python 3.10.12

### Other information

_No response_

### PR DESCRIPTION
**Pull request by rahman**
Allows a Token to be provided for maxConcurrency without runtime errors

Closes #27796.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rahman** [comment]
Exemption Request: I'm not sure integration test changes are required but happy to add them if so

**Review by sumupitchayan — APPROVED** [review]
Thank you for contributing

**Comment by rahman** [comment]
@mergifyio refresh

**Comment by rahman** [comment]
@sumupitchayan The `Queue: Embarked in merge queue` failed. Not sure how to resolve it?

```
The merge queue pull request can't be updated
Details:

Mergify doesn't have permission to update

For security reasons, Mergify can't update this pull request. Try updating locally.
GitHub response: refusing to allow a GitHub App to create or update workflow .github/workflows/issue-label-assign.yml without workflows permission
```

**Comment by rahman** [comment]
> @sumupitchayan The `Queue: Embarked in merge queue` failed. Not sure how to resolve it?
> 
> ```
> The merge queue pull request can't be updated
> Details:
> 
> Mergify doesn't have permission to update
> 
> For security reasons, Mergify can't update this pull request. Try updating locally.
> GitHub response: refusing to allow a GitHub App to create or update workflow .github/workflows/issue-label-assign.yml without workflows permission
> ```

@scanlonp are you able to help with this? I can see you resolved this issue on another pr #27648

**Review by scanlonp — APPROVED** [review]
Re-approve

**Comment by scanlonp** [comment]
@rahman what happens is when our workflows are changed, mergify loses permissions until your branch is manually updated. That also clears any approving reviews. This should get it on the right track.

Our build has been acting up. We have some fixes incoming. Once those are in, a quick update here will get it merged!

**Comment by rahman** [comment]
Thanks @scanlonp. The CodeBuild step failed due to an `unsafe-perm` flag which appears to be fixed in #28068. Will the CodeBuild step need to be manually re-run after that pr has been reviewed and merged?

**Comment by rahman** [comment]
Thanks @scanlonp

**Comment by scanlonp** [comment]
@Mergifyio update

**Pull request merged**
