### PR TITLE
fix(core): incorrect GetParameter permissions in nonstandard partitions

### PR DESCRIPTION
**Pull request by cmckni3**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by cmckni3** [comment]
Fixes bootstrap template for GovCloud and other partitions.

CloudFormation reported the role had invalid permissions for `aws:ssm`.

**Comment by cmckni3** [comment]
Let me know which test(s) if any to update.

**Comment by cmckni3** [comment]
@eladb @NetaNir

**Review by eladb — COMMENTED** [review]
LGTM, @rix0rrr can you take a look?

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
