### PR TITLE
chore(ssm): latest parameter value with dynamic reference

### PR DESCRIPTION
**Pull request by jogold**
CloudFormation now allows referencing the latest Systems Manager parameter
values in templates without specifying parameter versions using dynamic
references.

Remove the "trick" with the `Parameter` using a default value.

See https://aws.amazon.com/about-aws/whats-new/2021/04/now-reference-latest-aws-systems-manager-parameter-values-in-aws-cloudformation-templates-without-specifying-parameter-versions/

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
⚠️ **This will influence the following behavior**:

https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/aws-cdk/lib/api/deploy-stack.ts#L220-L227

and

https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/aws-cdk/lib/api/util/cloudformation.ts#L427-L432

= stacks that previously had Parameters with default values to reference latest SSM parameters where never skipped now they will be...

**Comment by jogold** [comment]
> ⚠️ **This will influence the following behavior**:
> 
> https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/aws-cdk/lib/api/deploy-stack.ts#L220-L227
> 
> and
> 
> https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/aws-cdk/lib/api/util/cloudformation.ts#L427-L432
> 
> = stacks that previously had Parameters with default values to reference latest SSM parameters where never skipped now they will be...

Decided to not skip deploy if a `{{resolve:ssm:param}}` is detected in the template.

**Review by MrArnoldPalmer — APPROVED** [review]

**Comment by mjgp2** [comment]
Hi @jogold 

This change doesn't work if you are trying to update a stack without changing the template, because CF does not register these `{{ssm}}` template values as parameters, and so will not you create a changeset because it thinks nothing has changed as it doesn't seem to be smart enough to determine that there is a change? This fundamentally breaks a CI pattern we have where we are updating the SSM value for a ECR image, and then updating the stack using the current template via AWS CLI.

**Comment by jogold** [comment]
@MrArnoldPalmer what do you think?

I understand how it breaks things here for this use case but on the other hand the new behavior is more deterministic which is more in line with how the CDK normally behaves?

@mjgp2 how are you updating the SSM value? manually and then you don't want to copy the new version in your stack?

**Comment by mjgp2** [comment]
SSM values can be updated by a whole bunch of processes within Ops. The main thing for us it to be able to apply these SSM parameters to an existing cloudformation stack as part of automation (such as CI or release processes) but guarantee no change in the stack other than the parameters. Difference IAM roles are allowed to update certain SSM parameters than update a stack.

It seems fundamentally that perhaps this is a cloudformation issue, because my expectation (even without using CDK) would be that I can refresh the parameters in a stack. This inline syntax does not allow it.

As this is a breaking change I would very much suggest that there is the option for either underlying CF template to be generated while CF sorts out the differences between the parameter behaviour and the inline template behaviour.

**Comment by mjgp2** [comment]
Thanks for this @jogold - I'm not sure that the CF team realises this difference in behaviour. Seems very odd!

**Pull request merged**
