### PR TITLE
fix(ecs): ec2Service placement strategies use incorrect casing which causes drift

### LINKED ISSUE #20812: aws_ecs: ec2Service placement strategies use incorrect casing which causes drift
### Describe the bug

When adding the packedByCpu() PlacementStrategy to a new ecs service, the cf template generated has the Property 
```json
"PlacementStrategies": [{
    "Field": "cpu",
    "Type": "binpack"
}]
```
However this will cause the Stack to drift as CF only allows CPU spelled in uppercase.
See here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-placementstrategy.html

### Expected Behavior

CDK should generate the "Field" attribute of "PlacementStrategies" according to CF demands.

In the CF Template PlacementStrategies should look like this:
```json 
"PlacementStrategies": [{
    "Field": "CPU",
    "Type": "binpack"
}],
```

### Current Behavior

CDK generates  the "Field" attribute of "PlacementStrategies" NOT according to CF demands but instead spells it in lowercase.

In the CF Template PlacementStrategies actually looks like this:
```json 
"PlacementStrategies": [{
    "Field": "cpu",
     "Type": "binpack"
}],
```

### Reproduction Steps

1. Generate a fresh cdk project with `cdk init app --language=typescript -j`

2. in the lib/project-name-stack.ts  add a ecs service to a cluster with the PlacementStrategy set:

```typescript
import { aws_ecs, aws_ec2, Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';

export class VanillaCdkStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const vpc = new aws_ec2.Vpc(this, 'Vpc', { maxAzs: 2 });

    const cluster = new aws_ecs.Cluster(this, 'EcsCluster', { vpc });
    cluster.addCapacity('DefaultAutoScalingGroup', {
      instanceType: aws_ec2.InstanceType.of(aws_ec2.InstanceClass.T2, aws_ec2.InstanceSize.MICRO)
    });

    const taskDefinition = new aws_ecs.Ec2TaskDefinition(this, 'TaskDef');
    const container = taskDefinition.addContainer('web', {
      image: aws_ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
      memoryLimitMiB: 256,
    });

    const service = new aws_ecs.Ec2Service(this, "Test_Stack",{
      cluster,
      taskDefinition,
      placementStrategies: [
        aws_ecs.PlacementStrategy.packedByCpu(), // <--- here
      ]
    });
  }
}
```

3. run cdk synth

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.28.1 (build d035432)

### Framework Version

_No response_

### Node.js Version

v16.14.2

### OS

Windows 10 Enterprise 21H2

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tea-418**
Fixes #20812 

Switches lowercase cpu and memory placement strategy to uppercase as required by cloudformation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-placementstrategy.html

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by peterwoodworth — DISMISSED** [review]
It seems we aren't testing this property in any integration tests yet - we should be testing deployment of all properties we set. Could you whip up a quick[ integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md), or edit an existing one to use this property?

**Comment by tea-418** [comment]
Hey @peterwoodworth Thanks for your response!
I tried creating an integ test. Unfortunately I am unable to run it myself since I dont have no personal account and the one from work is a bit restrictive. 

If you could run the test it would also be greatly appreciated. 
I am not the best integration tester so any adjustment also would be greatly appreciated. 

If you have any questions to my code do not hesitate to ask. I tried orienting myself on other integ tests but didnt really find alot using assertions.
Anyway thanks in advance!
Cheers

**Comment by peterwoodworth** [comment]
Thanks @tea-418, I'll get to this next week!

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
