### PR TITLE
feat(eks): Make kubectl provider work with any aws-iam-authenticator enabled cluster

### PR DESCRIPTION
**Pull request by anguslees**
Previously, the kubectl custom resource (aka `KubernetesManifest`,
`HelmChart`) _only_ worked against true EKS clusters, even though the
only EKS-specific step was 'logging in' to the cluster.

Now the kubectl provider is passed `~/.kube/config` directly and thus
supports any Kubernetes cluster that can be described without
additional dependencies.  In practice this means any cluster that uses
`aws-iam-authenticator` (eg: EKS, kops on AWS) or kubectl-builtin
methods such as x509 client certificates.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by anguslees** [comment]
Note: I'm passing a ~40-line text blob through a single lambda parameter, and I think reasonable people could dislike that.  Let me know if you want me to use some other method (S3 object?) instead.

**Comment by iliapolo** [comment]
@anguslees This looks super interesting. Something doesn't add up though, the `KubectlProvider` still accepts an `ICluster` - Are you instantiating an `ICluster` for non EKS clusters?

**Comment by iliapolo** [comment]
don't close just yet

**Comment by anguslees** [comment]
> Are you instantiating an ICluster for non EKS clusters?

Yes.  I don't want to, if you have another 'abstract Kubernetes cluster' type that I should use.

**Comment by anguslees** [comment]
ping @iliapolo.  Is the fact I'm using `ICluster` a blocker for this PR?

**Comment by iliapolo** [comment]
> ping @iliapolo. Is the fact I'm using `ICluster` a blocker for this PR?

No. I just wanted to make sure I understood it correctly. Like you pointed out, I'm also not in love with having to create a fake `ICluster` - but we can address this in a separate PR. 

My intuition says we should probably extract the provider into a separate module, independent of `@aws-cdk/aws-eks`, and this PR is a big step closer to that.

> Note: I'm passing a ~40-line json blob through a single lambda parameter, and I think reasonable people could dislike that. Let me know if you want me to use some other method (S3 object?) instead.

Not ideal but i'm also not too worried about that - I don't see that config becoming a monster, and it does avoid us from having to deal with assets and downloads in the handler itself. We can always circle back to that if necessary.

> Also the "kubeConfig" probably belongs as a property on eks.ICluster, perhaps instead of kubectlRole. I didn't want to modify the public interface in this PR, and I acknowledge the current KubectlProvider.kubeConfigFor(cluster) seems a bit out of place as a result. Suggestions welcome.

Yeah, I don't see a way out of having a `kubeConfig` property on `ICluster`. We can't change the `ICluster` API since this module is now stable, so we can only add it and support both use cases, with the appropriate validations. I wonder though, without this property, how will you be able to actually use the change you are proposing? the current `kubeConfigFor` always creates an EKS specific config due to the `eks get-token` call.

Am I missing something? Or are you planning a subsequent PR?

**Comment by anguslees** [comment]
> how will you be able to actually use the change you are proposing? the current `kubeConfigFor` always creates an EKS specific config due to the `eks get-token` call.

Oh, that's an excellent question! :sweat_smile:

For my specific use case, this is sufficient, because my cluster is also running `aws-iam-authenticator` but is not EKS.  So the `aws eks get-token` command does the right thing (it ignores the cluster name and just uses the role, fyi), provided I avoid the `aws eks update-kubeconfig` call that existed before this PR.

I had sort of thought this PR also made it possible for other uses, by just using `KubectlProvider` directly.  But I see `KubectlProvider` is private, and the new `kubeConfig` property can't easily be overridden, so I failed at that goal. :disappointed: ...  I think I should make `KubectlProvider` public, and accept `kubeConfig` as a constructor option - does that sound reasonable?

**Comment by iliapolo** [comment]
@anguslees 

> aws eks get-token command does the right thing (it ignores the cluster name and just uses the role, fyi)

Strange, so it ignores the cluster name even though `--cluster-name` is a required option? 
Also - are you just passing some random string as the cluster name in your case? 

> I think I should make KubectlProvider public, and accept kubeConfig as a constructor option - does that sound reasonable?

For the longer term it does. But not as part of this PR. It would open up a rather large surface area to something we had always considered private until now. So it requires some more thought in my opinion. 

I think we should just rephrase this PR as `Support any aws-iam-authenticator enabled cluster`, rather than `Any non EKS cluster` - which i'm cool with since I imagine its a quite common scenario for k8s on AWS. 

I'm good with starting to review this but i'd like to fully understand this `aws eks get-token` call before that.

**Comment by iliapolo** [comment]
dont close

**Comment by anguslees** [comment]
> Strange, so it ignores the cluster name even though --cluster-name is a required option?
> Also - are you just passing some random string as the cluster name in your case?

Correct, it ignores the cluster name.  I can't tell you why it's implemented this way.
And yes, I just pass in the name of the CDK construct, which is basically just a random string when the construct is not a real EKS cluster.

> I think we should just rephrase this PR as Support any aws-iam-authenticator enabled cluster, rather than Any non EKS cluster - which i'm cool with since I imagine its a quite common scenario for k8s on AWS.

sgtm.

> I'm good with starting to review this but i'd like to fully understand this aws eks get-token call before that.

I suggest you start reading at https://github.com/kubernetes-sigs/aws-iam-authenticator, since `aws eks get-token` is basically a wrapper/reimplementation of `aws-iam-authenticator token`

**Comment by anguslees** [comment]
> it ignores the cluster name

I should correct the above.  The cluster-name _is_ used by iam-authenticator, but it's just an arbitrary string that has to match on client and server (to prevent reusing a token against multiple clusters).  On EKS, it's the real EKS cluster name, but on a DIY setup it can be any value you choose to use as the iam-authenticator config `clusterID`.

**Comment by TheRealAmazonKendra** [comment]
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

**Pull request closed without merging**
