### PR TITLE
feat(docdb): cluster - deletion protection

### PR DESCRIPTION
**Pull request by cjihrig**
This commit adds support for `deletionProtection` on docdb `DatabaseCluster`s.

Fixes: https://github.com/aws/aws-cdk/issues/15170

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by peterwoodworth — APPROVED** [review]
This looks good, thank you for adding this!

**Comment by cjihrig** [comment]
Thanks @peterwoodworth. Is there anything else that I need to do here to get this landed?

**Comment by cjihrig** [comment]
ping?

**Comment by skinny85** [comment]
@cjihrig like the failing check says:

```
Error: Features must contain a change to a README file
```

So, you need to update the ReadMe file to mention this new feature 🙂.

**Comment by cjihrig** [comment]
@skinny85 updated the README, PTAL.

**Comment by skinny85** [comment]
@peterwoodworth is the one doing the review, I'll leave the final word to him 🙂.

**Review by peterwoodworth — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
