### PR TITLE
feat(neptune-alpha): engineVersion v1.3

### LINKED ISSUE #28648: (neptune-alpha): support for engine version v1.3
### Describe the feature

Neptune has released engine v1.3. We would like to make CDK compatible with this version as well.
https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases.html

### Use Case

Creating v1.3 engine Cluster

### Proposed Solution

Update [EngineVersion](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-neptune-alpha/lib/cluster.ts#L18) and [ParameterGroupFamily](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-neptune-alpha/lib/parameter-group.ts#L8) enums.

A detailed description of v1.3 follows.
engineVersion: https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases-1.3.0.0.html
parameterGroupFamily: https://docs.aws.amazon.com/neptune/latest/userguide/parameter-groups.html

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.116.1

### Environment details (OS name and version, etc.)

irrelevant

### PR DESCRIPTION
**Pull request by badmintoncryer**
This PR implements support for the [v1.3 engine](https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases-1.3.0.0.html).

Closes #28648.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by go-to-k — CHANGES_REQUESTED** [review]
Thanks for this PR. I made a few comments.

**Comment by go-to-k** [comment]
The PR title would be `feat(neptune-alpha): engineVersion v1.3`.

**Comment by badmintoncryer** [comment]
@go-to-k Thank you for your continuous reviews! I have completed the modifications.

**Review by go-to-k — APPROVED** [review]
Looks good!

**Review by kaizencc — APPROVED** [review]

**Pull request merged**
