### PR TITLE
fix(eks): eks.AccessEntryType.STANDARD maps to a wrong value

### PR DESCRIPTION
**Pull request by naaandor**
### Reason for this change

Tried making use of the `eks.AccessEntry` construct, with the `eks.AccessEntryType.STANDARD` as accessEntryType, but the stack deployment failed with the following error: `AccessEntry type must be one of [EC2_LINUX, EC2_WINDOWS, FARGATE_LINUX, STANDARD]`.

Seems like 'Standard' is not alright, suggested also by `eksctl` [docs](https://eksctl.io/usage/access-entries/#iam-entities).

If this is the case, documentation in the following places also needs to be corrected:

- https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateAccessEntry.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-accessentry.html
- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.CfnAccessEntry.html#construct-props

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ncsereoka** [comment]
Exemption Request

**Comment by pahud** [comment]
Thank you for the heads-up.

>The type of the new access entry. Valid values are Standard, FARGATE_LINUX, EC2_LINUX, and EC2_WINDOWS.


Looks like we need to get the [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-accessentry.html#cfn-eks-accessentry-type) fixed.

**Comment by pahud** [comment]
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/2116

**Comment by xazhao** [comment]
Hi @ncsereoka , thanks for raising the PR. Could you please add an integration test to make sure the new value can be deployed?

**Review by xazhao — DISMISSED** [review]
LGTM. Thanks for adding the integration test

**Review by paulhcsun — APPROVED** [review]

**Comment by paulhcsun** [comment]
@mergifyio update

**Pull request merged**
