### PR TITLE
feat(stepfunctions): add IntrinsicFunction class

### PR DESCRIPTION
**Pull request by w-haibara**
Add `IntrinsicFunction` class for generate [intrinsic function](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html) strings. This makes it possible to define functions more clearly.

When defining complex functions such as the following, programmers had to check the syntax by themselves.
```typescript
const fn = "States.Format('1={}, 2={}', States.JsonToString($.path1), States.Format('3={}', $.path2))";
```

By introducing this class, we can leave the complicated grammar checking to the interpreter.
```typescript
const fn = IntrinsicFunction.StatesForamt('1={}, 2={}',
      IntrinsicFunction.StatesJsonToString('$.path1'),
      IntrinsicFunction.StatesForamt('3={}', '$.path2'));
```

### CODE REVIEW

**Comment by pahud** [comment]
Hi @yamatatsu , wdyt?

**Comment by yamatatsu** [comment]
Hi @w-haibara! I am happy to see more Japanese committers.

It is needed to change the base branch to `master` instead of `v2-main`. In aws-cdk, PRs is merged into the branch `master`, and merging into `v2-main` is automated as [these PRs](https://github.com/aws/aws-cdk/pulls?q=is%3Apr+sort%3Aupdated-desc+base%3Av2-main).

**Comment by w-haibara** [comment]
Hi @yamatatsu. Thank you for checking!

> It is needed to change the base branch to master instead of v2-main
I will fix it.

**Comment by yamatatsu** [comment]
@w-haibara Sorry, my advice was not enough...
It is needed to following works:
- rebase on master
- or, create new branch from master, commit your 3 files and re-create new PR

Because, if my guess is right, This branch `w-haibara:v2-main` already (before you commited) include some commits that should not be merged into `master`.

**Comment by w-haibara** [comment]
@yamatatsu I've just realized my misunderstanding 💦 
Thank you very much for your kind explanation. I will re-create a new PR.

**Pull request closed without merging**
