### PR TITLE
feat(bedrock): additional foundation models

### PR DESCRIPTION
**Pull request by mazyu36**
Add some missing foundation models IDs.

```sh
% aws bedrock list-foundation-models --region us-west-2 | jq -r '.modelSummaries[].modelId'
```

The following models are missing:

* anthropic.claude-3-5-sonnet-20241022-v2:0:18k
* anthropic.claude-3-5-sonnet-20241022-v2:0:200k
* anthropic.claude-3-5-sonnet-20241022-v2:0:51k
* meta.llama3-3-70b-instruct-v1:0
* stability.sd3-5-large-v1:0
* stability.stable-image-core-v1:1
* stability.stable-image-ultra-v1:1

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — COMMENTED** [review]
Maybe better to create a single PR given that https://github.com/aws/aws-cdk/pull/32597 is not yet merged 🤔

**Comment by mazyu36** [comment]
@lpizzinidev 
Thanks. I’ve merged #32597 changes to this PR.

**Review by GavinZZ — DISMISSED** [review]

**Comment by GavinZZ** [comment]
@mergifyio requeue

**Comment by mazyu36** [comment]
@mergifyio update

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍

**Review by kaizencc — APPROVED** [review]

**Pull request merged**
