### PR TITLE
feat(bootstrap): add permission boundary to roles created in CDK bootstrap related to #12207

### PR DESCRIPTION
**Pull request by greg-aws**
A new feature to add permission boundaries to CDK roles created during modern bootstrapping.  The argument `--permission-oundary-policy-arn` can be used in order to input the policy arn of the permission boundary

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
(Clicked close accidentally)

**Comment by greg-aws** [comment]
Hello, yes I agree this is somewhat niche and it is aimed at allowing developers who are already governed by specific permission boundaries to bootstrap their accounts. The same could be solved using `--template`, so if you think this is unneeded bloat I would understand. This is something my organization would benefit from, however I can see how the vast majority of users would not utilize this feature.

 I think that the [PermissionBoundary ](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.PermissionsBoundary.html)class does a fairly good job of addressing your first bullet.

**Comment by rix0rrr** [comment]
> I think that the [PermissionBoundary ](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.PermissionsBoundary.html)class does a fairly good job of addressing your first bullet.

The bootstrap template would still need to be updated to make it easy to force the use of permissions boundaries though. Or is that also typically done using SCPs?

> If you think this is code bloat which wont be widely used I am happy to close the PR, let me know.

I was hoping for you to turn it into the other feature :). But I'm afraid I don't know enough about SCPs to judge what the best user experience would be (yet). Can you enlighten me?

**Comment by greg-aws** [comment]
> 
> 
> > I think that the [PermissionBoundary ](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.PermissionsBoundary.html)class does a fairly good job of addressing your first bullet.
> 
> The bootstrap template would still need to be updated to make it easy to force the use of permissions boundaries though. Or is that also typically done using SCPs?
> 
Currently custom policies would need to be passed in through --cloudformation-execution-policies to enforce the permission boundary.

I think I see what you are getting at. So instead of just using the AdministratorAccess policy for the CloudFormation Execution Role we could add an additional policy which denies the creation of IAM Roles or Users if a permission boundary is not applied.

I'd be happy to take that on.

**Comment by greg-aws** [comment]
> > I think that the [PermissionBoundary ](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.PermissionsBoundary.html)class does a fairly good job of addressing your first bullet.
> 
> The bootstrap template would still need to be updated to make it easy to force the use of permissions boundaries though. Or is that also typically done using SCPs?
> 
> > If you think this is code bloat which wont be widely used I am happy to close the PR, let me know.
> 
> I was hoping for you to turn it into the other feature :). But I'm afraid I don't know enough about SCPs to judge what the best user experience would be (yet). Can you enlighten me?

After thinking about this some more I am going to withdraw this pull request. I think that using `--template` or `--cloudformation-execution-policies` will provide the best user experience in both of the bullet points you outlined above. 

Applying a permission boundary to the CDK roles as I did will limit what the CDK Roles can do, but the same thing can be achieved using the parameters I mentioned above. 

For the second bullet point you brought up, additionally policies could be added to the default bootstrap roles to enforce permission boundaries on any IAM users or roles that are created, but I think if a user is limiting those then the default AdminPolicy would likely need to be modified as well. At this point I think we are getting into a level of customization where using the existing flags makes the most sense.

**Pull request closed without merging**
