### PR TITLE
feat(athena): L2 WorkGroup construct

### PR DESCRIPTION
**Pull request by Stacy-D**
Closes https://github.com/aws/aws-cdk/issues/12599
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by iliapolo** [comment]
@njlynch Thanks :)

**Review by njlynch — COMMENTED** [review]
Thanks for the contribution!

You've picked a really ...interesting... resource to build an L2 for. The model of having "creation" and "update" properties is more or less unprecedented. I really think the right API for this is to paper over the complexity of the create/update properties and provide a simplified interface for the users, but that's going to require some tricks.

A few high-level options spring to mind, most of which involve using a Custom Resource in some capacity to make a `GetWorkGroup` API call to determine if the WorkGroup already exists or not, and then use that information to do the right thing. That could be used to set a parameter in a nested stack where the real work group is created, or perhaps the Custom Resource itself actually just calls CreateWorkGroup or UpdateWorkGroup directly rather than driving via CloudFormation. 

The absolute base level -- but I still think an improvement -- would be to expose only a single set of properties plus a boolean "isFirstDeployment" that defaults to false and can be set to true for the first deployment. That's certainly the simplest to implement, but I think not as elegant a customer experience.

Think about it a bit, and let's discuss what makes sense moving forward.

**Review by njlynch — CHANGES_REQUESTED** [review]
Nothing new to say, just marking the correct status. :) 
Let me know how I can help.

**Comment by Stacy-D** [comment]
I'll get to it soon and do some trials with custom resource based implementation.

**Comment by Stacy-D** [comment]
Hey @njlynch, here's my first take on WorkGroup backed by Custom Resource as opposed to using cloudformation which turned out to be unusable for this case.

 I decided on using 2 custom resources one to manage the workgroup itself and second to query for the attributes as the response body of update/create requests for workgroup is empty. However, even with using `getWorkgroup` I didn't manage to retrieve creationTime attribute which, according to [API reference ](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Athena.html#getWorkGroup-property) should be returned in `WorkGroup.CreationTime`. When using it,  I get `vendor response doesn't contain attribute` error and function logs don't show `CreationTime` attribute:
```
{
    "Status": "SUCCESS",
    "Reason": "OK",
    "PhysicalResourceId": "MyWorkgroup4C023E07Lookup",
    "StackId": "<id>",
    "RequestId": "5f608529-5c67-4623-8863-8b3f80dd3af9",
    "LogicalResourceId": "MyWorkgroupLookup59B9953E",
    "NoEcho": false,
    "Data": {
        "apiVersion": null,
        "region": "us-east-1",
        "WorkGroup.Name": "some-workgroup",
        "WorkGroup.State": "ENABLED",
        "WorkGroup.Configuration.ResultConfiguration.OutputLocation": "s3://some-bucket",
        "WorkGroup.Configuration.ResultConfiguration.EncryptionConfiguration.EncryptionOption": "SSE_KMS",
        "WorkGroup.Configuration.ResultConfiguration.EncryptionConfiguration.KmsKey": "arn:aws:kms:us-east-1:123456:key/key",
        "WorkGroup.Configuration.EnforceWorkGroupConfiguration": true,
        "WorkGroup.Configuration.PublishCloudWatchMetricsEnabled": true,
        "WorkGroup.Configuration.RequesterPaysEnabled": true,
        "WorkGroup.Configuration.EngineVersion.SelectedEngineVersion": "Athena engine version 2",
        "WorkGroup.Configuration.EngineVersion.EffectiveEngineVersion": "Athena engine version 2",
        "WorkGroup.Description": "A test workgroup"
    }
}
```

Also regarding the policies used in the two custom resources. I tried using `AwsCustomResourcePolicy.fromSdkCalls({ resources: [this.workgroupArn] })` for both resources separately to ensure the correct permissions granted, but it didn't go as planned. Using separate policies results in ` Failed to create resource. User: arn:aws:sts::123456:assumed-role/aws-workgroup-integ-AWS679f53fac002430cb0da5b7982b-1HJRTJD3RE6ZB/aws-workgroup-integ-AWS679f53fac002430cb0da5b7982b-1C4165SZG6Z13 is not authorized to perform: athena:GetWorkGroup on resource: arn:aws:athena:us-east-1:1234567:workgroup/some-workgroup`, even though the permissions look correctly setup. I suspect there's some race condition happening during the deployment that results in the function using the role with incomplete permissions(might be similar to https://github.com/aws/aws-cdk/issues/12945). As I didn't have any idea of how to solve it, for now I've supplied the extended permissions to both resources.

Let me know what do you think about this approach.

**Comment by njlynch** [comment]
We're still working with the WorkGroup team internally to improve this model so this PR can be much more straightforward. In the meantime, since this current form of the PR likely isn't going to reflect the end-result and we're not making any forward progress, I'm going to close this out.

Looking forward to working with you to re-create this once the underlying model has been fixed!

**Pull request closed without merging**
