### PR TITLE
feat(lambda-nodejs): external and install modules

### LINKED ISSUE #6323: @aws-cdk/aws-lambda-nodejs doesn't build functions with native modules
I'm trying to get a lambda set up with @aws-cdk/aws-lambda-nodejs.

I applied the change mentioned in #6274, and now I have a build error:

Error: Failed to build file at [my lambda function]: Error: 🚨  [project path]/node_modules/pg/lib/native/client.js:11:21: Cannot resolve dependency 'pg-native'

### Reproduction Steps

Use `"pg": "7.18.1"`, then in the source of the lambda:

```typescript
import * as pg from 'pg';
```

### Error Log

Error: Failed to build file at [my lambda function]: Error: 🚨  [project path]/node_modules/pg/lib/native/client.js:11:21: Cannot resolve dependency 'pg-native'

### Environment

  - **CLI Version      :** 1.24.0
  - **Framework Version:** 1.24.0
  - **OS               :** OS X 10.15.3
  - **Language         :** Typescript

### Other

I'm familiar with how to work around this error in Webpack, but given that Parcel is a zero config tool, I'm not sure what to do about this error.

I think connecting to RDS databases from Node Lambdas will be a common use case, so this should be supported out of the box if possible, or at least have a documented solution.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
### Commit Message
feat(lambda-nodejs): external and install modules (#7870)

Add support for:
* external modules: modules that should not be bundled. Defaults to 'aws-sdk'.
Can be used for modules already included in a Layer.
* install modules: modules that should not be bundled but included in the
`node_modules` folder of the Lambda package. Those modules are installed in a
[Lambda compatible Docker container](https://github.com/lambci/docker-lambda)
with the right installer (`npm` or `yarn`) based on lock file detection.

Closes #6323
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by orangewise** [comment]
@jogold will this PR also help us in solving errors with node built-ins? Like this one:

Error: [Status 1] stdout: 🚨  /project/node_modules/bluebird/js/release/promise.js:34:12: Cannot resolve dependency 'async_hooks'
  32 | };
  33 | var AsyncResource = util.isNode && util.nodeSupportsAsyncResource ?
> 34 |     require("async_hooks").AsyncResource : null;
     |            ^
  35 | var getContextAsyncHooks = function() {
  36 |     return {
  37 |         domain: getDomain(),

**Comment by jogold** [comment]
@orangewise Yes, it should do it with `externalModules: ['async_hooks']`.

**Comment by orangewise** [comment]
Awesome @jogold , appreciate your contributions a lot.

**Comment by jogold** [comment]
Not ready yet, there's an issue with the parcel plugin here. Investigating.

**Comment by orangewise** [comment]
Nice, hope it will be available soon 👍

**Comment by orangewise** [comment]
Hi @jogold I see you closed this issue. Not sure if I understand how this get's merged now ;) Will it?

**Comment by jogold** [comment]
I prefer to get #7898 merged first, then I can go back to this.

**Pull request closed without merging**
