### PR TITLE
feat(step-functions): Add timeoutPath and heartbeatPath to task-base

### LINKED ISSUE #15531: (aws-stepfunctions): Support dynamic Task timeouts (TimeoutSecondsPath/HeartbeatSecondsPath)
Amazon States Language supports dynamic Task state timeout and heartbeat configurations by the `TimeoutSecondsPath` and `HeartbeatSecondsPath` properties respectively. `TimeoutSecondsPath` has the same effect as `TimeoutSeconds` but reads the seconds value at runtime from the state input using JSONPath. This is not supported in CDK without a CustomState.

- https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html
- https://states-language.net/spec.html#task-state

### Use Case

Allows CDK users to specify Task state timeout and heartbeat settings at runtime instead of hardcoding static values in the state machine definition.

### Proposed Solution

* Option 1 - Expose explicit `timeoutPath` and `heartbeatPath` in [TaskBaseProps](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions/lib/states/task-base.ts)

```javaScript
const myTask = new EcsRunTask(scope, "MyTask", {
    ...
    timeoutPath: JsonPath.numberAt("$.myTimeoutInSeconds")
    ...
});

// OR

const myTask = new EcsRunTask(scope, "MyTask", {
    ...
    timeoutPath: "$.myTimeoutInSeconds"
    ...
});
```

* Option 2 - Use the existing `timeout` and `heartbeat` properties and append "Path" to the generated ASL if the provided value is JSONPath, similar to how Parameters works in [json-path.ts](https://github.com/aws/aws-cdk/blob/94f81c441f9e2cb8dc70eb2e772d2cd75e468b67/packages/%40aws-cdk/aws-stepfunctions/lib/json-path.ts)

```javaScript
const myTask = new EcsRunTask(scope, "MyTask", {
    ...
    timeout: JsonPath.numberAt("$.myTimeoutInSeconds")
    ...
});
```

Both would render the same ASL:

```json
{
  "Type": "Task",
  "Resource": "...",
  ...
  "TimeoutSecondsPath": "$.myTimeoutInSeconds",
  ...
}
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by hutchy2570**
Adds the ability to specify `timeoutPath` and `heartbeatPath` in Step Functions tasks.  Fixes #15531.

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hutchy2570** [comment]
I didn't see any existing integration tests around the existing timeout/heartbeat properties, so not sure if this needs to update any integration tests.  The unit tests have been updated to verify the new properties are mapped to the correct JSON output.

**Comment by hutchy2570** [comment]
@BenChaimberg you asked to review this contribtion in https://github.com/aws/aws-cdk/issues/15531#issuecomment-882755205 (But that was over a year, apologies if you're not working on CDK any more)

**Comment by jakejscott** [comment]
@hutchy2570 Wahoo, thanks for taking a look at this one. We just ran into this issue recently and would love to see this get implemented!

**Comment by hutchy2570** [comment]
This pr is awaiting review, please see my earlier comment about integration tests

**Pull request closed without merging**
