### PR TITLE
chore: update eslint rule to allow max 1 empty line

### PR DESCRIPTION
**Pull request by kaizencc**
There should be no reason to have back-to-back new lines which our current eslint rules allow. I made the rule stricter and fixed instances where we were breaking the stricter rule.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by kaizencc** [comment]
I added `cli-integ-tested` to get past the linter but I didn't actually integ test the cli changes. That is because the only thing this PR changes is removal of excess new lines. No code was changed from this PR

**Comment by rix0rrr** [comment]
What's the reason behind this change?

**Comment by kaizencc** [comment]
> What's the reason behind this change?

Just personal preference. I suppose we should take this up as a vote, since the value we get is "i dislike seeing extra new lines that are unnecessary and try to fix them when i see them" but the unvalue is that we will receive more linter errors now.

**Comment by mrgrain** [comment]
No opinion here. But while you're add it, can you force a newline at the end of each file? ;P

**Review by comcalvi — APPROVED** [review]

**Pull request merged**
