### PR TITLE
feat(ec2): return NAT gateway info in VPC construct

### LINKED ISSUE #10616: [aws-ec2] expose NatGatewayId from VPC
Expose NatGatewayId from the VPC construct.

### Use Case

I'm building a dashboard and need access to the NatGatewayId in order to access the metrics

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by yuimam**
Fixes #10616 

example:
```typescript
const vpc = new Vpc(stack, 'TheVPC');
const natGateways = vpc.natGateways.map(nat => ({
  id: nat.natGatewayId,
  availabilityZone: nat.availabilityZone
}));
```
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — DISMISSED** [review]
I'm not inclined to accept this. I would like to keep the surface area of Vpc small and if you really need this, you can assign `NatGatewayProvider` to an object and after instantiating the VPC read the `configuredGateways` property directly.

**Comment by yuimam** [comment]
OK, then how about this approach?

**Comment by rix0rrr** [comment]
Can you help my understand why it is so important to have this available directly on the Vpc construct? Feels to me that if it's available on an external collaborating class, that is preferable?

**Comment by yuimam** [comment]
I checked the solution in the original issue, and I noticed that I missed that way.
Close this PR.

**Pull request closed without merging**
