### PR TITLE
fix(eks): fix helm deploy login for public ECR repositories

### LINKED ISSUE #23977: aws-eks: OCI HelmChart from public.ecr.aws only works in us-east-1
### Describe the bug

I'm trying to add a HelmChart from the public.ecr.aws OCI repository to a stack deployed in us-west-2 and am getting this error.

```
Received response status [FAILED] from custom resource. Message returned: Error: b'\nAn error occurred (UnsupportedCommandException) when calling the GetAuthorizati
onToken operation: GetAuthorizationToken command is only supported in us-east-1.\nLogin Succeeded\nError: public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart:0.1.
5: not found\n'  
```

### Expected Behavior

I expect the chart to install without error.

### Current Behavior

Failing with the following error.

```
Received response status [FAILED] from custom resource. Message returned: Error: b'\nAn error occurred (UnsupportedCommandException) when calling the GetAuthorizati
onToken operation: GetAuthorizationToken command is only supported in us-east-1.\nLogin Succeeded\nError: public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart:0.1.
5: not found\n'  
```

### Reproduction Steps

The HelmChart used looks like this. Stack was deployed into us-west-2.

```ts
        const chart = new eks.HelmChart(this, 'Resource', {
            cluster: cluster,
            chart: 'apigatewayv2-controller',
            version: '0.1.5',
            repository: 'oci://public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart',
            namespace: NAMESPACE,
            values: {
                cloudProvider: 'aws',
                awsRegion: cluster.env.region,
                autoDiscovery: {
                  clusterName: cluster.clusterName,
                },
                rbac: {
                  serviceAccount: {
                    create: false,
                    name: this._service_account.serviceAccountName,
                  },
                },
                metrics: {
                  enabled: true,
                },
              },
            });
```

### Possible Solution

Change this line of code https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py#L113

to

```python
region = 'us-east-1'
```

### Additional Information/Context

According to the Amazon ECR public registries documentation the region should always be us-east-1 for the `ecr-public get-login-password` operation.

https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth
_When authenticating to a public registry, always authenticate to the us-east-1 Region when using the AWS CLI._

### CDK CLI Version

2.62.2 (build c164a49)

### Framework Version

_No response_

### Node.js Version

v14.21.2

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

4.7.4

### Other information

_No response_

### PR DESCRIPTION
**Pull request by zorrofox**
fix helm deploy login for public ECR repositories

I have tested this issue fixed in `us-east-1` and `us-west-2` integ testing for
```
yarn integ-runner integ.eks-helm-asset.js --force --parallel-regions us-east-1
yarn integ-runner integ.eks-helm-asset.js --force --parallel-regions us-west-2
```

Closes #23977.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thank you for your contribution! This is close. See: https://github.com/aws/aws-cdk/pull/23176.

**Comment by zorrofox** [comment]
Do I need create new Integ testing for this? I know there already have a pull request for this bug. But #23176 not be merged.

**Comment by TheRealAmazonKendra** [comment]
> #23176

No need, the integ test covers this. Any test that would prove a failure would fail the test as well. Adding an exemption.

**Comment by otterley** [comment]
I'd like to request this be merged ASAP. Currently no version of Karpenter newer than 0.17 (which is rather old now) can be installed by a CDK app because of the issue being fixed by this PR.

**Comment by TheRealAmazonKendra** [comment]
> I'd like to request this be merged ASAP. Currently no version of Karpenter newer than 0.17 (which is rather old now) can be installed by a CDK app because of the issue being fixed by this PR.

It still requires the role to be added. We will review it once it's been completed and marked as ready.

**Comment by TheRealAmazonKendra** [comment]
The integ tests will need updating. If you need assistance running them, please let me know.

**Comment by zorrofox** [comment]
@TheRealAmazonKendra the commits need rerun 9 integ testings and 7 have passed, but `integ.alb-controller` and `integ.eks-service-account-sdk-call` run into failed because Pinger test error. But I don't think these issues are caused by these modifications and both integ testings will run into errors even no these commits. Can you clarify this?

**Comment by otterley** [comment]
@zorrofox @TheRealAmazonKendra These two tests have proved to be extremely flaky and racy. @pahud and I have had to re-run them multiple times to get a passing result.

I believe you can merge this request if these are the only two tests that are failing.

**Comment by zorrofox** [comment]
I will mark the PR as ready for review! Thanks, @otterley .

**Comment by TheRealAmazonKendra** [comment]
> @zorrofox @TheRealAmazonKendra These two tests have proved to be extremely flaky and racy. @pahud and I have had to re-run them multiple times to get a passing result.
> 
> I believe you can merge this request if these are the only two tests that are failing.

We cannot merge failing tests. It will fail in the pipeline.

**Review by TheRealAmazonKendra — DISMISSED** [review]
@zorrofox, if you can resolve the merge conflicts, I can help troubleshoot on the tests.

**Comment by otterley** [comment]
@TheRealAmazonKendra They were already (often) failing before this merge. The situation is identical to how it would have been pre-merge. Those failing tests should never have been merged in the first place; delaying a subsequent PR that made no effective changes to its behavior is unfair to those waiting on a solution.

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra They were already (often) failing before this merge. The situation is identical to the status quo ante. Those failing tests should never have been merged in the first place; delaying a subsequent PR that made no effective changes that possibly could have affected their behavior is unfair to those waiting on a solution.
> 
> I'd support cleaning up the mess post-merge, however.

We simply cannot merge a PR with failing tests. Our cicd workflow disallows it. We will not be merging this until the tests pass. As I said, I'll help troubleshoot but we will not be merging this until we have succeeding tests.

**Comment by otterley** [comment]
I would recommend disabling or removing the broken tests, then, because they were always broken. This PR, and all subsequent PRs related to this code, should not become an innocent victim of someone else's mistake.

**Comment by pahud** [comment]
I have fixed the integ tests errors in https://github.com/aws/aws-cdk/pull/24276 and we can get it merged first to help this PR move forward.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
Oh good god, more merge conflicts. I'll help get these resolved since this keeps happening.

**Comment by zorrofox** [comment]
@TheRealAmazonKendra I handled the conflicts.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
