### PR TITLE
feat(assets): replace docker build with docker buildx build

### LINKED ISSUE #12472: (assets): allow user to pass platform option to Docker builds
### Use Case

To be able to build images for `amd64` architecture (e.g. AWS Fargate) on a system that is using other architecture like `arm64` (e.g. Apple M1).

### Proposed Solution

Replace `docker build` with `docker buildx build`.

https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images

With `buildx` you can build cross-platform images by declaring `--platform` argument. e.g. `docker buildx build --platform linux/amd64 someimage:sometag .` executed on system Apple M1 results in an image which works system with `amd64` architecture.

`buildx` allows you also to build image for multiple platforms at once. e.g. `--platform linux/amd64,linux/arm64`

### Other

Currently image `.fromAsset` results in an image that works only on the same architecture where it was built. In that sense, this could be considered also a bug – the image built doesn't work on the target system (Fargate).

```ts
import { FargateTaskDefinition, ContainerImage } from '@aws-cdk/aws-ecs';

const taskDefinition = new FargateTaskDefinition(this, 'TaskDefinition');

taskDefinition
  .addContainer('Container', {
    image: ContainerImage.fromAsset(path.resolve(__dirname, '../image')),
  });
```

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by relm923**
Convert `docker build` command to `docker buildx build` and add a `platform` parameter to enable building images for multiple platforms/architectures

Closes #12472

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by relm923** [comment]
Failing due to `buildx` not being available in CodeBuild. This is passing locally

**Review by eladb — CHANGES_REQUESTED** [review]
This needs to be an opt-in feature and not the default behavior, especially this is an experimental docker feature, so I think we will likely need to add an option to `options` that will enable this behavior.

**Comment by relm923** [comment]
> This needs to be an opt-in feature and not the default behavior, especially this is an experimental docker feature, so I think we will likely need to add an option to `options` that will enable this behavior.

Happy to make it opt-in or at least conditional on passing the `platform` option once I get everything working

I need to get `buildx` working in CI first though. Where is [/root/ecr-proxy/start.sh](https://github.com/aws/aws-cdk/blob/master/buildspec-pr.yaml#L11) defined?

**Comment by eladb** [comment]
> I need to get buildx working in CI first though. Where is /root/ecr-proxy/start.sh defined?

We won't be able to get that running. Let's just write a unit test to verify that the correct command is called.

**Comment by relm923** [comment]
I have the correct command being called but I'm not clear on the relationship between `ContainerImage.fromAsset()` and `BundlingDockerImage.fromAsset()`

**Comment by eladb** [comment]
@relm923 I am closing this PR for now. Please reopen when ready to continue

**Pull request closed without merging**
