### PR TITLE
fix(pipelines): artifact bucket permissions missing for in-account deployments

### LINKED ISSUE #15307: (cli): CDK Pipeline in account bootstrapped with 1.110.0 (bootstrap version 7): S3 Access Denied
CDKPipeline fails with S3 Access Denied error when account has been bootstrapped with `aws-cdk@1.110.0` (bootstrap version 7).

If I downgrade my CDK CLI to 1.108.0, bootstrap again (bootstrap version 6) and push a change through the pipeline it completes successfully.

### Reproduction Steps

Minimal cdk pipeline repo here: https://github.com/cogwirrel/minimal-cdk-pipeline-ts

`npm i -g aws-cdk@1.110.0`
`cdk bootstrap`
`cdk deploy`
`git remote add cc codecommit://MyRepo` (requires [git-remote-codecommit](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-git-remote-codecommit.html))
`git push cc mainline`

Observe error in the pipeline:

```
Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: ZE8ZB6NBMFEY4F6F; S3 Extended Request ID: t9dE+lUpj3K+CKD87YAPLOT0i2pD8CIqoTJv+KxBZQ6S84nM05bpPHzq0EhdNyjs8L00lSrR9wg=; Proxy: null)
```

### What did you expect to happen?

Empty CDK Pipeline to deploy successfully

### What actually happened?

"Prepare" step for the pipeline stage failed with an S3 Access Denied error.

### Environment

  - **CDK CLI Version  :** 1.110.0
  - **Framework Version:** 1.110.0
  - **Node.js Version:**  14.17.0
  - **OS               :** macOS Big Sur (11.4)
  - **Language (Version):**  Typescript 4.3.2

### Other

Possibly related to https://github.com/aws/aws-cdk/pull/15192 ?

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
A recent change to the default `deploy-role` policies required that the
required permissions statements are added to the artifacts bucket
instead.

This happened to be working for stacks which had NO `account` env property
set, but not for stacks that DID have an `account` property set which
was the same as the pipeline's account property.

Ultimately this was caused by an account comparison deep in the bowels of the
Grants system, which happened to work out because in cases of mismatched
accounts it would think there was a cross-account access and it was trying to
add permissions to both principal and resource. But in this case, it's much more
accurate to say that we can NEVER add permissions to the `deploy-role`, and
instead always want the permissions added to the bucket (rather than dropping
them).

Fixes #15307.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by skinny85 — COMMENTED** [review]
@rix0rrr I wonder: shouldn't we simply always return `statementAdded: false` in `addToPrincipalPolicy()` for immutable Roles? What's the consequence of changing this behavior now?

**Comment by rix0rrr** [comment]
> @rix0rrr I wonder: shouldn't we simply always return `statementAdded: false` in `addToPrincipalPolicy()` for immutable Roles? What's the consequence of changing this behavior now?

It would add the permissions to the resource always, which may or may not be intended. Bit dangerous to change.

**Review by skinny85 — APPROVED** [review]
My opinion of this change is that I would switch to return `statementAdded: false` always for immutable Roles. I think this actually makes sense, because the statements are not added to an immutable Role. So I would consider the current behavior a bug.

I really don't like the addition of the `addGrantsToResources` property. I understand that it's the only way to do this in a fully, 100% backwards-compatible way, but I think it's a confusing and weird property, and makes the IAM library more complicated than it should be.

However, since you're the owner of both of these libraries, the ultimate decision is yours to make. I don't have any comments on the actual code (assuming you disagree with me that the current behavior of returning `statementAdded: true` for immutable Roles is a bug), so I'm approving the PR.

I trust you to make the decision you think is best 🙂.

**Comment by rix0rrr** [comment]
I think it still makes sense to give this control to users, but I agree with you that in an ideal world the defaults would have been reversed.

Fortunately, by adding this flag we now have a clear mechanism of how to do that: a feature flag that controls the default of this property.

**Pull request merged**
