### PR TITLE
fix(aws-lambda-nodejs): Default entry finding when Node returns paths starting with file://

### LINKED ISSUE #21630: aws-lambda-nodejs: Default entry finding fails when defining file starts with "file://"
### Describe the bug

Attempting to create a lambda with NodejsFunction, which should auto find the handler based on the defining files path.  

I get an error that looks like this: 

```
Error: Cannot find handler file file:///Users/stack.handler.ts, file:///Users/<path>/stack.handler.js or file:///Users/<path>/stack.handler.mjs
```

where the middle of the path has been replaced with <path> for brevity and privacy. 

[This](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L189) implies the paths being checked start with "file://", which I've tested and does not work with Node 16.13.1.

Those paths are produced from [this function](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L195-L211), which I believe is incorrect.  

This is running on macos 12.5, with the a fore mentioned version of nodejs. 

### Expected Behavior

I expected it to find the file, as the path was correct without the `file://` prefix.  

### Current Behavior

Error: Cannot find handler file file:///Users/stack.handler.ts, file:///Users/<path>/stack.handler.js or file:///Users/<path>/stack.handler.mjs

### Reproduction Steps

Create a lambda function using `NodejsFunction` with no `entry` parameter specified, and synthesize. 

### Possible Solution

`callsites()` produces paths that start with file:// when they are local files, and `findDefiningFile` doesn't scrub the path. Maybe make findDefining file remove the prefix when it's `file://`

### Additional Information/Context

_No response_

### CDK CLI Version

2.37.1 (build f15dee0)

### Framework Version

_No response_

### Node.js Version

16.13.1

### OS

macos 12.5

### Language

Typescript

### Language Version

4.7.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by okko**
Fixes #21630.

Stack filenames contain `file://` prefix in ES module files. This removes the prefix for Node compatibility.

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by okko** [comment]
@corymhall Please advice if I should change `findEntry` to be exported so that I can add tests for this case. I'm not sure how to create a test scenario using only the currently exported `NodejsFunction`.

**Comment by corymhall** [comment]
> Please advice if I should change `findEntry` to be exported so that I can add tests for this case. I'm not sure how to create a test scenario using only the currently exported `NodejsFunction`.

I think we can add a test in `function.test.ts`. It seems like all that is needed to reproduce the issue is to have a `package.json` with `"type": "module"`. If that is the case we could just add new test directory with a `package.json` and handler file.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
I would like to see an integration test for this. It's not part of our PRLinter just yet (change coming soon) but we are now requiring integ tests on fixes.

**Comment by okko** [comment]
An integration test would require the test tooling to compile the test case project to ESM and then synthesize that. I believe that would require a separate package.json, tsconfig.json, jest config, cdk.json that executes ts-node in esm mode, and hooking that into the way the tests run. I'm not familiar enough with the aws-cdk development tooling to do all of that, and I think that shouldn't be in the scope of this fix. I have provided all the needed files at https://github.com/okko/aws-cdk-esm-file-urls-reproduce for reference.

At the moment this blocks us from using NodejsFunction with a project compiling to ESM.

**Comment by corymhall** [comment]
> An integration test would require the test tooling to compile the test case project to ESM and then synthesize that. I believe that would require a separate package.json, tsconfig.json, jest config, cdk.json that executes ts-node in esm mode, and hooking that into the way the tests run. I'm not familiar enough with the aws-cdk development tooling to do all of that, and I think that shouldn't be in the scope of this fix. I have provided all the needed files at [okko/aws-cdk-esm-file-urls-reproduce](https://github.com/okko/aws-cdk-esm-file-urls-reproduce) for reference.

We should update the `integ.esm.ts` integration test as part of this PR. Right now it is just using the `test/integ-handlers/esm.ts` as the entry, but we should be able to add a subfolder `test/integ-handlers/esm/esm.ts` and add a package.json

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Putting this back into changes requested in regard to updating the test.

**Comment by VladimirGrenaderov** [comment]
@okko any updates? Tricks with 'entry: new URL(import.meta.url.replace(/(.*)\.(.+)/, `$1.${id}.$2`)).pathname' are so ugly.

**Comment by TheRealAmazonKendra** [comment]
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

**Pull request closed without merging**
