### PR TITLE
feat(cloudwatch): Add L2 Construct for Insight Rule

### PR DESCRIPTION
**Pull request by seanyles-amzn**
To address the issue https://github.com/aws/aws-cdk/issues/13005 we need to have a L2 construct for the CloudWatch Insight Rule. This PR  continues #21861 but only the Insight Rule Construct. I have the widget code in another branch that I can PR later as requested in the previous PR.

Per our discussion in the previous comment https://github.com/aws/aws-cdk/pull/21861#issuecomment-1242122584 we will use the prior PR as the design doc for this L2. Will fix all building error and convert this PR as ready to review

### CODE REVIEW

**Comment by pahud** [comment]
I will help @seanyles-amzn on this PR.

**Comment by seanyles-amzn** [comment]
Hi @[kaizencc](https://github.com/kaizencc) can you take a first look before I start writing the tests

**Comment by pahud** [comment]
Thanks for your contribution. Looks like your PR still needs an integ test and multiple unit tests but I think you can continue that after the maintainer takes a first look.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
We will not have the capacity to provide a review on this until all checks pass and there is proper unit test coverage. Putting this into draft until that time. Please mark this as ready once those things have been completed.

**Pull request closed without merging**
