### PR TITLE
docs: update package name in docs to v2

### LINKED ISSUE #18980: (cloudfront): V1 cloudfront origins reference in v2 cloudfront docs
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront-readme.html#creating-a-distribution

### Describe your issue?

In the developer docs for v2 of the cdk it states: 
`Constructs to define origins are in the @aws-cdk/aws-cloudfront-origins module.`
This makes reference to v2 of the API, and has been replaced by it's own module on `aws-cdk-lib`. 
As expected this gives types errors on Typescript due to the mismatch of cdk libraries. 
That line should be removed or modified to point to the correct v2 reference.

### PR DESCRIPTION
**Pull request by claraberendsen**
Fixes #18980 by updating documentation to reference V2 API and keeps a comment for V1 API users.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by claraberendsen** [comment]
@peterwoodworth definitely, can see to work on it this weekend. As someone that uses the cdk on a daily basis, with all the ongoing changes that it has (which are great, because it means it's improving) this issues in the docs, even though minor, lend themselves to produce confusion (and more open issues). 
In the long run, maybe it will be better to have the ability to reference different docs according to the version of the api. I'm not sure of what changes that would mean to the repo, but I think would provide more readability and sustainability to the docs. 
Meanwhile, I can do the manual work of looking for similar cases :wink:

**Comment by peterwoodworth** [comment]
I was thinking the same thing - however I personally have no idea how feasible the idea is to show different package name depending on which doc you're referencing. That's something that I was going to look at on my end 🙂 

If not, IMO we should just prefer the most recent package name, because when we stop supporting v1 then that sidenote would quickly become outdated

**Review by peterwoodworth — CHANGES_REQUESTED** [review]
Sorry for the wait here, let's just stick with only the raw text of the new module name 🙂

**Comment by tim-finnigan** [comment]
Hey @peterwoodworth I was wondering how come we want raw text for the new module name when the other one is in markdown?

**Pull request closed without merging**
