### PR TITLE
chore: correct v2 init templates

### PR DESCRIPTION
**Pull request by nija-at**
Two corrections here -

* Python module name has changed from aws_cdk_lib to aws-cdk-lib.
* Maven, .NET and Python do not recognize semver version ranges. 
  Translate them into appropriate version ranges.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by eladb — CHANGES_REQUESTED** [review]
Do we really want to remove the version specifier altogether or just rewrite the spec to be compatible with maven/pypi syntax?

@RomainMuller ?

**Comment by RomainMuller** [comment]
So in `pom.xml`, not specifying is the "standard" way to do things. It creates a "loose" requirement (i.e: it is used unless another requirement was specified earlier in the dependency tree).

I think this is perhaps "more idiomatic" Java...

**Comment by nija-at** [comment]
@eladb - updated to retain version range information.

**Review by eladb — APPROVED** [review]
looks awesome. @RomainMuller I think we should have some code like this in jsii, should we extract to a separate module/library that can be reused here and there?

**Pull request merged**
