### PR TITLE
feat(appconfig): inline YAML support for hosted configuration

### PR DESCRIPTION
**Pull request by chenjane-dev**
Adding an additional helper for using inline content for a YAML config

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by chenjane-dev** [comment]
`Exemption Request`: No update to README, as this feature has very niche utility

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Thanks, looks good to me.

Documentation about `ConfigurationContent` methods should be added [here](https://github.com/aws/aws-cdk/blob/fce26b635d0ef2c443ca6d4e390a90f586130f05/packages/%40aws-cdk/aws-appconfig-alpha/README.md?plain=1#L85C1-L85C1).

Suggestion:

> You can define a hosted configuration content using `ConfigurationContent` methods:
> * `fromFile` - Defines the hosted configuration content from a file.
> * ...

**Review by lpizzinidev — APPROVED** [review]

**Review by sumupitchayan — APPROVED** [review]
Thanks for your contribution!

**Comment by vinayak-kukreja** [comment]
@Mergifyio update

**Review by sumupitchayan — APPROVED** [review]

**Pull request merged**
