### PR TITLE
feat(elasticloadbalancingv2): dualstack NetworkLoadBalancer

### LINKED ISSUE #27538: ElasticLoadBalancingV2: add dualstack NetworkLoadBalancer creation
### Describe the feature

Currently it is not possible to create a dualstack Network Load Balancer with the higher level construct, it is only possible with the lower level CfnLoadBalancer resource. Dualstack Network Load Balancers were introduced ~3 years ago. 

### Use Case

It is not possible to create a dualstack Network Load Balancer with the higher level construct. It is only possible with the lower level CfnLoadBalancer resource. There are limitations to the CfnLoadBalancer resource; it doesn't have an ARN property, it is not a valid RecordTarget. 

### Proposed Solution

add ipAddressType property to NetworkLoadBalancer. This is implemented for Application Load Balancers so can reference its implementation. 

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.99.1

### Environment details (OS name and version, etc.)

Amazon Linux 2 aarch64 5.10 Kernel

### PR DESCRIPTION
**Pull request by lpizzinidev**
Adds support for dual-stack NetworkLoadBalancer via the [`ipAddressType`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-ipaddresstype) property.

Example:
```
const lb = new elbv2.NetworkLoadBalancer(this, 'LB', {
  vpc,
  internetFacing: true
  ipAddressType: elbv2.IpAddressType.DUAL_STACK,
});
```

Also, added validation to enforce that UDP or TCP_UDP listeners cannot be added to a dualstack NLB.

Closes #27538.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jaredlundell** [comment]
Dualstack NLBs are not required to be internet-facing.  The only requirement is that the subnets it is placed in support IPv6.  See https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-ip-address-type.html

**Comment by lpizzinidev** [comment]
@jaredlundell 
Thanks for the feedback.
I added the validation because of the helper shown on the console when creating a NLB:

Screenshot 2023-10-19 at 08 46 04


> If the load balancer is an internal load balancer, or if you add a UDP or TCP_UDP listener, you must choose IPv4.

Not sure if I misinterpreted it or if there is a documentation inconsistency.

**Review by kylelaker — APPROVED** [review]
This is really cool to have! Thanks for the work on this!

**Comment by jaredlundell** [comment]
Looks like that help info in the console is incorrect.  Here's a screenshot from the console of an Internal, Dualstack NLB, so it's definitely possible:

image

**Comment by lpizzinidev** [comment]
@jaredlundell 
👍 I'll adapt the implementation, thanks!

**Review by sumupitchayan — DISMISSED** [review]

**Comment by sumupitchayan** [comment]
@Mergifyio update

**Review by kaizencc — DISMISSED** [review]
Was previously approved

**Review by kaizencc — APPROVED** [review]

**Pull request merged**
