### PR TITLE
chore(iam): correct spelling in documentation

### PR DESCRIPTION
**Pull request by LuisValdesZero**
chore(iam):  correct spelling in documentation

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — APPROVED** [review]

**Comment by mrgrain** [comment]
@kavichu Thanks for the fix. For future reference: Please do not update the branch from main, unless there are merge conflicts. It just makes everything more complicated for us since any previous reviews will be revoked etc.

**Review by mrgrain — APPROVED** [review]

**Comment by kavichu** [comment]
> @kavichu Thanks for the fix and updating the branch!
> 
> In this case it was needed. But just for future reference: Normally you should not update the branch from main, unless there are merge conflicts. It just makes everything more complicated for us since any previous reviews will be revoked etc.

@mrgrain Sorry for that, I am really into learning the workflow. I thought it would update my fork branch and then hit back to this PR, thanks for the explanation.

**Comment by mrgrain** [comment]
> > @kavichu Thanks for the fix and updating the branch!
> > In this case it was needed. But just for future reference: Normally you should not update the branch from main, unless there are merge conflicts. It just makes everything more complicated for us since any previous reviews will be revoked etc.
> 
> @mrgrain Sorry for that, I am really into learning the workflow. I thought it would update my fork branch and then hit back to this PR, thanks for the explanation.

All good! In this situation we did hit one of the two scenarios where an update is required.

It's more of an FYI. Unfortunately GitHub has this shiny "Update branch" button that we cannot disable. 😅 
If you ever want to update for any other reason, you can comment `@mergifyio update` and the automation will take over.

**Comment by kavichu** [comment]
> > > @kavichu Thanks for the fix and updating the branch!
> > > In this case it was needed. But just for future reference: Normally you should not update the branch from main, unless there are merge conflicts. It just makes everything more complicated for us since any previous reviews will be revoked etc.
> > 
> > 
> > @mrgrain Sorry for that, I am really into learning the workflow. I thought it would update my fork branch and then hit back to this PR, thanks for the explanation.
> 
> All good! In this situation we did hit one of the two scenarios where an update is required.
> 
> It's more of an FYI. Unfortunately GitHub has this shiny "Update branch" button that we cannot disable. 😅 If you ever want to update for any other reason, you can comment `@mergifyio update` and the automation will take over.

Awesome, next time I know about `@mergifyio update` and  that the shiny button is there only trick you into click it and see what happens. Deep inside I wanted to know what will happen.

**Pull request merged**
