### PR TITLE
feat(events): make target optional in `onXxx()` methods

### LINKED ISSUE #2913: `target` should be made optional in `OnEventOptions`
https://github.com/awslabs/aws-cdk/blob/60f46c830e7e27dd8d5339c53166a07174ce3a4b/packages/%40aws-cdk/aws-events/lib/on-event-options.ts#L7-L16

Making `target` optional allows to use the rule returned by the `onXxx()` in another construct that will call `addTarget()`.

```ts
const onCommitRule = repo.onCommit('CommitEvent'); // event pattern is correctly set up
                                                   // don't want to set the target here

const other = new ComplexConstructThatCallsAddTarget(this, 'Complex', {
  rule: onCommitRule
});
```

### PR DESCRIPTION
**Pull request by jogold**
Make `target` optional in `OnEventOptions` so that it is no required when calling a `onXxx()`
method.

This allows to use "preconfigured" rules in other constructs.

Update `awslint:events-method-signature` to enforce optional `options` parameter in `onXxx()` method signatures.

Closes #2913

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by jogold** [comment]
> Is it valid to provision a Rule without any targets?

Yes

**Comment by eladb** [comment]
Okay, so let’s just add a test

**Comment by eladb** [comment]
It’s fishy that nothing broke at the consumption side when this changes from required to optional. I’d expect some null check...

**Comment by jogold** [comment]
> It’s fishy that nothing broke at the consumption side when this changes from required to optional. I’d expect some null check...

https://github.com/awslabs/aws-cdk/blob/83eee09e8198ae1921b932c09a6d14c88392800d/packages/%40aws-cdk/aws-events/lib/rule.ts#L115-L127

There's one already

**Comment by jogold** [comment]
> Okay, so let’s just add a test

https://github.com/awslabs/aws-cdk/blob/83eee09e8198ae1921b932c09a6d14c88392800d/packages/%40aws-cdk/aws-events/test/test.rule.ts is full of rules created without targets, what kind of test do you want to add? something in the `onXxx()` method of another package ?

An extra test in `rds` without target?
https://github.com/awslabs/aws-cdk/blob/83eee09e8198ae1921b932c09a6d14c88392800d/packages/%40aws-cdk/aws-rds/test/test.instance.ts#L315-L319

**Comment by eladb** [comment]
Yes sounds good. Just to exercise this specific path

**Pull request merged**
