### PR TITLE
chore: added links to the relevant aws cdk workshop tutorials in v2 sample-app readme for the various languages

### PR DESCRIPTION
**Pull request by damogallagher**
When getting started with the AWS CDK, it is useful to have links to a good tutorial to help learn the tool.
This pr adds links to the generated README.md files for the V2 sample apps in order to access the CDK Workshops.
This is a trivial addition but may help folks who are unaware that the CDK Workshops exist

@peterwoodworth I forgot to add these links for the V2 app so created a separate PR

### CODE REVIEW

**Comment by xrn** [comment]
@damogallagher what about golang?

**Comment by damogallagher** [comment]
> @damogallagher what about golang?

There is no sampel apps in the v2 folder for golang

**Comment by peterwoodworth** [comment]
We're still not entirely sure what we're going to do for the workshop with v2. I'll keep this open as a reminder, and I'll give updates when they're ready

**Comment by peterwoodworth** [comment]
Closing because we have this on the backlog internally. Thanks for the PR!

**Pull request closed without merging**
