### PR TITLE
chore(codegen): add Type Annotation

### PR DESCRIPTION
**Pull request by tokkiyaa**
Add Type Annotations to codegen to public method, exported funcion.
Also I added annotation to private method where there is typed annotated private method in the same file.
Also I added annotation to non-exported function where there is typed annotated non-exported function in the same file.

----

Please read the [contribution guidelines](https://github.com/awslabs/aws-cdk/blob/master/CONTRIBUTING.md) and follow the pull-request checklist.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
Very true. May I ask for some motivation for submitting this PR?

**Comment by tokkiyaa** [comment]
For just making it easy to read codegen!

**Comment by rix0rrr** [comment]
I have to confess I'm ambivalent about this change. I like type inference to do as much work for me as possible.

But  I guess it doesn't hurt too much either...

**Comment by rix0rrr** [comment]
I will let other devs chime in with their opinion.

**Comment by RomainMuller** [comment]
I am all for annotating the return type of all `public` members, but I don't care much for `private` ones. My motivation here is that `public` is a contract, so it must be tight and changes to it should be intentional.

Private stuff is implementation details and I'd much rather let inference do it's job there, unless those cases where the function is very long / complex, and it's hard to determine the formal result type.

I don't mind merging this PR though - the work has been done, and it's easy to remove the type annotation later if the result of those methods becomes... more complicated. I wouldn't however encourage people to spend effort to this effect in the future.

**Pull request merged**
