### PR TITLE
chore: transform private references to be local

### PR DESCRIPTION
**Pull request by RomainMuller**
In order for dependabot to be able to identify package updates, it needs
to be able to resolve all packages in the dependency closure. Private
packages are not published to the npmjs.com registry and fail resolving.

This changes the private packages to use local path references within
the mono-repo, so that dependabot can work normally. This can also
enable standard use of `npm audit`.

----

Please read the [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) and follow the pull-request checklist.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by CaerusKaru** [comment]
Have you considered switching to [Renovate](https://renovatebot.com/) instead?

**Comment by RomainMuller** [comment]
@CaerusKaru I haven't looked there at this point. Dependabot having been acquired by GitHub makes it an easy go-to, and for now I've had a pretty positive experience... but if it turns out too constraining, alternatives will be investigated as they deserve!

**Comment by CaerusKaru** [comment]
One of the main benefits is that Renovate supports Lerna out of the box, so you don’t need such a large commit to get it to work. Plus it’s  also on the GitHub Marketplace, so at worst it’s  one click Moreno to install than Dependabot (not to mention that just because GitHub bought it, doesn’t make it the best :wink:)

**Comment by RomainMuller** [comment]
@CaerusKaru - Those changes make sense to me and I have wanted to get them done a long while ago...

**Pull request merged**
