### PR TITLE
fix(acm): validated certificate survives eventual consistency in service

### LINKED ISSUE #3527: aws-certificatemanager DnsValidatedCertificateHandler fails on missing DomainValidatedOptions
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Underlying Lambda implementation of DnsValidatedCertificate construct does not correctly handle response from describeCertificate call and fails in situations where DomainValidations are not present on the first attempt.

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L107

* **What is the expected behavior (or behavior of feature suggested)?**
It should properly validate the response and break the while loop after a number of attempts.

### PR DESCRIPTION
**Pull request by michirue**
The `DomainValidationOptions` array could be empty, which would make the custom resource fail.

Handle that case, and limit the amount of retries.

Fixes #3527.

----

Please read the [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) and follow the pull-request checklist.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hoegertn** [comment]
I think 

```js
await sleep(Math.random() * (Math.pow(attempt, 2) * 100));
```

should be 

```js
await sleep(Math.random() * (Math.pow(2, attempt) * 100));
```

Can you add this fix? Then my PR is obsolete.

**Comment by hoegertn** [comment]
Next thing is that it only uses the first DomainValidation. If there are more ResourceRecords to set (e.g. for SANs) they are not populated in R53.

**Comment by michirue** [comment]
> I think
> 
> ```js
> await sleep(Math.random() * (Math.pow(attempt, 2) * 100));
> ```
> 
> should be
> 
> ```js
> await sleep(Math.random() * (Math.pow(2, attempt) * 100));
> ```
> 
> Can you add this fix? Then my PR is obsolete.

Agree. Changed to 2^attempt.

**Comment by michirue** [comment]
> Next thing is that it only uses the first DomainValidation. If there are more ResourceRecords to set (e.g. for SANs) they are not populated in R53.

Yes, it should also support providing a SAN/HostedZoneId map instead of a single hosted zone to cover all ACM/Route53 certificate creation scenarios.

**Comment by stephankaag** [comment]
I had to adjust the max attempts to 5 before it worked for me, but after that, it worked 👍

**Pull request merged**
