### PR TITLE
chore(ecs-patterns): expose EcsTask object on ScheduledFargateTask tasks

### PR DESCRIPTION
**Pull request by luads**
I was searching for a way to fetch the Security Group of a `ScheduledFargateTask` object and couldn't find it. The `EcsTask` object allows us to access the Security Group, but it's not currently exposed for this object.

----
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by luads** [comment]
@MrArnoldPalmer just rebased with master, could you please do a review on this one?

**Comment by SoManyHs** [comment]
Hi @luads, would you mind adding tests to this change? Thanks!

**Comment by luads** [comment]
@SoManyHs any recommendations of what to test here? I'm basically adding a property that needs to be populated. It has no effect on the resources or stack output. 

I've tried simply asserting that the `this.ecsTask` object is of type `EcsTask` but the assertion lib is not compatible with simple jest assertions, and honestly I don't see the value in adding that type of test.

**Comment by SoManyHs** [comment]
Duplicated of https://github.com/aws/aws-cdk/issues/14971, addressed by https://github.com/aws/aws-cdk/pull/15127

**Pull request closed without merging**
