### PR TITLE
feat(step-functions): Making the StateMachine more subclassable 

### PR DESCRIPTION
**Pull request by mbonig**
----

I wanted to make a simple subclass of the StateMachine construct without having to rewrite it but the constructor wasn't laid out in a way that made that easy, so I make a couple of simple changes that push the creation of some resources into protected methods so that subclasses can easily override just what they need.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by kaizen3031593** [comment]
@mbonig can you explain your use case a bit more for me? I'm having trouble understanding why/when would you need to subclass `StateMachine` beyond what we already have in [`StateMachineFragment`](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-stepfunctions#state-machine-fragments).

**Comment by mbonig** [comment]
> @mbonig can you explain your use case a bit more for me? I'm having trouble understanding why/when would you need to subclass `StateMachine` beyond what we already have in [`StateMachineFragment`](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-stepfunctions#state-machine-fragments).

Please take a look at this construct: 
https://github.com/mbonig/state-machine/


I wanted to create a slight change to how the CfnStateMachine was created and couldn't with the current code.

**Comment by kaizen3031593** [comment]
Hi @mbonig, I talked to @rix0rrr about this one and we generally don't encourage subclassing construct libraries in this way. Instead the pattern we go for is to wrap the L1 or L2 construct to achieve what you want. Now, I'm curious if you have a use case that cannot be achieved through wrapping? In particular, I feel like an escape hatch could be used to modify the `CfnStateMachine` however you want.

**Comment by mbonig** [comment]
I had originally tried wrapping the L2, but that didn't work as I don't have an IChainable to pass to the props. I could use the escape hatches, I suppose, but that felt like a last resort. 

What are the issues with just having these few protected methods for creating the constructs?

**Comment by kaizen3031593** [comment]
@mbonig I would say that this simply is a precedent that we don't want to set, because it isn't scalable to redo all our L2s to make them subclassable, when that wasn't a design property we had in mind originally. However, I will tag @rix0rrr who might have more specific ideas on why this is/isn't something we want to do.

btw, I don't think escape hatches are really a last resort. Sounds like they are meant for this use case -- changing the L1 post creation.

**Comment by mbonig** [comment]
>  when that wasn't a design property we had in mind originally.

I'd love to know more about this and why it wasn't considered. This being an OOP-based API I would have thought this was a major consideration.

**Comment by mbonig** [comment]
I did have success in using escape hatches. Although I worry that this doesn't really solve the problem overall, that basic OOP principles are being violated with this library and would be better long-term if things like SOLID were adhered to.

**Comment by mbonig** [comment]
Additionally, there is a nasty little bit of hackery I had to do just to satisfy interfaces:

```
super(scope, id, {
      ...props,
      definition: new Pass(scope, 'Pass'),
    });
    scope.node.tryRemoveChild('Pass');
```

Any recommendations on how to not have to do this?

**Comment by rix0rrr** [comment]
> I had originally tried wrapping the L2, but that didn't work as I don't have an IChainable to pass to the props. I could use the escape hatches, I suppose, but that felt like a last resort.

I don't understand. Why does the following not work?

```ts
class MyStateMachine extends Construct implements IStateMachine {
  constructor() {
    super();
   
    const def = new Pass(this, 'Pass'); // Or whatever

    const machine = new StateMachine(this, 'Default', {
      definition: def,
    });
  }
}
```

> What are the issues with just having these few protected methods for creating the constructs?

From my experience, designing "template hole" classes inevitably becomes a mess where the superclass is forced to be aware of all of its implementors and change becomes hard or impossible. This pattern also suffers from the framework problem where the subclass *really* would love to be in charge of the main control flow, but can't because the superclass is actually in charge of control flow. 

Sometimes out of convenience I will design complex inheritance hierarchies, but they never cross a module boundary and aren't part of the public contract, so that when I inevitably code myself into a corner I at least have the opportunity to tear it all up and redo it; something that would not be possible if we make it part of the public contract.

Ideally, it should not be necessary to do what you want to do with inheritance. If it is, we should talk about what it is you cannot achieve by composition, and address that instead.

**Comment by mbonig** [comment]
> ```ts
> class MyStateMachine extends Construct implements IStateMachine {
>   constructor() {
>     super();
>    
>     const def = new Pass(this, 'Pass'); // Or whatever
> 
>     const machine = new StateMachine(this, 'Default', {
>       definition: def,
>     });
>   }
> }
> ```

Additionally, using composition here doesn't actually meet the interface requirements.

**Comment by rix0rrr** [comment]
> The creation of this Pass feels completely unnecessary. I don't want it, I don't need it. [...] But I have to create it (and then delete it, because I don't want it in my scope at all, since I don't need or want it) just to satisfy the interface of the StateMachine.

In my example, this `Pass` was illustrative. That's where the definition would go.

>  I am going to provide my own ASL. 

Let's talk about that. Where is the ASL coming from? Do you have a JSON file somewhere you just wholly want to substitute in? 

If that is the issue, some `Definition.fromJson()` or `StateMachine.fromJson()` would probably be a better fit?

> I can't meaningfully subclass any of the AWS CDK constructs, seems very anti-OOP 

It comes down to predictability. If we add a number of `protected` methods which are intended to be overridden to modify details of how the construct behaves, then our public API becomes larger, and specifically in a way that's harder to reason about. You might implement any logic in there, calling any methods anywhere on the current object and any other, and we must not make *any* changes anymore that might break you -- without actually knowing what you are doing.

Conversely, any behavior you need should just be achievable using the public API, which is much more tractable. You can call this public method, or not. You can pass this construction property, or not. Those are test cases we can track.

We do support polymorphism, but it will usually be interface-based. So we will accept `IThing`, and anything and anyone can implement an `IThing`. How you get there is an implementation detail. You can get one by subclassing a `Thing` if that works for you, and if not you can wrap a `Thing` and selectively forward part of the interface, or completely reimplement it.

**Comment by mbonig** [comment]
> > The creation of this Pass feels completely unnecessary. I don't want it, I don't need it. [...] But I have to create it (and then delete it, because I don't want it in my scope at all, since I don't need or want it) just to satisfy the interface of the StateMachine.
> 
> In my example, this `Pass` was illustrative. That's where the definition would go.
> 
> > I am going to provide my own ASL.
> 
> Let's talk about that. Where is the ASL coming from? Do you have a JSON file somewhere you just wholly want to substitute in?
> 

The ASL comes from the Workflow Studio. I design my workflows there.

> If that is the issue, some `Definition.fromJson()` or `StateMachine.fromJson()` would probably be a better fit?
> 

That would get me partially there. In my case I'd want to manipulate the json between the step when it's loaded and when the construct is created. See what I've done with it here: https://github.com/mbonig/state-machine/blob/4e671de04508a58eb0209de4355d074885d4aa60/src/StateMachine.ts#L70

> > I can't meaningfully subclass any of the AWS CDK constructs, seems very anti-OOP
> 
> It comes down to predictability. If we add a number of `protected` methods which are intended to be overridden to modify details of how the construct behaves, then our public API becomes larger, and specifically in a way that's harder to reason about. You might implement any logic in there, calling any methods anywhere on the current object and any other, and we must not make _any_ changes anymore that might break you -- without actually knowing what you are doing.
> 
> Conversely, any behavior you need should just be achievable using the public API, which is much more tractable. You can call this public method, or not. You can pass this construction property, or not. Those are test cases we can track.
> 

Isn't that what the Liskov substitution principle is for? Yes, I could create a subclass and I could do whatever I want but you're not responsible for the bad things I decide to do with my code. 


> We do support polymorphism, but it will usually be interface-based. So we will accept `IThing`, and anything and anyone can implement an `IThing`. How you get there is an implementation detail. You can get one by subclassing a `Thing` if that works for you, and if not you can wrap a `Thing` and selectively forward part of the interface, or completely reimplement it.

And there is the rub, yes I *can* wrap, except that loses the original interface. Or, I can reimplement, except now I have completely own another implementation that only diverges in a minuscule way, defeating a huge benefit from OOP. 

The .fromJSON() approach could work, and I'd just have to provide a helper function that would do the substitution, something like:

```ts
const myWorkflow = StateMachine.fromJSON(overrideValues(theWorkflowASL, { ... }));
```

Which only really solves this issue for this very specific use case. More generally, as a principle, the constructs of the CDK are unable to be subclassed in any meaningful way.

Let's say I extend this problem to the VPC construct, if I want to make a slight change to the way subnets are created then I could override the `createSubnets` function (assuming it was protected). I would have to adhere to the contract of that method and would need to ensure it still modified state properly (liskov) but that's on me as the implementor. But I can't, and right now if I want to have the VPC construct and all it's goodness but want to change one small aspect of how it works I cannot. I have to reimplement it from scratch. It just feels like there is a massive opportunity being missed here by having an OOP API but not unlocking one of the most useful aspects to OOP.

**Comment by Naumel** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Pull request closed without merging**
