### PR TITLE
fix(cli): hotswap deploy fails on multiple CfnEvaluationException

### LINKED ISSUE #22323: cli: hotswap deploy fails on multiple CfnEvaluationException
### Describe the bug

When we try to hotswap-deploy but there multiple changes that throw `CfnEvaluationException`, the deployment fails with an error. It seems caused by inappropriate handling of promises.

### Expected Behavior

Deployment successes without error.

### Current Behavior

We get the following error on deployment.

```
/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:294
      throw new CfnEvaluationException(`We don't support attributes of the '${resource.ResourceType}' resource. This is a CDK limitation. ` +
            ^
Error: We don't support attributes of the 'AWS::CloudFront::Distribution' resource. This is a CDK limitation. Please report it at https://github.com/aws/aws-cdk/issues/new/choose
    at EvaluateCloudFormationTemplate.formatResourceAttribute (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:294:13)
    at EvaluateCloudFormationTemplate.findGetAttTarget (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:281:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CfnIntrinsics.Fn::GetAtt (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:174:27)
    at async Promise.all (index 1)
    at CfnIntrinsics.Fn::Join (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:149:31)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at isLambdaFunctionCodeOnlyChange (/Users/cdk/node_modules/aws-cdk/lib/api/hotswap/lambda-functions.ts:185:23)
    at isHotswappableLambdaFunctionChange (/Users/cdk/node_modules/aws-cdk/lib/api/hotswap/lambda-functions.ts:34:28)
```

### Reproduction Steps

1. Deploy the below stack
2. change `literal: '1'` to `literal: '2'`
3. run `npx cdk deploy --hotswap` and you get the error above

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import { BlockPublicAccess, Bucket } from 'aws-cdk-lib/aws-s3';
import { RemovalPolicy } from 'aws-cdk-lib';
import { Distribution } from 'aws-cdk-lib/aws-cloudfront';
import { S3Origin } from 'aws-cdk-lib/aws-cloudfront-origins';

export class LambdaHotswapStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const bucket = new Bucket(this, 'Bucket', {
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    const distribution = new Distribution(this, 'Distribution', {
      defaultBehavior: {
        origin: new S3Origin(bucket),
      },
    });

    const environment = {
      literal: '1',
      // any token that is not supported by evaluate-cloudformation-template.ts
      token: distribution.domainName,
    };

    // this will cause a CfnEvaluationException
    new Function(this, 'Function1', {
      code: Code.fromInline('exports.handler=()=>{}'),
      runtime: Runtime.NODEJS_16_X,
      handler: 'index.handler',
      environment,
    });

    // one more function for a secondary CfnEvaluationException
    new Function(this, 'Function2', {
      code: Code.fromInline('exports.handler=()=>{}'),
      runtime: Runtime.NODEJS_16_X,
      handler: 'index.handler',
      environment,
    });
  }
}
```

### Possible Solution

`CfnEvaluationException` is usually caught here. However If there are multiple ones thrown, the first one is only caught but others do not seem to be handled. I'm not quite sure how it can be generally solved - maybe using `Promise.allSettled` instead of `Promise.all`? That will need a lot of refactor though... I'll investigate about this more later but please let me know if CDK team has already come up with a solution for this kind of issue.

https://github.com/aws/aws-cdk/blob/31012c5e4a3a944796e563fcda8b8d4cff7b949e/packages/aws-cdk/lib/api/deploy-stack.ts#L294-L305

### Additional Information/Context

_No response_

### CDK CLI Version

2.44.0

### Framework Version

2.44.0

### Node.js Version

16.13.1

### OS

macOS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### LINKED ISSUE #22332: (integ-tests): Set environment for Deploy Assert Stack
### Describe the feature

Allow setting the AWS environment (account/region) for the deploy assert stack

### Use Case

I have a construct that uses ELBv2 access logging. ELBv2 access logging requires setting the region for the cdk environment. As showcased by this error

`Error: Region is required to enable ELBv2 access logging`

After setting the environment, I received the following error when I attempted to pass a reference to an Api Call in the Integ Test

`Error: Stack "foo/DefaultTest/DeployAssert" cannot consume a cross reference from stack "bar". Cross stack references are only supported for stacks deployed to the same environment or between nested stacks and their parent stack`

### Proposed Solution

Allow setting the cdk environment in [IntegTestProps](https://github.com/aws/aws-cdk/blob/v1-main/packages/%40aws-cdk/integ-tests/lib/test-case.ts#L116)

### Other Information

_No response_

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.41.0

### Environment details (OS name and version, etc.)

Osx

### PR DESCRIPTION
**Pull request by tmokmss**
closes #22323 

To avoid unhandled rejections, we run promises just before we call `Promise.all`.

The concern of this fix is that hotswap process may take longer time because now async tasks run lazily. However I don't think it will be a big problem since those tasks are not I/O bound, so most of them are already running sequentially, not in parallel.

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by tmokmss** [comment]
> ❌ Fixes must contain a change to an integration test file and the resulting snapshot.

I don't necessarily think we need to change integration tests for this change, but please let me know if we need it 🙏

**Comment by rix0rrr** [comment]
Thanks for the investigation! I'm running it through the CLI pipeline to be sure, then it'll be ready to merge.

**Comment by tmokmss** [comment]
@rix0rrr Hi, I'm pinging you just in case you missed to approved this PR. Thanks!

**Review by rix0rrr — DISMISSED** [review]

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
