### PR TITLE
fix(apigateway): allow importing json schema

### LINKED ISSUE #20055: aws-apigateway: JsonSchema expects type as enum type
### Describe the bug

When hand-writing a schema or importing a schema from somewhere else to use in multiple places, including apigateway, TypeScript rejects the schema:

```
const analyticsEventInputSchema = {
  type: 'object',
  properties: {
    name: { type: 'string' }
  }
}
const analyticsEventModel = api.addModel("AnalyticsEvent", {
  modelName: "AnalyticsEvent",
  contentType: "application/json",
  schema: analyticsEventInputSchema,
});
```

### Expected Behavior

This should just work

### Current Behavior

> Types of property 'type' are incompatible.
> Type '"object"' is not assignable to type 'JsonSchemaType | JsonSchemaType[] | undefined'.

### Reproduction Steps

If the example above is not enough to show the issue, I can create a reproducing repo.

### Possible Solution

Introduce a string union type for `JsonSchemaTypeString` and use it here:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/json-schema.ts#L34

Keep the exported `JsonSchemaType` enum to avoid a breaking change and deprecate it.

### Additional Information/Context

_No response_

### CDK CLI Version

2.20.0

### Framework Version

_No response_

### Node.js Version

16.13.1

### OS

Windows 11

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by dbartholomae**
This fixes #20055 and #20056

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by dbartholomae** [comment]
@peterwoodworth any idea how I can fix the issue? I tried adding an export to the new types, but it seems that `ReadonlyArray` seems to be the problem. I don't understand jsii enough to know how to work around this.

**Comment by dbartholomae** [comment]
(Might also be that it already works and we just need to restart the build job with the newest code)

**Comment by dbartholomae** [comment]
I don't know for local - I am working on Windows and since the repo is heavily relying on Bash, I used the GitPod link to work with the code instead. But in the end the failing build on AWS is what matters, I guess.

**Comment by peterwoodworth** [comment]
I'll try to investigate this later this week @dbartholomae

**Comment by peterwoodworth** [comment]
I've reached out to someone who might know about this. Thanks for your patience here @dbartholomae

**Comment by dbartholomae** [comment]
@peterwoodworth thanks! Anything I need to do to keep the PR alive?

**Comment by dbartholomae** [comment]
@peterwoodworth how to proceed?

**Comment by peterwoodworth** [comment]
@dbartholomae

This won't be an effective way to proceed here. JSII prevents us from using union types due to strongly typed languages (Java, Go) losing compile time safety. On top of this, we can't use private utility types like ReadonlyArray either. (I was right when I said that the existing ones are fine because they aren't customer facing i.e. compiled through JSII)

Instead, a path forward here is to create some new class with a static method which will import a schema and convert it to the `JsonSchema` type. Something like this:

```ts
export class JsonSchemaImporter {
  static fromObj(input: Object): JsonSchema {
    // convert input to JsonSchema type
  }
}
```

I suggest creating a new branch & PR for this. Feel free to reach out to me here or on slack for any more questions!

**Pull request closed without merging**
