### PR TITLE
feat(kms): add HMAC keyUsage and keySpecs to Key

### PR DESCRIPTION
**Pull request by tendermario**
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [no] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by tendermario** [comment]
This adds in the values missing from the Key enums to create an HMAC key, as currently I can created HMAC keys from the interface or CloudFormation, but not from the CDK. Chatting with the team, it sounds like the CF change was recent enough that cdk may be just lagging behind.

---

Despite using ada, I had trouble getting cdk to identify my aws credentials successfully.

"Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment"

If someone could run `yarn integ --update-on-failed integ.key.js` on my behalf, updating the snapshot should be all that's needed.

I could try again on my personal laptop later.

**Comment by tendermario** [comment]
On the linter requiring a readme update, I don't see any mention of RSA/ECC encryption types to wedge something about my change next to it. Not sure this needs a readme update - it's trying to match the doc spec that currently is live: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-kms.CfnKey.html#keyusage-1

**Comment by tendermario** [comment]
I'll ping @Naumel internally about this to perhaps help me get this in.

**Comment by TheRealAmazonKendra** [comment]
We can't provide a meaningful review until the build is passing but please make sure the PR body aligns to the guidelines in our [contributing guide](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md#step-4-pull-request).

**Pull request closed without merging**
