### PR TITLE
chore(deps): Dependabot v1 -> Dependabot v2

### PR DESCRIPTION
**Pull request by sullis**
Dependabot v2 is the successor to Dependabot v1.
    
Dependabot v2 is sometimes described as "GitHub-native" dependabot.
    
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
    
Dependabot 2 uses a different yaml file syntax. Some of the property keys have changed.
    
The v2 file format is documented here:

https://docs.github.com/en/github/administering-a-repository/about-github-dependabot-version-updates

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by sullis** [comment]
> @sullis can you add the motivation, relevant documentation, any other link(s) that capture the changes (i.e. `update_configs` -> `updates`) in syntax and behaviour into the commit body?

I updated the commit message and the PR description.

**Review by RomainMuller — DISMISSED** [review]
Dependabot v2 does not support auto-merge in the same way that v1 did. You also need to update the GitHub action that auto-approves Dependabot PRs so it adds the required command message to trigger the automatic merging by Dependabot itself.

**Comment by sullis** [comment]
I rebased this PR.

**Comment by RomainMuller** [comment]
We have changed the way we operate those, so resolving now. Thank you for your support however!

**Pull request closed without merging**
