### PR TITLE
fix(s3-deployment): User metadata keys have redundant triple `x-amz` prefix

### PR DESCRIPTION
**Pull request by bmwalters**
Without this fix, keys are prefixed with x-amzn-meta- by the TypeScript code,
then the Python code runs and prefixes metadata keys again with x-amz-meta-.
Then, the Python shells out to aws-cli which makes a request to the S3 service.
There, the keys are prefixed *yet again* with x-amz-meta- _unconditionally_.

Thus no matter what keys the user specified, the keys in S3 would be:
x-amz-meta-x-amz-meta-x-amzn-meta-<user input>.

This issue was originally reported as #8459.

#10678 attempted to fix this issue, and fixed the Python, but missed the TS.
It also suffers from the S3 service adding the prefix unconditionally.

After this change, neither the TypeScript code nor the Python code will attempt
to prepend to the metadata key. Instead we rely on the S3 service to do it.

BREAKING CHANGE: User metadata keys of bucket objects will change from `x-amz-meta-x-amz-meta-x-amzn-meta-mykey` to `x-amz-meta-mykey`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by bmwalters** [comment]
Before this change:

image

After this change:

image

Still needs more work...

**Comment by bmwalters** [comment]
@iliapolo @ayush987goyal The `s3` CLI command which the `s3_deploy` lambda shells out to here:
https://github.com/aws/aws-cdk/blob/bf059fad435c5d0edeafd5d545b43d7392620ef3/packages/%40aws-cdk/aws-s3-deployment/lib/lambda/index.py#L178

already adds the `x-amz-meta-` prefix if it's missing. Can we just remove the logic from the TypeScript and Python code that attempts to add the prefix and rely on S3 doing it? Seems simpler and also might be where the snag is.

**Comment by bmwalters** [comment]
Yeah, I confirmed that running

```shell
$ AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=my-profile \
    aws s3 sync ./my-contents/ s3://my-bucket//my-path/ --metadata '{ "x-amz-meta-sourceurl": "static" }'  --metadata-directive REPLACE
```

results in duplicate `x-amz-meta-x-amz-meta-sourceurl`. This means that S3 is adding the prefix for us unconditionally when using the S3 CLI like this.

I'll update this patch to remove adding the prefix in TS and Python entirely.

**Review by iliapolo — COMMENTED** [review]
@bmwalters This is great. It was pretty messy, my only question/concern is how is this going to affect existing objects in the bucket? will their metadata change?

**Comment by bmwalters** [comment]
Yes, the metadata keys will change. For example, to access metadata created by s3-deployment using an SDK:

```swift
// before
let metadata = s3Object.metadata?["x-amz-meta-x-amzn-meta-mykey"]
// after
let metadata = s3Object.metadata?["mykey"]
```

The previous version is awkward so I'm not sure how many users there actually are. If we want to preserve the incorrect metadata keys as well we could internally duplicate each key, so if the user passes in "mykey" they end up with both "x-amz-meta-mykey" and "x-amz-meta-x-amz-meta-x-amzn-meta-mykey". Otherwise this could be listed as a potentially breaking change.

**Comment by iliapolo** [comment]
@bmwalters Ok, lets mention this as a breaking change 👍  

> P.S: Notice there are conflicts needs resolving

**Review by iliapolo — APPROVED** [review]

**Review by iliapolo — APPROVED** [review]

**Pull request merged**
