### PR TITLE
docs(contributing): remove single line breaks to clean up md formatting

### PR DESCRIPTION
**Pull request by evzzk**
### Issue # (if applicable)

Closes #<issue number here>.

### Reason for this change

Before we start making documentation changes, I want to clean up the single line breaks of this document. This will minimize unnecessary noise in future diffs. 

### Description of changes

Removed single line breaks.

### Describe any new or updated permissions being added

<!— What new or updated IAM permissions are needed to support the changes being introduced ? -->

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by kaizencc** [comment]
why the changes to `THIRD_PARTY_LICENSES`?

**Review by rix0rrr — DISMISSED** [review]

**Comment by mrgrain** [comment]
@evzzk I'm not going to die on this hill, but I think this is a much worse reading experience for anyone looking at the source. The rendered markdown is not effected by this at all. I also don't really understand the reason for the change. Sure you want to minimize diffs - but how is that achieving that. 

Standard linter rules usually limit the line length to 80, in other projects we use higher limits but the principle remains the same. Personally I like to write a s single sentence per line. This also makes for a nice diff experience.

PS: The THIRD_PARTY_LICENSES change should be reverted.

**Comment by kaizencc** [comment]
I agree with @mrgrain here. The line breaks are intentional for anyone reading the raw source and imo good sanitary habits for writing markdown files. I do kind of want to die on this hill - it makes my personal experience reading markdown files far worse. I cannot see how this would benefit future changes either.

**Review by kaizencc — CHANGES_REQUESTED** [review]
At the very least this shouldn't be merged until the `THIRD_PARTY_LICENSES` is removed

**Comment by evzzk** [comment]
> PS: The THIRD_PARTY_LICENSES change should not be included here. I guess you probably got this from running a build, this seems like something we need to investigate separately - because it shouldn't have changed.

@mrgrain `THIRD_PARTY_LICENSES` was updated after running `npx lerna run build --skip-nx-cache`. I'll remove it from my PR.

**Comment by evzzk** [comment]
@mrgrain @kaizencc I'm planning on rewriting/restructuring a lot of this doc, so removing single line breaks was for the purpose of minimizing unnecessary noise. For example, if I move a paragraph or section to another part of the doc, but change where the line breaks happen, it'll take a little bit of extra time to make sense of this in the diff. In deciding to do this, my thought was that the rendered markdown isn't affected and IDEs have visual code wrapping features, so I figured the impact on readability was minimal, and that the benefits outweigh the cons. I'm good with going in a different direction though.

If we go to a 'single sentence per line' approach, should we still stay within an 80 character line length limit?

**Comment by mrgrain** [comment]
> > PS: The THIRD_PARTY_LICENSES change should not be included here. I guess you probably got this from running a build, this seems like something we need to investigate separately - because it shouldn't have changed.
> 
> @mrgrain `THIRD_PARTY_LICENSES` was updated after running `npx lerna run build --skip-nx-cache`. I'll remove it from my PR. 

Cool. Thanks for the details!

**Comment by kaizencc** [comment]
> @mrgrain @kaizencc I'm planning on rewriting/restructuring a lot of this doc, so removing single line breaks was for the purpose of minimizing unnecessary noise. For example, if I move a paragraph or section to another part of the doc, but change where the line breaks happen, it'll take a little bit of extra time to make sense of this in the diff. In deciding to do this, my thought was that the rendered markdown isn't affected and IDEs have visual code wrapping features, so I figured the impact on readability was minimal, and that the benefits outweigh the cons. I'm good with going in a different direction though.

my personal opinion: i have been reviewing documentation that has line break changes, and it is exceedingly easy to follow what has been changed and what hasn't. also because its a review of documentation, i'm less worried about polluting the diff because what i care about is what the current state of the documentation is. i would like to follow [established markdown style guides](https://google.github.io/styleguide/docguide/style.html#character-line-limit) that advocate for 80 character limits.

**Comment by evzzk** [comment]
@kaizencc I'm good with that. In that case, I'll close this PR since formatting changes aren't necessary before I start working on updating the content.

**Pull request closed without merging**
