### PR TITLE
fix(core): hangs when used with yarn PnP

### PR DESCRIPTION
**Pull request by keithlayne**
### Commit Message
fix(core): hangs when used with yarn PnP

The `findNpmPackage` function in `runtime-info.ts` has a subtle and
mostly innocuous bug.  Its parent, `collectRuntimeInformation`, iterates
over the modules in `require.cache` and resolves the library version for
each.

It uses the `paths` property of each entry to locate the package
description for that module.  An example:

For `/foo/bar/aws-cdk/packages/aws-cdk/lib/index.js`:

```js
[ '/foo/aws-cdk/packages/aws-cdk/lib/node_modules',
  '/foo/aws-cdk/packages/aws-cdk/node_modules',
  '/foo/aws-cdk/packages/node_modules',
  '/foo/aws-cdk/node_modules',
  '/foo/node_modules',
  '/node_modules' ]
```

`findNpmPackage` maps over these, and if the string ends with
`/node_modules` or `\\node_modules` it strips that off, ending with:

```js
[ '/foo/aws-cdk/packages/aws-cdk/lib',
  '/foo/aws-cdk/packages/aws-cdk',
  '/foo/aws-cdk/packages',
  '/foo/aws-cdk',
  '/foo',
  '' ]
```

...and passes this array as the `paths` option to `require.resolve`.

The problem is that `''` is interpreted as the current working
directory, and instead of walking the file tree to the root (as was
probably intended) it appends whatever node's current working directory
is to the search.

It's hard to imagine this ever really having a negative impact on
package resolution, but unfortunately this triggered a likewise obscure
bug in yarn 2 when configured with PnP.  (See yarnpkg/berry#1298).  This
bug is fixed in yarn 2 master but hasn't been released yet.  The effect
of these two bugs when triggered is for the CDK CLI to hang.

This change seems to meet the intent of the code without having the
above problem.  It seems canonically correct and uses the `fs` lib more
idiomatically.  It's also less code :)

This passes all existing tests.  It's not clear how this would be tested
without exporting `findNpmPackage` and adding tests for it.

**CAVEAT:** I can't test this on windows, but it's worth noting the
following:

```js
// Node 12.16.3
path.win32.resolve('C:')
// => 'C:\\foo\\aws-cdk' (current working directory)
```

```js
// Node 10.13.0
path.win32.resolve('C:')
// => 'C:\\'
```

Both of these results come on OSX.  But it appears that the yarn bug
would not trigger on either version, while node may or may not have the
same wrong behavior for `findNpmVersion` on windows.

### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by keithlayne** [comment]
I don't think I can contrive any kind of failing test for this.  Should I relabel it as `refactor`?

**Comment by keithlayne** [comment]
I found a way to test it.  I'm not sure it's entirely realistic, but it shows the bug (and fails without a fix).

**Comment by keithlayne** [comment]
From the contributing guide:
> Submit a Pull Requests on GitHub and assign the PR for a review to the "awslabs/aws-cdk" team.
Yo @SomayaB, sorry for the ping but can I get a review?  Or let me know how to request a review without pinging you?

**Comment by orta** [comment]
The latter part of that contributing guide can be automated if this repo adds a code-owners file too
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**Pull request merged**
