### PR TITLE
docs: add beta banner

### PR DESCRIPTION
**Pull request by Doug-AWS**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license

Changes to doc build script:

- Added Python 2.7 path
- Copies HTML files from docs/_templates to Sphinx directory, overwriting layout.html to include header.html. The change to layout.html is trivial. Injects line 169, so if someone can think of a cleaner solution, please do so as the Sphinx template does not include a header so one cannot simply replace that file:

{% include "header.html" %}

### CODE REVIEW

**Comment by Doug-AWS** [comment]
Here's an example (I still need to change "beta" to "developer preview"):

image

**Comment by Doug-AWS** [comment]
Ok, changed "beta" to "developer preview".

**Comment by eladb** [comment]
I am not sure I like how this looks to be honest. Any chance we can use some preformatted "warning" thing instead of just yellow highlighting?

**Comment by Doug-AWS** [comment]
I've made the suggested changes. Can we please merge this?

**Comment by eladb** [comment]
There are 562 file changes in this commit. I think something went wrong...

**Comment by Doug-AWS** [comment]
Forgot to rebase. I'll close this and try a different branch/PR.

**Comment by eladb** [comment]
Please include a screenshot :-)

**Comment by Doug-AWS** [comment]
See PR #1053

**Pull request closed without merging**
