### PR TITLE
fix(core): max resources quota enforced on nested stacks

### LINKED ISSUE #28186: (aws-cdk): (Unable to create nested stack with > 500 resources)
### Describe the bug

I am using a nested stack inside of a regular stack to get past the resource limit of 500 in a stack. After moving 413 resources to a nested stack I receive the following error on deployment:

```[Info at /dev/Frontend/LambdasApi-dev] Number of resources: 413 is approaching allowed maximum of 500```

Please note that `/dev/Frontend/LambdasApi-dev` refers to my nested stack. 

As per the resource limits stated in this table here:

[https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)

Nested stacks should have a max resource limit of 2500, not 500 hence the bug.

The part of the repository that gives this warning is here, the nested stack class simply extends the stack with some modifications, resource limit is not one of those modifications:

https://github.com/aws/aws-cdk/blob/8e42fe6f765b3556f0e4038f8ae252d48a46ed98/packages/aws-cdk-lib/core/lib/stack.ts#L1086

### Expected Behavior

I would expect to be able to create 2500 resources in a nested stack as per the documentation here:

[https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)

### Current Behavior

I receive a warning message if I am close to going over 500 resources in a nested stack and presumably an error if I do go over 500

### Reproduction Steps

1. Create a stack 
2. Create a nested stack within the first stack
3. Populate the nested stack with >400 resources to receive the warning and >500 to presumably get an error

### Possible Solution

Implement custom resource limits for Nested Stacks

### Additional Information/Context

_No response_

### CDK CLI Version

2.111.0

### Framework Version

_No response_

### Node.js Version

18.16.0

### OS

Ubuntu

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by lpizzinidev**
The max resource quota of 500 should not be applied on nested stacks.
[AWS CloudFormation quotas](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html).

Closes #28186.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by lpizzinidev** [comment]
Exemption Request.
Unit tests should provide enough coverage here.

**Comment by scanlonp** [comment]
@lpizzinidev, sounds good. This could just be something we let cloudformation enforce. I doubt too many users will be running into the 2500 resource limit.

**Comment by lpizzinidev** [comment]
@scanlonp 
Yeah, probably the best approach here is to not validate the number of resources if the stack is nested.

**Comment by scanlonp** [comment]
I still think this is a no-op. Commented here https://github.com/aws/aws-cdk/issues/28186#issuecomment-1839591309.

**Comment by lpizzinidev** [comment]
Closing due to https://github.com/aws/aws-cdk/issues/28186#issuecomment-1839591309

**Pull request closed without merging**
