### PR TITLE
fix: this.node.addError does not cause `cdk diff` to fail #4700

### PR DESCRIPTION
**Pull request by nideveloper**
Adding in appStacks.processMetadata(stacks); command into the diff method so that metadata is processed correctly and the diff should fail

This is for issue https://github.com/aws/aws-cdk/issues/4700

I am unsure how to go about effectively testing this change so I wanted to open the pull request early and start some conversation.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by shivlaks** [comment]
@nideveloper thanks for taking a run at this issue! 

When you say you're not sure testing the change, did you mean locally or writing unit/integ tests?

The PR checklist should point you towards running/adding [integ tests](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#running-cli-integration-tests), but I'm wondering if the CONTRIBUTING guide itself needs to be beefed up?

**Comment by nideveloper** [comment]
@shivlaks sorry I should have been way more specific. So when I looked into the existing tests for the diff functionality it doesn't actually test the inner workings of diff. A flag is passed in to say pass or fail, this overrides everything that diff actually does internally. So I don't really have an example of a test that uses diff to fail for two mock stacks without setting this flag which for my purposes of this change wouldn't be a very good test as the change is to fail diff if error flags are in the stack.

test
https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/test/test.diff.ts#L78

diff use of fail flag
https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/cdk-toolkit.ts#L75

I just wanted to make sure before I go down a certain path with testing this that I was going the right way or that I am not missing something obvious

**Comment by nideveloper** [comment]
I should add I got all the existing tests running and passing locally etc, I didn't have any issues with that so I think the documentation is probably ok.

**Comment by nideveloper** [comment]
I worked it out, going through the commit process now.

**Comment by shivlaks** [comment]
> I worked it out, going through the commit process now.

that's great, looking good. i'm wondering if we can also add an integ test for verifying this scenario

**Comment by nideveloper** [comment]
> > I worked it out, going through the commit process now.
> 
> that's great, looking good. i'm wondering if we can also add an integ test for verifying this scenario

Correct me if i'm wrong but since this ticket is about testing a scenario where you do a diff on a stack with an error I would need to modify this file to create a test stack that has an error? 

https://github.com/nideveloper/aws-cdk/blob/master/packages/aws-cdk/test/integ/cli/app/app.js#L147

That way I could create a file like this one to test it fails

https://github.com/nideveloper/aws-cdk/blob/master/packages/aws-cdk/test/integ/cli/test-cdk-diff.sh

**Comment by nideveloper** [comment]
@shivlaks I was writing some integration tests there but the existing tests all seem to be based around stacks that can deploy and be interrogated via the cli. A stack with an error on it cannot be deployed. I am pretty sure I can keep modifying until it works but it seems to be against the spirit of the int tests

**Comment by shivlaks** [comment]
> @shivlaks I was writing some integration tests there but the existing tests all seem to be based around stacks that can deploy and be interrogated via the cli. A stack with an error on it cannot be deployed. I am pretty sure I can keep modifying until it works but it seems to be against the spirit of the int tests

fair point, I don't think it's necessary. have you run the cli integ tests and verified that they all pass?

**Comment by nideveloper** [comment]
Awesome, let me revert my local changes and run them again today then confirm back here!

**Comment by nideveloper** [comment]
@shivlaks just ran the integration tests and they pass. Will update the branch to be up to date with master and then it should be good to go

**Comment by nideveloper** [comment]
> @shivlaks just ran the integration tests and they pass. Will update the branch to be up to date with master and then it should be good to go

Code updated to latest from master, automated builds ran and passed. Should be good to go

**Pull request merged**
