### PR TITLE
fix(ses): incorrect DKIM records for EmailIdentity

### LINKED ISSUE #21306: aws-ses: DKIM records are created with incorrect name from EmailIdentity
### Describe the bug

When creating a new `ses.EmailIdentity` construct, the names of the DKIM records that get created in Route53 are incorrect.

### Expected Behavior

If the DKIM record name is` x.y.example.com`, and the hosted zone is `y.example.com`, the name of the record that gets set in Route53 should be `x.y.example.com`

### Current Behavior

If the DKIM record name is` x.y.example.com`, and the hosted zone is `y.example.com`, the name of the record that gets set in Route53 should is `x.y.example.com.y.example.com`

### Reproduction Steps

Here is a simple reproduction case:
```typescript
const myHostedZone = ...; // However you're grabbing or creating your hosted zone

const sesIdentity = new ses.EmailIdentity(this, "ses-identity", {
  identity: ses.Identity.publicHostedZone(hostedZone),
  mailFromDomain: `mail.${hostedZoneDomain}`,
});
```

### Possible Solution

The reason for the incorrect record names is because of the function here in the source code:.

https://github.com/aws/aws-cdk/blob/ac323408383b6eb40c3d08a7537a117227370d99/packages/%40aws-cdk/aws-ses/lib/email-identity.ts#L220-L237

It calls `route53.CnameRecord`, which accepts a record name _excluding_ the hosted zone suffix - eg. for `x.y.example.com` where the hosted zone is `y.example.com`, the record name should just be `x`.

However, it's passing in `dkimDnsTokenName1` etc, which [according to the Cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-emailidentity.html#aws-resource-ses-emailidentity-return-values-fn--getatt), is the entire host for the record, including the hosted zone.

This means that `route53.CnameRecord` tried to append the hosted zone name onto the end of the record name which already includes the hosted zone name, leading to the duplication.

This can be seen in a `cdk synth`:
```yaml
...
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        Fn::Join:
          - ""
          - - Fn::GetAtt:
                - <Our SES Entity ID>
                - DkimDNSTokenName1
            - .y.example.com.
      Type: CNAME
...
```

There are 2 fixes that I can think of:

1. Call `CfnRecordSet` rather than `CnameRecord` - eg:
```typescript
new route53.CfnRecordSet(emailIdentity, "DkimDnsToken1", {
  hostedZoneName: hostedZone.zoneName + ".",
  name: Lazy.string({ produce: () => emailIdentity.dkimDnsTokenName1 }),
  type: "CNAME",
  resourceRecords: [Lazy.string({ produce: () => emailIdentity.dkimDnsTokenValue1 })],
  ttl: "1800",
})
```
2. Use a hacky workaround to lop off the suffix before passing to `CnameRecord` - by combining `cdk.Fn.select` and `cdk.Fn.split` to remove the last part of the string. Here's how that would look:
```typescript
// This function removes a string from the end of another string using Cfn functions.
// For example, calling it on "abcd" with suffix "cd" would return "ab".
// We accomplish this by splitting by the suffix (which gives ["ab"]), then selecting the 0th value.
const hackyCfnRemoveSuffix = (sourceString: string, suffixToRemove: string) =>
  cdk.Fn.select(0, cdk.Fn.split(suffixToRemove, sourceString));

// Then use it in the bind function
new route53.CnameRecord(emailIdentity, 'DkimDnsToken1', {
  zone: hostedZone,
  recordName: hackyCfnRemoveSuffix(Lazy.string({ produce: () => emailIdentity.dkimDnsTokenName1 }), "." + hostedZone.zoneName),
  domainName: Lazy.string({ produce: () => emailIdentity.dkimDnsTokenValue1 }),
});
```

### Additional Information/Context

_No response_

### CDK CLI Version

2.29.0 (build 47d7ec4)

### Framework Version

2.33.0

### Node.js Version

v16.15.1

### OS

MacOS

### Language

Typescript

### Language Version

_No response_

### Other information

# Workaround
For anyone else experiencing this issue - we've opted to go with the `CfnRecordSet` option as it's a bit simpler to see what's going on. Simply map through each of the `dkimRecords` after creating the `EmailIdentity` and create the correct records - note that this won't remove the incorrect ones unfortunately.

Code below:
```typescript
// Create SES email identity based on Route53 hosted zone
const sesIdentity = new ses.EmailIdentity(this, "ses-identity", {
  identity: ses.Identity.publicHostedZone(hostedZone),
  mailFromDomain: `mail.${hostedZone.zoneName}`,
});

// Temporary workaround: There is a bug with the EmailIdentity construct where if the DKIM record is x.y.example.com,
// and the hosted zone is y.example.com, the record that gets set is x.y.example.com.y.example.com. For now, we are
// manually creating the correct records.
const dkimCnameRecords = sesIdentity.dkimRecords.map(
  (dkimRecord, index) =>
    new route53.CfnRecordSet(this, `dkim-record-${index}`, {
      hostedZoneName: hostedZone.zoneName + ".",
      name: dkimRecord.name,
      type: "CNAME",
      resourceRecords: [dkimRecord.value],
      ttl: "1800",
    })
);
```

### PR DESCRIPTION
**Pull request by jogold**
Because `route53.determineFullyQualifiedDomainName()` doesn't correctly
handles tokens we get the zone name twice here.

Another way to solve this would be to fix
`determineFullyQualifiedDomainName()`. There is already a discussion
there https://github.com/aws/aws-cdk/pull/20435 for the hosted zone name
part, not the record name.

Closes #21306

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@corymhall FYI

Do you think it is better to solve this in `route53`?

**Comment by TheRealAmazonKendra** [comment]
I think that we should fix this in `route53` instead of here, since that's the actual source of this bug. I closed the other PR because I didn't think the approach was right but I want to keep the conversation going in the issue of what the right path forward really is.

**Comment by corymhall** [comment]
> Do you think it is better to solve this in `route53`?

I commented on the issue. I agree with @TheRealAmazonKendra, we should address this in route53.

**Comment by TheRealAmazonKendra** [comment]
I'm going to go ahead and close this since we won't be moving forward with this particular approach.

**Comment by jogold** [comment]
@TheRealAmazonKendra if this is fixed under a feature flag in route53 how can it be fixed for everyone in ses?

**Comment by corymhall** [comment]
That's a good point...I guess we need this PR as well, otherwise it will remain broken for anyone that doesn't opt-in to the feature flag.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio requeue

**Pull request merged**
