### PR TITLE
fix(s3): bucket deletion fails if object creation races against cleanup

### LINKED ISSUE #26874: @aws-cdk: S3 buckets block stack deletion
### Describe the bug

On stack deletion, buckets with `RemovalPolicy.DESTROY` often fail to delete due to continued writes to it, such as from zombie CloudFront distribution logging (the CloudFront distribution no longer exists in the console, but log data continues to populate the bucket rapidly).

This appears to be a resource accounting bug within AWS and not CDK-specific, but through the use of a DENY policy, CDK's existing auto-delete should be able to mitigate.

### Expected Behavior

On stack deletion, the S3 buckets with `RemovalPolicy.DESTROY` should always be deleted.

### Current Behavior

On stack deletion, the S3 buckets with `RemovalPolicy.DESTROY` often cannot be deleted after emptying due to a race condition with external writers, thereby blocking overall stack deletion.

### Reproduction Steps

Errant behavior is non-deterministic.

1. Using the AWS CloudFrontToS3 construct (@aws-solutions-constructs/aws-cloudfront-s3), deploy a stack.
2. Delete the stack.

### Possible Solution

The auto-delete lambda should add a policy to the target buckets to deny further PutObject calls prior to emptying the bucket.

### Additional Information/Context

Defunct CloudFront distributions intermittently continue writing (often for more than 24 hours) to its log buckets even though the CloudFront distributions no longer appear in the AWS console, in the CLI, or in the stack resources. The zombie distributions have been observed to continue writing large numbers of small objects for days.

### CDK CLI Version

2.93.0 (build 724bd01)

### Framework Version

_No response_

### Node.js Version

v18.17.1

### OS

Amazon Linux 3.0 (ARM64)

### Language

Typescript

### Language Version

5.1.6

### Other information

_No response_

### PR DESCRIPTION
**Pull request by miles-po**
Adds a DENY policy for S3:PutObject on buckets to be auto-deleted to prevent a race condition on emptying with external bucket writers.

As a new contributor, the requirements for integration testing were unclear to me. I have tested the policy on my own buckets and included unit tests, but am willing to work toward code compliance with assistance.

Closes #26874.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by miles-po** [comment]
Clarification Request: As a new contributor, the requirements for integration testing were unclear to me. I have tested the policy on my own buckets and included unit tests, but am willing to work toward code compliance with assistance.

**Comment by rix0rrr** [comment]
[This document](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md) should be mostly accurate explaining what they are and how they should be run.

You don't need to add a new one, but you probably will need to update some existing snapshots. You'll need AWS account credentials to run the actual tests in.

The tests are in `packages/@aws-cdk-testing/framework-integ` these days.

**Comment by mrgrain** [comment]
@miles-po Thanks for this! Are you still interested in wrapping this up? If you can get the unit tests passing and update the integration test snapshots with `--dry-run`, that'd be great. Once that's done I can verify  for you that the integ tests are working and get it shipped.

**Comment by miles-po** [comment]
Family's been ill, so I've been playing catch-up. I started working on it again late yesterday. Was hoping to finish up today.

**Comment by miles-po** [comment]
@mrgrain I added some fixes including unit test repair. I keep getting an integration test failure in the `cdk-s3-bucket-auto-delete-objects` stack. I obviously can't rule out user error, but looking back at the code, I can't find why my additions would cause a missing bucket error. Would appreciate any help I can get as I fear I've taken it as far as I know how in this codebase.

Screenshot 2023-09-19 at 12 36 00

**Comment by miles-po** [comment]
And after fixing one set of unit tests, I broke another. Lemme fix that before I ask for more help. (Oops!)

**Comment by miles-po** [comment]
@mrgrain Made my fixes. Appears to me the only failures are now snapshot failures. Been trying to get the integration tests to work in a sandbox account, following the contributors instructions as close as I know how, but nothing I try seems to work. If they work for you, I owe you a beverage of your choice for getting the snapshots to work. If not, I'm here to help with the code debugging process and answer any questions I can.

**Comment by mrgrain** [comment]
> @mrgrain Made my fixes. Appears to me the only failures are now snapshot failures. Been trying to get the integration tests to work in a sandbox account, following the contributors instructions as close as I know how, but nothing I try seems to work. If they work for you, I owe you a beverage of your choice for getting the snapshots to work. If not, I'm here to help with the code debugging process and answer any questions I can.

No worries. I'll try to get to it tomorrow. Did you encounter any specific errors?



> @mrgrain I didn't run `--dry-run` because the [contributing instructions](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) specifically said:

Haha, fair. I guess we should change this to "Please do not run the cdk-integ tool with --dry-run or manually update the snapshot **unless specifically asked to**."

**Comment by miles-po** [comment]
> No worries. I'll try to get to it tomorrow. Did you encounter any specific errors?

The same `The specified bucket does not exist` error I mentioned earlier in the conversation.

**Review by rix0rrr — DISMISSED** [review]

**Comment by miles-po** [comment]
@mrgrain @rix0rrr Thank you both so much for pushing this through!

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
