### PR TITLE
fix(aws-ecs): export instance drain hook

### LINKED ISSUE #1391: ECS: instance draining hook does not exported
exported in `lib/` but not  in `index.ts`

### PR DESCRIPTION
**Pull request by cohalz**
fix #1391 
----

### Pull Request Checklist

Please check all boxes, including N/A items:

#### Testing

- [ ] Unit test and/or integration test added
- [ ] __Toolkit change?:__ [integration tests](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/integ-tests/test.sh) manually executed (paste output to the PR description)
- [ ] __Init template change?:__ coordinated update of integration tests (currently maintained in a private repo).

#### Documentation

- [x] __README__: README and/or documentation topic updated
- [x] __jsdocs__: All public APIs documented

### Title and description

- [x] __Change type__: Title is prefixed with change type:
  * `fix(module): <title>` bug fix (_patch_)
  * `feat(module): <title>` feature/capability (_minor_)
  * `chore(module): <title> ` won't appear in changelog
  * `build(module): <title>` won't appear in changelog
- [x] __Title format__: Title uses lower case and doesn't end with a period
- [x] __Breaking change?__: Last paragraph of description is: `BREAKING CHANGE: <describe exactly what changed and how to achieve similar behavior + link to documentation/gist/issue if more details are required>`
- [x] __References__: Indicate issues fixed via: `Fixes #xxx` or `Closes #xxx`

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by eladb** [comment]
@rix0rrr @SoManyHs was this intentional?

**Comment by rix0rrr** [comment]
Yes. It's not clear to me why it should be exported. @cohalz, what problems is this causing for you?

**Comment by cohalz** [comment]
Even if I create your own without using the ECS construct I want to use instance drain hook.

**Comment by rix0rrr** [comment]
That brings up my next question: what use cases of yours is the rest of the ECS library not satsifying?

**Comment by rix0rrr** [comment]
Oh I see, spot instances

**Comment by cohalz** [comment]
I don't confirm whether hooks can be used in spot instances, I think that there is no loss by being exported when using ondemand.

**Comment by rix0rrr** [comment]
I'm sorry, I'm going to close this PR. For now the drain hook is an implementation detail that I'd rather not expose, and I don't think it will work for your use case.

If I'm wrong, or a definite use case for it pops up, we can reconsider this.

**Pull request closed without merging**
