### PR TITLE
chore(ecs-service-extensions): Adding defined return types to the ServiceExtension abstract class

### PR DESCRIPTION
**Pull request by nathanpeck**
The ServiceExtension abstract class was missing a TypeScript definition for the return type of the hook. This worked through TypeScript type inference, but did not result in a helpful tooltip guide when attempting to implement your own ServiceExtension. This change should result in proper warnings and tooltips in IDE's when implementing a ServiceExtension

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by piradeepk — DISMISSED** [review]
Ship it! 💯

**Comment by piradeepk** [comment]
I'd probably call this a fix or chore since it's not actually adding new functionality.

**Comment by nathanpeck** [comment]
Sorry @piradeepk can I get another approval... it wasn't letting me merge this because it only had one commit

**Comment by piradeepk** [comment]
I believe you're also gonna have to change your commit to say chore as well

**Review by piradeepk — DISMISSED** [review]
Ship it! 💯

**Review by piradeepk — APPROVED** [review]
Ship it! 💯

**Pull request merged**
