### PR TITLE
feat(msk): add Kafka versions 3.1.1, 3.2.0, and  and 3.3.1

### LINKED ISSUE #23899: (aws-msk): Support newer versions of Kafka
### Describe the feature

CDK supports at the moment Kafka versions until v2.8.1 (see packages/@aws-cdk/aws-msk/lib/cluster-version.ts).
MSK itself added support for 

- Apache Kafka version 3.3.1
- Apache Kafka version 3.2.0
- Apache Kafka version 3.1.1
- Amazon MSK tiered storage version 2.8.2.tiered

(see https://docs.aws.amazon.com/msk/latest/developerguide/supported-kafka-versions.html)

These new versions should be enabled also in the CDK.

### Use Case

Within the next few month I need to migrate self-managed Kafka clusters to MSK. Here I would like to go with CDK and Kafka v3.x

### Proposed Solution

The change could be implemented by enhancing the KafkaVersions class.
There is one additional change as  tiered storage was introduced with 2.8.2- not sure how to treat this one.

### Other Information

- [https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-msk-offers-low-cost-storage-tier-scales-virtually-unlimited-storage/](https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-msk-offers-low-cost-storage-tier-scales-virtually-unlimited-storage/)
- [MSK Create Cluster CLI command](https://docs.aws.amazon.com//cli/latest/reference/kafka/create-cluster.html)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.62.2

### Environment details (OS name and version, etc.)

Ubuntu 22.04

### PR DESCRIPTION
**Pull request by stefanfreitag**
Add support for Apache Kafka versions 3.1.1, 3.2.0 and 3.3.1 in Amazon MSK.

Announcements:
- [3.1.1 and 3.2.0](https://aws.amazon.com/about-aws/whats-new/2022/06/amazon-msk-adds-support-apache-kafka-version-3-1-1-3-2-0/) (Posted On: Jun 22, 2022)
- [3.3.1](https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-msk-support-apache-kafka-version-3-3-1) (Posted On: Oct 26, 2022)

Closes #23899 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by stefanfreitag** [comment]
The code change adds new versions to the already existing/ supported Kafka versions.

- The supported versions were not mentioned in the README so far - I decided to not start with this.
- The unit/ integration tests all use the default version 2.6.1 of Kafka. I thought about updating those tests, but skipped. Happy to apply a change (new PR or as part of this). 
Nevertheless, if we go with the default/ recommended version it would be in my opinion 2.8.1 - the newly introduced versions would also not be covered by this.

Please let me know your thoughts.

**Comment by stefanfreitag** [comment]
Hi @TheRealAmazonKendra !
I tried to come up with a unit test for the Kafka versions. To my understanding we would need to check/ensure that `msk.KafkaVersion.VX_Y_Z` contains always the correct version as string, e.g. msk.KafkaVersion.V3_2_0 -> '3.2.0'.
Not sure if a parameterized test is what you had in mind, but its a starting point for discussion.
(ok, noticed that there is a different flavor for the syntax around test.each - will have a look) 

On the integration test I am unsure about the expectation. I noticed that three clusters with Kafka version 2.8.1 are generated, all with a different way for e.g. authentication. Would i need to setup an additional cluster with the newer Kafka versions? Or three because of the different authentication mechanisms?

**Comment by TheRealAmazonKendra** [comment]
> Hi @TheRealAmazonKendra ! I tried to come up with a unit test for the Kafka versions. To my understanding we would need to check/ensure that `msk.KafkaVersion.VX_Y_Z` contains always the correct version as string, e.g. msk.KafkaVersion.V3_2_0 -> '3.2.0'. Not sure if a parameterized test is what you had in mind, but its a starting point for discussion. (ok, noticed that there is a different flavor for the syntax around test.each - will have a look)
> 
> On the integration test I am unsure about the expectation. I noticed that three clusters with Kafka version 2.8.1 are generated, all with a different way for e.g. authentication. Would i need to setup an additional cluster with the newer Kafka versions? Or three because of the different authentication mechanisms?

Apologies for the delay, I missed the notification last week. Just one for each. We just want to see that it deploys.

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra I was able to run the integration tests in an AWS account and notices that it creates a Private CA - which is quite costly. Is there any information how contributors typically deal with this kind of costs?

Yes, and we need to make the documentation better because this question comes up frequently so I apologize for it not being more clear. Just write the test cases and commit them. Then tag me with a note to run the tests and update the snapshots for you.

**Review by TheRealAmazonKendra — DISMISSED** [review]
Putting back into changes requested to reflect status.

**Comment by stefanfreitag** [comment]
Hello @TheRealAmazonKendra! As discussed I updated the integration test code and added three MSK clusters, one for each version added. Please let me know if I need to change/ update.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
Well, this exercise was worthwhile because I found that our test was actually broken. I've pushed the fix and the updated snapshots. As long as this passes, I see it as good to go.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
