### PR TITLE
feat(eks): bump aws-node-termination-handler to 0.9.5

### PR DESCRIPTION
**Pull request by pahud**
Closes aws/aws-cdk#10277

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
I will validate it in my environment. Please do not merge for now.

**Comment by pahud** [comment]
Now I can confirmed the new deployment is successfully running in my environment.

圖片

**Comment by pahud** [comment]
Ready for review now.  @iliapolo  :-)

**Review by iliapolo — CHANGES_REQUESTED** [review]
@pahud Lets change this to a feature and add a note in the readme specifying which version is used.

This is a valuable thing to see in the changelog.

**Comment by pahud** [comment]
> @pahud Lets change this to a feature and add a note in the readme specifying which version is used.
> 
> This is a valuable thing to see in the changelog.

fixed. Please check it out again.

**Comment by iliapolo** [comment]
@pahud 

> fixed. Please check it out again.

Mmm - I don't see a change in the README...

**Comment by pahud** [comment]
> @pahud
> 
> > fixed. Please check it out again.
> 
> Mmm - I don't see a change in the README...

Aha. Sorry. Just fixed.

**Review by iliapolo — APPROVED** [review]

**Pull request merged**
