### PR TITLE
chore(ec2): add missing interface VPC endpoint services

### PR DESCRIPTION
**Pull request by hoegertn**
----
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
We'll need some sort of tests with this change. Additionally, please see the Pull Request section of our Contributing Guide regarding our guidelines to PR body text.

**Comment by hoegertn** [comment]
Given that this PR only adds some static variables to an existing enum without tests, I would love some feedback on what the tests should include.

I will update the PR description.

**Comment by TheRealAmazonKendra** [comment]
> Given that this PR only adds some static variables to an existing enum without tests, I would love some feedback on what the tests should include.
> 
> I will update the PR description.

We have a lot of areas where our test coverage isn't what it should be. We use any opportunity we can get to improve test coverage. 

Basically, we want to ensure that use of these values creates the template output we'd expect. So, please write tests that use these in a construct and ensure that the template matches your expected values. If you need examples of where we've tested against templates, please let me know.

**Comment by TheRealAmazonKendra** [comment]
Closing since #21401 has been merged.

**Pull request closed without merging**
