### PR TITLE
chore: fix patch build

### PR DESCRIPTION
**Pull request by rix0rrr**
The patch file that's in here is unnecessary, and in fact harmful: because the rename it applies is not necessary, it copies `undefined` values into perfectly fine types.

Remove patch and add guard rails agains this.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by mrgrain — APPROVED** [review]
Ah yes, the patch needs to go in after the spec has been updated.

How did the pass the PR build though 🤔

**Comment by rix0rrr** [comment]
I'm wondering that as well

**Comment by rix0rrr** [comment]
Haaa and now the check fails because the spec has an error at the old commit

**Comment by rix0rrr** [comment]
Oh it's because `git rev-parse --abbrev-ref HEAD` returns `HEAD` if we aren't on a branch, and then the next `git checkout HEAD` which should restore the commit ptr doesn't do anything

**Pull request merged**
