### PR TITLE
fix(eks): fix helm deploy for public-ecr repositories

### LINKED ISSUE #23052: aws-eks: addHelmChart() fails with public.ecr.aws
### Describe the bug

When updating a stack containing an EKS cluster and adding an helm chart as following:
```typescript
const chart = this.cluster.addHelmChart('karpenter', {
wait: true,
timeout: Duration.minutes(15),
chart: 'karpenter',
release: 'karpenter',
repository: 'oci://public.ecr.aws/karpenter/karpenter',
namespace: 'karpenter',
version: 'v0.19.2', 
createNamespace: false,
values: {
  serviceAccount: {
    create: false,
    name: serviceAccount.serviceAccountName,
    annotations: { 'eks.amazonaws.com/role-arn': serviceAccount.role.roleArn },
  },
  clusterName: this.cluster.clusterName,
  clusterEndpoint: this.cluster.clusterEndpoint,
  aws: { defaultInstanceProfile: instanceProfile.ref },
},
});
chart.node.addDependency(namespace);
```
The process timeout after the specified (maximum allowed) 15 minutes.

Looking at the lambda logs on CloudWatch, we get:
`[INFO]	2022-11-23T02:24:24.338Z	ba8e8ffd-8069-4590-a492-9a58168180d0	b'\nCould not connect to the endpoint URL: "https://api.ecr-public.ap-southeast-2.amazonaws.com/"\nLogin Succeeded\nPulled: public.ecr.aws/karpenter/karpenter:v0.19.2\nDigest: sha256:4ee72250b55d7c45d72f4c8382ed9b2f0f63ec67def84cd63300667e58ff2167\n'
`
`2022-11-23T02:39:13.812Z ba8e8ffd-8069-4590-a492-9a58168180d0 Task timed out after 900.10 seconds`

### Expected Behavior

The helm chart should be pulled and installed.

### Current Behavior

The process timeout.

### Reproduction Steps

This is a simplified version of our code

```typescript
export class EksCluster extends Stack {
  cluster: Cluster;
  version = eks.KubernetesVersion.of('1.24');
  vpc: ec2.IVpc;

  constructor(scope: Construct, id: string, props: EksClusterProps) {
    super(scope, id);
    this.vpc = ec2.Vpc.fromLookup(this, 'Vpc', { tags: { BaseVPC: 'true' } });

    this.cluster = new eks.Cluster(this, 'EKSCluster', {
      clusterName: 'testCluster',
      version: this.version,
      vpc: this.vpc,
      defaultCapacity: 0,
      kubectlLayer: new KubectlV24Layer(this, 'KubeCtlLayer'),
    });

    this.cluster.addHelmChart('karpenter', {
      timeout: Duration.minutes(15),
      wait: true,
      chart: 'karpenter',
      release: 'karpenter',
      repository: 'oci://public.ecr.aws/karpenter/karpenter',
      namespace: 'karpenter',
      version: 'v0.19.2',
      createNamespace: false,
    });
  }
}
```

### Possible Solution

_No response_

### Additional Information/Context

`https://api.ecr-public.ap-southeast-2.amazonaws.com/` seems wrong as [it looks like only `us-east-1` and `us-west-2` are available regions](https://docs.aws.amazon.com/general/latest/gr/ecr-public.html). This URL is generated by `cdk` using the default region of our stack. I don't know if there is a way to specify a region for this specific helm chart repo?

### CDK CLI Version

2.50.0 (build 4c11af6)

### Framework Version

2.50.0

### Node.js Version

v16.17.0

### OS

Ubuntu 22.04.1 LTS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by pahud**
This PR continues the development of https://github.com/aws/aws-cdk/pull/23176 and fixes https://github.com/aws/aws-cdk/issues/23052

Using the default region causes aws ecr-public get-login-password --region {region} to fail, which then breaks the further steps of the helm deploy process. See the issue https://github.com/aws/aws-cdk/issues/23052 for more details.

According to the [ECR docs](https://docs.aws.amazon.com/general/latest/gr/ecr-public.html) the region should be either us-east-1 or us-west-2 for public-ecr and when authenticating to a public registry, always authenticate to the `us-east-1` Region when using the AWS CLI. See [doc](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth).

Note that the command also requires additional permissions to succeed, for which I added the Managed Policy AmazonElasticContainerRegistryPublicReadOnly  to the handler lambda role.

Closes #23052

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
creating as a PR draft as the integ tests will take a huge amount of time. Will update the snapshots when they complete.

**Comment by TheRealAmazonKendra** [comment]
This one is already in the works https://github.com/aws/aws-cdk/pull/24104.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by pahud** [comment]
close in favor of https://github.com/aws/aws-cdk/pull/24104

**Pull request closed without merging**
