### PR TITLE
chore(bedrock): add Amazon Nova Canvas, Lite, Micro, Pro, Reel models

### PR DESCRIPTION
**Pull request by mazyu36**
Add Amazon Nova models.

https://aws.amazon.com/blogs/aws/introducing-amazon-nova-frontier-intelligence-and-industry-leading-price-performance/

* amazon.nova-canvas-v1:0
* amazon.nova-lite-v1:0
* amazon.nova-lite-v1:0:300k
* amazon.nova-micro-v1:0
* amazon.nova-micro-v1:0:128k
* amazon.nova-pro-v1:0
* amazon.nova-pro-v1:0:300k
* amazon.nova-reel-v1:0

```sh
% aws bedrock get-foundation-model --model-identifier amazon.nova-canvas-v1:0 --region us-east-1

{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-canvas-v1:0",
        "modelId": "amazon.nova-canvas-v1:0",

// omit

% aws bedrock get-foundation-model --model-identifier amazon.nova-lite-v1:0 --region us-east-1

{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-lite-v1:0",
        "modelId": "amazon.nova-lite-v1:0",

// omit

% % aws bedrock get-foundation-model --model-identifier amazon.nova-lite-v1:0:300k --region us-east-1
{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-lite-v1:0:300k",
        "modelId": "amazon.nova-lite-v1:0:300k",

// omit

% aws bedrock get-foundation-model --model-identifier amazon.nova-micro-v1:0 --region us-east-1

{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-micro-v1:0",
        "modelId": "amazon.nova-micro-v1:0",

// omit

% aws bedrock get-foundation-model --model-identifier amazon.nova-micro-v1:0:128k --region us-east-1
{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-micro-v1:0:128k",
        "modelId": "amazon.nova-micro-v1:0:128k",

// omit

% aws bedrock get-foundation-model --model-identifier amazon.nova-pro-v1:0 --region us-east-1

{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-pro-v1:0",
        "modelId": "amazon.nova-pro-v1:0",

// omit

%  aws bedrock get-foundation-model --model-identifier amazon.nova-pro-v1:0:300k --region us-east-1
{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-pro-v1:0:300k",
        "modelId": "amazon.nova-pro-v1:0:300k",

// omit

% aws bedrock get-foundation-model --model-identifier amazon.nova-reel-v1:0 --region us-east-1

{
    "modelDetails": {
        "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-reel-v1:0",
        "modelId": "amazon.nova-reel-v1:0",
        "modelName": "Nova Reel",

// omit
```

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mazyu36** [comment]
@mergifyio refresh

**Review by GavinZZ — APPROVED** [review]

**Comment by mazyu36** [comment]
@Mergifyio update

**Comment by mazyu36** [comment]
@Mergifyio refresh

**Comment by mazyu36** [comment]
@Mergifyio update

**Comment by mazyu36** [comment]
@Mergifyio refresh

**Pull request merged**
