### PR TITLE
docs(appsync): add placeholder Query type for improved schema compatibility

### PR DESCRIPTION
**Pull request by azarboon**
### Issue # (if applicable)

Closes #<issue number here>.

### Reason for this change

While the current schema is technically valid with a single root `Mutation` type, most GraphQL clients and tools expect a default `Query` operation for introspection and standard queries. This PR introduces a minimal placeholder `Query` type to improve compatibility and align with common GraphQL conventions.

### Describe any new or updated permissions being added

<!— What new or updated IAM permissions are needed to support the changes being introduced ? -->

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by kaizencc — DISMISSED** [review]
Thanks @azarboon

**Comment by azarboon** [comment]
@mergifyio requeue

**Comment by azarboon** [comment]
@kaizencc Thanks for approving! I noticed the branch was out of sync, so I updated it. When the issue persisted, I synced my fork directly. It seems the issue is resolved now, but the PR still can't be merged. Since this is my first contribution to aws-cdk, I’d really appreciate your help in guiding me through the final steps. Thanks again!

**Comment by azarboon** [comment]
Closing this PR to start fresh with a clean branch. I’ll do my best to properly sync the new branch with the latest upstream changes and ensure it contains only the intended edits. A new PR will follow shortly. Thank you for your time and patience!

**Pull request closed without merging**
