### PR TITLE
feat(cli): new deployment monitoring

### PR DESCRIPTION
**Pull request by rix0rrr**
Implement a new stack monitor, which updates the screen in-place and
shows the resources currently being deployed plus a progress bar,
instead of dumping a giant history of all events to the screen.

The new monitor can is activated automatically if the output is a TTY,
if we're not on Windows, and if we're not doing a verbose run.

Fix in both old and new stack monitors: detect rollback events, and
instead of increasing the event counter (leading to a progress of
`84/45` resources done), roll the counter backwards as resources are
being rolled back.

anim

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
I did not write tests for this as, to be quite frank... I'm not sure how.

It's purely a UI thing, it'll be hard to write tests for.

Not saying it's not worth testing... just don't really know how.

**Comment by rix0rrr** [comment]
Good call

**Comment by RomainMuller** [comment]
Side Q though - have you smoke tested how this behaves when an update fails and rolls back?

**Comment by robertd** [comment]
It's not working really well on iTerm2 with zsh (using robierussel/oh-my-zsh)?

Is there a way to use more verbose output (for CI/CD purposes too)?

```zsh
➜  sipp-api-cdk git:(master) ✗ cdk deploy
SippApiStack: deploying...
SippApiStack: creating CloudFormation changeset...








 ✅  SippApiStack

Outputs:
SippApiStack.ServiceServiceURL250C0FB6 = https://sipp-api-alb.acme.com
SippApiStack.ServiceLoadBalancerDNSEC5B149E = internal-SippA-Servi-1X2ZSXSR3W328-1234567890.us-west-2.elb.amazonaws.com

Stack ARN:
arn:aws:cloudformation:us-west-2:1234567890:stack/SippApiStack/3841b3e0-b271-11ea-aae2-065639e88e5c
```

**Comment by slotnick** [comment]
Encountering exactly the same here. Is there an option to disable this mode and revert to the previous display? It’s also useful to understand what happened during the build, which is lost with this update. My working model is to kick off a build, then check back after awhile to see what happened. This change makes that very difficult.

**Comment by nija-at** [comment]
@slotnick & @robertd - I've opened a separate issue here to track this - https://github.com/aws/aws-cdk/issues/8696.

**Comment by rohinigaonkar** [comment]
Love this. Would like to request adding monitoring for **destroy**ing a stack too.

**Pull request merged**
