### PR TITLE
fix(aws-ecs)/ec2 container service role does not use managed policy

### LINKED ISSUE #2827: EC2 Container Service Role
**Describe the bug**

I would expect that when using `@aws-cdk/aws-ecs.Cluster.addCapacity`, the instance role created would simply use the `AmazonEC2ContainerServiceforEC2Role` managed policy, as described in the [ECS documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html). However, it seems like it creates a completely new policy with hardcoded permissions.

**To Reproduce**
```typescript
const cluster = new ecs.Cluster(this, 'Cluster', {
    clusterName: 'MyECSCluster',
    vpc: this.vpc
});
cluster.addCapacity('ASG', {
    instanceType: new ec2.InstanceType('c5.large'),
    taskDrainTimeSeconds: 0
});
```

A new `ClusterASGInstanceRoleDefaultPolicy########` policy is created.

**Expected behavior**
I'd expect that the `AmazonEC2ContainerServiceforEC2Role` managed policy is attached to the instance role.

**Version:**
 - Windows / Linux / OSX
 - Typescript
 - 0.34

### PR DESCRIPTION
**Pull request by made2591**
# Bug

When using `@aws-cdk/aws-ecs.Cluster.addCapacity`, the instance role created would simply use the `AmazonEC2ContainerServiceforEC2Role` managed policy, as described in the [ECS documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html). However, it seems like it creates a completely new policy with hardcoded permissions.

To Reproduce

```
const cluster = new ecs.Cluster(this, 'Cluster', {
    clusterName: 'MyECSCluster',
    vpc: this.vpc
});
cluster.addCapacity('ASG', {
    instanceType: new ec2.InstanceType('c5.large'),
    taskDrainTimeSeconds: 0
});
```

A new `ClusterASGInstanceRoleDefaultPolicyXXXXXXXX` policy is created.

# Fix

I think this is due to the way the `addCapacity` operates in [cluster.ts](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/cluster.ts): the method first creates and then calls the `addAutoScalingGroup` method defined in the `Cluster` class. This method defines manually the required permissions in a policy statement attached to the role associated with the autoscaling group. 

As done in eks-[cluster.ts](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster.ts), I fixed it by using `attachManagedPolicy` to the autoscalingGroup role with the [AmazonEC2ContainerServiceforEC2Role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html) that was previously created manually.

close #2827 

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by rix0rrr** [comment]
Hi @made2591.

This behavior is in purpose. Not sure why you're classifying it as a bug. What is it breaking for you?

**Comment by made2591** [comment]
Hi @rix0rrr ... I supposed it was better using managed policy whenever it's possible: am I wrong? Let's say tomorrow the set of permissions will change for some reason: if the list of permissions is *hardcoded* inside cdk, then the wrong set of permissions will be attached. On the other hand, if we refer to a managed policy is up to AWS keep that aligned with the minimum required permission... am I misunderstanding something? 🤔

**Comment by rix0rrr** [comment]
The reason why we choose to inline policies is because managed policies must necessarily always have `resource: *` statements, whereas we can often generate more targeted policies, which are only able to affect the intended resources.

If you are replacing `resource-*` statements, I feel less strongly about this, but if the statements are targeted, I feel the least permissions boundary is preferable.

**Comment by made2591** [comment]
Ok, makes sense: I thought it was fine because it was already like this (`.addAllResources());`) even before introducing the managed one. Feel free to discard the change if you want ;)

**Comment by made2591** [comment]
PS: then it makes sense maybe applying the same logic in eks ([source](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L311)) - I was just wondering, no rush...

**Comment by made2591** [comment]
@rix0rrr any news on this? At least regarding the eks package

**Comment by rix0rrr** [comment]
I'm going to assign this to @eladb who is working on the EKS package right now.

**Comment by SoManyHs** [comment]
Sorry for the delay. @eladb was this addressed in the EKS package, and/or should we close this?

**Comment by rix0rrr** [comment]
Unless proven otherwise, I will close this as intended behavior.

**Pull request closed without merging**
