### PR TITLE
feat(cli): process credentials

### LINKED ISSUE #3008: Profile based credentials don't work with credential_process
* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

When using `--profile` (see also #3007), the CLI doesn't respect `credential_process`. The profile has to have hardcoded credentials.

* **What is the expected behavior (or behavior of feature suggested)?**

`credentials_process` is respected and invoked the same way other AWS CLI tools do.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Parity with AWS CLI.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.35.0
  - Module Version: 0.35.0
  - OS: macOS Mojave 
  - Language: TypeScript

### PR DESCRIPTION
**Pull request by hoegertn**
This adds support for the credentials_process feature.

Using the aws-sso-credential-process utility you can also use AWS SSO with this feature

This should fix #3008 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hoegertn** [comment]
@rix0rrr @pahud this worked in my tests. Did I miss something obvious?

**Comment by pahud** [comment]
> @rix0rrr @pahud this worked in my tests. Did I miss something obvious?

I haven't tested it yet. But LGTM. Thanks for your contribution!!

**Review by rix0rrr — DISMISSED** [review]

**Comment by pahud** [comment]
checking the CI log

```
aws-cdk:   â— with default config files â€º CLI compatible credentials loading â€º mfa_serial in profile will ask user for token
aws-cdk:     expect(received).toEqual(expected) // deep equality
aws-cdk:     Expected: "Error fetching MFA token: test"
aws-cdk:     Received: "Profile mfa-role did not include credential process"
```

Looks like this test was failing.

**Comment by hoegertn** [comment]
Are you able to confirm that it works? So is the code broken or the tests needs change? I think the mock of the Mfa provider is the issue

**Comment by pahud** [comment]
> Are you able to confirm that it works? So is the code broken or the tests needs change? I think the mock of the Mfa provider is the issue

Please see my screenshot. I can confirm it works ,but I have no idea how to fix that test at this time.

圖片

**Comment by hoegertn** [comment]
I had to modify the MFA test as the MFA error is no longer thrown if there is another cred provider in the chain. I changed it to check the mock to be called instead of relying on the error message.

@rix0rrr It would be great if you could re-approve

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
