### PR TITLE
feat(s3): initial implementation of object lock

### PR DESCRIPTION
**Pull request by meve**
This feature introduces S3 Object Lock. Any feedback is welcome and appreciated. It should partially fix https://github.com/aws/aws-cdk/issues/5247.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
My comments are not a reflection on your implementation, but I really dislike the contract CloudFormation provided on this. I'm hoping we can take another pass here and improve the user experience. If you need some input on how to go about that, I'm happy do some brainstorming.

**Comment by meve** [comment]
@TheRealAmazonKendra I couldn't agree more with your comment. My initial goal was to stay close to the CloudFormation implementation, so that's how I ended up with the current result. I am all for improving the user experience, and therefore I would happily accept your offer.

**Comment by TheRealAmazonKendra** [comment]
Apologies for my delayed response on this. I have a bit of a backlog but I will provide a real response tomorrow.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Pull request closed without merging**
