### PR TITLE
chore(stepfunctions-tasks): scope IAM permissions for StartExecution

### PR DESCRIPTION
**Pull request by jogold**
### Commit Message
chore(stepfunctions-tasks): scope IAM permissions for StartExecution (#7976)

Step Functions use CloudWatch managed rules when working with synchronous step functions tasks.
This requires `states:DescribeExecution` and `states:StopExecution` permissions.
Those weren't scoped to the executions of the "child" state machine.

See https://docs.aws.amazon.com/step-functions/latest/dg/concept-create-iam-advanced.html#concept-create-iam-advanced-execution

Added an integ test to validate the IAM permissions.

### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@shivlaks to be integrated in #7946

**Comment by shivlaks** [comment]
> @shivlaks to be integrated in #7946

appreciate the heads up!

**Comment by wong-a** [comment]
> Added an integ test to validate the IAM permissions.

Do the integ tests actually run an execution? It looks like they're just validating the generated CloudFormation template

**Comment by shivlaks** [comment]
> > Added an integ test to validate the IAM permissions.
> 
> Do the integ tests actually run an execution? It looks like they're just validating the generated CloudFormation template

@wong-a they're snapshots as running all integration tests across the suite would be lengthy for the PR build. They primarily help detect regression. For example, if a new property is added or modified, there will be a mismatch with the snapshot. More on the methodology [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#step-3-work-your-magic)

**Pull request merged**
