### PR TITLE
feat(sns): add TracingConfig prop

### LINKED ISSUE #29714: sns: Support for TracingConfig
### Describe the feature

Enable setting of TracingConfig in the L2 construct for SNS topics.
https://docs.aws.amazon.com/sns/latest/dg/sns-active-tracing.html### 

### Use Case

Currently, to set the TracingConfig, it is necessary to configure it via L1.
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sns.CfnTopic.html#tracingconfig

### Proposed Solution

Allows passing the "TracingConfig" parameter as an argument.
```ts
const topic = new sns.Topic(this, 'MyTopic', {
  tracingConfig: 'Active',
});
```

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.135.0

### Environment details (OS name and version, etc.)

irrelevant

### PR DESCRIPTION
**Pull request by jun1-t**
### Issue # (if applicable)

Closes #29714

### Reason for this change

Currently, to set the TracingConfig, it is necessary to configure it via L1.
So, add TracingConfig props to L2.

### Description of changes
added TracingConfig props to topic.ts, sns.test.ts, integ.sns.ts, and README.md for AWS SNS.

### Description of how you validated changes
I confirmed with unit test and integ test that it works as expected.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by nmussy — APPROVED** [review]
Previously reviewed in #29715, still LGTM 👍

**Review by TheRealAmazonKendra — APPROVED** [review]
Thank you for your contribution! Excellent feedback here from @nmussy so I have nothing further.

For future reference, maintainers can reopen closed PRs regardless of who closes them so feel free to tag one of us and we can help reopen the original one, if that's easier for you.

**Comment by jun1-t** [comment]
@TheRealAmazonKendra @nmussy 
Thank you for the approval. And, thank you for letting me know about reopening the pull request. I understand.

However, it appears that the subsequent check failed. The details of the error that occurred during the check, it is written as follows, but I'm unsure what specific actions to take. What should I do?

> Mergify doesn't have permission to update

> For security reasons, Mergify can't update this pull request. Try updating locally.
> GitHub response: refusing to allow a GitHub App to create or update workflow .github/workflows/request-cli-integ-test.yml without workflows permission

**Comment by nmussy** [comment]
You should have a checkbox on the right side of this page, which needs to be selected, "Allow edits and access to secrets by maintainers"

image

Once it's done, you can send the message `@mergifyio update` to force it to refresh and merge

**Comment by jun1-t** [comment]
@mergifyio update

**Comment by nmussy** [comment]
This might be an issue with mergify, I'll let a maintainer take over

**Comment by jun1-t** [comment]
@nmussy 
> This might be an issue with mergify, I'll let a maintainer take over

Thank you for letting me know. I understand.
It looks slightly different from nmussy's image, but the checkbox appears to be selected.
image

**Review by xazhao — APPROVED** [review]

**Comment by jun1-t** [comment]
@xazhao 
Thank you for merging.

**Pull request merged**
