### PR TITLE
fix(iam): override Role.applyRemovalPolicy for customizeRoles

### LINKED ISSUE #31651: aws-iam: Role.customizeRoles does not work with constructs that calls applyRemovalPolicy internally
### Describe the bug

`Role.customizeRoles` throws an Error if there is a construct that calls `applyRemovalPolicy` internally. This means users cannot use with some constructs like `RestApi`.

```
Error: Cannot apply RemovalPolicy: no child or not a CfnResource. Apply the removal policy on the CfnResource directly.
```

Based on the unit test code, this appears to be the intended behavior by design. However, in practice, it is difficult for users to check whether `customizeRoles` has been called when using `Role` and avoid calling `applyRemovalPolicy`.

https://github.com/aws/aws-cdk/blob/18eb3eb971fceb8f182ae4f5da5a70447c60d6d0/packages/aws-cdk-lib/aws-iam/test/role.test.ts#L250-L252

For example, `RestApi` calls `applyRemovalPolicy` internally.

https://github.com/aws/aws-cdk/blob/18eb3eb971fceb8f182ae4f5da5a70447c60d6d0/packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts#L592

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

Ensure that the cloud assembly synthesis succeeds even if `Role.applyRemovalPolicy` is called.

### Current Behavior

Throws error:

```
Error: Cannot apply RemovalPolicy: no child or not a CfnResource. Apply the removal policy on the CfnResource directly.
```

### Reproduction Steps

```typescript
const app = new App();
Role.customizeRoles(app);
const stack = new Stack(app, 'Stack');
new RestApi(stack, 'RestApi');
```

and synthesize it.

### Possible Solution

While it might be possible to fix `RestApi`, there could be other constructs within aws-cdk-lib that also call `Role.applyRemovalPolicy`. Moreover, it's nearly impossible to make library users aware of this.

Since `Role` implements the `IResource` interface, it has the responsibility to respond to the `applyRemovalPolicy` call. Therefore, I think it would be good to override `applyRemovalPolicy` in the `Role` class.

### Additional Information/Context

_No response_

### CDK CLI Version

2.161.0 (build be5ad8b)

### Framework Version

2.161.0

### Node.js Version

v20.13.1

### OS

macOS Sonoma

### Language

TypeScript

### Language Version

TypeScript v5.6.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by konokenj**
### Issue # (if applicable)

Closes #31651 

### Reason for this change

`Role.customizeRoles` throws an Error if there is a construct that calls `applyRemovalPolicy` internally. This means users cannot use with some constructs like `RestApi`.

```
Error: Cannot apply RemovalPolicy: no child or not a CfnResource. Apply the removal policy on the CfnResource directly.
```

This can be reproduced with:

```typescript
const app = new App();
Role.customizeRoles(app);
const stack = new Stack(app, 'Stack');
new RestApi(stack, 'RestApi');
```

Or explicitly:
 
```typescript
const app = new App();
Role.customizeRoles(app);
const stack = new Stack(app, 'Stack');
const role = new Role(stack, 'Role', { assumedBy: new ServicePrincipal('sns.amazonaws.com') });
role.applyRemovalPolicy(RemovalPolicy.DESTROY);
```

### Description of changes

While it might be possible to fix `RestApi`, there could be other constructs within aws-cdk-lib that also call `Role.applyRemovalPolicy`. Moreover, it's nearly impossible to make library users aware of this.

Since `Role` implements the `IResource` interface, it has the responsibility to respond to the `applyRemovalPolicy` call. Therefore, I think it would be good to override `applyRemovalPolicy` in the `Role` class.

### Description of how you validated changes

Fixed the existing unit test to change behavior.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by konokenj** [comment]
Exemption Request

I've run integ tests in aws-iam, but no changes.

```
❯ yarn integ aws-iam/test/integ.*.js                     
yarn run v1.22.22
$ integ-runner --language javascript aws-iam/test/integ.access-key.js aws-iam/test/integ.composite-principal.js aws-iam/test/integ.condition-with-ref.js aws-iam/test/integ.group.js aws-iam/test/integ.imported-role.js aws-iam/test/integ.instance-profile.js aws-iam/test/integ.managed-policy.js aws-iam/test/integ.oidc-provider.js aws-iam/test/integ.permissions-boundary.js aws-iam/test/integ.policy.js aws-iam/test/integ.principal-with-conditions-and-tags.js aws-iam/test/integ.principal-with-conditions.js aws-iam/test/integ.role.js aws-iam/test/integ.saml-provider.js aws-iam/test/integ.user-import.js aws-iam/test/integ.user.js aws-iam/test/integ.users-and-groups.js

Verifying integration test snapshots...

   Waiting for 17 more
  UNCHANGED  aws-iam/test/integ.user-import 59.019s
  UNCHANGED  aws-iam/test/integ.user 59.137s
  UNCHANGED  aws-iam/test/integ.group 59.023s
  UNCHANGED  aws-iam/test/integ.access-key 59.138s
  UNCHANGED  aws-iam/test/integ.composite-principal 59.218s
  UNCHANGED  aws-iam/test/integ.saml-provider 59.55s
  UNCHANGED  aws-iam/test/integ.principal-with-conditions-and-tags 59.556s
  UNCHANGED  aws-iam/test/integ.role 59.752s
  UNCHANGED  aws-iam/test/integ.principal-with-conditions 59.846s
  UNCHANGED  aws-iam/test/integ.condition-with-ref 59.864s
  UNCHANGED  aws-iam/test/integ.permissions-boundary 59.885s
  UNCHANGED  aws-iam/test/integ.instance-profile 59.814s
  UNCHANGED  aws-iam/test/integ.imported-role 60.011s
  UNCHANGED  aws-iam/test/integ.managed-policy 60.09s
  UNCHANGED  aws-iam/test/integ.policy 60.352s
  UNCHANGED  aws-iam/test/integ.oidc-provider 60.714s
  UNCHANGED  aws-iam/test/integ.users-and-groups 15.874s

Snapshot Results: 

Tests:    17 passed, 17 total
✨  Done in 80.46s.
```

**Review by GavinZZ — DISMISSED** [review]
LGTM, nice fix!

**Comment by GavinZZ** [comment]
@konokenj thanks for raising the PR. I think the changes look good, but I would still like to request to update an existing/add  a new integration under `aws-cdk-lib/aws-iam` to test the example you described, where using `Role.customizeRoles(stack)` and create an RestAPI resource.

**Comment by konokenj** [comment]
I added integration tests while referring to this.

https://github.com/aws/aws-cdk/blob/e1d3e8746b62e623bb1b3305354c60856eaea1eb/packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-customize-roles.ts

**Review by GavinZZ — APPROVED** [review]

**Pull request merged**
