### PR TITLE
fix(iam): AccountPrincipal accepts values which aren't account IDs

### LINKED ISSUE #20288: aws_iam: `any` parameter type in AccountPrinciple constructor
### Describe the bug

The AccountPrinciple class as found in: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-iam/lib/principals.ts#L395 has a construct that takes a single argument which is the `accountId` the type of this 'account id' parameter is `any`. Can this parameter be changed to be of type `string` instead?

### Expected Behavior

I expect the following piece of code to give a Type error on the first parameter.
```ts
new aws_iam.AccountPrincipal({ hello: 'world' }); // This is currently valid, and should not be, it should throw a TypeError
new aws_iam.AccountPrincipal('0123456789012'); // This is valid, and should be
```

### Current Behavior

Currently, TypeScript does not complain about the code below.
```ts
new aws_iam.AccountPrincipal({ hello: 'world' }); // This is currently valid, and should not be, it should throw a TypeError
new aws_iam.AccountPrincipal('0123456789012'); // This is valid, and should be
```

### Reproduction Steps

```
import { aws_iam } from 'aws-cdk-lib';

new aws_iam.AccountPrincipal('0123456789012');
new aws_iam.AccountPrincipal({ hello: 'world' });
```

### Possible Solution

To fix this we can simply replace `any` with `string` in the constructor parameter of the `AccountPrinciple` class in:  https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-iam/lib/principals.ts#L395

But first, we should double check there isn't any reasoning behind this being of type `any`.

### Additional Information/Context

_No response_

### CDK CLI Version

2.16.0 (build 4c77925)

### Framework Version

_No response_

### Node.js Version

v14.18.0

### OS

MacOS

### Language

Typescript

### Language Version

3.9.7

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tejasmr**
Changed the type of accountId in AccountPrincipal constructor to string from any fixes #20288 

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by tezz-io** [comment]
The parameter accountId was having the type 'any' and being assigned to a data member of class AccountPrincipal called principalAccount which is of type 'string | undefined'. accountId and principalAccount are meant to hold the AWS account id which should be in the form of string. Changing the type annotation of accountId as parameter in AccountPrincipal constructor won't have any other effects other than specifying the TypeScript linter the type of the parameter accountId. There doesn't seem to be any other reason for the type of accountId to be 'any' since this parameter is only part of the constructor, and will be used to create the stack dependent token and assigning to principalAccount in the constructor. The format of the stack dependent token only works with valid accountId, and the principalAccount should also be valid accountId. If you pass an object, it should give you TypeError to indicate the error in the format given to the AccountPrincipal constructor.

**Comment by tezz-io** [comment]
Seems like a check compatibility issue: [check-api-compatibility.sh](https://github.com/aws/aws-cdk/blob/master/scripts/check-api-compatibility.sh)
From this, [aws-iam](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-iam) folder, there is a .warnings.jsii.js file which is not tracked in git. 
This file has the following line:
```js
function _aws_cdk_aws_iam_AccountPrincipal(p) {
}
...
module.exports = { ..., _aws_cdk_aws_iam_AccountPrincipal, ... };

```
The build is failing because of this. I tried to add the type annotation but it is not supported by javascript files. Either we have to make this file typescript (refactor rename it) and add type annotation `p: string`, or we have to remove this compatibility check for AccountPrincipal. There might be some work around for this, which I am not aware of.

**Comment by tezz-io** [comment]
@rix0rrr can you review this PR?

**Review by rix0rrr — DISMISSED** [review]
I agree this is poor choices in the past, but unencoded tokens (`IResolvable`) are accepted here, and the change would require code changes by consumers (i.e., not acceptable).

We have to change this into a run-time check, unfortunately:

```ts
if (!Token.isUnresolved(accountId) && typeof accountId !== 'string') {
  throw new Error('...');
}
```

**Review by tezz-io — COMMENTED** [review]
Where should I add this change, if I can do it?

**Comment by rix0rrr** [comment]
> I added this change inside the constructor and reverted back to any. Should this be a fix or a chore?

Both are reasonable. You can call it a `fix` if you want to :)

**Comment by rix0rrr** [comment]
```
@aws-cdk/aws-iam: lib/principals.ts:396:10 - error TS2304: Cannot find name 'Token'.
@aws-cdk/aws-iam: 396     if (!Token.isUnresolved(accountId) && typeof accountId !== 'string') {
```

**Comment by tezz-io** [comment]
@rix0rrr can you review?

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Still needs a test, and the breaking changes except is no longer necessary

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
