### PR TITLE
feat(bedrock): support meta llama3-2

### PR DESCRIPTION
**Pull request by go-to-k**
### Issue # (if applicable)

Closes #<issue number here>.

### Reason for this change

Added Meta Llama 3.2 models.

- meta.llama3-2-1b-instruct-v1:0
- meta.llama3-2-3b-instruct-v1:0
- meta.llama3-2-11b-instruct-v1:0
- meta.llama3-2-90b-instruct-v1:0

ref

- https://aws.amazon.com/about-aws/whats-new/2024/09/llama-3-2-generative-ai-models-amazon-bedrock/
- https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html

### Description of changes

Added the models.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by sumupitchayan — COMMENTED** [review]
Thanks for the PR - can you validate these changes by adding these newly supported models to an existing integ test and update the snapshots? Just to confirm that it deploys - also a nit, I think this should be a `feat` instead of a `chore`

**Comment by go-to-k** [comment]
@sumupitchayan 

> can you validate these changes by adding these newly supported models to an existing integ test and update the snapshots?

Integ tests don't yet appear to exist in the bedrock module, and there is no a directory for bedrock in the @aws-cdk-testing module. What should I do?

**Comment by go-to-k** [comment]
Oh, I found in SFn tasks module! I will add to the test.

https://github.com/go-to-k/aws-cdk/blob/9ddfe788283e1b42508299e3f9cc2ea3aae5134f/packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.ts#L16

**Comment by go-to-k** [comment]
@sumupitchayan 

Updated and run.

**Review by sumupitchayan — APPROVED** [review]
LGTM, thanks for adding the test!

**Comment by go-to-k** [comment]
@Mergifyio update

**Pull request merged**
