### PR TITLE
fix(ecr-assets): fix repeated deploys of stacks with tar assets

### LINKED ISSUE #18822: (cdk-assets): TarballImageAsset fails build if trying to load tarball with existing tag
### What is the problem?

When loading an image tarball that has different contents, but the same image tag, it will fail to load with an error similar to the following:

```
Error parsing reference: "The image bazel/projects/my_image:my_image already exists, renaming the old one with ID sha256:b9bf91fbc75ee3d7f9d78c7c2f27d06205f8c71f274b444ebfe573c9d159c26f to empty string\nbazel/projects/my_image:my_image" is not a valid repository/tag: invalid reference format: repository name must be lowercase
```

### Reproduction Steps

This is a complete example script to show reproduce the root cause error without a bunch of CDK code:

```
echo "FROM busybox\nWORKDIR /" | docker build -t cdk_example:test -
docker save cdk_example:test -o test.tar
echo "FROM busybox\nWORKDIR /different" | docker build -t cdk_example:test -
docker load -i test.tar
```

When executing that final load, you'll get the output:

```
The image cdk_example:test already exists, renaming the old one with ID sha256:3e782920eed15d9f99ae20b58d734022aacd6f510a128c3baad4377b3541b419 to empty string
Loaded image: cdk_example:test
```

When CDK itself loads an image, it gets the repository and tag for an image by piping the output of `docker load` to `sed "s/Loaded image: //g"`

If that `sed` command is run on the typical output, you correctly get the image name. But when run on the output above, you get:

```
The image cdk_example:test already exists, renaming the old one with ID sha256:3e782920eed15d9f99ae20b58d734022aacd6f510a128c3baad4377b3541b419 to empty string
cdk_example:test
```

Which then fails when CDK attempts to re-tag the image for upload to ECR.

### What did you expect to happen?

The image would deploy successfully

### What actually happened?

The image fails to deploy when trying to load the tarball for pushing

### CDK CLI Version

2.9.0 (build a69725c)

### Framework Version

_No response_

### Node.js Version

v16.13.2

### OS

Linux

### Language

Python

### Language Version

_No response_

### Other information

The following `sed` command is able to accurately extract the image name:

```
sed -nr 's/^Loaded image: (.*)$/\1/p'
```

Credit to this comment for a more robust way to do this:  https://github.com/docker/cli/issues/2212#issuecomment-953224385

### PR DESCRIPTION
**Pull request by dastbe**
The current implementation fails because it assumes the output of
`docker load` can only be

```
Loaded Image: {image}
```

However, if docker has to take any actions (such as untagging a previous
image) the output will look like

```
{error message}
{error message}
Loaded Image: {image}
```

To fix this, we can simply take the last line of the output via `tail`
before we attempt to extract the image. If the last line isn't of the
correct form, this will fail in an effectively equivalent way to how it
failed previously.

A previous attempt at fixing this (#18823) used a more complicated `sed`
command which used a cli flag that is not consistently available. This
approach won't work on all platforms (ex. macos) and is also much less
clear that it's correct.

This change also adds an integration test that tests the tarbell stack, though
it doesn't test the repeated deploy automatically. I have tested that by
running the integration test multiple times with an image modification in
between. We also vendor the tarball of the hello-world docker image, which
results in ~20kb of additional data in the repo. This is about as small as we
can get a vendored image with as straightforward a vendoring process.

fixes #18822

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by dastbe** [comment]
ping!

**Review by comcalvi — DISMISSED** [review]
We have a `demo-tarball` file with an empty tarball in it...Instead of using `hello-world`, can we use a tarball form of the `demo-image` directory under `test`?

**Comment by dastbe** [comment]
> We have a `demo-tarball` file with an empty tarball in it...Instead of using `hello-world`, can we use a tarball form of the `demo-image` directory under `test`?

so unfortunately an empty tarball is not valid from docker's perspective, so won't be loaded and therefore the integration test will fail. here's an example:

```
docker images
REPOSITORY              TAG       IMAGE ID       CREATED       SIZE
ghcr.io/dagger/engine   v0.3.9    2671daeb98d9   5 weeks ago   183MB
dastbe on Davids-Air in ~/workplace/aws-cdk/packages/@aws-cdk/aws-ecr-assets/test (fix-repeated-tarball-invocations)
docker load -i demo-tarball/empty.tar
open /var/lib/docker/tmp/docker-import-995944040/repositories: no such file or directory
dastbe on Davids-Air in ~/workplace/aws-cdk/packages/@aws-cdk/aws-ecr-assets/test (fix-repeated-tarball-invocations)
docker images
REPOSITORY              TAG       IMAGE ID       CREATED       SIZE
ghcr.io/dagger/engine   v0.3.9    2671daeb98d9   5 weeks ago   183MB
dastbe on Davids-Air in ~/workplace/aws-cdk/packages/@aws-cdk/aws-ecr-assets/test (fix-repeated-tarball-invocations)
docker load -i demo-tarball-hello-world/hello-world.tar
efb53921da33: Loading layer [==================================================>]  10.75kB/10.75kB
Loaded image: hello-world:latest
dastbe on Davids-Air in ~/workplace/aws-cdk/packages/@aws-cdk/aws-ecr-assets/test (fix-repeated-tarball-invocations)
docker images
REPOSITORY              TAG       IMAGE ID       CREATED         SIZE
ghcr.io/dagger/engine   v0.3.9    2671daeb98d9   5 weeks ago     183MB
hello-world             latest    46331d942d63   11 months ago   9.14kB
```

**Review by MrArnoldPalmer — DISMISSED** [review]
@dastbe thanks for your patience here. With the test failure using the empty-tarball I think vendoring `hello-world` is alright. I'd say lets remove the `update.sh` script cause I don't really see the need to update the image in the tarball for testing purposes and it isn't referenced anywhere in the test.

Additionally investigated changing the test, to either be a unit test or to not actually deploy the stack in the integ test using `deploy: { enabled: false }` because we don't actually need it to do so, only to build the images with docker. Either way though the build commands don't get run until actual stack deploy so I believe this is in fact the best way to test this for now.

**Comment by dastbe** [comment]
> I'd say lets remove the update.sh script cause I don't really see the need to update the image in the tarball for testing purposes and it isn't referenced anywhere in the test.

done

> Additionally investigated changing the test, to either be a unit test or to not actually deploy the stack in the integ test using deploy: { enabled: false } because we don't actually need it to do so, only to build the images with docker. Either way though the build commands don't get run until actual stack deploy so I believe this is in fact the best way to test this for now.

just to clarify you're not asking me to change anything correct?

**Review by MrArnoldPalmer — DISMISSED** [review]
> just to clarify you're not asking me to change anything correct?

Correct, you're all good 👍🏻

**Comment by TheRealAmazonKendra** [comment]
When you manually rebase or merge from main, it cancels our reviews, which is why this hasn't merged yet. Please do not take that action in the future, unless using the command `@Mergifyio update`. Our automation takes care of handling everything once we've provided an approval.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
