### PR TITLE
docs(codepipeline): clarification for the CodeBuildAction extraInputs property

### PR DESCRIPTION
**Pull request by logemann**
### Commit Message
docs(codepipeline): clarification for the CodeBuildAction extraInputs property

### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by swyp-de** [comment]
The 00, 01 are the resulting subfolders on the buildmachine's filesystem. People normally need to know how this is structured because they do a lot of commands in the buildSpec section like copying files and stuff. Dont know what kind of link to Codebuild doc you mean. I like inline documentation on the properties because thats where developers look at in the first place.

**Comment by logemann** [comment]
never mind. 01, 01 are a folder which is part of CODEBUILD_SRC_DIR like 

CODEBUILD_SRC_DIR=/codebuild/output/src913/src/s3/00
or
CODEBUILD_SRC_DIR_Artifact_Source_Swyp_S3_Source=/codebuild/output/src913/src/s3/01

So referencing to the variable name instead of the specific folder on the build system seems to make more sense.

**Comment by skinny85** [comment]
Right, but those are 100% implementation details of how CodeBuild works internally. They are not documented anywhere, and are very likely to change, so I don't think adding them to CDK docs is a good idea.

**Comment by logemann** [comment]
you are 100% right.

**Comment by skinny85** [comment]
Do you want to change the PR to mention the `CODEBUILD_SRC_<build-artifact-name` environment variables instead?

**Comment by logemann** [comment]
yep sorry. Will do....

**Comment by logemann** [comment]
finalized the inline doc. There is also a typo in https://docs.aws.amazon.com/codebuild/latest/userguide/sample-multi-in-out.html when it comes to the following section:

This directory is stored in the built-in environment variable **CODEBUILD_SRC_DIR_sourceIdentifer**. For more information, see Environment variables in build environments.

there is a "i" missing. Just want to mention it. I accidentally copied that in the inline doc but then fixed it again.

**Comment by logemann** [comment]
Dang... did i merge wrongly? Just wanted to reintegrate latest master to my "featurebranch"....

**Comment by skinny85** [comment]
> Dang... did i merge wrongly? Just wanted to reintegrate latest master to my "featurebranch"....

You had some trailing whitespace in the commit, which our linter rejects (you can see the build results in the comment that the automation makes on the PR).

**Pull request merged**
