### PR TITLE
feat(cli): add deploy order info to CDK deploy command

### PR DESCRIPTION
**Pull request by AlexGurtoff**
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

closes https://github.com/aws/aws-cdk/issues/22882

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by AlexGurtoff** [comment]
I don't think README.md changes are required in the scope of this PR. Also, I'm unable to run integration tests. Please run one of the maintainers if this is still required

**Comment by mrgrain** [comment]
@AlexGurtoff I'm concerned about the experience for users with a lot of stacks. Also with parallel deployments the numbers maybe aren't that useful. Maybe this should be hidden behind a verbosity//debug check. What do you think?

**Comment by AlexGurtoff** [comment]
> @AlexGurtoff I'm concerned about the experience for users with a lot of stacks. Also with parallel deployments the numbers maybe aren't that useful. Maybe this should be hidden behind a verbosity//debug check. What do you think?

@mrgrain Thank you for your response and suggestion! But what if hide this feature behind the flag, like `--show-order`? I would like this feature to be usable without the need to turn on the debug level, because it really can be useful for normal deployments, not only for debug :)

**Comment by mrgrain** [comment]
@AlexGurtoff Yeah that's fair. Although there's always going to be a balance between different needs. Arguably the current output with one verbosity level is too verbose. 😅 

But anyway. Your suggestion of a new flag reminded me that `cdk list` already displays the stacks in order of deployment. I think this is the better experience. Anyone who is interested in this information can run an additional command. I think this PR is not needed anymore.

**Pull request closed without merging**
