### PR TITLE
fix(cloudfront): custom originId not used for multiple behaviors with same origin

### LINKED ISSUE #22758: (cloudfront): (custom originId handling issue for multiple behaviours with same origin)
### Describe the bug

When setting custom `originId`s for CloudFront origins und the new `Distribution` construct there is an issue when using the same origin for multiple behaviours. The first behaviour uses the correct custom `originId` as `TargetOriginId` but every behaviour after that use the auto-generated `originId` instead of the correct custom `originId`.

### Expected Behavior

The custom `originId` is used for every usage of the origin in the behaviors in the `TargetOriginId` property.

### Current Behavior

Only the first behaviour using a given origin uses the correct custom `originId` in the `TargetOriginId` property. Every behaviour after that uses the auto-generated id.

### Reproduction Steps

Create origin with custom `originId` and use it in at least two behaviours. 

### Possible Solution

Prepared the following fix: https://github.com/aws/aws-cdk/pull/22756

### Additional Information/Context

_No response_

### CDK CLI Version

2.50.0

### Framework Version

_No response_

### Node.js Version

v14.19.1

### OS

OSX

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by patricksuter**
When setting custom `originId`s for CloudFront origins und the new `Distribution` construct there is an issue when using the same origin for multiple behaviours. The first behaviour uses the correct custom `originId` as `TargetOriginId` but every behaviour after that use the auto-generated `originId` instead of the correct custom id.

fixes #22758

Improved the handling of the `originId` to correctly pick either the auto-generated `originId` or the explicitly set `originId` of the origin. The issue was caused by the auto-generated `originId` to always be set on the internal list of origins which caused issues when adding more than one behaviour since the wrong id was returned when re-using an existing origin from the internal list.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by mrgrain — APPROVED** [review]
Looks good! Thanks for the excellent PR 🚀

**Comment by mrgrain** [comment]
Hi @patricksuter unfortunately we cannot merge this right now as your fork does not allow our automation to push changes to your branch.
https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Please let me know once you've adjusted the fork settings and I can get this back into the queue.

**There is not need for you to manually update the branch from main at this stage. In fact this will reset any approval and further delay shipping this change.**

**Comment by patricksuter** [comment]
@mrgrain I cannot give the necessary permissions to push changes because I used our fork of the aws-cdk repo from our organization. I guess I need to create a user-based fork and re-open a new pull request or do have any idea on how to grant the necessary permission on this PR?

**Comment by mrgrain** [comment]
@patricksuter Yes please re-open the PR from a user-based fork. That seems to be the easiest way.

**Comment by mrgrain** [comment]
Closed in favor of #22830

**Pull request closed without merging**
