### PR TITLE
fix: import should write overrideTemplate to assembly.outdir

### LINKED ISSUE #2083: cdk deploy show me: ENOENT: no such file or directory, mkdtemp
## Step to reproduce
```
mkdir hello-cdk
cd hello-cdk
cdk init app --language=typescript
cdk deploy
```
ENOENT: no such file or directory, mkdtemp '/home/oren/t/cdkMDNeAB'

## Useful information

I use Ubuntu in Windows (Windows Subsystem for Linux)

cat /etc/lsb-release
```
Ubuntu 18.04.1 LTS
```

node -v
```
v10.15.3
```

cdk --version
```
0.26.0 (build e6f3f48)
```

### PR DESCRIPTION
**Pull request by nburtsev**
### Issue # (if applicable)

Addresses #22530 

### Reason for this change

During `cdk import` template file is written to the project root, not to `cdk.out` which fails the following stack deployment.

### Description of changes

I've just added a path.join similar to how it is done in regular template generation.

### Description of how you validated changes

I've tested this locally, imports stacks just fine.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nburtsev** [comment]
Exemption Request

Not sure if this should be an exemption or a clarification, but this only affects `cdk import` which has no tests at the moment, I've tested it locally but I don't think I can come up with tests to commit on my own.

**Comment by TheRealAmazonKendra** [comment]
Also, we do have cdk import tests. Unit tests are in https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/test/import.test.ts and integ tests are in https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk-testing/cli-integ/tests/cli-integ-tests.

**Comment by nburtsev** [comment]
@TheRealAmazonKendra  Thank you very much for pointing the tests to me, I completely missed them. 

Let me try to explain the problem. When the template is synthesized, if it is larger than 50kb and cannot be inlined in the request, CLI writes it to filesystem to be uploaded to S3. Unlike regular deployments `import` overrides the template, when it does so the code responsible for writing the large template to the filesystem does it to project root. 

This code reproduces the issue:
```
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as sqs from "aws-cdk-lib/aws-sqs";
import * as iam from "aws-cdk-lib/aws-iam";

export class AwsCdkImportBugStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    for (let i = 0; i < 70; i++) {
      const q = new sqs.Queue(this, `AwsCdkImportBugQueue${i}`, {
        visibilityTimeout: cdk.Duration.seconds(300),
        enforceSSL: true,
      });
    }

    // new sqs.Queue(this, `AwsCdkImportBugQueue`, {
    //   visibilityTimeout: cdk.Duration.seconds(300),
    //   enforceSSL: true,
    //   removalPolicy: cdk.RemovalPolicy.RETAIN,
    // });
  }
}

```

Deploy the stack, uncomment the queue, and try to import. This error happens: 
```
$ npx cdk import                                  
AwsCdkImportBugStack
AwsCdkImportBugStack/AwsCdkImportBugQueue/Resource (AWS::SQS::Queue): enter QueueUrl (empty to skip): https://sqs.eu-central-1.amazonaws.com/<cut>/AwsCdkBugStack-keep186A2ECA-IznVNwytuY1b
AwsCdkImportBugStack/AwsCdkImportBugQueue/Policy/Resource (AWS::SQS::QueuePolicy): enter Id (empty to skip): 
Skipping import of AwsCdkImportBugStack/AwsCdkImportBugQueue/Policy/Resource
AwsCdkImportBugStack: importing resources into stack...
[0%] start: Publishing 06a2c6415fd2982e3285e9d615e5f9b99d1d795a9064479fbe6b88455ac62f6c:current
[100%] fail: ENOENT: no such file or directory, open '/home/nburtsev/projects/aws-cdk-import-bug/cdk.out/AwsCdkImportBugStack.template.json-06a2c6415fd2982e3285e9d615e5f9b99d1d795a9064479fbe6b88455ac62f6c.yaml'

 ❌  AwsCdkImportBugStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at publishAssets (/home/nburtsev/projects/aws-cdk-import-bug/node_modules/aws-cdk/lib/index.js:420:84876)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack (/home/nburtsev/projects/aws-cdk-import-bug/node_modules/aws-cdk/lib/index.js:430:391)
    at async ResourceImporter.importResources (/home/nburtsev/projects/aws-cdk-import-bug/node_modules/aws-cdk/lib/index.js:433:171694)
    at async ResourceImporter.importResourcesFromMap (/home/nburtsev/projects/aws-cdk-import-bug/node_modules/aws-cdk/lib/index.js:433:171357)
    at async CdkToolkit.import (/home/nburtsev/projects/aws-cdk-import-bug/node_modules/aws-cdk/lib/index.js:433:205058)
    at async exec4 (/home/nburtsev/projects/aws-cdk-import-bug/node_modules/aws-cdk/lib/index.js:488:54378)

Failed to publish one or more assets. See the error messages above for more information.
```

The file is created, it's just in the project root not in cdk.out:
```
~/projects/aws-cdk-import-bug $ ls -la         
total 284
drwxr-xr-x   7 nburtsev users   4096 Mar 22 10:48 .
drwxr-xr-x   8 nburtsev users   4096 Mar 22 10:11 ..
-rw-r--r--   1 nburtsev users  64131 Mar 22 10:48 AwsCdkImportBugStack.template.json-06a2c6415fd2982e3285e9d615e5f9b99d1d795a9064479fbe6b88455ac62f6c.yaml
drwxr-xr-x   2 nburtsev users   4096 Mar 22 10:12 bin
-rw-r--r--   1 nburtsev users   3185 Mar 22 10:12 cdk.json
drwxr-xr-x   2 nburtsev users   4096 Mar 22 10:48 cdk.out
<cut>
```

Concerning tests, now that I know where they are I will attempt to adjust them. Please advise if adding another conditional resource creation in https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js#L122 similar to what is already there, that would create 70 queues and then attempt the import (i.e. same as my example code does) is acceptable.

**Comment by MikeDombo** [comment]
Same problem as https://github.com/aws/aws-cdk/issues/22530

**Comment by TheRealAmazonKendra** [comment]
Ohhhhhhh. I see. Thanks for the explanation!

**Comment by TheRealAmazonKendra** [comment]
Well, this is fun. Turns out that cdk import test is broken and passing because it's not actually testing anything. Gimme a day to try and get that fixed and then I'll revisit your PR. With your explanation, I think your solution is likely correct but I have strong reservations about letting a change go through when the test is not testing.

**Comment by TheRealAmazonKendra** [comment]
Do not merge label added because of issues with test, not with PR.

**Comment by nburtsev** [comment]
Figured I'd post this here, while it is being worked on.
If you encounter this issue - just move the file that's generated into cdk.out and run the import again, as long as you have the same inputs (or use json mapping for it) it will run just fine.

**Pull request closed without merging**
