### PR TITLE
fix(docs): fix issue #718 (Aurora DB example)

### PR DESCRIPTION
**Pull request by Doug-AWS**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

Resolves issue #718

### CODE REVIEW

**Comment by eladb** [comment]
Please update PR title and description to adhere to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2). The title should be something like `fix(docs): fix Aurora DB example`

**Comment by eladb** [comment]
Also make sure that you modify the __commit__ title to adhere to conventional commits.

**Comment by Doug-AWS** [comment]
I also updated the commit message.

**Comment by eladb** [comment]
You will need to update the commit message when you "Squash and merge" from the GitHub UI...

**Pull request merged**
