### PR TITLE
feat(redshift): adds elasticIp parameter to redshift cluster

### LINKED ISSUE #19191: (aws-redshift): Redshift construct is missing the  elasticIp property
### What is the problem?

The aws-redshift-alpha cluster construct as spec'd here:

https://constructs.dev/packages/@aws-cdk/aws-redshift-alpha/v/2.14.0-alpha.0/api/Cluster?lang=typescript

is missing the elasticIp property on the CfnCluster resource.  

### Reproduction Steps

instantiate a new Cluster resource.  elasticIp prop is missing.

### What did you expect to happen?

the elasticIp property needs to be available or the construct is not able to associate an elastic IP.

### What actually happened?

elasticIp property is missing.

### CDK CLI Version

2.14

### Framework Version

_No response_

### Node.js Version

v16.14.0

### OS

macOS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by daschaa**
Fixes #19191.

Adds the property `elasticIp` to the `ClusterProps`.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by corymhall — DISMISSED** [review]
@daschaa it looks like there are some additional considerations when creating a public redshift cluster and using an elasticIP https://docs.aws.amazon.com/redshift/latest/mgmt/managing-clusters-vpc.html.

Can you update the README to have a section that discusses this?

**Comment by daschaa** [comment]
> @daschaa it looks like there are some additional considerations when creating a public redshift cluster and using an elasticIP https://docs.aws.amazon.com/redshift/latest/mgmt/managing-clusters-vpc.html.
> 
> Can you update the README to have a section that discusses this?

Of course! Thanks for the feedback.
In the link you provided is a really good section about the elastic ip configuration. Quote:

> If you configure your cluster to be publicly accessible, you can optionally select an elastic IP address to use for the external IP address. An elastic IP address is a static IP address that is associated with your AWS account. You can use an elastic IP address to connect to your cluster from outside the VPC. An elastic IP address gives you the ability to change your underlying configuration without affecting the IP address that clients use to connect to your cluster. This approach can be helpful for situations such as recovery after a failure.

Is it ok to copy this to the readme? Imho it explains it very good and simple. :)

**Comment by corymhall** [comment]
> Is it ok to copy this to the readme? Imho it explains it very good and simple. :)

yeah I think that is fine. Some of the other items I think it is important to include:

1. The piece around connecting from within the VPC (with a code example showing the VPC configuration)
2. The note around giving the cluster an elastic IP _before_ making the VPC configuration (only active after a resize)
3. When to use the elasticIP vs the `clusterEndpointAddress`
4. How to attach or change the ip  _after_ the cluster has been completed.

**Comment by daschaa** [comment]
@corymhall I updated the Readme and added the section about the elastic ip. I hope everything is ok - it would be great if you could double check.

In the topic of * when to use elastic ip vs. cluster endpoint* I'm not quite sure how to formulate it. As far as I understand it, the elastic ip should only be used when you **need** to have a static ip which you use to connect to the Redshift Cluster and the cluster endpoint is more dynamic, because it is a DNS address which is generated. Is it correct?

And the last thing about changing the ip after the cluster has been completed I do not quite understand. Could you give me a hint where to look regarding this topic?

Thanks in advance! ❤️

**Comment by corymhall** [comment]
> And the last thing about changing the ip after the cluster has been completed I do not quite understand. Could you give me a hint where to look regarding this topic?

It's near the bottom of that page:


> The option to associate a cluster with an elastic IP address is available when you create the cluster or restore the cluster from a snapshot. In some cases, you might want to associate the cluster with an elastic IP address or change an elastic IP address that is associated with the cluster. To attach an elastic IP address after the cluster is created, first update the cluster so that it is not publicly accessible, then make it both publicly accessible and add an Elastic IP address in the same operation. 
 
----------------------

> In the topic of when to use elastic ip vs. cluster endpoint I'm not quite sure how to formulate it. 

I would just take from this portion. I think the important thing to not is just that they are _not_ the same thing. There might be some confusion if there is a public _elasticIP_ _and_ a public _node_ ip address.

> The elastic IP address is an external IP address for accessing the cluster outside of a VPC. It's not related to the cluster node public IP addresses and private IP addresses that are displayed in the Amazon Redshift console under Connection details. The public and private cluster node IP addresses appear regardless of whether the cluster is publicly accessible or not. They are used only in certain circumstances to configure ingress rules on the remote host. These circumstances occur when you load data from an Amazon EC2 instance or other remote host using a Secure Shell (SSH) connection.

**Review by corymhall — APPROVED** [review]
@daschaa awesome! love the readme updates ❤️

**Comment by daschaa** [comment]
@corymhall Are the tests flaky? Because I did not change anything I think..

**Pull request merged**
