### PR TITLE
fix(custom_resources): Provider Lambda function is missing lambda:GetFunctionConfiguration permission

### LINKED ISSUE #26838: custom_resources: Provider Lambda function is missing lambda:GetFunctionConfiguration
### Describe the bug

The [Landing Zone Accelerator](https://github.com/awslabs/landing-zone-accelerator-on-aws) solution leverages the custom_resources module to create service-linked roles via CDK custom resources. When this custom resource Lambda function is invoked several times in succession, users intermittently receive the following error:

```
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
```

We believe this is the result of queuing incoming requests and the role attached to the `cdk.custom_resources.Provider` function is missing the permission: `lambda:GetFunctionConfiguration`

### Expected Behavior

Custom resource provider implements appropriate permissions and retries to execute successfully when invoked several times in succession. 

### Current Behavior

Transient failures:

```
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
```

### Reproduction Steps

Deploy v1.4.3 of the Landing Zone Accelerator on AWS.

For a smaller sample that can be extracted without deploying the entire LZA solution, you may use this custom resource construct that is used by LZA to create the service-linked roles:

https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/1614a01824c5a43f97fadfb8ec0c3627a0f343dd/source/packages/%40aws-accelerator/constructs/lib/aws-iam/service-linked-role.ts#L87

### Possible Solution

Add `lambda:GetFunctionConfiguration` permission to the provider Lambda function's IAM role.

### Additional Information/Context

_No response_

### CDK CLI Version

2.79

### Framework Version

_No response_

### Node.js Version

16.20.1

### OS

Amazon Linux

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jasoncaoawshc**
This PR solves the problem of missing permissions for lambda created with the provider framework. 

We found this issue in the [landing zone accelerator](https://github.com/awslabs/landing-zone-accelerator-on-aws) solution that leverages the custom_resources module. [Related issue](https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/237). 

Closes #26838.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jasoncaoawshc** [comment]
Exemption Request: integration tests do not exist for the custom_resources module

**Comment by scanlonp** [comment]
Hello, the custom resource integ tests live here https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk-testing/framework-integ/test/custom-resources/test. 

Additionally, we will not be able to provide a meaningful review until the build is passing.

**Comment by vinayak-kukreja** [comment]
Hey, I see you have opened the PR from `main` branch on your fork. Could you move to another branch. You can find more information about this in our [Contribution](https://github.com/aws/aws-cdk/pull/27204) guide.

**Comment by jasoncaoawshc** [comment]
Exemption request: We can't really integ test this as it would require a lambda function that was already inactive (20 minute wait time) and we don't have that resource setup.

**Comment by vinayak-kukreja** [comment]
> Exemption request: We can't really integ test this as it would require a lambda function that was already inactive (20 minute wait time) and we don't have that resource setup.

That is fine, we can run the test for you. But the build is failing right now and we cannot prioritize a review for this PR till that is fixed. Let us know if we can assist with anything.

**Pull request closed without merging**
