### PR TITLE
fix(ec2): launch template names in imdsv2 not unique across stacks (under feature flag)

### PR DESCRIPTION
**Pull request by jericht**
Fixes https://github.com/aws/aws-cdk/issues/17656

### Notes
Changes the name for the `LaunchTemplate` created in the aspect that enforces IMDSv2 on EC2 instances to a unique name.

Introduces a new feature flag (`@aws-cdk/aws-ec2:uniqueImdsv2TemplateName`) to change the launch template name.

### Testing
Added a unit test

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jericht** [comment]
@njlynch This is ready for review now. Could you take a look when you get the chance?

**Review by njlynch — DISMISSED** [review]
Thanks for the fix!

However, I'm not sure this approach will work from a backwards-compatibility perspective. It appears from the docs that changing the `launchTemplateName` on the [LaunchTemplate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html#aws-resource-ec2-launchtemplate-properties) requires replacement, as does altering the `launchTemplateName` on the [Instance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-launchtemplatespecification.html#aws-properties-ec2-instance-launchtemplatespecification-properties).

The above means that accepting this change would cause instance replacements for any user who's using this feature, potentially causing unwanted and/or unexpected data loss.

An alternative approach is required, preferably by adding some mechanism (e.g., new property) for users to explicitly opt into this new naming scheme. Suggestions welcome!

**Review by njlynch — CHANGES_REQUESTED** [review]
Looking at how the implementation turned out, I don't think this is optimal. Deprecating the `requireImdsv2` property for the options property isn't great, and the naming of `uniqueLaunchTemplateNames` is awkward (but I can't think of much better names with this design).

Let's flip this around a bit -- I think this is probably a good place to introduce a [feature flag](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#feature-flags), so we can adjust the default behavior without uglifying the API. :) Maybe something like `@aws-cdk/aws-ec2:uniqueImdsv2TemplateName`. Take a look at the above contributing guide on flags, and let me know if you have any questions on this approach.

**Comment by jericht** [comment]
@njlynch Thanks for pointing me to the feature flag approach, it's much cleaner! I've updated the CR, so it's ready for another review.

**Review by njlynch — APPROVED** [review]
Looks great! I agree - much cleaner.

I made a minor update to use some of our newer best-practice helpers for feature flags. I'll take an action to document them in our contributing guide as well. 

Thanks!

**Pull request merged**
