### PR TITLE
docs(events): update link about key policy for event bus

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

N/A

### Reason for this change
The link about key policy for an Event Bus has been updated.

### Description of changes
Updated a link in docs.

### Description of how you validated changes
No tests because only docs has been changed.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by GavinZZ — APPROVED** [review]
Nice

**Comment by mazyu36** [comment]
@mergifyio update

**Comment by mazyu36** [comment]
@mergifyio refresh

**Comment by mazyu36** [comment]
@Mergifyio update

**Review by sumupitchayan — APPROVED** [review]

**Pull request merged**
