### PR TITLE
fix(secretsmanager): automatic rotation cannot be disabled

### LINKED ISSUE #18749: (secretsmanager): cannot make 'RotationRules' unset for RotationSchedule
### What is the problem?

Without tapping into the `CfnRotationSchedule` construct directly, it is not possible to leave the `RotationRules` (`automaticallyAfter` in the `RotationSchedule` construct) property of `AWS::SecretsManager::RotationSchedule` empty. When using the `CfnRotationSchedule` and not setting the `rotationRules` property, it is left unset as is expected.

The CloudFormation docs (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-rotationschedule.html#cfn-secretsmanager-rotationschedule-rotationrules) has this property set as optional, and when left empty, allows you to configure a rotation lambda without any schedule.

My use-case for this is for secrets that do not need to be automatically rotated, but only on demand when needed.

### Reproduction Steps

```typescript
const rotationSchedule = new secretsmanager.RotationSchedule(this, 'MyRotationSchedule', {
  secret: secret,
  // automaticallyAfter: cdk.Duration.minutes(30),
  rotationLambda: function_,
});
```

### What did you expect to happen?

The resulting CloudFormation template to not have the property `RotationRules` set for the `AWS::SecretsManager::RotationSchedule` resource.

### What actually happened?

The resulting CloudFormation template has the property `RotationRules` set to a default of 30 days for the `AWS::SecretsManager::RotationSchedule` resource.

### CDK CLI Version

2.10.0

### Framework Version

2.10.0

### Node.js Version

16.13.2

### OS

Ubuntu 20.04 LTS (WSL2)

### Language

Typescript

### Language Version

4.5.5

### Other information

_No response_

### PR DESCRIPTION
**Pull request by AdamVD**
fixes #18749

Adds a `manualRotation` prop to `RotationSchedule` in order to leave `automaticallyAfterDays` unset on the underlying Cfn resource.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by AdamVD** [comment]
@skinny85 just bumping this!

**Review by skinny85 — COMMENTED** [review]
@AdamVD thanks for the ping, this slipped under my radar!

Before I dive into the details, what do you think about, instead of adding a new property, adding a "magic" value for `automaticallyAfter` (0 comes to mind immediately), and that will mean "disable rotation"?

**Comment by AdamVD** [comment]
@skinny85 No problem, I figured that was all and that's why I bumped! 

I actually proposed that as one of the two options in the issue #18749. Basically my argument for the solution you see implemented is that it is better from a UX perspective rather than using a "magic" value of zero. The issue creator agreed, but I'll follow your wisdom on what the better solution is out of the two. Just let me know!

**Comment by skinny85** [comment]
I actually feel like `automaticallyAfter: Duration.days(0)` makes it clear to me that rotation is disabled, and doesn't require a separate property (and all of the dance that you have to do to validate that they're not both provided at the same time).

I guess I don't know for a fact that `Duration.days(0)` is allowed 😛. Can you check?

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
I'm inclined to agree that using `automaticallyAfter: Duration.days(0)` is the preferred route. I'm not a big fan of using mutually exclusive optional parameters.

**Comment by skinny85** [comment]
@AdamVD are you still working on this PR?

**Comment by AdamVD** [comment]
@skinny85 Thanks for the bump. I'll try to switch the implementation by early next week.

**Comment by Jacco** [comment]
From a UX perspective maybe a Duration.never() could be implemented so that the user does not have to google if it’s 0 or 9999 :-)

**Comment by AdamVD** [comment]
@Jacco Interesting idea! I also have the feeling that a duration of zero isn't a great UX, but we are limited on options. I think a _never_ option could make sense with something like `Schedule` (from `aws-events`), but it doesn't seem to belong with `Duration`. I wonder if adding `Duration.zero()` would be better than picking one of the time units to provide with `0`. Using a union type would give us some good options but they can't be used in the CDK codebase.

@skinny85 I'll leave it to you to decide!

**Comment by skinny85** [comment]
I really like the ideas here!

Between `Duration.never()` and `Duration.zero()` - that's a tough call! I really like the "fluentness" of `never()`, but I agree it might be a tiny bit confusing.

@AdamVD I'll let you make the final call - propose something in the PR!

Also, to be 100% transparent, I'm no longer with AWS, so I can't merge this PR anymore - but I'd be happy to help in whatever way I can!

**Comment by Jacco** [comment]
Duration.eternity ;-)

**Comment by AdamVD** [comment]
@skinny85 thanks for the input and clarifying your status. Best wishes on your transition!

@Jacco I actually love that... "Automatically rotate my keys after eternity". It's perfect! I wonder if I can get someone to approve this 🤔

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
