### PR TITLE
fix(ec2): passing keypair to instance unexpectedly does nothing

### LINKED ISSUE #28478: aws_ec2: passing keyPair to Instance does nothing
### Describe the bug

With keyName property being deprecated (https://github.com/aws/aws-cdk/pull/28138), creating aws_ec2.KeyPair and passing it to aws_ec2.Instance does nothing.

### Expected Behavior

Make sure the keypair is associated with the instance when passed through keyPair property.

### Current Behavior

keypair does not get associated with the instance.

### Reproduction Steps

```ts
const keyPair = new ec2.KeyPair(this, 'KeyPair', {});
 this.instance = new ec2.Instance(this, 'EC2Instance', {
      vpc: props.vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
      securityGroup,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MICRO),
      machineImage: ec2.MachineImage.latestAmazonLinux2023(),
      keyPair,
      userDataCausesReplacement: true,
      ssmSessionPermissions: true,
    });

```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.116.1 (build 222de71)

### Framework Version

_No response_

### Node.js Version

20.10.0

### OS

Linux

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### LINKED ISSUE #28569: aws_ec2: KeyPair static methods do not retrieve existing key pairs
### Describe the bug

using the static methods
```typescript
KeyPair.fromKeyPairName()
KeyPair.fromKeyPairAttributes()
```
and the the keyPair property on the InstanceProps interface does not set the public key on the instance at instance deployment

```typescript
{
     keyPair:IKeyPair
}

### Expected Behavior

using the methods:

```typescript
    const keyPair = KeyPair.fromKeyPairAttributes(this, 'key-pair', {
      keyPairName: 'myExistingKeyName',
      type: KeyPairType.RSA
    });
```

```typescript
   const instance = new ec2.Instance(this, 'instance', {
      vpc: this.props.vpc,
      securityGroup: this.props.applicationSecurityGroup,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PUBLIC
      },
      instanceName: 'host',
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MEDIUM),
      machineImage: ec2.MachineImage.latestAmazonLinux2023(),
      keyPair: keyPair,
      userDataCausesReplacement: true
    });
```

Should result in the public key being set on in the ~/.ssh/authorized_keys file of the instance.  

### Current Behavior

No keys are set when that property / method is used.  

the "keyName" property marked as obsolete **DOES** work however.  

### Reproduction Steps

using the methods:

```typescript
    const keyPair = KeyPair.fromKeyPairAttributes(this, 'key-pair', {
      keyPairName: 'myExistingKeyName',
      type: KeyPairType.RSA
    });
```

```typescript
   const instance = new ec2.Instance(this, 'instance', {
      vpc: this.props.vpc,
      securityGroup: this.props.applicationSecurityGroup,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PUBLIC
      },
      instanceName: 'host',
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MEDIUM),
      machineImage: ec2.MachineImage.latestAmazonLinux2023(),
      keyPair: keyPair,
      userDataCausesReplacement: true
    });
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.117.0 (build 59d9b23)

### Framework Version

_No response_

### Node.js Version

v18.16.0

### OS

macOS sonoma 14.1.2 (23B92)

### Language

TypeScript

### Language Version

5.3.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ayush-shah-1501**
Fixes by Specifying key pair reference in cfnInstance.

This will change behavior if both `keyName` and `keyPair` is set on an existing resource, since we will use `keyPair.keyPairName` instead of `keyName` now. However, there is no correct use case for specifying both `keyPair` and `keyName`, and given `keyName` is deprecated, this PR is introducing the correct behavior.

Closes #28478.
Closes #28569 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ayush-shah-1501** [comment]
This PR is quick fix of [here](https://github.com/aws/aws-cdk/pull/28138,) which didn't need changes to readme and tests.

**Comment by sumupitchayan** [comment]
@ayush-shah-1501 this PR title should be `fix` not `chore` and should also include tests to validate this functionality fixes the bug

**Comment by kylelaker** [comment]
@ayush-shah-1501 Thanks for catching this! So sorry for missing this in the original PR. I will momentarily open a PR on your repo that will add a possible test & updates the integration tests.

Additionally, so long as a user follows the docs for how to use an existing key pair, this should not be a breaking change.

**Comment by ayush-shah-1501** [comment]
Exemption Request: This PR is quick fix of https://github.com/aws/aws-cdk/pull/28138 PR

**Comment by kylelaker** [comment]
For what it's worth, I think it's safe to not call this a breaking change. The correct behavior is documented and it does work correctly for other resource types; this condition was just missed in the implementation for `Instance`. Honestly, the current behavior (with `keyName` deprecated and `keyPair` not working) is far more broken than the results of this change.

**Review by kylelaker — APPROVED** [review]

**Review by kaizencc — APPROVED** [review]
Thanks @ayush-shah-1501

**Comment by cponfick** [comment]
I am not sure if this change is at fault here, but using the ´keyPair´ parameter does not set the Ref in CFN. It does nothing.

Example:
```python
instance = aws_ec2.Instance(
            self,
            f"id",
            vpc=base.vpc,
            instance_type=aws_ec2.InstanceType.of(
                aws_ec2.InstanceClass.T3, aws_ec2.InstanceSize.MICRO
            ),
            machine_image=aws_ec2.MachineImage.generic_linux(
                {'eu-central-1': 'ami-0faab6bdbac9486fb'}
            ),
            key_pair=key_pair,
            # key_name=key_pair.key_pair_name,
            associate_public_ip_address=True,
            vpc_subnets=aws_ec2.SubnetSelection(
                subnet_type=aws_ec2.SubnetType.PUBLIC
            ),
        )
```

`keyName` works as expected.

**Comment by kaizencc** [comment]
@cponfick this hasn't been released yet. will be out in 2.119.0. let us know in a new issue if the problem persists!

**Comment by alastairmccormack** [comment]
Has this been regressed? 

I just used `aws_cdk.aws_ec2.KeyPair.from_key_pair_name()` with version 2.128.0 (build d995261), and it did nothing leaving the instance with no key. I've used `Instance.key_name` instead and all is good.

**Pull request merged**
