### PR TITLE
chore(core): bundle assets in .cdk.staging

### LINKED ISSUE #8589: Change the bundler's /asset-output local volume mount location
I'd like to be able to specify where AWS CDK locally mounts the bundler's `/asset-output` volume or for the default to stay inside the cdk asset directory. It currently uses the system temp directory, but this causes a few issues for me.

### Use Case
First, my BitBucket Pipelines breaks because BitBucket's security disallows CDK (and me) from mounting a Docker volume outside of the clone directory. (Error listed below.) So, to fix my pipeline, I need to get CDK to put the asset-output volume somewhere inside the directory where my repo has been cloned.

Second, I've noticed that this use of the system temp dir doesn't work with a snap package-based docker. The /tmp that you mount from a docker running in a snap package doesn't seem to be in the same file namespace as what CDK can see after running the docker command. In this situation, when you try to synth, the bundler claims that nothing is written to /asset-output which is false. (CDK isn't looking at the right directory because it doesn't know where snap's /tmp is.)

I can appreciate that this is probably a weird niche situation. It can be remedied by uninstalling snap-based docker and installing docker ce from docker hub. But, having the ability to specify a different directory for `/asset-output` would address this as well.

Third, it seems that using the os temp directory has changed what drives need to be shared with Docker for Windows. I have all of my project work on my "E:" drive, and so I only planned to have my E drive shared with Docker. When I tried to use the custom bundling, I was getting a "Filesharing has been cancelled" error from Docker. I was able to get the problem to go away by adding my "C:" drive to Docker desktop. This was not a huge problem for me, just more of an unexpected stumbling point.

### Proposed Solution
I'd be happy if I could specify a prefix for where to mount /asset-output locally. I'd be happy enough using a special context variable or command line flag when invoking the CDK CLI. Otherwise, putting the asset-output somewhere into the cdk asset directory would work for me.

### Other

**Bitbucket Error:**
```
stderr: docker: Error response from daemon: authorization denied by plugin pipelines: -v only supports $BITBUCKET_CLONE_DIR and its subdirectories.
```

**Snap-based Docker Error**
```
Bundling did not produce any output. Check that your container writes content to /asset-output.
```

**Docker Desktop for Windows error:**
```
Failed to run bundling Docker image for asset Stats-Dev/compute/Libs/Code/Stage: Error: [Status 125] stdout:


stderr: docker: Error response from daemon: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled","StackTrace":"   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__6.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__4.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:line 47\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.HttpApi\\Controllers\\FilesharingController.cs:line 21\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}.
See 'docker run --help'.
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by jogold**
Using `/tmp` can be problematic with some Docker setups or in CI.

The directory `.cdk.staging` is already gitignored in the init
templates.

Closes #8589

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
> I am wondering if it will make more sense to mount it by default under the project directory in `./.tmp` or `./.cdk.tmp` instead of the system temp directory.

Better, and renaming here should always work:
https://github.com/aws/aws-cdk/blob/b0286e96076b298868686a1582e0bebdc3a82ddd/packages/%40aws-cdk/core/lib/asset-staging.ts#L122-L128

**Comment by jogold** [comment]
There was previously a `.cdk.staging` apparently:
https://github.com/aws/aws-cdk/blob/b0286e96076b298868686a1582e0bebdc3a82ddd/packages/aws-cdk/lib/init-templates/app/typescript/.template.gitignore#L7

https://github.com/aws/aws-cdk/blob/b0286e96076b298868686a1582e0bebdc3a82ddd/.gitignore#L32

Should I use this instead?

**Comment by eladb** [comment]
> There was previously a `.cdk.staging` apparently:
> https://github.com/aws/aws-cdk/blob/b0286e96076b298868686a1582e0bebdc3a82ddd/packages/aws-cdk/lib/init-templates/app/typescript/.template.gitignore#L7
> 
> https://github.com/aws/aws-cdk/blob/b0286e96076b298868686a1582e0bebdc3a82ddd/.gitignore#L32
> 
> Should I use this instead?

Sure, why not

**Comment by jogold** [comment]
Funny...
`Error: EXDEV: cross-device link not permitted, rename '.cdk.staging/asset-bundle-nKh6F4' -> '/tmp/cdk.outSqgZ2f/asset.2f37f937c51e2c191af66acf9b09f548926008ec68c575bd2ee54b6e997c0e00'`

We need a `FileSystem.moveDirectory()`

**Comment by jogold** [comment]
> We need a `FileSystem.moveDirectory()` that tries to rename and otherwise copies and unlinks.

Wouldn't it be better to bundle `fs-extra` in `core`? I know you don't like adding dependencies but it's [small](https://bundlephobia.com/result?p=fs-extra@9.0.1) well maintained and covers all the edge cases (`EACCESS`, `EPERM`, windows, etc.)

**Comment by eladb** [comment]
> Funny...
> 
> `Error: EXDEV: cross-device link not permitted, rename '.cdk.staging/asset-bundle-nKh6F4' -> '/tmp/cdk.outSqgZ2f/asset.2f37f937c51e2c191af66acf9b09f548926008ec68c575bd2ee54b6e997c0e00'`
> 
> 
> 
> We need a `FileSystem.moveDirectory()` that tries to rename and otherwise copies **and** unlinks (since we are not in `/tmp` anymore).

Haha. This is for when cdk.out is under /tmp ha?

I am okay bundling fs-extra in core.

**Comment by eladb** [comment]
For the record here’s ‘fs-extra’s dep closure:

7C46DE7F-9141-40AA-86F9-D826980048C0

**Pull request merged**
