### PR TITLE
fix(rds): serverlessV2MaxCapacity can be set to 0.5, which is invalid

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

N/A

### Reason for this change
In [CFn docs](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-serverlessv2scalingconfiguration.html#cfn-rds-dbcluster-serverlessv2scalingconfiguration-maxcapacity),  MaximumCapacity value must be higher than 0.5 ACUs.

```
The maximum capacity must be higher than 0.5 ACUs.
```

This means MaximumCapacity cannot be set to 0.5 ACUs. 
However, in the CDK, `serverlessV2MaxCapacity` can be set to 0.5, which is invalid.

When I attempted to deploy with `serverlessV2MaxCapacity` set to 0.5, I encountered the following error:
> CREATE_FAILED        | AWS::RDS::DBCluster                         | Integ-Cluster (IntegCluster4261F36F) Resource handler returned message: "Serverless v2 maximum capacity 0.5 isn't valid. The maximum capacity must be at least 1.0.

In the Management Console, Maximum Capacity cannot be set to 0.5.

image

### Description of changes
Fix a validation.

### Description of how you validated changes
Fix unit tests.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mazyu36** [comment]
Exemption Request: Integration tests cannot be added because only the incorrect conditional statement was fixed

**Comment by tehnrd** [comment]
Issue I created before realizing the PR already existed.

https://github.com/aws/aws-cdk/issues/32234

**Review by badmintoncryer — APPROVED** [review]

**Review by gracelu0 — APPROVED** [review]
Thanks!

**Comment by mazyu36** [comment]
@Mergifyio update

**Comment by mazyu36** [comment]
@Mergifyio update

**Pull request merged**
