### PR TITLE
chore: Updating the prlinter

### PR DESCRIPTION
**Pull request by Naumel**
Adding the title check for all submitted PRs, not only the breaking change ones.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Naumel** [comment]
@Mergifyio update

**Review by rix0rrr — CHANGES_REQUESTED** [review]
It's probably safer to not change the existing behavior of the breaking change checker. This specific change, requiring a module always breaks cases today where we could do `chore: blabla` (that is now illegal because it's not formatted like `chore(something): blabla`). Same for `fix` or `feat`.

Why not add a new check that PR titles conform to "conventional commits", just like the check that we used to have but are now missing?

The format should be:

```
<type> [ "(" <arbitrary text> ")" ] ":" <arbitrary text>
<type> := "feat" | "fix" | "chore" | "refactor" | "docs"  (I think that's most of what we use)
```

**Comment by Naumel** [comment]
From https://www.conventionalcommits.org/en/v1.0.0/#summary

>types other than `fix:` and `feat:` are allowed, for example [@commitlint/config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) (based on the [the Angular convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines)) recommends `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`

**Comment by TheRealAmazonKendra** [comment]
This is going to conflict with the changes in https://github.com/aws/aws-cdk/pull/22029.

**Comment by Naumel** [comment]
@Mergifyio update

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
