### PR TITLE
fix(eks): latest `AlbController` version isn't compatible with the chart version 

### PR DESCRIPTION
**Pull request by adriantaut**
Bump the chart version.

Fixes https://github.com/aws/aws-cdk/issues/20764

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by iliapolo** [comment]
@adriantaut The PR body says that you allow the version to be passed - but I don't see that functionality in the code...did you mean something else? I'd actually be in favor of exposing this version.

**Review by iliapolo — APPROVED** [review]

**Comment by adriantaut** [comment]
> @adriantaut Scratch my previous comment. I see the change was due to [#20764 (comment)](https://github.com/aws/aws-cdk/issues/20764#issuecomment-1173497364) 👍

cheers, thank you @iliapolo for your approval!

**Review by iliapolo — APPROVED** [review]

**Comment by adriantaut** [comment]
@iliapolo aren't the PRs backported to CDKv1 anymore?

**Comment by iliapolo** [comment]
@adriantaut No. See https://github.com/aws/aws-cdk/issues/19836

**Pull request merged**
