### PR TITLE
chore: include emitDecoratorMetadata flag

### LINKED ISSUE #24089: (aws_lambda_nodejs): text after `@` (ampersand) is trimmed in documentation
### Describe the issue

 If the code documentation contains '@' ampersand, the rest of the text is trimmed in HTML documentation

For example, the JS docs for BundlingOptions.externalModules in `aws-lambda-nodejs/lib/types.ts` is:
```js
['aws-sdk'] if the runtime is < Node.js 18.x, ['@aws-sdk/*'] otherwise.
```

https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L178-L181

In the documentation, the content is trimmed after `@`
```console
Type: string[] (optional, default: ['aws-sdk'] if the runtime is < Node.js 18.x, [')
```

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#externalmodules

<details>
<summary>Screenshot</summary>

aws_cdk_ampersand

</details>

### Links

* Code: https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L178-L181
* Documentation: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#externalmodules

### PR DESCRIPTION
**Pull request by aasthavar**
Closes #24089

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by aasthavar** [comment]
Clarification Request

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Please make sure that your PR body describes the problem the PR is solving, and the design approach and alternatives considered. Explain why the PR solves the problem. A link to an issue is helpful, but does not replace an explanation of your thought process (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request))

**Comment by TheRealAmazonKendra** [comment]
Also, what kind of clarification are you needing?

**Comment by TheRealAmazonKendra** [comment]
Removing the label while we are awaiting a response. Please re-add when you respond.

Thanks!

**Pull request closed without merging**
