### PR TITLE
fix(app): add source map support to TypeScript apps

### LINKED ISSUE #1579: Document how to enable source map support
Currently, when an uncaught exception is encountered when running `cdk`, the backtrace is of the compiled Javascript code, not the TypeScript source.  For example:

```
 cdk synth
/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.js:305
            throw new Error(`There is already a Construct with name '${childName}' in ${this.toString()}`);
            ^

Error: There is already a Construct with name 'Snapshot Complete' in [object Object]
    at ConstructNode.addChild (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.js:305:19)
    at new ConstructNode (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.js:37:24)
    at new Construct (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.js:417:21)
    at new State (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/aws-stepfunctions/lib/states/state.js:10:9)
    at new Task (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/aws-stepfunctions/lib/states/task.js:14:9)
    at new Snapshotter (/Users/otterley/src/common/snapshotter/lib/index.js:50:30)
    at new DevEnvStack (/Users/otterley/src/aem/dev-env/lib/dev-env-stack.js:17:9)
    at Object.<anonymous> (/Users/otterley/src/aem/dev-env/bin/dev-env.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
```

This is easily remediable by running `require('source-map-support').install();` in the app entry point.

If we do this, we get references to the original source:

```
$ cdk synth

/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.ts:364
      throw new Error(`There is already a Construct with name '${childName}' in ${this.toString()}`);
            ^
Error: There is already a Construct with name 'Snapshot Complete' in [object Object]
    at ConstructNode.addChild (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.ts:364:13)
    at new ConstructNode (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.ts:62:18)
    at new Construct (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.ts:496:17)
    at new State (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/aws-stepfunctions/lib/states/state.ts:152:9)
    at new Task (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/aws-stepfunctions/lib/states/task.ts:101:9)
    at new Snapshotter (/Users/otterley/src/common/snapshotter/lib/index.ts:72:22)
    at new DevEnvStack (/Users/otterley/src/aem/dev-env/lib/dev-env-stack.ts:19:5)
    at Object.<anonymous> (/Users/otterley/src/aem/dev-env/bin/dev-env.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
```

### PR DESCRIPTION
**Pull request by mifisignal**
Add source map support to the TypeScript app entry point template.
This won't retroactively fix existing CDK apps, but it will ensure
that apps generated in the future via `cdk init --app` will have
it enabled.

Fixes #1579 

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added
  - __CLI change?:__ manually run [integration tests](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/integ-tests/test.sh) and paste output as a PR comment
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by rix0rrr** [comment]
`"source-map-support"` also needs to be added as a dependency to `package.json` if we're going this route.

But I seem to recall we disabled this on purpose, I just don't remember why. @eladb, do you?

You can also get source map support by default on your machine by setting the following environment variable:

```
export NODE_OPTIONS="-r source-map-support"
cdk deploy
```

No need to change any files.

**Comment by eladb** [comment]
Source map support makes sense only if you actually have the sources on your machine, and most of our users don’t have them available. Moreover, there isn’t uncommon in the JavaScript world to source locations in stack trace output to jump into the JavaScript code, add a “printf debug” in order to diagnose a problem.  

We can totally recommend Rico’s approach in our contribution guide for people who are debugging with sources

**Comment by rix0rrr** [comment]
Although all `source-map-support` does is hook up to the NodeJS API and translate any stack traces using the source map in the source files.

I guess we might enable it by default from the toolkit or sth?

**Comment by otterley** [comment]
I'm a bit puzzled here.  The context in question is a TypeScript app.  When will one _not_ have the sources for this and the dependencies?

Having the correct lines in the stack trace, especially when the trace results from an error in user code (stacks, libs, etc.), makes for a pleasant UX.  If it's possible to make this easy, let's make it work out of the box by default instead of asking the customer to do any gymnastics.

**Comment by otterley** [comment]
@rix0rrr Added `source-map-support` to the `packages.json` template.

**Comment by rix0rrr** [comment]
I actually also feel we can merge this. It's what most people are going to want, and those that don't will be savvy enough to remove it.

**Comment by eladb** [comment]
okay by me

**Pull request merged**
