### PR TITLE
feat(cfnspec): cloudformation spec v50.0.0

### PR DESCRIPTION
**Pull request by robertd**
Generated by running `./scripts/bump-cfnspec.sh`. Needed some additions required for #17840.

Closes #17858 (duplicate)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
@rix0rrr It looks like a newly announced service (AWS::Evidently::Project) is not liking `cfnspec`'s tests.

**Comment by skinny85** [comment]
@robertd yeah, we need a patch removing it. Would that be something you could do? Look for the other patches in that directory for inspiration, like [this](https://github.com/aws/aws-cdk/blob/cd8a377d90871d1f6856a2f640231f1b2ba35469/packages/%40aws-cdk/cfnspec/spec-source/600_Ecs_TaskDefinition_EFSVolumeConfiguration_AuthorizationConfig_patch.json#L1-L15).

**Comment by robertd** [comment]
> @robertd yeah, we need a patch removing it. Would that be something you could do? Look for the other patches in that directory for inspiration, like [this](https://github.com/aws/aws-cdk/blob/cd8a377d90871d1f6856a2f640231f1b2ba35469/packages/%40aws-cdk/cfnspec/spec-source/600_Ecs_TaskDefinition_EFSVolumeConfiguration_AuthorizationConfig_patch.json#L1-L15).

Thanks @skinny85. I was just troubleshooting this on my end.

These two are the offenders:
```
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-evidently-project.html#cfn-evidently-project-datadelivery
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-evidently-project-datadeliveryobject.html#cfn-evidently-project-datadeliveryobject-s3
```
I'm looking at the patch you provided.... How do I pick prefix number for it?

**Comment by robertd** [comment]
@skinny85  Please review and let me know what you think.

**Comment by robertd** [comment]
I'm not 100% sure why build is failing on `amplify` now as I'm able to build that module on my box just fine.

```bash
➜  aws-amplify git:(cfnspec) ../../../scripts/buildup --resume
************************************************************
 buildup usage:
 - execute 'buildup --resume' to resume after failure
 - execute 'buildup' to restart the build from the start

 for advanced usage, see /Users/rdjurasaj/code/robertd/aws-cdk/scripts/foreach.sh
************************************************************
starting new session ('@aws-cdk/aws-amplify' and its dependencies)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/tools/@aws-cdk/eslint-plugin: yarn build  (43 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/tools/@aws-cdk/pkglint: yarn build  (42 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/tools/@aws-cdk/yarn-cling: yarn build  (41 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/awslint: yarn build  (40 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/tools/@aws-cdk/cdk-build-tools: yarn build  (39 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/cloud-assembly-schema: yarn build  (38 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/cfnspec: yarn build  (37 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/region-info: yarn build  (36 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/tools/@aws-cdk/cfn2ts: yarn build  (35 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/cx-api: yarn build  (34 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/cloudformation-diff: yarn build  (33 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/core: yarn build  (32 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/cdk-assets: yarn build  (31 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/assertions: yarn build  (30 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/assert-internal: yarn build  (29 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/aws-cdk: yarn build  (28 remaining)
---------------------------------------------------------------------------------/Users/rdjurasaj/code/robertd/aws-cdk/tools/@aws-cdk/cdk-integ-tools: yarn build  (27 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-sam: yarn build  (26 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-signer: yarn build  (25 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-iam: yarn build  (24 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/assets: yarn build  (23 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-codestarnotifications: yarn build  (22 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-kms: yarn build  (21 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-cloudwatch: yarn build  (20 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-events: yarn build  (19 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-codeguruprofiler: yarn build  (18 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-autoscaling-common: yarn build  (17 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-ecr: yarn build  (16 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-s3: yarn build  (15 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-ssm: yarn build  (14 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-applicationautoscaling: yarn build  (13 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-sqs: yarn build  (12 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-ecr-assets: yarn build  (11 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-s3-assets: yarn build  (10 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-sns: yarn build  (9 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-logs: yarn build  (8 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-codecommit: yarn build  (7 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-ec2: yarn build  (6 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-efs: yarn build  (5 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-lambda: yarn build  (4 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-secretsmanager: yarn build  (3 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-codebuild: yarn build  (2 remaining)
---------------------------------------------------------------------------------
/Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-amplify: yarn build  (1 remaining)
done (queue is empty). reseting queue:
state cleared. you are free to start a new command.
************************************************************
buildup done
************************************************************
➜  aws-amplify git:(cfnspec) lr build && lr test
info cli using local version of lerna
lerna notice cli v4.0.0
lerna notice filter including "@aws-cdk/aws-amplify"
lerna info filter [ '@aws-cdk/aws-amplify' ]
lerna info Executing command in 1 package: "yarn run build"
@aws-cdk/aws-amplify: yarn run v1.22.17
@aws-cdk/aws-amplify: $ cdk-build
@aws-cdk/aws-amplify: WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
@aws-cdk/aws-amplify: (node:8183) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/rdjurasaj/code/robertd/aws-cdk/packages/@aws-cdk/aws-amplify/node_modules/yaml/package.json.
@aws-cdk/aws-amplify: Update this package.json to use a subpath pattern like "./*".
@aws-cdk/aws-amplify: (Use `node --trace-deprecation ...` to show where the warning was created)
@aws-cdk/aws-amplify: warning JSII6: A "peerDependency" on "@aws-cdk/aws-codebuild" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-codebuild" at "0.0.0" (found "undefined")"
@aws-cdk/aws-amplify: warning JSII6: A "peerDependency" on "@aws-cdk/aws-codecommit" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-codecommit" at "0.0.0" (found "undefined")"
@aws-cdk/aws-amplify: warning JSII6: A "peerDependency" on "@aws-cdk/aws-iam" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-iam" at "0.0.0" (found "undefined")"
@aws-cdk/aws-amplify: warning JSII6: A "peerDependency" on "@aws-cdk/aws-kms" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-kms" at "0.0.0" (found "undefined")"
@aws-cdk/aws-amplify: warning JSII6: A "peerDependency" on "@aws-cdk/aws-secretsmanager" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-secretsmanager" at "0.0.0" (found "undefined")"
@aws-cdk/aws-amplify: warning JSII6: A "peerDependency" on "@aws-cdk/core" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/core" at "0.0.0" (found "undefined")"
@aws-cdk/aws-amplify: warning JSII6: A "peerDependency" on "constructs" at "^3.3.69" means you should take a "devDependency" on "constructs" at "3.3.69" (found "undefined")"
@aws-cdk/aws-amplify: Build times for @aws-cdk/aws-amplify: Total time (14.0s) | /Users/rdjurasaj/code/robertd/aws-cdk/node_modules/jsii/bin/jsii (7.7s) | cfn2ts (0.3s)
@aws-cdk/aws-amplify: Done in 14.23s.
lerna success run Ran npm script 'build' in 1 package in 14.4s:
lerna success - @aws-cdk/aws-amplify
info cli using local version of lerna
lerna notice cli v4.0.0
lerna notice filter including "@aws-cdk/aws-amplify"
lerna info filter [ '@aws-cdk/aws-amplify' ]
lerna info Executing command in 1 package: "yarn run test"
@aws-cdk/aws-amplify: yarn run v1.22.17
@aws-cdk/aws-amplify: $ cdk-test
@aws-cdk/aws-amplify: PASS test/branch.test.js (22.154 s)
@aws-cdk/aws-amplify: PASS test/domain.test.js (22.282 s)
@aws-cdk/aws-amplify: PASS test/app.test.js (22.689 s)
@aws-cdk/aws-amplify: =============================== Coverage summary ===============================
@aws-cdk/aws-amplify: Statements   : 96.61% ( 114/118 )
@aws-cdk/aws-amplify: Branches     : 85.71% ( 78/91 )
@aws-cdk/aws-amplify: Functions    : 90% ( 36/40 )
@aws-cdk/aws-amplify: Lines        : 96.52% ( 111/115 )
@aws-cdk/aws-amplify: ================================================================================
@aws-cdk/aws-amplify: Test Suites: 3 passed, 3 total
@aws-cdk/aws-amplify: Tests:       21 passed, 21 total
@aws-cdk/aws-amplify: Snapshots:   0 total
@aws-cdk/aws-amplify: Time:        23.446 s
@aws-cdk/aws-amplify: Ran all test suites.
@aws-cdk/aws-amplify: Verifying integ.app-codecommit.js against integ.app-codecommit.expected.json ... OK.
@aws-cdk/aws-amplify: Verifying integ.app.js against integ.app.expected.json ... OK.
@aws-cdk/aws-amplify: Tests successful. Total time (27.3s) | /Users/rdjurasaj/code/robertd/aws-cdk/node_modules/jest/bin/jest.js (24.6s) | cdk-integ-assert (2.6s)
@aws-cdk/aws-amplify: Done in 27.53s.
lerna success run Ran npm script 'test' in 1 package in 27.7s:
lerna success - @aws-cdk/aws-amplify
➜  aws-amplify git:(cfnspec)
```

**Comment by robertd** [comment]
Scratch my comment above... it's `amplofybuilder` that's throwing an error. Investigating....

**Comment by robertd** [comment]
Interestingly... wrong import statement was generated by `cfnspecs`.

Original:
```ts
// AWS::AmplifyUIBuilder CloudFormation Resources:
export * from './aws-amplifyuibuilder.generated';
```

Updated:
```ts
// AWS::AmplifyUIBuilder CloudFormation Resources:
export * from './amplifyuibuilder.generated';
```

**Comment by skinny85** [comment]
> Interestingly... wrong import statement was generated by `cfnspecs`.
> 
> Original:
> 
> ```ts
> // AWS::AmplifyUIBuilder CloudFormation Resources:
> export * from './aws-amplifyuibuilder.generated';
> ```
> 
> Updated:
> 
> ```ts
> // AWS::AmplifyUIBuilder CloudFormation Resources:
> export * from './amplifyuibuilder.generated';
> ```

I'm pretty sure this PR: https://github.com/aws/aws-cdk/pull/16692 broke that. Previously, the code was:

```ts
    const lowcaseModuleName = moduleBaseName.toLocaleLowerCase();
```

Now it's:

```ts
    const lowcaseModuleName = module.moduleName.toLocaleLowerCase();
```

Instead of lowercasing the base name of the module, we're now lowercasing the entire module name. And hence `aws-amplifyuibuilder.generated` instead of `amplifyuibuilder.generated`.

Thanks for noticing!

**Comment by skinny85** [comment]
@robertd would you mind changing [this line](https://github.com/aws/aws-cdk/blob/cd8a377d90871d1f6856a2f640231f1b2ba35469/packages/%40aws-cdk/cfnspec/build-tools/create-missing-libraries.ts#L29-L29) to be `const lowcaseModuleName = module.moduleBaseName.toLocaleLowerCase();` instead?

**Comment by robertd** [comment]
> @robertd would you mind changing [this line](https://github.com/aws/aws-cdk/blob/cd8a377d90871d1f6856a2f640231f1b2ba35469/packages/%40aws-cdk/cfnspec/build-tools/create-missing-libraries.ts#L29-L29) to be `const lowcaseModuleName = module.moduleBaseName.toLocaleLowerCase();` instead?

@skinny85  I've applied your suggestion and I've re-ran `./scripts/bump-cfnspec.sh`.

**Comment by robertd** [comment]
@rix0rrr Please review. Thanks!

**Review by skinny85 — DISMISSED** [review]
Thanks for the contribution @robertd!

**Review by skinny85 — APPROVED** [review]

**Pull request merged**
