### PR TITLE
fix(assets): invalid fingerprint when 'exclude' captures root directory name

### LINKED ISSUE #7718: Asset.fingerprint() does not handle excludes correctly
When creating an asset from a directory with certain exclude options, the fingerprint does not change even if the files change.

### Reproduction Steps

Add to packages/@aws-cdk/assets/test/fs/test.fs-fingerprint.ts
```ts
'considers negated exclude patterns for fingerprint'(test: Test) {
  // GIVEN
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fingerprint-tests'));
  const options = {path: dir, exclude: ['**', '!file.txt'], sourcePath: dir};

  // WHEN
  const f1 = libfs.fingerprint(dir, options);
  fs.writeFileSync(path.join(dir, 'file.txt'), 'data');
  const f2 = libfs.fingerprint(dir, options);

  // THEN
  test.notDeepEqual(f1, f2);
  test.done();
},
```

### Error Log

AssertionError: 'c917eba4ddad2e97bec2e1c5607246911cb811be0f87131042791f5525f69575' notDeepEqual 'c917eba4ddad2e97bec2e1c5607246911cb811be0f87131042791f5525f69575'

### Environment

  - **CLI Version      : master**
  - **Framework Version: master**
  - **OS               : linux**
  - **Language         : typescript**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by christophgysin**
### Commit Message
fix(assets): fix(assets): invalid fingerprint when 'exclude' captures root directory name (#7719)

When creating an asset from a directory with certain exclude options, the fingerprint does not change even if the files change.

If a fingerprint is calculated over a directory with exclude options `[ '**', '!file' ]`, the code never descends into the directory.

This commit skips the exclude check for the root directory, to correctly handle negated expressions in the exclude options.

fixes #7718
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eladb** [comment]
@christophgysin can I bug you to rebase this change on top of #7708 once it's merged (hopefully shortly)

**Comment by eladb** [comment]
@christophgysin ok, #7708 has been merged to master. Can you please rebase here?

**Comment by christophgysin** [comment]
@eladb I updated the commit message accordingly. Let me know if something is still unclear.

**Comment by eladb** [comment]
@christophgysin updated commit title accordingly to represent the bug and not the solution (think that this goes under "bug fixes" section in the changelog).

**Pull request merged**
