### PR TITLE
fix(ec2): filtering by AZ will not work in all cases

### PR DESCRIPTION
**Pull request by rix0rrr**
Relates to #10475 but doesn't solve it yet.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
Don't have time to continue working on this right now, posting it as a reminder.

**Comment by rix0rrr** [comment]
It's `Annotations.of(construct).addError()`

**Comment by flemjame-at-amazon** [comment]
@rix0rrr I think there are other areas of CDK where string comparison against tokens is a challenge. Would it make sense to have some helper libraries, maybe in `core`, that handle string comparison where tokens may be present, and can be configured to throw errors?

**Comment by rix0rrr** [comment]
We probably won't finish this.

**Pull request closed without merging**
