### PR TITLE
feat(ec2): add rds-data vpc endpoint

### LINKED ISSUE #15239: (ec2): Add rds-data VPC interface endpoints
Add `rds-data` VPC interface endpoints

### Use Case

VPC interface endpoints are supported for `rds-data` but don't exist in CDK:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/vpc-interface-endpoints.html

### Proposed Solution

Add support for `rds-data` VPC interface endpoints

### Other

Temporary workaround:
```
vpc.addInterfaceEndpoint("rds-data", {
      service: {
        name: `com.amazonaws.${process.env.CDK_DEFAULT_REGION}.rds-data`,
        port: 443,
      },
```

I "presume" the implementation would be:

https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-ec2/lib/vpc-endpoint.ts#L290

```
public static readonly RDS_DATA = new InterfaceVpcEndpointAwsService('rds-data');
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by neilferreira**
Fixes https://github.com/aws/aws-cdk/issues/15239 (ec2): Add rds-data VPC interface endpoints 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by owenashurst** [comment]
@neilferreira you need to rename the title of the PR to follow convention. e.g. `fix: add rds-data vpc endpoint`

**Comment by neilferreira** [comment]
> @neilferreira you need to rename the title of the PR to follow convention. e.g. `fix: add rds-data vpc endpoint`

Done thankyou

**Review by njlynch — CHANGES_REQUESTED** [review]
Thanks for the contribution!

You'll need to edit the `package.json` file to exclude this new API element from needing docs (as is apparently the convention for this class). See the error message from the build here:

> @aws-cdk/aws-ec2: error: [awslint:docs-public-apis:@aws-cdk/aws-ec2.InterfaceVpcEndpointAwsService.RDS_DATA] Public API element must have a docstring 
@aws-cdk/aws-ec2: Error: /codebuild/output/src279546990/src/github.com/aws/aws-cdk/tools/cdk-build-tools/bin/cdk-awslint exited with error code 1

Also, please ensure you've checked the option to allow maintainers to push to your branch; this will allow our automation to automatically merge and update the PR once approved.

**Comment by neilferreira** [comment]
@njlynch Fixed the `package.json` to make the docstring optional

The option has been ticked to allow your bot to make changes too.

Screen Shot 2021-06-29 at 10 30 55 am

**Comment by neilferreira** [comment]
Is that recent failure related to my change? There are so many errors in the pipeline I'm not sure which to focus on?
```
Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```


```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-cdk/assertions@1.109.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Review by njlynch — APPROVED** [review]

**Comment by njlynch** [comment]
> Is that recent failure related to my change?

No, this is an annoying side-effect of being behind `master` after a new version is released. We run a script that checks API backwards compatibility, and it compares the version in the repo (on your fork) with the latest version published. When your fork doesn't have the same latest version, you get these types of errors. A merge from master always fixes it, which I've done. This looks good to go now, thanks for the contribution!

**Pull request merged**
