### PR TITLE
fix(ecs-patterns): memory limit is not set at the container level

### PR DESCRIPTION
**Pull request by gnagy**
I ran into an issue when deploying a Java application on Fargate, where the container kept getting killed because of out-of-memory condition. Setting  memoryLimitMiB also on container fixed the problem, based on:

https://aws.amazon.com/blogs/containers/how-amazon-ecs-manages-cpu-and-memory-resources/

> [Update 12/11/2020] Some applications are container-aware and can configure themselves to take full advantage of the resources available inside the container. The latest versions of Java are a good example of this pattern. For this reason, some of these applications work best when CPU and memory resources are explicitly configured at the container level, in addition to the configuration at the task level. In other words, while containers without specific resource configurations can nominally access all task resources, https://github.com/aws/amazon-ecs-agent/issues/1735.

I initially asked about this in https://github.com/aws/aws-cdk/issues/13127

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — DISMISSED** [review]
Thank you for your contribution. A couple quick initial comments: 
- In general this looks like a very straight forward change but we will still need unit tests on it. 
- This change should probably be made on all the Fargate service types, not just here.
- Make sure the build succeeds. Currently it's failing on a formatting issue but I suspect when that's fixed it will fail on the integration tests due to this change.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thanks for the update! The build is still failing on formatting issues. Please run the linter locally to find the locations causing the failure. Additionally, this change will change the output of tests in both this package and almost certainly in other packages that use these constructs in their integration tests. It may be beneficial to run the build locally so you can find those. It's also fine to just keep pushing changes and update based off the build failure if the local build is too laborious to run. It takes quite a while.

**Comment by gnagy** [comment]
Hi, I think I got the code and tests working, and now the build is still failing with `Error: Some changes were destructive!`. This sounds scary and not sure what it means. Can you help me with what are the next steps?

**Review by TheRealAmazonKendra — DISMISSED** [review]
This the change I expected it to need when I mentioned above that it will probably cause the integration tests to fail. Because you're adding these fields, they now show up in the output of the integration tests. Just go ahead and add those values in the expected output and this change looks good to go, as far as I'm concerned.

Don't be too surprised if these same failures show up elsewhere that happens to use these constructs in their integration tests. They'll just need the same update.

**Review by TheRealAmazonKendra — APPROVED** [review]
🎉Looks good! Thank you for all your work on this!

**Review by TheRealAmazonKendra — APPROVED** [review]

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio refresh

**Pull request merged**
