### PR TITLE
fix(events-targets): #13568 Fix permissions for cross account event rules, fix minor typos

### PR DESCRIPTION
**Pull request by john-tipper**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by nija-at — DISMISSED** [review]
Hi @john-tipper -

Thanks for taking the time to submit this PR!

Before I dive into the code, could you look at the contribution guide and update your commit title and commit message to how is described there?

**Review by nija-at — CHANGES_REQUESTED** [review]
Please see comment above.

**Comment by john-tipper** [comment]
> Please see comment above.

Sorry, I'm not seeing what you're after - the commit title/message now follows the style in the guide, as far as I can see. Or are you referring to the PR title too (no conventions mentioned in the guide, btw)?

**Comment by nija-at** [comment]
> > Please see comment above.
> 
> Sorry, I'm not seeing what you're after - the commit title/message now follows the style in the guide, as far as I can see. Or are you referring to the PR title too (no conventions mentioned in the guide, btw)?

Apologies @john-tipper for the confusion.

I was referring to this section - https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#step-4-commit. The same rules for commit title and message should be applied to PR title and message.

Looks the guide needs to be updated to reflect that.

**Comment by rix0rrr** [comment]
Please put a description of the bug you are fixing, the situation in which the bug would exhibit, and the reason why your fix works and any alternatives you considered into the PR body.

**Comment by rix0rrr** [comment]
This PR hasn't seen action for a long while, and I'm pretty sure there is more wrong with the Event Targets cross-account/region model than can be fixed by these lines. Closing PR.

**Pull request closed without merging**
