### PR TITLE
revert: "feat(codepipeline): `GitPushFilter` with branches and file paths for trigger"

### PR DESCRIPTION
**Pull request by gracelu0**
Reverts aws/aws-cdk#29127

### CODE REVIEW

**Review by aaythapa — APPROVED** [review]

**Comment by go-to-k** [comment]
@gracelu0 Why did you revert? I would like you to state reasons. Is it relevant to the following comment?

https://github.com/aws/aws-cdk/pull/30465#issuecomment-2153270981

**Comment by gracelu0** [comment]
> @gracelu0 Why did you revert? I would like you to state reasons. Is it relevant to the following comment?
> 
> [#30465 (comment)](https://github.com/aws/aws-cdk/pull/30465#issuecomment-2153270981)

Hi @go-to-k , yes I believe so. @TheRealAmazonKendra is working on some CodePipeline changes and can provide more context here. Thank you for your effort and apologies as I know the community has been looking forward to this feature. I'll make sure to communicate more clearly next time beforehand.

**Comment by TheRealAmazonKendra** [comment]
This was reverted based off my request because there were a couple bugs in the logic and because the contract here doesn't meet our design guidelines. Wherever possible (and I recognize that it is not possible. 100% of the time), we should not have optional props that are mutually exclusive or that rely on each other. If you require several statements validating the contract you have defined, that indicates that the contract is not quite right.

This is not perfect, this here is a PR that I have in progress to deprecate the triggers as they exist now and to improve the abstraction https://github.com/aws/aws-cdk/pull/30516. While we have limitations of how much we can perfect things here because of the changes that are already released, we should be using enum like classes and adding static functions to abstract away complexity and improve upon the CloudFormation contract.

**Comment by go-to-k** [comment]
Thanks for your clarification. I got it.

**Pull request merged**
