### PR TITLE
fix(lambda-python): handler path is incorrectly generated when using PythonFunction

### PR DESCRIPTION
**Pull request by sarisia**
When using PythonFunction, current implementation generates `handler` value incorrectly.

## Code

```typescript
new PythonFunction(stack, 'handler', {
    entry: 'test/lambda-handler-sub-nested',
    index: 'inner/inner2/custom_index.py',
    handler: 'custom_handler',
    runtime: Runtime.PYTHON_3_8,
});
```

## Expected

```yaml
Handler: inner.inner2.custom_index.custom_handler
```

## Current Behaviour

```yaml
Handler: inner.inner2/custom_index.custom_handler
```

This PR fix the issue by modifying string replace pattern.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — COMMENTED** [review]
Does this change have an issue associated with it? If so, please add it to the description.

**Comment by sarisia** [comment]
> Does this change have an issue associated with it? If so, please add it to the description.

We don’t have an open issue.

**Review by TheRealAmazonKendra — APPROVED** [review]
Thank you for your contribution!

**Comment by sarisia** [comment]
@mergifyio refresh

**Pull request merged**
