### PR TITLE
chore(integ-tests): cleanup the old *.expected.json files in favor of the new integ-tests

### PR DESCRIPTION
**Pull request by robertd**
Remove the old `*.expected.json` files in favor of the newly rolled out integ-tests.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
@corymhall I've marked this as PR as WIP until I push the updates to `CONTRIBUTING.md`.

**Comment by robertd** [comment]
@corymhall Can you please advise on `cloudformation-include` package use of old `*.expected.json`format.

Specifically these files being used in `cloudformation-include/test/nested-stacks.test.ts`:
[packages/@aws-cdk/cloudformation-include/test/test-templates/nested/child-import-stack.expected.json](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cloudformation-include/test/test-templates/nested/child-import-stack.expected.json)
[packages/@aws-cdk/cloudformation-include/test/test-templates/nested/only-nested-stack.expected.json](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cloudformation-include/test/test-templates/nested/only-nested-stack.expected.json)

Should these be simply renamed to omit `*.expected.*`, as they've been pretty static in the past? Or should they be pointing to the corresponding dynamically created `.json` file in the newly created `nested-stacks.integ.snapshots` directory?

**Comment by corymhall** [comment]
> Specifically these files being used in cloudformation-include/test/nested-stacks.test.ts:
[packages/@aws-cdk/cloudformation-include/test/test-templates/nested/child-import-stack.expected.json](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cloudformation-include/test/test-templates/nested/child-import-stack.expected.json?rgh-link-date=2022-05-04T19%3A54%3A38Z)
[packages/@aws-cdk/cloudformation-include/test/test-templates/nested/only-nested-stack.expected.json](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cloudformation-include/test/test-templates/nested/only-nested-stack.expected.json?rgh-link-date=2022-05-04T19%3A54%3A38Z)

> Should these be simply renamed to omit *.expected.*, as they've been pretty static in the past? Or should they be pointing to the corresponding dynamically created .json files in the newly created nested-stacks.integ.snapshots directory?

It looks like those specific files are just used for unit tests so you can just leave those as is.

**Review by corymhall — APPROVED** [review]
@robertd thanks for doing this!

**Pull request merged**
