### PR TITLE
feat(ecs-patterns): Add ECS deployment circuit breaker support to higher-level constructs

### LINKED ISSUE #12360: aws-ecs-patterns: Add CircuitBreaker pattern for QueueProcessingFargateService
The DeploymentController was recently released, but I can't configure the CircuitBreaker as described in this blog:

https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.DeploymentCircuitBreaker.html

### Use Case

Automatic rollback of failing deployment.

### Proposed Solution

Add CircuitBreaker to the configuration options (optional)

### Other

I'm assuming all the details needed to add this are in the blog post. The CircuitBreaker type exists for the BaseService from which ECS and FargateService classes are derived. We should just need to expose the option to this higher level props type.

---

This is a :rocket: Feature Request

### LINKED ISSUE #12534: aws-ecs-patterns: Add CircuitBreaker pattern for ApplicationLoadBalancedFargateService
The [ApplicationLoadBalancedFargateService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html) ECS pattern currently does not support the [new CircuitBreaker functionality](https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/). Anyone who wants to use is is currently forced to use lower-level constructs ([FargateService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateService.html))

### Use Case

Automatic rollback of failing deployments.

### Proposed Solution

Add CircuitBreaker support to the higher-level constructs such as [ApplicationLoadBalancedFargateService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html).

### Other

Related to #12360

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by ridha**
Fixes #12534
Fixes #12360

This change adds the option to set the `circuitBreaker` on the higher-level constructs such as ApplicationLoadBalancedFargateService

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by shreyharia — APPROVED** [review]

**Review by SoManyHs — COMMENTED** [review]
This is super great, thank you so much for adding this! ❤️  One small thought -- since using circuitBreakers requires you to specify `DeploymentControllerType.ECS` as the `deploymentController`, what do you think about setting that on behalf of the customer in the controller if `props.circuitBreaker` is defined? Otherwise, it might be helpful to add a validation in the constructor as well.

**Comment by ridha** [comment]
Good point. Updated code to set deploymentController to ECS deployment type if `circuitBreaker` is defined

**Review by SoManyHs — COMMENTED** [review]
Awesome! One more thing (and apologies for not mentioning this earlier) -- do you think you could add an integ test for this change? Thanks!

**Review by daveharmon — APPROVED** [review]

**Comment by ridha** [comment]
Added some basic integ tests

**Review by daveharmon — APPROVED** [review]

**Review by daveharmon — APPROVED** [review]

**Review by SoManyHs — APPROVED** [review]
Awesome!! 🎉 Thank you so much for this contribution!! ❤️

**Pull request merged**
