### PR TITLE
feat(cli): report retained resources during cdk deploy

### PR DESCRIPTION
**Pull request by TrygviZL**
As most stateful resources are not destroyed during `cdk destroy` it can be difficult to figure out what orphaned resources are in the account. This PR adds a report in the form of a table listing all the resources that are retained when a specific stack is destroyed. An example of how it looks from running the integration test can be seen below.

deletionreport2

Notes:
* The method of fetching the table name in order to delete it in the integration test relies on a RegExp which is not very elegant. Any input would be welcome :)

Fixes: #21806 
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by TrygviZL** [comment]
Looking a more into utilizing the SDk, we could use `listStackResources` to which does include bothe the logical and physical ID of the respurce and match it with the logical ID from the Cfn template.
I do not know if it possible to provide a link to open the the console at the specific respurce, but great idea and I will check if possible.

**Comment by TrygviZL** [comment]
@niebloomj The PR and description is updated to now display the full-length Physical ID of the resource. I did check i it is possible to give a link to the resource in the console, but there is no officially supported library for that.
@peterwoodworth The PR is ready for a round of comments. The Linter does give error that Integration test + snapshot and change to readme is missing. These do seem unecessary for this PR, but let me know if I need to do anything :)

**Comment by niebloomj** [comment]
> @niebloomj The PR and description is updated to now display the full-length Physical ID of the resource. I did check i it is possible to give a link to the resource in the console, but there is no officially supported library for that. @peterwoodworth The PR is ready for a round of comments. The Linter does give error that Integration test + snapshot and change to readme is missing. These do seem unecessary for this PR, but let me know if I need to do anything :)

Thank you!

**Comment by TheRealAmazonKendra** [comment]
Note that the PR Linter speaks on behalf of us. As it says, if you believe that certain requirements should be exempted, we need a reason, not just that you don't think it's necessary.

**Comment by TrygviZL** [comment]
> Note that the PR Linter speaks on behalf of us. As it says, if you believe that certain requirements should be exempted, we need a reason, not just that you don't think it's necessary.

Thanks for the comment @TheRealAmazonKendra !
That is an oversight from my side, I of course should in clude my reasoning.
**Feature should contain README change**: this change does not alter the behavour of the cli, but adds additional information to the user during deletion of a stack. I believe that adding a describtion to the README file would not be useful.
**Feature should have integration test and snapshot**: This feature does include an integration test but no snapshot. As it only includes changes to the cli output without affecting any resources which would require a snapshot. 

Let me know if you agree :)

**Pull request closed without merging**
