### PR TITLE
fix(apigateway): allow endpointConfiguration to be defined

### PR DESCRIPTION
**Pull request by jcrugzz**
Only RestApi allowed endpointConfiguration to be defined rather than both SpecRestApi and RestApi which it is relevant for.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jcrugzz** [comment]
apologies, first time writing typescript. Trying to get everything oriented appropriately here since Im coming from having made the changes in javascript in my own app and working to translate them back to the original. Thanks for bearing with me and appreciate any suggestions

**Comment by jcrugzz** [comment]
@ericzbeard My changes seem to pass tests now, was just getting unrelated failure due to docker image pull rate limits. Appreciate whenever you can take a look :).

**Comment by jcrugzz** [comment]
@nija-at thoughts on this? I'd like to remove my local changes since I will need to have changes updated via CICD. Thank you!

**Comment by nija-at** [comment]
It looks like this is already being addressed in this PR https://github.com/aws/aws-cdk/pull/9068.

**Comment by nija-at** [comment]
Closing this PR in favour of the duplicate #9068 that is already in progress.

**Comment by jcrugzz** [comment]
@nija-at thanks, missed that :)

**Pull request closed without merging**
