### PR TITLE
chore(bedrock): support claude3-opus and base models for provisioned throughput

### PR DESCRIPTION
**Pull request by ymhiroki**
### Issue # (if applicable)

N/A

### Reason for this change

[Anthropic's Claude 3 Opus mode is now available](https://aws.amazon.com/jp/blogs/aws/anthropics-claude-3-opus-model-on-amazon-bedrock/), and new model IDs are published in [the guide](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html).

### Description of changes

I added model IDs for Claude 3 Opus for on-demand throughput and Claude 3 Sonnet/Haiku for provisioned throughput.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by godwingrs22 — APPROVED** [review]
Thanks @ymhiroki for your contribution.

**Comment by TheRealAmazonKendra** [comment]
Note: this is safe to merge once https://github.com/aws/aws-cdk/pull/29911 merges.

**Comment by ymhiroki** [comment]
@TheRealAmazonKendra
Thanks for the comment! #29911 seems to be already merged.
Would you like to remove the `pr/do-not-merge` label?

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Pull request merged**
