### PR TITLE
WIP: feat(cli): improve TypeScript app template

### PR DESCRIPTION
**Pull request by hoegertn**
Some proposed improvements to the TS app template.

Some changes I wanted to propose for a longer time plus changes proposed here: https://twitter.com/atechiethought/status/1292854923386859521

WIP: Let's discuss this here and add more if needed

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hoegertn** [comment]
I will create and fix the tests after we agreed on the changes.

**Comment by shivlaks** [comment]
@hoegertn - I'm marking this as a draft for now, what can I do to help move this conversation forward so we can get our init template refresh merged in the next release or two?

**Comment by hoegertn** [comment]
> @hoegertn - I'm marking this as a draft for now, what can I do to help move this conversation forward so we can get our init template refresh merged in the next release or two?

Hi, this sounds great. We need comments from the team on the changes I made and if everything is fine I can write tests for the changes and we can merge it.

**Comment by shivlaks** [comment]
there was some discussion about init templates in #5903 and maybe that's a good place to continue the conversation / close the loop on the hanging threads

**Comment by hoegertn** [comment]
> there was some discussion about init templates in #5903 and maybe that's a good place to continue the conversation / close the loop on the hanging threads

Sounds great. I think the topics discussed there, are already part of this PR.

**Comment by hoegertn** [comment]
@shivlaks @eladb Do you think we can discuss this and get it released?

**Comment by Jerry-AWS** [comment]
Adding myself and Noah since this will impact CDK Developer Guide and the CDK Workshop. We need to have documentation changes ready to launch at the same time as this is released because moving files around is going to break tutorials.

**Review by eladb — COMMENTED** [review]
What's the rational of putting everything under `app`? The package is an app project, not sure I see the value.

Also, can we take this opportunity and set up the project so that source and output are not side-by-side (e.g. source is under `src`)? (see `projen new typescript` as an example)

I am also not a huge fan of deep nesting and over-organizing this. This is the very base project and it should be pretty bare bones.

I am also looking into creating a cdk app project in projen and was wondering if we should just implement it there and call projen from here?

**Comment by hoegertn** [comment]
Hi thanks for your feedback.

> What's the rational of putting everything under `app`? The package is an app project, not sure I see the value.

Given that there are other folders for your Lambda functions / Docker projects / Frontend app / etc inside your repo I like the approach of having all CDK related code in one subfolder. It is also easier to target all CDK files using a glob pattern without hitting other files in your repo.

> Also, can we take this opportunity and set up the project so that source and output are not side-by-side (e.g. source is under `src`)? (see `projen new typescript` as an example)

What do you mean by source and output? I removed the tsc script as I do not see any reason to create js files in an app project as cdk.json is configured to use ts-node.

> I am also not a huge fan of deep nesting and over-organizing this. This is the very base project and it should be pretty bare bones.
> 
> I am also looking into creating a cdk app project in projen and was wondering if we should just implement it there and call projen from here?

While I really like the approach of projen and would love to see a CDK app template there I think we should not force this on all users of the CDK.

**Comment by hoegertn** [comment]
@eladb @shivlaks any idea how to proceed here?

**Comment by hoegertn** [comment]
I am closing this as we improved this and added it to projen.

**Pull request closed without merging**
