### PR TITLE
feat(eks): support AWS Load Balancer Controller v2.4.5

### PR DESCRIPTION
**Pull request by guessi**
### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [X] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by guessi** [comment]
Just found  **AWS Load Balancer Controller v2.4.5** released

- https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
The changes in the integ tests indicate to me that they may have been run with `--dry-run`. Please revert the snapshot changes and rerun the tests with the following command: `yarn integ --update-on-failed`.

**Comment by guessi** [comment]
I did run `--dry-run` before, but I'm not that familiar with integ ... studying. Will update later.

**Comment by guessi** [comment]
@TheRealAmazonKendra 

I tried to revert the change of integs, and run the commands as requested.
But it looks like CodeBuild CI is not happy with that. Should I get it back?

**Command output:**
image

**CodeBuild:**
image

**Pull request closed without merging**
