### PR TITLE
fix: explicitly set the 'ImagePullPrincipalType' of image

### LINKED ISSUE #10569: [codebuild] can’t change custom image to amazon curated image of project
Create a codebuild project like below, 

```ts
const prj = new codebuild.Project(this, `project`, {
      source: codebuild.Source.gitHub({
        owner: 'tuna',
        repo: 'opentuna',
        cloneDepth: 1,
        branchOrRef: 'master',
      }),
      environment: {
        // uncomment below line to update the build image from node:12-buster
        // buildImage: codebuild.LinuxBuildImage.AMAZON_LINUX_2_3,
        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('node:12-buster'),
        privileged: true,
        computeType: codebuild.ComputeType.SMALL,
      },
      buildSpec: codebuild.BuildSpec.fromObject({
        version: '0.2',
        phases: {
          install: {
            'runtime-versions': {
              nodejs: 12
            },
            commands: [
              'npm ci',
            ],
          },
          build: {
            commands: [
              'npm i aws-cdk'
            ],
          },
        },
      })
    });
```
Failed on updating the build image from docker image `node:12-buster` to Amazon Linux 2.3.

### Reproduction Steps

see above

### What actually happened?

```
6:19:27 PM | UPDATE_FAILED        | AWS::CodeBuild::Project | projectC7BA6BD1
Failed to call UpdateProject, reason: Invalid input: cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE (Service:
[██████████████████████████████████████▋···················] (2/3)
 
6:19:27 PM | UPDATE_FAILED        | AWS::CodeBuild::Project | project
Failed to call UpdateProject, reason: Invalid input: cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE (Service:
AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; Request ID: e17bc52c-5147-4276-a652-e8fbf5407319; Proxy: null)
6:19:28 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack | CodebuildChangeImageTypeBugStack
The following resource(s) failed to update: [projectC7BA6BD1].
```

### Environment

  - **CLI Version      :** 1.64.1
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

There is a same report https://github.com/aws/aws-codebuild-docker-images/issues/163 already.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by zxkane**
closes #10569 as workaround for the violation of CloudFormation of CodeBuild

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by skinny85 — APPROVED** [review]
Thanks @zxkane !

**Comment by msimperi** [comment]
This also actually sets `ImagePullCredentialsType` which was visible in snapshot tests with our change. Just FYI if someone else sees that change.

**Comment by skinny85** [comment]
Yes, we're aware @msimperi, as this required snapshot updates from our side as well. But the problem was serious enough that we determined it was worth it in this case. Apologies for the inconvenience.

**Comment by msimperi** [comment]
Yeah, the change was nice. I was just adding here a note that I saw only this `ImagePullCredentialsType` change which was not mentioned in discussions (only in changeset). Thanks for rocking and keep it going!

**Pull request merged**
