### PR TITLE
fix(sns-subscriptions):  lambda function cannot subscribe to topics with same id (under feature flag)

### LINKED ISSUE #7832: SNS Lambda Subscription Conflict
When subscribing multiple SNS Topics to a single Lambda Function, if two of those Topics have the same `id` (scope-local - this could happen if those Topics are in different scopes) then the second subscription will fail to be created with:
```
A subscription with id "SomeId" already exists under the scope Stack/Resource
```

### Reproduction Steps
See [robwettach/sns-lambda-subscription-conflict](https://github.com/robwettach/sns-lambda-subscription-conflict)

### Error Log
```
A subscription with id "SomeId" already exists under the scope Stack/Resource
```

### Environment

  - **CLI Version      :** 1.37.0 (build e4709de)
  - **Framework Version:** 1.37.0
  - **OS               :** macOS Mojave 10.14.6
  - **Language         :** TypeScript (all)

### Other
I believe changing [this line](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-sns-subscriptions/lib/lambda.ts#L37) from 
```
subscriberId: topic.node.id,
```
to
```
subscriberId: topic.node.uniqueId,
```
will solve this issue.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by i05nagai**
When subscribing multiple SNS Topics to a single Lambda Function, if two of those Topics have the same id (scope-local - this could happen if those Topics are in different scopes) then the second subscription will fail to be created. This change provides a way to ensure the uniqueness of topic subscriptions under feature flags. Note that enabling the feature flag requires recreation of resources due to logical id changes.

Closes #7832. Re-opening a PR (#19028) with a test because the PR has been closed.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by i05nagai** [comment]
I'm not sure about CDK's policy about Logical ID stability. This introduces a recreation of `SNS::Subscription` for Lambda due to the logical ID change if it has been deployed. If changing logical IDs is no problem,  I'll try to update the integration tests.
An idea to keep logical id stable is to use `Names.nodeUniqueId` only when there is a conflict of ids from another scope for now. Then switching the logic completely with a major update. I'd appreciate it if you could give me some insight into this.

**Comment by rix0rrr** [comment]
It depends on what the effect of the LogicalID replacement is (and hence, the recreation of the resource).

Sometimes, the resource can be freely recreated and it doesn't matter.

In this case, I'm pretty sure SNS re-subscription has undesirable side effects. For example, if the resource is in a different account, you will need to manually reconfirm the subscription.

Can you put the change behind a feature flag?

**Comment by i05nagai** [comment]
That makes sense. Thank you! I have added a feature flag. Could you please take a look?

**Comment by i05nagai** [comment]
Hi, should I resolve the conflicts?

**Comment by TheRealAmazonKendra** [comment]
> Hi, should I resolve the conflicts?

Apologies on the delayed answer here. Yes, please do.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
We need the conflicts resolved before we can provide a review.

**Comment by TheRealAmazonKendra** [comment]
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

**Pull request closed without merging**
