### PR TITLE
chore: enforce `import/order` lint rule

### PR DESCRIPTION
**Pull request by mrgrain**
A recent change in a dependency we use to enforce the order of imports included a small update  to sort import from `./` before `../`.
We previously warned about violations of this rule, but did not enforce it.
This frequently causes files unrelated to a change being updated.

With this change I've updated all violations of this rule and the lint step is now free of warnings.
Most of these updates where automated, by passing `--fix` to the lint command.
For a few I had to manual resolve the problem.
In a small number of cases the import order could not be changed without causing a test failure.
For these I have just disabled the rule per line/block and did not investigate further.

This changes also updates the `import/order` rule to `error` to avoid any future issues.

Existing PRs will be fine, we enforce update from main anyway.
In some circumstances where new imports are added this will cause conflicts and require manual intervention.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — APPROVED** [review]

**Review by kaizencc — APPROVED** [review]

**Comment by TheRealAmazonKendra** [comment]
NICE. I was going to do this so I'm glad you beat me to it!

**Comment by Naumel** [comment]
Not sure if anyone already put this through the pipeline, I'll check and do so otherwise.

The failed build:
```
@aws-cdk/lambda-layer-node-proxy-agent:   CHANGED    integ.node-proxy-agent 1.354s
@aws-cdk/lambda-layer-node-proxy-agent:       Resources
@aws-cdk/lambda-layer-node-proxy-agent: [~] AWS::Lambda::Function ProviderNode14frameworkonEventD778512E 
@aws-cdk/lambda-layer-node-proxy-agent:  â””â”€ [~] Code
@aws-cdk/lambda-layer-node-proxy-agent:      â””â”€ [~] .S3Key:
@aws-cdk/lambda-layer-node-proxy-agent:          â”œâ”€ [-] a8a62b989c7866e3ad5b24f3eb6228f8ca91ebff5f5c76f1da466f6c805c0585.zip
@aws-cdk/lambda-layer-node-proxy-agent:          â””â”€ [+] b6c61204d329ddd29ca4df2357f2e13237eeb763fecd5410d8fee397066160eb.zip
@aws-cdk/lambda-layer-node-proxy-agent: Snapshot Results: 
@aws-cdk/lambda-layer-node-proxy-agent: Tests:    1 failed, 1 total
@aws-cdk/lambda-layer-node-proxy-agent: Error: Some tests failed!
@aws-cdk/lambda-layer-node-proxy-agent: To re-run failed tests run: integ-runner --update-on-failed
@aws-cdk/lambda-layer-node-proxy-agent:     at main (/codebuild/output/src218385782/src/github.com/aws/aws-cdk/packages/@aws-cdk/integ-runner/lib/cli.js:164:19)
@aws-cdk/lambda-layer-node-proxy-agent: Error: integ-runner exited with error code 1
@aws-cdk/lambda-layer-node-proxy-agent: Tests failed. Total time (12.3s) | /codebuild/output/src218385782/src/github.com/aws/aws-cdk/node_modules/jest/bin/jest.js (10.6s) | integ-runner (1.7s)
@aws-cdk/lambda-layer-node-proxy-agent: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by mrgrain** [comment]
@Naumel I am on it, see last change. Need to get the build green first anyway 😅

**Comment by mrgrain** [comment]
Running pipeline test with execution id `e432669d-7be7-42ed-a986-0276df736655`...

**Pull request merged**
