### PR TITLE
v1.10.0

### PR DESCRIPTION
**Pull request by rix0rrr**
See CHANGELOG

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nmussy** [comment]
@rix0rrr It seems you didn't bump `package-lock.json` version fields (#4060)

**Comment by rix0rrr** [comment]
This release may impact our canaries, I think I'm not going to release on a Friday.

**Comment by jd-carroll** [comment]
@rix0rrr I recently started managing my first lerna repo and am having trouble managing package dependencies updates (i.e `npm update`).  What script did you use to update all of the versions like this?

**Comment by nmussy** [comment]
@jd-carroll You can check out the [bump.sh](https://github.com/aws/aws-cdk/blob/master/bump.sh) script, it's pretty straightforward:

https://github.com/aws/aws-cdk/blob/462055269c62a475201bbd51dc29768d32e31add/bump.sh#L13

**Comment by jd-carroll** [comment]
@nmussy Thanks for the help! I guess I was looking for a way to better manage external dependencies (not the ones within my lerna repo).  I feel like there are a couple of things like this and updating the `package-lock.json` and updating deps in the root `node_modules` folder that could use a little work.  But thanks again for help! 😄

**Pull request merged**
