### PR TITLE
fix(cloudfront-origins): policy not added for custom OAI

### LINKED ISSUE #18185: (cloudfront): explicit OAI for S3Origin doesn't work for cloudfront.
### General Issue

General Issue

### The Question

When I try to associate OAI by passing the props in the `S3Origin`, it doesn't work
`const s3Origin = new S3Origin(Bucket, {originAccessIdentity: oai});`
While it works when no OAI is passed, A new OAI is created for the same bucket
` const s3Origin = new S3Origin(Bucket)`

I create the OAI by using `cloudfront.OriginAccessIdentity`
```
const oai = new cloudfront.OriginAccessIdentity(this, 'OAI',{
   comment: "This is for OAI"
})
```

### CDK CLI Version

1.126.0

### Framework Version

_No response_

### Node.js Version

_No response_

### OS

Windows

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by smguggen**
Closes [**#18185**](https://github.com/aws/aws-cdk/issues/18185): When creating an `S3Origin` without including an existing `Origin Access Identity`, an `OriginAccessIdentity` is created and added to the bucket's resource policy. However, since the adding to the resource policy is inside of the `if (!this.originAccessIdentity)`closure, custom OAI's are not added to the bucket policy by default. Since using `bucket.grantRead` creates an overly permissive policy (as noted in the source code comments), adding the OAI to the bucket policy by default for both cases would create a more consistent result. 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by peterwoodworth — COMMENTED** [review]
The fix looks good to me @smguggen, but be sure to run the integration tests! 🙂

**Comment by smguggen** [comment]
@peterwoodworth Yeah I just came back and saw that. I've been wracking my brain trying to figure out why `integ.s3-origin` is still failing and I didn't even notice there's another integration test called `integ.origin-oai`, which is actually the one that's failing. My mistake, will fix.

**Review by peterwoodworth — APPROVED** [review]
LGTM, will let @njlynch take a look before merge

**Comment by mnapoli** [comment]
Thank you! ❤️  That allowed some simplifications in our CDK constructs (https://github.com/getlift/lift/pull/150)

**Pull request merged**
