### PR TITLE
fix(ecr): auto delete images on ECR repository containing manifest list

### LINKED ISSUE #24822: Auto delete images upon ECR repo removal - CDK v2.70.0 not working
### Describe the bug

Tested this much awaited feature in CDKv2.70.0 and it is still not working as expected.

Error
```
Resource handler returned message: "The repository with name 'test-app' in registry with id '1234567890' 
cannot be deleted because it still contains images (Service: Ecr, Status Code: 400,
Request ID: 842c370d-f12344XXXXX-ed47d07f0443)" 
(RequestToken: c64e0c80-9xxxxxxca5006c6c, HandlerErrorCode: GeneralServiceException)
```

ecr: add option to auto delete images upon ECR repository removal (https://github.com/aws/aws-cdk/issues/24572) ([7de5b00](https://github.com/aws/aws-cdk/commit/7de5b00dcf24c4f6721317860c7e42c485e3ca58)), closes https://github.com/aws/aws-cdk/issues/15932 https://github.com/aws/aws-cdk/issues/12618 https://github.com/aws/aws-cdk/issues/15932

### Expected Behavior

Delete of ECR repo with images should succeed if removalPolicy "Destroy" and autoDelete "true"

```
const bucket = new ecr.Repository(this, 'Repo', {
  repositoryName: 'delete-even-if-contains-images',
  removalPolicy: cdk.RemovalPolicy.DESTROY,
  autoDeleteImages: true,
});
```

### Current Behavior

Error
```
Resource handler returned message: "The repository with name 'test-app' in registry with id '1234567890' 
cannot be deleted because it still contains images (Service: Ecr, Status Code: 400,
Request ID: 842c370d-f12344XXXXX-ed47d07f0443)" 
(RequestToken: c64e0c80-9xxxxxxca5006c6c, HandlerErrorCode: GeneralServiceException)
```

### Reproduction Steps

Create a ECR repo similar to below using `cdk deploy` and add images to it. Afterwards, execute `cdk destroy` which fails with exception mentioned above

```
const bucket = new ecr.Repository(this, 'Repo', {
  repositoryName: 'delete-even-if-contains-images',
  removalPolicy: cdk.RemovalPolicy.DESTROY,
  autoDeleteImages: true,
});
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

CDK v2.70.0 

### Framework Version

_No response_

### Node.js Version

v19.8.0

### OS

mac-os M1

### Language

Java

### Language Version

JDK 17

### Other information

_No response_

### PR DESCRIPTION
**Pull request by hkford**
Fixes #24822

As I commented on [GitHub issue](https://github.com/aws/aws-cdk/issues/24822#issuecomment-1531165305), auto delete container images in ECR repository fails when it has container manifest list. I fix custom resource Lambda function to delete tagged images first.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
Hi @hkford feel free to ping me on cdk.dev slack if you need any help to complete this PR.

**Comment by hkford** [comment]
Exemption Request - All integration tests remain unchanged so I think we do not need to update snapshots in this PR.

**Comment by missourian55** [comment]
@hkford  Waiting for this PR to be available. Can you please?

**Comment by hkford** [comment]
@missourian55 
I'm waiting for this PR to be reviewed by maintainer. This PR does not need integration test change.

**Comment by hkford** [comment]
Exemption Request - All integration tests remain unchanged so I think we do not need to update snapshots in this PR.

**Pull request closed without merging**
