### PR TITLE
chore(build): allow only building docs for dev

### PR DESCRIPTION
**Pull request by eladb**
Tweak build-docs.sh so if BUILD_DOCS_DEV is set,
it will continue despite not having reference documentation in dist/sphinx.

Update CONTRIBUTING

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by Doug-AWS** [comment]
set BUILD_DOCS_DEV=1 DOH!

**Comment by eladb** [comment]
It's a new feature 👍

**Comment by Doug-AWS** [comment]
This requires Sphinx 1.7.6 and the Sphinx extensions m2r 0.1.14, sphinx_tabs (not sphinx-tabs as shown in requirements.txt) 1.1.7, and sphinx_rtd_theme 0.4.1.

I recommend we use a Python virtual environment as it is a PITA to change these if you already have a different version installed.

Once I created a virtual environment (see https://www.pythonforbeginners.com/basics/how-to-use-python-virtualenv), I installed Sphinx and the extensions, fixed requirements.txt, and changed the PYTHONPATH setting in build-docs.sh to (it was 3.6 and 3.7):

export PYTHONPATH=${PYTHON_DEPS}/lib/python2.7/site-packages

**Comment by Doug-AWS** [comment]
The virtual environment was a red herring. Fixing requirements.txt and changing the PYTHONPATH made my build work.

**Pull request merged**
