### PR TITLE
fix(ssm): fix service principals for all regions since ap-east-1 

### LINKED ISSUE #16188: ssm: service principals are incorrect for all regions since `ap-east-1`
### The Issue

iam.ServicePrincipal (https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/ServicePrincipal.html) offers a "region" parameter. Presumably this parameter is so you can say something like ssm.ap-us-east-1.amazonaws.com to be inclusive of regional-only service endpoints. 

Such as the ones called out on this page: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-inventory-datasync.html#systems-manager-inventory-resource-data-sync-AWS-Organizations

> 
> "Note
> 
> The Asia Pacific Region came online in April 25, 2019. If you create a resource data sync for an AWS Region that came online since the Asia Pacific (Hong Kong) Region (ap-east-1) or later, then you must enter a Region-specific service principal entry in the SSMBucketDelivery section. The following example includes a Region-specific service principal entry for ssm.ap-east-1.amazonaws.com."

However

Here is a snippet of CDK Python that results in some odd behavior: 

```
        kmsKey = kms.Key(
            self,
            "S3-KMSKey",
        )

        kmsKey.add_to_resource_policy(
            statement=iam.PolicyStatement(
                sid="ssm-access-policy",
                conditions=[],
                effect=iam.Effect.ALLOW,
                actions=["kms:GenerateDataKey"],
                principals=[
                    iam.ServicePrincipal(service="ssm.amazonaws.com"),
                    iam.ServicePrincipal(
                        service="ssm.amazonaws.com", region="ap-east-1"
                    ),
                    iam.ServicePrincipal(service="ssm", region="ap-east-1"),
                ],
                resources=[kmsKey.key_arn],
            )
        )
```

That snippet uses ServicePrincipal three different ways, two of which should result in regional endpoints, and yet none of them do. 

That snippet spits out something that looks like... 

```
Resources:
  S3KMSKey26947010:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
          - Action: kms:GenerateDataKey
            Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
                - ssm.amazonaws.com
                - ssm.amazonaws.com
            Resource:
              Fn::GetAtt:
                - S3KMSKey26947010
                - Arn
            Sid: ssm-access-policy
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: SsmInventoryAthenaStack/S3-KMSKey/Resource
```
Notice that none of the Principal -> Service definitions have 'ap-east-1' in their URLs. 

This might be related to these two issues:
https://github.com/aws/aws-cdk/issues/2622
https://github.com/aws/aws-cdk/issues/2999

Where CDK was exclusively crafting regional endpoints

### Environment

  - **CDK CLI Version:**  2.0.0-rc.17 (build fb5dc58)
  - **Module Version:**  2.0.0rc17 (I think, pulled from python's Pipfile.lock for aws-cdk-libs)
  - **Node.js Version:**  v14.17.1
  - **OS:**  OSX
  - **Language:**  Python

### PR DESCRIPTION
**Pull request by jolo-dev**
fixes #16188 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by njlynch — DISMISSED** [review]
Thanks for the contribution!

I made some suggestions that will reduce duplication and make it easier to add more region-specific principals in the future.

**Comment by jolo-dev** [comment]
@njlynch Thanks for your review. I have apply your requests

**Review by njlynch — DISMISSED** [review]

**Review by njlynch — DISMISSED** [review]

**Comment by jolo-dev** [comment]
@njlynch I didn't know that you took over. I guess, you have to approve again.

**Comment by njlynch** [comment]
> I didn't know that you took over. I guess, you have to approve again.

Can you please revert the changes to CHANGELOG.md? You've introduced merge conflicts here. You don't need to merge to the latest from `master`; our workflows will do that for you automatically once it's been approved.

**Comment by jolo-dev** [comment]
Hey @njlynch,
I have reverted the `CHANGELOG.md`.

**Review by njlynch — APPROVED** [review]

**Pull request merged**
