### PR TITLE
feat(pipelines): add `synthCodeBuildDefaults`

### PR DESCRIPTION
**Pull request by hoegertn**
This change allows specifying the codeBuildDefaults for the synth-action as it is already possible with assets and self-mutation.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
The reason it's possible for those other actions is because you have NO CHOICE other than to specify them there, as you don't control any other aspects of their creation. For the synth step that's not true, if you care you can always drop to a `CodeBuildStep` and specify what you need there. The same question is going to arise for arbitrary `ScriptStep`s in `pre` and `post` positions, and we're also not going to add `codeBuildDefaults` for those.

I'm trying to keep the API narrow yet complete--do you have an example of a use case that would be markedly improved by supplying the properties here instead of somewhere else?

**Comment by hoegertn** [comment]
I am trying to keep the separation of Blueprint and Implementation. So I can provide the ShellStep to synthesize and have the CodeBuild overrides somewhere else. E.g. in a construct library, I want to set env, VPC, etc but let the user provide the ShellStep for the synthesize action.

**Comment by rix0rrr** [comment]
If that's the goal, then you can still have them specify `ShellStep` and turn it into a `CodeBuildStep` in your construct library.

And VPC would probably apply to *all* codeBuild steps and hence would go into `codeBuildDefaults`.

Do you have an actual immediate issue, or is this hedging against the future?

**Comment by hoegertn** [comment]
It is an immediate issue as I want to set a buildEnvVariable for synth and setting it for all build projects fails for asset actions (#15628)

But I can workaround it if you do not want this to be included in the API

**Comment by rix0rrr** [comment]
I do see the point (and--confession time--I did have it in originally), but I'd prefer to keep the API minimalist for now and not have too many ways to achieve the same goals. If you could supply both `synthCodeBuildDefaults` as well as use a `CodeBuildStep`, then which one is the "right" solution? I'd prefer to avoid the confusion.

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
