### PR TITLE
feat(ec2): added `requireImdsv2` flag to `NatInstanceProvider`

### LINKED ISSUE #23803: aws_cdk.aws_ec2 NatInstanceProvider: missing require_imdsv2
### Describe the feature

Can we get the require_imdsv2 parameter added to the aws_cdk.aws_ec2 NatInstanceProvider resource?
This was resolved for EC2 and ASG here:  Support setting EC2 instance metadata to require token (IMDSv2) #5137

#16051
#16052

### Use Case

The AWS Foundational Security Best Practices v1.0.0 for Security Hub will produce a finding for the NAT instances under EC2.8: EC2 instances should use Instance Metadata Service Version 2 (IMDSv2)

### Proposed Solution

_No response_

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.61.1 (build d319d9c)

### Environment details (OS name and version, etc.)

WSL: Ubuntu 20.04.5 LTS (Focal Fossa)

### PR DESCRIPTION
**Pull request by lpizzinidev**
Added `requireImdsv2` parameter to `NatInstanceProps`.
This will allow configuring [`IMDSv2`](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) instance metadata on NAT instances.

Closes #23803

### CODE REVIEW

**Comment by lpizzinidev** [comment]
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Features must contain a change to an integration test file and the resulting snapshot.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.
> 
> If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

Exemption Request.

I don't think that this PR should require changes to existing or the creation of new integration tests.
Let me know if you think that some changes are required.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Please make sure that your PR body describes the problem the PR is solving, and the design approach and alternatives considered. Explain why the PR solves the problem. A link to an issue is helpful, but does not replace an explanation of your thought process (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request))

**Comment by TheRealAmazonKendra** [comment]
We will want an integ test update for this. 

You can feel free to add the prop to an existing one and then run it using `yarn integ --update-on-failed.` Updating an existing one is better, in this case, that creating a new test because it will show us the outcome of adding this prop to an existing stack.

**Comment by lpizzinidev** [comment]
@TheRealAmazonKendra 
I've updated an integration to include the new property.
However, CodeBuild is failing because of
```
@aws-cdk/aws-ec2: !!! This test contains destructive changes !!!
...
```
Do I need to make other updates to my tests?

**Pull request closed without merging**
