### PR TITLE
docs(route53): Add example of A record for Elastic IP

### PR DESCRIPTION
**Pull request by GrahamLea**
It took me ages to figure out how to add an A record for an EIP.

Using `instance.instancePublicIp` doesn't work, because it seems the instance is given another public IP before the EIP is associated with it, and that is what `instance.instancePublicIp` resolves to, which then quickly becomes wrong.

It's not clear in `RecordTarget.fromIpAddresses` that it can take a reference to an EIP. I'm still not even sure why this works, but it does. So I thought I'd add an example to help others see how to do it.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by njlynch — APPROVED** [review]
Thanks for the contribution!

> It's not clear in RecordTarget.fromIpAddresses that it can take a reference to an EIP. I'm still not even sure why this works, but it does

`fromIpAddresses` takes a list of IPs as strings, and the EIP's reference is an IP address ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html#aws-properties-ec2-eip-return-values)).

**Comment by GrahamLea** [comment]
> `fromIpAddresses` takes a list of IPs as strings, and the EIP's reference is an IP address ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html#aws-properties-ec2-eip-return-values)).

Ah, thanks @njlynch - my expertise at finding the right info in CloudFormation docs is still nascent. 😁

**Comment by njlynch** [comment]
@Mergifyio rebase

**Comment by njlynch** [comment]
@GrahamLea - Somehow this PR ended up in an odd state and never got merged. I tried merging the latest changes, but it appears we don't have permissions on the branch (anymore?). Can you see if "allow maintainers to push changes" is enabled on this PR, or alternatively open a new PR and mention me on it so I can re-approve?

**Comment by GrahamLea** [comment]
Hi @njlynch. I don't know why, but the "Allow maintainers..." option is not available on this PR. I've merged master into the PR branch. If that isn't enough to make it work, let me know and I can open another PR.

**Review by njlynch — APPROVED** [review]

**Pull request merged**
