### PR TITLE
chore(init-templates/typescript): exclude node_modules

### LINKED ISSUE #11902: (init-templates/typescript): exclude node_modules
### The Question

I don't know whether it is intentional or not, however when initializing a Typescript app the `node_modules` are included into the project and will therefore be type checked and so on. This is because you override the default settings of exclude to `"exclude": ["cdk.out"]`.

> Note: without an exclude list, node_modules is excluded by default; as soon as one is added, it's important to explicitly add node_modules to the list. (Source: [Specifying Files](https://github.com/microsoft/TypeScript/wiki/Performance#specifying-files))

Regarding the [Performance recommendation](https://github.com/microsoft/TypeScript/wiki/Performance) by the official Typescript team, it is considered a best practice to exclude `node_modules`.  This could easily be achieved by adding it to `exclude`:

https://github.com/aws/aws-cdk/blob/60875a5d6cd93b7d6f0f9b1b94153f6d1f4766b1/packages/aws-cdk/lib/init-templates/v2/app/typescript/tsconfig.json#L22

```jsonc
{
  // ...
  "exclude": [
    "node_modules",
    "cdk.out"
  ]
}
```

If you don't mind I would create a PR myself. :-)

### Environment

  - **CDK CLI Version:** 1.76.0
  - **Node.js Version:** v12.16.2
  - **OS:** macOS Catalina
  - **Language (Version):** ^4.0.2

### PR DESCRIPTION
**Pull request by bmacher**
Closes #11902

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by bmacher** [comment]
@peterwoodworth the failing `PR Linter` check tells that features must have a change in a README. As this is just a little change in the `tsconfig` I don't really know what to change.

**Comment by peterwoodworth** [comment]
I changed the title of the issue to `chore` as this isn't really a new feature for customers to use. In doing so, you no longer have to make a change to a readme, as that isn't required for chores.

Did you notice or test any difference before and after adding `node_modules`?

**Comment by bmacher** [comment]
My IDE feels a bit faster.

**Review by peterwoodworth — APPROVED** [review]
Looks good, thanks for your contribution!

**Pull request merged**
