### PR TITLE
docs(route-53-targets): Grammar corrections to route53-targets readme.md

### PR DESCRIPTION
**Pull request by rcollette**
.. for things like a/an.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by peterwoodworth — APPROVED** [review]
thanks for helping to clean up our docs!

**Comment by peterwoodworth** [comment]
@rcollette can you resubmit this PR on the latest version? Not sure why the build failed for you here.

**Comment by peterwoodworth** [comment]
@rcollette let me know if you're able to resubmit this, if not I'll go ahead and do it this week

**Comment by rcollette** [comment]
@peterwoodworth  - Have at it.

**Pull request closed without merging**
