### PR TITLE
feat: Parameterize bootstrap stack version

### PR DESCRIPTION
**Pull request by rabbittsoup**
The hard coding of the cdk version ssm parameter limits custom bootstrap configurations.  In a managed account environment, the naming may not conform to environment requirements, preventing cdk bootstrap deployment.  By also allowing the parameter name to be customized, multiple bootstrap stacks could exist in the same environment, which can enable more granular management of the bootstrap resources.

This implementation resolves the issue by allowing the ssm parameter name to be customized through the same mechanism as other default/modern synthesizer parameters.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rabbittsoup** [comment]
Fixes Issue #14313

**Comment by rabbittsoup** [comment]
Original post edited.

**Comment by rix0rrr** [comment]
I have a feeling I just recently approved the exact same change in a different PR? Or am I going batty?

In any case, there are conflicts to resolve now, sorry.

**Comment by rabbittsoup** [comment]
The other approved change was for v2, this is v1.

**Comment by rabbittsoup** [comment]
Conflicts resolved

**Review by rix0rrr — APPROVED** [review]

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
