### PR TITLE
feat(lambda-nodejs): custom asset hash

### LINKED ISSUE #16157: (aws-lambda-nodejs): `CUSTOM` hash pass-through
Currently the `@aws-cdk/aws-lambda-nodejs` Functions default to `OUTPUT` hash type - however it'd be great to make this a configuration option to allow custom calculation of the hash to trigger a build on-demand.

### Use Case

Improved deploy times when used with a Node-based async checksum algorithm for directories, or for manually triggering deploys in CI/CD based on external data.

### Proposed Solution

As part of the `NodejsFunction` export `props`, re-add a `bundling` option for customizing the hash method & value using the existing `@aws-cdk/aws-lambda#Function` props. It would purely be a pass-through to the `bundling.ts`, optionally falling back to the current defaults - there wouldn't be any breaking changes.

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by jogold**
By default the asset hash for a `NodejsFunction` is based on the
bundling output, the result of the `esbuild` bundling.

Add a `assetHash` prop to customize the asset hash and allow users to
implement their own logic. This can be useful if users want to invalidate
the asset based on specific (input) file contents or logic.

Closes #16157

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@nija-at can you check this? thx!

**Comment by jogold** [comment]
> @jogold - can you update the PR description with more details on what is going on here and why this is needed?
> 
> I couldn't fully understand it from the linked issue.

updated

**Comment by nija-at** [comment]
I'm still following the motivation.

What is a use case for this? Why would we want to provide such an option?
Why is updating our current hash calculation not enough?

It feels that this is going to be used incorrectly more often than correctly, and thereby users are going to shoot themselves in the foot.

**Comment by jogold** [comment]
> What is a use case for this? Why would we want to provide such an option?

@oyed can you detail your use case here?

One use case I can think of: you don't want the hash to change if the way `esbuild` bundles changes, e.g. for the same input files and dependencies the content of the resulting `index.js` is different but functionally remains the same. This can happen after an update of `esbuild` for example.

Identifying the specific input files of a `NodejsFunction` is almost impossible to achieve in the construct itself. The idea of the `NodejsFunction` is to allow users to mix infra and runtime code, so we don't know what is the "source".


> It feels that this is going to be used incorrectly more often than correctly, and thereby users are going to shoot themselves in the foot.

We're just exposing an asset option from `core` which allows to do this. `aws-lambda-go` and `aws-lambda-python` are already exposing this.

**Review by eladb — DISMISSED** [review]
LGTM

**Review by eladb — DISMISSED** [review]

**Review by eladb — APPROVED** [review]

**Pull request merged**
