### PR TITLE
fix(appsync): Populate construct name dynamically for lambda authorizer permission in appsync

### PR DESCRIPTION
**Pull request by ranjith-jagadeesh**
fixes https://github.com/aws/aws-cdk/issues/23434

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by owenmorgan — APPROVED** [review]

**Review by robertpitt — APPROVED** [review]

**Review by MrArnoldPalmer — APPROVED** [review]
TY for adding tests and reopening! 🔥

**Comment by ranjith-jagadeesh** [comment]
> TY for adding tests and reopening! 🔥

Thanks for reviewing and merging🔥

**Comment by ranjith-jagadeesh** [comment]
@MrArnoldPalmer When new version of package @aws-cdk/aws-appsync-alpha will be released?

**Comment by MrArnoldPalmer** [comment]
@ranjith-jagadeesh the appsync package is now stable and in `aws-cdk-lib` so no new versions of the alpha  package will be released. This fix will go out in our next normally planned release, probably sometime next week.

**Pull request merged**
