### PR TITLE
feat(stepfunctions): add `EvaluateExpression` task

### PR DESCRIPTION
**Pull request by jogold**
Use the `EvaluateExpression` to perform simple operations referencing state paths. The
`expression` referenced in the task will be evaluated in a Lambda function
(`eval()`). This allows you to not have to write Lambda code for simple operations.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
See [README - Eval example](https://github.com/aws/aws-cdk/blob/59c0e5a809c812273ac4b790cf8fbd4015d96e35/packages/%40aws-cdk/aws-stepfunctions/README.md#eval-example) for usage example.

**Comment by rix0rrr** [comment]
This is another super sexy submission @jogold! I've been putting off reviewing it a little because it honestly scares me a little, what with using `eval` and all.

Undoubtedly very useful, but I have serious reservations about shipping this in the core library. I wonder if it's not better off in a 3rd party construct library.

**Comment by jogold** [comment]
@rix0rrr I was expecting this kind of reaction to the usage of `eval` 😄 

One of the security issues with `eval` is when it's used to evaluate user input, especially on a server/backend. 

Let's look at the `eval` in the context here: the user is the CDK developer not an "external user" (he should know what he's doing) and the `eval` is run in an isolated backend (Lambda) with no IAM permission. Isn't this comparable to letting a CDK developer write (bad) Lambda code?

**Comment by rix0rrr** [comment]
It is, and my concern is not about security. More about whether or not we want to take on the maintenance burden of when people are inevitably going to misuse/abuse the feature.

Nevertheless, because it is a little unorthodox, we're also going to have to have a security review with the appropriate people internally. I don't predict that being a blocker though. Given that the IAM policy of the Lambda has barely  any permissions, the worst you would be able to do is rack up Lambda charges in your own account.

**Pull request merged**
