### PR TITLE
feat(cli): exposed `synth`'s `quiet` option in `cdk.json`

### LINKED ISSUE #24251: aws-cdk / cli: option to have the `synth`'s `--quiet` option exposed in `cdk.json`
### Describe the feature

The vast majority of the time when running `cdk synth` we don't want the template to be written -- I can't think of a time when I _do_ want it to be written...

Whilst the `--quiet` option can be added to the command line, it would be nice to be able to specify this in any of the `cdk.json` files

### Use Case

When running `cdk synth`, the output is written to the `cdk.out/` folder, and this is generally what I look at when I want to view the CF Templates, etc.  On the console I really only want to be seeing the warnings and errors, never the template.

Adding `--quiet` each and every time I want to synth is cumbersome, often forgotten (which could mean scrolling back several hundred lines to see any other outputs), and is additional characters to have to type each and every time.

### Proposed Solution

Either a
```
"quiet": true
```
or
```
"synthesize": {
    "quiet": true
}
```
in the cdk.json, picked up in any of the files (personally I'd add it to `~/.cdk.json`).

### Other Information

_No response_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.65.0

### Environment details (OS name and version, etc.)

MacOS, although the feature would be for all OSes.

### PR DESCRIPTION
**Pull request by lpizzinidev**
The `quiet` option for `synth` can now be specified in `cdk.json` as:
```
{
  "quiet": true
}
```

Closes #24251

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by lpizzinidev** [comment]
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Features must contain a change to an integration test file and the resulting snapshot.
> ❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/24335/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.
> 
> If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

Exemption Request.

I didn't find any integration test related to CLI in the repo.
Let me know if I need to add a new one or point me to an existing one so that I can update it if necessary.

Thanks.

**Comment by TheRealAmazonKendra** [comment]
In lieu of integ tests on this, please provide us with the summary of how this was manually tested. We will run it through our CLI tests separately.

**Comment by TheRealAmazonKendra** [comment]
Oops. Removed too many labels. Adding the exemption request back.

**Comment by lpizzinidev** [comment]
@TheRealAmazonKendra 
In the end, I did add an integration test in `packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts` (it looks like the linter is not recognizing it as so).
This allowed me to fix the implementation which should now be working.
Let me know if you need me to apply other changes or improvements to the PR.

**Comment by TheRealAmazonKendra** [comment]
I have a small backlog of things to put through the CLI test pipeline but I'll try to get this run today. This looks good but we always run these through to just be sure. 

Was the documentation clear and sufficient for these type of tests? Given that it's a newer module, I just want to make sure we don't have gaps there.

**Comment by lpizzinidev** [comment]
@TheRealAmazonKendra 
Thanks for the quick feedback.

The docs in `@aws-cdk-testing/cli-integ` were clear to me.
Maybe a reference to CLI integration tests and their location could be added in `INTEGRATION_TESTS.md`.
Since they don't follow the same format as other integration tests, it took me a while to find them 😄

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra Thanks for the quick feedback.
> 
> The docs in `@aws-cdk-testing/cli-integ` were clear to me. Maybe a reference to CLI integration tests and their location could be added in `INTEGRATION_TESTS.md`. Since they don't follow the same format as other integration tests, it took me a while to find them 😄

Good idea! Thanks for the feedback on this!

**Comment by gburke-ppb** [comment]
@ lpizzinidev Thank you for this!  🙏🏻👍🏻

**Comment by lpizzinidev** [comment]
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Features must contain a change to an integration test file and the resulting snapshot.
> ❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/24335/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.
> 
> If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

Exemption Request.
Integration test added in `cli.integtest.ts`.

**Comment by gburke-ppb** [comment]
Any update on this?

**Pull request closed without merging**
