### PR TITLE
chore: add core team members to mergify and merit badger

### PR DESCRIPTION
**Pull request by kaizencc**
From now on, we need to keep our core members in sync between mergify and merit badger. I can't think of a good way to automate this (yet) while keeping the github actions separate. We could simply filter for PRs that have the `contribution/core` label that mergify adds, but there is a race condition here and `contribution/core` may not be added before the merit badger is run.

### CODE REVIEW

**Comment by kaizencc** [comment]
The bots should be correctly ignored by #22192. I'm wary of adding `[bot]` to the list of ignore usernames because the `[` keyword will mess with the input and isn't allowed for normal usernames anyway. The docs also point to ignoring bot accounts using `if` conditions rather than anything else.

**Review by Naumel — APPROVED** [review]

**Comment by TheRealAmazonKendra** [comment]
But... I want a badge...

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio requeue

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
