### PR TITLE
feat: move "s3-assets" and "ecr-assets" into "core"

### LINKED ISSUE #11859: (ecr-assets): confusing docs on  Grant Permissions to DockerImageAsset
Link to reference doc page: [aws-ecr-assets.DockerImageAsset](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecr-assets.DockerImageAsset.html#repositoryspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan)

Describe your issue: 

It is not clear how to grant permissions to a `DockerImageAsset`.  Buried in the python comments is the following remark:

```
### Pull Permissions

Depending on the consumer of your image asset, you will need to make sure
the principal has permissions to pull the image.

In most cases, you should use the `asset.repository.grantPull(principal)`
method. This will modify the IAM policy of the principal to allow it to
pull images from this repository.

If the pulling principal is not in the same account or is an AWS service that
doesn't assume a role in your account (e.g. AWS CodeBuild), pull permissions
must be granted on the **resource policy** (and not on the principal's policy).
To do that, you can use `asset.repository.addToResourcePolicy(statement)` to
grant the desired principal the following permissions: "ecr:GetDownloadUrlForLayer",
"ecr:BatchGetImage" and "ecr:BatchCheckLayerAvailability".
"""
``` 

For cases where task definitions cannot be create in CDK (for example they are created later by lambda), it is still beneficial to declare the container in CDK.  Especially with CDKPipelines now in preview.

This language is found at the Overview level, however, a nod in the class page would be helpful or we could alias the function.

```python
def grant_pull(self, grantee: aws_cdk.aws_iam.IGrantable) -> aws_cdk.aws_iam.Grant:
   self.repository.grant_pull(grantee)
```

---

This is a 📕 documentation issue

### LINKED ISSUE #13327: (aws-ecr-assets): DockerImageAsset.repository is not really a repository (e.g. grants result in a no-op)
When adding pull permissions as stated in the [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecr-assets-readme.html#pull-permissions), the result is a no-op

### Reproduction Steps

```javascript
const myAsset = new DockerImageAsset(this, "MyAsset", {
  directory: path.join(process.cwd(), "docker", "my-asset"),
});
myAsset.repository.addToResourcePolicy(
  new PolicyStatement({
    principals: [
      new AccountPrincipal("123123123"),
      new AccountPrincipal("78667867"),
    ],
    actions: [
      "ecr:GetDownloadUrlForLayer",
      "ecr:BatchCheckLayerAvailability",
      "ecr:BatchGetImage",
    ],
  }),
);
```

### What did you expect to happen?

ECR repo's permissions policy gets updated according to the code

### What actually happened?

Nothing

### Environment

  - **CDK CLI Version  :*1.86.0*
  - **Framework Version: *1.86.0*
  - **Node.js Version: *v13.8.0*
  - **OS               :*MacOS Catalina*
  - **Language (Version): *TypeScript (3.9.6)*

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
This change deprecates the `@aws-cdk/aws-s3-assets` and `@sws-cdk/aws-ecr-assets` modules and moves all the asset types to the `core` module under `FileAsset` and `ImageAsset`. Old classes and modules are marked `@deprecated` and will no longer be supported in the next major version of the AWS CDK.

As part of this change, the API of `FileAsset` and `ImageAsset` have been narrowed to reflect the capabilities of the asset system with modern bootstrapping. Namely, the S3 bucket and ECR repository used to host assets are no longer exposed via the API since they can not be controlled from the CDK app (they are created as part of bootstrapping).

Fixes #13327
Fixes #11859

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by markusl** [comment]
Hi!

Just wanted to clarify what do you mean by "ECR repository [...] can not be controlled from the CDK app"? For our use cases, it would be important to be able to provide ECR lifecycle policies and configure ECR image scanning. Is this PR going to affect that kind of capabilities?

Br,
Markus

**Comment by eladb** [comment]
> ECR lifecycle policies and configure ECR image scanning

This is something you should be able to set up when you bootstrap the ECR repository, but not as part of the CDK app. @skinny85 do we have support for these in the bootstrapping stack?

**Comment by skinny85** [comment]
@eladb we do not allowing customizing the ECR repository through any switches in the `bootstrap` command itself today.

But you can use your own template for bootstrapping with the `--template` switch.

**Review by rix0rrr — APPROVED** [review]

**Comment by eladb** [comment]
Superseded by https://github.com/aws/aws-cdk/pull/14160

**Pull request closed without merging**
