### PR TITLE
chore(cloudfront): use standard file naming convention for OAI and Web Distribution

### PR DESCRIPTION
**Pull request by robertd**
cc @njlynch 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by njlynch — DISMISSED** [review]
I suspect the build is going to fail due to this import:

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudfront/lib/web_distribution.ts#L10

Can you double-check that's the only one missing?

**Comment by robertd** [comment]
> I suspect the build is going to fail due to this import:
> 
> https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudfront/lib/web_distribution.ts#L10
> 
> Can you double-check that's the only one missing?

Whopss... Interestingly it compiled on my box... I'll triple check!

**Comment by robertd** [comment]
Ah... I forgot to clean the build... so I had compiled files with underscore still present :)

**Comment by njlynch** [comment]
> Whoops... Interestingly it compiled on my box... I'll triple check!

An artifact of our build-in-place strategy, I'm afraid. You likely have a `origin_access_identity.d.ts` and `origin_access_identity.js` file lingering from a previous build. Running a `git clean -fdx .` in the module you're working in is a good best practice to ensure you're building off of a clean set of files.

**Comment by robertd** [comment]
> > Whoops... Interestingly it compiled on my box... I'll triple check!
> 
> An artifact of our build-in-place strategy, I'm afraid. You likely have a `origin_access_identity.d.ts` and `origin_access_identity.js` file lingering from a previous build. Running a `git clean -fdx .` in the module you're working in is a good best practice to ensure you're building off of a clean set of files.

That's exactly what happened... and exactly what I've been doing right now :)

**Comment by robertd** [comment]
@njlynch updated commend to include chore, rebased off of fresh master and force pushed.

**Review by njlynch — APPROVED** [review]
Nice! This has been on my mental backlog for a while.

**Comment by robertd** [comment]
Not sure where my previous comment disappeared...

I don't think build error is related to this PR. I'll retry it again...

```bash
@aws-cdk/lambda-layer-awscli: $ cdk-build
@aws-cdk/lambda-layer-kubectl: $ cdk-build
@aws-cdk/lambda-layer-awscli: >> Building AWS Lambda layer inside a docker image...
@aws-cdk/lambda-layer-kubectl: >> Building AWS Lambda layer inside a docker image...
@aws-cdk/lambda-layer-kubectl: Sending build context to Docker daemon  3.584kB
@aws-cdk/lambda-layer-awscli: Sending build context to Docker daemon  4.096kB
@aws-cdk/lambda-layer-kubectl: Step 1/15 : FROM public.ecr.aws/lambda/provided:latest
@aws-cdk/lambda-layer-awscli: Step 1/18 : FROM public.ecr.aws/lambda/provided:latest
time="2021-01-28T18:40:42.973003326Z" level=error msg="Not continuing with pull after error: toomanyrequests: Rate exceeded"
@aws-cdk/lambda-layer-kubectl: toomanyrequests: Rate exceeded
@aws-cdk/lambda-layer-kubectl: Error: layer/build.sh exited with error code 1
@aws-cdk/lambda-layer-kubectl: Build failed.!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@aws-cdk/lambda-layer-kubectl: error Command failed with exit code 1.
@aws-cdk/lambda-layer-kubectl: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@aws-cdk/lambda-layer-awscli: latest: Pulling from lambda/provided
@aws-cdk/lambda-layer-awscli: c146c9d87b8b: Pulling fs layer
@aws-cdk/lambda-layer-awscli: 46d81d379e51: Pulling fs layer
@aws-cdk/lambda-layer-awscli: 9d6bb25e5f2d: Pulling fs layer
@aws-cdk/lambda-layer-awscli: 03ac043af787: Pulling fs layer
@aws-cdk/lambda-layer-awscli: 03ac043af787: Waiting
@aws-cdk/lambda-layer-kubectl: error Command failed with exit code 1.
@aws-cdk/lambda-layer-kubectl: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build+test exited 1 in '@aws-cdk/lambda-layer-kubectl'
lerna WARN complete Waiting for 9 child processes to exit. CTRL-C to exit immediately.

real	15m2.073s
user	112m54.675s
sys	7m54.942s
âŒ  Last command failed. Scroll up to see errors in log (search for '!!!!!!!!').
```

**Comment by robertd** [comment]
@njlynch Build is passing now.

**Review by njlynch — APPROVED** [review]

**Pull request merged**
