### PR TITLE
feat(ecs-patterns): ecs-patterns library is now stable

### PR DESCRIPTION
**Pull request by piradeepk**
Update ecs-patterns stability from experimental to stable

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pkandasamy91** [comment]
Will do a final pass today before I resolve conflicts :)

**Comment by pkandasamy91** [comment]
@rix0rrr Ready to go stable! :)

**Comment by pkandasamy91** [comment]
> Be sure that you are sure :)

Have to remove the integ test as the DNS Certificate can't be validated against a mocked domain: https://github.com/aws/aws-cdk/pull/4371

Once this PR is merged, I'm sure :)

**Comment by rix0rrr** [comment]
Remove the label when you are ready to merge.

**Pull request merged**
