### PR TITLE
fix(cloudfront): trim autogenerated cache policy name

### LINKED ISSUE #18918: (cloudfront): Name length of cache policy
### What is the problem?

When introducing a CachePolicy to a CloudFront distribution via CDK the automatic generated name could grow beyond 128 characters. This will cause the CloudFormation stack to fail as the request will be answered as a bad request. 

### Reproduction Steps

This appears if the constructs and stacks are nested and the parent logical ids are rather long. 

### What did you expect to happen?

CDK should not generate names longer than the limit to avoid those errors as the naming generation is sometimes hard to track. 

### What actually happened?

The CFN message is rather useless as we figured that root cause out by reproducing the error with all params in the management console. The CFN message reads: _Resource handler returned message: "Invalid request provided: AWS::CloudFront::CachePolicy"_ 

No further errors are provided.

### CDK CLI Version

2.8.0

### Framework Version

2.8.0

### Node.js Version

16.13.2

### OS

Windows 11

### Language

Typescript

### Language Version

3.9.10

### Other information

_No response_

### PR DESCRIPTION
**Pull request by robertd**
Closes #18918

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
@RigoIce Thanks for figuring out the main cause given the generic cloudformation error. 👍

**Comment by RigoIce** [comment]
Hi @robertd. I just wanted to jump into a discussion about that PR. 

I already had a look into the code and found out that a fix just slicing the name would probably effect the appended region. Under some circumstances we could again have same names in different regions for the policies. The region suffix was introduced in #13737 closing #13629. 

I thought more about slicing the expression `Names.uniqueId(this)`. This would probably cut of the hash what would be less problematic, I think. Also, there shouldn't be any backward problems as this only effects non-working policies with name lengths above 128 and still keeps the uniqueness across the regions. 

However, that seemed not to cover all facets for me as well because the hash could serve as a unique identifier within a region. I wasn't convinced whether my proposed slicing approach could cause problems with uniqueness in one region, i.e. multiple policies. 

So, this is the reason I haven't proposed a PR on my own as I see a possible solution with a backward compatible optional parameter for `uniqueId()` limiting the part before the hash. But this is going all the way down to CDK core just for handling exceptional cases.

Maybe my considerations are too complicated or maybe the idea could also help in other cases where a shorter ID is required. 

Happy to discuss and support.

**Comment by robertd** [comment]
@RigoIce Makes sense... Although, slicing the `uniqueId` will have to take in consideration region concatenation... and that becomes somewhat complicated once you get longer regions (i.e. `ap-southeast-3`).

I'm not 100% sure what would be the best scenario here... slice uniqueId down to 110 characters and then append region ... just to be on the safe side?

**Comment by comcalvi** [comment]
I agree with that @robertd, we need to maintain the cross-region safety introduced in #13737. I see no issue with slicing it down to 110 and then appending the region.

**Comment by robertd** [comment]
Thanks for chiming in @comcalvi. I’ll update the PR.

**Comment by robertd** [comment]
@comcalvi  ready for your review. Thanks.

**Review by comcalvi — DISMISSED** [review]
Thanks for the fix, this is great!

**Comment by robertd** [comment]
@comcalvi I had to merge in the latest master because build failed for some weird reason. Please reapprove the PR again. TIA.

**Review by comcalvi — APPROVED** [review]

**Pull request merged**
