### PR TITLE
chore: add AppMesh ECR account for ap-northeast-3 and ap-southeast-3

### PR DESCRIPTION
**Pull request by liubnu**
Add ECR accounts of new regions for AWS App Mesh.

----

### All Submissions:

* [Y] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [N] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [N] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Naumel** [comment]
Hello, thank you for your submission.

As per the information described in [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request), the pull request title needs to have formatting that conforms to the convention.

**Comment by Naumel** [comment]
Additionally, from the build output, you have failing tests which should be addressed.

```
@aws-cdk/aws-codebuild: Snapshot Results: 
@aws-cdk/aws-codebuild: Tests:    1 failed, 16 total
@aws-cdk/aws-codebuild: Error: Some tests failed!
@aws-cdk/aws-codebuild: To re-run failed tests run: yarn integ-runner --update-on-failed
```

**Comment by Naumel** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Just putting this in request changes to accurately reflect the status.

**Pull request closed without merging**
