### PR TITLE
fix(athena): WorkGroup tags corruption

### LINKED ISSUE #6936: Incompatible tags definition for AWS::Athena::WorkGroup
Currently it is not possible to create an AWS::Athena::WorkGroup due to the way tags are defined.

The WorkGroup resource expects `tags` to be a list of objects. The definition in the autogenerated code though has another level. Something like:

```json
"Tags": {
  "Tags": [{
    "key": "a",
    "value": "b"
  }]
}
```

Even if no tags are set for the resource, the generated template holds an empty object:

```json
"Tags": {},
```

This format is not supported and CloudFormation fails with an `Internal Failure`.

### Reproduction Steps

This code compiles. Note the nested tags definition.

```
    new athena.CfnWorkGroup(scope, 'Athena-Workgroup', {
        name: 'HelloWorld',
        description: 'A WorkGroup,
        recursiveDeleteOption: true,
        state: 'ENABLED',
        tags: {
            tags: [{
                key: 'a',
                value: 'b',
            }]
        },
        workGroupConfiguration: {
            requesterPaysEnabled: true,
            resultConfiguration: {
                outputLocation: `s3://${bucket.bucketName}/athena/results/`,
                encryptionConfiguration: {
                    encryptionOption: 'CSE_KMS',
                    kmsKey: key.keyArn,
                },
            },
        }
    });
```

If you remove the outer `tags`, it won't compile.

If you remove the whole `tags` definition it again compiles, but fails to create the resource due to the unexpected default value of `{}`.

### Error Log

`Internal Failure` ;-)

### Environment

All of them

### Other

I wanted to go ahead and fix the problem myself but since this is part of the autogenerated code which even seems to be not in the repo, I wouldn't know how.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by moofish32**
Since Athena does not have AWS constructs the tests are empty. What does
the team think about me adding one test to verify this patch is
correctly applied for the cfn generated constructs?

Can I also get feedback on the file name choice I made or a pointer to
conventions on the patch file names?

Fixes #6936

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by moofish32** [comment]
@iliapolo initial draft work here. A little more to do in my opinion, but looking for a little guidance from your side about what is necessary. Specifically the lint failure, which I think might be alleviated if I add a unit test here.

**Comment by moofish32** [comment]
@iliapolo - not sure if there is naming convention on these patches? But I've added a test to verify tags render correctly based on the docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-workgroup.html#aws-resource-athena-workgroup--examples. I didn't write an integration test because that's not normally here for cfn constructs, but let me know.

@udondan and @blimmer  -- https://github.com/aws/aws-cdk/pull/9085/files#diff-337b645f01ad335010f3212222427af8R23-R32 does this look right to you?

**Comment by iliapolo** [comment]
@moofish32 P.S I also opened an issue (the very first one!) with the Athena resource provider in CloudFormation: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-athena/issues/21

**Comment by udondan** [comment]
> @moofish32 P.S I also opened an issue (the very first one!) with the Athena resource provider in CloudFormation: [aws-cloudformation/aws-cloudformation-resource-providers-athena#21](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-athena/issues/21)

Is this repo/org the source of the CFN spec? I wasn't aware of this. Is there a list of als AWS orgs on GitHub?

**Comment by iliapolo** [comment]
@udondan 

> Is this repo/org the source of the CFN spec? I wasn't aware of this. Is there a list of als AWS orgs on GitHub?

Im honestly not sure. I was poking around to see if there is a repo for the spec, and came across this specific athena resource provider. Lets wait a bit for their response and we can ask them.

**Comment by moofish32** [comment]
> @moofish32 I'd feel more comfortable if we also had a small integ test that makes sure this change actually deploys well. Would this be hard to accomplish?

I debated about this too. Should be possible, but I want to highlight that we won't see an Integ change when the spec updates, until we remove the patch. Since you won't see a change in the CFN output the test won't fire. So this is sort of a one time benefit **and** somebody needs to remember to kill this patch when the spec is fixed (hardest job in software).

**Comment by moofish32** [comment]
not quite enough time tonight to do the Integ test, but hopefully by Monday.

**Comment by moofish32** [comment]
@iliapolo - can you give this another pass now?

**Pull request merged**
