### PR TITLE
fix(ecs): ecs exec cannot be enabled for ECS Anywhere (ecs.ExternalService)

### LINKED ISSUE #31181: ecs.ExternalService: enableExecuteCommand is shown as not supported (while in fact it is supported)
### Describe the bug

When creating an ExternalService, specifying the `enableExecuteCommand: true` option for the property will result in the following error when running `cdk synth`.

```
Error: Enable Execute Command options are not supported for External service
```

However, the `enableExecuteCommand` option is actually supported by the ExternalService as well, and can be manually enabled using the AWS CLI.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

When creating an ExternalService, the `enableExecuteCommand: true` option can be set for the property.

### Current Behavior

When creating an ExternalService, setting the `enableExecuteCommand: true` option to the property causes an error when executing `cdk synth`.

### Reproduction Steps

A code snippet that reproduces the problem is like as follows:
```ts
    const ecsService = new ecs.ExternalService(this, 'ExternalService', {
      serviceName: "EcsAnywhereService",
      cluster: EcsAnywhereCluster,
      taskDefinition,
      desiredCount: 1,
      enableExecuteCommand: true,
    });
```

<details><summary>Click here to show entire stack code</summary>
<p>

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as iam from "aws-cdk-lib/aws-iam";
import { CfnOutput } from 'aws-cdk-lib/core';

export class PocEcsAnywhereStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // VPC
    const vpc = new ec2.Vpc(this, "EcsAnywhereVPC", {
      ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
      natGateways: 0,
      maxAzs: 2,
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: "EcsAnywherePublic",
          subnetType: ec2.SubnetType.PUBLIC,
        },
        {
          cidrMask: 24,
          name: "EcsAnywherePrivate",
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
        }
      ]
    }
    )

    // ECS Cluster
    const EcsAnywhereCluster = new ecs.Cluster(this, "EcsAnywhereCluster", {
      vpc: vpc,
      clusterName: "EcsAnywhereCluster",

    })

    // Task role
    const taskRole = new iam.Role(this, 'TaskRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
    });
    taskRole.addToPolicy(new iam.PolicyStatement({
      actions: [
        // for ECS Exec
        'ssmmessages:CreateControlChannel',
        'ssmmessages:CreateDataChannel',
        'ssmmessages:OpenControlChannel',
        'ssmmessages:OpenDataChannel',
      ],
      resources: ['*'],
    }));

    // ECS task definition
    const taskDefinition = new ecs.ExternalTaskDefinition(this, 'ExternalTaskDefinition', {
      // executionRole: taskExecutionRole,
      taskRole: taskRole,
    });

    taskDefinition.addContainer('NginxContainer', {
      image: ecs.ContainerImage.fromRegistry(
        "public.ecr.aws/nginx/nginx:latest"
      ),
      cpu: 256,
      memoryLimitMiB: 512,
      containerName: "EcsAnywhereContainer",
      // for ECS Exec
      linuxParameters: new ecs.LinuxParameters(this, 'LinuxParameters', {
        initProcessEnabled: true,
      }),
    })

    // ECS service
    const ecsService = new ecs.ExternalService(this, 'ExternalService', {
      serviceName: "EcsAnywhereService",
      cluster: EcsAnywhereCluster,
      taskDefinition,
      desiredCount: 1,
      enableExecuteCommand: true, // for ECS Exec
    });

    // Instance role for ECS Anywhere
    const instance_iam_role = new iam.Role(this, 'EcsAnywhereInstanceRole', {
      roleName: "EcsAnywhereInstanceRole",
      assumedBy: new iam.ServicePrincipal("ssm.amazonaws.com"),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName("AmazonSSMManagedInstanceCore"),
        iam.ManagedPolicy.fromManagedPolicyArn(this, "EcsAnywhereEC2Policy", "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"),
      ]
    })

    // Output
    new CfnOutput(this, "Step1RegisterExternalInstance", {
      description: "Create an Systems Manager activation pair",
      value: `aws ssm create-activation --iam-role ${instance_iam_role.roleName}`,
      exportName: "1-RegisterExternalInstance",
    })

    const ecsAnywhereInstallScriptUrl = "https://amazon-ecs-agent.s3.amazonaws.com/ecs-anywhere-install-latest.sh"
    new CfnOutput(this, "Step2DownloadInstallationScript", {
      description: "On your VM, download installation script",
      value: `curl -o "ecs-anywhere-install.sh" "${ecsAnywhereInstallScriptUrl}" && sudo chmod +x ecs-anywhere-install.sh`,
      exportName: "2-DownloadInstallationScript",
    });

    new CfnOutput(this, "Step3ExecuteScript", {
      description: "Run installation script on VM",
      value: `sudo ./ecs-anywhere-install.sh  --region ${this.region} --cluster ${EcsAnywhereCluster.clusterName} --activation-id $ACTIVATION_ID --activation-code $ACTIVATION_CODE`,
      exportName: "3-ExecuteInstallationScript",
    });
  }
}
```

</p>
</details> 

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.154.0 (build 0fc07f3)

### Framework Version

_No response_

### Node.js Version

v20.17.0

### OS

Debian GNU/Linux 11 (bullseye)

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

Closes #31181.

### Reason for this change

In the `ecs.ExternalService` class (ECS Anywhere), the `enableExecuteCommand` property cannot be set to true, so it is not possible to enable ECS exec.
However, the [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html) states that ECS Anywhere supports ECS Exec.

> ECS Exec is supported for tasks that run on the following infrastructure:
> Linux and Windows containers on external instances (Amazon ECS Anywhere)

### Description of changes
Remove unnecessary if statement.

### Description of how you validated changes
Fix an unit test.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mazyu36** [comment]
Exemption Request: unable to execute integ test.

To complete the deployment, an external instance such as a VM is required, but I think this is very difficult in integ test. 
In a previous PR for the `ExternalService` implementation, integ test wasn't inclueded.

https://github.com/aws/aws-cdk/pull/14931#issuecomment-863403359

I tried running the integration test, but since the external instance did not exist, the deployment could not be completed, and the test could not be finished.

スクリーンショット 2024-09-09 22 15 41


During the deployment, I confirmed that the `enableExecuteCommand` property of the ExternalService was set to true using the CLI, so I would like to consider this as an alternative.

```sh
 % aws ecs describe-services --cluster aws-ecs-integ-external-exec-command-ExternalCluster14BF29C2-1WgNGhaSCe6j --service aws-ecs-integ-external-exec-command-ExternalService9AC5437C-yEbQ87UFPByK  --region us-east-1                           
{
    "services": [
        {
            "serviceArn": "arn:aws:ecs:us-east-1:...
             // omit
            "enableExecuteCommand": true
             // omit
}
```

**Review by go-to-k — CHANGES_REQUESTED** [review]
Could you change the description (`in your Ec2Service or FargateService`) in README?

> To enable the ECS Exec feature for your containers, set the boolean flag enableExecuteCommand to true in your Ec2Service or FargateService.

https://github.com/go-to-k/aws-cdk/blob/152f32d887baacecd95d4d3aea7703cb467b1771/packages/aws-cdk-lib/aws-ecs/README.md#ecs-exec-command

**Comment by mazyu36** [comment]
@go-to-k 
Thanks. I've updated.

**Review by go-to-k — APPROVED** [review]
Thank you.

**Review by GavinZZ — APPROVED** [review]

**Comment by GavinZZ** [comment]
@mergify update

**Review by GavinZZ — APPROVED** [review]

**Pull request merged**
