### PR TITLE
docs(aws-ecs): add detail to healthCheckGracePeriod doc comment

### LINKED ISSUE #16675: aws-ecs-patterns: Default value for `healthCheckGracePeriod` is not long enough, causes delays in ECS deployments
The default `healthCheckGracePeriod` of 60 seconds for `NetworkLoadBalancedEc2Service` is not long enough. It causes the hosts to potentially bounce between `initial` and `draining` states. According to the [NLB documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-register-targets.html): `It can take a few minutes for the registration process to complete and health checks to start`. The `healthCheckGraccePeriod` is used by ECS to ignore any `unhealthy` health checks from the NLB. Once a host is registered successfully the first status of the host is `unhealthy`. If registration takes more than 60 seconds, this health causes ECS to put the service into draining state and bring up a new service, causing the host to bounce between `initial` and `draining`. In practice based on registration time and default health check configurations for the NLB, 300+ seconds would be a good value for `healthCheckGracePeriod`.

### Reproduction Steps

Spin up a service using `NetworkLoadBalancedEc2Service` construct.

### What did you expect to happen?

The service to successfully deploy using ECS deploy.

### What actually happened?

As explained in the description, the service kept on bouncing between `initial` and `draining` causing deployments to take multiple hours to stabilize.

### Environment

  - **CDK CLI Version  :*1.122.0 (build ae09c16)*
  - **Framework Version:*1.23.0*
  - **Node.js Version:*v14.16.1*
  - **OS               :*OSX*
  - **Language (Version):*TypeScript (4.4.3)*

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by xykkong**
Update healthCheckGracePeriod default value from 60s to 300s
closes #16675

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by madeline-k — CHANGES_REQUESTED** [review]
Thanks for opening this PR, @xykkong! As I mentioned on #16675, we can't make this change as it would be a breaking change, and cause users relying on the default value to start seeing their deployments taking 5x longer to fail. 

However, I think we could instead add to the doc comment for each `healthCheckGracePeriod` a description for why one might want to increase the value.

**Comment by xykkong** [comment]
Thanks, @madeline-k! No problem. Do you have suggestions for the description? I was thinking of using this one.
```
The period of time, in seconds, that the Amazon ECS service scheduler ignores unhealthy
Elastic Load Balancing target health checks after a task has first started. If this value is not long enough, it would put the service into a draining state and bring up a new service, causing it to bounce between initial and draining.
```

**Comment by madeline-k** [comment]
> Thanks, @madeline-k! No problem. Do you have suggestions for the description? I was thinking of using this one.
> 
> ```
> The period of time, in seconds, that the Amazon ECS service scheduler ignores unhealthy Elastic Load Balancing target health checks after a task has first started. If this value is not long enough, it would put the service into a draining state and bring up a new service, causing it to bounce between initial and draining.
> ```

Looks good, I would just edit it a bit for clarity to:

The period of time, in seconds, that the Amazon ECS service scheduler ignores unhealthy Elastic Load Balancing target health checks after a task has first started. If your tasks take longer than this value to start, then your service may go into a draining state and bring up a new service. This may cause your service deployment to bounce between initial and draining, and never complete.

**Comment by madeline-k** [comment]
This PR has not had any updates in a long time, so I'm closing it. If the author or anyone is still interested to contribute this change (in its current state it is not merge-able), then feel free to open a new PR!

**Pull request closed without merging**
