### PR TITLE
fix(events): imported event rule ignores environment from arn

### PR DESCRIPTION
**Pull request by go-to-k**
This PR fixes the bug that `fromEventRuleArn` does not extract region and account from the arn.

- Behavior until now

```ts
    const stack = new Stack(); // <- region: us-east-1, account: 123456789012
    const imported = Rule.fromEventRuleArn(stack, 'Imported', 'arn:aws:events:us-west-2:999999999999:rule/example');

    // imported.env.region : us-east-1("Ref": "AWS::Region"). But it should be us-west-2.
    // imported.env.account : 123456789012("Ref": "AWS::AccountId"). But it should be 999999999999.
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by go-to-k** [comment]
Exemption Request, because I think unit tests could cover it.

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍

**Comment by vinayak-kukreja** [comment]
@Mergifyio update

**Review by vinayak-kukreja — APPROVED** [review]
Hey, this is great. Thank you for your contribution.

**Pull request merged**
