### PR TITLE
fix(cli): "fancy" progress reporting not disabled on all CI systems

### PR DESCRIPTION
**Pull request by andreialecu**
Fixes: #8696 #8893

Detects whether the `CI` environment variable is set and reverts output to `standard` behavior.

The fancy output was especially broken on CircleCI.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by andreialecu** [comment]
Seems that a test is needed. Any suggestions on how to test this are appreciated. The PR that implemented it had no tests https://github.com/aws/aws-cdk/pull/8165 so I'm unsure what to do here.

**Comment by skinny85** [comment]
Thanks for the vote of confidence @SomayaB , but I think @rix0rrr should look into this one 🙂

**Comment by andreialecu** [comment]
Some additional explanation:
* The `CI` env variable should be set by most CI servers, but I'm not sure if all of them properly set it.
* There is a package at https://www.npmjs.com/package/ci-info which would detect CIs that don't follow the standards properly. I didn't want to add a dependency to it though, as I wasn't sure if that was ok. If you want to use the `ci-info` package, let me know and I can update the PR.
* Alternatively, someone could run `CI=1 cdk deploy` or `export CI=1`.

**Comment by andreialecu** [comment]
The `--ci` argument is deprecated. Not sure what the process is to de-deprecate it.

This was more of a quick band aid for an urgent problem that is breaking output on some CIs.

I'm on vacation this week so I won't be able to dive too deep into it. If you can take over in the mean time, please. :)

**Comment by andreialecu** [comment]
Some information about CircleCI and TTY here: https://discuss.circleci.com/t/circleci-terminal-is-a-tty-but-term-is-not-set/9965

**Comment by robertd** [comment]
@andreialecu @rix0rrr I'm still not retaining the cfn events. Also, using `CI` env variable I loose color.
I'm using iTerm2 and zsh (oh-my-zsh).

Using `export CI=""`:

```bash
 ~/code/   master ●  export CI=""; cdk deploy
^[IsaidCloudFrontDistribution: deploying...
IsaidCloudFrontDistribution: creating CloudFormation changeset...
[██████████████████████████████████████████████████████████] (2/2)




 ✅  IsaidCloudFrontDistribution

Stack ARN:
arn:aws:cloudformation:us-west-2:123456789:stack/IsaidCloudFrontDistribution/c12044d0-e22b-11ea-858b-06675510bae4
```

Using `--ci`:

```bash
cdk deploy --ci
IsaidCloudFrontDistribution: deploying...
IsaidCloudFrontDistribution: creating CloudFormation changeset...
[██████████████████████████████████████████████████████████] (2/2)




 ✅  IsaidCloudFrontDistribution

Stack ARN:
arn:aws:cloudformation:us-west-2:123456789:stack/IsaidCloudFrontDistribution/c12044d0-e22b-11ea-858b-06675510bae4
```

**Comment by joel100** [comment]
This doesn't seem to work with 1.61.1. I'm deploying with Octopus deploy and output seems to be the same and output is still coming from StdErr.

I've tried
`
$env:CI=""
& cdk deploy --require-approval never
`
and

`& cdk deploy --ci --require-approval never`

Both times I get the following output.
`
September 3rd 2020 09:18:18Error
XXX: deploying... 
September 3rd 2020 09:18:18Error
[0%] start: Publishing 8e48b9c55f892c6662b118c86cac6064ee9d5beb743b3c550e816229dcc87f96:current 
September 3rd 2020 09:18:18Error
[100%] success: Published 8e48b9c55f892c6662b118c86cac6064ee9d5beb743b3c550e816229dcc87f96:current 
September 3rd 2020 09:18:18Error
XXX: creating CloudFormation changeset... 
September 3rd 2020 09:18:23Info
arn:aws:cloudformation:us-east-2:14785470xxxx:stack/XXX/xxxxxxxx-ede3-11ea-8a6c-xxxxxxxxxxxx 
September 3rd 2020 09:18:23Error
 Γ£à  XXX (no changes) 
September 3rd 2020 09:18:23Error
Stack ARN:
 `

What am I missing here?

**Comment by robertd** [comment]
@joel100 https://github.com/aws/aws-cdk/pull/9623 is supposed to fix this, but it didn’t land in 1.61.1. It will definitely be in 1.62.0 later this week.

**Comment by efenderbosch** [comment]
Did this ever get released?

**Pull request merged**
