### PR TITLE
chore(core): add @amzn to version reporting

### PR DESCRIPTION
**Pull request by NetaNir**
Add the amzn scope to our version reporting, owned by Amazon: https://www.npmjs.com/org/amzn

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by skinny85** [comment]
Tagging @rix0rrr as well.

**Comment by eladb** [comment]
Title is not clear- add scope to what?

**Comment by eladb** [comment]
Do we own this npm scope?

**Comment by NetaNir** [comment]
Updated the title.
Yes we own the scope https://www.npmjs.com/org/amzn

**Review by eladb — APPROVED** [review]

**Pull request merged**
