### PR TITLE
chore(pipelines): add example of the modern API with an ECS deployment

### LINKED ISSUE #17558: (aws-codepipeline-actions): Support cross-account ECS deployments with codepipeline actions
### General Issue

Cross Account & Cross Region ECS

### The Question

What is the recommended approach from CDK for cross account ECS deployments through codepipeline at present?

We have a code pipeline that needs to deploy a fargate service into multiple AWS accounts and regions. 

The few things we considered were:
1. Multi-stack approach where we have a pipeline stack with a `CodeBuildAction` that builds the actual service, pushes the container image to ECR and outputs an `imageTag`. Another `CodeBuildAction` does a `cdk synth` for the service stack and outputs its template. We then use `TagParameterContainerImage` with a `CloudFormationCreateUpdateStackAction` to deploy this template with the appropriate `imageTag`  - An ECR resource policy issue described in #15070 blocks this approach to do this cross-account.
2. Single stack with multiple stages in a code-pipeline with instances of `EcsDeployAction` that takes `account` and `region` as parameters and a `role' with appropriate cross-account and cross-region permissions - Something similar to this has been discussed in #11199 but the issue has been closed with a pull request (https://github.com/aws/aws-cdk/pull/15944/) without clarity on the final approach.

Is there any elegant way of doing this today? Probably @skinny85 who has been active in most of these issues and discussions can help us with this.

### CDK CLI Version

1.132.0

### Framework Version

_No response_

### Node.js Version

_No response_

### OS

_No response_

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tobytipton**
Provides tests as examples to #17558 for deploy ECS with the modern CDK pipeline API.

closes #17558 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by tobytipton** [comment]
Doesn't look the failed code build is related to my change.

```
aws-cdk: FAIL test/version.test.js (25.919 s)
aws-cdk:   â— Return later version when exists & skip recent re-check
aws-cdk:     thrown: "Exceeded timeout of 10000 ms for a test.
aws-cdk:     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
aws-cdk:       45 | });
aws-cdk:       46 |
aws-cdk:     > 47 | test('Return later version when exists & skip recent re-check', async () => {
aws-cdk:          | ^
aws-cdk:       48 |   const cache = new VersionCheckTTL(tmpfile(), 100);
aws-cdk:       49 |   const result = await latestVersionIfHigher('0.0.0', cache);
aws-cdk:       50 |   expect(result).not.toBeNull();
aws-cdk:       at Object.<anonymous> (test/version.test.ts:47:1)
aws-cdk:   â— Return null if version is higher than npm
aws-cdk:     thrown: "Exceeded timeout of 10000 ms for a test.
aws-cdk:     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
aws-cdk:       55 | });
aws-cdk:       56 |
aws-cdk:     > 57 | test('Return null if version is higher than npm', async () => {
aws-cdk:          | ^
aws-cdk:       58 |   const cache = new VersionCheckTTL(tmpfile(), 100);
aws-cdk:       59 |   const result = await latestVersionIfHigher('100.100.100', cache);
aws-cdk:       60 |   expect(result).toBeNull();
aws-cdk:       at Object.<anonymous> (test/version.test.ts:57:1)
aws-cdk: A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
aws-cdk: =============================== Coverage summary ===============================
```

**Comment by skinny85** [comment]
@rix0rrr you want to take this one?

**Comment by rix0rrr** [comment]
I'm sorry, but this is not how CDK pipelines is intended to work.

In CDK pipelines, we deploy all changes via CloudFormation: that includes updates to your ECS service. If you want to deploy other scenarios, you can build whatever shape of pipeline you prefer with full control by using the `aws-codepipeline` module directly.

Yes, you *can* use the custom step facility of CDK pipelines and use it as a convenient front-end over the CodePipeline module, and get pretty close to arbitrary pipelines. But this is not how we recommend you use the library, and so we will not include how-tos on how to achieve that into the upstream repository.

**Comment by shawnwang-avl** [comment]
Pulled the thread on why my ECS is not deploying to here. Using CloudFormation to deploy ECS is indeed easier than rigging your own ECS deployment step/action.

There are however 2 important things I wish CDK docs would call out:
1. ECS service must use [DockerImageAsset](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr_assets.DockerImageAsset.html)
2. Using [DockerImageAsset](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr_assets.DockerImageAsset.html) imply your source code building must be self-contained in Dockerfile. 

We previously built our own ECR image with Codebuild step and had part of the build cmds in CodeBuild step, and took significant time to refactor this. It is also not a perfect solution - we are no longer able to [retrieve Github SSH key from Secrets Manager](https://github.com/aws/aws-cdk/issues/14395) for instance.

**Pull request closed without merging**
