### PR TITLE
fix(cli): credential provider plugins cannot be used with modern synthesis

### PR DESCRIPTION
**Pull request by IainCole**
I'm not currently able to use CDK pipelines because I use a credential provider. I believe this is because the new bootstrap uses assumed roles. When assuming a role, only defaultCredentials is checked, I'm not sure if this was intentional or not because there is a comment that seems to mention this (that I will edit if this PR has any merit), but it seems odd to not allow a credential provider here.

I'm not 100% sure why I had to change the account ID in the tests, but I did and all the tests seem to still pass.

### CODE REVIEW

**Comment by rix0rrr** [comment]
Wait, how do you intend to use this?

There is an assumed role, sure. Your credential provider is going to give you credentials to use to assume the role, is that right?

Our intended use of this feature was that you would use your default (user/developer) credentials to account A to federate into another account B (assuming that account B had given you permissions to do so by using `--trust`).

Can you describe your use case in more detail? What kind of credential provider are you using?

**Review by rix0rrr — CHANGES_REQUESTED** [review]
If we agree that this is a useful change, you're going to have to add a test to assert that the credentials returned by the provider will be used to assume the role.

Changing the call signatures of the function in existing tests does not constitute sufficient testing, we didn't test the new functionality yet :).

**Comment by IainCole** [comment]
Yeah, I want the credentials to come from a credential provider. I work for a large IaaS company and have a lot of AWS accounts I need to be using with CDK, I also don't want to have loads of creds on my machine if at all possible. So I use a credential provider to authenticate me and retrieve credentials for use in CDK which works great, but I can't use any of the new bootstrap assumeRole stuff because it can't get the credentials from the plugin, happy to add tests and stuff if we think this is a useful change.

**Comment by rix0rrr** [comment]
Okay I do see the use case here. Feeling slightly uneasy about the change (as there are now 2 federation mechanisms fighting), but given that we don't really have anything better in place and you need to be unblocked, I'll go ahead and okay it after you add that test.

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
