### PR TITLE
feat(appsync): schema validation after synthesis

### LINKED ISSUE #14022: Validate AppSync Code-First GraphQL Schema before deploying
I am using the code-first approach to constructing my GraphQL schema with `@aws-cdk/aws-appsync`. I have noticed that the schemas errors are really vague when pushing new schema changes via CDK.

E.G the last error I got was:
`Schema Creation Status is FAILED with details: Failed to parse schema document - ensure it's a valid SDL-formatted document.`

I would love to be able to validate the schema before deployment or even print / save the schema to file as a test run. Its sometimes hard to spot mistakes when you are composing your schema using multiple files.

### Use Case

We use AWS CDK and App Sync to build our GraphQL API. We need to be able to write the GraphQL schema reliably and test it before deploys.

### Current Workaround

Currently, I am doing a `console.log()` of the schema during deployment to try and spot issues.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by BryanPan342**
Perform semantic schema validation before deploying CDK app.

Fixes #14022

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by BryanPan342** [comment]
@hirenumradia @MrArnoldPalmer tagging both of you to have our conversation here!

I have been running into two issues:

1. Originally I wanted to run the validation through CDK's methodology with the `this.node.addValidation()` but I have found that the schema's lazy string producer runs **after** the `addValidation` so I have thus run the validation after the producer... Not a big fan of this implementation but I would love some guidance on this front @MrArnoldPalmer 

2. The validation fails to resolve when run against appsync specific directives and scalars (@aws_iam_key etc.). My solution for this is simply to inject the declarations of each of the custom appsync rules into the validation. I would love to have someone on the AppSync team to provide some guidance on how AppSync actually runs its own validation, that way I dont add/miss anything.

**Comment by MrArnoldPalmer** [comment]
hmm @BryanPan342 lemme know what you think about this.

What if the function we pass in to `Lazy` that returns to schema does a bunch of work before returning it,

Specifically:
1. Computes the schema that we use for resolution, IE without all of the appsync specific directives.
2. If validation passes, add appsync directives and return the string
3. If fails, throws an error with a nice message. Can we throw and error or does CDK get mad 😠 ?

**Comment by BryanPan342** [comment]
> 1. Computes the schema that we use for resolution, IE without all of the appsync specific directives.
> 2. If validation passes, add appsync directives and return the string
> 3. If fails, throws an error with a nice message. Can we throw and error or does CDK get mad 😠 ?

Wooo 😅  great cuz that's how I am doing it currently.

We can throw an error! Unfortunately in doing some more preparation for this, I realized that our current directive implementation needs a bit more work haha.

**Comment by BryanPan342** [comment]
It's going to be a huge PR @MrArnoldPalmer.. we have to essentially change every unit test because I didn't write a root query for each of them..

**Comment by MrArnoldPalmer** [comment]
@BryanPan342

> To run validation, all schemas must come with a root query type

Can we just create a mock `GraphqlApiTest` that defines a root query by default and replace the `new GraphQlApi` in all our unit tests with that? That would be the easiest way forward but kinda hides some stuff from test bodies.

2+3 both make sense to do before continuing. Lemme know if you need anything for these.

**Comment by BryanPan342** [comment]
> Can we just create a mock `GraphqlApiTest` that defines a root query by default and replace the `new GraphQlApi`.

That's pretty clever actually. I'm thinking about putting it in private and creating a function that injects the schema definition stuff to make the `expect` clauses to be much cleaner.

Do you mind if I actually make this a PR first? 

I'm looking at a roadmap that looks like the following: 

1.  PR for GraphqlApiTest
2. PR for custom directives
3. PR for input type correction
4. PR for Schema Validation

Does that look right?

**Comment by MrArnoldPalmer** [comment]
That looks right to me 👍🏻

**Comment by TheRealAmazonKendra** [comment]
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

**Pull request closed without merging**
