### PR TITLE
chore: shrinkwrap CLI and cdk-assets tools

### PR DESCRIPTION
**Pull request by rix0rrr**
### Commit Message
chore: shrinkwrap CLI and cdk-assets tools

The CLI and the `cdk-assets` tool present a security risk as
they're being downloaded from NPM, as any of their dependencies
can be compromised at any time and downloaded to any user's
machine without a lockfile.

Generate a lockfile (`npm-shrinkwrap.json`) that will be respected
by NPM upon install.
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
> Also - note that this addresses the risk ONLY for users installing via `npm`, as for examples `yarn` does not support or honor shrink-wrap files... 🤷🏻‍♂️

I'm aware. The primary motivation for this is CI/CD though, which is guaranteed to use NPM.

**Comment by rix0rrr** [comment]
> actually test those shrink-wrap files are valid with several versions of `npm`?

I'm open to it, but it's a little awkward to test. Got any ideas?

**Comment by rix0rrr** [comment]
I guess the integ tests will test it at least with the version of NPM we are using there, as it will `npm install` the CLI from Verdaccio.

**Comment by eladb** [comment]
Is this respected by yarn? wondering if we need more intensive shrinkwrapping (vendoring)

**Comment by RomainMuller** [comment]
Vendoring-in can introduce licensing difficulties (but IANAL; and I don't think it's an obvious show-stopper either).

With respects to testing with several versions of npm... It's possible to replace the current npm version by... `npm install`-ing another version... Maybe this is the way? I agree this is kinda awkward though, ideally we'd basically have a variety of Docker images with select versions of `npm` known to be of interest (typically, the default one shipping with node 10, 12 and 13?)

**Comment by rix0rrr** [comment]
It is for sure not respected by `yarn`, but I'm not sure that is a strict requirement.

* For the CI/CD project, we will be generating calls to `npm install` in the SelfMutate and PublishAsset stages, so we control the tool and we will use the tool that DOES respect the shrinkwrapping.
* For enterprises/security-sensitive customers, we can recommend they install through NPM.
* People that still insist on using `yarn` despite our recommendations know what they are getting into (and potentially have their own mitigation strategies).

As for statically linking all transitive dependencies, yes there are licensing implications. We have to check all licenses and check that we are allowed to distribute them, and also include copyright notices for all packages included in our distribution.

**Comment by rix0rrr** [comment]
Can we continue the discussion on this?

What would you like to see here?

**Pull request merged**
