### PR TITLE
feat(ecs-patterns): Add DeploymentController option to Fargate services

### LINKED ISSUE #10971: [ecs-patterns] Blue-green deployments with ApplicationLoadBalancedFargateService
In order to support blue-green deployments with `ApplicationLoadBalancedFargateService` I need to be able to change the deployment controller type of the provisioned Fargate service.

### Use Case

We have been doing blue-green deployments for the past couple of month using a modified version of `ApplicationLoadBalancedFargateService` construct. We have extended it to support changing of the deployment controller type to `CODE_DEPLOY` so we can support blue-green deployments. 

Our workflow is the following:
1. A PR is approved and merged to master.
1. Docker image is built, tagged and pushed to AWS ECR.
1. A blue-green deployment is triggered with `ecs deploy` using [this script](https://gist.github.com/ligaz/7ade15a84a4c66b90acf892a494bf7a4). The script reads its inputs from the outputs of the specified stack provisioned with AWS CDK.

In order to support this we need to be able to change the deployment controller of the Fargate service.

### Proposed Solution

Add option to change the deployment controller of ApplicationLoadBalancedFargateService. Implemented in #10452

### PR DESCRIPTION
**Pull request by ligaz**
This change adds the option to set the `DeploymentController` on `ApplicationLoadBalanced`,
`NetworkLoadBalanced` and `QueueProcessing` ECS Services (both EC2 and Fargate). `MultipleTargetGroups` services are not updated because this option might not be applicable for them - one service might be using the default deployment
controller while others might use `CODE_DEPLOY` or `EXTERNAL`.

By default if this options is not passed it will use the default one from the respective Service construct  which
is `ECS`'s rolling updates.

Related to aws/containers-roadmap#130

Closes #10971.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by iamhopaul123** [comment]
Hello @ligaz, thank you so much for contributing! Have one question tho: why are we only adding deployment controller option to fargate service?

**Comment by ligaz** [comment]
@iamhopaul123 This is where I need it in my current project. Do you feel I should add it in some other place as well?

**Comment by iamhopaul123** [comment]
Gotcha! It would be best if you could add for EC2 but it's ok if you just want to do it for Fargate. In addition, have you tested it locally on your project to see if this works as we expect?

**Comment by ligaz** [comment]
Yes, I did. We have two production stacks that are running with those changes. Do you think I should add more test cases?

**Review by iamhopaul123 — APPROVED** [review]
That'll be good enough. Approved. Thank you for your contribution!

**Comment by ligaz** [comment]
@iamhopaul123 As there are conflicting files with the latest changes in the target branch should I do anything specific in order to get this one merged?

**Comment by iamhopaul123** [comment]
No i think just resolve the conflict and it should be good! FYI [ecs-extension](https://github.com/nathanpeck/aws-cdk-rfcs/blob/master/text/0219-ecs-service-extensions.md) is now available, which provides an alternative way for users to extend their ECS services.

**Comment by ligaz** [comment]
👍 Thanks for the ECS Service Extensions RFC pointer. Will definitely subscribe and follow its development.

**Comment by ligaz** [comment]
@iamhopaul123 Do you have an idea when this one will get merged?

**Comment by iamhopaul123** [comment]
@ligaz Could you resolve those conflicts?

**Comment by ligaz** [comment]
@@iamhopaul123 ✅ Done.

**Comment by iamhopaul123** [comment]
Hello @ligaz, after discussing with the team, we have the following suggestion about supporting extra deployment controller: 

Since we want ecs patterns to be more opinionated with high abstraction level than normal L2 construct like `FargateService`, we'd like to see it to support a more specific use case instead of a generic one. For example, blue green deployment requires more configuration besides specifying in the task definition.

Thus, could you be more specific about the use case you are trying to address and cut an issue? After that we can discuss how we want to let the patterns to support it. Thank you for your efforts though and really sorry I didn't make this clear at the beginning. Hope you could understand!

**Comment by ligaz** [comment]
Sure @iamhopaul123 . Here is the issue: #10971.

**Comment by ligaz** [comment]
@iamhopaul123 @MrArnoldPalmer Do I need to elaborate more on my use case?

**Comment by iamhopaul123** [comment]
@ligaz Yes please! That'll be great.

**Comment by rayrapetyan** [comment]
+1 to merge this PR ASAP, struggling with the same issue.

**Comment by ligaz** [comment]
@iamhopaul123 Which part from #10971 needs more elaboration?

**Comment by ligaz** [comment]
@rayrapetyan You can always copy the code from this ECS pattern and modify it. This is exactly what I have done in my projects.

**Comment by rayrapetyan** [comment]
@ligaz, thanks I did exactly same yesterday, I agree it gives much more flexibility.

**Comment by piradeepk** [comment]
@ligaz thanks for adding this feature flag! Would you mind implementing this to the Ec2 patterns as well (we'd like to maintain feature parity between the two launch types if possible)?

**Comment by ligaz** [comment]
@piradeepk Can you check the updated PR? It adds support to the Ec2 patterns as well.

**Comment by ligaz** [comment]
@iamhopaul123 Can you help me push this one forward?

**Comment by iamhopaul123** [comment]
@piradeepk any thought on this?

**Comment by piradeepk** [comment]
@ligaz first off I wanted to say thanks for taking this on! Are there are other properties/configurations that we would need defined to be used with specific deployment controllers?

**Comment by ligaz** [comment]
@piradeepk Nope. My current needs are just to change the deployment controller type. As far as I know this is the only option for the [Deployment Controller](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentcontroller.html).

**Review by SoManyHs — APPROVED** [review]

**Pull request merged**
