### PR TITLE
refactor: readonly struct properties and hide internals

### PR DESCRIPTION
**Pull request by eladb**
This change upgrades the repo to jsii 0.8.0 which requires that all struct types (data interfaces like our "Props" interfaces) will be marked `readonly` in order to ensure they can be passed by-value.

The new jsii version also hides all members marked as `@internal` which means that those APIs will not be available from outside the framework.

Fixes awslabs/cdk-ops#321

BREAKING CHANGE: `stack._toCloudFormation` method is now unavailable and is replaced by `@aws-cdk/assert.SynthUtils.toCloudFormation(stack)`.

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by hoegertn** [comment]
What is the new/correct way to modify Props after creating the object?

I use this currently to set fields conditionally after creating the object with my shared config:
e.g. https://github.com/taimos/cdk-constructs/blob/master/lib/alexa/skill.ts#L57

**Comment by eladb** [comment]
@hoegertn not sure what this line points at :-)

**Comment by hoegertn** [comment]
Sorry, I changed it already. Here is the link to the revision: https://github.com/taimos/cdk-constructs/blob/e2279f2bcc004374dcbba5c14be61dd78ab30158/lib/alexa/skill.ts#L56

I changed it in master, but I am not really happy with the code.

**Comment by yueyingcui** [comment]
@eladb since the attributes are readonly now, could you share a recommended way to modify/dynamically create Props objects?

**Comment by eladb** [comment]
See https://github.com/awslabs/aws-cdk/pull/2372

**Comment by yueyingcui** [comment]
Thanks!

**Pull request merged**
