### PR TITLE
feat(aws-applicationautoscaling): enabling autoscaling for ElastiCache Redis cluster

### PR DESCRIPTION
**Pull request by astrohome**
Following the recently released support for autoscaling in ElastiCache Redis cluster, I'd like to use CDK in order to manage the infrastructure. The only required change is to introduce a new enum value for 'elasticache' key ([cloudformation doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalabletarget.html#cfn-applicationautoscaling-scalabletarget-servicenamespace)), however to improve dev experience I've introduced three new `PredefinedMetricType` following [cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationautoscaling-scalingpolicy-predefinedmetricspecification.html#cfn-applicationautoscaling-scalingpolicy-predefinedmetricspecification-predefinedmetrictype)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — DISMISSED** [review]

**Review by comcalvi — CHANGES_REQUESTED** [review]
Could you incorporate the requested changes to the README to satisfy the linter?

**Review by comcalvi — DISMISSED** [review]

**Comment by astrohome** [comment]
I'm sorry, just pushed an example to the README file before seeing your comment. Let me know if that's okay.

**Comment by comcalvi** [comment]
@astrohome More examples are good! Just add the newline at the end of the README file to please the linter.

**Comment by astrohome** [comment]
Done!

**Review by comcalvi — APPROVED** [review]

**Pull request merged**
