### PR TITLE
fix(apigateway): validation for path parts does not allow creation of resources beginning with dollar sign

### PR DESCRIPTION
**Pull request by lawofcycles**
This PR adjusts the validation rules for path parts in resources created using the APIGateway library to allow the use of dollar mark in pathParts, as requested in https://github.com/aws/aws-cdk/issues/27083. This enables the creation of resources with paths such as $test(from the reproduction steps in the related issue).

An existing resource unit test ('url for a resource') has been updated to ensure that a dollar mark in a pathPart does not throw an error and properly reflects in the output of RestApi.urlForPath. The integration test integ.restapi has also been updated, wherein the appliances resource now has a path of $appliances:all instead of appliances:all.

Closes https://github.com/aws/aws-cdk/issues/27083.

#### All Submissions:
- [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)
#### Adding new Unconventional Dependencies:
- [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)
#### New Features
- [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
  - [x] Did you use yarn integ to deploy the infrastructure and generate the snapshot (i.e. yarn integ without --dry-run)?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license

### CODE REVIEW

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍
Can you please update the title to describe the bug as per [guidelines](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request)?
Suggestion: `fix(apigateway): validation for path parts does not allow creation of resources with dollar sign`.

**Comment by lawofcycles** [comment]
I misunderstood guideline that name of PR should be same to name of issue.
I changed the title.

**Review by scanlonp — DISMISSED** [review]
Looks good, thanks!

**Comment by lawofcycles** [comment]
@scanlonp 
According to workflow, it seems some checks were not successful
> Queue: Embarked in merge queue — This pull request cannot be embarked for merge
Do I need further action to solve it?

**Review by scanlonp — APPROVED** [review]

**Comment by scanlonp** [comment]
@mergifyio update

**Pull request merged**
