### PR TITLE
fix(core): AssetStaging - make skip flag use stack id instead of stack name 

### PR DESCRIPTION
**Pull request by mpuhacz**
Fixes: #16713

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mpuhacz** [comment]
> ### AWS CodeBuild CI Report
> * CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
> * Commit ID: [0934656](https://github.com/aws/aws-cdk/commit/0934656672820c62b9ef0e1f02ec29952097a81f)
> * Result: FAILED
> * [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4354c06b-fd9e-4dd9-b237-d42c3cb48669%2Fbuild.log) (available for 30 days)
> 
> _Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)_

A not related test is failing. Can we restart the test job?
```
@aws-cdk/custom-resources: FAIL test/aws-custom-resource/aws-custom-resource-provider.test.js (196.634 s)
@aws-cdk/custom-resources:   â— installs the latest SDK
@aws-cdk/custom-resources:     : Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Error:
@aws-cdk/custom-resources:       420 | });
@aws-cdk/custom-resources:       421 |
@aws-cdk/custom-resources:     > 422 | test('installs the latest SDK', async () => {
@aws-cdk/custom-resources:           | ^
@aws-cdk/custom-resources:       423 |   const tmpPath = '/tmp/node_modules/aws-sdk';
@aws-cdk/custom-resources:       424 |
@aws-cdk/custom-resources:       425 |   // Symlink to normal SDK to be able to call AWS.setSDK()
@aws-cdk/custom-resources:       at new Spec (../../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
@aws-cdk/custom-resources:       at Object.<anonymous> (test/aws-custom-resource/aws-custom-resource-provider.test.ts:422:1)
@aws-cdk/custom-resources: =============================== Coverage summary ===============================
@aws-cdk/custom-resources: Statements   : 93.55% ( 334/357 )
@aws-cdk/custom-resources: Branches     : 91.98% ( 218/237 )
@aws-cdk/custom-resources: Functions    : 94.91% ( 56/59 )
@aws-cdk/custom-resources: Lines        : 93.44% ( 328/351 )
@aws-cdk/custom-resources: ================================================================================
@aws-cdk/custom-resources: Test Suites: 1 failed, 4 passed, 5 total
```

**Comment by rix0rrr** [comment]
Thanks, good catch.

I'm curious how you validated this change, and I'd also like to see a test added that shows the difference.

**Comment by mpuhacz** [comment]
@rix0rrr 
I was testing the change manually using the code from issue #16713 (see, Reproduction Steps). 
Happy to add tests. I didn't find one for `asset-staging.ts`, would creating a new one in `aws-cdk/core/test/asset-staging.test.ts` be alright?

**Comment by rix0rrr** [comment]
> would creating a new one in `aws-cdk/core/test/asset-staging.test.ts` be alright?

That seems excellent, thanks

**Pull request closed without merging**
