### PR TITLE
feat(bootstrap): ECR `ScanOnPush` is now enabled by default

### PR DESCRIPTION
**Pull request by PatMyron**
[`AWS::ECR::Repository.ImageScanningConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagescanningconfiguration)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — APPROVED** [review]
Did you just thumbs-up your own PR 🤓

**Comment by PatMyron** [comment]
@rix0rrr figured triaging sorts by reactions 😛

**Comment by PatMyron** [comment]
@Jerry-AWS unsure about maintaining bootstrap template history in the CDK guide, but heads up just in case

**Comment by Jerry-AWS** [comment]
thanks @PatMyron. I'm not currently tracking that in the Dev Guide, but maybe it'd be a good idea to add a link directly to the template's GitHub history from there. What do you think?

**Comment by PatMyron** [comment]
@Jerry-AWS agreed on linking the template source itself since the template history tables at the bottom get outdated otherwise:
https://docs.aws.amazon.com/cdk/v1/guide/bootstrapping.html#bootstrapping-contract
https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-contract

**Pull request merged**
