### PR TITLE
feat(wafv2): add WebAcl L2 Construct

### PR DESCRIPTION
**Pull request by yamatatsu**
This PR is implementation for https://github.com/aws/aws-cdk/issues/17749.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
Hey @kimisme9386 are you able to take a look?

**Comment by kimisme9386** [comment]
@yamatatsu 
I have some questions and suggestions as below:
1. According to your design in issue #17749, it seems to me that it doesn't implement `wafv2Statement` class ? I think it is a great idea for using the WebAcl L2 Construct because it has more expressive for this L2 construct.

2. In my opinion, It's a good way if the name property within `wafv2Statement.ManagedRuleGroupStatement` use enum and constant instead of string, such as `wafv2Statement.AWS_MANAGED_RULES_COMMON_RULESET`, `AWS_MANAGED_RULES_ADMIN_PROTECTION_RULESET` , `wafv2Statement.AWS_MANAGED_RULES_KNOWN_BADINPUTS_RULESET`, etc..., It's total 12 rules in this [docs](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html).

3.  Does you considerate support [AWS WAF lable](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-labels.html) for this L2 construct ? It's also a good feature.

**Comment by yamatatsu** [comment]
@kimisme9386 
> 1.
I'm assuming Statement classes! It will be implemented with `IStatement` and classes each statements, as `aws-events-targets` and `aws-sns-subscriptions` (I haven't thought yet which to create another package or not).

> 2.
I think so too! Users will be able to choice from candidates with code documentations and get detail from `@see` links. It will be helpful. I think.

> 3.
I have not design that feature yet😵. I described WebAcl CFn template as this, and I thought It is better to design core of WebAcl at first. I beleave L2 `WebAcl` Class I designed can be base of that feature😉.

**Comment by jacido** [comment]
Is there another link this is being worked on?

**Pull request closed without merging**
