### PR TITLE
chore(route53-patterns): block public access in redirect bucket

### PR DESCRIPTION
**Pull request by jogold**
The bucket acts only as a website redirect, it is supposed to remain empty,
no objects will ever be served, so we should block public access.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@hoegertn do you agree?

**Comment by hoegertn** [comment]
I fully agree if you tested this. I sometimes had issues with these blocks that they disable serving functionality.

But if it works I would love to add more access blocks.

**Comment by jogold** [comment]
> fully agree if you tested this.

Yes this has been tested, works properly.

**Review by shivlaks — APPROVED** [review]
good call

**Pull request merged**
