### PR TITLE
docs(s3): add example to s3 bucket documentation

### LINKED ISSUE #20374: aws-s3: wrong code example for Bucket construct
### Describe the issue

The code example published in S3 module documentation is wrong and pointing to CodeBuild Project construct example

### Links

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-s3.Bucket.html
https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_s3/Bucket.html

### PR DESCRIPTION
**Pull request by daschaa**
Fixes #20374

Adds an example to the S3 `Bucket` docstring.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by daschaa** [comment]
@peterwoodworth I have now added a pull request with an example, but [as we discussed](https://github.com/aws/aws-cdk/issues/20374#issuecomment-1179816906), I don't know how it renders it 😅 It would be nice to get some feedback from you how it looks like.
And if you might have suggestions for more parameters for the example, I'd be happy too 😄 I think just the bucket name might be a bit too less?

Thanks in advance! ❤️

**Review by peterwoodworth — CHANGES_REQUESTED** [review]
This is how it's supposed to be formatted! good job 🙂 

It appears that there's extra spaces / indentation, could you make sure that the start of the example `new s3.Bucket...` is the same indentation as the @ example line?

As for props - I'd request that we do not specify the `bucketName`. We actually recommend against this as best practice, see [here](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_physical_names)

I honestly wouldn't mind if we don't have props, but take a look through the overview page. Anything related to encryption, blocking public access, bucket deletion, etc would be great to have here. 

Also be sure to put a semicolon at the end of the bucket declaration!

**Comment by daschaa** [comment]
@peterwoodworth Thank you for your detailed answers! I have added the requested changes. I hope it's ok like that, otherwise I would appreciate your feedback :)

**Comment by TheRealAmazonKendra** [comment]
Oops. Looks like the spacing with the imports got a bit messed up with this revision.

**Comment by daschaa** [comment]
@TheRealAmazonKendra 🤦🏼 I don't know how this happened. I fixed it with `yarn lint --fix` :) I hope its ok now :)

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks good! Thanks for the change!

**Pull request merged**
