### PR TITLE
fix(ecs): redirect config should honor openListener flag

### PR DESCRIPTION
**Pull request by hoegertn**
The redirectHTTP feature should honor the settings of the openListener option.
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hoegertn** [comment]
@eladb is fixing a bug still a breaking change? This changes the behavior of the security group when using redirectHTTP and openListener but imho it was broken before.

**Comment by hoegertn** [comment]
I will fix the test asap. Gitpod pre-built did not work so I could not run it while creating the PR

**Comment by MrArnoldPalmer** [comment]
@hoegertn Fixing a bug isn't considered a breaking change. This PR is kinda a grey area though since the redirectHTTP feature didn't explicitly define what this behavior should be. We could I guess add another `redirectOpen` or some other prop that explicitly defines if the redirect listener is public to avoid breakage, but I agree that this PR is the right solution.

Since users that are passing `false` for `openListener` are the ones affected by this, the change in behavior they will see doesn't seem to actually "break" anything. If a user attempts to access the http endpoint from outside the VPC, whereas before they would be redirected the https endpoint that they are unable to access, they will just be unable to access before the redirect.

@aws/aws-ecs-devx opinions?

**Comment by iamhopaul123** [comment]
> Since users that are passing false for openListener are the ones affected by this, the change in behavior they will see doesn't seem to actually "break" anything.

Agree it might not break any real thing, but i was wondering what use cases are we trying to address for this PR? Could you provide some use cases why we want to make this change @hoegertn?

**Comment by hoegertn** [comment]
Currently if you set openListener to `false` it will not open up the security group to the world. If you activate `redirectHttp` it will add another SecurityGroup entry for the port 80 and it will not honor the settings of `openListener`. 

So when you want to restrict the Listener it will still open up the port 80. While this is not a security issue as it will only redirect to a closed port this still comes up as a finding for companies that do not allow unrestricted security groups.

**Comment by iamhopaul123** [comment]
@hoegertn thank you for your explanation. It totally makes sense to me! Let's ship it.

**Review by iamhopaul123 — APPROVED** [review]

**Pull request merged**
