### PR TITLE
feat(lambda): dotnet6 runtime

### PR DESCRIPTION
**Pull request by PatMyron**
fix https://github.com/aws/aws-lambda-dotnet/issues/1088, fix https://github.com/aws/aws-cdk/issues/19148
https://aws.amazon.com/about-aws/whats-new/2022/02/aws-lambda-adds-support-net6/
https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by Roman-Blinkov — APPROVED** [review]
Thank you man.

**Comment by peterwoodworth** [comment]
@PatMyron is this ready on CloudFormation's side of things?
The runtime isn't listed as an accepted runtime yet in the docs
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime

**Comment by PatMyron** [comment]
@peterwoodworth [CloudFormation resource provider schema](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html) for `AWS::Lambda::Function` doesn't have `Runtime` constraints

**Comment by drewdelano** [comment]
@peterwoodworth this is a fairly recent change, so the docs are probably out of date:

https://github.com/aws/aws-lambda-dotnet/issues/889#issuecomment-1050091711

**Review by kaizen3031593 — APPROVED** [review]
Thanks for this!

**Review by peterwoodworth — APPROVED** [review]

**Pull request merged**
