### PR TITLE
docs(custom-resource): add example for AwsApiCall

### PR DESCRIPTION
**Pull request by ymhiroki**
There weren't any examples for `AwsApiCall` in the document other than the Overview.
This commit adds examples to the document of  `AwsApiCall` and it helps users understand the usage.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — APPROVED** [review]

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Hey, thanks for this! 

I was confused about how a user chooses between v2 and v3 on the custom resource, but I see from the README that it's done by registering a special fact. That information is missing here, which might be a bit confusing.

But I think we might change something about this construct anyway, so let's hold off on this change a little until we've settled on how it works.

**Comment by rix0rrr** [comment]
Okay yeah, the v3 documentation is out of date. See the following PR: https://github.com/aws/aws-cdk/pull/26631

**Comment by ymhiroki** [comment]
@rix0rrr Thanks for your comments!
I updated the PR to use only SDKv3. How about it?

**Comment by rix0rrr** [comment]
> I updated the PR to use only SDKv3. How about it?

I meant the other way around. It should all be only SDKv2-style strings.

**Review by rix0rrr — DISMISSED** [review]
I meant the other way around. It should all be only SDKv2-style strings.

**Comment by ymhiroki** [comment]
I see. I fixed it.

**Review by rix0rrr — COMMENTED** [review]
Thanks!

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
