### PR TITLE
fix(aws-iam): prevent adding duplicate resources and actions

### LINKED ISSUE #13611: (aws-iam): `addResources` should filter out duplicate resources
The stacks we're creating are somewhat complex, and in our case it's possible that at one point a call to `policy.addResources()` is made with the same resources as a previous call. 

### Reproduction Steps

```ts
import * as cdk from "@aws-cdk/core";
import * as iam from "@aws-cdk/aws-iam";
import * as ecr from "@aws-cdk/aws-ecr";
import * as ecs from "@aws-cdk/aws-ecs";

export class CIStack extends cdk.Stack {
  iamGroupCIRunner: iam.Group;

  ecrUploadPolicy = new iam.PolicyStatement({
    actions: [
      "ecr:InitiateLayerUpload",
      "ecr:UploadLayerPart",
      "ecr:CompleteLayerUpload",
      "ecr:BatchCheckLayerAvailability",
      "ecr:PutImage",
    ],
  });

  ecsUpdatePolicy = new iam.PolicyStatement({
    actions: ["ecs:DescribeService", "ecs:UpdateService"],
  });

  stackPolicy = new iam.PolicyStatement({
    effect: iam.Effect.ALLOW,
    actions: ["cloudformation:DescribeStacks"],
  });

  constructor(scope: cdk.App, id: string, props: cdk.StackProps) {
    super(scope, id, props);

    this.iamGroupCIRunner = new iam.Group(this, `CIRunner`);


    this.initEcr();
    this.initEcs();
  }

  private initEcr() {
    this.iamGroupCIRunner.addToPolicy(
      new iam.PolicyStatement({
        resources: ["*"],
        actions: ["ecr:GetAuthorizationToken"],
      }),
    );

    this.iamGroupCIRunner.addToPolicy(this.ecrUploadPolicy);
  }

  private initEcs() {
    this.iamGroupCIRunner.addToPolicy(this.ecsUpdatePolicy);

    this.iamGroupCIRunner.addToPolicy(
      new iam.PolicyStatement({
        resources: ["*"],
        actions: [
          "ecs:DescribeTaskDefinition",
          "ecs:RegisterTaskDefinition",
          "ecs:RunTask",
          "ecs:StartTask",
        ],
      }),
    );
  }

  public setupEcrEcs({
    repository,
    service,
    taskDefinition,
    stack,
  }: {
    repository: ecr.IRepository;
    service: ecs.Ec2Service;
    taskDefinition: ecs.TaskDefinition;
    stack: cdk.Stack;
    }) {
    this.ecrUploadPolicy.addResources(repository.repositoryArn);
    this.ecsUpdatePolicy.addResources(service.serviceArn);
    this.stackPolicy.addResources(stack.stackId);

    taskDefinition.taskRole.grantPassRole(this.iamGroupCIRunner);
    taskDefinition.executionRole?.grantPassRole(this.iamGroupCIRunner);
  }
}
```

Other stacks then call `ciStack.setupEcrEcs(...)`. However, the `repository` being passed can be identical for some of them, and it results in this changeset:

```
│ + │ arn:${AWS::Partition}:ecr:eu-west-1:...:repos │ Allow  │ ecr:BatchCheckLayerAvailability                        │ AWS:${CIRunner}    │                                                          │
│   │ itory/aws-cdk/assets                                   │        │ ecr:CompleteLayerUpload                                │                    │                                                          │
│   │ arn:${AWS::Partition}:ecr:eu-west-1:...:repos │        │ ecr:InitiateLayerUpload                                │                    │                                                          │
│   │ itory/aws-cdk/assets                                   │        │ ecr:PutImage                                           │                    │                                                          │
│   │                                                        │        │ ecr:UploadLayerPart                                    │                    │                                                          │
```

Notice how the exact same resource is added twice.

### What did you expect to happen?

Duplicate values should probably be omitted. Perhaps a `Set` instead of an array should be used internally?

### What actually happened?

Duplicate resources added, see above.

### Environment

  - **CDK CLI Version  :** 1.93.0
  - **Framework Version:** 1.93.0

### Other

Alternatively, a way to check whether the policy already has a resource added to it would provide a workaround for this.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by andreialecu**
fixes #13611

cc @rix0rrr 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by andreialecu** [comment]
Note that the issue that this PR fixes was also making us run into https://github.com/aws/aws-cdk/issues/11562

It resulted in a lot of code in the stacks to try to prevent it (keeping track of which resources were already added and not add them again).

**Comment by andreialecu** [comment]
It seems the tests failed because there's a redundant `glue:BatchDeletePartition` included in both of these arrays:

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-glue/lib/table.ts#L402-L419

Is it right that `readPermissions` includes `'glue:BatchDeletePartition'` though? That seems weird to include for reading.

**Comment by andreialecu** [comment]
Bump.

**Comment by rix0rrr** [comment]
Good point on the Glue permissions. Tagging in @BenChaimberg who now proudly owns Glue :). Ben, do you know whether this is intentional and necessary, or an oversight?

**Comment by BenChaimberg** [comment]
I have not confirmed whether these permissions are unnecessary, but I don't see anything wrong with updating the tests with the deduplicated permissions in the meantime. What do you think @rix0rrr ?

**Review by rix0rrr — DISMISSED** [review]
> I don't see anything wrong with updating the tests with the deduplicated permissions in the meantime. What do you think @rix0rrr ?

That is fair.

So I guess, update the tests (leaving current behavior as-is)

**Comment by BenChaimberg** [comment]
FYI: opened #15116

**Comment by andreialecu** [comment]
> So I guess, update the tests (leaving current behavior as-is)

@rix0rrr done, tests pass now.

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
