### PR TITLE
fix(cli): HTTP timeout is too low for some asset uploads

### LINKED ISSUE #13183: Add option to increase/disable assets upload timeout
I'm trying to add a Lambda Layer via CDK but it looks like the upload fails for some internal timeout:

```
[0%] start: Publishing fdd5d5d7901fc2a1ffa2e30c60f85e42ca1b7f8e4819d773ce8c463987e0aa62:current
[20%] fail: Connection timed out after 120000ms
[20%] start: Publishing e0292dd2f039507b0062983f02625a7ec6c602540fd9e59c9c97fc4c9ce62c73:current
[40%] success: Published e0292dd2f039507b0062983f02625a7ec6c602540fd9e59c9c97fc4c9ce62c73:current
[40%] start: Publishing 82d67eb5056b8bbfb2aea167a350a1c9977d850cefab5036a0fc8e46d33b6faa:current
[60%] success: Published 82d67eb5056b8bbfb2aea167a350a1c9977d850cefab5036a0fc8e46d33b6faa:current
[60%] start: Publishing ae727bd9c2d762603829726cc74490c409b557fc1d152e6be63b5d8bb8120355:current
[80%] success: Published ae727bd9c2d762603829726cc74490c409b557fc1d152e6be63b5d8bb8120355:current
[80%] start: Publishing 67b7823b74bc135986aa72f889d6a8da058d0c4a20cbc2dfc6f78995fdd2fc24:current
[100%] success: Published 67b7823b74bc135986aa72f889d6a8da058d0c4a20cbc2dfc6f78995fdd2fc24:current

 ❌  pocket-to-kindle failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/Users/alex/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Object.deployStack (/Users/alex/node_modules/aws-cdk/lib/api/deploy-stack.ts:230:3)
    at CdkToolkit.deploy (/Users/alex/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/Users/alex/node_modules/aws-cdk/bin/cdk.ts:207:9)
Failed to publish one or more assets. See the error messages above for more information.
```

Running CDK version 1.90.1 (build 0aee440) Node.js v15.8.0

### Use Case

Depending on the network bandwidth uploads of sizeable assets, like Lambda Layers, might require longer than average. Having a CLI flag or ENV var to increase such timeout sounds good to have.

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by hedrall**
Close #13183 

I checked the code base and I understacd that the setting parameter when construct `SdkProvider` in cdk.ts is used when construct actual sdk instance.

If there are no problems with my implementation, I would like to write a test and complete the PR. 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — DISMISSED** [review]
I don't have anything against this change in principle, but I'm also not looking forward to mirroring every single configurable aspect of the HTTP client this way.

What is your particular use case for this feature? Are you looking to decrease or increase?

If true that the default is 120s, that seems excessively high to me. A default of 10s with no configurability (or something along that order of magnitude) seems better.

**Comment by hedrall** [comment]
@rix0rrr 
It's not a case I've actually faced, but as mentioned in the original issue(13183), there seems to be a use case where they want to extend the timeout setting when deploying large sized assets. And, I created the PR because I thought it was necessary to have a way to deal with such edge cases.

I would appreciate your advice on the direction of implementation.

**Comment by rix0rrr** [comment]
Aha I see. I think I would be comfortable just bumping the default higher.

I hope there is a different value for the CONNECT timeout though. I wouldn't want to sit waiting for 2 minutes before the network figures out the target host is unrouteable, or something like that.

So I'd prefer defaults on:

* Connect timeout: low
* HTTP request completion timeout: high

**Comment by hedrall** [comment]
> I wouldn't want to sit waiting for 2 minutes before the network figures out the target host is unrouteable, or something like that.

If we do not explicitly set the environment variable HTTP_TIMEOUT, the timeout will be default as 120000 milliseconds.

Do we also need to make connect timeout separately configurable as well?

According to reference of AWS SDK, connectTimeout is configurable.

> connectTimeout [Integer] — Sets the socket to timeout after failing to establish a connection with the server after connectTimeout milliseconds. This timeout has no effect once a socket connection has been established.
> timeout [Integer] — The number of milliseconds a request can take before automatically being terminated. Defaults to two minutes (120000).

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#httpOptions-property

**Review by rix0rrr — CHANGES_REQUESTED** [review]
I'm comfortable having the connect timeout low (10-ish seconds) and the HTTP timeout high (5 minutes?) and not having it configurable.

**Comment by hedrall** [comment]
Thank you for your comment, and I fixed code. Can I make simple change like it?

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
