### PR TITLE
chore(applicationautoscaling): add neptune as an option for ServiceNamespaces

### PR DESCRIPTION
**Pull request by sennetheunisporphy**
----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by sennetheunisporphy** [comment]
> Thank you for taking the time and submitting the changes. Please review https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#step-4-pull-request in order to understand the conventions for pull request titles.

Adapted the title, is that better?

**Comment by Naumel** [comment]
> Adapted the title, is that better?

It's a step in the right direction, it still requires [changes](https://github.com/aws/aws-cdk/actions/runs/3081939611/jobs/4981048248) to meet the criteria.

**Comment by sennetheunisporphy** [comment]
> > Adapted the title, is that better?
> 
> It's a step in the right direction, it still requires [changes](https://github.com/aws/aws-cdk/actions/runs/3081939611/jobs/4981048248) to meet the criteria.

I renamed it to fix, as it more fixing the extra option then adding a real new feature.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio requeue

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio unqueue

**Comment by TheRealAmazonKendra** [comment]
@Mergiftyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio refresh

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio requeue

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio requeue

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio unqueue

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio unqueue

**Review by TheRealAmazonKendra — DISMISSED** [review]

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio refresh

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio requeue

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
In case anyone is reading these comments and are wondering what the hell I'm doing, some mergify commands aren't working correctly on some changes. I'm trying to figure out what's going on and get it resolved.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
In case anyone is reading these comments and are wondering what the hell I'm doing, some mergify commands aren't working correctly on some changes. I'm trying to figure out what's going on and get it resolved.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio refresh

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio refresh

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio requeue

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio get your shit together.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
