### PR TITLE
chore: support for Docker in VS Code devcontainer

### PR DESCRIPTION
**Pull request by mrgrain**
The current devcontainer configuration doesn't support docker commands.

More details in this Slack Thread: https://cdk-dev.slack.com/archives/C018XT6REKT/p1661980670194059

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by misterjoshua** [comment]
I tested these changes and they work on both my Ubuntu 22.04 LTS box and on another computer in Windows Subsystem for Linux.

**Comment by mrgrain** [comment]
Manually tested the devcontainer on MacOS and WSL 2.0.

**Comment by TheRealAmazonKendra** [comment]
There's no way I can ask for tests in code here, is there? I do wonder if this should be a feat just so it shows up in the changelog, even though we'll have to exempt tests and whatnot.

**Comment by mrgrain** [comment]
Excellent question. I did some research and find this https://code.visualstudio.com/docs/remote/devcontainer-cli
I think the question is more if it's worth the setup. I'm not sure if we have something similar at the moment.

Agreed on making it a feature and I'd like to make some changes to the contributing guide.

**Comment by mrgrain** [comment]
@TheRealAmazonKendra I've decided against automated testing of this. The only thing we would gain from this is to know if the Dockerfile builds. Will add docs changes though.

**Review by corymhall — APPROVED** [review]
Shipping! Not a big risk since it only effects local development.

**Pull request merged**
