### PR TITLE
fix(cli): breaks due to faulty version of `colors`

### PR DESCRIPTION
**Pull request by SheaBelsky**
Fixes https://github.com/aws/aws-cdk/issues/18322 and https://github.com/aws/aws-cdk/issues/18323

Clarifying question: I'm not sure if the `yarn.lock` file should have automatically updated itself to only refer to `colors@1.4.0` when I set the dependency within the workspace _and_ added the resolution for child dependencies. If it's expected behavior for it _not_ to update the `yarn.lock` file after adding `resolutions`, great! If I need to do something else for that to happen, let me know!

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by DanielRuf** [comment]
Keep in mind that lockfiles might not workwhen packages are globally installed.

**Comment by DanielRuf** [comment]
npm users might need also https://www.npmjs.com/package/npm-force-resolutions

**Comment by bodokaiser** [comment]
Adding

```json
 "resolutions": { "colors": "1.4.0" }
```

to my `package.json` worked for me

**Review by iliapolo — APPROVED** [review]
@SheaBelsky Thanks for this!

**Comment by revmischa** [comment]
The maintainer of `colors`: https://www.nbcnewyork.com/news/local/possible-bomb-making-materials-found-at-queens-home-after-fire-police-sources/2619627/

**Pull request merged**
