### PR TITLE
fix(globalaccelerator): changing `installLatestAwsSdk` breaks Security Group reference

### LINKED ISSUE #23796: (cognito): Client Secret handler resource update breaks references
### Describe the bug

In #23591 `installLatestAwsSdk`. This results in a resource update for custom resources. The custom resource that fetches the client secret does not have an `onUpdate` handler (https://github.com/aws/aws-cdk/blame/0798876e5e6c1a665033c759aed3bc0eab05a892/packages/%40aws-cdk/aws-cognito/lib/user-pool-client.ts#L449).

When the update occurs, the response object does not have a `UserPoolClient.ClientSecret` field, resulting in failures when `.userPoolClientSecret` is referenced.

**This results in stacks that fail to update**

### Expected Behavior

Updates should happen gracefully. The same content as the `onCreate` handler should be run for update events.

### Current Behavior

There is no update handler. Updates fail with an error like:

> CustomResource attribute error: Vendor response doesn't contain UserPoolClient.ClientSecret key in object arn:aws-us-gov:cloudformation:us-gov-west-1:123456789012:stack/StackName/UUID|ResourceId|UUID in S3 bucket cloudformation-custom-resource-storage-usgovwest1

CloudWatch Logs shows:

```
{
    "RequestType": "Update",
    "ResourceType": "Custom::DescribeCognitoUserPoolClient",
    "ResourceProperties": {
        "ServiceToken": "...",
        "InstallLatestAwsSdk": "true",
        "Create": "{\"region\":\"us-gov-west-1\",\"service\":\"CognitoIdentityServiceProvider\",\"action\":\"describeUserPoolClient\",\"parameters\":{\"UserPoolId\":\"...\",\"ClientId\":\"...\"},\"physicalResourceId\":{\"id\":\"...\"}}"
    },
    "OldResourceProperties": {
        "ServiceToken": "...",
        "InstallLatestAwsSdk": "false",
        "Create": "{\"region\":\"us-gov-west-1\",\"service\":\"CognitoIdentityServiceProvider\",\"action\":\"describeUserPoolClient\",\"parameters\":{\"UserPoolId\":\"...\",\"ClientId\":\"...\"},\"physicalResourceId\":{\"id\":\"...\"}}"
    }
}

```

```
{
    "Status": "SUCCESS",
    "Reason": "OK",
    "PhysicalResourceId": "...",
    "StackId": "...",
    "RequestId": "...",
    "LogicalResourceId": "...",
    "NoEcho": false,
    "Data": {}
}

```

I can confirm, but do not want to share, the contents of the `Create` object match between the two events.

### Reproduction Steps

- use a version of the CDK _prior_ to #23591

```ts
import * as cdk from "aws-cdk-lib";
import * as cognito from "aws-cdk-lib/aws-cognito";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";

const app = new cdk.App();
const stack = new cdk.Stack(app, 'TestStack');
const userPool = new cognito.UserPool(stack, 'UserPool');
const client = userPool.addClient('TestClient', { generateSecret: true });
const secret = new secretsmanager.Secret(stack, 'ClientSecret', {
  secretStringValue: client.userPoolClientSecret;
});
```

- update the stack using v2.61.1

### Possible Solution

Copy the `onCreate` handler to `onUpdate`.

### Additional Information/Context

Typically, if the User Pool ID or the User Pool Client ID changes, the User Pool Client Secret would too. But other properties passed to the resource can change (like `installLatestAwsSdk`) and this will result in a resource update

### CDK CLI Version

2.61.1

### Framework Version

_No response_

### Node.js Version

16

### OS

Linux

### Language

Typescript

### Language Version

_No response_

### Other information

I am preparing a patch that implements the suggested fix.

### PR DESCRIPTION
**Pull request by jingwy**
### Issue # (if applicable)

Closes #23796

### Reason for this change

In https://github.com/aws/aws-cdk/pull/23591 `installLatestAwsSdk`. This results in a resource update for custom resources. The custom resource that fetches the security groups does not have an onUpdate handler (https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-globalaccelerator/lib/_accelerator-security-group.ts#L32).

When the empty object is returned, this results in an update failure in
CloudFormation because the specific property isn't available and so it will fail with error below:

```
CustomResource attribute error: Vendor response doesn't contain SecurityGroups.0.GroupId key in object
```

When the update occurs, the response object does not have a `SecurityGroups.0.GroupId` field, resulting in failures when `SecurityGroups` is referenced.

### Description of changes
Update the onCreate to onUpdate for custom resources to mitigate the CloudFormation update failure. Documentations: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.AwsCustomResource.html#oncreate. 
Similar fix for Cognito: https://github.com/aws/aws-cdk/pull/23798

### Description of how you validated changes

The integration test is updated with the latest assets.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jingwy** [comment]
> The pull request linter fails with the following errors:
> 
> ```
> ❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.
> 
> If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

Hi, this is already fixed, and I saw the check was passed under action, not sure why it is not updated in the pr.

**Comment by jingwy** [comment]
> ### AWS CodeBuild CI Report
> 
>     * CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
> 
>     * Commit ID: [508a6f6](https://github.com/aws/aws-cdk/commit/508a6f6e61f261707b6aa959fbe74afcbee0a1b5)
> 
>     * Result: FAILED
> 
>     * [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0978f4af-15ef-4258-96cb-71cb2c04f133%2Fbuild.log) (available for 30 days)
> 
> 
> _Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)_

Hi, I have run the integ test locally and it passed with the udpated snapshot, not sure why the build was failing here due to integ test failure.

**Review by paulhcsun — CHANGES_REQUESTED** [review]
Hi @jingwy, thank you for the fix. 

I'm good with the code change because it appears to be the correct fix as per https://github.com/aws/aws-cdk/pull/23798 but just need a couple additional things before I'd like to merge this in.

1. Could you add a new integration test which tests the specific case that was failing for you?

2. Could you update the title of the PR to reflect the bug that you're fixing rather than the change that you're making?

**Review by paulhcsun — APPROVED** [review]
Nice work @jingwy!

Approving as the new onUpdate behaviour is being covered already within the `integ.globalaccelerator.ts`.

**Pull request merged**
