### PR TITLE
chore(iam): add descriptions for all autogenerated roles

### LINKED ISSUE #6235: [Question] Autogenerated description for IAM Roles created by CDK
## :question: General Issue

Now that #6179 has landed, it would be really nice if we can have autogenerated descriptions for roles created automatically by CDK. This would be really helpful, especially if you're pushing CDK within your team and there are 100's of roles, and they don't necessarily like add IAM Role description field (se screenshot below). 

image

### The Question

Where would this logic go? In `aws-iam` package, or each package should populate `description` field separately. In any case tons of tests would have to be fixed all across the board.

I would just like to start a discussion and see where it goes.

### PR DESCRIPTION
**Pull request by robertd**
Closes #6235

@rix0rrr @skinny85 Let me know if this looks good. I'll be updating tests next. Thanks!

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by robertd** [comment]
@rix0rrr This turned out to be major yak shaving task :). I'm still having some issues with aws-eks and aws-eks-legacy integration tests. I'll push what I have on those two shortly.

**Comment by robertd** [comment]
> @robertd I appreciate the work you're doing and I think it's a good idea to label all roles.
> 
> However, I don't recall us talking about the specific labeling that we were going to be doing, and it's concerning to me how much effort you've put into this already.

Frankly, I thought of this after making the first commit (f5f818e), but then I decided it would be a good learning experience for me to see how deep the rabbit hole goes.

I do agree that we need better verbiage here, but now it's easier for me to use these somewhat "generic" statements (i.e. `Generated by [module] for stack: [stack-name]`) and replace them across the board.

> Because of all the time this must have cost you already, I feel a little hesitant and embarrassed to make you do it all over again. But the truth is, I don't think the message "Generated by [some module] for [stackname]" is very useful.

Please don't feel bad about it because it turned out to be a [yak-shaving](https://americanexpress.io/yak-shaving/) (but rewarding) experience for me 😅. The only reason I ended up using the `Generated...` verbiage is because of similar task in #6291. 

>I'd like to see some more information in there, such as: 
> * What "type" of role is this? Instance role? Lambda role? Pipeline role? Etc.

I concur.

> * What resource is likely going to be using the role? Either by referencing the resource name, or maybe even better its construct path?

Can you provide some guidance (examples) of what exactly this should look like?

> * Maybe toss the letters "CDK" in there, for example "the aws-autoscaling module" assumes a high level of familiarity with the CDK already, but not everyone will have that.

Initially, I had "CDK" in it, but then I realized I wanted to know more information;  like which package it originated from. We can definitely iterate through few verbiage examples and pick which one is the best.
 
> Before you start changing the entire codebase, can we try out a couple of different role descriptions, and see how they feel? Specifically how they feel when browsing them in the console, and whether they give the information you'd expect if you're looking at them there (not the CloudFormation template, since it will won't have resolved references yet).

Yes, absolutely. Please provide me with some examples of what you'd like to see and where to get the information from (i.e. resource name, construct path, etc). 

P.S. The reason for all these commits was that for whatever reason my local build wasn't working, but that's been addressed now (#6406). I relied on `AWS CodeBuild` to provide me a clue of the next issue. That's how I've learned more about `decdk` for example.

**Comment by robertd** [comment]
@rix0rrr still waiting on your answers/guidance when you have time so I can start working on this.

**Comment by eladb** [comment]
This shouldn't be a `chore` since it impact user stacks.

**Comment by rix0rrr** [comment]
> Can we somehow enforce this? Otherwise we'll keep forgetting...

@eladb How about we make the `Role` constructor throw if it is getting run under CDK tests and no `description` is supplied? Won't affect users but will catch the attention of CDK devs. We set an environment variable, `CDK_TESTING=1` and test for that in the constructor.

A more cdk-idiomatic way might be using "context" but we don't have a way of easily attaching context to all constructs in all tests without manually rewriting all tests and telling all people they should write their tests differently. Plus, sometimes the unit test construct tree is rooted in `App` and sometimes in `Stack` so there's no single obvious place to hook into.

If you've got some cycles left for core work, this might be an interesting feature.

> still waiting on your answers/guidance when you have time so I can start working on this.

@robertd sorry. Just discovered that the tool I use for keeping on top of GitHub issues assigned to me doesn't tell me when there are new comments, just new commits.

How about:

```
  description: `<Instance|Execution|Blah> Role for ${this.node.path} (generated by CDK)`
```
?

**Comment by eladb** [comment]
@rix0rrr sounds good

**Comment by robertd** [comment]
I'll get back to this at some point.

**Comment by robertd** [comment]
> This shouldn't be a `chore` since it impact user stacks.

@eladb What should I reclassify it under then?

**Pull request closed without merging**
