### PR TITLE
chore(pr-linter): use aws-cdk-automation identity

### PR DESCRIPTION
**Pull request by TheRealAmazonKendra**
Testing this time from a branch instead of directly to our repository. Initially making this 'fix' so it will fail the linter.

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
This might not be necessary anymore after https://github.com/aws/aws-cdk/pull/22194 ?

**Comment by TheRealAmazonKendra** [comment]
> This might not be necessary anymore after #22194 ?

Only the part that changes the identity back to `aws-cdk-automation`. I'll edit it so that only that change is still a thing.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio rebase

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by TheRealAmazonKendra** [comment]
Not sure why this is failing and not actually getting the updated code from main so I'm going to close this one and reopen a new one from a new branch.

**Pull request closed without merging**
