### PR TITLE
fix(eks): cannot upgrade version of clusters with an explicit name

### LINKED ISSUE #6060: Cannot update EKS Version
When upgrading an EKS Stack from 1.13 to 1.14, I'm receiving the error: 

```
Failed to update resource. Error: User: arn:aws:sts::600528167609:assumed-role/xxxxxxxx-cluster-ClusterCreationRole360249-IJHJOC0CU6XD/AWSCDK.EKSCluster.Update.b8b203ff-1091-4625-b292-f27705da4896 is not authorized to perform: eks:UpdateClusterVersion on resource: arn:aws:eks:eu-central-1:600528167609:cluster/xxxxxxx/update 
```

### Reproduction Steps

Create an EKS Cluster version 1.13

### Error Log

```
Failed to update resource. Error: User: arn:aws:sts::600528167609:assumed-role/xxxxxxxx-cluster-ClusterCreationRole360249-IJHJOC0CU6XD/AWSCDK.EKSCluster.Update.b8b203ff-1091-4625-b292-f27705da4896 is not authorized to perform: eks:UpdateClusterVersion on resource: arn:aws:eks:eu-central-1:600528167609:cluster/xxxxxxx/update at invokeUserFunction (/var/task/framework.js:85:19) at process._tickCallback (internal/process/next_tick.js:68:7) Remote function error: AccessDeniedException: User: arn:aws:sts::600528167609:assumed-role/xxxxxx-cluster-ClusterCreationRole360249-IJHJOC0CU6XD/AWSCDK.EKSCluster.Update.b8b203ff-1091-4625-b292-f27705da4896 is not authorized to perform: eks:UpdateClusterVersion on resource: arn:aws:eks:eu-central-1:600528167609:cluster/xxxxxx/update at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27) at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8) at Request.callListeners (
```

### Environment

  - **CLI Version:** 1.22

### Other

I see in https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster-resource.ts#L74 that access only to resourceArn is granted. Maybe this should be extended to something like: 
```
 resources: [ resourceArn, `${resourceAn}/*` ]
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by moatazelmasry2**
Fixes #6060

Steps to verify: 
1. Create an EKS Cluster version 1.13
2. Change the version to 1.14 and apply
3. Get the error that an update cannot take place because ClusterCreationRole is not allowed to do an eks:UpdateClusterVersion on arn:aws:eks:xxxx:xxx:cluster/xxxx/update
4. Apply this PR and retry
5. Updating the cluster works!

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eladb** [comment]
Thanks, this looks great. Test expectations should be updated.

**Comment by moatazelmasry2** [comment]
>  Test expectations should be updated.
Thanks but I didn't understand the last part. Should I change/add something?

**Comment by eladb** [comment]
> Thanks but I didn't understand the last part. Should I change/add something?

**Comment by eladb** [comment]
@moatazelmasry2 wrote:

> Thanks but I didn't understand the last part. Should I change/add something?

If you run `yarn test`, tests will fail and you will need to fix them.

**Comment by eladb** [comment]
@moatazelmasry2 any updates here? Can I help?

**Comment by moatazelmasry2** [comment]
@eladb thanks, sorry didn't have much time for that yet and still a total ts/cdk noob here. Will try to finally get this thing compiling today and we will see then. Will let you know

**Comment by eladb** [comment]
Hey, FYI, I've consolidated all integ tests of EKS into a single test so this should be easier to move forward here. Just run "yarn integ" and wait 30 minutes...

**Pull request merged**
