### PR TITLE
fix(route53-patterns): correct spelling for `useCertificate` feature flag

### PR DESCRIPTION
**Pull request by kbanman**
The current feature flag `@aws-cdk/aws-route53-patters:useCertificate` is mis-spelled.

This PR corrects the spelling while continuing to allow for use of the errant spelling. Please let me know if there are additional measures I should take to mark the old spelling as deprecated so it could be removed in a future major version.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
This doesn't need an integ test, but as much as I hate the typo, I also don't super love adding a duplicate and keeping the old typo one as well. Curious what other team members think here.

**Comment by kbanman** [comment]
The typo is present on public documentation, so I expect removing support could lead to hard-to-debug broken builds. I do think there is room to be more noisy about the use of the typo version, to make it easier to remove in the future

**Review by comcalvi — APPROVED** [review]
thanks for the fix!

**Comment by kbanman** [comment]
Conflicts resolved

**Review by comcalvi — APPROVED** [review]

**Pull request closed without merging**
