### PR TITLE
fix(stepfunctions-tasks): updated EMR service role to use `AmazonEMRServicePolicy_v2` (under feature flag)

### LINKED ISSUE #23915: emr-create-cluster: uses EMR V1 policies instead of V2
### Describe the bug

AWS documentation states that V1 policies are on the deprecation path, however, they are still used within CDK. For example, by default, the [service role created](https://github.com/aws/aws-cdk/blob/d319d9ccba17d0ef8b566e0c68af1f622518f254/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts#L345) uses `AmazonElasticMapReduceRole` instead of `AmazonEMRServicePolicy_v2`. Consequently, I have received warnings that these policies are going to be deprecated and that I should update them.

### Expected Behavior

V2 policies should be used as documented [here](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-managed-iam-policies.html).

### Current Behavior

V1 policies are used.

### Reproduction Steps

N/A

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.51.0

### Framework Version

_No response_

### Node.js Version

v16.19.0

### OS

macOS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by lpizzinidev**
Closes #23915 

**Summary**
Changed EMR used policies from `AmazonElasticMapReduceRole` to `AmazonEMRServicePolicy_v2` as by [documentation](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-managed-iam-policies.html).

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by davidjgolding** [comment]
As per [IAM managed policy for full access](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-managed-policy-fullaccess-v2.html), this won't work as the tag `for-use-with-amazon-emr-managed-policies = true` hasn't been included.

**Comment by lpizzinidev** [comment]
@davidjgolding 
Thanks for the feedback. I'll try to fix it and add some tests as requested by CI.

**Comment by lpizzinidev** [comment]
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Fixes must contain a change to an integration test file and the resulting snapshot.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.

I'm not changing the CFN stack so I don't think integration test changes should be necessary.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
The fact that this change didn't make the build fail means that we have a testing gap here. Please do write a test that uses this. We have a lot of testing gaps in this module, which makes me uneasy. Don't worry, I won't ask you to fill any of the ones that you didn't touch code on, but I think we need to ensure this fix is tested.

**Comment by lpizzinidev** [comment]
@TheRealAmazonKendra 
Thanks for the feedback! I'll work on this 👍

**Comment by lpizzinidev** [comment]
Hi @TheRealAmazonKendra ✋
I'm trying to run an integration test I've created for this PR following [this](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md#how-to-write-integration-tests) guide but I keep getting an error message:

Screenshot 2023-02-10 at 17 07 39

Can you help me?
Thanks

**Comment by TheRealAmazonKendra** [comment]
You'll need to run `cdk bootstrap aws://<account-number>/<region>`. That will setup those resources so you can run the test.

**Comment by lpizzinidev** [comment]
Thanks @TheRealAmazonKendra 👍
I've added a simple integration test for the changes related to this PR. 
Please let me know if you need any more improvements.

If you think that is valuable I might submit a PR with a doc change explaining the need to run the `cdk bootstrap aws://<account-number>/<region>` command before integration tests (unless already explained).
This might help other beginner users like me get started contributing to the repo.

Also, as you noticed (https://github.com/aws/aws-cdk/pull/23985#pullrequestreview-1290649586), there aren't many integration tests for the `emr` module so I might submit PRs to address that issue as well.

**Comment by TheRealAmazonKendra** [comment]
Hey, sorry I missed your changes here. Mergify should have dismissed my original review when you pushed changes but it didn't so I wasn't alerted. Not sure why that happened.

I'm concerned that this is going to cause a breaking change for customers already using the old policy. This may need to go under a feature flag. I'm going to ask for a second opinion from my team. 

Also, please make sure that your PR title confirms to the conventional commit standard (fix, feat, chore) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request)). Specifically, a fix should include the bug being fixed, not the solution implemented.

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Comment by lpizzinidev** [comment]
> This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

@TheRealAmazonKendra 
I did add integration tests as requested [above](https://github.com/aws/aws-cdk/pull/23985#pullrequestreview-1290649586).

**Review by MrArnoldPalmer — DISMISSED** [review]
So I think we should be cautious and put this behind a feature flag. Upon reading the docs it seems that there are some resources that don't automatically have the appropriate tags propagated and may require manual intervention.

I may be misreading but the fact that it's potentially unclear at all means a feature flag is probably necessary. That being said adding some unit tests for both on and off states of the flag will be necessary.

**Comment by lpizzinidev** [comment]
@MrArnoldPalmer 
My bad, I missed the part about the feature flag.
Thanks for the feedback anyway, I submitted the changes.
Let me know if further work or improvements are needed 💪

**Review by MrArnoldPalmer — DISMISSED** [review]
Awesome, TYVM! :shipit:

**Review by MrArnoldPalmer — APPROVED** [review]
:shipit:

**Review by MrArnoldPalmer — APPROVED** [review]

**Pull request merged**
