### PR TITLE
fix(redshift): tableNameSuffix evaluation

### LINKED ISSUE #17064: (aws-redshift): Tables are always created with a suffix
### What is the problem?

When creating a Redshift table using the Table construct the table are always created with a suffix. Looking at the code it appears that this should be an optional behavior.

### Reproduction Steps

Create a table
```
const myTable = new redshift.Table(this, "MyTable", {
    cluster: cluster,
    adminUser: adminSecret,
    databaseName: "MyDb",
    tableName: "s.my_table",
    tableColumns: [
        { name: 'id', dataType: 'numeric(38,0) DISTKEY NOT NULL encode raw' },
        { name: 'request_datetime_utc', dataType: 'timestamp without time zone NULL encode raw' }
    ]
});
```

and build CDK to generate CFN

```
"MyTableD7252149": {
  "Type": "Custom::RedshiftDatabaseQuery",
  "Properties": {
    "ServiceToken": {
      "Fn::GetAtt": [
        "MyTableProviderframeworkonEventA4849808",
        "Arn"
      ]
    },
    "handler": "table",
    "clusterName": {
      "Ref": "MyCluster"
    },
    "adminUserArn": {
      "Ref": "AdminSecret"
    },
    "databaseName": "MyDb",
    "tableName": {
      "prefix": "s.my_table",
      "generateSuffix": false
    },
    "tableColumns": [
      {
        "name": "id",
        "dataType": "numeric(38,0) DISTKEY NOT NULL encode raw"
      },
      {
        "name": "request_datetime_utc",
        "dataType": "timestamp without time zone NULL encode raw"
      }
    ]
  },
  "UpdateReplacePolicy": "Retain",
  "DeletionPolicy": "Retain",
  "Metadata": {
    "aws:cdk:path": "MyStack/MyTable/Resource/Resource/Default"
  }
},
```

Notice that `generateSuffix` is set to false which would mean that my table should simply have the name `s.my_table`

### What did you expect to happen?

A Redshift table created with the name `s.my_table`

### What actually happened?

A Redshift table created with the name `s.my_tabled8a03679`

### CDK CLI Version

1.126.0

### Framework Version

_No response_

### Node.js Version

NodeJS-12.0

### OS

Amazon Linux 2012

### Language

Typescript

### Language Version

_No response_

### Other information

I can see that the `generateSuffix: "false"` is present in the Lambda Event for the Table creation custom resource

```
{
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:us-west-2:11111111111111:function:IGTWBRDBInfrastructure-ComplianceDrCidTableProvide-g2VTPfULZtQa",
    "ResponseURL": "https://cloudformation-custom-resource-response-uswest2.s3-us-west-2.amazonaws.com/arn%3Aaws%3Acloudformation%3Aus-west-2%3A1",
    "StackId": "arn:aws:cloudformation:us-west-2:11111111111111:stack/MyStack/9b0abc30-9591-11ea-ba99-067aa3cae1e0",
    "RequestId": "132a420e-5173-4e22-9b96-c04493148172",
    "LogicalResourceId": "MyTableD7252149",
    "ResourceType": "Custom::RedshiftDatabaseQuery",
    "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:us-west-2:11111111111111:function:MyTableProvide-g2VTPfULZtQa",
        "handler": "table",
        "tableColumns": [
            {
                "dataType": "numeric(38,0) DISTKEY NOT NULL encode raw",
                "name": cid"
            },
            {
                "dataType": "timestamp without time zone NULL encode zstd",
                "name": "request_completed_datetime_utc"
            }
        ],
        "adminUserArn": "arn:aws:secretsmanager:us-west-2:11111111111111:secret:AdminSecret-omYPRk",
        "databaseName": "MyDb",
        "clusterName": "MyCluster",
        "tableName": {
            "prefix": "s.my_table",
            "generateSuffix": "false"
        }
    }
}
```

however it is a string as opposed to a boolean. As a result [`props.tableName.generateSuffix ? `${event.RequestId.substring(0, 8)}` : ''`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts#L9) is evaluated to true instead of false which creates the suffix.

### PR DESCRIPTION
**Pull request by ibrahimcesar**
- Check if the generateSuffix is explicitly 'true';
- Closes #17064

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by njlynch — DISMISSED** [review]
It looks like your editor settings are different from ours, in that you've introduced double-quotes everywhere we use single quotes. This is causing the build to fail on our linter. You'll need to revert these change for the build to succeed.

**Review by njlynch — DISMISSED** [review]
Can you please enable "Allow edits from maintainers"? This is necessary for our automation to keep the branch up to date, and eventually be merged in.

**Comment by ibrahimcesar** [comment]
Captura de Tela 2021-11-11 às 12 07 09

Sure! I assumed this was the default behaviour.

Thanks!

**Review by njlynch — APPROVED** [review]
I made a few more clean-ups so the diff was minimal. Thanks for the contribution!

**Comment by ibrahimcesar** [comment]
Thanks @njlynch! I'll learn from your adjustments 😄

**Pull request merged**
