### PR TITLE
feat(lambda): node12.x, python3.8 and java11 runtimes

### LINKED ISSUE #5089: Supper new Lambda runtime versions
Python 3.8 runtime now available in AWS Lambda https://aws.amazon.com/blogs/compute/python-3-8-runtime-now-available-in-aws-lambda/ 

Node.js 12.x runtime now available in AWS Lambda https://aws.amazon.com/blogs/compute/node-js-12-x-runtime-now-available-in-aws-lambda/ 

Java 11 runtime now available in AWS Lambda https://aws.amazon.com/blogs/compute/java-11-runtime-now-available-in-aws-lambda/ 

### Proposed Solution

https://github.com/aws/aws-cdk/blob/2d92ab3e22130408056257d87620a3e03d75b226/packages/%40aws-cdk/aws-lambda/lib/runtime.ts#L25-L48

### Other

cloudformation resource reference for Lambda function:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by wulfmann**
Fixes #5089 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by wulfmann** [comment]
Recently saw there is an older pr for this that wasn’t included on the issue. Feel free to close if you wish.

**Comment by trivikr** [comment]
> Recently saw there is an older pr for this that wasn’t included on the issue

If the related PR is #4655, it adds new alias `NODE_LATEST` which points to latest version of Node.js runtime.
It won't be blocking this PR, although there will be merge conflicts for the one which is merged latter.

**Comment by nija-at** [comment]
The team will be heads down for a couple of days, so it'll be a bit longer before we can get to this. Apologies for the delayed response.

**Comment by trivikr** [comment]
Thanks merging this, when is it expected to be released?
Will it be released with v1.17.2?

**Comment by arnulfojr** [comment]
Can we get an estimated date(time) for the release? :D

**Comment by nija-at** [comment]
It will be released early next week, as part of our regular CDK release (`1.18.0`)

**Comment by trivikr** [comment]
This commit is released in v1.18.0 https://github.com/aws/aws-cdk/releases/tag/v1.18.0

**Pull request merged**
