### PR TITLE
fix(stepfunctions-tasks): EcsRunTask containerOverrides throws if container name doesn't match construct ID

### LINKED ISSUE #15171: (stepfunctions-tasks): EcsRunTask containerOverrides throws if container name doesn't match construct ID
I ran into an issue while updating CDK from 1.77.0 to1.109.0. I create a step function which utilizes ECS tasks (Fargate) to run a long-running task. It uses `EcsRunTask` from the `@aws-cdk/aws-stepfunctions-tasks` library.

### Reproduction Steps

```
const vpc = new ec2.Vpc(this, 'VPC');
const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
  cpu: 1024,
  memoryLimitMiB: 8192,
});
const containerDefinition = taskDefinition.addContainer('TaskContainer', {
  image: ecs.ContainerImage.fromDockerImageAsset(new ecrassets.DockerImageAsset(this, 'asset', { directory: path.join(__dirname, './image-asset') })),
  containerName: 'AnyOtherNameThatIsNotTheConstructId',
  environment: {
    EVENT: '',
  },
});
new sfntasks.EcsRunTask(this, 'ECSTaskRun', {
  cluster: new ecs.Cluster(this, 'Cluster', { vpc }),
  launchTarget: new sfntasks.EcsFargateLaunchTarget(),
  taskDefinition: taskDefinition,
  assignPublicIp: true,
  containerOverrides: [
    {
      containerDefinition: containerDefinition,
      environment: [{ name: 'EVENT', value: 'something' }],
    },
  ],
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
  resultPath: sfn.JsonPath.DISCARD,
});
```

### What did you expect to happen?

No error, since the container definition defined in the override is directly returned from the call to `TaskDefinition.addContainer`, implying that the container does in fact exist in the task definition.

### What actually happened?

```
Error: Overrides mention container with name 'XXX', but no such container in task definition
```

### Environment

  - **Framework Version:** 1.109.0
  - **Node.js Version:** v14.16.1

### Other

Error is coming from the code in `cdk\node_modules\@aws-cdk\aws-stepfunctions-tasks\lib\ecs\run-task.js` line 141 were it takes the name of the container (as defined in the overriding option) and looks for it (as a key) in the task definition (with the function `tryFindChild`:

```
            const name = override.containerDefinition.containerName;
            if (!cdk.Token.isUnresolved(name)) {
                const cont = this.props.taskDefinition.node.tryFindChild(name);
                if (!cont) {
                    throw new Error(`Overrides mention container with name '${name}', but no such container in task definition`);
                }
            }
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by Cruaier**
EcsRunTask, container override is now using using method `findContainer` to check for container in TaskDefinition

fixes #15171 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Cruaier** [comment]
@BenChaimberg please have a look - I added the changes as you proposed and wrote another UT for the special case which may arise if you use a wrong container for the override.

**Comment by BenChaimberg** [comment]
Looks great! Please add a test that address the specific error in the reported issue (overriding a container whose name does not match its construct ID *does not* throw an error)

**Review by BenChaimberg — CHANGES_REQUESTED** [review]
Looks great! Please add a test that address the specific error in the reported issue (overriding a container whose name does not match its construct ID *does not* throw an error)

**Comment by Cruaier** [comment]
@BenChaimberg I added the missing UT...sorry it took me a while. Should be all fine now.

**Review by BenChaimberg — APPROVED** [review]

**Pull request merged**
