### PR TITLE
fix(dynamodb): cannot change serverSideEncryption from true to false

### LINKED ISSUE #8286: Cannot change DynamoDB serverSideEncryption from true to false
When you have already deployed a DynamoDB table with `serverSideEncryption: true`, you cannot change it to `false`. Changing it to false results in a CloudFormation deploy error. This most likely happens because AWS CDK removes the underlying CloudFormation property `SSESpecification / SSEEnabled` instead of setting it to false at https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L1355

I have successfully changed the CloudFormation property `SSESpecification / SSEEnabled: true` to `false` when using CloudFormation directly. And I also get the same error if I try to remove the property completely.

I think AWS CDK needs some way to configure DynamoDB Tables so that the `SSESpecification / SSEEnabled: false` property is included in the CloudFormation stack.

PS: The reason to change serverSideEncryption to false is that it results in DEFAULT encryption being used, which doesn't cost anything. When serverSideEncryption is true, the mode is KMS - AWS managed CMK and AWS charges you for it. At least that's what the DynamoDB console says.

### Reproduction Steps

1. Deploy a DynamoDB table with serverSideEncryption: true
2. Change it to serverSideEncryption: false and try to deploy the update

### Error Log

CloudFormation error when deploying update:

`At least one of ProvisionedThroughput, BillingMode, UpdateStreamEnabled, GlobalSecondaryIndexUpdates or SSESpecification or ReplicaUpdates is required (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException`

### Environment

  - **CLI Version      : 1.42.0 (build 3b64241)**
  - **Framework Version: 1.42.0**
  - **OS               : Linux**
  - **Language         : TypeScript**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by RomainMuller**
When a table was deployed with `serverSideEncryption` set to `true` (by
requesting `AWS_MANAGED` or `CUSTOM` server side encryption), it was not
possible to switch back to `DEFAULT` as this could drop the
`serverSideEncryption` configuration altogether, which CloudFormation
will not allow.

This changes makes `Table` continue to not set the
`serverSideEncryption` configuration if nothing was configured (the user
chose the implicit default behavior), but to actually set the value
explicitly to `false` if the user *explicitly* requests `DEFAULT`
encryption.

This makes it possible to flip away from `AWS_MANAGED` and `CUSTOM`
encryption to the cheaper alternative that is `DEFAULT`.

Fixes #8286

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by RomainMuller** [comment]
> This feels off. What happens if I set encryption to MANAGED and then remove my setting with the expectation that now I'll use the default encryption (as the documentation of this prop indicates). Sounds like this is going to fail.
> 
> Why not just always be explicit?

Because turning an argument __required__ is a breaking change to a stable API, and so this is not an option?

**Comment by eladb** [comment]
> > This feels off. What happens if I set encryption to MANAGED and then remove my setting with the expectation that now I'll use the default encryption (as the documentation of this prop indicates). Sounds like this is going to fail.
> 
> > 
> 
> > Why not just always be explicit?
> 
> 
> 
> Because turning an argument __required__ is a breaking change to a stable API, and so this is not an option?

I am not proposing to make it required. Just that no value will render the same as DEFAULT. Yes it means that existing stacks will now change to explicitly indicate this but I don’t think that’s a problem. Do you?

**Comment by RomainMuller** [comment]
@eladb - last I checked, changing this value causes "some interruption" according to the CloudFormation docs. I don't feel comfortable causing "some interruption" to all existing stacks...

**Comment by eladb** [comment]
> @eladb - last I checked, changing this value causes "some interruption" according to the CloudFormation docs. I don't feel comfortable causing "some interruption" to all existing stacks...

So I would deprecate this field and introduce a new one with proper semantics.

**Comment by RomainMuller** [comment]
> > @eladb - last I checked, changing this value causes "some interruption" according to the CloudFormation docs. I don't feel comfortable causing "some interruption" to all existing stacks...
> 
> So I would deprecate this field and introduce a new one with proper semantics.

Won't that mean the new field **must** be optional, and the behavior when it's `undefined` **must** be exactly the current behavior? Wouldn't that basically be replicating the current field?

**Comment by eladb** [comment]
> Won't that mean the new field must be optional, and the behavior when it's undefined must be exactly the current behavior? Wouldn't that basically be replicating the current field?

Can we introduce a new field for which the behavior will be that if it is undefined it will explicitly set encryption to DEFAULT?

**Comment by RomainMuller** [comment]
> > Won't that mean the new field must be optional, and the behavior when it's undefined must be exactly the current behavior? Wouldn't that basically be replicating the current field?
> 
> Can we introduce a new field for which the behavior will be that if it is undefined it will explicitly set encryption to DEFAULT?

But won't this change the behavior of existing apps that do not set this hypothetical new property (meaning all of them)?

**Comment by RomainMuller** [comment]
> As long as they won't break or replace resources I think that's a legitimate change. No?

We've come full circle to the original premise of the discussion... Which is that changing this value might cause *some interruption* and I don't think this is acceptable.

**Review by eladb — APPROVED** [review]

**Pull request merged**
