### PR TITLE
fix(config): explicit `ruleScope` value overwritten on `CloudFormationStackDriftDetectionCheck`

### PR DESCRIPTION
**Pull request by sHtev**
If `ruleScope` is set in the props of `CloudFormationStackDriftDetectionCheck`, and `ownStackOnly` is not set then the current code:

```ts
    this.ruleScope = RuleScope.fromResource( ResourceType.CLOUDFORMATION_STACK, props.ownStackOnly ? Stack.of(this).stackId : undefined );
```
overwrites  `this.ruleScope` with a resource `RuleScope` with an `undefined` resource id.

This makes it impossible to scope the drift check based on tags or resource ids other than that of the current stack.

The change in this PR explicitly checks for the `ownStackOnly` prop before overriding the ruleScope, and sets a sensible default if `ruleScope` itself is undefined to mirror existing default behaviour.

An example with a tag-filtering `RuleScope` has been added to the unit tests.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by sHtev** [comment]
Note: the integration test currently has a warning it is undeployable, I hope this does not stop this needed fix being applied

**Comment by sHtev** [comment]
Exemption Request if someone could help me understand why the codebuild fails when integration works locally that would be great

**Comment by paulhcsun** [comment]
Hi @sHtev, apologies for not getting around to this, if you're still interested in working on this I've taken a look at the codebuild failure, usually integ test failures in the PR pipeline are because the snapshots you've added don't match up with what's being created by the pipeline. Could you just double check that the snapshots included in the PR are the most recent snapshots you have from running the integ tests locally?

**Comment by paulhcsun** [comment]
Closing this PR for staleness. Please open a new PR if you'd like to continue working on this @sHtev.

**Pull request closed without merging**
