### PR TITLE
chore(rds): add missing rds engine versions

### PR DESCRIPTION
**Pull request by sakurai-ryo**
This Pull Request will add supported RDS engine versions.

Added engine versions are as follows.
```sh
$ aws rds describe-db-engine-versions \
--query "DBEngineVersions[?EngineVersion=='5.7.44'||EngineVersion=='8.0.35'].[DBEngineVersionDescription,EngineVersion,Status]" \
--engine mysql
[
    [
        "MySQL 5.7.44",
        "5.7.44",
        "available"
    ],
    [
        "MySQL 8.0.35",
        "8.0.35",
        "available"
    ]
]

$ aws rds describe-db-engine-versions \
--query "DBEngineVersions[?EngineVersion=='15.00.4322.2.v1'||EngineVersion=='15.00.4335.1.v1'].[DBEngineVersionDescription,EngineVersion,Status]" \
--engine sqlserver-ee
[
    [
        "SQL Server 2019 15.00.4322.2.v1",
        "15.00.4322.2.v1",
        "available"
    ],
    [
        "SQL Server 2019 15.00.4335.1.v1",
        "15.00.4335.1.v1",
        "available"
    ]
]

$ aws rds describe-db-engine-versions \
--query "DBEngineVersions[?EngineVersion=='19.0.0.0.ru-2023-07.rur-2023-07.r1'||EngineVersion=='19.0.0.0.ru-2023-10.rur-2023-10.r1'].[DBEngineVersionDescription,EngineVersion,Status]" \
--engine oracle-ee-cdb
[
    [
        "Oracle 19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "available"
    ],
    [
        "Oracle 19.0.0.0.ru-2023-10.rur-2023-10.r1",
        "19.0.0.0.ru-2023-10.rur-2023-10.r1",
        "available"
    ]
]


$ aws rds describe-db-engine-versions \
--query "DBEngineVersions[?EngineVersion=='21.0.0.0.ru-2023-07.rur-2023-07.r1'||EngineVersion=='21.0.0.0.ru-2023-10.rur-2023-10.r1'].[DBEngineVersionDescription,EngineVersion,Status]" \
--engine oracle-ee-cdb
[
    [
        "Oracle 21.0.0.0.ru-2023-07.rur-2023-07.r1",
        "21.0.0.0.ru-2023-07.rur-2023-07.r1",
        "available"
    ],
    [
        "Oracle 21.0.0.0.ru-2023-10.rur-2023-10.r1",
        "21.0.0.0.ru-2023-10.rur-2023-10.r1",
        "available"
    ]
]
```
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by go-to-k** [comment]
Thanks, sounds nice!

Just to be sure, could you please post any release notes or references?

**Comment by sakurai-ryo** [comment]
@go-to-k 
Thank you for your review!
The following versions are mentioned in the documentation or release notes.
```
MySQL
5.7.44
https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-rds-mysql-new-minor-version-5-7-44

Oracle
19.0.0.0.ru-2023-07.rur-2023-07.r1
19.0.0.0.ru-2023-10.rur-2023-10.r1
https://docs.aws.amazon.com/AmazonRDS/latest/OracleReleaseNotes/oracle-version-19-0.html

21.0.0.0.ru-2023-07.rur-2023-07.r1
21.0.0.0.ru-2023-10.rur-2023-10.r1
https://docs.aws.amazon.com/AmazonRDS/latest/OracleReleaseNotes/oracle-version-21-0.html
```

However, for MySQL v8.0.35 and SQL Server, there is no mention in the documentation, but I can check in the CLI or console.
Is it better to exclude these versions that are not documented from this PR?

SQL Server
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_SQLServer.html#SQLServer.Concepts.General.VersionSupport
MySQL
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.Concepts.VersionMgmt.html

**Review by go-to-k — APPROVED** [review]
Thanks for listing docs!

> However, for MySQL v8.0.35 and SQL Server, there is no mention in the documentation, but I can check in the CLI or console.
> Is it better to exclude these versions that are not documented from this PR?

`You can also use the describe-db-engine-versions AWS CLI command to see a list of supported versions, as well as defaults for newly created DB instances.`

The SQL Server documentation states that the `describe-db-engine-versions` AWS CLI command can be used to check for supported versions. (And you have already done it.)

Also, if they are not beta versions and can be checked successfully in the CLI or console as well as any other versions, I would be good.

Therefore, I approve it in my review.

Thank you for the contribution!

**Review by scanlonp — DISMISSED** [review]
I agree. I think the cli check is sufficient to know they are supported.

Thanks!

**Review by scanlonp — APPROVED** [review]

**Pull request merged**
