### PR TITLE
[needs love] feat(@aws-cdk/s3): add support for bucket replication.

### PR DESCRIPTION
**Pull request by rix0rrr**
You can now call `source.enableBucketReplication(dest)` to replicate
one bucket to a different one.

Note that the two buckets must live in different regions.

By submitting this pull request, I confirm that my contribution is made under
the terms of the beta license.

### CODE REVIEW

**Comment by rix0rrr** [comment]
This PR will be a great motivating example for cross-stack references.

**Comment by eladb** [comment]
What's the follow up on this?

**Comment by rix0rrr** [comment]
Cross stack references first, then this. Still percolating in the back of my head, will start working on it as soon as I have time.

**Comment by moofish32** [comment]
@rix0rrr -- bucket replication is cross region, cross stack references are in region? Is there something to make all that work here?

**Comment by rix0rrr** [comment]
Not yet, but there will be 😊

**Comment by pinedajr** [comment]
[fdasset1532912315696.zip](https://github.com/awslabs/aws-cdk/files/2343048/fdasset1532912315696.zip)

**Comment by eladb** [comment]
@rix0rrr what should we do with this?

**Comment by eladb** [comment]
Opened #1680

**Pull request closed without merging**
