### PR TITLE
feat(events-targets): add dlq support for ecs target

### LINKED ISSUE #21118: events-targets: dead letter queue for an ECS task target
### Describe the feature

For an Event Bridge rule with an ECS task target, support a dead letter queue.

### Use Case

This has been implemented for other targets already such as Lambda. It may be useful to track problems with invoking the task.

### Proposed Solution

workaround based on the pattern of [this PR](https://github.com/aws/aws-cdk/pull/11617).
I tested that this produces a dead letter queue in the event bridge rule target.

``` typescript
import * as events from '@aws-cdk/aws-events';
import * as events_targets from '@aws-cdk/aws-events-targets';
import * as sqs from '@aws-cdk/aws-sqs';

interface EcsTaskProps extends events_targets.EcsTaskProps {
    deadLetterQueue?: sqs.Queue;
}

class EcsTask implements events.IRuleTarget {
    readonly deadLetterQueue?: sqs.Queue;
    readonly wrappedTask: events_targets.EcsTask
    constructor(private readonly props: EcsTaskProps) {
        this.deadLetterQueue = props.deadLetterQueue ;
        this.wrappedTask = new events_targets.EcsTask(props);
    }

    public bind(rule: events.IRule, _id?: string): events.RuleTargetConfig {
        const wrappedResult = this.wrappedTask.bind(rule, _id);
        let deadLetterConfig: events.CfnRule.DeadLetterConfigProperty | undefined = undefined
        if (this.deadLetterQueue) {
            events_targets.addToDeadLetterQueueResourcePolicy(rule, this.deadLetterQueue);
            deadLetterConfig = this.deadLetterQueue ? { arn: this.deadLetterQueue?.queueArn } : undefined
        }
        return { ...wrappedResult, deadLetterConfig }
    }
}
```

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

Mac

### PR DESCRIPTION
**Pull request by jumic**
Add DLQ support for ECS target.

Closes #21118.

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — DISMISSED** [review]
This is almost perfect, but can you update these integration tests to use the new `IntegTest` type. Here's the [documentation](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md) for that.

**Comment by jumic** [comment]
I updated the integration tests to the new type. In addition, I renamed `integ.event-ec2-task.lit.ts` to `integ.event-ec2-task.ts` because it's not used in the documentation.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thanks for taking this on!

**Review by TheRealAmazonKendra — APPROVED** [review]
Oooooops. I hit the wrong button. Approving, not requesting changes.

**Pull request merged**
