### PR TITLE
feat: replaced s3.Bucket with s3.IBucket in S3EventSource constructor.

### PR DESCRIPTION
**Pull request by eglijin**
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) yes

### Adding new Unconventional Dependencies:
No Unconventional Dependencies
### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* I've updated the synth tests, which I think are enough for the scope of this change. 

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
```ts
constructor(readonly bucket: s3.Bucket) {
}
```

This is a single declaration of two things. It expands to the following, but unfortunately not both of them can be changed:

```ts
readonly bucket: s3.Bucket;  // <-- you CANNOT change this to s3.IBucket

constructor(bucket: s3.Bucket) {   // <-- you CAN change this to s3.IBucket
  this.bucket = bucket;
}
```

You'll have to introduce a private field to hold the `IBucket` and turn the `readonly bucket: s3.Bucket` into a `getter` that throws if the `IBucket` we got passed in is accidentally not *really* a `Bucket`.

**Comment by eglijin** [comment]
> ```ts
> ```ts
> constructor(readonly bucket: s3.Bucket) {
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> This is a single declaration of two things. It expands to the following, but unfortunately not both of them can be changed:
> ```ts
> readonly bucket: s3.Bucket;  // <-- you CANNOT change this to s3.IBucket
> 
> constructor(bucket: s3.Bucket) {   // <-- you CAN change this to s3.IBucket
>   this.bucket = bucket;
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> You'll have to introduce a private field to hold the IBucket and turn the readonly bucket: s3.Bucket into a getter that throws if the IBucket we got passed in is accidentally not really a Bucket.
> ```

@rix0rrr I'm a beginner in ts/node, but If I understand correctly the Idea is that the S3EventSource type has a variable that returns s3.Bucket, and that contract should be maintained, and you suggest we separate that into a constructor that accepts  an s3.IBucket and a getter that returns the s3.Bucket with the addition of the type check in the getter.

The use-case I'm trying to achieve with this change is 

```
const fn = new LambdaFunction(stack, .....);
const bucket = s3.Bucket.fromBucketArn(stack, 'id', 'arn');
fn.addEventSource(new S3EventSource(bucket, {
      events: [s3.EventType.OBJECT_CREATED],
      filters: [{ prefix: 'subdir/' }],
    }));
```
s3.Bucket.fromBucketArn returns an s3.IBucket
I'm passing that to S3EventSource 
and I'm expecting the bucket to properly be identified by it's arn.
But coming from a Java background I don't get why S3EventSource should be tied to a concrete implementation aka s3.Bucket if it is supposed to work with the highest abstraction of a bucket aka s3.IBucket, and the code that calls S3EventSource.bucket should work properly with s3.IBucket or throw.

**Comment by rix0rrr** [comment]
Sorry if I didn't make myself clear.

* You are right, your reasoning is sound, the fact that we don't accept `IBucket` is a mistake.
* However, we have backwards compatibility to contend with. Someone could have written the following code (in Java):

```java
S3EventSource source;
Bucket bucket = source.bucket;   // Compilation error if 'source.bucket' is all of a sudden an IBucket instead of a Bucket
```

So: we are not allowed to break the compilation of any of our customers, so we have to keep `source.bucket` typed as `Bucket`, *even* if we didn't get a `Bucket` instance.

If that happens, I'm fine with turning it into a runtime error. The odds of people having written this are small, but given that the API is what it is, we have to commit to it.

**Comment by eglijin** [comment]
In that case, let's follow the path you suggested, but add a depreciation flag on the S3EventSource.bucket getter, that way the api can transition to the appropriate abstraction level and the customers that already depend on the property have time to migrate. 
Additionally from what I can tell the only public non inherited methods that Bucket has over IBucket are 
addLifecycleRule, addMetric, addCorsRule, addInventory. The chances that someone will grab a hold of the source.bucket to call any of these methods are very very small, as in most cases you'll already have a reference to the bucket before passing it to the S3EventSource.

**Review by rix0rrr — DISMISSED** [review]

**Comment by eglijin** [comment]
For some reason I'm getting 
`Parameters
[-] Parameter BootstrapVersion: {"Type":"AWS::SSM::Parameter::Value<String>","Default":"/cdk-bootstrap/hnb659fds/version","Description":"Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]"}
[+] Parameter Asset1S3Bucket: {"Type":"String","Description":"S3 bucket for asset \"Asset1Hash\""}
[+] Parameter Asset1S3VersionKey: {"Type":"String","Description":"S3 key for asset version \"Asset1Hash\""}
[+] Parameter Asset1ArtifactHash: {"Type":"String","Description":"Artifact hash for asset \"Asset1Hash\""}

Resources
[~] AWS::Lambda::Function CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F 
 └─ [~] Code
     ├─ [~] .S3Bucket:
     │   ├─ [-] Removed: .Fn::Sub
     │   └─ [+] Added: .Ref
     └─ [~] .S3Key:
         └─ @@ -1,1 +1,33 @@
            [-] "be270bbdebe0851c887569796e3997437cca54ce86893ed94788500448e92824.zip"
            [+] {
            [+]   "Fn::Join": [
            [+]     "",
            [+]     [
            [+]       {
            [+]         "Fn::Select": [
            [+]           0,
            [+]           {
            [+]             "Fn::Split": [
            [+]               "||",
            [+]               {
            [+]                 "Ref": "Asset1S3VersionKey"
            [+]               }
            [+]             ]
            [+]           }
            [+]         ]
            [+]       },
            [+]       {
            [+]         "Fn::Select": [
            [+]           1,
            [+]           {
            [+]             "Fn::Split": [
            [+]               "||",
            [+]               {
            [+]                 "Ref": "Asset1S3VersionKey"
            [+]               }
            [+]             ]
            [+]           }
            [+]         ]
            [+]       }
            [+]     ]
            [+]   ]
            [+] }

Other Changes
[-] Unknown Rules: {"CheckBootstrapVersion":{"Assertions":[{"Assert":{"Fn::Not":[{"Fn::Contains":[["1","2","3","4","5"],{"Ref":"BootstrapVersion"}]}]},"AssertDescription":"CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI."}]}}
`
@rix0rrr can you help me figure it out ?

**Pull request closed without merging**
