### PR TITLE
feat(ecs-patterns): allow passthrough of security groups to service

### LINKED ISSUE #8953: [ecs-patterns] ApplicationLoadBalancedFargateService - how to add security group to Network Interface
Hi,

I am trying to create a Fargate ECS cluster with two Tasks. I want each Task to communicate over tcp to non-default ports. I am using the ApplicationLoadBalancedFargateService in C#, but I cannot see where to add a Security Group that allows inbound traffic to these ports. I can add one in the console after the stack has been deployed, but I want to include it in the CDK stack. I can see that the following group is successfully created:

```
            var secGroup = new SecurityGroup(this, "secgroup", 
             new SecurityGroupProps
            {
                Vpc = vpc,
                SecurityGroupName = "MySecurityGroup",
                Description = "Silo security port access"
            });
            secGroup.AddIngressRule(Peer.Ipv4("0.0.0.0/0"), Port.Tcp(11111), "Silo port access");
            secGroup.AddIngressRule(Peer.Ipv4("0.0.0.0/0"), Port.Tcp(30000), "Gateway port access");
```

but it does not get added to the ENI of the ECS Service. I have tried adding the group to the Service created as part of using `ApplicationLoadBalancedFargateService` via the `Connections.AddSecurityGroup` method.

How can I get the security group to be used for the ENIs created for the tasks?

Many thanks

### PR DESCRIPTION
**Pull request by clementallen**
Closes #8953

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by iamhopaul123 — COMMENTED** [review]
Looks great! Could you add manual test to double check if this feature works as we expect?

**Comment by clementallen** [comment]
> Looks great! Could you add manual test to double check if this feature works as we expect?

Thanks @iamhopaul123 - I'm not quite sure what you mean by adding a manual test?  I've tested it with my own CDK projects and it works as expected.

**Comment by iamhopaul123** [comment]
> I've tested it with my own CDK projects and it works as expected.

That's exactly what I meant. Would you mind adding security groups option to ec2 pattern as well? Otherwise it might be a bit odd to see fargate supports passthrough of SGs but ec2 doesn't...

**Comment by clementallen** [comment]
> Would you mind adding security groups option to ec2 pattern as well

Sure can do, and to the other patterns too such as NLB Fargate, multiple target groups etc?

**Comment by iamhopaul123** [comment]
that'll be great! thank you so much!

**Comment by clementallen** [comment]
@iamhopaul123 

I'm not hugely familiar with the non-fargate Ec2 patterns, but it seems the `Ec2TaskDefinition` needs a `networkMode` of `AWS_VPC` if a securityGroup is provided.  Should I also allow that to be passed in from top level pattern?

**Comment by iamhopaul123** [comment]
yeah that's true. But it should be already handled by ec2service so I don't think we should overkill the issue. At least we can be sure that i'll error out before deploying to the CFN.

**Comment by clementallen** [comment]
@iamhopaul123 if `networkMode` isn't passed, it will error before deploying whenever a security group is provided, meaning there isn't much use providing one :)

Would it be okay if I raised a separate issue for the EC2 security groups and kept this MR focused on Fargate?

**Comment by iamhopaul123** [comment]
Sounds good to me!

**Review by iamhopaul123 — APPROVED** [review]
:ship:

**Pull request merged**
