### PR TITLE
feat(elbv2): add metrics to INetworkLoadBalancer and IApplicationLoadBalancer

### LINKED ISSUE #10850: [elbv2] support metric methods on IApplicationTargetGroup
ApplicationTargetGroup.FromTargetGroupAttributes returns an IApplicationTargetGroupProxy instead of IApplicationTargetGroup, as outlined in the documentation. This class cannot be cast to ApplicationTargetGroup

### Reproduction Steps

```c#
var targetGroup = (ApplicationTargetGroup) ApplicationTargetGroup.FromTargetGroupAttributes(this, "TargetGroup", new TargetGroupAttributes {
    TargetGroupArn = props.TargetGroupArn,
    LoadBalancerArns = props.LoadBalancerArn
});
_metric = targetGroup.MetricHttpCodeTarget(props.StatusCode);
```

### What did you expect to happen?

IApplicationTargetGroup is cast to ApplicationTargetGroup and returns HttpCode metric

### What actually happened?

On cdk synth:

`Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Amazon.CDK.AWS.ElasticLoadBalancingV2.IApplicationTargetGroupProxy' to type 'Amazon.CDK.AWS.ElasticLoadBalancingV2.ApplicationTargetGroup'.`

### Environment

  - **CLI Version      :** 1.67.0
  - **Framework Version:** 1.67.0
  - **Node.js Version:**  v12.19.0
  - **OS               :** OSX 10.14.6
  - **Language (Version):**  .NET Core 3.1.200

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by edisongustavo**
By moving the metrics methods to the `INetworkLoadBalancer` and `IApplicationLoadBalancer` interfaces it allows to create these metrics also for LBs that are imported via the `fromXXX` methods.

To create the metrics for LBs requires only the full name of the LB. This attribute is available at the constructs returned by the `fromXXX` methods.

To solve this problem I did:

- Introduce a new interface for each LB type: `INetworkLoadBalancerMetrics`, `IApplicationLoadBalancerMetrics`
- Create a concrete implementation for the new interfaces (1 for each): `NetworkLoadBalancerMetrics` and `ApplicationLoadBalancerMetrics`
- Make each concrete implementation of each Load Balancer to also provide a `metrics` field. The concrete implementations of the load balancers are: `ImportedApplicationLoadBalancer`, `LookedUpApplicationLoadBalancer`, `ApplicationLoadBalancer` (and the same for the NLB classes).

I chose to create a new interface because code can be reused across the 3 concrete implementations of each Load Balancer. I deprecated the `metricXXX()` methods of each load balancer because I think it is cleaner to access metrics through the new `metrics` attribute/interface.

This task is a step in the direction to fix #10850, but I'd like to get feedback and merge this PR first before proceeding into the `TargetGroup` constructs.

PS: I'm learning Typescript, so please, tell me if I'm doing something wrong here.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by edisongustavo** [comment]
I've just discovered the [flat design guidelines](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md#flat) and I will change this PR to have a flat structure instead.

**Comment by comcalvi** [comment]
@edisongustavo what do you intend to change to be flat?

**Comment by edisongustavo** [comment]
Remove the `Metrics` interface. It will lead to more code repetition but it would follow the design guidelines.

The `ImportedApplicationLoadBalancer` and `LookedUpApplicationLoadBalancer` classes would have all the `metricXXX()` methods implemented by delegating them to the `metrics` field.

Or do you think that would be bad design? I particularly like what I did, but if the design guidelines are what they are, then so be it.

**Comment by comcalvi** [comment]
The design guidelines state 

```
Do not introduce artificial nesting for props.
```

keyword here being `artificial` 🙂. Your changes do not violate this.

**Review by comcalvi — APPROVED** [review]
Nice work on this PR!

**Comment by comcalvi** [comment]
Is there anything we could change around the flat design guidelines to make them clearer? @edisongustavo

**Comment by comcalvi** [comment]
@mergifyio refresh

**Review by comcalvi — APPROVED** [review]

**Comment by edisongustavo** [comment]
> Is there anything we could change around the flat design guidelines to make them clearer? @comcalvi 

I think they are well written, I just didn't pay enough attention to it :sweat_smile:

**Pull request merged**
