### PR TITLE
fix(s3): grantRead does not allow s3:HeadObject

### LINKED ISSUE #27389: s3: bucket.grantRead does not allow s3:HeadObject
### Describe the bug

Currently `bucket.grantRead` does not allow s3:HeadObject action. Because of this, the code like below does not work if you set the IAM policy by `grantRead` method, which is a surprising behavior.

```py
s3 = boto3.client("s3")
# this operation requires s3:HeadObject permission
s3.download_file(bucket, key, filepath)

# you get the following error:
# [ERROR] ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

### Expected Behavior

`bucket.grantRead` allows s3:HeadObject action.

### Current Behavior

`bucket.grantRead` only allows `s3:GetBucket* , s3:GetObject*, s3:List*` actions.

### Reproduction Steps

```ts
    const bucket = new Bucket(this, 'Bucket', {
    });
    const role = new Role(this, 'Role', {
      assumedBy: new ServicePrincipal('sns.amazonaws.com'),
    });
    bucket.grantRead(role);
    // See the synthesized IAM policy.
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.99.1

### Framework Version

2.99.1

### Node.js Version

v18.13.0

### OS

macOS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by lpizzinidev**
Fixes the policy enforced by `grantRead` to allow operations that require to read an object's metadata, for example:
```
s3 = boto3.client("s3")
# this operation requires s3:HeadObject permission
s3.download_file(bucket, key, filepath)
```

Closes #27389.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by tmokmss — APPROVED** [review]
Thank you!

**Review by vinayak-kukreja — APPROVED** [review]
Thank you for your contribution. And, thank you @tmokmss for reviewing the PR. :)

**Review by vinayak-kukreja — APPROVED** [review]

**Comment by sixcorners** [comment]
Is HeadObject a real action? I think the iam console seems to see s3:HeadObject as an unrecognized action.. Unless I messed something up.

**Comment by lpizzinidev** [comment]
@sixcorners 
It seems you're right.
Screenshot 2023-10-12 at 08 15 09
@tmokmss Thoughts?

**Comment by lpizzinidev** [comment]
@tmokmss Agree.
@vinayak-kukreja This PR should be reverted as it is adding an unrecognized action to the policy.
@sixcorners Thanks for the feedback! 💪

**Comment by zxkane** [comment]
The recoginized `s3:HeadObject` will break the [cfn-lint](https://github.com/aws-cloudformation/cfn-lint) scan.

**Pull request merged**
