### PR TITLE
feat(ecs): add support for enabling container insights

### PR DESCRIPTION
**Pull request by michaelbrewer**
Fixes issue #5296

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hencrice** [comment]
LGTM

**Comment by hencrice** [comment]
@michaelbrewer Could you add unit tests?

**Comment by michaelbrewer** [comment]
Added some tests @pkandasamy91  / @hencrice .
1. For default behavior
2. For when container insights are enabled.

**Comment by PettitWesley** [comment]
@michaelbrewer I think this needs to be rebased with master.

**Comment by michaelbrewer** [comment]
> @michaelbrewer I think this needs to be rebased with master.

is it fine now?

**Comment by ranman** [comment]
Hoping to see this one enabled soon!

**Comment by michaelbrewer** [comment]
@SoManyHs  @pkandasamy91  - what are the blockers on this?

**Pull request merged**
