### PR TITLE
docs: add references to new security dev guide

### PR DESCRIPTION
**Pull request by corymhall**
This adds some references to the new [Security and Safety Dev Guide](https://github.com/aws/aws-cdk/wiki/Security-And-Safety-Dev-Guide)

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by kaizencc — APPROVED** [review]

**Comment by mrgrain** [comment]
@mergifyio unqueue

**Comment by mrgrain** [comment]
@mergifyio update

**Comment by mrgrain** [comment]
FYI I had to unqueue this PR as it was blocking the pipeline due to a build not reporting back.

**Comment by mrgrain** [comment]
@mergifyio requeue

**Comment by mrgrain** [comment]
@mergifyio update

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio requeue

**Comment by TheRealAmazonKendra** [comment]
@Merfifyio update

**Pull request merged**
