### PR TITLE
feat(eks): removalPolicy to HelmChart

### PR DESCRIPTION
**Pull request by foriequal0**
I wanted to refactor HelmChart in the CFn stack while I keep the release in the cluster, but it was so hard to do it with `Aspects.of(...)`. So I've drilled a hole to set `removalPolicy` from the HelmChart.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by iliapolo** [comment]
@foriequal0 I'm not sure I fully understand the use case. Can you elaborate please?

**Comment by foriequal0** [comment]
I have HelmChart resources with a specific `release` parameter:
```ts
new HelmChart(this, "SomeResourceName", {
  ...
  repository: "some-repo",
  chart: "some-chart",
  release: "some-release",
});
```
When I rename or move the Cfn resources, as you know, Cfn creates new resources and clean old resources. Generally, physical names are generated so this will not cause problems.
However, in this case, as I've specified release name, so the some-sort-of physical name is not generated. So this is happens:
On the creation of the new HelmChart resource: `helm upgrade --install --repo some-repo some-release some-chart` is executed (if I undersood this code correctly: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py#L49)
On the cleanup of the old HelmChart: `helm uninstall some-release` is executed.
As a result: some-release is gone!
I could've let release names are generated, but I didn't. I want the chart alive in the cluster, but also I want to rename the HelmChart resource.
If it were some other resources, I could've attach deletionPolicy with `Aspect.of(...)`, and proceed [import process](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import.html).

Sorry that I have to admit that I've PRd without much thinking. I realized that it is an abuse of implementation detail (`helm update --install` can overwrite existing release, so the new HelmChart overtakes the ownership). Also I've always set `deletionPolicy` with `Aspect.of(stack)` at stack level. So I felt it was so hard to do it since they are basically `CustomResource` and there is no way to get the type of `CustomResource` in the stack level visitor. But might I can `Aspect.of(helmChart)` to every helmCharts. It would be similar to adding a `removalPolicy` to every chart options.
Thank you for asking why I've PRd it.

**Comment by iliapolo** [comment]
@foriequal0 Are you still looking to get this merged? I don't mind it but it does require some lint fixes as well as a unit test.

**Comment by foriequal0** [comment]
Oh thank you for notify me. I don't have a time to fix this for a while :cry: . You can close this if you want.

**Pull request closed without merging**
