### PR TITLE
feat(eks): using kubectl role for kubectl handler lambda

### PR DESCRIPTION
**Pull request by aka-toxa**
This resolves [issue#12107](https://github.com/aws/aws-cdk/issues/12107) 
we remove intermediate IAMRole for kubectl-provider and directly use kubectl role

@iliapolo I have no idea how to properly make a unittests there can you help please?

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by iliapolo** [comment]
@aka-toxa 

> I have no idea how to properly make a unittests there can you help please?

What specifically? We don't have unittests for the lambda handler, the integ tests should cover that. And as far the provider is concerned, I would just a test that validates the role of the handler is the same as `cluster.kubectlRole`. 

Or did you mean something else?

**Comment by aka-toxa** [comment]
ah yeah I didn't seen that existing integ tests are failed. thought that there is no tests for provider at all.

**Comment by iliapolo** [comment]
@aka-toxa Can this be closed in favor of https://github.com/aws/aws-cdk/pull/14689 ?

**Comment by aka-toxa** [comment]
@iliapolo yes 
are you happy with #14689 approach? I can carry on with tests there

**Pull request closed without merging**
