### PR TITLE
feat(appsync): implement resolvable fields for code-first schema

### PR DESCRIPTION
**Pull request by BryanPan342**
Implemented interfaces and resolvable fields for code-first schema.

`Field` extends `GraphqlType` and will allow you to define arguments.

<details>

<summary> Field Example </summary>

```gql
type Node {
  test(argument: string): String
}
```

The CDK code required would be:

```ts
const field = new appsync.Field(appsync.GraphqlType.string(), {
  args: {
    argument: appsync.GraphqlType.string(),
  },
});
const type = new appsynce.ObjectType('Node', {
  definition: { test: field },
});
```

</details>

`ResolvableField` extends `Field` and will allow you to define arguments and its resolvers.
[**Object Types**](#Object-Types) can have fields that resolve and perform operations on
your backend.

<details>

<summary> Resolvable Field Example </summary>

For example, if we want to create the following type:

```gql
type Query {
  get(argument: string): String
}
```

The CDK code required would be:

```ts
const field = new appsync.Field(appsync.GraphqlType.string(), {
  args: {
    argument: appsync.GraphqlType.string(),
  },
  dataSource: api.addNoneDataSource('none'),
  requestMappingTemplate: dummyRequest,
  responseMappingTemplate: dummyResponse,
});
const type = new appsynce.ObjectType('Query', {
  definition: { get: field },
});

</details>

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by andrestone** [comment]
Hey there!

This is looking very much like a reimplementation of [this](https://github.com/graphql-nexus/schema/). 

I'm wondering if it was possible to let the user leverage that lib while we would only make small adjustments to make it a better fit here.

Thoughts?

**Comment by BryanPan342** [comment]
Hi @andrestone!

Yes it does! When I started the design, I drew inspiration from Nexus, thought I have moved away from some of its heuristics.

Some of the problems I couldnt solve from just using Nexus were the following:

1. Nexus uses generics, which would make it incompatible with JSII. In other words, we need support across multiple languages and JSII doesn't like generics.

2. Mapping Templates are something unique to AppSync and we planned on having some nice interactions with it and code-first schema.

3. We wanted the declaration of the schema to follow the structure of Constructs. Just for consistency throughout CDK.

Would love to hit a discussion on solutions to these issues!

**Comment by andrestone** [comment]
>
> 1. Nexus uses generics, which would make it incompatible with JSII. In other words, we need support across multiple languages and JSII doesn't like generics.
> 2. Mapping Templates are something unique to AppSync and we planned on having some nice interactions with it and code-first schema.
> 3. We wanted the declaration of the schema to follow the structure of Constructs. Just for consistency throughout CDK.

Oh, I see. My suggestion, though, was to shift most of it out of the CDK scope and to minimally modify the API so users can plug their "code-first" flow into CDK.

On a side note: have seen [this](https://github.com/punchcard/punchcard/tree/master/packages/punchcard/lib/appsync/lang)? 

If not, also have a look at [this](https://github.com/punchcard/punchcard/blob/master/packages/punchcard/lib/appsync/api/api.ts). Despite of the divergence of the CDK programming model, I think there's some inspiration there (templating DSL and pretty comprehensive AppSync `$util` implementation).

I'm looking forward to have a pure CDK solution for defining code-first schema and also a less restrictive way for defining mapping templates with type support. Are we moving on this direction?

**Comment by MrArnoldPalmer** [comment]
@andrestone hey there. We have recently discussed extracting the graphql type building logic into some thin layer on top of an existing implementation. Letting users bring their own sounds interesting. We would have to investigate more to see what that takes but generally we are moving in that direction.

We have also been looking at punchcard's implementation (which is pretty dang cool btw) for inspiration and guidance. As @BryanPan342 says, supporting all JSII languages is one of our main goals which means no TS unions/generics for now. This is what necessitates the need for us to layer our own API on top of the existing graphql implementation if we bring one in.

We have an [RFC related to mapping templates](https://github.com/aws/aws-cdk-rfcs/pull/177) (looks like you've seen it already but for other's reference). JSII restrictions also limit what we can do in that space.

**Comment by andrestone** [comment]
Thanks, @MrArnoldPalmer. 

It feels like this is the best path, after all. Using any of the existing code-first tools would require us to write a compatibility layer API to bind code-first resolvers to AppSync / CloudFormation types, and there's no specification as for how those resolvers are bound to the `GraphQLSchema` type (which is the standard those tools adhere to). Moreover, it'll would be maybe even the same amount of code to maintain against a pretty unstable external lib.

So, keep it up @BryanPan342! Please hit me up if I can help with testing or anything.

**Comment by BryanPan342** [comment]
@andrestone Thanks for the feedback!

I have a reference app [here](https://github.com/BryanPan342/starwars-code-first) that mimics the Star Wars API!

Feel free to look at it and would love any feedback in terms of the API. I wanted to showcase how to dynamically create a schema and it seems like the typical paginated schema with Connections and Edges is a good way to showcase it's power!

**Comment by BryanPan342** [comment]
@andrestone @asterikx would love your thoughts on the api!

The README can be found [here](https://github.com/aws/aws-cdk/blob/57fcb030e4ee59c000f4bd4b82c0e0e8c6184279/packages/%40aws-cdk/aws-appsync/README.md#code-first-schema).

The `ResolvableField` and `Field` change would essentially allow for users to implement queries and mutations as a base line!

I made an reference app for the Star Wars API [here](https://github.com/bryanpan342/starwars-code-first/) that you can check out to see a big example of dynamic schema generation.

We are planning to implement a `Lazy` feature that would make it so that users wouldn't have to use the `appendToSchema` function at all (planning to have that merged in by next week).

**Comment by BryanPan342** [comment]
> Hello!
> 
> Could we expose `pipelineConfig` in `ResolvableFieldOptions` in order to have minimal support for pipeline resolvers using this API?

Good point! I was going to add this once AppSync `function` creation was created but yeah the support here would be nice. I'll add this into the PR with some tests tmrw!

**Comment by BryanPan342** [comment]
@andrestone added implementation for `pipelineConfig`!

@shivlaks I separated the tests (only for code-first tests) so each one file has one describe :) felt like it would get hairy pretty soon

**Pull request merged**
