### PR TITLE
fix(ecr): AutoDeleteImages custom resource description contains "undefined"

### PR DESCRIPTION
**Pull request by go-to-k**
The repository name is embedded in the `description` of `CustomResourceProvider` for the ECR AutoDeleteImages, but the repository name becomes to `undefined` because the `CustomResourceProvider` is created before the repository name is set.

```ts
  private enableAutoDeleteImages() {
    const firstTime = Stack.of(this).node.tryFindChild(`${AUTO_DELETE_IMAGES_RESOURCE_TYPE}CustomResourceProvider`) === undefined;
    const provider = CustomResourceProvider.getOrCreateProvider(this, AUTO_DELETE_IMAGES_RESOURCE_TYPE, {
      codeDirectory: path.join(__dirname, '..', '..', 'custom-resource-handlers', 'dist', 'aws-ecr', 'auto-delete-images-handler'),
      useCfnResponseWrapper: false,
      runtime: CustomResourceProviderRuntime.NODEJS_18_X,
      description: `Lambda function for auto-deleting images in ${this.repositoryName} repository.`,
    });
```

So I moved the `enableAutoDeleteImages` calls after following codes that set `repositoryName` in the `Repository` constructor.

```ts
this.repositoryName = this.getResourceNameAttribute(resource.ref);
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by tmokmss — COMMENTED** [review]
If we just move this assignment before calling `enableAutoDeleteImages`, will that resolve the problem?

https://github.com/aws/aws-cdk/blob/bc86d050295fc0d4904e4123f120d706689ca952/packages/aws-cdk-lib/aws-ecr/lib/repository.ts#L722

**Comment by go-to-k** [comment]
@tmokmss 

> If we just move this assignment before calling enableAutoDeleteImages, will that resolve the problem?

In that case, `${this.repositoryName}` is just `Token[XX]` instead of `undefined`, which may not make much sense.

I considered that as well, since it is more natural for the source code, but I did not change it out of respect for the intent of the original code.

**Comment by go-to-k** [comment]
@tmokmss

Sorry, I was misunderstood.

The `getResourceNameAttribute` uses `mimicReference`. So we should move the assignment before calling `enableAutoDeleteImages`.

I will change.

**Review by tmokmss — APPROVED** [review]
Thanks, LGTM. Make sure you change PR title and description as well :)

**Comment by go-to-k** [comment]
Thank you, I changed!

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
