### PR TITLE
feat(cognito): Add support for standard & custom attributes

### LINKED ISSUE #1747: Add support for Cognito Schema
Add CDK support so that [Schema](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-schema) information can be configured for UserPools. This allows one to specify additional attributes that are allowed/required for new users.

### PR DESCRIPTION
**Pull request by netroy**
Fixes #1747 & #5866 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nija-at** [comment]
Can this wait a couple of weeks? I'm working on (re-)designing the CDK Cognito APIs and would like to align this with that work. 

It looks like this isn't a blocking issue and users have a way to work around this.

**Comment by netroy** [comment]
Absolutely. 
I'm using the `Cfn*` constructs directly in my current project, so not blocked by this.
If you prefer, I can also close this PR, & revisit after your changes.

**Comment by nija-at** [comment]
Leave it open for now. We'll take a call once I have more data.

**Comment by nija-at** [comment]
My proposal to re-work Cognito's APIs is here - https://github.com/aws/aws-cdk-rfcs/pull/91. The RFC is in the comments period. Feel free to chime in if you have any comments on the proposal.

Closing this issue in favour of this. The implementation of this RFC will address user pool attributes.

**Comment by netroy** [comment]
@nija-at should i send a bug-fix PR with only the second commit?

**Comment by nija-at** [comment]
I went ahead and already did this - https://github.com/aws/aws-cdk/commit/acf3ffce5b7dacd25b6611d07835f30c85d53006. Hope you don't mind.

**Comment by netroy** [comment]
Thanks, you saved me some time. Why would I mind 😅.

**Pull request closed without merging**
