### PR TITLE
feat(cli): added new flag monitored-environment to conditionally change the assume role policies (#19130)

### LINKED ISSUE #19130: (core): enable adding `sts:SetSourceIdentity` to bootstrap stack trust policy for monitored environments
### Description

In [monitored AWS accounts](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_control-access_monitor.html) it's required for the user to add `sts:SetSourceIdentity` to the trust policy of the cdk-toolkit iam roles. 

If not done the deployment does not fail, however the log is spammed with:
```
current credentials could not be used to assume 'arn:aws:iam::************:role/cdk-hnb659fds-lookup-role-************-region', but are for the right account. Proceeding anyway.
```

### Use Case

Using CDK in monitored environments

### Proposed Solution

provide a flag or another way how to modify the trust policy

### Other information

I'd be willing to implement this, however I'd need some guidance where to start, since I couldn't find the place where the trust policy is built

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by falkvonohlen**
In an monitored AWS account it might be necessary to allow for sts:SetSourceIdentity in an assume role policy in order to allow the role to be assumed. See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_control-access_monitor.html

Fixes #19130

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
I'm sorry for labeling this issue `p1` -- given that it seems a bootstrap template update is sufficient to address it, I'm not inclined to merge this. We have a bootstrap template customization mechanism explicitly to address all the various ways that organizations want to configure their roles, and that we cannot provide those out of the box.

But for my personal curiosity, and because I haven't heard of this mechanism before, can you answer a couple of questions for me?

* What does a "Monitored AWS Account" mean? That term is not explained on the linked page.
* Who calls `SetSourceIdentity`? I'm pretty sure it's not the CLI.
* This PR puts `sts:SetSourceIdentity` in the `AssumeRolePolicyDocument`, while the linked page puts it in the identity policies. Do both locations work? Are we sure?
* The linked page shows conditions that restrict the possible values of the source identity, while this PR just allows all values. Does that not negate the benefit of the keys, as it allows spoofing the value?
* Since apparently we just want to allow everyone to call `SetSourceIdentity` to set the source identity to whatever they please... is there a downside to globally enabling this? Why the conditional enable in the first place?

**Comment by falkvonohlen** [comment]
Hi to address your questions:

- Monitored AWS Accounts (at least for me) means accounts provisioned in an enterprise context and therefore monitored by a central team
- SetSourceIdentity is required, if the role provided by the enterprise to the devs assumes another role (explained in the link)
- I'm not sure, but the way I implemented it does work for sure
- How do you want to set conditions as we do know nothing about the roles used to assume the cdk
- From my point of view it would be also fine to just allow it by default as also [jaecktec](https://github.com/jaecktec) suggested in the issue

**Comment by mrgrain** [comment]
I'm with @rix0rrr on this. The docs quite clearly state:
> AWS doesn’t control the value of the source identity in either the sts:SourceIdentity or aws:SourceIdentity keys. If you choose to require a source identity, you must choose an attribute that you want your users or IdP to provide. **For security purposes, you must ensure that you can control how those values are provided.**

(Highlight is mine)

Based on the above quote, my understanding is that adding the permissions without controlling the values creates a security risk. It could cause Administrators & users to wrongly ascertain the source identity of the user. 

--- 

@falkvonohlen In a monitored AWS account, would you not expect the monitoring instance to provide you with a suitable bootstrap template or at least guidance on how to adopt one? My assumption is here that you won't be the only one using CDK and the monitoring instance will have an interest in creating a secure environment for everyone.

**Comment by falkvonohlen** [comment]
Thanks for the feedback, I´m just going to download the template adapt it and deploy it with --template bootstrap-template.yaml. I would have just liked to get the command line argument option the same way I have it for kms keys, policies and so on.

**Pull request closed without merging**
