### PR TITLE
feat(cfn-include): the package cloudformation-include is now 'Developer Preview'

### PR DESCRIPTION
**Pull request by skinny85**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by NetaNir — APPROVED** [review]
🥳

**Comment by alexpulver** [comment]
Long awaited :). Thanks!

**Comment by skinny85** [comment]
> Long awaited :). Thanks!

@alexpulver our pleasure. If you have any feedback on the `cloudformation-include` library, please let us know!

**Comment by alexpulver** [comment]
One thing I already noticed, is that adding `cloudformation-include` module to the project dependencies pulls in almost all (or all) other AWS CDK modules, resulting in ~200MB virtual environment size (in Python case). I assume this is by design, since these are required for casting the resources, is that correct? 

P.S.: I understand that AWS CDK moves back to [monolithic packaging](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0006-monolothic-packaging.md) design anyway in CDK v2, which should improve install time for all modules.

**Comment by skinny85** [comment]
You're exactly correct @alexpulver - `cloudformation-include` depends on all CDK modules that define `Cfn*` resources (exactly because it needs access to the underlying `Cfn*` classes), which is most of them, and the CDK is moving to monolithic packaging, which will include the `cloudformation-include` module when that transition happens.

**Comment by alexpulver** [comment]
Thanks :). Another question/feedback - I see that `CfnInclude` class creates a resource tree under the parent construct node. Would it make sense to just rely on the regular CDK escape hatches mechanism for CFN resource lookup and customization, without explicit `CfnInclude.get_resource()` calls?

image

**Comment by skinny85** [comment]
That's more of an implementation detail. For example, things like Conditions, Outputs, Mappings, etc. can actually have the same names as Resources and Parameters in the template. Because of that, they're created under a different scope than `this` (you can even see those parent scopes in your screenshot, indexes 0 through 2 under `children` in `CfnInclude`).

Methods like `get_resource`, `get_condition`, `get_output`, `get_mapping`, etc. hide those details.

**Pull request merged**
