### PR TITLE
feat(ecs): allow HTTPS connections from LB to task

### PR DESCRIPTION
**Pull request by hoegertn**
If you need or want to encrypt traffic between the load balancer and the ECS task you need to set the protocol of the target group to `HTTPS`. This PR adds a new property to specify this.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hoegertn** [comment]
@iamhopaul123 would you mind taking a look at this?

**Review by iamhopaul123 — COMMENTED** [review]
Awesome! LGTM. Thank you for doing this! The only request is could you test this feature manually to make sure it works as expected?

**Comment by hoegertn** [comment]
The Unittest shows that the CFN is created correctly. The setting itself I can confirm as I am running this using overrides for some setups.

**Review by jtwolgamott — APPROVED** [review]

**Comment by jtwolgamott** [comment]
I require this functionality as well, looking forward to seeing this merged.

**Review by bvtujo — APPROVED** [review]

**Pull request merged**
