### PR TITLE
fix(ecs): update driverOpts type definition from array to map

### LINKED ISSUE #3341: ECS: Incorrect volume driverOpts typing
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

The `driverOpts` property for the Docker Volume configuration is defined as an array of string, instead of a map string [according to the CloudFormation reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-dockervolumeconfiguration.html#cfn-ecs-taskdefinition-dockervolumeconfiguration-driveropts).

https://github.com/aws/aws-cdk/blob/032e170860af391108e8e6e42cd68d11bfcafca4/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L487

* **What is the expected behavior (or behavior of feature suggested)?**
 `driverOpts` should be a string map

* **What is the motivation / use case for changing the behavior or adding this feature?**
Fix CloudFormation generated template

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

I tried adding the following volume:

```ts
taskDefinition.addVolume({
    name: EBS_VOLUME_NAME,
    dockerVolumeConfiguration: {
        autoprovision: true,
        scope: Scope.SHARED,
        driver: 'rexray/ebs',
        driverOpts: [
            "volumetype=gp2",
            "size=5"
        ]
    }
});
```

As expected the template is incorrect:
```json
"DriverOpts": {
  "0": "volumetype=gp2",
  "1": "size=5"
},
```

Replacing it with a map fixes the template:

```ts
taskDefinition.addVolume({
    name: EBS_VOLUME_NAME,
    dockerVolumeConfiguration: {
        autoprovision: true,
        scope: Scope.SHARED,
        driver: 'rexray/ebs',
        driverOpts: {
            // @ts-ignore
            volumetype: 'gp2',
            size: '5'
        }
    }
});
```
```json
"DriverOpts": {
  "volumetype": "gp2",
  "size": "5"
},
```

This should be a pretty straightforward fix, replacing the `driverOpts` definition line with:
```ts
readonly driverOpts?: {[key: string]: string};
```

### PR DESCRIPTION
**Pull request by nmussy**
BREAKING CHANGE `@aws-cdk/aws-ecs.DockerVolumeConfiguration.driverOpts`:  The type was incorrectly defined as `string[]`, now fixed to `{[key: string]: string}`.

Fixes #3341

----

Please read the [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) and follow the pull-request checklist.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nmussy** [comment]
I don't understand [why the build fails](https://travis-ci.org/aws/aws-cdk/builds/561026600#L6600-L6605), could someone help me out? Thanks in advance.

**Comment by eladb** [comment]
I suspect this is a breaking change although seems like the original type was actually a bug. @SoManyHs what do you think?

**Comment by pkandasamy91** [comment]
> I suspect this is a breaking change although seems like the original type was actually a bug. @SoManyHs what do you think?

@eladb Yes to both, the original type was incorrect, and it should have been a map not an array.  @nmussy Thanks for taking the time to fix the issue!

**Comment by nmussy** [comment]
Thanks for the review! I still don't know why the build fails though?

**Comment by pkandasamy91** [comment]
I believe it's because there are changes that break the current behaviour (which is expected). @eladb how do you want to proceed?

**Comment by eladb** [comment]
Since this is an experimental module, you can add an exception. See https://github.com/aws/aws-cdk/commit/aecaa5d6618cf3f4907f20cb372d93eec9ebb640 

Make sure to ibdicate this in the commit message per convention.

**Comment by nmussy** [comment]
Should be good. @eladb Should we tag v2 issue, or at least add a `review allowed-breaking-changes.txt` step?

**Comment by pkandasamy91** [comment]
> Since this is an experimental module, you can add an exception. See [aecaa5d](https://github.com/aws/aws-cdk/commit/aecaa5d6618cf3f4907f20cb372d93eec9ebb640)
> 
> Make sure to ibdicate this in the commit message per convention.

@eladb not sure if you're thinking about aws-ecs-patterns but these changes are for the aws-ecs module which should be stable not experimental.

**Comment by nmussy** [comment]
I ran `scripts/check-api-compatibility.sh` locally and didn't get any errors. I guess I didn't build it properly. Do I have to add every method listed in the error to the `breaking-changes.txt`?

https://github.com/aws/aws-cdk/blob/3c83197307a38650181dad687e42716c08d3bcd2/allowed-breaking-changes.txt#L1

**Pull request merged**
