### PR TITLE
chore(rds): add AuroraPostgresEngineVersion 12.4

### PR DESCRIPTION
**Pull request by TLadd**
A new version of Aurora Postgres was recently released https://aws.amazon.com/about-aws/whats-new/2021/01/amazon-aurora-supports-postgresql-12/

Screen Shot 2021-02-05 at 9 15 58 AM

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by skinny85 — DISMISSED** [review]
Thanks for the fix @TLadd !

**Comment by TLadd** [comment]
@skinny85 Ran into issues with the PR Linter so I needed to manually modify the commit.

**Review by skinny85 — DISMISSED** [review]
> @skinny85 Ran into issues with the PR Linter so I needed to manually modify the commit.

No worries, our build was having some problems yesterday, but it should all be working now!

**Comment by skinny85** [comment]
I guess I was too optimistic... it seems like our build is still dead 😕

**Review by skinny85 — APPROVED** [review]

**Pull request merged**
