### PR TITLE
feat(route53): fromPublicHostedZoneAttributes method with zoneName

### LINKED ISSUE #18700: (route53): PublicHostedZone fromPublicHostedZoneAttributes function with zoneName support
### Description

Support a method called `fromPublicHostedZoneAttributes()` on `PublicHostedZone` where you can pass in the zoneName as an attribute

### Use Case

[VpcEndpointServiceDomainName](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-route53.VpcEndpointServiceDomainName.html) accepts an `IPublicHostedZone`, however this will result in an error if you import with the current import method supported by PublicHostedZone.

### Proposed Solution

This method would be similar to [`HostedZone.fromHostedZoneAttributes()`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-route53.HostedZone.html#static-fromwbrhostedwbrzonewbridscope-id-hostedzoneid)

### Other information

_No response_

### Acknowledge

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by peterwoodworth**
fixes #18700

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `cdk-integ` to deploy the infrastructure and generate the snapshot (i.e. `cdk-integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by comcalvi — APPROVED** [review]
Conditional approval on adding the README changes.

**Comment by peterwoodworth** [comment]
Wasn't expecting an approval so fast haha, was gonna add that soon!

I also want to add testing for this, but I'm not sure what the best way to test this is - the other import methods aren't tested. If they were, we'd need to either test it in `route53` and add `elasticloadbalancingV2` as a dependency or vice versa. This is because the only construct which uses an `IPublicHostedZone`  that I can find that uses zoneName prop is `VpcEndpointServiceDomainName` which requires you to create a NLB

Will that as simple as just adding the dependency to the package.json file in the respective package? I tried that at first but ran into some weird errors about not being able to export Cfn properties

**Comment by peterwoodworth** [comment]
@comcalvi in case this doesn't end up in your queue otherwise 😛

**Comment by comcalvi** [comment]
Yep, you should be able to add `@aws-cdk/aws-elasticloadbalancingv2` as a dependency of route53 by adding it to the `dependencies` section of the `package.json` and running `yarn install --frozen-lockfile`. It would be awesome if you added testing for these methods.

**Comment by peterwoodworth** [comment]
Added testing in `elbv2` package due to what I assume is creating a circular dependency when I add the elbv2 package to route53

**Comment by peterwoodworth** [comment]
Added testing in `elbv2` package due to what I assume is creating a circular dependency when I add the elbv2 package to route53

**Comment by peterwoodworth** [comment]
... don't look at what the title used to be 🤦🏻

**Comment by peterwoodworth** [comment]
@comcalvi can you take a quick look at this at some point to make sure it's all good with the recent additions? I don't want to just remove the label and let this go through without you taking another look.

**Review by comcalvi — DISMISSED** [review]
This looks almost perfect, but can you add one test that verifies the behavior of `fromPublicHostedZoneId()`? I know that method already existed, but we should have had tests for it before.

**Comment by peterwoodworth** [comment]
Added one @comcalvi 👍🏻

**Review by comcalvi — APPROVED** [review]
Looks great!

**Pull request merged**
