### PR TITLE
chore(aws-cdk-lib): minify aws-cdk-lib sources

### PR DESCRIPTION
**Pull request by njlynch**
This PR takes one step toward improving the load times for
`aws-cdk-lib`. Post-build, `esbuild` is used to minify the source and move
source maps to external files. In local testing, this changed the average time
for loading `aws-cdk-lib` from ~1110ms to ~830ms (25% reduction), and the size
of the locally-packed JS-only source from 53MB to 45MB.

Changes went through full v2 pipeline run, passing all tests. Any other suggestions
for additional verification welcome.

related #18036

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by eladb — APPROVED** [review]
Neat!

**Comment by hoegertn** [comment]
During the development of my CDK apps, I often look into the source code to see how constructs are built internally. This will affect the UX of this as the js files will be unreadable. Any idea how to "fix" this?

**Comment by njlynch** [comment]
> During the development of my CDK apps, I often look into the source code to see how constructs are built internally. This will affect the UX of this as the js files will be unreadable. Any idea how to "fix" this?

The source maps -- which include the original .ts source -- are being included and referenced from the minified source. What's your typical workflow for looking at the js files? Are you just manually browsing to them, or using an IDE? Maybe there's a way the source maps can be utilized instead within the same (or similar) workflow.

**Comment by hoegertn** [comment]
> > During the development of my CDK apps, I often look into the source code to see how constructs are built internally. This will affect the UX of this as the js files will be unreadable. Any idea how to "fix" this?
> 
> The source maps -- which include the original .ts source -- are being included and referenced from the minified source. What's your typical workflow for looking at the js files? Are you just manually browsing to them, or using an IDE? Maybe there's a way the source maps can be utilized instead within the same (or similar) workflow.

I am using VSCode and click on the class name which leads to the `d.ts` file, then I click on the `.js` file nearby to see the code

**Comment by njlynch** [comment]
> I am using VSCode and click on the class name which leads to the d.ts file, then I click on the .js file nearby to see the code

Gotcha. At this point, I think we'd prefer the trade-off of minimal distributed footprint and speedier load times, at the cost of this specific workflow. I believe there are some extensions for VS Code which let you load and view source maps, although I haven't tried any of them personally.

**Pull request merged**
