### PR TITLE
feat(EcsDeployAction): define service attributes instead of service itself

### LINKED ISSUE #17911: (EcsDeployAction): define service attributes instead of service itself.
### Description

EcsDeployAction should allow passing of a serviceName, clusterName, region and possibly account or requiring role, instead of requiring the service which is an IBaseService to set the CodePipeline Configuration and region.

This will allow for using EcsDeployAction to have better support in the CodePipeline API where a you typically would define the ECS service/cluster in a stack inside of a stage.

This would also better support having one pipeline which creates the ECS service/cluster and another pipeline which deploys updated code to the stack.

### Use Case

Typical use case is to have a pipeline which defines a stage which has a stack to create the ECS service.  That ECS service needs to be deployed to via EcsDeployAction, to do that you need need to pass in the service.  Passing the service which is defined in the stack in the pipeline stage results in ```dependency cannot cross stage boundaries```. 

The other use case is to have one pipeline which create the ECS service infrastructure and another pipeline which handles the deployments to the ECS deployment via the EcsDeployAction.

### Proposed Solution

Currently EcsDeployAction takes a service as an IBaseService which based on the service determines the ClusterName, ServiceName for the CodePipeline Action Configuration.  The service is also used to determine the region for the CodePipeline Action.

The proposed solution would be to make service optional, if the combination of serviceName, clusterName, region and role is passed in as props.  There would need to be a check to ensure either service or the combination of service attributes is passed in, to ensure service doesn't override the attributes.

Most likely using an property of serviceAttributes which requires serviceName, clusterName and making region as an optional property to be leveraged only when the serviceAttributes are passed in.

### Other information

_No response_

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by tobytipton**
This implements feature request #17911 by providing a service attributes to the Deploy Action.

Also increase the tests to cover the the attribute, as well as provides tests where using service fails and how serviceAttributes can resolve the issue.

closes #17911 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by skinny85 — CHANGES_REQUESTED** [review]
Thanks for the contribution @tobytipton, but this is not a change we will make. You can have the same effect by using the `FargateService.fromFargateServiceAttributes()` and `Ec2Service.fromEc2ServiceAttributes()`, and passing the name and region (using the ARN) there, and using the existing `service` property of `EcsDeployAction`. So, this doesn't add anything to the expressivity of the CDK.

**Comment by tobytipton** [comment]
Both `FargateService.fromFargateServiceAttributes()` and `Ec2Service.fromEc2ServiceAttributes()` require the cluster to be defined, which leads to the same cross stage boundaries issue if you do the import of the cluster in the appropriate region and and account.

If there is a working example of this working I am all for using the process instead, from my testing I couldn't find a better way to solve this.

**Comment by tobytipton** [comment]
So looking further at `FargateService.fromFargateServiceAttributes()` seems to work however, ran into a slight issue when the service is created in a stack inside of a pipeline stage, the serviceArn is a token.   

Levaraging `FargateService.fromFargateServiceAttributes()` to get the service in the region with the clusterName (as a const), and serviceName to get out the serviceArn from `FargateService.fromFargateServiceAttributes()` inside a stack in a stage and then using `FargateService.fromFargateServiceAttributes()` with the serviceArn and clusterName to create the service to pass to EcsDeployAction.  Produces the correct Configuration and Region in the CFN.

```
      const app = new cdk.App();
      const stack = new cdk.Stack(app, 'PipelineStack', {
        env: {
          region: 'us-east-1',
          account: '234567890123',
        },
      });


      const artifact = new codepipeline.Artifact('Artifact');
      const bucket = new s3.Bucket(stack, 'PipelineBucket', {
        versioned: true,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      });
      const source = new cpactions.S3SourceAction({
        actionName: 'Source',
        output: artifact,
        bucket,
        bucketKey: 'key',
      });

      class TestStack extends cdk.Stack {
        public readonly serviceArn: string;
        public readonly clusterName: string;
        // eslint-disable-next-line @aws-cdk/no-core-construct
        constructor(scope: Construct, id: string, props: cdk.StackProps) {
          super(scope, id, props);
          const vpc = new ec2.Vpc(this, 'Vpc');
          this.clusterName = 'cluster-name';
          const service = ecs.FargateService.fromFargateServiceAttributes(this, 'FargateService', {
            serviceName: 'service-name',
            cluster: ecs.Cluster.fromClusterAttributes(this, 'Cluster', {
              vpc,
              securityGroups: [],
              clusterName: this.clusterName,
            }),
          });
          this.serviceArn = service.serviceArn;
        }
      }
      class TestStage extends cdk.Stage {
        public readonly serviceArn: string;
        public readonly clusterName: string;
        // eslint-disable-next-line @aws-cdk/no-core-construct
        constructor(scope: Construct, id: string, props: cdk.StageProps) {
          super(scope, id, props);
          const testStack = new TestStack(this, 'ecsStack', {});
          this.serviceArn = testStack.serviceArn;
          this.clusterName = testStack.clusterName;
        }
      }

      const pipeline = new codepipeline.Pipeline(stack, 'Pipeline', {
        stages: [
          {
            stageName: 'Source',
            actions: [source],
          },
        ],
      });
      const testStage = new TestStage(
        stack,
        'TestStage',
        {
          env: {
            region: 'us-west-2',
            account: '123456789012',
          },
        },
      );
      const testIStage = pipeline.addStage(testStage);
      const service = ecs.FargateService.fromFargateServiceAttributes(stack, 'FargateService', {
        serviceArn: testStage.serviceArn,
        cluster: ecs.Cluster.fromClusterAttributes(stack, 'Cluster', {
          vpc: new ec2.Vpc(stack, 'Vpc'),
          securityGroups: [],
          clusterName: testStage.clusterName,
        }),
      });
      const deployAction = new cpactions.EcsDeployAction({
        actionName: 'ECS',
        service: service,
        imageFile: artifact.atPath('imageFile.json'),
      });
      testIStage.addAction(deployAction);

      app.synth();
```
generates the region, configuration correctly.
```
            Actions: [
              {
                Name: 'ECS',
                ActionTypeId: {
                  Category: 'Deploy',
                  Provider: 'ECS',
                },
                Configuration: {
                  ClusterName: 'cluster-name',
                  ServiceName: 'service-name',
                  FileName: 'imageFile.json',
                },
                Region: 'us-west-2',
              },
```

However if I create the ECS service in the region stack and then "export" out the clusterName and serviceArn, it doesn't set the region correctly, I added the role here because with out it, it was causing `The 'account' property must be a concrete value`

```
      const app = new cdk.App();
      const stack = new cdk.Stack(app, 'PipelineStack', {
        env: {
          region: 'us-east-1',
          account: '234567890123',
        },
      });
      const artifact = new codepipeline.Artifact('Artifact');
      const bucket = new s3.Bucket(stack, 'PipelineBucket', {
        versioned: true,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      });
      const source = new cpactions.S3SourceAction({
        actionName: 'Source',
        output: artifact,
        bucket,
        bucketKey: 'key',
      });
      const pipeline = new codepipeline.Pipeline(stack, 'Pipeline', {
        stages: [
          {
            stageName: 'Source',
            actions: [source],
          },
        ],
      });

      class TestStack extends cdk.Stack {
        public readonly serviceArn: string;
        public readonly clusterName: string;
        public readonly deployRole: iam.IRole;
        // eslint-disable-next-line @aws-cdk/no-core-construct
        constructor(scope: Construct, id: string, props: cdk.StackProps) {
          super(scope, id, props);
          const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition');
          taskDefinition.addContainer('MainContainer', {
            image: ecs.ContainerImage.fromRegistry('amazon/amazon-ecs-sample'),
          });
          const vpc = new ec2.Vpc(this, 'VPC');
          const cluster = new ecs.Cluster(this, 'Cluster', {
            clusterName: cdk.PhysicalName.GENERATE_IF_NEEDED,
            vpc,
          });
          const service = new ecs.FargateService(this, 'FargateService', {
            cluster,
            taskDefinition,
            serviceName: cdk.PhysicalName.GENERATE_IF_NEEDED,
          });
          const importService = ecs.FargateService.fromFargateServiceAttributes(this, 'ImportFargateService', {
            serviceArn: service.serviceArn,
            cluster: cluster,
          });
          this.serviceArn = importService.serviceArn;
          this.clusterName = cluster.clusterName;
          const deployArn = this.formatArn({
            service: 'iam',
            resource: 'role',
            resourceName: 'deployrole',
          });
          this.deployRole = iam.Role.fromRoleArn(
            this,
            'DeployRole',
            deployArn,
          );
        }
      }
      class TestStage extends cdk.Stage {
        public readonly serviceArn: string;
        public readonly clusterName: string;
        public readonly deployRole: iam.IRole;
        // eslint-disable-next-line @aws-cdk/no-core-construct
        constructor(scope: Construct, id: string, props: cdk.StageProps) {
          super(scope, id, props);
          const testStack = new TestStack(this, 'ecsStack', {});
          this.serviceArn = testStack.serviceArn;
          this.clusterName = testStack.clusterName;
          this.deployRole = testStack.deployRole;
        }
      }
      const testStage = new TestStage(
        stack,
        'TestStage',
        {
          env: {
            region: 'us-west-2',
            account: '123456789012',
          },
        },
      );
      const testIStage = pipeline.addStage(testStage);
      const service = ecs.FargateService.fromFargateServiceAttributes(stack, 'FargateService', {
        serviceArn: testStage.serviceArn,
        cluster: ecs.Cluster.fromClusterAttributes(stack, 'Cluster', {
          vpc: new ec2.Vpc(stack, 'Vpc'),
          securityGroups: [],
          clusterName: testStage.clusterName,
        }),
      });
      const deployAction = new cpactions.EcsDeployAction({
        actionName: 'ECS',
        service: service,
        imageFile: artifact.atPath('imageFile.json'),
        role: testStage.deployRole,
      });
      testIStage.addAction(deployAction);

      app.synth();
```
Generates something like this which has `ClusterName`, `ServiceName`, and `RoleArn` so it should target the correct account, service and cluster however, there is no `Region` which means it will not work as expected.
```
         "Actions": [
                  {
                    "ActionTypeId": {
                      "Category": "Deploy",
                      "Owner": "AWS",
                      "Provider": "ECS",
                      "Version": "1"
                    },
                    "Configuration": {
                      "ClusterName": "teststage-ecsstackeecsstackcluster631300db487421429f3b",
                      "ServiceName": {
                        "Fn::Select": [
                          1,
                          {
                            "Fn::Split": [
                              "/",
                              {
                                "Fn::Select": [
                                  5,
                                  {
                                    "Fn::Split": [
                                      ":",
                                      {
                                        "Fn::Join": [
                                          "",
                                          [
                                            "arn:",
                                            {
                                              "Ref": "AWS::Partition"
                                            },
                                            ":ecs:us-west-2:123456789012:service/teststage-ecsstackeecsstackcluster631300db487421429f3b/teststage-ecsstackckfargateservicecb7fe40e2cebe441d9da"
                                          ]
                                        ]
                                      }
                                    ]
                                  }
                                ]
                              }
                            ]
                          }
                        ]
                      },
                      "FileName": "imageFile.json"
                    },
                    "InputArtifacts": [
                      {
                        "Name": "Artifact"
                      }
                    ],
                    "Name": "ECS",
                    "RoleArn": {
                      "Fn::Join": [
                        "",
                        [
                          "arn:",
                          {
                            "Ref": "AWS::Partition"
                          },
                          ":iam:us-west-2:123456789012:role/deployrole"
                        ]
                      ]
                    },
                    "RunOrder": 1
                  }
                ],
                "Name": "TestStage"
              }
```

It appears in the working example where the import is using names to import the resource serviceArn is `"arn:${Token[AWS.Partition.9]}:ecs:us-west-2:123456789012:service/service-name"` where the create of new resource gives a token for the serviceArn on the service, which is why the region doesn't get generated.

To workaround this had to do define the serviceArn on the stack which creates the service like so rather than trying to use the `service.serviceArn` directly.

```
const serviceArn = this.formatArn({
    service: 'ecs',
    resource: 'service',
    resourceName: service.serviceName,
});
```
that generates the serviceArn to `"arn:${Token[AWS.Partition.8]}:ecs:us-west-2:123456789012:service/${Token[TOKEN.1785]}"` so when the `FargateService.fromFargateServiceAttributes` is passed the serviceArn the `Region` can correctly be determined from the serviceArn, as well determine the `ServiceName`.

**Comment by skinny85** [comment]
Thanks for the detailed explanation @tobytipton!

Do you think it's worth it to update our documentation with your findings?

**Comment by tobytipton** [comment]
I think it would be helpful to provide some additional documentation around this.  Part of the reason I provided this detail was to make it easier for later reference for others which might be running into a similar scenario.

I created my self some test with the above examples for testing them out to make sure I had it working correctly.

**Comment by skinny85** [comment]
@tobytipton I see you opened https://github.com/aws/aws-cdk/pull/18042, I assume that's the example you're referencing here? Anyway, thanks for all your work on this!

**Comment by tobytipton** [comment]
Sorry I was referring to the example I did in #17917 which is for just the [aws-codepipelines Pipeline API](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.Pipeline.html) #18042 is the example/test for [modern CDK PIpelines](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CodePipeline.html) If you would like I can do test/example for the aws-codepipelines Pipeline API as well.

**Comment by skinny85** [comment]
If you have the time, it would of course be awesome to get an example for the `@aws-cdk/aws-codepipeline` API too 🙂.

**Comment by tobytipton** [comment]
I added the example/test to #18042 if that is ok, since both are leveraging ECS Deploy Action.

**Comment by skinny85** [comment]
Actually, can you split that out to a separate PR?

Those two modules are owned by different owners, so splitting them up will make them easier to review and then merge.

**Comment by tobytipton** [comment]
Separate PR created #18059

**Comment by skinny85** [comment]
Thank you!

**Pull request closed without merging**
