### PR TITLE
docs(ssm): doc for grantRead in IParameter is missing GetParameters

### PR DESCRIPTION
**Pull request by go-to-k**
The doc for `grantRead` in `IParameter` is missing `GetParameters`.

The `grantRead` actually grants 'ssm:GetParameters'.

```ts
    return iam.Grant.addToPrincipal({
      grantee,
      actions: [
        'ssm:DescribeParameters',
        'ssm:GetParameters',
        'ssm:GetParameter',
        'ssm:GetParameterHistory',
      ],
```

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ssm/lib/parameter.ts#L181-L186

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by lpizzinidev — APPROVED** [review]
Nice catch 👍

**Review by scanlonp — DISMISSED** [review]

**Comment by go-to-k** [comment]
@scanlonp Thanks to approve, but the merge failed... Do you handle this again please?

**Review by scanlonp — DISMISSED** [review]

**Comment by go-to-k** [comment]
@scanlonp 

Oh... It appears that CodeBuild has failed this time. Do you know how to deal with this? Is it possible to have it run again?

```
aws-cdk: FAIL test/commands/migrate.test.ts (37.451 s)
aws-cdk:   笳� Migrate Function Tests 窶ｺ generateCdkApp generates the expected cdk app when called for java
aws-cdk:     thrown: "Exceeded timeout of 30000 ms for a test.
aws-cdk:     Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
aws-cdk:     [0m [90m 218 |[39m[0m
aws-cdk:     [0m [90m 219 |[39m [36mfunction[39m cliTest(name[33m:[39m string[33m,[39m handler[33m:[39m (dir[33m:[39m string) [33m=>[39m [36mvoid[39m [33m|[39m [33mPromise[39m[33m<[39m[33many[39m[33m>[39m)[33m:[39m [36mvoid[39m {[0m
aws-cdk:     [0m[31m[1m>[22m[39m[90m 220 |[39m   test(name[33m,[39m () [33m=>[39m withTempDir(handler))[33m;[39m[0m
aws-cdk:     [0m [90m     |[39m   [31m[1m^[22m[39m[0m
aws-cdk:     [0m [90m 221 |[39m }[0m
aws-cdk:     [0m [90m 222 |[39m[0m
aws-cdk:     [0m [90m 223 |[39m [36masync[39m [36mfunction[39m withTempDir(cb[33m:[39m (dir[33m:[39m string) [33m=>[39m [36mvoid[39m [33m|[39m [33mPromise[39m[33m<[39m[33many[39m[33m>[39m) {[0m
aws-cdk:       at cliTest (test/commands/migrate.test.ts:220:3)
aws-cdk:       at test/commands/migrate.test.ts:149:3
aws-cdk:       at Object.<anonymous> (test/commands/migrate.test.ts:11:1)
```

**Comment by scanlonp** [comment]
I would guess it is this change (#27870) that is now causing a java app creation test to fail. Unsure why it would pass the build there but fail here. Will check it out.

**Comment by go-to-k** [comment]
@scanlonp 

Oh! This time the Build succeeded!
Plese check it.

**Review by scanlonp — APPROVED** [review]

**Pull request merged**
