### PR TITLE
feat(lambda): add nodejs18.x runtime

### PR DESCRIPTION
**Pull request by TheRealAmazonKendra**
Node18 runtime for Lambda Functions is available in all commercial regions except DXB, ZAZ and ZRH.

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by madeline-k — APPROVED** [review]

**Comment by alfaproject** [comment]
Is there any more information about this runtime? Can't see it in lambda documentation

**Comment by spg** [comment]
@alfaproject Can't create a Lambda with Node18 from the Console either

**Comment by mrgrain** [comment]
See [this comment for some more details](https://github.com/aws/aws-lambda-base-images/issues/47#issuecomment-1292011841).

I believe the missing info is due to the rollout strategy, putting the official announcement last. (For previous years this was the other way around, also causing confusion). Please provide feedback to the Lambda team directly via the above thread/repo.

**Comment by alexherriott** [comment]
Hi,

Now that NODE_18 is available, Is there a related issue / timeline for when NODE_14 runtimes will be migrated to NODE_18

Thanks

**Pull request merged**
