### PR TITLE
chore(prlint): allow multiple scopes in PR title

### PR DESCRIPTION
**Pull request by jogold**
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
I'm not sure that this is something that we want. PRs should contain one set of changes. If it's doing multiple things, it should be split into multiple PRs.

**Comment by jogold** [comment]
> I'm not sure that this is something that we want. PRs should contain one set of changes. If it's doing multiple things, it should be split into multiple PRs.

How would you name #22395 or #17363?

**Comment by Naumel** [comment]
> Something else regarding the linter: in #22395 I get "Features must contain a change to an integration test file and the resulting snapshot." because I changed only the snapshot. I think this too strict for such a case.

I'll invoke the ye ol' 80-20 rule: for 80% of cases, the rule applies. For anything else, a conversation can be had and labels can be added as an escape hatch. If you notice that the percentages are not in that range, let's have a chat about that.

**Comment by Naumel** [comment]
> > I'm not sure that this is something that we want. PRs should contain one set of changes. If it's doing multiple things, it should be split into multiple PRs.
> 
> How would you name #22395 or #17363?

The [PRs are linked](https://github.com/aws/aws-cdk/releases/tag/v2.45.0) with the changes. Proper descriptions, labels and/or looking at the diff can easily tell the bigger story.

Completeness is not pragmatic when the number of exceptions regarding linting is not trivial. And, for best practices, I will point right back to what Kendra mentioned, changes should be small and incremental.

**Pull request closed without merging**
