### PR TITLE
feat(efs): Filesystem.addAccessPoint()

### PR DESCRIPTION
**Pull request by pahud**
feat(efs): addAccessPoint() support for efs FileSystem

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
Trying to add `addAccessPoint()` for efs.FileSystem now.

My integ test looks like this:

```ts
import * as ec2 from '@aws-cdk/aws-ec2';
import * as cdk from '@aws-cdk/core';
import { FileSystem } from '../lib';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'test-efs-integ');

const vpc = new ec2.Vpc(stack, 'Vpc', { maxAzs: 3, natGateways: 1});

const fileSystem = new FileSystem(stack, 'FileSystem', {
  vpc,
});

fileSystem.addAccessPoint('AccessPoint', {
  createAcl: {
    ownerGid: '1000',
    ownerUid: '1000',
    permissions: '755',
  },
  path: '/custom-path',
  posixUser: {
    gid: '1000',
    uid: '1000',
  },
})
```

But I am getting the error: **Error: There is already a Construct with name 'Resource' in FileSystem [FileSystem]**


> $ ../../../node_modules/.bin/cdk --app 'test/integ.efs.js' diff
> /home/ec2-user/github/aws-cdk/node_modules/constructs/lib/construct.js:414
>             throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
>             ^
> 
> Error: There is already a Construct with name 'Resource' in FileSystem [FileSystem]
>     at Node.addChild (/home/ec2-user/github/aws-cdk/node_modules/constructs/lib/construct.js:414:19)
>     at new Node (/home/ec2-user/github/aws-cdk/node_modules/constructs/lib/construct.js:31:28)
>     at new ConstructNode (/home/ec2-user/github/aws-cdk/packages/@aws-cdk/core/lib/construct-compat.js:148:28)

**Comment by pahud** [comment]
Hi @nija-at and @jogold 

Can you help check it out and advise how to fix this error?

Thanks!

**Comment by jogold** [comment]
@pahud the problem lies here:
https://github.com/aws/aws-cdk/blob/32b54a504357922e55ac98850a8e4acc9a0349f5/packages/%40aws-cdk/aws-efs/lib/access-point.ts#L140

you should be using `this` instead of `sope`
```ts
 const resource = new CfnAccessPoint(this, 'Resource', { 
```
= creating the `CfnAccessPoint` in the scope of the `AccessPoint` and not in the scope of its passed scope, otherwise you get the name collision because your `CfnAccessPoint` with `id` `Resource` gets created in the scope of the file system which already has a `Resource` node.

**Comment by pahud** [comment]
> @pahud the problem lies here:
> 
> https://github.com/aws/aws-cdk/blob/32b54a504357922e55ac98850a8e4acc9a0349f5/packages/%40aws-cdk/aws-efs/lib/access-point.ts#L140
> 
> you should be using `this` instead of `sope`
> 
> ```ts
>  const resource = new CfnAccessPoint(this, 'Resource', { 
> ```
> 
> = creating the `CfnAccessPoint` in the scope of the `AccessPoint` and not in the scope of its passed scope, otherwise you get the name collision because your `CfnAccessPoint` with `id` `Resource` gets created in the scope of the file system which already has a `Resource` node.
> 
> (might be something an `awslint` rule could have picked up)

This is super helpful! Thanks for the insight!

**Comment by pahud** [comment]
Hi @nija-at , all checks passed. Would you please check this out? Thanks.

**Pull request merged**
