### PR TITLE
refactor(pipelines): buildspec version as Number

### PR DESCRIPTION
**Pull request by tobni**
According to the spec this is not a string, and codebuild projects with BatchEnabled
 cannot parse the buildspec when version is incorrectly set to a string.

This package (pipelines) does not expose BatchEnabled at all, so it is currently not a bug.
I found this because I have set BatchEnabled outside of the pipelines constructs to utilize batched builds.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Have you tested and run one of these builds after changing the string to a number? I suspect that the way these templates are processed under the hood does require them to be a string because of stuff we're doing under the hood. I'm not positive about this, but I would need to see that these build jobs still run properly with this change.

**Comment by tobni** [comment]
@TheRealAmazonKendra Thanks for the review!

The integration tests are rendering correct templates, and this number is not further processed, its dumped into json.



We currently deploy doing this

```
        cfn_project.add_override(
            'Properties.Source.BuildSpec',
            Fn.join('"version": 0.2', Fn.split('"version": "0.2"', new_spec)),
        )
```
Meaning changing the cfn to ensure the property is a number.

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra Thanks for the review!
> 
> The integration tests are rendering correct templates, and this number is not further processed, its dumped into json.
> 
> We currently deploy doing this
> 
> ```
>         cfn_project.add_override(
>             'Properties.Source.BuildSpec',
>             Fn.join('"version": 0.2', Fn.split('"version": "0.2"', new_spec)),
>         )
> ```
> 
> Meaning changing the cfn to ensure the property is a number, come deployment time.

I get that the integration tests are running fine but they don't actually execute the build. We should verify that these still execute without any issue.

**Comment by TheRealAmazonKendra** [comment]
After thinking about it for a while, given that this update could potentially break the functionality of customers using this code and that it's not currently a bug because we're not exposing batch builds, I'm not comfortable with this change. It would need to go under a feature flag and I don't think it's worth it to add one for this case. We appreciate the catch here, and if we expose BatchEnabled, it's something we'll have to deal with at that time.

**Pull request closed without merging**
