### PR TITLE
chore(integ): correct --silent flag in yarn workspaces info

### PR DESCRIPTION
**Pull request by umireon**
## Overview

The `--silent` flag in `yarn workspaces info` does not works.
The `--json` flag is suggested in https://github.com/yarnpkg/yarn/issues/7881.

The output of `yarn workspaces --json info` is as follows and requires `JSON.parse()` twice:

```
{"type":"log","data":"{\n  \"aws-cdk-lib\": {\n    \"location\" --- snip --- \"workspaceDependencies\": [],\n    \"mismatchedWorkspaceDependencies\": []\n  }\n}"}
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by umireon** [comment]
It seems to work. (All the integ tests in cli.integtest.ts had failed because `JSON.parse` had thrown SyntaxError without this change)

スクリーンショット 2021-06-18 1 12 01

**Comment by skinny85** [comment]
I don't really feel qualified to comment on this. @rix0rrr would you mind taking a look?

**Comment by rix0rrr** [comment]
The change seems correct but I don't understand why it's advantageous.

**Comment by umireon** [comment]
@rix0rrr It's not advantageous.
The `--silent` flag does not work with the current `yarn workspaces info`.
`yarn workspaces info` prepend and append garbages and these cause the SyntaxError in `JSON.parse`.

```
yarn workspaces v1.22.10
{
  "aws-cdk-lib": {
--- snip ---
    "mismatchedWorkspaceDependencies": []
  }
}
Done in 0.61s.
```

The `--json` flag is required to remove these garbases.

**Comment by umireon** [comment]
@rix0rrr 
スクリーンショット 2021-06-18 18 09 34

**Comment by umireon** [comment]
I noticed that just moving the `--silent` flag in front of `info` works.

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
