### PR TITLE
feat(glue-alpha): add `cfn-glue-table-tableinput-parameters` to Glue table construct

### PR DESCRIPTION
**Pull request by lawofcycles**
Add [cfn-glue-table-tableinput-parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-parameters) to Glue Table construct as optional props

User can specify additional table parameter when creating Glue Table. 
Any key/value can be set depending on each user's requirement like table's additional metadata or statistics. Some parameter can be used when AWS services / 3rd party tools read table like `skip.header.line.count`.

Closes https://github.com/aws/aws-cdk/issues/14159.

---
All Submissions:
- [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)
Adding new Unconventional Dependencies:
- [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)
New Features
- [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
  - [x] Did you use yarn integ to deploy the infrastructure and generate the snapshot (i.e. yarn integ without --dry-run)?
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license

### CODE REVIEW

**Comment by lawofcycles** [comment]
Note: On current glue-alpha,`skip.header.line.count` is set on wrong parameter section, cfn-glue-table-storagedescriptor-parameters on table class.
It should be set to `cfn-glue-table-tableinput-parameters` because other services like Athena expect it. This issue is reported on https://github.com/aws/aws-cdk/issues/27365 and I may fix it on another pull request in the future.

**Comment by lawofcycles** [comment]
It seems integration test failed on CodeBuild. I'll check.

>  Lerna (powered by Nx)   Running targets build, test for 63 projects failed
> 
>    Tasks not run because their dependencies failed or --nx-bail=true:
>    
>    - @aws-cdk/aws-apigatewayv2-authorizers-alpha:test
>    - @aws-cdk/aws-iot-actions-alpha:test
>    - @aws-cdk/aws-iotevents-actions-alpha:test
>    - @aws-cdk/aws-scheduler-targets-alpha:test
>    
>    Failed tasks:
>    
>    - @aws-cdk/aws-glue-alpha:test
> 
> 
> real	18m14.153s
> user	209m8.220s
> sys	13m29.698s

**Comment by lawofcycles** [comment]
I have resolved some issues. I would appreciate it if you could review it.

**Comment by vinayak-kukreja** [comment]
Hey @lawofcycles , apologies for the delay and thank you for opening a contribution with us. I will review this PR soon.

**Comment by vinayak-kukreja** [comment]
Awaiting @TheRealAmazonKendra review on the PR.

**Comment by bcolas** [comment]
Any chance to have it reviewed quickly : this is a issue that avoid us to push S3Table in CI/CD to production : no access to change CloudFormation template in production environment

**Comment by kaizencc** [comment]
FYI: we're in the process of revamping the glue module, which is why I haven't been approving any glue PRs lately. Please bear with us a bit longer, I'm trying to see if we can get the green light to continue to merge quality-of-life PRs in the meantime.

**Comment by natalie-white-aws** [comment]
Per Kendra's request, I reviewed these changes and can confirm that these changes do not conflict with the glue-alpha L2 work in flight. Safe to merge pending all other CDK service team checks without impacting our work.

**Review by sumupitchayan — APPROVED** [review]

**Comment by sumupitchayan** [comment]
@Mergifyio update

**Review by sumupitchayan — APPROVED** [review]

**Pull request merged**
