### PR TITLE
chore(cx-api): remove more `instanceof`s

### LINKED ISSUE #17974: aws-cdk: cx-api installed twice by NPM
### What is the problem?

When requiring `aws-cdk` and `aws-cdk-lib` in a project, then the `cx-api` package gets installed twice:

- once as a dependency of `aws-cdk`
- once inside `aws-cdk-lib`

That causes a problem similar to #14468 because of this bit:

https://github.com/aws/aws-cdk/blob/4e7a2758eec6999aee5432b3e9e6bbe7626a2d6b/packages/aws-cdk/lib/api/cloudformation-deployments.ts#L328-L330

The `instanceof` fails because of the class duplication (again, similar thing happened in #14468, see this comment: https://github.com/aws/aws-cdk/issues/14468#issuecomment-832628741).

I signaled this with CDK v1 here: https://github.com/aws/aws-cdk/issues/14468#issuecomment-844984602 but the same problem happens with CDK v2.

Note: I am requiring both of those package to deploy with the CDK programmatically, not deploying via the CLI. BTW let me know if that is completely not meant to be done that way.

### Reproduction Steps

Package.json:

```
{
  "dependencies": {
    "aws-cdk": "^2.1.0",
    "aws-cdk-lib": "^2.1.0",
    "aws-sdk": "^2.1046.0"
  }
}
```

JS file:

```js
        const app = new App();
        const stack = new Stack(app, 'test-stack', {
            env: {
                region: 'us-east-1',
                name: "dev",
            }
        });
        new Queue(stack, 'Queue');

        const stackArtifact = app.synth().getStackByName('test-stack');

        const sdkProvider = new SdkProvider(new CredentialProviderChain(), 'us-east-1');
        const cloudFormation = new CloudFormationDeployments({ sdkProvider });
        await cloudFormation.deployStack({
            stack: stackArtifact,
        });
```

### What did you expect to happen?

`isAssetManifestArtifact()` should return true. And the deployment should succeed.

### What actually happened?

`isAssetManifestArtifact()` returns false, caused some assets not to be uploaded to S3 (namely the CloudFormation template).

That causes the deployment to fail because the CloudFormation deployment is looking for a template on S3 that doesn't exist (it was never uploaded there).

### CDK CLI Version

Not using the CDK CLI

### Framework Version

_No response_

### Node.js Version

17.0.1

### OS

macOS

### Language

Typescript

### Language Version

4.1.2

### Other information

I have no idea how we could make that `instanceof` more robust.

BUT even if we did, what if there are other `instanceof` tests in the codebase? (#14468 tells us that this isn't an isolated problem)

Maybe we should fix the root problem: how can we make sure cx-api (or any other dependency) is installed once in projects that require `aws-cdk` and `aws-cdk-lib`?

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #17974

Follow-up of #14468 

This follows the implementation of https://github.com/aws/constructs/pull/955 to be more robust.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `cdk-integ` to deploy the infrastructure and generate the snapshot (i.e. `cdk-integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — CHANGES_REQUESTED** [review]
I'd rather you follow [this pattern](https://github.com/aws/constructs/pull/955).

This feels pretty dangerous as renaming the class would break this fix.

**Comment by mnapoli** [comment]
@rix0rrr thank you for the guidance, that makes complete sense!

I've updated the PR!

**Comment by mnapoli** [comment]
> - Result: SUCCEEDED

🎉

**Review by rix0rrr — APPROVED** [review]

**Comment by mnapoli** [comment]
🙏  thank you!

**Pull request merged**
