### PR TITLE
feat(elasticloadbalancingv2): add security group support for nlb

### LINKED ISSUE #26735: (aws-elasticloadbalancingv2): (network-load-balancer-supports-security-groups)
### Describe the feature

https://aws.amazon.com/tw/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/
network load balancer supports security groups.

### Use Case

Supports create NLB with SG via aws cdk L2.

### Proposed Solution

Support securityGroup into NetworkLoadBalancerProps.

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.91.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.4.1

### PR DESCRIPTION
**Pull request by msambol**
Closes #26735.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by msambol** [comment]
I was looking at adding `addSecurityGroup` as well but it's a little weird because security groups get set in `super`. I can spend more time on this if we want it.

**Comment by msambol** [comment]
I was looking at adding `addSecurityGroup` as well but it's a little convoluted because security groups get set in `super`. I can spend more time on this if we want it.

**Review by mikewrighton — DISMISSED** [review]

**Comment by msambol** [comment]
@mikewrighton This good to merge?

**Review by mikewrighton — APPROVED** [review]

**Comment by vinayak-kukreja** [comment]
@Mergifyio update

**Review by mikewrighton — APPROVED** [review]

**Pull request merged**
